### DISCUSSION TITLE
html document with collapsible toc

### DISCUSSION THREAD

**Discussion by MarcoPortmann** [quarto-dev/quarto-cli#10010] [Q&A]
### Description

I would like to create an html document with a collapsible TOC. When the page is loaded, the TOC shall be displayed. But it should be possible to reduce it to the heading or an icon at the top left.

I have something like this 
![image](https://github.com/quarto-dev/quarto-cli/assets/7468121/a3668512-3256-433b-9732-8e1bc9a96589)

or this

![image](https://github.com/quarto-dev/quarto-cli/assets/7468121/ac8c86a8-577a-4525-b6ef-d1a03abca9ea)

in mind. Is something like that possible in Quarto? How would I have to expand the following code?

``````markdown
---
title: "Quarto Document"
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
---


# Title
## Subtitle

# Title 2
## Subtitle 2
``````

I have searched the documentation and forums extensively. I see similar functionality for book or website projects. However, I would like to avoid to turn this into a book or website project.

**Comment by cderv** [comment]
We do collapse navigation on article layout like here https://quarto.org/docs/authoring/article-layout.html

I don't remember if this can be activated otherwise. I think it is only activated like this when no room in the margins available. 

I don't see any config for toc to activate this on any HTML toc: https://quarto.org/docs/reference/formats/html.html#table-of-contents

**Reply by mcanouil** [reply]
> I think it is only activated like this when no room in the margins available.

One could use that as a workaround.

**Comment by MarcoPortmann** [comment]
The best solution I've found so far is to integrate the qmd document into a minimalist website project and tweak the sidebar for mobile devices using custom CSS.


```yaml
project:
  type: website

website:
  favicon: "favicon.ico"
  title: ""
  navbar:
    logo: "departement_logo.svg"
    logo-href: "https://www.something.com/"
  sidebar:
    open-graph:
    site-name: Title

format:
  html:
    theme:
      - custom.scss
    toc: true
```
