### DISCUSSION TITLE
Feature Request: SASS-variables for Callout Blocks in revealJS presentation

### DISCUSSION THREAD

**Discussion by Mavoort** [quarto-dev/quarto-cli#10024] [Q&A] [answered]
### Description

Hello, 
I would like to create a custom theme for my revealjs presentation. 
This is (womewhat) how it's supposed to look (except for the icon):

![2024-06-15-031754_467x179_scrot](https://github.com/quarto-dev/quarto-cli/assets/46296384/219d752e-482e-4275-acb8-19e5c8b02eb5)

To achieve this, one would typically create a `custom.scss` file and set the corresponding [SASS-variables](https://quarto.org/docs/presentations/revealjs/themes.html#sass-variables) to change things like colors, fonts or margins.

However, I am unable to change the color of the callout boxes of my presentatio that way. **It would be nice to have some SASS variables for that**, e.g. `callout-color-tip`, `callout-color-warning` like [we have for HTML pages](https://quarto.org/docs/output-formats/html-themes.html#callouts).

At the moment I try to overwrite the colors with come custom css instead. However, setting the border colors via

``` css
/*-- scss:defaults --*/
$purple: #800080;

/*-- scss:rules --*/
div.callout-warning {
  border-left-color: $purple !important;
}
```
doesn't work either, because the default color in Quarto has also set the `important` attribute.

**Comment by mcanouil** [comment]
It does not work because you need to be more precise in your rule as explained in <https://quarto.org/docs/presentations/revealjs/themes.html#customizing-themes>.

I don't know why the default CSS rule in Quarto adds `!important` to it in Reveal.js (edit: it is "needed" to overwrite Bootstrap in regular HTML) but here you also need to use it to overwrite Quarto.

Note that you can't change the colour of the icon because that's a raster image.

````qmd
---
title: "Quarto Playground"
format:
  revealjs:
    theme: [default, custom.scss]
---

## Quarto Playground

::: {.callout-warning icon="false"}
## {{< iconify octicon:copilot-warning-16 >}} Warning

This is a warning!
:::
````

````scss
/*-- scss:defaults --*/
$purple: #800080;

/*-- scss:rules --*/
.reveal .slide div.callout-warning {
  border-left-color: $purple !important;
}

.reveal .slide div.callout-warning.callout-style-default .callout-title {
  background-color: lighten($purple, 50%);
}
````

<img width="1503" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/43959745-09ff-4f98-9856-eb119893e567">


Also note the following discussion:

- https://github.com/quarto-dev/quarto-cli/discussions/4755
