### DISCUSSION TITLE
Output as multiple html

### DISCUSSION THREAD

**Discussion by aloboa** [quarto-dev/quarto-cli#10067] [Q&A]
### Description

In the case of html otput, eg:

```
---
title: "Test"
format: 
  html:
    code-fold: true
    toc: true
    toc-location: left
    toc-expand: 2
---
```

how may I get independent HTML files for each main section?
