### DISCUSSION TITLE
dark mode broken for my website

### DISCUSSION THREAD

**Discussion by daniellga** [quarto-dev/quarto-cli#10071] [Q&A] [answered]
For some time now dark mode looks broken for my website. Could someone check what is happening?

Link for the githubpages with the generated website:
https://daniellga.github.io/harmonium/

Link for the repo
https://github.com/daniellga/harmonium

The quarto generated website is in the docs folder while the inputs to generate this website is in _docs folder.

quarto_yml
```
project:
  type: website
  output-dir: ../../docs

website:
  title: "Harmonium"
  navbar:
    tools:
      - icon: github
        href: https://github.com/daniellga/harmonium
        text: GitHub
  sidebar:
    style: "docked"
    contents:
      - section: "Classes"
        contents: contents/* 

format:
  html:
    theme:
      dark: litera
      light: litera
    css: styles.css
    toc: true
    grid:
      body-width: 1000px
```

Image of the dark mode generated:

![image](https://github.com/quarto-dev/quarto/assets/43149605/f2907f8b-9106-44bb-9caf-f9c577a718fa)

Thanks in advance!

**Comment by gadenbuie** [comment]
You [currently have the following](https://github.com/daniellga/harmonium/blob/73a09eae531c9d865e64925ac843a4ae558c5e2f/_docs/_quarto.yml#L18-L22) in your `_quarto.yml`:

```yaml
format:
  html:
    theme:
      dark: litera
      light: litera
```

which means that you're using [Litera](https://bootswatch.com/litera/), a **light** Bootswatch theme, in both dark and light mode. So when you switch between light and dark mode on the website, the overall theme doesn't change.

What _does_ change is the [highlight style](https://quarto.org/docs/output-formats/html-code.html#highlighting), because by default Quarto uses syntax highlighting styles that are designed to work with light and dark themes. The default dark syntax highlighting doesn't look great with a light theme like `litera`.
