### DISCUSSION TITLE
Skip to Main Content button

### DISCUSSION THREAD

**Discussion by nathanj3** [quarto-dev/quarto-cli#10096] [Feature Requests]
### Description

I'd love the addition of a toggle option for HTML/book rendering to add a "Skip to main content" button that's hidden but becomes visible when tab navigated. It seems possible to add manually by putting the html code inside
```
book:
  sidebar:
    header: |
      <custom code that links to H1 on that page>
```
and then to add custom css to make it hide/display correctly, but it would be very nice to have it built in. It's an accessibility feature that makes life easier for keyboard users, and I'm working to bring everything up to snuff with the new US ADA Title II requirements.
