### DISCUSSION TITLE
How to include external files (qmd, md) when rendering and deplying via Github actions?

### DISCUSSION THREAD

**Discussion by wiesehahn** [quarto-dev/quarto-cli#10203] [Q&A]
### Description

We have a website which we render and deploy via Github actions to Github pages. 
```yml
# file: .github/workflows/publish.yml
name: Publish Website

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ['main']

jobs:
  quarto:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::rmarkdown
            any::knitr
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Render Website
        run: quarto render
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
Now we would like to add content to a post from an external repository/file. We could of course copy paste the content but to keep just one code base we would like to include the external content.
```qmd
---
title: Some Title

description: |
  Some description

categories:
  - Some category

date: today
---

<!--------------- post content ----------------->

{{< include https://raw.githubusercontent.com/quarto-dev/quarto-cli/main/CONTRIBUTING.md >}}
```

Like this it does not work and we receive
```
ERROR: Include directive failed.
  in file /home/runner/work/username.github.io/username.github.io/posts/post_folder/index.qmd, 
  could not find file /home/runner/work/username.github.io/username.github.io/posts/post_folder/https://raw.githubusercontent.com/quarto-dev/quarto-cli/main/CONTRIBUTING.md.
```

What is the correct way of including and rendering external markdown content?
