### DISCUSSION TITLE
How to exclude a directory during build - quarto website

### DISCUSSION THREAD

**Discussion by dereckmezquita** [quarto-dev/quarto-cli#10264] [Q&A] [answered]
### Description

I just started a brand new project using a quarto website layouts generated by RStudio.

I have my website that is at the root of my directory as it was created by the template. I also want to have some extra folders in my project for research and just old code. These are not necessarily pages that should be built and I want to exclude them.

```bash
(base) work@Derecks-MacBook-Air datascope % quarto preview /Users/work/Coding/datascope-playground/datascope/index.qmd --no-browser --no-watch-inputs
pandoc 
  to: html
  output-file: index.html
  standalone: true
  title-prefix: datascope
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  css:
    - styles.css
  toc: true
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  theme: cosmo
  title: datascope
  
Output created: _site/index.html

Preparing to preview
[ 1/14] deprecated/deprecated-code.Rmd
- The project is out-of-sync -- use `renv::status()` for details.


processing file: deprecated-code.Rmd
1/8                  
2/8 [setup]          
3/8                  
4/8 [unnamed-chunk-1]
Error in `data$fasttrack_abscorrup_idea_by_country_time %>% mutate(country = countrycode(
    country, "iso3c", "country.name")) %>% ggplot(aes(time, abscorrup_idea,
    group = country))`:
! could not find function "%>%"



Quitting from lines 14-27 [unnamed-chunk-1] (deprecated-code.Rmd)
Execution halted
(base) work@Derecks-MacBook-Air datascope % 
```

~~I tried adding an excluded statement to my config file, but that did not work. What is the correct way to do this please?~~

I have searched online and the documentation. I found indications that an exclude statement in the config should be possible but nothing has worked for me. I would want something as simple as this:

```yml
project:
  type: website

website:
  title: "datascope"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

exclude:
  - "deprecated/"
```

What is the correct way to do this please?

**Comment by sarveshguru** [comment]
write "/** " after "deprecated"

````bash 
exclude:
  - "deprecated/**"

**Reply by dereckmezquita** [reply]
Thank you, I just tried that and it still tries to build those files.

```yml
url: https://dereckmezquita.github.io/datascope/

project:
  type: website

website:
  title: "datascope"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

exclude:
  - "deprecated/**"
```

```bash
(base) work@Derecks-MacBook-Air datascope % quarto preview /Users/work/Coding/datascope-playground/datascope/index.qmd --no-browser --no-watch-inputs
pandoc 
  to: html
  output-file: index.html
  standalone: true
  title-prefix: datascope
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  css:
    - styles.css
  toc: true
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  url: 'https://dereckmezquita.github.io/datascope/'
  exclude:
    - deprecated/**
  theme: cosmo
  title: datascope
  
Output created: _site/index.html

Preparing to preview
[ 1/14] deprecated/deprecated-code.Rmd
- The project is out-of-sync -- use `renv::status()` for details.


processing file: deprecated-code.Rmd
1/8                  
2/8 [setup]          
3/8                  
4/8 [unnamed-chunk-1]
Error in `data$fasttrack_abscorrup_idea_by_country_time %>% mutate(country = countrycode(
    country, "iso3c", "country.name")) %>% ggplot(aes(time, abscorrup_idea,
    group = country))`:
! could not find function "%>%"



Quitting from lines 14-27 [unnamed-chunk-1] (deprecated-code.Rmd)
Execution halted
(base) work@Derecks-MacBook-Air datascope % 
```
