### DISCUSSION TITLE
How to remove template name from link to Typst output?

### DISCUSSION THREAD

**Discussion by aaronschiff** [quarto-dev/quarto-cli#10270] [Q&A] [answered]
### Description

This is pretty minor but ... I care about details 😅

I have a project that produces html and pdf output via a custom Typst template. I have used `format-link` in the project's `_quarto.yml` file to change the way the link to the Typst output is displayed in the html table of contents, but it still includes the template's name in brackets. Is there a way to remove the template name?

Here is the relevant part of the project `_quarto.yml`, where my template is called "cheatsheet": 

```
format:
  html:
    toc: true
  cheatsheet-typst:
    toc: false

format-links:
  - html
  - format: cheatsheet-typst
    text: PDF
    icon: file-pdf
```

Here's link in the rendered html: 

<img width="152" alt="Screenshot 2024-07-11 at 17 13 39" src="https://github.com/quarto-dev/quarto-cli/assets/10150126/1b0e74be-a953-4e8e-8509-d617eb8520b8">

I'd like it to just say "PDF".
