### DISCUSSION TITLE
How to fix position of body when using margin?

### DISCUSSION THREAD

**Discussion by Hrrsmjd** [quarto-dev/quarto-cli#10286] [Q&A]
### Description

I am creating a personal blog and would like to use the margin for citations and references. When I include components in the margin, the body shifts left. How can I fix the position of the body so that it doesn't shift when moving between pages with and without margins? I have tried editing the page layout options in the sitewide `_quarto.yml` file and in the `.qmd` file (see below).

![image](https://github.com/user-attachments/assets/d6a1cf1b-7d1b-4e5c-a8fd-63fdb0c2625c)

`_quarto.yml`:
```
project:
  type: website
website:
  title: "temp"
format:
  html:
    grid: 
      margin-width: 350px
```

`test.qmd`:
```
---
title: "test"
format:
  html:
    grid: 
      margin-width: 350px
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam rhoncus nunc non ante dapibus, ac hendrerit magna gravida. Ut viverra porttitor mattis. Sed sed magna sed velit varius rhoncus eu ut erat. Aenean eget justo nisl. Nulla tincidunt vulputate enim, sit amet vestibulum lectus. Aliquam ultricies, lacus ac ultricies aliquet, ex metus posuere lorem, nec imperdiet nunc massa in libero. Aenean facilisis nibh et massa feugiat, vitae gravida erat tincidunt. Fusce odio velit, euismod in dictum in, dignissim sed orci. Nam maximus, urna at mattis sollicitudin, lorem sapien pulvinar neque, ut ultrices mi risus nec urna. Fusce venenatis vulputate mauris sed lobortis. Donec auctor mauris vel nulla tristique posuere. Quisque gravida porta finibus. Mauris aliquet porttitor massa, sed euismod lacus euismod a.
::: column-margin <!-- If I comment this out, it unshifts. -->
test 
:::
```

**Comment by mcanouil** [comment]
Why are you setting the `margin-width` at different levels?
The grid customisation is a global setting, see <https://quarto.org/docs/output-formats/page-layout.html#grid-customization>.

Also, please read carefully the documentation:

> The values of these variables don’t directly specify the display width of the corresponding component, instead they specify a maximum base value. The maximum values are scaled to create minimum values, and together they are used to compute the size and position of each component across different layout types (fixed vs. floating), responsive sizes (large screen vs. mobile size), and page contents (margin vs. no margin content).

I also cannot reproduce your issue, see fully reproducible examples below using 1.6.

Which Quarto version are you using?

1. `quarto create project website`
2. Edit `_quarto.yml`
```yaml
project:
  type: website

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      margin-width: 350px
```
3. Edit `index.qmd`
```markdown
---
title: "Website"
---

{{< lipsum 1 >}}

{{< lipsum 1 >}}

::: {.column-margin}
{{< lipsum 1 >}}
:::
```

<img width="723" alt="image" src="https://github.com/user-attachments/assets/5f0c7599-9007-4fc4-9feb-b12bf15df5a6">

**Reply by Hrrsmjd** [reply]
> I also cannot reproduce your issue, see fully reproducible examples below using 1.6.
> 

> ```yaml
> project:
>   type: website
> 
> website:
>   title: "Website"
>   navbar:
>     left:
>       - href: index.qmd
>         text: Home
>       - about.qmd
> 
> format:
>   html:
>     theme: cosmo
>     css: styles.css
>     toc: true
>     grid: 
>       margin-width: 350px
> ```

You are using a theme that is fixing the margins.

**Reply by mcanouil** [reply]
Sorry, but having or not set the theme does not change anything.
So please do provide sufficient information to reproduce as clearly the screenshot you shared is unrelated to the code you shared.
Help us help you as currently we can't.

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/a00b0c5c-71ca-4c36-9a26-26b504e262cd">

**Reply by Hrrsmjd** [reply]
> Sorry, but having or not set the theme does not change anything. 

You are right it wasn't the theme.

> So please do provide sufficient information to reproduce as clearly the screenshot you shared is unrelated to the code you shared. 

Quarto 1.4.522

1. `quarto create project website`
2. `Edit _quarto.yml`
```
project:
  type: website

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    # toc: true
    grid: 
      margin-width: 350px
```
3. `Edit index.qmd`
```
---
title: "Website"
---

{{< lipsum 1 >}}

{{< lipsum 1 >}}

::: {.column-margin}
{{< lipsum 1 >}}
:::
```
If you comment/uncomment `{.column-margin}`, the main body shifts horizontally.
