### DISCUSSION TITLE
Alternative icons

### DISCUSSION THREAD

**Discussion by roaldarbol** [quarto-dev/quarto-cli#10397] [Q&A] [answered]
According to https://quarto.org/docs/websites/website-about.html#links, icons are automatically used from Bootstrap 5. However, many icons, e.g. ORCiD are not available on Bootstrap 5. Is it possible to use an alternative collection of icons, e.g. Fontawesome? Or specify a link to a symbol in the `icon` field?

**Comment by roaldarbol** [comment, marked as answer]
Never mind - found the Fontawesome extension that takes care of this. :-) Sorry about that!

**Reply by mcanouil** [reply]
There is also the iconify extension which tens of thousands of icons including font awesome.

**Comment by joelnitta** [comment]
For others coming across this, it is not sufficient to merely install the [fontawesome extension](https://github.com/quarto-ext/fontawesome) and then use the name of one of those icons for the `icon` key.

Rather, you need to use the shortcode in quotes for the `text` key.

For example:

```
title: "Finley Malloc"
about:
  id: hero-heading
  template: jolla
  image: profile.jpg
  links:
    - text: "{{< fa brands bluesky >}}"
      href: https://bsky.app/profile/joelnitta.com
```
