### DISCUSSION TITLE
Freeze execution of individual code blocks

### DISCUSSION THREAD

**Discussion by skwde** [quarto-dev/quarto-cli#10429] [Q&A] [answered]
### Description

While creating slides I would like to have code blocks executed until I am 

1. Happy with the code
2. Happy with the output

It seems however that there is no fine-grained control on which ones to freeze and which ones to run.
It appears that the `freeze: true` can only applied globally via `_quarto.yml` or via `_metadata.yml`.

While this is fine at the beginning once there are many executable code blocks it quickly takes a lot of time when rerendering / previewing.

Here is a minimal working example:

Use the `revealjs-slides/_metadata.yml`

```yml

jupyter: python3
execute:
  echo: true
  output: true
  freeze: false
  # cache: true
  keep-ipynb: false
format:
  revealjs:
    # ## use aspectratio 1610
    width: 1280 # default: 970
    height: 800 # default: 700
    auto-stretch: false
    navigation-mode: vertical
    controls: true
    progress: true
    slide-number: h.v
    toc: true
    toc-depth: 1
```

and the `revealjs-slides/slides.qmd`

````qmd
---
title: TEST
---

# ABC

```{python}
# | tags: [parameters]
bound = 1000000
```

starting at `0`

There are of course severals ways to do this.

Using a simple `for` loop

```{python}
# | freeze: true
%%timeit
s = []
for i in range(bound):
    s.append(i*i)
sum(s)
```
````

The `_quarto.yml` just has

```yml
date: last-modified
date-format: long
```

Running this via

```sh
quarto preview revealjs-slides/slides.qmd --no-browser  --port 8000
```

while modifying `revealjs-slides/slides.qmd` shows that the `freeze: true` in the executable code block is just ignored.

Note, also using `{{< include sub.qmd >}}` in `slides.qmd` with  a frontmatter `execute.freeze: true` in `sub.qmd` seems to be ignored.

How do I prevent individual codeblocks from rendering and / or vice versa when setting `freeze: true` globally?

---

My setup:

```sh
# quarto --version
1.5.5
```

on debian bookworm in a devcontainer on MacOS.
