### DISCUSSION TITLE
Author names are missing in the HTML using scholarly-metadata and author-info-blocks

### DISCUSSION THREAD

**Discussion by zhengchencai** [quarto-dev/quarto-cli#10422] [Q&A] [answered]
### Description

Hi there,

I used scholarly-metadata.lua and author-info-blocks.lua to render a HTML, but the author names are missing. And "Authors" and "Affiliations" are empty, how can I fix this? 

I don't need to use Pandoc Lua; any other solution is fine. The default affiliation in Quarto rendered HTML repeats the same institute for all affiliated authors, which is unnecessary and lengthy. It would be better to list the affiliations and assign them using superscript affiliation IDs like the figure below but with a list of authors. Thanks a lot.

```
---
title: "Testing Lua filters with Qmd"
author:
  - Jane Doe:
      institute:
        - federation
      equal_contributor: "yes"
      correspondence: "yes"
      email: jane.doe@example.com
  - John Q. Doe:
      institute: [federation, acme]
      equal_contributor: "yes"
  - Juan Pérez:
      institute: acme
institute:
  - federation: Federation of Planets
  - acme:
      name: Acme Corporation

format: html
filters: 
  - scholarly-metadata.lua
  - author-info-blocks.lua
---
```
![image](https://github.com/user-attachments/assets/b7745c17-54f1-43c8-b572-086a81307c90)

If I add name in the author,

```
---
title: "Testing Lua filters with Qmd"
author:
  - name: Jane Doe
    institute:
      - federation
    equal_contributor: "yes"
    correspondence: "yes"
    email: jane.doe@example.com
  - name: John Q. Doe
    institute: [federation, acme]
    equal_contributor: "yes"
  - name: Juan Pérez
    institute: acme
institute:
  - federation: Federation of Planets
  - acme:
      name: Acme Corporation

format: html
filters: 
  - scholarly-metadata.lua
  - author-info-blocks.lua
---

```
![image](https://github.com/user-attachments/assets/5743a5db-5b59-4b7a-ba3e-003420a26812)
