### DISCUSSION TITLE
Autopopulate Dropdown Menu with Folder Items

### DISCUSSION THREAD

**Discussion by marcocamilo** [quarto-dev/quarto-cli#10457] [Q&A]
### Bug description

I'm trying to set the menu to auto populate with the contents of my portfolio folder, but with no success. I don't know if it's possible to have it auto fill with the contents of a folder, but if so, how would it be possible?

```yaml
website:
  title: "name"
  navbar:
    background: white
    foreground: black
    right:
      - href: index.qmd
        text: Home
      - text: Portfolio
        menu:
          - portfolio/*
```

### Quarto check output

Quarto 1.5.45
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.45
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/local/texlive/2024basic/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.14
      Path: /Users/marcocamilo/.pyenv/versions/3.10.14/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
      knitr: 1.47
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
