### DISCUSSION TITLE
Text alignment in About Pages

### DISCUSSION THREAD

**Discussion by harrysw1729** [quarto-dev/quarto-cli#10458] [Q&A] [answered]
### Description

I am creating a website using Quarto. I noticed that the about pages with template `solana` will centre the texts when the screen is narrow, e.g. mobile phone.

Here is an example to illustrate the question. The project has three files: `_quarto.yml`, `index.qmd`, and `page.qmd`.

For `_quarto.yml`:

```yml
project:
  type: website

website:
  navbar:
    right:
      - text: "About"
        href: index.qmd
      - text: "Page"
        href: page.qmd

```

For `index.qmd`:

```qmd
---
title: "About"
about:
  template: solana
---

## Title

- Item 1
- Item 2

```

Lastly, for `page.qmd`:

```qmd
---
title: "Page"
---

## Title

- Item 1
- Item 2

```

After rendering the website with `quarto render`, the about page centred the text that leaves this large space between bullets and item content:
<img width="475" alt="image" src="https://github.com/user-attachments/assets/6ad689cc-375b-4837-9e30-9e1cb2a0cd92">

In contrast, the usual webpage seems free of this issue:

<img width="508" alt="image" src="https://github.com/user-attachments/assets/e9e97dec-83c1-4755-9943-bca62d236518">

Is there any quick solution to this? I tried to work with the CSS, but I don't know what selectors I should be looking at. Thank you very much for your help! 😃

**Comment by mcanouil** [comment, marked as answer]
To find the selector you need to use your favourite browser inspect/developer mode.
Note that since it's dependent on the screen there will me a `@media` component.

Source code: https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/projects/website/about

edit:

```css
ul {
  list-style-position: inside;
}
```
