### DISCUSSION TITLE
How do I change the part numbers in a PDF?

### DISCUSSION THREAD

**Discussion by dmonder** [quarto-dev/quarto-cli#10470] [Q&A] [answered]
### Description

I have a Quarto document that contains 4 sections in response to a required template. The template includes the following parts:

- Part I: Signatures Attesting to Integrity
- Part II: Institutional Summary Form Prepared for Commission Reviews
- Part III: Fifth-Year Compliance Certification 
- Part IV: Follow Up Report (Not applicable for first submission)
- Part V: Impact Report of the Quality Enhancement Plan

Right now I am doing the following in my _quarto.yml:

```
book:
  chapters:
    - index.qmd
    - part: "Signatures Attesting to Integrity" 
      chapters: 
        - Signatures.qmd
    - part: "Institutional Summary Form Prepared for SACSCOC Reviews"
      chapters: 
        - Summary.qmd
    - part: "Requirements"
      chapters: 
        - ... this has all the requirements
      
    - part: "Focused Report" # I DON'T WANT THIS PART
      chapters: 
        - Focused-Report.qmd
        
    - part: "Impact Report of the Quality Enhancement Plan"
      chapters: 
        - QEP-Impact-Report.qmd

format:
  pdf:
    documentclass: scrreport
```

I would like to construct my document such that it skips Part IV as that is not applicable at this point. Is there some way to do this via the configuration, header options in the part files, or in a Lua script?

Thanks,
David

**Comment by mcanouil** [comment]
Please provide a fully reproducible example or at least a complete one. For instance, you did not provide the format.

**Reply by dmonder** [reply]
Updated to include the format section. I can work on a reproducible example, but I need to extract it from my actual work sample which is much larger and includes many more options for our final product.

**Reply by mcanouil** [reply]
If your target is LaTeX/PDF, then use LaTeX command for instance in `include-in-header`, such as something like `\renewcommand{\thepart}{\Roman{part}}`.

Example:

```yml
format:
  pdf:
    documentclass: scrreprt
    include-in-header:
      - text: |
          \renewcommand{\thepart}{\arabic{part}}
```

See:
- https://quarto.org/docs/books/book-output.html#pdf-styles
- https://quarto.org/docs/reference/formats/pdf.html#includes

**Reply by dmonder** [reply]
I am not wanting to change the number _type_. I want to have it include parts I, II, III, and V, but skip IV. I want to specify the following:

```
book:
  chapters:
    - index.qmd
    - part: "Signatures Attesting to Integrity"   # This is Part I
      chapters: 
        - Signatures.qmd
        - 
    - part: "Institutional Summary Form Prepared for SACSCOC Reviews"  # This is Part II
      chapters: 
        - Summary.qmd
        - 
    - part: "Requirements"  # This is Part III
      chapters: 
        - ... this has all the requirements
      
    - part: "Impact Report of the Quality Enhancement Plan"  # This is Part V
      chapters: 
        - QEP-Impact-Report.qmd

format:
  pdf:
    documentclass: scrreport
```

And get a PDF that numbers them as Part I, II, III, and __V__.
