### DISCUSSION TITLE
Side navigation font color incorrect when title-block-banner in use

### DISCUSSION THREAD

**Discussion by royfrancis** [quarto-dev/quarto-cli#10521] [Q&A]
### Description

![Screenshot 2024-08-15 at 11 09 29](https://github.com/user-attachments/assets/c7deab84-da74-47c2-8ce0-5624ae133a2f)

```
project:
  type: website

format:
  html:
    title-block-banner: true

website:
  title: Website
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reports/report.qmd
        text: Report
  sidebar:
    contents:
      - section: Reports
        contents: "reports/*"
```

quarto  1.5.56
