### DISCUSSION TITLE
Is it possible to group output files by format?

### DISCUSSION THREAD

**Discussion by lucaspar** [quarto-dev/quarto-cli#10599] [Q&A] [answered]
### Description

I have several output files generated and it's getting difficult to navigate. I'm looking for a config/solution to group outputs by format as follows:

```txt
  docs.qmd
  outputs
 ├─  html
 │  ├─  docs.html
 │  └─  img
 │     └─  sample.png
 └─  gfm
    └─  docs.md
```

Right now the `html` and `gfm` dirs do not exist and all different formats are mixed in `outputs/`, which is not ideal. The project is configured as:

```yaml
project:
    type: website
    output-dir: "outputs"
    execute-dir: "file"
```
