### DISCUSSION TITLE
How do I include a .js script across a website without format-resources?

### DISCUSSION THREAD

**Discussion by andrewpbray** [quarto-dev/quarto-cli#10654] [Q&A] [answered]
### Description

Hello! I've been experimenting with the best way to deploy a .js script that modifies the sidebar across part of a website that uses hybrid navigation. After trying (and failing) to pass it via `_quarto.yml`, I've made a custom html format for those pages that have the sidebar. `_extension.yml` looks like this:

```yaml
contributes:
  formats:
    html:
      include-in-header:
        - text: |
            <script src="mysidebar.js"></script>
      format-resources:
        - "mysidebar.js"
```

This works, but the downside is that `format-resources` has copied that .js file across the repo any place that format is being used.

I believe I could do this with a filter that uses `quarto.doc.add_html_dependency()` but this seems like the sort of functionality that wouldn't require a filter.

**Comment by mcanouil** [comment]
Did you try using `file` instead of `text` (with the same
Content)?

**Reply by andrewpbray** [reply]
Here are two branches with different attempts:

### Method 1

```yaml
contributes:
  formats:
    html:
      include-in-header:
        - text: |
            <script src="mysidebar.js"></script>
      format-resources:
        - "mysidebar.js"
```
[https://github.com/stat20/stat20notes/tree/try-format-resources](https://github.com/stat20/stat20notes/tree/try-format-resources)

If you run `template.qmd` you'll see it copies the script into that directory.

### Method 2

```yaml
contributes:
  formats:
    html:
      include-in-header:
        - file: "mysidebar.js"
```
[https://github.com/stat20/stat20notes/tree/try-file](https://github.com/stat20/stat20notes/tree/try-file)

If you run `template.qmd`, you'll see it puts the content of the file at the top of the `<body>`, which is unexpected.

Is this the syntax you had in mind for `file`?
