### DISCUSSION TITLE
How to have a table of content in page which is using EJS Template

### DISCUSSION THREAD

**Discussion by shravanngoswamii** [quarto-dev/quarto-cli#10721] [Q&A]
### Description

Is there anyway I can get the table of content in a page that is generating from this setup?

index.qmd:
````qmd
---
pagetitle: Publications by Year
toc: true
toc-depth: 3
listing:
  id: yearwise-publications
  template: templates/years.ejs
  contents: assets/data/by-year.yaml
---

## Publications by Year

::: {#yearwise-publications}

:::
````

templates/years.ejs:

```ejs
<% for (const item of items) { %>

### <%- item.year %> {#<%- item.year %>}

<% for (const pubdata of item.data) { %>

::: {#<%- pubdata.id %> .entry-block }

<% if (pubdata.title && pubdata.url) { %>
#### [<%- pubdata.title %>](<%- pubdata.url %>)
<% } else { %>
#### <%- pubdata.title %>
<% } %>

<% 
// Extract and format fields
const fields = {
    author: pubdata.author_formatted || '',
    editor: pubdata.editor_formatted || '',
    booktitle: pubdata.booktitle || '',
    journal: pubdata.journal || '',
    institution: pubdata.institution || '',
    school: pubdata.school || '',
    address: pubdata.address || '',
    location: pubdata.location || '',
    publisher: pubdata.publisher || '',
    series: pubdata.series || '',
    doi: pubdata.doi || '',
    isbn: pubdata.isbn || '',
    issn: pubdata.issn || '',
    acmid: pubdata.acmid || '',
    pubmedid: pubdata.pubmedid || '',
    note: pubdata.note || '',
    day: pubdata.day || '',
    month: pubdata.month || '',
    abstract: pubdata.abstract || '',
    annote: pubdata.annote || ''
};

// Construct the entry text
const entry_text_parts = [
    fields.author ? `${fields.author}, ` : '',
    fields.day ? `${fields.day}, ` : '',
    fields.month ? `${fields.month} ` : '',
    `${pubdata.year}. `,
    fields.booktitle ? `(In ${fields.booktitle}). ` : '',
    fields.editor ? `Edited by ${fields.editor}. ` : '',
    fields.journal ? `(${fields.journal}). ` : '',
    fields.institution ? `${fields.institution}, ` : '',
    fields.school ? `${fields.school}, ` : '',
    fields.address ? `${fields.address}. ` : '',
    fields.location ? `${fields.location}. ` : '',
    fields.publisher ? `${fields.publisher}. ` : '',
    fields.series ? `${fields.series}. ` : '',
    fields.doi ? `**DOI**: ${fields.doi}. ` : '',
    fields.isbn ? `**ISBN**: ${fields.isbn}. ` : '',
    fields.issn ? `**ISSN**: ${fields.issn}. ` : '',
    fields.acmid ? `**ACM ID**: ${fields.acmid}. ` : '',
    fields.pubmedid ? `**PubMed ID**: ${fields.pubmedid}. ` : '',
    fields.note ? `**Note**: ${fields.note}. ` : ''
].join('').trim();
%>

<%- entry_text_parts %>

<% if (fields.abstract || pubdata.url) { %>
::: {.tab-set}
<% if (fields.abstract) { %>
[Abstract[▼]{#arrow-abstract-<%- pubdata.id %> .arrow .arrow-down}]{.tab-link onclick="toggleAbstract('abstract-<%- pubdata.id %>')"}
<% } %> <% if (pubdata.url) { %> [URL](<%- pubdata.url %>){.tab-link}
<% } %>
:::

<% if (fields.abstract) { %>
::: {#abstract-<%- pubdata.id %> .abstract-content}
<%= fields.abstract %>
:::
<% } %>
<% } %>

<% if (fields.annote) { %>
**Comment:** <%= fields.annote %>
<% } %>

:::

<% } %>
<% } %>
```

sample yaml data:
```yaml
- year: '2022'
  data:
  - id: AllWenMarEtal22
    type: article
    cat: deep
    title: Sparse MoEs meet Efficient Ensembles
    journal: TMLR
    year: '2022'
    url: .
    abstract: '...'
    annote: <a href="https://github.com/google-research/vmoe">Code</a>
    author_formatted: James Urquhart Allingham, Florian Wenzel, Zelda E Mariet, Basil
      Mustafa, Joan Puigcerver, Neil Houlsby, Ghassen Jerfel, Vincent Fortuin, Balaji
      Lakshminarayanan, Jasper Snoek, Dustin Tran, Carlos Riquelme Ruiz, Rodolphe
      Jenatton
    editor_formatted: ''
```
