### DISCUSSION TITLE
Compiling to docx when there is latex preamble

### DISCUSSION THREAD

**Discussion by affans** [quarto-dev/quarto-cli#10777] [Q&A]
### Description

In my markdown document, I have the following preamble that declares a new operator in latex
```
format:
  docx:
    toc: false
    highlight-style: github
  pdf:
    include-in-header:
      - text: |
          \usepackage{amsmath}
          \DeclareMathOperator*{\argmin}{\arg\!\min}
```
And used in the document as 
```
$$
\theta^* = \argmin_\theta w_{\mathcal{F}} L_{\mathcal{F}}(\theta) + w_d L_{\text{d}}(\theta) 
$$
```
However, compiling to `docx` or `typst` fails since `argmin` does not seem to be a valid command in either. Is there a way to have this convert to docx?
