### DISCUSSION TITLE
shared metadata is not working properly!

### DISCUSSION THREAD

**Discussion by shravanngoswamii** [quarto-dev/quarto-cli#10818] [Q&A] [answered]
### Description

I am using shared metadata using `_metadata.yml` for one directory in a website, and it's causing issues in directories outside that directory.

In `_quarto.yml`, I have grid as this:
```
format:
  html:
    grid:
      sidebar-width: 900px
      body-width: 2400px
      margin-width: 900px
 ```
 
 and in `publications/_metadata.yml`, I have this:
 ```
 grid:
  sidebar-width: 0px
  body-width: 2400px
  margin-width: 900px
```

Now the issue is, when I preview the site locally, main site follows the _quarto.yml and when I open publications page one time then even homepage (which should follow `_quarto.yml` grid) starts following metadata of publications directory! And in a site hosted on GitHub hosted, it directly starts following metadata of publications instead of `_quarto.yml`

I have not opened the issue because I do not know if it's a bug, or I am using it in a wrong way!
