### DISCUSSION TITLE
My pre-render script is suddenly causing an "Argument list too long"  error, causing the quarto render to abort.

### DISCUSSION THREAD

**Discussion by Analect** [quarto-dev/quarto-cli#10823] [Q&A]
### Description

I'm hitting this problem with a private gitlab-hosted repo, containing circa 1500 documents that get rendered with quarto. I'm not able to share this set-up, however the approach I'm taking is similar to what is shown publically [here](https://github.com/Analect/quarto-graph-experiments/blob/main/_quarto.yml#L7-L9), where I'm scraping some document meta-data and pushing this to files in a `data` folder which are then published as `resources` in the rendered docs. I'm experimenting with alternative ways to work with the document meta-data and wanted to leverage the `pre-render` capability within quarto.

```yml
project:
  type: website
  resources:
    - "data/**/*"
    - "package/**/*"
    - "coi-serviceworker.min.js"
  pre-render:
    - scripts/metadata-scrape.py
    - scripts/load_data_kuzu.py
  render:
    - "*.qmd"
    ...
```

The gitlab-runner that is doing the rendering is based on this [docker image](https://gitlab.com/b-data/jupyterlab/r-project/docker-stack/-/blob/main/VERSION_MATRIX.md?ref_type=heads), a debian 12 OS, with quarto 1.5.57 on-board. If I comment-out the `pre-render` scripts, then things run fine. However, when I enable the `scripts/metadata-scrape.py` on the gitlab repo (similar in pattern to this [scripts/metadata-scrape.py](https://github.com/Analect/quarto-graph-experiments/blob/main/scripts/metadata-scrape.py), only longer to handle custom meta-data), I'm getting this `Argument list too long` error. Can you shed any light on why this might be happening when quarto is handling `pre-render` scripts.

![image](https://github.com/user-attachments/assets/cbb8f1f9-19a8-48bd-8c51-b88ec7bbc494)

Per [this](https://unix.stackexchange.com/questions/45583/argument-list-too-long-how-do-i-deal-with-it-without-changing-my-command), I tried to set a longer command-line buffer with `ulimit -s 65536` on the VM running this dockerized gitlab-runner, but also included in the `.gitlab-ci.yml` so that it gets applied within the runner itself (see image above), but none of these have helped.
