### DISCUSSION TITLE
How to set up Giscus comments in my blog?

### DISCUSSION THREAD

**Discussion by guilhermeparreira** [quarto-dev/quarto-cli#10868] [Q&A] [answered]
### Description

Hi There!

I am trying to set up `giscus` comments for [my blog](https://github.com/guilhermeparreira/guilhermeparreira.github.io/tree/main/posts) but the giscus comment section does not show.

What I have done so far:

+ The repository is [public]
+ The giscus app is installed on my github
+ The [Discussions feature](https://github.com/guilhermeparreira/guilhermeparreira.github.io/discussions) is turned on.

I entered into the `giscus` website and I included the settings at the end of my [`_metadata.yml`](https://github.com/guilhermeparreira/guilhermeparreira.github.io/blob/main/posts/_metadata.yml) which is inside of my `posts` folder on my `website`:

```yml
comments:
  giscus:
    repo: "guilhermeparreira/guilhermeparreira.github.io"
    repo-id: "R_kgDOMqTkUA"
    mapping: "pathname"
    category: "Announcements"
    category-id: "DIC_kwDOMqTkUM4CiNf2"
    reactions-enabled: true
    input-position: "bottom"
    lang: "en"
    theme: "light"
    loading: "lazy"
```

quarto version: 1.5.57
ubuntu: 24.04.1 LTS

 ```bash
guilherme@guilherme-G3-3579:~/Documents/guilhermeparreira.github.io$ quarto check
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

guilherme@guilherme-G3-3579:~/Documents/guilhermeparreira.github.io$ 
```
