### DISCUSSION TITLE
Accessing `_quarto.yml` metadata from R

### DISCUSSION THREAD

**Discussion by arnaudgallou** [quarto-dev/quarto-cli#10886] [Q&A] [answered]
### Description

Is it possible to access metadata contained in a `_quarto.yml` file from R? I was hoping that `rmarkdown::metadata` would work but it seems it can only access metadata specified in `.qmd` files.

E.g. considering the following `_quarto.yml`:
```yaml
project:
  type: manuscript

manuscript:
  article: index.qmd

title: test
```

 And `index.qmd`

````qmd
---
bibliography: refs.bib
---

```{r}
rmarkdown::metadata
```
````

Rendering `index.qmd` will only show:

```r
$bibliography
[1] "refs.bib"
```
