### DISCUSSION TITLE
Quarto book: source abstract from external chapters

### DISCUSSION THREAD

**Discussion by ed3o3tst** [quarto-dev/quarto-cli#10915] [Q&A]
### Description

Hi,

Im trying to make all my papers for my PhD thesis in Quarto and as such I am trying to direct look at how to make a thesis from all these individual projects/papers.

Now I can make a book simply by:

```
---
project:
  type: book

book:
  title: "Thesis"
  author: "Myname"
  chapters:
    - paper1.qmd
    - paper2.qmd
    - paper2.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
---
```

Now paper1.qmd, paper2.qmd and paper3.qmd are quarto manuscripts with in the yaml for example the abstract, e.g.:
```
---
title: |
  Title
abstract: |
  This is the abstract text
citation:

format:
  pdf: default
---
```
Now when I render my book now, I do get them included in the book, but the text in the yaml of paper1,2,3 is just plain text. That means for example for paper1 I get this:

# Title

This is the abstract text

## Introduction
Rest of paper

When I run at the made tex-file there is also no abstract environment. How to I get the metadata from paper1,2,3 to my main (i.e., book) document? This because I want to make a chapterpage for each paper that does include the title, chapter number but also only the abstract text from each paper.

Thanks in advance!
