### DISCUSSION TITLE
How to use `date` for `field-types` in nested item for custom listings

### DISCUSSION THREAD

**Discussion by lwjohnst86** [quarto-dev/quarto-cli#10942] [Q&A] [answered]
### Description

I have a date field in a YAML file that is nested under a main heading. I want that date to be formatted via Quarto's `date-format`, so that it can hopefully sort the entries, or at least format them more easily. But I can't seem to use nested fields in the `field-types` of `listings`.

See this [GitHub](https://github.com/lwjohnst86/test-custom-listing) for an example of this.

I have a YAML file that looks a bit like:

```yaml
- section: Test section
  entries:
    - title: Subsection
      start: "2022-12-01"
      end: "2022-12-01"

- section: Test section 231
  entries:
    - title: Subsection 3
      start: "2022-12-01"
      end: "2022-12-02"
```

And I have an EJS template that has something like this:

``` javascript
<% for (const item of items) { %>
## <%= item.section %>

<% for (const entry of item.entries) { %>
<%= entry.title %>
:  <%= entry.start %>
:  <%= entry.end %>
<% } %>
<% } %>
```

And my quarto doc is like this:

````qmd
---
date-format: "medium"
listing:
  - id: sections
    template: sections.ejs
    contents: data.yml
    field-types:
      # entries.start: date doesn't work either
      start: date
      end: date
---

::: {#sections}
:::
````

And the `_quarto.yml` like:

```yaml
project:
  type: website

website:
  title: "test"

format:
  html:
    theme: cosmo
    toc: true
```

It ends up formatting as-is (as `2022-12-01`), not as a date via `medium` foramt. Is this something that isn't available yet, so I have to use some EJS function?
