### DISCUSSION TITLE
After publishing my website online, the sidebar and margin width is not correct

### DISCUSSION THREAD

**Discussion by CDucloux** [quarto-dev/quarto-cli#10989] [Q&A]
## Description of the issue

Whenever I'm publishing my website (whether it is on Netlify or Quarto Pub), I get the following issue on all pages :

- The margin and sidebar width is far too large **(image below)**

[
![problem_quarto](https://github.com/user-attachments/assets/82d3520b-0b33-4e6d-9927-958648d07905)
](url)

**See also** : https://corentin-ducloux.netlify.app/

However, in my `_quarto.yml`, the following is set :

```yml
format:
  html:
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem
```

Also, when rendering on local, the website format is such as set in the grid. 

Am I missing something here ? I use a Github Action to publish my website when I commit on `develop` / `main`

Here is my repository : https://github.com/CDucloux/Quarto_Website

## Notes

*Edit* : Interestingly enough, manually publishing the website via `quarto publish netlify` works well, but using the Github Action is what creates the sidebar and margin width error  

## Additional infos

- Quarto v1.5.57
