### DISCUSSION TITLE
Problems when trying to render references (.bib file) in html format

### DISCUSSION THREAD

**Discussion by argofix** [quarto-dev/quarto-cli#10997] [Q&A] [answered]
### **Bug description**

I'm facing problems trying to render references (.bib file) in html format using Quarto.
The complete document is a book with six chapters and each chapter has its own reference section at the end, so that I have six .bib reference files (references_chapter1.bib, references_chapter2.bib etc.).

When I try to render the document I get an error message indicating some problem in the the reference file of chapter 5:

```
processing file: cap05.qmd
                                                                                                                                                                                            
output file: cap05.knit.md

WARNING: Warning: The computation used to determine source line information from the engine timed out.
Line number information will be unavailable and/or inaccurate.
Error reading bibliography file referencias_cap05.bib:
(line 1074, column 1):
unexpected end of input

```

**Error position:**

![erro](https://github.com/user-attachments/assets/4bf8c313-53c5-4274-93de-fb3d757112b9)

The[ complete content of my reference file is here](https://hypnotic-canopy-692.notion.site/references-11404557515780ecaaa2c3bfa53ad12f).

I checked for formatting and spelling mistakes such as missing code delimiters { , = or even empty spaces, but I couldn't find any. All smalls adjustments I tried (deleting or inserting { , or spaces) did not solve the problem.

When I make small adjustments in the file content, the error message, most of the time, keep indicating a problem always in the last line and in the last character position or the file content, even when the indicated position has no characters inserted (as shown in the image above).

Checking in Stackoverflow I realized that my problem is a bit similar to the one addressed in the following question "[Quarto Render having diff of engine output timed out issue](https://stackoverflow.com/questions/75226354/quarto-render-having-diff-of-engine-output-timed-out-issue?rq=2)", except for the fact that he is running Python while I am running my analyzes in R. 

Despite that, I still haven't been able to see a way to solve my problem.

I coudn´t figure out yet how to elaborate a small self-contained "working" (reproducible) example of my situation.

### **My environment:**

Windows 10 Home Version 22H2

Intel(R) Core(TM) i3-6100T 
CPU @ 3.20GHz   3.20 GHz
16,0 GB RAM

RStudio 2024.04.0+735 "Chocolate Cosmos" Release (a00d0e775dbc93e0d79a1bf474e3e8e8de677383, 2024-04-24) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
RStudio/2024.04.0+735 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36,

Quarto 1.4.551

### **Quarto check output:**

```bash

Quarto 1.4.551
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.551
      Path: C:\Users\Arlindo_Casa\AppData\Local\Programs\Quarto\bin
      CodePage: unknown

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Arlindo_Casa\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.8.2
      Path: C:/Users/Arlindo_Casa/AppData/Local/Programs/Python/Python38-32/python.exe
      Jupyter: 4.6.3
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\Arlindo_Casa\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\Arlindo_Casa\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 14, in <module>
    from yaml import safe_load
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK

```

### **This is the structure of my _quarto.yml file:**

```
project:
  type: book
  output-dir: docs
  

book:
  title: " "
  subtitle: " "
  #author: "Centro Nacional de Pesquisa e Conservação de Aves Silvestres - CEMAVE"
  #date: "7 June 2023"
  language: custom.yml
  search: true
  sharing: [twitter, facebook, linkedin]
  # cover-image: "imagens/capa/capa_nova_1.jpeg"
  # repo-url:
  repo-actions: [edit]
  # site-url:
  sidebar:
    collapse-level: 4
    pinned: false
  chapters:
    - index.qmd
    - expediente.qmd
    - equipe.qmd
    - agradecimentos.qmd
    - lista_siglas.qmd
    - apresentacao.qmd
    - cap01.qmd
    - cap02.qmd
    - cap03.qmd
    - cap04.qmd
    - cap05.qmd
    - cap06.qmd
  
    #- referencias.qmd
    
  appendices:
    - apendice.qmd

#bibliography: referencias.bib
csl: ecology_alterado2.csl

execute: 
  freese: auto

opts_chunk:
    fig.align: center
format:
  html:
    theme:
      - cosmo
      - custom.scss
    callout-appearance: simple
    #template-partials: [toc.html, title-block.html]
    toc: true

```
