### DISCUSSION TITLE
How to put bullet points in Figure captions in the right margin?

### DISCUSSION THREAD

**Discussion by jarbet** [quarto-dev/quarto-cli#11036] [Q&A]
When making a quarto HTML report, I often put my Figure captions in the far right margin.  How can I add a Markdown bulletted list to a figure caption using `#| fig-cap:`?  Here is my current attempt:

````
---
title: "How to put bullet points in figure captions that are in the right margin?"
editor: source
format:
    html:
        embed-resources: true
        anchor-sections: true
        code-tools: true
        code-fold: true
        toc: true
        toc-depth: 3
        toc-location: left
        captions: true
        cap-location: margin
        table-captions: true
        tbl-cap-location: margin
        reference-location: margin
---

## Attempt 1 (looks bad)

* It seems markdown is not supported for adding bullet points directly in `fig-cap`, but this would be a great feature to add.
* You can try manually adding bullet points, but if the lines are long, they wont be aligned with the bullets like in a normal Markdown bulletted list, so it looks kind of bad:

```{r}
#| label: fig-cool-plot2
#| fig-cap: 'Hello world <br> * This is a long note that does not fit on one line.  The problem is when starting a new line, it is no longer aligned with the bullet point like done in Markdown bulletted lists <br> * Note 2<br> * Note 3'
#| fig-number: TRUE
plot(1)
```

## Attempt 2 (looks good but has downsides)

Although this approach looks good, a big downside is you can no longer use the automated figure numbering and referencing that is supported in the above.  Instead, you have to manually keep track of figure numbers.


```{r}
plot(1)
```

::: {.column-margin}
Figure 1: cool figure

* This is a long note that does not fit on one line.  Notice now the text is correctly aligned with the bullet.
* Note 2
* Note 3
:::

````

Here's the output:

![Image](https://github.com/user-attachments/assets/fa26f70c-4276-4a50-8811-af2835e2fc3b)

![Image](https://github.com/user-attachments/assets/4975866c-8b4c-4e48-a469-09523e9594f1)
