### DISCUSSION TITLE
How to disable numbering of title page?

### DISCUSSION THREAD

**Discussion by roaldarbol** [quarto-dev/quarto-cli#11055] [Q&A] [answered]
### Description

I am building a book (a PhD thesis) with Quarto, and only the sections with main content should be numbered. Whilst I can avoid numbering by using `{.unnumbered}` for any header blocks, I haven't been able to find a way to do this for `index.md`, my title page. Does anyone know a way of managed this?

**Comment by cderv** [comment]
Can you share your book repo for example ? 

Or an example of what exactly you tried ? What is inside your `index.md` ? 

Having example allows us to be sure we are considering the right things and not misunderstanding anything. 

Thank you !

**Reply by roaldarbol** [reply]
Absolutely! I found out the underlying reason was that `roles: null` in `author` in `_quarto.yml` throws an error (using anything else in `roles` works`) - and that was the error I ended up having to circumvent.

So if you create a new book project, and instead use this `_quarto.yml` it'll break:
```yml
project:
  type: book

book:
  title: "Awesome title"
  date: "12/20/2024"
  author:
    - name: Some name
      roles: null
  chapters:
    - index.qmd
    - part: Introduction
      chapters:
        - intro.qmd
        - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual
```

UNLESS you add the following YAML header to `index.qmd`:
```yml
---
title: "Awesome title"
date: "12/20/2024"
author:
  - name: Some name
---
```
That somehow escapes the error - so what I had working was a happy coincidence that only surfaced when I tried to remove the YAML content from `index.qmd`.
