### DISCUSSION TITLE
Run sentence wrap without visual mode?

### DISCUSSION THREAD

**Discussion by malcolmbarrett** [quarto-dev/quarto-cli#11060] [Q&A]
### Description

My collaborators and I switch between source and visual mode a lot. I want to keep our documents in a sentence-wrapped form. Right now we have:

```yaml
editor_options:
  markdown:
    wrap: sentence
    canonical: true
```

But it only wraps in visual mode. Is it possible to run the wrapping algorithm on a given file or project all at once without going through them in visual mode one by one?
