### DISCUSSION TITLE
Quarto doesn't jump to a new line when we have multiple authors

### DISCUSSION THREAD

**Discussion by fabriciofx** [quarto-dev/quarto-cli#11120] [Q&A]
Hi! I think i found a bug in Quarto when I'm trying put multiple auhtors. Example:

```
title: "Some title"
authors:
  - name: "Author One"
  - name: "Author Two"
  - name: "Author Three"  
date: "`r format(Sys.Date())`"
output: pdf_document
```

Desired output:

     Some title

    Author One
    Author Two
    Author Three

I'm using Quarto 1.5.57.

**Comment by cscheid** [comment]
Transferring to a Q&A.

**Comment by cscheid** [comment]
It looks like you're using RMarkdown syntax here; Quarto requires `format: pdf` instead of `output: ...`. In the future, please refer to our [docs](https://quarto.org/docs/output-formats/pdf-basics.html) before filing a bug. Thanks!

**Reply by mcanouil** [reply]
Additionally, you need to update the way you set the date.
Quarto does not need R to do that, and the R expression inside YAML is a "lucky side effect" when using `knitr` as engine.
See <https://quarto.org/docs/reference/dates.html>

**Reply by fabriciofx** [reply]
@cscheid @mcanouil Right, my configuration is now:

```
---
title: "Some Title"
authors:
  - name: "Author One"
  - name: "Author Two"
  - name: "Author Three"  
date: last-modified
date-format: long
lang: pt
format:  
  pdf: 
    toc: true
    number-sections: true
    papersize: A4
    fig-cap-location: bottom
    documentclass: report 
    lof: true
    lot: true
    geometry: 
      - top=30mm
      - left=30mm
      - right=20mm
      - heightrounded 
    fontfamily: libertinus
bibliography: references.bib 
csl: normas_abnt.csl
params:
  ano: "2024"
---
```

And still the authors list are in the same line, but I'd like them one per line.
