### DISCUSSION TITLE
Custom listing template and nested listings

### DISCUSSION THREAD

**Discussion by nurfatimaj** [quarto-dev/quarto-cli#11166] [Q&A]
### Description

Hi!

I am working on my academic CV website and would like to include a list of events where a given project has been presented. Inside the project page I wanted to use document listings. Suppose the project page is in `project-A/index.qmd` and I have presentations in `project-A/presentations/event-1/index.qmd` and `project-A/presentations/event-2/index.qmd` and etc. 

So, in `project-A/index.qmd` I can include the following
```yaml
listing:
    id: presentation
    template: custom.ejs
    contents: presentations/
```

This shows me the listing of all the presentations in the format I want (from custom.ejs file) in the project page. 

Now, I also want to have a listing of all research projects I do. So, let's say I have `research.qmd` file at the top level of the website folder. It is also a listing:
```yaml
title: "Research"
listing:
  contents: 
    - '.'
    - '!presentations/'
  type: custom
  template: research_list.ejs
```

The issue is that I don't know how to make my `research_list.ejs` evaluate the listing inside the project pages to loop over all presentations for each paper. 

Simplified version of my `research_list.ejs` file looks like this:
```ejs
```{=html}
<div class="list">
  <% for (const item of items) { %>
    <div class="publication" <%= metadataAttrs(item) %>>
      <h5 class="listing-title"><a href="<%- item.path %>"><%- item.title %></a></h5>

      <% if (item.listing) { %>
        <% if (item.listing.contents != "") { %>
          <ul class="publication-presentations">
            <% for (const presentation of item.listing.contents) { %>
              <li><a href="<%- presentation.path %>"><%- presentation.title %></a> (<%- date.toLocaleString('en-GB', {month: 'long', year: 'numeric' }) %>)</li>
            <% } %>
          </ul>
        <% } %>
      <% } %>
    </div>
  <% } %>
</div>
```

But the loop over `item.listing.contents` object does not do what I want it to do. It literally loops over characters in "presentations/" (from the listing contents in the project page). Is there any way to let `research_list.ejs` know that `item.listing` refers to the listing and that it should evaluate that part to generate an actual array of presentation objects?

Right now I am making this all work by using Metadata Listings. So, the listing on the project page looks like this
```yaml
listing: 
  id: presentations
  type: custom
  template: custom.ejs
  contents: 
    - name: Event 1
      link: presentations/event-1/index.qmd
      date: October 24, 2024
    - name: Event 2
       link: presentations/event-2/index.qmd
       date: December 1, 2024
```
so then I get presentation lists both inside project page and research listing page. But it would be slightly easier if I could just use usual listing tools without having to remember to type them into contents. 

Thank you!
