### DISCUSSION TITLE
"navbar" in single HTML document

### DISCUSSION THREAD

**Discussion by allefeld** [quarto-dev/quarto-cli#11181] [Q&A]
### Description

I would like to activate the website project navbar at the top in a single HTML document (default project, format HTML). In this context it would not be a navigation bar, but describe an institutional setting, e.g. contain a logo and a programme name. The file is to be uploaded to a website which is generally differently managed (Moodle).

I was able to achieve that, but it is very hacky: I do declare a website project in `_quarto.yml`.
```yaml
project:
  type: website
  post-render: ./post-render.sh
embed-resources: true

website:
  title: Programme Name
  navbar:
    logo: institution-logo.svg
    logo-href: "#"
  search: false
```
But then `logo-href: "#"` neutralizes the links enclosing logo and name, `search: false` suppresses the site search function,
`embed-resources: true` makes the HTML file self-contained, and the script `post-render.sh` copies only the needed HTML file out of the `_site` subdirectory and deletes the subdirectory:
```bash
#!/bin/bash

echo "$QUARTO_PROJECT_OUTPUT_FILES" | while IFS= read -r filename; do
    cp -p "$filename" .
done

rm -rf "_site/"
```

Is there a better way to do this?

***
Btw., `_site` contains `site-libs` despite `embed-resources: true` and `search.json` despite `search: false`.
