### DISCUSSION TITLE
Using variables and meta in _quarto.yml

### DISCUSSION THREAD

**Discussion by royfrancis** [quarto-dev/quarto-cli#11236] [Q&A] [answered]
### Description

I understand that variables defined in `_variables.yml` can be used in any qmd file using `{{< var bla >}}`.

I have two questions. One is if a variable defined in `_variables.yml` can be used in `_quarto.yml`?

Second question is if yaml variables defined in `_quarto.yml` can be reused in the same document without using `_variables.yml`? Here is a made up example:

`_quarto.yml`

```
project:
  type: website
  output-dir: "bla"

website:
  page-footer:
    border: false
    left: "The output dir is {{< var project.output-dir >}}"
```

I've tried both and they don't seem to work.

```
quarto --version
1.5.56
```
