### DISCUSSION TITLE
Does the `mainfont` option support lists of fonts?

### DISCUSSION THREAD

**Discussion by jimjam-slam** [quarto-dev/quarto-cli#11268] [Q&A]
### Description

The [HTML reference](https://quarto.org/docs/reference/formats/html.html) describes the `mainfont` option as:

> For HTML output, sets the CSS `font-family` on the HTML element.

You could either read "sets the CSS `font-family` as "set a single font family" or "set the `font-family` option... I had read it as the latter and assumed that it would accept any value that `font-family` can take in CSS.

However, if I set `mainfont` to a comma-separated list of fonts, it appears to duplicate any double-quotes used in any of the names. Creating a website with `quarto create` and then setting `format.html.mainfont` to any of the following fails:

```yaml
# these all produce `--bs-body-font-family: Creepster, "" Cascadia Code "", Inter`
mainfont: Creepster, "Cascadia Code", Inter
mainfont: 'Creepster, "Cascadia Code", Inter'
mainfont: "Creepster, \"Cascadia Code\", Inter"

# this works! `--bs-body-font-family: Creepster, Arial, Inter`
mainfont: Creepster, Arial, Inter

# this produces `--bs-body-font-family: "Cascadia Code"`
# (double quotes aren't consumed... or are added back by quarto?)
mainfont: "Cascadia Code"
```

If it was intended that this option only support one font, that's okay! I wanted to clarify because we've added some font YAML options to Closeread, and we [noticed](https://github.com/qmd-lab/closeread/issues/114) that the same YAML string for our font option and the `mainfont` option lead to different CSS custom property values being emitted.

Options going in:

```yaml
mainfont: 'et-book, Palatino, "Palatino Linotype", "Palatino LT STD", "Book Antiqua", Georgia, serif'
cr-style:
  narrative-font-family: 'et-book, Palatino, "Palatino Linotype", "Palatino LT STD", "Book Antiqua", Georgia, serif'
```

Property values coming out:

```yaml
--cr-narrative-font-family: et-book, Palatino, “Palatino Linotype”, “Palatino LT STD”, “Book Antiqua”, Georgia, serif;
--bs-body-font-family: et-book, Palatino, "" Palatino Linotype "", "" Palatino LT STD "", "" Book Antiqua "", Georgia, serif;
```

Thanks!
