### DISCUSSION TITLE
How do I include other document metadata in the header and footer?

### DISCUSSION THREAD

**Discussion by m31-galaxy** [quarto-dev/quarto-cli#11271] [Q&A] [answered]
### Description

I'm aiming to get information such as document title and author name into the header of the PDF-rendered output - is this doable without manually retyping the same information in two places?

Here's what my `_quarto.yml` file currently looks like:

```yml
project:
  render:
    - report.md

title: My Document Title
date: today
toc: true
highlight-style: atom-one

author:
  - My Name

format:
  pdf:
    papersize: a4
```

In this case, I'm looking to get `My Document Title | My Name` into the header, on the left and right sides respectively.

I am using Quarto 1.6.32 on AlmaLinux 9.4 x86_64.

**Comment by mcanouil** [comment, marked as answer]
Use the meta shortcode or modify the template/partials:

- https://quarto.org/docs/authoring/variables.html
- https://quarto.org/docs/journals/templates.html#latex-partials

Note that without providing a reproducible code which shows how and where you want to reuse metadata, it's impossible to provide a specific answer.

**Reply by m31-galaxy** [reply]
Thank you! For future visitors, here was my solution in my `_quarto.yml` file (ended up switching to Typst):

```yml
title: "{{< var module >}} {{< var project >}} – {{< var title >}}"
date: today
author:
  name: "{{< var matriculation_number >}}"
keywords:
  - "{{< var module >}}"

project:
  render:
    - report.md
format:
  typst: default

include-in-header:
  - text: |
      #set page(header: context {
        if counter(page).get().first() == 1 [
          Tutor: {{< var tutor >}}
          #h(1fr)
          {{< var matriculation_number >}}
        ] else [
          {{< var module >}} {{< var project >}} – {{< var title >}}
          #h(1fr)
          {{< var matriculation_number >}}
        ]
      })
```
