### DISCUSSION TITLE
Setting the directory to get chapters from in Quarto's books

### DISCUSSION THREAD

**Discussion by arnaudgallou** [quarto-dev/quarto-cli#11329] [Q&A] [answered]
### Description

I'm working on a Quarto book that has many chapters that currently live at the root of the project.

``` yaml
book:
  chapters:
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_n.qmd
```

I'd like to move those files to their own directory (say `foo/`) to make the project a bit cleaner and better organized. Instead of prefixing every file name listed under `chapters` with `foo/`, I'm wondering if there's a way to set the directory to get chapters from.

Something like this for example:

``` yaml
book:
  chapters-dir: foo
  chapters:
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_n.qmd
```

I couldn't find any YAML key to do that but I may have missed it. Is this possible? If not, could you consider it as a feature request?
