### DISCUSSION TITLE
Miscellaneous questions about Quarto books

### DISCUSSION THREAD

**Discussion by harrelfe** [quarto-dev/quarto-cli#1132] [Q&A] [answered]
I am having good success in creating a Quarto book at https://hbiostat.org/rflow but need to put the icing on the cake.  I'd appreciate some help on a few items.

I have

```
project:
  type: book
...
book:
 ...
  cover-image: "my.png"
  ...
  
website:
  url: https://hbiostat.org/rflow
  comments:
    hypothesis:
      theme: clean
      openSidebar: true
      enableExperimentalNewNoteButton: true
  google-analytics: "G-P47...."

```

The cover image appears on the first page but is extremely small.  I've also tried `cover.image` under `format: html`.

I can't see that the google analytic has been implemented in the generated html.

The `hypothesis` options don't seem to have any effect.

Also I'm getting very large files created in `.quarto/_freeze` not matter what I put for the `freeze` parameter.

```
execute:
  freeze: false
```

Thanks in advance for any help.
