### DISCUSSION TITLE
How do I override the navbar background color using _brand.yml styling?

### DISCUSSION THREAD

**Discussion by coatless** [quarto-dev/quarto-cli#11355] [Q&A]
### Description

I've been trying to change the navigation bar for a Quarto webpage using `_brand.yml` on Quarto pre-release v1.6.33 to no avail. It seems stuck at `#517699` (blue variant), c.f.

<img width="1519" alt="Screenshot showing a blue navigation top bar" src="https://github.com/user-attachments/assets/5641ecd9-33c2-4603-b431-e435ab4f935d">

Website: https://stanford-brand-yml.github.io/quarto-branded-website/
MWE/Code: https://github.com/stanford-brand-yml/quarto-branded-website

I've tried the suggestion at: https://prerelease.quarto.org/docs/authoring/brand.html#in-scss

The other [use cases of text elements and supported fields (under Typography?)](https://prerelease.quarto.org/docs/authoring/brand.html#typography) omit setting a navbar color.

<img width="874" alt="A screenshot of the full set of text elements and supported fields" src="https://github.com/user-attachments/assets/ef37516f-a12b-4961-bebd-960c11854e09">

Relevant lines in the MWE:

[**_brand.yml**](https://github.com/stanford-brand-yml/quarto-branded-website/blob/82466fc8a3d41e10dc51d174c125e1fe2eb35e99/_brand.yml#L17-L19)
```yml
color:
  palette:
    cardinal: "#8C1515"
```

[**_custom.scss**](https://github.com/stanford-brand-yml/quarto-branded-website/blob/82466fc8a3d41e10dc51d174c125e1fe2eb35e99/_custom.scss)
```
/*-- scss:defaults --*/
$navbar-bg: $brand-cardinal; 
```

[**_quarto.yml**](https://github.com/stanford-brand-yml/quarto-branded-website/blob/82466fc8a3d41e10dc51d174c125e1fe2eb35e99/_quarto.yml#L20-L27)
```
format:
  html:
    toc: true
    theme:
      - custom.scss

# Use the brand file for all documents in the project
brand: _brand.yml
```

> [!NOTE]
>
> Background color for the navbar seems to be set in: 
> 
> https://github.com/quarto-dev/quarto-cli/blob/8e51fc22e41e58f1c4c7bbedff4a7bdbea58a54d/src/resources/formats/html/bootstrap/_bootstrap-variables.scss#L63-L67

**Comment by gadenbuie** [comment]
brand.yml includes [a `defaults` section](https://posit-dev.github.io/brand-yml/brand/defaults.html) where you'll be able to make these kinds of output-specific choices. In fact, I have this exact type of customization in the [brand.yml website](https://posit-dev.github.io/brand-yml/) itself (the black navbar background).

The way I've envisioned making this kind of change is through `defaults.bootstrap`:

```yaml
defaults:
  bootstrap:
    defaults:
      navbar-bg: $brand-cardinal
```

It's not currently implemented in Quarto exactly as above (but will be if #11378 is merged). In the current pre-release of Quarto, you can use this formulation:

```yaml
defaults:
  bootstrap:
    navbar-bg: $brand-cardinal
```

Just be sure to leave yourself a TODO note to revisit if the syntax changes.

I should also note that it looks like some of what you tried should have worked. I do think it'd be useful for someone from the Quarto to take a look at your reprex.

**Reply by coatless** [reply]
Mmm, the code cells are the same? Is this ["The Office" picture difference test](https://knowyourmeme.com/memes/theyre-the-same-picture)? 😉 

I swear I looked closely at the `brand-yml` website, but I didn't find the rule change (the [`brand-yml-theme.scss`](https://github.com/posit-dev/brand-yml/blob/3290f6ba0179177ad613302f420c2a3f47104c1e/docs/brand-yml-theme.scss) is modifying code cells and set the theme explicitly to brand [`_quarto.yml`](https://github.com/posit-dev/brand-yml/blob/3290f6ba0179177ad613302f420c2a3f47104c1e/docs/_quarto.yml#L65)). Though, it's right there at the end of the [`_brand.yml` file](https://github.com/posit-dev/brand-yml/blob/3290f6ba0179177ad613302f420c2a3f47104c1e/docs/_brand.yml#L99-L102).

```yml
defaults:
  bootstrap:
    enable-rounded: false
    navbar-bg: $brand-black
```

Thanks!
