### DISCUSSION TITLE
How do I force a hyphen instead of an en dash in page ranges in citations?

### DISCUSSION THREAD

**Discussion by robertoragno** [quarto-dev/quarto-cli#11363] [Q&A] [answered]
### Description

I am writing a book in Quarto using the 'book' class to generate a PDF output. My editor insists that I use a hyphen (-) instead of the en dash (–) to indicate the page range, both for in-text citations and in the final reference list. Currently, a citation in the format `[@author2024, p.86-87]` is printed as 'Author 2024, pp. 86-87' when I need 'Author 2024, pp. 86-87'.

I have tried looking in my .CSL file (https://www.zotero.org/styles/taylor-and-francis-harvard-x) to see if I can change something to make it work, but I can't seem to get it right because I think Pandoc is forcing the en dash. 

I am using R Studio. In Tools -> Global Options -> R Markdown -> Citations, I have set 'Use BibTex for citation keys'.

Thank you in advance for all the help, I am really losing my mind over this minor issue.

**Comment by mcanouil** [comment]
Without a reproducible example hard to help accurately.

- https://github.com/quarto-dev/quarto-cli/discussions/3828

````qmd
---
title: "Quarto Playground"
format: html
from: markdown-smart
---

1--2
````

**Reply by robertoragno** [reply]
Thank you for the response, I do not have an issue with the rendering of two hyphens - that works as expected. My issue is related to how citations are printed through citeproc (I think?) 

Simplifying a bit my book project I have:

**_quarto.yml**
```
project:
  type: book
  
book:
  chapters:
    - index.qmd
    - references.qmd

bibliography: references.bib
csl: taylor-and-francis-harvard-x.csl
    
format:
  pdf:
    documentclass: book
    keep-tex: false
    hyperrefoptions: draft
    linestretch: 1.18
    mainfont: Times New Roman
    sansfont: Times New Roman
    fontsize: 11pt
    toc: false 
    extra_dependencies: ["booktabs"]
    link-citations: true
    lang: en
    geometry:
      - top=2.3cm
      - left=2.2cm
      - right=2.2cm
      - bottom=2.6cm
      - paperwidth=225mm
      - paperheight=280mm
      - footskip=8mm
    include-in-header:
    - file: include_in_header_TEX/preamble.tex
    - file: include_in_header_TEX/chapter_headers.tex
```
  
 **index.qmd**
`Horden and Purcell [-@hordenCorruptingSeaStudy2000, pp. 287-297] highlighted the... `

**references.bib**
```
@book{hordenCorruptingSeaStudy2000,
  title = {The Corrupting Sea: A Study of {{Mediterranean}} History},
  shorttitle = {The Corrupting Sea},
  author = {Horden, Peregrine and Purcell, Nicholas},
  year = {2000},
  publisher = {{Blackwell}},
  address = {{Oxford}},
  isbn = {978-0-631-13666-8 978-0-631-21890-6},
  lccn = {DE59 .H7 2000},
  keywords = {Civilization,Mediterranean Region,Sources}
}
```

**Output:** 
Horden and Purcell (pp. 287–297) highlighted the... 

**Output in references page*
Horden, P. and Purcell, N., 2000. The corrupting sea: A study of Mediterranean history. Oxford: Blackwell.

This particular case does not have a page range in the bibliography, but i would also need to change that.
