### DISCUSSION TITLE
Where can I find the title-block.html html partial template used?

### DISCUSSION THREAD

**Discussion by rkrug** [quarto-dev/quarto-cli#11434] [Q&A]
### Description

Quarto version: 1.5.75
Positron
macOS Sequoia

My aim is to modify the header in a html document with added metadata, e.g. a disclaimer as specified in the yaml front matter.

Currently I am using the following header

```
---
title: 'A Title'
subtitle: 'A subtitlet'
author:
  - name: AAA BBB
    id: sb
    orcid: 1234-1234-1234-1234
    email: jaaa@bbb.cc
    affiliation: 
      - name: Whatever Institute
        city: Providence
        state: RI
        url: www.brown.edu
    roles: [author, editor]
  - name: CCC DDD
    id: cd
    orcid: 2345-2345-2345-2345
    email: bbb@ccc.dd
    affiliation: 
      - name: Another Great Institute
        city: Providence
        state: RI
        url: www.brown.edu
abstract: > 
  A short description what this is about.
  This is not a traditional abstract, but rather something else ...
disclaimer: >
  Some disclaimer for the header
keywords:
  - aaaaa
  - bbbbb
license: "CC BY"
copyright: 
  holder: No idea
  year: 2023
citation: 
  type: report
  container-title: TestBox
  doi: 10.5281/zenodo.1xxxx
doi: 10.5281/zenodo.1xxxx
version: 0.0.1

format:
    html:
        toc: true
        toc-depth: 4
        toc_expand: true
        embed-resources: true
        code-fold: true
        code-summary: 'Show the code'
```
Which gives me the following header section:

> <img width="464" alt="Screenshot 2024-11-14 at 16 24 34" src="https://github.com/user-attachments/assets/74ed64fa-4738-4012-9e77-06eb96eb3d1c">

Now when I use the `title-block.html` partial template from [the official template](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/html/templates/title-block.html) I get

> <img width="422" alt="Screenshot 2024-11-14 at 16 29 51" src="https://github.com/user-attachments/assets/27f982d9-4b13-41f7-9bdf-9ebb8ed8f5af">

which is different to what I would like to have.

Essentially I would like to have an additional part for the disclaimer, some additional text, etc, but essentially as shown in the first screenshot.

So I assume that I am using the wrong template partial. Where can I find the used template partial so that I c a modify it, or what am I missing?

Thanks

Rainer

**Comment by mcanouil** [comment]
You are using the right partial but you are not (you can't) using Quarto internals when you modify it.

See one of the previous discussions:
- https://github.com/quarto-dev/quarto-cli/discussions/8237


Edit: actually you are not using the documented partials

- https://quarto.org/docs/journals/templates.html#html-partials
- https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/html/pandoc

**Reply by rkrug** [reply]
OK - thanks for the clarification. So how can I implement these changes in the template or any other approach to achieve at least adding the Disclaimer section in the header?

**Reply by kbvernon** [reply]
> Edit: actually you are not using the documented partials
> 
> https://quarto.org/docs/journals/templates.html#html-partials
> https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/html/pandoc

Can I get some clarification on this? If I have the following yaml:
````
---
title: "Untitled"
format: html
author:
  - name: Bob
    orcid: 0000-0003-1689-0557
  - name: Tom
    orcid: 0000-0003-1689-0557
---
````
it renders this html header tag for the title block:
```html
<header id="title-block-header" class="quarto-title-block default">...</header>
```
which looks to me like the template partial in `html/templates/title-block.html`, not the one in `html/pandoc/title-block.html`. I also see in `html/templates` additional template partials not listed in the docs. Can these be manipulated in a similar fashion? Or, are we only allowed to replace partials in `html/pandoc`?

For reference
```r
quarto::quarto_version()
#> [1] ‘1.6.40’
```
