### DISCUSSION TITLE
YAML arguments not being passed to my Typst template partials

### DISCUSSION THREAD

**Discussion by mattwarkentin** [quarto-dev/quarto-cli#11459] [Q&A] [answered]
### Description

Hi,

I am trying to create my first Typst custom format. However, I am running up against an issue where the YAML arguments in the Quarto document are not being passed to `typst-template.typ`. I have tried to strip away the unnecessary code from my templates to try to provide a minimal example and hopefully identify the issue.

Even though I have set the `toc: false` argument, a ToC is still included in the report.

## Quarto document (`template.qmd`)
````md
---
title: This is the title of my report.
format: 
  report-typst:
    toc: false
---

# Introduction

## Second level

### Third level

#### Fourth level

# Methods

# Results
````

## Typst Show (`typst-show.typ`)
````typ
#show: doc => report(
$if(title)$
  title: [$title$],
$endif$
$if(subtitle)$
  subtitle: [$subtitle$],
$endif$
$if(date)$
  date: [$date$],
$endif$
$if(lang)$
  lang: "$lang$",
$endif$
$if(region)$
  region: "$region$",
$endif$
$if(margin)$
  margin: ($for(margin/pairs)$$margin.key$: $margin.value$,$endfor$),
$endif$
$if(papersize)$
  paper: "$papersize$",
$endif$
$if(mainfont)$
  font: ("$mainfont$",),
$endif$
$if(fontsize)$
  fontsize: $fontsize$,
$endif$
$if(toc)$
  toc: $toc$,
$endif$
$if(toc-title)$
  toc_title: [$toc-title$],
$endif$
$if(toc-indent)$
  toc_indent: $toc-indent$,
$endif$
$if(toc-depth)$
  toc_depth: $toc-depth$,
$endif$
$if(lof)$
  lof: $lof$,
$endif$
$if(lof-title)$
  lof_title: [$lof-title$],
$endif$
$if(lot)$
  lot: $lot$,
$endif$
$if(lot-title)$
  lot_title: [$lot-title$],
$endif$
  doc,
)
````

## Typst Template (`typst-template.typ`)
````typ
#let report(
  title: none,
  subtitle: none,
  date: none,
  margin: (x: 1.25in, y: 1.25in),
  paper: "us-letter",
  lang: "en",
  region: "US",
  font: (),
  fontsize: 12pt,
  toc: true,
  toc_title: "Table of contents",
  toc_depth: 3,
  toc_indent: 1.5em,
  lof: true,
  lof_title: "List of figures",
  lot: true,
  lot_title: "List of tables",
  doc,
) = {
  if toc {
    block(above: 0em, below: 2em)[
    #outline(
      title: toc_title,
      depth: toc_depth,
      indent: toc_indent
    );
    ]
    pagebreak(weak: true)
  }

  set page(numbering: "1")

  if lof {
    block(above: 0em, below: 2em)[
    #outline(
      title: lof_title,
      target: figure.where(kind: "quarto-float-fig")
    );
    ]
    pagebreak(weak: true)
  }

  if lot {
    block(above: 0em, below: 2em)[
    #outline(
      title: lot_title,
      target: figure.where(kind: "quarto-float-tbl")
    );
    ]
    pagebreak(weak: true)
  }

  doc
}
````

## Snippet of the rendered Typst document (`template.typ` from `keep-typ: true`)

Somewhere along the way it is picking up `toc_title` and `toc_depth` but not the actual argument I'm passing, `toc`.

````typ
#show: doc => report(
  title: [This is the title of my report.],
  date: [2024-11-15],
  lang: "en",
  font: ("Narin",),
  fontsize: 12pt,
  toc_title: [Table of contents],
  toc_depth: 3,
  doc,
)
````

**Comment by mattwarkentin** [comment]
From the terminal during rendering...so `toc` is being passed on to pandoc.
````
pandoc 
  to: typst
  output-file: template.typ
  standalone: true
  default-image-extension: png
  wrap: none
  citeproc: false
  toc: false
  
metadata
  font-paths: _extensions/report/assets/fonts
  mainfont: Narin
  fontsize: 12pt
  lang: en
  subtitle: Oncology Outcomes (O2)
  date: today
  title: This is the title of my great report.
  
[typst]: Compiling template.typ to template.pdf...DONE

Output created: template.pdf
````

**Reply by mattwarkentin** [reply]
And for completeness, the `_extension.yml` file:
````yaml
title: Report
author: Matt Warkentin
version: 0.0.1
contributes:
  formats:
    typst:
      font-paths: assets/fonts
      mainfont: Narin
      fontsize: 12pt
      lang: en
      date: today
      execute:
        echo: false
        warning: false
        message: false
      fig-width: 8
      fig-height: 6
      fig-dpi: 300
      default-image-extension: png
      df-print: paged
      keep-typ: true
      template-partials:
        - typst-template.typ
        - typst-show.typ
````

**Reply by mcanouil** [reply]
Could you share a Git repository instead?

**Reply by mattwarkentin** [reply]
Sure, here it is: https://github.com/oncology-outcomes/report

**Reply by mattwarkentin** [reply]
FWIW, when setting the following YAML params:
````yaml
---
title: This is an example report
format: 
    report-typst:
        foo: bar
        toc: false
---
````
It seems like `toc` is passed to pandoc but not metadata available to `typst-show.typ`.
````sh
pandoc 
  to: typst
  output-file: template.typ
  standalone: true
  default-image-extension: png
  wrap: none
  citeproc: false
  toc: false
  
metadata
  font-paths: _extensions/report/assets/fonts
  mainfont: Narin
  fontsize: 12pt
  lang: en
  subtitle: Oncology Outcomes (O2)
  date: today
  title: This is an example report
  foo: bar
  
[typst]: Compiling template.typ to template.pdf...DONE

Output created: template.pdf
````
