### DISCUSSION TITLE
Control font size code output

### DISCUSSION THREAD

**Discussion by JackCaster** [quarto-dev/quarto-cli#11469] [Q&A]
### Description

Is it possible to change the font size of the output for a code block? By default, it is too large. My workaround is, for a PDF/Latex output, is to redefine the Highlight Verbatim environment (as found in the generated latex file) with 

```yaml

format:
  pdf:
    documentclass: article
    papersize: a4
    include-in-header:
      text: |
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}, fontsize=\small}
```
but I find this solution a bit clunky. It would be nice to be able to redefine the font size with a YAML option, for example.
