### DISCUSSION TITLE
Section numbers of index page?

### DISCUSSION THREAD

**Discussion by eitsupi** [quarto-dev/quarto-cli#1147] [Q&A] [answered]
If you set up `number-sections: true` for a book project, the section numbers on the index page look quite odd because they start at `0` but the next page starts at `2`.
Is this intended?

````yml
project:
  type: book

book:
  title: test
  chapters:
    - index.md
    - page1.md

format:
  html: default

number-sections: true
````

![image](https://user-images.githubusercontent.com/50911393/173557361-1303b20d-a4cc-47f1-a351-f824cc97a717.png)
![image](https://user-images.githubusercontent.com/50911393/173557412-a436995e-bd68-41fb-a111-fb1e58177a17.png)
