### DISCUSSION TITLE
Is it possible to specifiy a .ipynb file in the project yaml (instead of .qmd)?

### DISCUSSION THREAD

**Discussion by Sciemon** [quarto-dev/quarto-cli#11488] [Q&A] [answered]
### Description

The shortened _quarto.yml file for a website looks like this, but the last .ipynb file is not rendered (only the .qmd files are):

```
website:
  [...]
  sidebar:
    - title: "Tutorials"
      style: "docked"
      contents:
        - docs/tutorials/inertia-fundamentals.qmd
        - docs/tutorials/coherency-identification.qmd
        - docs/tutorials/inertia_estimation_event_based.ipynb 
  [...]
```

So i wonder if only .qmd files are allowed?

**Comment by mcanouil** [comment, marked as answer]
Yes and it works.

1. `quarto create project website`
2. `quarto convert about.qmd`
3. `rm about.qmd`
4. Edit `_quarto.yml`

```yml
project:
  type: website

website:
  title: "demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:default
  sidebar:
    - id: default
      contents:
        - about.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

```sh
❯ quarto render
[1/2] index.qmd
[2/2] about.ipynb

Output created: _site/index.html
```
