### DISCUSSION TITLE
Is there a way to add a custom site header when using gh-pages?

### DISCUSSION THREAD

**Discussion by aflip** [quarto-dev/quarto-cli#11492] [Q&A] [answered]
### Description

 I'm deploying my quarto-built site using github pages. I would like to add something to the page headers. Currently I am rendering the website locally using `quarto render` then manually editing the index.html page. But i would like this meta content to go on all pages. On netlify there is an option to add a `_headers` file, is something like this possible on quarto > GH ? 

`<meta http-equiv="X-Clacks-Overhead" content="GNU Terry Pratchett"/>` this is what i want to add to all the page headers

**Comment by mcanouil** [comment]
Use `include-in-header` at the level you want https://quarto.org/docs/output-formats/html-basics.html#includes

> On netlify there is an option to add a _headers file, is something like this possible on quarto > GH ?

That's not up to Quarto.
This is cloud provider features, so you need to check the documentation of the provider you chose.

---

edit: adding my reply with code/screenshot

The following should work and can be combined with profiles, etc.
(the meta is at the bottom but still in the header)
```yml
format:
  html:
    include-in-header:
      - text: |
         <meta http-equiv="X-Clacks-Overhead" content="GNU Terry Pratchett"/>
```

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/934b5369-7f87-416e-8d4a-b769a1f54d9d">

**Comment by cscheid** [comment]
> But i would like this meta content to go on all pages. On netlify there is an option to add a `_headers` file, is something like this possible on quarto > GH ?

I would use post-render project scripts that edit the file programmatically: https://quarto.org/docs/projects/scripts.html#pre-and-post-render

**Reply by mcanouil** [reply, marked as answer]
The following should work and can be combined with profiles, etc.
(the meta is at the bottom but still in the header)
```yml
format:
  html:
    include-in-header:
      - text: |
         <meta http-equiv="X-Clacks-Overhead" content="GNU Terry Pratchett"/>
```

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/934b5369-7f87-416e-8d4a-b769a1f54d9d">
