### DISCUSSION TITLE
Difference with default Bootstrap and Bootswatch

### DISCUSSION THREAD

**Discussion by ajspadial** [quarto-dev/quarto-cli#11496] [Q&A] [answered]
### Description

Default Bootstrap 5 style maintain the basic underline decoration in <a> links. So do most of Bootswatch themes.

However, default Quarto style has removed it. I think basic Quarto drew underlines in links a few years ago. I have found no configuration setting to change that behaviour. 

Is there a way to recover underline in links, other that setting my own css/scss?

**Comment by mcanouil** [comment]
See (S)CSS theming https://quarto.org/docs/output-formats/html-themes.html (i.e., no you have to use (S)CSS)

And for some settings via the Brand feature: https://prerelease.quarto.org/docs/authoring/brand.html

**Reply by cderv** [reply, marked as answer]
With Quarto 1.6 it could be indeed added back using new brand feature 

````yaml
---
title: Test
format: html
brand:
  typography: 
    link: 
      decoration: underline
---

Link to [quarto.org](https://quarto.org)
````

Otherwise, this is controlled by `$link-decoration` SCSS variable. `$link-decoration: underline;` in a theme file
