### DISCUSSION TITLE
Use two languages for abtract and keywords

### DISCUSSION THREAD

**Discussion by Ppantaleo** [quarto-dev/quarto-cli#11497] [Q&A]
### Description

Hello, how to add two languages for abstract and keywords in YML? Currently I add it this way, but it is processed as text and does not display well: 

````
keywords: |
  en: |
    Podocnemidoidea, Upper Cretaceous, Patagonia, Plastron variability, Diversity

  es: |
    Podocnemidoidea, Cretácico Superior, Patagonia, Variabilidad del plastrón, Diversidad
abstract: |
  en: |
    The fossil record of pleurodiran turtles in the Cretaceous of Patagonia is diverse throughout all basins, with Pelomedusoides being scarce compared to the Chelidae. In this article, new records of pelomedusoids are reported from the Bajo de la Carpa Formation (Santonian) at the La Bonita site, Río Negro Province, Argentina. Two specimens are described and referred to Podocnemidoidea by the combination of the following features: posterior marginals not extending over the costals, a straight xiphiplastron with rounded tips, short and U-shaped anterior lobe, a rhomboidal entoplastron, and a humeral-pectoral sulcus that crosses the entoplastron. The observed variability of the pelomedusoid plastron in the specimens recorded in the Neuquén Group shows that these new specimens present a new scute scheme. Evaluating the diversity observed in the Cretaceous pelomedusoids in the Neuquén Group, three stages of their evolution are defined. A first stage in the Cenomanian where the Bothremydidae appear; a second stage in the late Turonian-Coniacian interval where the Bothremydidae and Podocnemidoidea coexist, and a final stage in the Santonian-Campanian where only the Podocnemidoidea persist and increase the diversity and abundance of morphotypes.

  es: |
    Los registros fósiles de tortugas pleurodiras en el Cretácico de Patagonia son diversos a lo largo de todas las cuencas, siendo los pelomedusoides escasos en comparación con los Chelidae. En este artículo se reportan nuevos registros de pelomedusoides de la Formación Bajo de la Carpa (Santoniano) en el sitio La Bonita, Provincia de Río Negro, Argentina. Se describen dos ejemplares y se asignan a Podocnemidoidea por la combinación de las siguientes características: escudos marginales posteriores que no se extienden sobre las costales, un xifiplastrón recto con extremos redondeados, lóbulo anterior corto y en forma de U, un entoplastrón romboidal y un surco humeral-pectoral que atraviesa el entoplastrón. La variabilidad observada en el plastrón de los pelomedusoides registrados en el Grupo Neuquén muestra que estos nuevos ejemplares presentan un nuevo esquema de escudos. Evaluando la diversidad observada en los pelomedusoides del Cretácico en el Grupo Neuquén, se definen tres etapas de su evolución: una primera etapa en el Cenomaniano donde aparecen los Bothremydidae; una segunda etapa en el intervalo Turoniano-Coniaciano tardío donde conviven los Bothremydidae y Podocnemidoidea, y una etapa final en el Santoniano-Campaniano donde solo los Podocnemidoidea persisten y aumentan la diversidad y abundancia de morfotipos.
````

and this gives error: : 
````
`keywords:
  en:
    - Podocnemidoidea
    - Upper Cretaceous
    - Patagonia
    - Plastron variability
    - Diversity
  es:
    - Podocnemidoidea
    - Cretácico Superior
    - Patagonia
    - Variabilidad del plastrón
    - Diversidad
abstract:
  en: |
    The fossil record of pleurodiran turtles in the Cretaceous of Patagonia is diverse throughout all basins, with Pelomedusoides being scarce compared to the Chelidae. In this article, new records of pelomedusoids are reported from the Bajo de la Carpa Formation (Santonian) at the La Bonita site, Río Negro Province, Argentina. Two specimens are described and referred to Podocnemidoidea by the combination of the following features: posterior marginals not extending over the costals, a straight xiphiplastron with rounded tips, short and U-shaped anterior lobe, a rhomboidal entoplastron, and a humeral-pectoral sulcus that crosses the entoplastron. The observed variability of the pelomedusoid plastron in the specimens recorded in the Neuquén Group shows that these new specimens present a new scute scheme. Evaluating the diversity observed in the Cretaceous pelomedusoids in the Neuquén Group, three stages of their evolution are defined. A first stage in the Cenomanian where the Bothremydidae appear; a second stage in the late Turonian-Coniacian interval where the Bothremydidae and Podocnemidoidea coexist, and a final stage in the Santonian-Campanian where only the Podocnemidoidea persist and increase the diversity and abundance of morphotypes.
  es: |
    TORTUGAS PELOMEDUSOIDES DE LA FORMACIÓN BAJO DE LA CARPA (SANTONIANO, CRETÁCICO SUPERIOR) DE LA PROVINCIA DE RÍO NEGRO, PATAGONIA, ARGENTINA. Los registros fósiles de tortugas Pleurodira en el Cretácico de Patagonia son diversos a lo largo de todas las cuencas, siendo los Pelomedusoides escaso en comparación con los Chelidae. En este artículo se dan a conocer nuevos registros de pelomedusoides de la Formación Bajo de la Carpa (Santoniano) en el sitio La Bonita, Provincia de Río Negro, Argentina. Se describen dos especímenes y se asignan a Podocnemidoidea por la combinación de las siguientes características: escudos marginales posteriores que no se extienden sobre las costales, un xifiplastrón recto con sus extremos posteriores redondeados, un lóbulo anterior, corto y en forma de U, un entoplastrón romboidal y un surco humeral-pectoral que atraviesa el entoplastrón. La variabilidad observada en el plastrón de pelomedusoides en los ejemplares registrados en el Grupo Neuquén muestra que estos nuevos ejemplares presentan un nuevo esquema de escudos. Evaluando la diversidad observada en pelomedusoides cretácicos en el Grupo Neuquén se definen tres etapas en su evolución. Una primera etapa en el Cenomaniano donde aparecen los Bothremydidae; una segunda etapa en el intervalo Turoniano-Coniaciano tardío donde conviven los Bothremydidae y Podocnemidoidea, y una etapa final en el Santoniano-Campaniano donde solo los Podocnemidoidea persisten y aumentan la diversidad y abundancia de morfotipos.
````

Thanks!! Version: 1.5.56
