### DISCUSSION TITLE
pandoc creating a custom-style even though I have a style in the refdoc.

### DISCUSSION THREAD

**Discussion by TheFirstHonour** [quarto-dev/quarto-cli#11512] [Q&A] [answered]
### Description

Hello. 
I followed this [guide](https://quarto.org/docs/output-formats/ms-word-templates.html), and I have a reference document with the style "Title2", but when I render the Docx, it also creates a Title2 style as you can see below. 

![{8C3E3073-840F-414F-80BF-2738ADC7A511}](https://github.com/user-attachments/assets/7762ce23-10f0-4ba6-b2e7-dff0a9a0c608)

And if I try to click on the "Title2" that I created inside the rendered document, it does not work at all. 
Am I missing something here? I just need it to use the custom style that I set. 

I also tried different names and none worked. 

Thanks in advance. 

CODE:
```
---
title: "test"
author: "test"
date: today
format: 
  docx:
    reference-doc: custom-reference2.docx
    toc: false
    toc-title: Contents
    number-sections: true
---

[test]{custom-style="Title2"}

# Introduction

This is a test sentence.

## Section 1: Getting Started



```
