### DISCUSSION TITLE
Can directory level _metadata.yml provide separate repo-actions

### DISCUSSION THREAD

**Discussion by mark-andrews** [quarto-dev/quarto-cli#11562] [Q&A] [answered]
### Description

In a directory level `_metadata.yml`, we can have a new `repo-url`  key that overrides the `website/repo-url` that is set in the top level `_quarto.yml`. See https://github.com/quarto-dev/quarto-cli/issues/4668 and https://github.com/quarto-dev/quarto-cli/commit/3870d39db199d81de65e06e6055b0a49e4309f05 .

However, it seems like I can not do the same thing with `repo-actions`. In other words, I can not set a `repo-actions` value in a directory level `_metadata.yml` that overrides the value set in `website/repo-actions` in `_quarto.yml`. For example, if my `_quarto.yml` has

```yml
website:
  repo-url: "https://github.com/foobar/barfoo"
  repo-actions: [source, edit]
````

if I have the following in a directory `_metadata.yml`

```yml
website:
  repo-url: "https://github.com/foobar/bazfoo"
  repo-actions: [source]
````

then the URL for the GitHub repo on pages in that sub-directory will change from `barfoo` to `bazfoo`, but the actions will not have from view source and edit source to just view source.

Ultimately what I would like is to have pages in some subdirectories to have the button to view the source code on GitHub, and pages in some other subdirectories to not have any buttons to link to the source code on GitHub, which I am trying to do by setting `repo-actions: none` in `_metadata.yml` in some directories.

Is there a way to to have directory level different values of `repo-actions`, or is there some other way of turning off these repo actions in all pages in some subdirectories?
