### DISCUSSION TITLE
How to use URL in yaml header (e.g., `theme`)?

### DISCUSSION THREAD

**Discussion by mcanouil** [quarto-dev/quarto-cli#1158] [Q&A] [answered]
Hi,

is there any way to allow something like below?
Especially, the ability to use URL for `theme`.

```
---
title: "A Title"
subtitle: "A Subtitle"
author: Mickaël Canouil, *Ph.D.*
institute: <a href="https://mickael.canouil.fr/">mickael.canouil.fr</a>
date: today
date-format: "dddd, [the] D[<sup style='font-size:65%;font-style:italic;'>th</sup>] [of] MMMM, YYYY"
format:
  revealjs:
    self-contained: true
    slide-number: c
    highlight-style: github
    theme: https://raw.githubusercontent.com/mcanouil/publishing-templates/main/quarto-revealjs/coeos/assets/coeos.scss
    footer: |
      <a href="https://mickael.canouil.fr/">mickael.canouil.fr</a>
      |
      <a href = "https://creativecommons.org/licenses/by-sa/4.0/">License: CC-BY-SA-4.0</a>
    logo: https://raw.githubusercontent.com/mcanouil/hex-stickers/main/SVG/mc.svg
    include-in-header: https://raw.githubusercontent.com/mcanouil/publishing-templates/main/quarto-revealjs/coeos/assets/favicon.html
---

## First slide

Content
```
