### DISCUSSION TITLE
cross-post: how do you exclude a specific file from quarto listing

### DISCUSSION THREAD

**Discussion by ligea-alexander** [quarto-dev/quarto-cli#11613] [Q&A]
### Description

[https://github.com/quarto-dev/quarto-web/discussions/1502#discussion-7611225](url)

Hi, I'm working on a Quarto-based portfolio and blog, and I have a scenario where I need help excluding specific .ipynb files from being rendered as individual posts in a listing. Here's the situation:

1. My blog folder contains multiple .qmd files for blog posts, along with some Jupyter notebooks that I use for referencing charts or code in the blog posts.
2. In one specific case, I referenced visualizations and analysis from a Jupyter notebook (1-intervention-analysis.ipynb) in a corporate-visualizations blog post (corp-viz.qmd).
3. The notebook is necessary because it contains charts that I embed or reference directly in the blog post, but I do not want the notebook itself to render as a standalone blog post in my listings.

Configurations I've tried: 
<img width="622" alt="Screenshot 2024-12-04 at 4 41 16 pm" src="https://github.com/user-attachments/assets/953e4588-7ce1-4ddf-a00c-a67fe4b36d6a">
```
---
title: "Blog"
title-block-banner: true
description: "I enjoy writing about tools I've tried and sharing that knowledge with fellow learners."
listing:
  id: data-viz-blog
  contents: blog
  type: grid
  categories: true
  sort-ui: [date]
  page-size: 36
  exclude:
    file: blog/corporate-visualizations/1-intervention-analysis.ipynb
---
```

**Comment by mcanouil** [comment]
See https://quarto.org/docs/websites/website-listings.html#listing-contents

Note that your use of include/exclude is incorrect (`file` or `item` are not metadata, unless you have set those in your documents; YAML indentation is important "exclude" is not under "contents"), trying out random things is unlikely to work, see <https://quarto.org/docs/websites/website-listings.html#including-or-excluding-items>.

Additionally, hide your Jupyter notebooks using a `_` prefix as described in https://quarto.org/docs/websites/index.html#render-targets

**Reply by ligea-alexander** [reply]
Hi, thanks for responding! 

I used the link shared covering listing-contents but everytime I do 
```
---
title: "Blog"
title-block-banner: true
description: "I enjoy writing about tools I've tried and sharing that knowledge with fellow learners."
listing:
  id: data-viz-blog
  contents: blog
  type: grid
  categories: true
  sort-ui: [date]
  page-size: 36
  exclude:
    - corporate-visualizations/1-intervention-analysis.ipynb
---
```

I get prompt there's an error: 
<img width="778" alt="Screenshot 2024-12-06 at 10 55 21 am" src="https://github.com/user-attachments/assets/97b1be1b-71b8-4c1f-bbdd-6a296470369a">

Additionally, I tried using a ```_``` in front of the jupyter notebook I don't want rendered and got this error:

```
ERROR: Unable to embed content from notebook '1-intervention-analysis.ipynb'
The file /projects/blog/corporate-visualizations/1-intervention-analysis.ipynb doesn't exist or cannot be read.
```

charts in the notebook are being referenced in the article so possibly using ```_``` is not suitable in this scenario?
