### DISCUSSION TITLE
Line numbers

### DISCUSSION THREAD

**Discussion by arnaudgallou** [quarto-dev/quarto-cli#1162] [Q&A] [answered]
Is there any ways to show line numbers in the margin when knitting as `.pdf`? Couldn't find the information in the documentation. I'm talking about line numbers of a text, not code chunk.

**Comment by cderv** [comment, marked as answer]
I think adding linenumbers on text can be done in LaTeX using **lineo** package

So you can just add the required LaTeX pieces of code in the header of your document
https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes

````yaml
format: 
  pdf:
    include-in-header:
      text: |
        \usepackage{lineno}
        \linenumbers
````
