### DISCUSSION TITLE
My website knotes.co.in dot showing the last content of the sidebar in mobile view

### DISCUSSION THREAD

**Discussion by drkmenon** [quarto-dev/quarto-cli#11696] [Q&A]
### Description

```
project:
  type: website
  output-dir: docs
  resources:
    - ads.txt 

website:
  title: "knotes"
  site-url: https://www.knotes.co.in
  description: "Kishore Puthezhath's digital garden built around orthopaedic stream"
  site-path: '/'
  favicon: /image/logo.png
  announcement: 
   icon: info-circle
   dismissable: true
   content: "**Save the date** - 11th Basic Orthopaedic Pathology Course **31 Jan** to **9 Feb 2025**  [click here](https://www.knotes.co.in/education%20technology/basicc)"
   type: primary
   position: below-navbar
  navbar:
    background: "#f9fbfd"
    foreground: dark
    search: false
    tools:
     - icon: linkedin
       text: linkedin
       href: https://www.linkedin.com/in/kishore-puthezhath-frcs-48482747/
     - icon: github
       text: github
       href: https://github.com/drkmenon
    logo: /image/knotes.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: https://www.knotes.co.in/revision%20notes/basic%20science/bone
        text: Orthopaedics
      - href: https://www.knotes.co.in/biomedical/research%20methodology/science
        text: Research
      - text: My blog
        href: posts.qmd
      - icon: rss
        href: posts.xml
    
  sidebar: 
    collapse-level: 2
    contents: 
      - section: Orthopaedics
        contents: Revision notes
      - text: "---"
      - section: Medical Education
        contents: Education technology
      - text: "---"  
      - section: Research
        contents: Biomedical
      - text: "---"
      - section: Practical Catallactics
        contents: Catallactics
      - text: "---"
      - section: Blog
        contents: posts
      - text: "---"
      - section: News
        contents: Farm news
      - text: "---"
      - section: Backyard
        contents: Dumping ground
      - text: "---"
      - section: About the author
        contents: 
          - href: author.qmd
          - href: articles.qmd
      - text: "---"
      - section: Privacy
        contents:
          - href: tenet.qmd
      - text: "---"
    background: white
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    right: "Copyright 2024 @ Kishore Puthezhath"
    left: "Opinions are for informational purposes"
    background: white
  reader-mode: false
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-7GYDLCJCZE"
    anonymize-ip: true
  margin-header: subscribe.html
  twitter-card: true  
  open-graph: true
  
  
  
    
format:
  html:
    theme:
      light: [cosmo, theme.scss]
    mainfont: san-sherif #palatino
    code-copy: true
    code-overflow: wrap
    fontsize: 1.2rem
    linestretch: 1.5
    fontcolor: "#1c1c1c"
    linkcolor: "#0072bb"
    backgroundcolor: "white"
    css: styles.css
    toc: true
    responsive: true
    freeze: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

editor: visual
bibliography: references.bib
comments: 
  hypothesis: true
```

 
This is my _quarto.yml of the website knotes.co.in. The website sidebar is not scrolling to the bottom most content in smaller screens. Ok with desktop and bigger screens. What to do?
