### DISCUSSION TITLE
Generating both the HTML and ipynb output for a profile

### DISCUSSION THREAD

**Discussion by jlperla** [quarto-dev/quarto-cli#11707] [Q&A] [answered]
### Description

I have a profile file such as a `_quarto-lectures.yml`
```yaml
project:
  type: website
  output-dir: .lectures_output
  render:
    - lectures/index.qmd
    - lectures/intro.qmd
    - lectures/python.qmd
search: false
website:
  title: "Example Quarto Slides"
  navbar:
    left:
      - href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

I want to output the HTML and also a ipynb verison of it.

RIght now I manually go
```bash
quarto render --profile lectures 
quarto render --profile lectures --to ipynb --no-clean
```

Is there a way to modify my file to make this happen automatically when I go `quarto render --profile lectures ` ?  A post-render, etc.?

**Comment by cscheid** [comment, marked as answer]
Did

```yml
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  ipynb: default
```

not do the trick?

**Reply by mcanouil** [reply]
It should work as it's also the example for `format-links`: https://quarto.org/docs/output-formats/html-multi-format.html

If it does not work at the project level, `_metadata.yml` inside subdirectories does, as well as document-level.

**Comment by jlperla** [comment]
Thanks.  So simple, not sure why I was confused.

It didn't work at the project level, but I put the `ipynb: default` in my indiviudal qmd files and it now outputs both the revealjs and the ipynb.

**Reply by mcanouil** [reply]
If you have a directory with Quarto documents, you can avoid repeating using `_metadata.yml`.

**Comment by jlperla** [comment]
Almost works for me!  My only challenge is that I have one of the qmd files intended to be a webpage entry to a set of revealjs lectures.

So I put in the following for the `_metadata.yml` which works great for all of my slides.
```
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
format:
  clean-revealjs:
    width: 1280
    height: 720
    toc: true
    toc-depth: 1
    progress: false
    scrollable: false
    chalkboard: true
  ipynb: default
execute: 
  cache: true    
``` 

But for the entrypoint (the `index.qmd') I want a normal HTML file, and no revealjs-clean and no ipynb output.

Can I make changes to the file itself to overrite those and turn off ipynb and the clean-revealjs instead?  For example, if I had the following in `index.qmd` then what should I replace the `null`, etc. with?

I would prefer not to put things in a sub-folder, but I guess that would also work.

---
title: "Example Quarto Slides"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  clean-revealjs: null
   ipynb: null
```

**Reply by mcanouil** [reply]
Here is how metadata are merged: https://quarto.org/docs/projects/quarto-projects.html#metadata-merging

**Reply by jlperla** [reply]
I was looking at that, but it was unclear what I could do to replace the whole `ipynb` and `clean-revealjs` with something to which removes it entirely, or says "ignore`? I tried things like the follwoing in my `index.qmd`...

```
format:
  clean-revealjs: false
  ipynb: false
  html: default
```
 but the false didn't work, neither did null, etc.
