### DISCUSSION TITLE
Working with Bootswatch themes

### DISCUSSION THREAD

**Discussion by andrewpbray** [quarto-dev/quarto-cli#1171] [Q&A] [answered]
I've noticed that each of the bootswatch themes have default elements but also variants of navbars and buttons. The sandstone theme, for example, shows three navbars on the [bootswatch website](https://bootswatch.com/sandstone/).

<img width="1129" alt="Screen Shot 2022-06-17 at 10 10 42 AM" src="https://user-images.githubusercontent.com/1627362/174346852-c08ab144-d335-413c-a63b-28950b83ae4f.png">

I went to see which one I'd get out of the box when I use this theme.

```
website:
  title: "My website"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
        
format:
  html:
    theme: sandstone
```

This will give me the top of the three navbars, in dark gray.

<img width="468" alt="Screen Shot 2022-06-17 at 10 30 18 AM" src="https://user-images.githubusercontent.com/1627362/174348968-33e8f7c3-7c7b-4277-8e33-130183640f9a.png">

This is fine, but I'm digging the softer contrast of the bottom of the three navbar, and am working to figure out the easiest way to create it. When I inspect the source for these, each of them differ in the last two of the four classes that they're assigned.

`<nav class="navbar navbar-expand-lg navbar-light bg-light">`
`<nav class="navbar navbar-expand-lg navbar-dark bg-primary">`
`<nav class="navbar navbar-expand-lg navbar-dark bg-dark">`

This says to me that I want a dark background and will probably need a light foreground too, so I add those navbar options to my YAML.

```
website:
  title: "My website"
  navbar:
    background: light
    foreground: dark
    left:
      - href: index.qmd
        text: Overview
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
         
format:
  html:
    theme: sandstone
```

That gets part of the way...

<img width="532" alt="Screen Shot 2022-06-17 at 10 34 41 AM" src="https://user-images.githubusercontent.com/1627362/174349591-6a95005b-85fa-4f33-8ba9-118cedb84989.png">

... but isn't quite there. The active page (overview) is the wrong color, as is the hovered over link (materials).

I can create a `custom.scss` file and tinker with promising sounding Sass variables like `$navbar-default-link-hover-color` and `$navbar-default-link-active-color`, but I was wondering if there was a more systematic way to do this.

More generally, I'm also wondering from a design perspective how you've decided which variables to make accessible with [YAML options](https://quarto.org/docs/websites/website-navigation.html#top-navigation).

Thanks!
