### DISCUSSION TITLE
Building series navigation

### DISCUSSION THREAD

**Discussion by eliottkalfon** [quarto-dev/quarto-cli#11722] [Q&A]
### Description

Hi all, I am trying to get navigation within a series of article to work. Including `page-navigation: true` in my _quarto.yml file did not do anything. I was wondering if this was linked to overwriting the footer, but removing it did not do much either.

here is my _quarto.yml config:

```yaml
project:
  type: website
  render:
    - "*.qmd"
    - "!resources/"

website:
  title: "Eliott Kalfon"
  page-navigation: true
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        menu:
          - text: "All Posts"
            href: posts/index.qmd
          - text: "Algorithms"
            href: posts/#category=Algorithms
          - text: "Engineering"
            href: posts/#category=Engineering
          - text: "Books"
            href: posts/#category=Books
          - text: "Blogging"
            href: posts/#category=Blogging
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer: |
    Want to connect? Contact me <a href="/contact.html">here</a>.<br>
    Copyright 2024, Eliott Kalfon

collections:
  posts:
    series:
      - name: "Algorithm Complexity Series"

resources:
  - resources/img/favicon-light.png
  - resources/img/favicon-dark.png

include-in-header: favicon.html

pagetitle: "{{< meta title >}}"`

```

and here some sample article metadata
```qmd
---
title: "Big Oh, Big Omega, Big Theta: What is asymptotic notation?"
author: "Eliott Kalfon"
date: "2024-08-31"
format:
  html:
    css: _blog_styles.css
editor: visual
categories: [Algorithms]
tags: [Algorithms, Complexity, Asymptotic Notation, Analysis]
series:
  name: "Algorithm Complexity Series"
  index: 2
---
```

Thanks a lot!
