### DISCUSSION TITLE
Allow extensions to have configuration

### DISCUSSION THREAD

**Discussion by multimeric** [quarto-dev/quarto-cli#11730] [Feature Requests]
### Description

Currently extensions are either enabled or disabled. For example, a filter extension [is either in the filter list, or it's not](https://quarto.org/docs/extensions/filters.html#activating-filters). However, extensions often provide behaviour that user will want to configure in detail. Shortcodes are a bit better because they have a arguments that can be used to configure them, but ideally these arguments could be put in one central place for the whole project to avoid repetition.

I think a nice solution to this would be to extend the Quarto YAML format. I propose that items in the `filters` list can optionally become a one-item map whose key must be the extension name and whose value must also be a map. This is a common YAML pattern:

```yaml
filters:
  - my_custom_extension:
        arg_one: 1
        arg_two: foo
  - quarto
```

Then, I think the lua API should gain another function that returns the extension's config. This would allow extensions like filters to easily use this information:
```lua
get_extension_config()
-- { arg_one = 1, arg_two = "foo" }
```

As a bonus extra, it would be cool if we could provide a schema to validate the configuration before even running the filter, but this is non-essential. e.g. in the `_extension.yml`:

```
contributes:
  filters:
    - my_custom_extension.lua
  config_schema:
    - schema.json
```
