### DISCUSSION TITLE
Allow extensions to have multiple filters at different phases of the lifecycle

### DISCUSSION THREAD

**Discussion by multimeric** [quarto-dev/quarto-cli#11749] [Feature Requests]
### Description

[Quarto 1.4 introduced lifecycle phase targeting](https://quarto.org/docs/prerelease/1.4/lua_changes.html). Unfortunately this still isn't available for extensions. 

For example, with a `_extension.yml` that contains this:
```yaml
contributes:
  filters:
  - at: pre-ast
    path: filter1.lua
  - at: post-quarto
    path: filter2.lua
  - at: post-render
    path: filter3.lua
```

```
In file _extensions/foo/_extension.yml
(line 7, column 5 through line 8, column 22) Array entry 1 with value at: pre-ast
  path: filter1.lua failed to be a string.
6:   filters:
7:   - at: pre-ast
      ~~~~~~~~~~~~
8:     path: filter1.lua
  ~~~~~~~~~~~~~~~~~~~~~~
9:   - at: post-quarto
✖ The value
```

However, it is desirable for extensions to be able to specify this, as they might need to hook into the lifecycle at multiple phases.
