### DISCUSSION TITLE
Parsing metadata for typst through a loop in show.typ

### DISCUSSION THREAD

**Discussion by royfrancis** [quarto-dev/quarto-cli#11759] [Q&A] [answered]
### Description

I have created a custom typst template to convert a qmd to pdf and it fails when running `quarto render index.qmd`:

```
[typst]: Compiling index.typ to index.pdf...error: unexpected argument
    ┌─ index.typ:179:10
    │  
179 │   #let sheet(
    │ ╭───────────^
180 │ │ 
181 │ │   labels: ()
182 │ │   
183 │ │ ) = {
    │ ╰─^
```

Here are the files:

**index.qmd** (Empty values and missing values for testing purposes)

```
---
labels:
  - line1: "Olivia Sterling"
    line2: "Quantum Physicist"
    line3: "Quantum Research Institute"
    line4: "o.sterling@quantumri.edu"
  - line1: "Marcus Finnegan"
    line2: "Chief Technology Officer"
    line3: ""
    line4: "m.finnegan@techinnovators.com"
  - line1: "Ariella Knox"
    line3: "Global Solutions Inc."
    line4: "a.knox@globalsolutions.com"
format:
  loop-typst:
    keep-typ: true
---
```

**typst-template.typ**

```
// main
#let sheet(

  labels: ()
  
) = {

  set page(
    paper: "a4",
  )
  set text(16pt, font: "Public Sans", fill: rgb("#444444"))

  grid(
    ..labels.map(label => {
      let content = (
        if label.line1 != "" and label.line1 != none { 
          label.line1 + "\n" 
        } else { 
          "" 
        }) + (if label.line2 != "" and label.line2 != none { 
          label.line2 + "\n" 
        } else { 
          "" 
        }) + (if label.line3 != "" and label.line3 != none { 
          label.line3 + "\n" 
        } else { 
          "" 
        }) + (if label.line4 != "" and label.line4 != none { 
          label.line4
        } else { 
          "" 
        }
      );
      
      block(inset: 1em, align(left, content))
    })
  )
}
```

**typst-show.typ** (This is likely the one with issues) I am following the example [here](https://github.com/quarto-ext/typst-templates/blob/main/ams/_extensions/ams/typst-show.typ), but I can't understand how it works. For example; where does the `by-author` even come from?

```
#show: sheet.with(

  $if(labels)$
    labels: (
    $for(labels)$
    (
      line1: "$it.line1$",
      line2: "$it.line2$",
      line3: "$it.line3$",
      line4: "$it.line4$",
    )$sep$,
    $endfor$,
    ),
  $endif$

)
```

I can see in the generated `index.typ`, that the data is not parsed correctly:

```
#show: sheet.with(

      labels: (
        (
      line1: "",
      line2: "",
      line3: "",
      line4: "",
    ),
    ),
  
)
```

The typst code has been validated on the typst app, so it's known to work. There is something going wrong in the show.typ file. There are probably other issues as well.

Here is a repo with these files organized as a quarto extension: https://github.com/royfrancis/typst-loop-test
Here is the working code on typst: https://typst.app/project/rN3JXHKwXgPKGgoYcYd3kp

`quarto 1.6.32`

**Comment by gordonwoodhull** [comment, marked as answer]
Indeed Typst does have a learning curve.

The error you are seeing is because your `sheet()` function only takes on parameter `labels`, but when used with 

```
#show: sheet.with(labels: ...)
```
Typst is going to pass the *rest of the document* as an implicit second parameter.

`.with()` partially specifies the parameters, returning another function with those parameters bound.

`#show:` will pass the rest of the document to the function on the right of the colon.

So you can either add a `doc` parameter to your `sheet()` function, or you can explicitly ignore this content with 

```
#show: doc => sheet(...)
```

Secondly, you seem to be using a metadata key (`labels`) which is defined by Quarto or Pandoc. You can see this by printing it in the template instead of trying to iterate over it; the value is `true`.

For example, renaming the key to `foo-labels` allows the data to get through.

### typst-show.typ
```
#show: doc => sheet(

  $if(foo-labels)$
    labels: (
    $for(foo-labels)$
    (
      line1: "$it.line1$",
      line2: "$it.line2$",
      line3: "$it.line3$",
      line4: "$it.line4$",
    )$sep$,
    $endfor$,
    ),
  $endif$
)
```

### index.qmd
```
---
foo-labels:
  - line1: "Olivia Sterling"
    line2: "Quantum Physicist"
    line3: "Quantum Research Institute"
    line4: "o.sterling@quantumri.edu"
  - line1: "Marcus Finnegan"
    line2: "Chief Technology Officer"
    line3: ""
    line4: "m.finnegan@techinnovators.com"
  - line1: "Ariella Knox"
    line3: "Global Solutions Inc."
    line4: "a.knox@globalsolutions.com"
format:
  loop-typst:
    keep-typ: true
    font-paths: fonts
---
```
<img width="438" alt="image" src="https://github.com/user-attachments/assets/0f776225-500f-42d6-9c9c-938012d1c891" />


### `by-author`

> where does the `by-author` even come from?

In general, the metadata passed to Pandoc is not exactly the same metadata you specify to Quarto; there is plenty of preprocessing that happens in the Quarto front-end and in the Lua filters before a different set of metadata is passed to Pandoc. 
(I haven't investigated the provenance of `by-author` in particular.)
