### DISCUSSION TITLE
Issues with Math Delimiters and Equation Number Alignment in Quarto Word Output

### DISCUSSION THREAD

**Discussion by JamesSmith20** [quarto-dev/quarto-cli#11753] [Q&A] [answered]
### Description

**1. Inability to Use `\(` or `\[` for Math Delimiters**

Currently, Quarto does not render equations wrapped with `\(`...`\)` or `\[`...`\]`. Only `$...$` for inline math and `$$...$$` for block math are supported. However, many users (including myself) prefer `\(` and `\[` for consistency with LaTeX standards. Additionally, some large language models and AI tools generate equations using `\(` and `\[` as their default output, making it challenging to integrate such content into Quarto documents without manual modifications.

When attempting to configure the YAML to replace `$` with `\(` and `$$` with `\[` using `mathjax` settings, it results in errors or fails to render correctly.

---

**2. Equation Numbering Alignment in Word Output**

When rendering a Quarto document to Word format, equation numbering is not right-aligned, leading to a suboptimal appearance. This has been discussed in community forums, such as this [[StackOverflow question](https://stackoverflow.com/questions/75230272/losing-equations-numbering-when-i-render-quarto-document-to-word)](https://stackoverflow.com/questions/75230272/losing-equations-numbering-when-i-render-quarto-document-to-word), where others have also encountered the issue without a clear resolution.

---

#### **Example 1: Math Delimiter Test**

This example demonstrates the inability to use `\(` and `\[` as math delimiters in Quarto:

```yaml
---
title: "Math Delimiter Test"
format:
  html:
    math:
      mathjax:
        tex:
          inlineMath: [["\\\\(", "\\\\)"]]
          displayMath: [["\\\\[", "\\\\]"]]
---

# Math Delimiter Test

Inline math example: \( E = mc^2 \) (should work with `\(`...`\)` but doesn't).

Block math example:

\[
a^2 + b^2 = c^2
\]
```

Expected Behavior:
- The `\( ... \)` and `\[ ... \]` delimiters should render math correctly in HTML output.

---

#### **Example 2: Equation Numbering in Word**

This example demonstrates the misalignment of equation numbers in Word output:

```yaml
---
title: "Equation Numbering Test"
author: "wananchi"
date: "`r Sys.Date()`"
format:
  docx:
    fontfamily: libertinus
    fontsize: 11pt
    toc: false
    number-sections: true
---

# Equation Numbering Test

The following demonstrates an equation with numbering:

$$
ES_{w,t} = \varepsilon_wEP_{w,t}\
$${#eq-test}
```

Expected Behavior:
- In Word output, equation numbering should be aligned to the right for better formatting and consistency with academic standards.

---

### Environment Details:
- **Quarto Version**: Output of `quarto check`:
  ```plaintext
  [Version Information]
  Quarto version: Quarto 1.5.52 (D:/Instrument/R/Quarto/bin/quarto.exe)
  ```
- **RStudio IDE Version**: 
 ```plaintext
  [Version Information]
  RStudio 2024.12.0+467 "Kousa Dogwood" Release (cf37a3e5488c937207f992226d255be71f5e3f41, 2024-12-11) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.12.0+467 Chrome/126.0.6478.234 Electron/31.7.6 Safari/537.36. 
  ```
- **Operating System**: 
```
  [Version Information]
The device name is LAPTOP-TJ8MJQCH
Processor Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz 2.30GHz
Machine with RAM 8.00GB (7.88GB available)
Device ID 2FEE0528-19A8-444A-9993-B90F15CECE1A
Product ID 00342-35380-37736-AAOEM
System Type 64-bit operating system based on x64 processor
```

- **Reproducibility**: I have upgraded all relevant software, including Quarto, RStudio, and R packages, to the latest versions.

---

### Additional Notes:
These issues affect both usability and formatting quality for academic and technical documents, particularly when Word is the primary output format. Given the prevalence of `\(` and `\[` in AI-generated content and LaTeX-based workflows, supporting these delimiters natively would significantly improve user experience.

**Comment by mcanouil** [comment, marked as answer]
```
format:
  html:
    math:
      mathjax:
        tex:
          inlineMath: [["\\\\(", "\\\\)"]]
          displayMath: [["\\\\[", "\\\\]"]]
```

Where did you see that syntax? Did you use some AI instead of actually looking at the documentation of the tools?
- https://quarto.org/docs/output-formats/html-basics.html#latex-equations
- https://pandoc.org/MANUAL.html#extension-tex_math_single_backslash 
- https://pandoc.org/MANUAL.html#extension-tex_math_double_backslash

Please avoid trusting and using blindly generated contents.

<table>
<tr><th>Input</th><th>Output</th></tr>
<tr><td>

````qmd
---
title: "Quarto Playground"
from: markdown+tex_math_single_backslash
format:
  html:
    html-math-method: mathjax
---

Inline math example: \( E = mc^2 \)

Block math example:

\[
a^2 + b^2 = c^2
\]

````

</td><td>

<img width="720" alt="image" src="https://github.com/user-attachments/assets/befe3b2c-ca87-4e6c-81ca-bb751ff93292" />

</td></tr>
</table>

---

This syntax ``date: "`r Sys.Date()`"`` is wrong (correct syntax is `date: today`). You should not use `` `r ...` `` expression in Quarto, especially when there is a native support for dates: https://quarto.org/docs/reference/dates.html
You should not blindly use/paste code found online.

This being said, Word document theming is handled by the reference document, see <https://quarto.org/docs/output-formats/ms-word-templates.html>.
Unfortunately, in the case of Word document, the numbering of equations is inside the equation block itself and this is why the number is not aligned but is centred as part of the equation.
This is done by [`src/resources/filters/crossref/equations.lua`](../blob/main/src/resources/filters/crossref/equations.lua).
It would need to figure out what's the OpenXML code and write an exception as done for LaTeX and Typst (Pull Request are welcome).
Note that Word does not actually support equation numbering, it supports captions which is not the same thing. You can find resources online showing how to hack your way to number equations in Word such as <https://www.howtogeek.com/740936/how-to-number-or-label-equations-in-microsoft-word/> or <https://www.supportyourtech.com/word/how-to-number-equations-in-word-a-step-by-step-guide/>.
As you can see, those are hacks.


Side note, the current stable version of Quarto is 1.6.39.

**Reply by JamesSmith20** [reply]
Thank you for your response! The documentation links and examples you shared were very helpful in addressing my issue. Much appreciated!

**Reply by JamesSmith20** [reply]
I also find using `docx-math-method: mathjax` correctly renders math in the MathJax method for DOCX output.
```
---
title: "Quarto Playground"
from: markdown+tex_math_single_backslash
format:
  docx:
    docx-math-method: mathjax
---
```
