### DISCUSSION TITLE
Wish: a way to define "presets" for chunk options for use in long documents / books

### DISCUSSION THREAD

**Discussion by gavinsimpson** [quarto-dev/quarto-cli#11751] [Feature Requests]
### Description

When writing longer documents (i.e. presentations for lectures, papers, books, &hellip;) I often find myself writing the same few sets of chunk options over and over again. For example:

* a chunk to load packages at the start of a chapter or slide deck, which I use `echo: false` and `output: false` and `message: false` etc
* chunk options with `fig-width` and `fig-height` defined for document figures containing a single full-width plot or for a row of two plots, etc

While one can set a single set of chunk defaults *per output format*, flexibility beyond that is (as far as I can tell) not possible. I would like to propose that it be possible that *classes* of chunks be defined in the YAML header or `_quarto.yml`, and subsequently applied to individual chunks via the chunk option `class`. I.e. something like

```yaml
chunks:
  setup:
    echo: false
    include: false
  one-fig-full:
    echo: false
    fig-width: 7
    fig-asp: 1/1.77777
    dpi: 150
    out.width: 100%
    fig.align: center
  one-fig: 
    echo: false
    fig-width: 7
    fig-asp: 1/1.77777
    dpi: 150
    out.width: 80%
    fig.align: right
  four-fig:
    echo: false
    fig-width: 7
    fig.asp: 1
    dpi: 150:
    fig-align: center
```

then

````{qmd}
```{r}
#| label: doc-setup
#| class: setup
library("ggplot2")
library("mgcv")
```
````

or

````{qmd}
```{r}
#| label: fig-plot1
#| class: one-fig-full
df |>
  ggplot(
    aes(
      x = x
      y = y
    )
  ) +
  geom_point()
```
````

It would be nice to be able to inherit options, for example:

```yaml
chunks:
  setup:
    echo: false
    include: false
  figs: 
    echo: false
    fig-width: 7
    fig-asp: 1/1.77777
    dpi: 150
    out.width: 100%
    fig.align: center
  one-fig-full-show:
    inherit: figs
    echo: true
```
