### DISCUSSION TITLE
Allow custom definition of source and edit urls for repo-actions, like issue-url already does

### DISCUSSION THREAD

**Discussion by kirkpsmith** [quarto-dev/quarto-cli#11790] [Feature Requests]
### Description

Hi, thank you Quarto devs!

Additional customization of the urls for viewing/editing the source of a page would extend the utility of `repo-actions` beyond just GitHub (GitLab, Forgejo, Gitea, Codeberg, _etc._).

For example, right now I am limited to this:
```
website:
  title: "Flow Battery Research Collective"
  site-url: "https://fbrc.dev"
  repo-url: https://codeberg.org/FBRC/website/
  repo-actions: [issue] # only the issue url works
```
I could use all three `repo-actions` if this functionality was implemented:
```
website:
  title: "Flow Battery Research Collective"
  site-url: "https://fbrc.dev"
  repo-url: https://codeberg.org/FBRC/website/
  repo-actions: [edit, source, issue]
  edit-url: https://codeberg.org/FBRC/website/_edit
  source-url: https://codeberg.org/FBRC/website/src/branch/

```
