### DISCUSSION TITLE
Problem wit toc-title when using partials in typst

### DISCUSSION THREAD

**Discussion by psads-git** [quarto-dev/quarto-cli#11848] [Q&A] [answered]
### Description

I am getting the following error, when using the document and template partial below. Could you please help me?
  
```
[typst]: Compiling x.typ to x.pdf...error: unexpected argument: toc_title
    ┌─ x.typ:266:2
    │
266 │   toc_title: [Table of contents],
    │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
The `quarto` document:

```
---
title: "My title"
author: My Name
execute: 
  cache: true
format:
  typst:
    template-partials:
      - typst-template.typ
    papersize: a4
    margin:
      x: 2cm
      y: 2cm
    toc: false
    number-sections: true
jupyter: myenv2
keep-typ: true
---

# introduction

```

The template partial is:

```
#let article(
  title: none,
  authors: none,
  date: none,
  abstract: none,
  cols: 1,
  margin: (x: 1.25in, y: 1.25in),
  paper: "us-letter",
  lang: "en",
  region: "US",
  font: (),
  fontsize: 11pt,
  sectionnumbering: none,
  toc: false,
  doc,
) = {
  set page(
    paper: paper,
    margin: margin,
    numbering: "1",
  )
  set par(justify: true)
  set text(lang: lang,
           region: region,
           font: font,
           size: fontsize)
  set heading(numbering: sectionnumbering)

  if title != none {
    align(center)[#block(inset: 2em)[
      #text(weight: "bold", size: 1.5em)[#title]
    ]]
  }

  if authors != none {
    let count = authors.len()
    let ncols = calc.min(count, 3)
    grid(
      columns: (1fr,) * ncols,
      row-gutter: 1.5em,
      ..authors.map(author =>
          align(center)[
            #author.name \
            #author.affiliation \
            #author.email
          ]
      )
    )
  }

  if date != none {
    align(center)[#block(inset: 1em)[
      #date
    ]]
  }

  if abstract != none {
    block(inset: 2em)[
    #text(weight: "semibold")[Abstract] #h(1em) #abstract
    ]
  }

  if toc {
    pagebreak()
    
    block(above: 0em, below: 2em)[
    #outline(
      title: auto,
      depth: none
    );
    ]
  }

  if cols == 1 {
    doc
  } else {
    columns(cols, doc)
  }
}
```
