### DISCUSSION TITLE
Page-footer only appear in the first html (index.qmd)

### DISCUSSION THREAD

**Discussion by ManuelSpinola** [quarto-dev/quarto-cli#11924] [Q&A]
### Description

Page-footer only appear in the first html (index.qmd), in others html the text is displayed but the image is not.

My _quarto.yml:

````
project:
  type: website
  render: 
    - "*.qmd"
    - "!contenido/articulos/2021-03-09-iucn-red-list"
    - "!contenido/blog/posts/2021-03-08-species-occurrences"
    - "!contenido/blog/posts/2021-03-09-iucn-red-list"
    - "!contenido/blog/posts/2021-03-28-metricas-del-paisaje"
    - "!contenido/blog/posts/2021-07-21-clusters-del-paisaje"

website:
  title: "Observatorio de Vida Silvestre y Biodiversidad - ICOMVIS - UNA - Costa Rica"
  site-url: https://mspinola-icomvis-ovs-website.netlify.app
  page-footer:
    left: Una iniciativa del ICOMVIS  ![ICOMVIS](imagenes/logo_ICOMVIS.jpg){fig-alt="ICOMVIS" width=45px}
    right: Universidad Nacional, Costa Rica ![UNA](imagenes/logo_UNA.jpg){fig-alt="UNA" width=65px}

````
