### DISCUSSION TITLE
In quarto book, how can I refer to appendices as "attachments"?

### DISCUSSION THREAD

**Discussion by bergsmat** [quarto-dev/quarto-cli#11950] [Q&A] [answered]
### Description

I'm using Quarto 1.6.39 with RStudio 2024.12.0 and R 4.4.2.

I created an instance of the quarto book template.  I revised `_quarto.yml` like this:

```
project:
  type: book
book:
  title: "title"
  author: "Norah Jones"
  date: "1/24/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
  appendices:
    - summary.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc: true
crossref:
  appendix-title: "Attachment"
  appendix-delim: ":"
```
In `index.qmd` I added "See @sec-summary."  I changed the first line of `summary.qmd` to 
```
# Summary {#sec-summary}
```
In the resulting pdf, Summary is indeed an appendix, and the link from `index.qmd` finds it.  But I don't see the word "Attachment" anywhere in the document.  This looks like #2345, which was closed in favor of #2356, which seems to have been addressed in #7320.  Elsewhere I learned that 
```
language: 
  section-title-appendices: "Attachments"
```
will change "Appendices" to "Attachments" in the table of contents.  Perhaps there is more help like this, but I can no longer locate the source.

Thanks in advance!

**Comment by mcanouil** [comment, marked as answer]
There are different things here: the prefix/title used for cross-reference and the title used for the sections, all these are defined in `_language.yml` (and other languages): https://quarto.org/docs/authoring/language.html

For instance, with the following I get "Attachment" everywhere.

```yml
language:
  crossref-apx-prefix: Attachment
  section-title-appendices: Attachment
```

What troubles me is:

```yml
crossref:
  appendix-title: "App."
  appendix-delim: ":"
```

from <https://quarto.org/docs/books/book-structure.html#parts-appendices>.

The above code does not seem to have any impact at all on anything.
Does the `crossref:` code do something for you?
