### DISCUSSION TITLE
How do I render and publish via Github actions using Chrome headless?

### DISCUSSION THREAD

**Discussion by serkor1** [quarto-dev/quarto-cli#11966] [Q&A]
### Description

Hi,

In my latest Github action I got this error:

```yaml
ERROR: Couldn't find open server.
Chrome process error: Old Headless mode has been removed from the Chrome binary. Please use the new Headless mode (https://developer.chrome.com/docs/chromium/new-headless) or the chrome-headless-shell which is a standalone implementation of the old Headless mode (https://developer.chrome.com/blog/chrome-headless-shell).



Stack trace:
Chrome process error: Old Headless mode has been removed from the Chrome binary. Please use the new Headless mode (https://developer.chrome.com/docs/chromium/new-headless) or the chrome-headless-shell which is a standalone implementation of the old Headless mode (https://developer.chrome.com/blog/chrome-headless-shell).


    at criClient (file:///opt/quarto/bin/quarto.js:38718:15)
    at eventLoopTick (ext:core/01_core.js:214:9)
    at async file:///opt/quarto/bin/quarto.js:38676:22
    at async Semaphore.runExclusive (file:///opt/quarto/bin/quarto.js:38350:29)
    at async Object.createPngsFromHtml (file:///opt/quarto/bin/quarto.js:38947:42)
    at async makePng (file:///opt/quarto/bin/quarto.js:82312:70)
    at async makeDefault (file:///opt/quarto/bin/quarto.js:82372:24)
    at async Object.cell (file:///opt/quarto/bin/quarto.js:82395:20)
    at async Promise.all (index 0)
    at async Object.document (file:///opt/quarto/bin/quarto.js:39242:25)
Error occurred during cleanup: NotFound: ESRCH: No such process
```

I tried to switch to `1.7.x`, but this did not solve my issue. @gadenbuie suggested that I set envvar `QUARTO_CHROME_HEADLESS_MODE=new`, which produced the same error. My repository structure, are given below:

```
Repository/
├─ docs/
│  ├─ _environment
│  ├─ _quarto.yaml
```

The part of the yaml-file that renders and publishes are given below:

```yaml
      - name: Render docs
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: docs/
          
      - name: Publish docs
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs/
          render: false
```

What is the cause of this error? And how do I solve it?
