### DISCUSSION TITLE
Why doesn't pdf title reflect title in _quarto.yml? I get "Quarto Basics" unless I use a partial template.

### DISCUSSION THREAD

**Discussion by brittAnderson** [quarto-dev/quarto-cli#11969] [Q&A] [answered]
### Description

This is the top of my _quarto.yml.  When I export to html I get the title I expect, but when I render pdf it uses a title "Quarto Basics" that must come from some template somewhere. Why doesn't quarto use the same title for both? It uses this title for the title of the pdf, but not the title page of the book output in pdf. I had to add a partial template to get the title I wanted. 

```
project:
  type: book
  output-dir: ../docs

book:
  title: "P390"
  author: "Britt Anderson"
```

**Comment by mcanouil** [comment]
I cannot reproduce your claim, so with no more information than a partial `_quarto.yml`, I have to guess the issue lies in your project.

I created a simple project with `quarto create project book demo demo`, changed `title` in `_quarto.yml` and get the proper result:

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/49dfc9b1-7180-4b2a-8830-328e393a0502" />


Note that using the following code means Quarto won't cleanup `../docs`, so everything previously rendered and not replaced by new files will remain there until YOU clean up this directory.
Quarto only cleans `output-dir` if it's inside the project as a safety.

```
project:
  output-dir: ../docs
```

**Comment by brittAnderson** [comment]
Here is the full _quarto.yml. Without the partial template at the end I get "Quarto Basics" in the title field everytime. 

```
project:
  type: book
  output-dir: ../docs

book:
  title: "P390"
  author: "Britt Anderson"
  date: "Winter 2025"
  cover-image: p390cover.png
  sidebar: 
    search: true  
  chapters:
    - index.qmd
    - intro.qmd
    - cCmpResTool.qmd
    - cOpenResearch.qmd
    - cCode.qmd
    - cWriting.qmd
    - cExps.qmd
    - cBiblio.qmd
    - cServer.qmd
    - cLLM.qmd
    - cDatabase.qmd
    - summary.qmd
  appendices:
    - cGit.qmd
    - cOSX.qmd
    - python-venv.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    template-partials: 
      - title.tex
    
engine: knitr
```
