### DISCUSSION TITLE
Shorten title in PDF headers - Header PDF

### DISCUSSION THREAD

**Discussion by Ppantaleo** [quarto-dev/quarto-cli#12005] [Q&A] [answered]
### Description

Hi, I export in PDF but when the chapter title is long, the header is wrong, it exceeds the margin. How do I adjust it? Thank you. 

https://github.com/PaideiaPublishingServices/Paideia-Editorial/tree/main/editar-publicar-financiar-ciencia-america-latina

![image](https://github.com/user-attachments/assets/596435da-2ba5-4fa9-a707-04f667b3142d)

**Comment by Steinthal** [comment, marked as answer]
If you change  the PDF format definition in ```_quarto.yml``` then the text is wrapped inside a ```\parbox```:

``` yaml
  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    number-sections: false
    latex-engine: lualatex
    include-in-header:
      text: |
        \usepackage[automark]{scrlayer-scrpage}
        \pagestyle{scrheadings}
```

![Screenshot 2025-02-02 at 00 42 53@2x](https://github.com/user-attachments/assets/a3ccb666-60e4-439b-bbb7-8ec244d7139e)
