### DISCUSSION TITLE
How to change figure size in beamer format with jupyter notebook?

### DISCUSSION THREAD

**Discussion by gVallverdu** [quarto-dev/quarto-cli#12062] [Q&A] [answered]
### Description

Hello

I work in a jupyter notebook to write a document and produce the output with quarto. I use the beamer format for output.

In python cells, I produce figure with:

```python
#| output: true
 
fig, ax = plt.subplots()

ax.plot(bla bla ...)
```

My issue is that in the beamer, figures seems to be scaled in order to fit the maximum width.

I tried several options in the yaml frontmater without success, for example:

* `fig-width: 2`
* `fig-height: 2`
* `out.width: "50%"`

Hereafter is the frontmater I am using:

```yaml
---
title: "A very nice title"
date: "January 2025"
execute:
  echo: false
  output: false
editor:
  render-on-save: false
format:
    beamer:
        slide-level: 2
        fig-align: "center"
        fig-width: 2
        pdf-engine: pdflatex
---
```

I tried both to produce the pdf from quarto preview of vscode or directly from the command line with the same result.

I tried also to change in matplotlib the figure size with something like:

```python
#| output: true
 
fig, ax = plt.subplots(figsize=(4, 2))

ax.plot(bla bla ...)
```

but I still got a figure that fit the page width:

<img width="774" alt="image" src="https://github.com/user-attachments/assets/b68b4088-44f7-4e73-808d-2d2bcf41bfa1" />

I take a look to the tex output, using `quarto render mynb.ipynb --to latex`.
For each figure there is a `\pandocbounded` macro, which seems to be new (few months). Maybe this macro cancel any option such as `fig-height` or others.

I am pretty new to quarto so there is maybe something I am missing in the workflow. The execution of the whole notebook take a while so I don't want to execute everything on render.

Thank you in advance.

Additional information:

* editor: vscode
* quarto version: 1.6.40
