### DISCUSSION TITLE
Is it possible to distribute python filters?

### DISCUSSION THREAD

**Discussion by acederberg** [quarto-dev/quarto-cli#12084] [Q&A]
### Description

Hi!

I could probably test this quickly but I think it is a worthwhile discussion. I looked and I didn't see any discussion about this directly so I decided I'd ask.

Is it possible to distribute filters in a language other than ``lua``.
Of course, I assume adding additional dependencies might require more work out of the user *(in my case `s3cmd` and `panflute` would be required by `python`)* and it should not be a feature ``quarto`` to handle the deps. However, it would be good enough to specify the deps in a file included by the extension (e.g. just include `requirements.txt` with the extension, in the case of `python`).

I see [in distributing a ``lua`` file is not necessarily required](https://quarto.org/docs/extensions/distributing.html) so I am wondering if I could do something like

```yaml
title: My Filter
author: Cooltools
version: 1.0.0
quarto-required: ">=1.2.0"
contributes:
  filters:
    - my-filter.py
```

for a ``python`` filter.
