### DISCUSSION TITLE
Adding new custom properties into template-partials (i.e. supervisor to the page title)

### DISCUSSION THREAD

**Discussion by danieltomasz** [quarto-dev/quarto-cli#12099] [Q&A]
### Description

I found serveral discussion about partials, but nowhere I cannot find how to  pass new  custom propereties to partials. I want to modify only the titlepage in the book  project  how can I correctly pass it with minimal changes/code boilerplate?

My example `title.tex`:
```tex
$if(title)$
\title{$title$$if(thanks)$\thanks{$thanks$}$endif$}
$endif$

$if(subtitle)$
$if(beamer)$
$else$
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
$endif$
\subtitle{$subtitle$}
$endif$

\author{$for(authors)$$it.name.literal$$sep$ \and $endfor$}

\date{$date$}

$if(supervisor)$
\newcommand{\supervisor}{\textbf{Supervisor:} $supervisor$}
$endif$

$if(dissertation_details)$
\newcommand{\dissertationdetails}{$dissertation_details$}
$endif$

$if(beamer)$
$if(institute)$
\institute{$for(institute)$$institute$$sep$ \and $endfor$}
$endif$
$if(titlegraphic)$
\titlegraphic{\includegraphics$if(titlegraphicoptions)$[$for(titlegraphicoptions)$$titlegraphicoptions$$sep$, $endfor$]$endif${$titlegraphic$}}$endif$
$if(logo)$
\logo{\includegraphics{$logo$}}
$endif$
$endif$

\begin{titlepage}
\begin{center}

{\Huge \textbf{$title$}}\\[0.5cm]

{\Large \textit{$subtitle$}}\\[1.5cm]

\textbf{$dissertation_details$}\\[0.5cm]

\supervisor\\[2cm]

\textbf{Author:} $for(authors)$$it.name.literal$$sep$ \and $endfor$\\[0.5cm]

\vfill
{\Large \textbf{$date$}}

\end{center}
\end{titlepage}
```
with the `_quarto.yml`

```
project:
  type: book

book:
  title: "My thesis"
  author: "John Kowalski"
  supervisor: "Prof. Dr. Adam Smith"
  dissertation_details: "A dissertation submitted to  University X in partial fulfilment of the requirements for the degree of Doctor of Philopsophy"
  chapters:
    - index.qmd
  output-file: "book"
  search: true


format:
  pdf:
    documentclass: book
    classoption: [oneside, 12pt]
    link-citations: true
    urlcolor: blue
    toclinkcolor: blue
    number-sections: true
    pdf-engine: lualatex
    toc-depth: 2
    template-partials:
      - title.tex

date-format: YYYY-MM-DDTHH:mm:ssZ
date: last-modified
```

I dont know how to pass `supervisor` and `dissertation_details` into pandoc to use in my `title.tex`

**Comment by danieltomasz** [comment]
the `title.tex` is probably wrong, but I want to learn about something related to this issue https://github.com/quarto-dev/quarto-cli/issues/3919

**Reply by danieltomasz** [reply]
I found a good intro, so probaly I will be able to fix this myself https://www.youtube.com/watch?v=TgauMpdgPVk

**Reply by Steinthal** [reply]
Did you manage to fix it yourself?
If not, here's how it looks like and some remarks:
![Screenshot 2025-02-18 at 18 34 36@2x](https://github.com/user-attachments/assets/114fd094-83c9-4806-9375-aa3e34ef4b48)


Remarks:
- As mentioned by **cderv** below, you need to to provide "supervisor" and "dissertation_details" as first level metadata:
```yaml
format:
  pdf:
    documentclass: book
    classoption: [oneside, 12pt]
    link-citations: true
    urlcolor: blue
    toclinkcolor: blue
    number-sections: true
    pdf-engine: lualatex
    toc-depth: 2
    template-partials:
      - before-body.tex

supervisor: "Prof. Dr. Adam Smith"
dissertation_details: "A dissertation submitted to  University X in partial fulfilment of the requirements for the degree of Doctor of Philopsophy"
```
- Instead of ```title.tex```, you need to define the title page in ```before-body.tex```:
``` latex
$if(has-frontmatter)$
\frontmatter
$endif$
$if(title)$
$if(beamer)$
\frame{\titlepage}
$else$
%\maketitle %<<< deactivate the generation of the default title page
\begin{titlepage}
  \begin{center}
    
  {\Huge \textbf{$title$}}\\[0.5cm]
    
  {\Large \textit{$subtitle$}}\\[1.5cm]
    
  $if(dissertation_details)$
  \textbf{$dissertation_details$}\\[0.5cm]
  $endif$

  $if(supervisor)$
  {\textbf{Supervisor:} $supervisor$}\\[2cm]
  $endif$
    
  \textbf{Author:} $for(authors)$$it.name.literal$$sep$ \and $endfor$\\[0.5cm]
    
  \vfill
  {\Large \textbf{$date$}}
    
  \end{center}
\end{titlepage}
$endif$
$if(abstract)$
\begin{abstract}
$abstract$
\end{abstract}
$endif$
$endif$
```
