### DISCUSSION TITLE
How to automatically generate the pdf format (quarto revealjs) using Github Actions ?

### DISCUSSION THREAD

**Discussion by ddotta** [quarto-dev/quarto-cli#12106] [Q&A] [answered]
### Description

Hello,

I have several Github repositories that include quarto files (revealjs presentation) and I'm currently using Quarto CLI to publish to Github Pages.
Example : https://github.com/SSM-Agriculture/formation-R-perf-02-fonctions
Instead, I'd like to use an automated approach (inspired by this great article: https://mickael.canouil.fr/posts/2024-12-30-quarto-github-pages/).

The question I'm asking myself is how to automatically generate the associated presentations in pdf format?

Do you have any examples of github repositories that do this to give me some inspiration?

Thanks in advance !

**Comment by mcanouil** [comment, marked as answer]
You can see an example with multi-formats rendering, which is a workaround to some issues about files conflicts, cleaning, etc. at [Quarto highlight-text extension "deploy" GitHub Action](https://github.com/mcanouil/quarto-highlight-text/blob/main/.github/workflows/deploy.yml).

Note that in your case you could simply add the `pdf` format as a target format in your default project:

- https://github.com/SSM-Agriculture/formation-R-perf-02-fonctions/blob/main/_quarto.yml#L4-L5

Note that, PDF (LaTeX) and Reveal.js should work well together (they don't step on each other feet when cleaning files).
If you have issues with `quarto render` you can iterate on the format with `--to <format>`.

**Comment by cderv** [comment]
> The question I'm asking myself is how to automatically generate the associated presentations in pdf format?

Just in case you are referring to PDF version of your slide, as a Print of the HTML to the PDF, then you need to use at tools that print to PDF like [`decktape`](https://github.com/astefanutti/decktape). If you find this Discussion forum you'll find some snippet of what could be used. 

Decktape provide a docker container which could help using it in Github action for example. 

Anyhow, this is generic scripting. Quarto has no command to print to pdf from revealjs slide or any html format. 
Only rendering to PDF through LaTeX or Typst is possible. (and in this case see above answer)

Hope it helps

**Comment by ddotta** [comment]
Thank you both @mcanouil and @cderv  for your answers.  
Yes I want to get a pdf version of my slides.  
I'll try to use `decktape`and hope I'll succeed 🤞

**Reply by mcanouil** [reply]
To be clear, my answer was about to generate a PDF version as target format not to save the Reveal.js HTML as PDF.

**Reply by ddotta** [reply]
Yes I get it, I'll try to find a repo to take example from that uses decktape to get a printable pdf version from html

**Reply by mcanouil** [reply]
You could searching in this Discussion platform first.
For example, there is this:

- https://github.com/quarto-dev/quarto-cli/discussions/7018#discussioncomment-8276855

**Reply by ddotta** [reply]
Thanks it's super useful!  
Do you know if there is something that can be integrated directly into Github actions?

**Reply by mcanouil** [reply]
Everything or almost, can be integrated in GitHub Action.

**Reply by cderv** [reply]
> Do you know if there is something that can be integrated directly into Github actions?

I think decktape repo shows example (or you can find online block) on how to use the decktape docker image to print HTML within github action workflow

**Reply by mcanouil** [reply]
If I had to write a GHA workflow it would be roughly like (obviously not tested at all, especially the last step):

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Decktape
        shell: bash
        run: npm install -g decktape

      - name: Build PDF
        shell: bash
        run: decktape [options] [command] <url> <filename>
```


Source: https://github.com/astefanutti/decktape

**Reply by ddotta** [reply]
Thanks again @cderv and @mcanouil you're awesome!

**Reply by mcanouil** [reply]
FYI, the workflow above works quite nicely (at least locally) and will look like this more realistically:

```yaml
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          tinytex: false
      
      - name: Render Quarto Project
        shell: bash
        run: quarto render index.qmd

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Convert Reveal.js to PDF
        shell: bash
        run: npx -y decktape reveal --size "1920x1080" index.html index.pdf
```

Here is a slight variation to take screenshot of the title slide:

https://github.com/mcanouil/quarto-revealjs-coeos/blob/main/.github/workflows/deploy.yml
