### DISCUSSION TITLE
quarto_render function ignores typst-template.typ file

### DISCUSSION THREAD

**Discussion by grousell** [quarto-dev/quarto-cli#12111] [Q&A] [answered]
### Description

I have a fully formatted Quarto doc with colors, logos etc. using typst-template.typ and typst-show.typ files. It
creates a beautiful PDF document when I click Render in RStudio - however when I run quarto::quarto_render() function, it creates the document but without any of the formatting from the .typ files. All of the files are in the top level of the working directory.

Here is the YAML and sample text from the document:

```
---
title: "TITLE"
subtitle: "Subtitle"
format:
  typst:
    template-partials:
      - typst-template.typ
      - typst-show.typ
shortcodes:
  - colbreak.lua
keep-typ: true
execute:
  echo: false
---


```
and here is the R code:

```
quarto::quarto_render(
  input = "test.qmd", 
  output_format = "pdf", 
  output_file = "test_report.pdf"
)
```
