### DISCUSSION TITLE
How to include a PDF file as an appendix?

### DISCUSSION THREAD

**Discussion by roaldarbol** [quarto-dev/quarto-cli#12169] [Q&A] [answered]
### Description

I have a thesis where I would like to add a PDF file (a manuscript) as an appendix. However, I am struggling to find a way to do it. I've tried to place the PDF file directly in `_quarto.yml` under `appendix`, and I've tried `{{< include my.pdf >}}` which just completely stalls my system.

Here's a minimal example consisting of three files in the same folder:
`_quarto.yml`:
```yml
project:
  type: book
  output-dir: _book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "5/9/2021"
  chapters:
    - index.qmd
  appendices: 
    - appendix.qmd

format:
  pdf:
    documentclass: scrreprt
```

---

`index.qmd`:
```qmd
Hi there
```

---

`appendix.qmd`:
```qmd
{{< include my.pdf >>}}
```

where `my.pdf` points to a PDF in the some folder
