### DISCUSSION TITLE
Add a button to website navbar

### DISCUSSION THREAD

**Discussion by juliasilge** [quarto-dev/quarto-cli#12196] [Q&A] [answered]
### Description

I am wanting to add a button in the navbar of a Quarto website. If I create a website using `quarto create project website button-in-navbar`, I can edit the project YAML like this to make a button:

```yaml
project:
  type: website

website:
  title: "button-in-navbar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://quarto.org/
        text: "<span class='btn btn-primary'>Click here</span>"
      - href: about.qmd
        text: About us     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

```

That _does_ make a button, but the vertical alignment is not good:

![Screenshot 2025-03-03 at 8 53 00 AM](https://github.com/user-attachments/assets/0bf6acff-e7ea-4ea3-8da8-dbd9a63a6cb1)

Notice how "Home" and "About us" are too high, while the title and button are vertically aligned nicely. I tried using `vertical-align: middle` for various styles, but could not figure out how to make that apply to the links in the navbar.

How might I go about improving the vertical alignment in the navbar in this case?
