### DISCUSSION TITLE
revealjs refresh browser between slides

### DISCUSSION THREAD

**Discussion by antoine4ucsd** [quarto-dev/quarto-cli#12207] [Q&A] [answered]
### Description

Hello
I created a quarto slidedeck with revealjs but the aspect of the plot is not rendering well. I have to refresh my browser between slides to make sure the plot dimension is properly displayed
Plots are being generated with echarts4r.

before refreshing:
![Screenshot 2025-03-04 at 15-24-48 🇨🇩 EVD Survivor Program in DRC](https://github.com/user-attachments/assets/15f60eab-ef6f-4d9e-abb1-e84f5c0b2b87)

and after refreshing my browser

![Screenshot 2025-03-04 at 15-25-34 🇨🇩 EVD Survivor Program in DRC](https://github.com/user-attachments/assets/0385fa76-75cd-4f12-8197-ca6ca1e7684b)

I tried various yaml options such as 
```

format:
  unhcr-revealjs:
    width: 1280
    height: 720
    auto-fit: true
    slide-layout: auto-stretch
    show-slide-number: print
```

not sure how to fix it
