### DISCUSSION TITLE
Project which doesn't support project wide previewing unless there is an 'index' file present.

### DISCUSSION THREAD

**Discussion by rgaiacs** [quarto-dev/quarto-cli#12227] [Q&A]
### Description

I'm working on a [project type extension](https://quarto.org/docs/extensions/project-types.html) for a website. When I run

```bash
quarto preview
```

the output is

```
ERROR: The project '' is a default type project which doesn't support project wide previewing unless there is an 'index' file present.

Please preview an individual file within this project instead.

Stack trace:

Please preview an individual file within this project instead.
    at serveProject (file:///opt/quarto/bin/quarto.js:108009:23)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Command.actionHandler (file:///opt/quarto/bin/quarto.js:108751:9)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8253:13)
    at async Command.parseCommand (file:///opt/quarto/bin/quarto.js:8143:20)
    at async quarto (file:///opt/quarto/bin/quarto.js:127391:9)
    at async file:///opt/quarto/bin/quarto.js:127418:9
    at async file:///opt/quarto/bin/quarto.js:127273:20
    at async mainRunner (file:///opt/quarto/bin/quarto.js:127275:9)
    at async file:///opt/quarto/bin/quarto.js:127409:5
```

If I change my `_quarto.yml` from

```yaml
project:
  type: mwe
```

to

```
project:
  type: mwe

format: hugo-md
```

and I re-run `quarto preview`, the command work as expected.

Is possible to tell the extension to skip the ´index` check like the Hugo extension does? Thanks!

# Extension

The error happens with a copy of the [Hugo extension](https://github.com/quarto-dev/quarto-cli/blob/4ca63a77b9f4b89621c7ed822a6612c6f298c9d2/src/resources/extensions/quarto/hugo/_extension.yml) that has a different name and related format name.

## `_extensions/mwe/_extension.yml`

The only change is in `contributes.project.format` from `hugo-md` to `mwe-md`.

```yaml
title: Hugo
author: RStudio, PBC
organization: quarto
contributes:
  project:
    project:
      type: default
      detect:
        - ["hugo.toml", "content"]
        - ["config.toml", "content"]
        - ["config/_default/config.toml", "content"]
      render:
        - "**/*.qmd"
        - "**/*.ipynb"
      preview:
        serve:
          cmd: "hugo serve --port {port} --bind {host} --navigateToChanged"
          env:
            HUGO_RELATIVEURLS: "true"
          ready: "Web Server is available at"
    format: mwe-md
  formats:
    md:
      variant: gfm+yaml_metadata_block+definition_lists+smart
      prefer-html: true
      fig-format: retina
      fig-width: 8
      fig-height: 5
      wrap: preserve
```

# Output of `quarto check`

```
Quarto 1.7.14
[✓] Checking environment information...
      Quarto cache location: /home/raniere/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.7.14
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking Chrome Headless....................OK
      Chrome:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.13.2
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.3
      Path: /usr/lib/R
      LibPaths:
        - /home/raniere/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.49
      rmarkdown: 2.29

[✓] Checking Knitr engine render......OK
```
