### DISCUSSION TITLE
revealJS slides size in web browser - layout

### DISCUSSION THREAD

**Discussion by antoine4ucsd** [quarto-dev/quarto-cli#12281] [Q&A]
### Description

Hello
I created a slide deck with revealJS 
I have problems with the width/height and how the slides appear in the web browser. it varies between screens, computers and also using the same screen when resizing the browser tab.
for example, below the slide is off and half of the second plot is cutt
![Screenshot 2025-03-13 at 8 43 41 AM](https://github.com/user-attachments/assets/08f298fd-bc5d-4006-9ff9-1f4c0ff54512)

I used 

```{r}
#| fig-height: 3.6
#| fig-width: 10
plt1
```

```{r}
#| fig-height: 3.6
#| fig-width: 10
plt2
```

but if I resize my browser (half of my screen width), it will look nice

![Screenshot 2025-03-13 at 8 43 51 AM](https://github.com/user-attachments/assets/d883b84a-4ea3-48b1-911b-4ca18f39e33d)

in yaml, I have this
```
format:
  unhcr-revealjs:
    view-distance: 15
    width: 1280
    height: 720
    footer: "As of 2025, week 9"
    slide-number: true
    slide-layout: auto-stretch
    show-slide-number: print
    pdf-separate-fragments: true
    embed-resources: true

```

any ways to make sure the content always shows up regardless of screen or brower width? and consistent across all slides?
THANK YOU!
