### DISCUSSION TITLE
How do I create a title page using typst and quarto markdown?

### DISCUSSION THREAD

**Discussion by Amogh-Joshi** [quarto-dev/quarto-cli#12287] [Q&A]
### Description

I want to create a title page. The end product is "pdf". I found a title page that I like: https://typst.app/project/rMobzKMab8wdFrb_MWiW0z 

My question is: How do I use this as a template? I've looked at a couple of videos (e.g., using _brand.yml) but I don't get it. Help? 

````
---
title: "Exploring Typst Workflow"
author: "Test"
date: "`r Sys.Date()`"
format:
  typst:
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-indent: 1.5em
    papersize: us-letter
    margin:
      x: 1cm
      y: 1cm
---

# Introduction

This report analyzes the **Gapminder dataset**, focusing on **GDP per capita**, **life expectancy**, and **population trends** over time.


```{r}
#| include: false

# Load required libraries
library(tidyverse)
library(gapminder)


```

The plot below shows the relationship between GDP per capita and life expectancy.

```{r}
#| echo: false

ggplot(gapminder, aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point(alpha = 0.7) +
  scale_x_log10() +  # Log scale for better visualization
  labs(title = "GDP per Capita vs. Life Expectancy",
       x = "GDP per Capita (log scale)",
       y = "Life Expectancy") +
  theme_minimal()

```


# Conclusion

The plot above illustrates the relationship between GDP per capita and life expectancy across different continents. The following observations can be made:
- Countries with higher GDP per capita tend to have higher life expectancy.
- Life expectancy has generally increased over time in most countries.
- The wealthiest countries in 2007 had GDP per capita exceeding $40,000.

````

**Comment by mcanouil** [comment]
Could you properly format your post using code blocks for code and terminal outputs? Thanks.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.
See <https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us>.

you really should not be doing that in Quarto.

```yaml
date: "`r Sys.Date()`"
```

Use the native feature instead: https://quarto.org/docs/reference/dates.html

To customise the templates, see the partials/templates documentation: https://quarto.org/docs/journals/templates.html

**Reply by Amogh-Joshi** [reply]
I've edited the post. I've made a note about the date. Thanks for that. 

I _don't get template partials._ Specifically, how do I exactly create a title page? 

This is the code for title page I found online. 
```typ
#let title-page(title:[], email:[], osid:[], fill: yellow, body) = {
  set page(fill: rgb("#FFD700"), margin: (top: 1.5in, rest: 2in))
  set text(font: "Source Sans Pro", size: 14pt)
  set heading(numbering: "1.1.1")
  line(start: (0%, 0%), end: (8.5in, 0%), stroke: (thickness: 2pt))
  align(horizon + left)[
    #text(size: 24pt, title)\
    #v(1em)
    OSEE Exam Report
    #v(2em)
    #link(email), OSID: #osid
  ]
  
  align(bottom + left)[#datetime.today().display()]
  pagebreak()
  set page(fill: none, margin: auto)
  align(horizon, outline(indent: auto))
  pagebreak()
  body
}

#show: body => title-page(
  title: [Offensive Security Exploitation \ Expert Exam Report],
  email: "mailto: student@youraddress.com",
  osid: [XXXX],
  body
)
```

**Reply by mcanouil** [reply]
Do you understand/know Typst? If not, this is unfortunately not the place to learn it. Read Typst documentation to understand how to structure a document.

Look at the default template or the partials (limited for Typst right now) which allow to modify only a part of a the template.

Finally, look at Quarto extensions such as https://github.com/quarto-ext/typst-templates or other Typst extensions listed on https://m.canouil.dev/quarto-extensions/#category=typst

**Reply by gordonwoodhull** [reply]
#11710 might give you an idea of which templates you need to modify (and should make what you want to do easier,  when it is merged).

**Reply by Amogh-Joshi** [reply]
I don't know typst that well but my issue is that I'm not able to use existing templates in quarto. I was able to get this working: 

cover-page.typ 
```typ
#let title-page(title: [], author: [], body) = {
  set page(fill: rgb("#FFD700"), margin: (top: 1.5in, rest: 2in))
  set text(font: "Source Sans Pro", size: 14pt)
  set heading(numbering: "1.1.1")
  line(start: (0%, 0%), end: (8.5in, 0%), stroke: (thickness: 2pt))
  
  align(horizon + left)[
    #text(size: 24pt, title)
    #v(1em)
    #text(size: 16pt, author) 
    #v(2em)
  ]
  
  align(bottom + left)[#datetime.today().display()]
  pagebreak()
  set page(fill: none, margin: auto)
  align(horizon, outline(indent: auto))
  body
}

#show: body => title-page(
  title: [$title$],
  author: [$author$],
  body
)
```

The QMD File. 
````
---
title: "Exploring Typst Workflow"
author: "AJ"
date: today
format:
  typst:
    template: cover_page.typ
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-indent: 1.5em
    papersize: us-letter
    margin:
      x: 1cm
      y: 1cm
---

# Introduction

This report analyzes the **Gapminder dataset**, focusing on **GDP per capita**, **life expectancy**, and **population trends** over time.


```{r}
#| include: false

# Load required libraries
library(tidyverse)
library(gapminder)


```

The plot below shows the relationship between GDP per capita and life expectancy.

```{r}
#| echo: false

ggplot(gapminder, aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point(alpha = 0.7) +
  scale_x_log10() +  # Log scale for better visualization
  labs(title = "GDP per Capita vs. Life Expectancy",
       x = "GDP per Capita (log scale)",
       y = "Life Expectancy") +
  theme_minimal()

```


# Conclusion

The plot above illustrates the relationship between GDP per capita and life expectancy across different continents. The following observations can be made:
- Countries with higher GDP per capita tend to have higher life expectancy.
- Life expectancy has generally increased over time in most countries.
- The wealthiest countries in 2007 had GDP per capita exceeding $40,000.
````

The issue is that the body isn't being shown. Unfortunately, there aren't any resources except the typst website and even there I don't see any tutorials to customize stuff (when compared to how I can use CSS to do detailed customization). Since my output is pdf, I want to use typst (instead of Latex).
