### DISCUSSION TITLE
when using double brackets for code , highlight doesn't work

### DISCUSSION THREAD

**Discussion by ggous** [quarto-dev/quarto-cli#1228] [Q&A]
Hi, 

If I use highlight style:

```
format:
  html:
    theme: cosmo
  pdf:
    include-before-body: 
        - colors.tex
    documentclass: scrreprt
    code-block-bg: true
    code-block-border-left: "#E9E9E9"
    keep-tex: true
    highlight-style: tango
```

and use double brackets for python code that I don't want to run:

`{{python}}`

 then the highlight style doesn't work.

Is there any workaround for this?

**Comment by dragonstyle** [comment]
Hi,

The example that you provided has the `highlight-style` set only under the the `pdf` format. If you'd like that style to apply to all formats, just move the key out to the root, like so:

````
---
format:
  html:
    theme: cosmo
  pdf:
    include-before-body: 
        - colors.tex
    documentclass: scrreprt
    code-block-bg: true
    code-block-border-left: "#E9E9E9"
    keep-tex: true
highlight-style: vim-dark
---

```{{python}}
foo = 1 + 1
```
````

**Reply by cderv** [reply]
Also just a note but 
```
    code-block-bg: true
    code-block-border-left: "#E9E9E9"
```

Is this not only for HTML output ? In the example above, these keys are provided in pdf too. Not sure they will work there to style PDF code blocks

**Comment by ggous** [comment]
Hi! Regarding the first answer.

I moved `highlight-style: tango` out of pdf and it still doesn't highlight code.

For the second answer, using the 

```
code-block-bg: true
code-block-border-left: "#E9E9E9"
```
results in changing the code background, but does not show the vertical color line at left! 
I couldn't find a way to use both! (for pdf)

Thanks!

**Reply by cderv** [reply]
Color is shown on the left for me : 
![image](https://user-images.githubusercontent.com/6791940/175956597-55d87a4c-b59a-44e9-8bc5-4329f00d842f.png)
`#E9E9E9` is light grey which you see on the side. 

This is using 
````yaml
format:
  html:
    theme: cosmo
    code-block-bg: true
    code-block-border-left: "#E9E9E9"
highlight-style: tango
````

Changing highlight style is working also 
````
format:
  html:
    theme: cosmo
    code-block-bg: true
    code-block-border-left: "#E9E9E9"
  pdf:
    keep-tex: true
highlight-style: vim-dark
````

Gets me this for PDF
![image](https://user-images.githubusercontent.com/6791940/175957127-cc94d54f-524e-470b-8317-6682b45a6162.png)

and this for HTML
![image](https://user-images.githubusercontent.com/6791940/175957772-7031af57-52a8-41e6-a290-061ca523fe36.png)

because `code-block-bg: true` is set which I believe will use bootstrap background instead of highlight one. Without it I correctly get the same highlight style
![image](https://user-images.githubusercontent.com/6791940/175958105-c3541082-f5be-4ee1-87d7-2f4d01f677f8.png)

(@dragonstyle is this expected that `code-block-bg: true` overrides highlight style background ?)


What are you expecting exactly ? Can you share a reproducible document with code blocks you are comparing ? Probably one with `{python}` and another with `{{python}}` ? Giving an example or illustration is the best way for us to really understand what you found. 
Thanks!

**Comment by ggous** [comment]
Ok, thanks for the answer.

Here is a small sample:

test.qmd

```{python}
def calc(x):
    return 2 * x + sum(x)
```

``` {python}}
def another(x):
    2 * x + 1 + sum(x)
```

and _quarto.yml:

```
project:
  type: book

book:
  title: "Ml"
  author: "George"
  date: "6/24/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - test.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    include-before-body: 
        - colors.tex
    documentclass: scrreprt
    code-block-bg: true
    code-block-border-left: "#E9E9E9"
    keep-tex: true
highlight-style: tango
editor: visual
```

colors.tex
```

\definecolor{cadmiumgreen}{rgb}{0.0, 0.42, 0.24}
\definecolor{ao(english)}{rgb}{0.0, 0.5, 0.0}
```

And here is a screenshot of the result:


![test](https://user-images.githubusercontent.com/89124942/176104519-65c73904-ce79-40f5-b2e1-427d9ab0501c.png)


As you can see, the second code which is commented, isn't highlighted.

Now, If I use for example:

```
code-block-bg: "#E9E9E9"
code-block-border-left: "#5D8AA8"
```
which is a gray background and a blue line, I receive:


![blue](https://user-images.githubusercontent.com/89124942/176105189-1cf7055e-97ce-4d99-96a1-13a1e2ba96cc.png)

I would expect the gray background and the blue line left.
