### DISCUSSION TITLE
Can I use Quarto Live even without live code chunks?

### DISCUSSION THREAD

**Discussion by bensoltoff** [quarto-dev/quarto-cli#12284] [Q&A]
### Description

I am currently dealing with a problem similar to #10544 but instead the output format is `revealjs`. I have a directory of Quarto documents, the majority of which are `format: revealjs`. I use `_metadata.yml` to set custom formatting for all of them.

Some of the slides have interactive code chunks embedded using Quarto Live, so the output format is `format: live-revealjs`. But if I try to set the same formatting options in `_metadata.yml` like

```yml
format:
  revealjs:
    width: 1600
    height: 900
  live-revealjs:
    width: 1600
    height: 900
```

I get the same error as in #10544. I can work around this by setting something like

```yml
format:
  live-revealjs:
    output-file: 14-slides-live.html
    width: 1600
    height: 900
```

in the `live-revealjs` documents, but I would rather not have to since it makes it harder to update the revealjs settings in the future.

As a workaround, I was thinking of switching all the Quarto documents to `format: live-revealjs` whether or not they actually have `webr` code chunks. Then `_metadata.yml` only defines settings for `live-revealjs` and all the documents inherit them. Has anyone tried this? Does it change the rendered slides in any meaningful way using `revealjs` vs `live-revealjs` if you don't have interactive code chunks?
