### DISCUSSION TITLE
Is there a way to "unit test" a quarto project?

### DISCUSSION THREAD

**Discussion by JosephBARBIERDARNAL** [quarto-dev/quarto-cli#12313] [Q&A] [answered]
### Description

Perhaps my question isn't very clear, but I'd like to be able to check that my quarto project isn't broken in the same way that we do unit tests in any software project.

For example, I'd like to test that the `_quarto.yaml` doesn't contain invalid keys/values, that the YAML frontmatter in my `.qmd` files is correct (whatever that means), and so on. There are probably other things that would be relevant to test, but these are the most intuitively (?) important.

Are there any tools built into the CLI? Or extensions that cover this specific topic? I couldn't find any resources after browsing Google.

**Comment by cscheid** [comment, marked as answer]
> For example, I'd like to test that the _quarto.yaml doesn't contain invalid keys/values, that the YAML frontmatter in my .qmd files is correct (whatever that means), and so on.

Quarto includes a validator, so it won't render unless it considers the YAML valid (for its own notion of valid, of course. It won't be able to catch, eg, typos in author names).

If you want to run these yourself, a good way to do it is to add a pre-render script to your quarto project: https://quarto.org/docs/projects/scripts.html#pre-and-post-render. You can also leverage `quarto run` and a Makefile if you don't want the tests to be run at every render. Finally, you might want to run `quarto inspect` in your project, look at the JSON output, and consider incorporating it into your test suite: it has a number of useful things.

**Reply by JosephBARBIERDARNAL** [reply]
The pre-render is exactly what I had in mind! Thanks also for the other information. I think I've got everything I need now.

**Comment by roaldarbol** [comment]
In relation to this, I'm wondering whether it's possible to supply front-matter values from the CLI? That way, especially for template testing, it would be much easier to test each parameter (whether it's missing, correct type, etc.). To me it seems the alternative is to create a bunch of files and run them which seems like a lot more overhead.

**Reply by JosephBARBIERDARNAL** [reply]
I think you can do it with extra params with:

```bash
quarto render file.qmd -P show_week:FALSE
```

So I guess this also exists for built-in params too.

**Reply by mcanouil** [reply]
See `quarto render --help` for the flags about metadata.

**Reply by mcanouil** [reply]
> I think you can do it with extra params with:
> 
> 
> 
> ```bash
> 
> quarto render file.qmd -P show_week:FALSE
> 
> ```
> 
> 
> 
> So I guess this also exists for built-in params too.

Parameters are for computations nothing else.

**Reply by mcanouil** [reply]
See the following example:

- https://github.com/mcanouil/generate-quarto-invoices

**Reply by roaldarbol** [reply]
@mcanouil Is the CLI documented somewhere? The descriptions from`--help` are rather short and not that informative.

Could they somehow be passed with `-M`? I see that relates to metadata, and when I `quarto render`, all the front matter fields show up under `metadata`, which makes me think there might be a way. However, running `quarto render -M test:"Something"` doesn't work, but it might be that I don't understand the correct way of passing the variable.

**Reply by roaldarbol** [reply]
Or maybe it's only implemented for certain standard Quarto metadata fields? I see it works with:
```
  Render w/ Metadata: quarto render document.qmd -M echo:false    
                      quarto render document.qmd -M code-fold:true
```

**Reply by mcanouil** [reply]
>Is the CLI documented somewhere? The descriptions from--help are rather short and not that informative.

No, there is an issue opened about that.

> However, running quarto render -M test:"Something" doesn't work

Sorry, but "it does not work" is not really something that can be use to help, especially when it does work.

I'm using the full flag, but `-M` does the exact same thing.

<img width="1624" alt='The image displays a code editor with a file titled "index.qmd" open. The code defines metadata for an HTML document with the title "Metadata." A terminal window below executes the command quarto render index.qmd --metadata test:something, generating an HTML file named "index.html." On the right side, a web browser shows the rendered output, displaying the title "Metadata" and the word "something."' src="https://github.com/user-attachments/assets/01938812-73f5-4a7d-ae09-d370dac97d37" />

**Reply by roaldarbol** [reply]
Oh, you're right, it does! What confused me was that it isn't rendered in the output:
```
quarto render -M margin-side:left
pandoc -M margin-side:left
  to: typst
  output-file: Behavioural-Grammar.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  variables: {}
  
metadata
  manuscript:
    article: Behavioural-Grammar.qmd
    notebooks: []
    mecaFile: Behavioural-Grammar-meca.zip
  notebook-preview-options:
    back: true
  theme: cosmo
  title-block-style: manuscript
  lightbox: auto
  title: What is it doing?
  subtitle: A Systematic Framework for the Description of Behaviour
  published: 22/03/2025
  updated: 22/03/2025
  authors:
    - name: Mikkel Roald-Arbøl
      orcid: 0000-0002-9998-0058
      affiliation: University of Sussex
      roles: writing
      corresponding: true
  bibliography:
    - bibliography.bib
  abstract: |
    To answer questions such as why animals behave in certain ways, what mechanisms enable the behaviour, a proper description of the behaviour is essential; otherwise the answers may relate other behaviours in reality. Organisms can perform a multitude of behaviours simultaneously, depending on the scales and levels, and what data is included to make the description. *Issue*... Here, I attempt to delineate the ways in which multiple descriptions of behaviour can be correct simultaneously-the domains of which descriptions can be made non-mutually exclusive. I primarily discuss behaviour of animals, but most of this framework can be used to describe behaviour of other living organisms, such as plants or cells, but also of systems we would not describe as living, such as robots or proteins. I consider this framework an analytical tool.
  parts:
    data-availability: There is not data.
  google-scholar: true
  clear-hidden-classes: none
  remove-hidden: all
  unroll-markdown-cells: true
  
[typst]: Compiling Behavioural-Grammar.typ to Behavioural-Grammar.pdf...DONE

Output created: _manuscript/Behavioural-Grammar.pdf
```

But when specifying `echo` and `code-fold` that way, they're appended to the metadata output:

```
quarto render -M echo:false -M code-fold:true -M margin-side:left
pandoc -M margin-side:left
  to: typst
  output-file: Behavioural-Grammar.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  variables: {}
  
metadata
  manuscript:
    article: Behavioural-Grammar.qmd
    notebooks: []
    mecaFile: Behavioural-Grammar-meca.zip
  notebook-preview-options:
    back: true
  theme: cosmo
  title-block-style: manuscript
  lightbox: auto
  title: What is it doing?
  subtitle: A Systematic Framework for the Description of Behaviour
  published: 22/03/2025
  updated: 22/03/2025
  authors:
    - name: Mikkel Roald-Arbøl
      orcid: 0000-0002-9998-0058
      affiliation: University of Sussex
      roles: writing
      corresponding: true
  bibliography:
    - bibliography.bib
  abstract: |
    To answer questions such as why animals behave in certain ways, what mechanisms enable the behaviour, a proper description of the behaviour is essential; otherwise the answers may relate other behaviours in reality. Organisms can perform a multitude of behaviours simultaneously, depending on the scales and levels, and what data is included to make the description. *Issue*... Here, I attempt to delineate the ways in which multiple descriptions of behaviour can be correct simultaneously-the domains of which descriptions can be made non-mutually exclusive. I primarily discuss behaviour of animals, but most of this framework can be used to describe behaviour of other living organisms, such as plants or cells, but also of systems we would not describe as living, such as robots or proteins. I consider this framework an analytical tool.
  parts:
    data-availability: There is not data.
  google-scholar: true
  clear-hidden-classes: none
  remove-hidden: all
  unroll-markdown-cells: true
  echo: false
  code-fold: true
  
[typst]: Compiling Behavioural-Grammar.typ to Behavioural-Grammar.pdf...DONE

Output created: _manuscript/Behavioural-Grammar.pdf
```

That seems like a small bug (maybe intended, IDK?). Should I open an issue for that?

**Reply by roaldarbol** [reply]
That's especially confusing when overwriting existing variables, e.g. when specifying `title:"Hi!"`, the console output doesn't reflect the change (notice the `metadata` `title`):
```
quarto render -M title:"Hi!"
pandoc -M title:Hi!
  to: typst
  output-file: Behavioural-Grammar.typ
  standalone: true
  shift-heading-level-by: -1
  default-image-extension: svg
  wrap: none
  citeproc: false
  variables: {}
  
metadata
  manuscript:
    article: Behavioural-Grammar.qmd
    notebooks: []
    mecaFile: Behavioural-Grammar-meca.zip
  notebook-preview-options:
    back: true
  theme: cosmo
  title-block-style: manuscript
  lightbox: auto
  title: What is it doing?
  subtitle: A Systematic Framework for the Description of Behaviour
  published: 22/03/2025
  updated: 22/03/2025
  authors:
    - name: Mikkel Roald-Arbøl
      orcid: 0000-0002-9998-0058
      affiliation: University of Sussex
      roles: writing
      corresponding: true
  bibliography:
    - bibliography.bib
  abstract: |
    To answer questions such as why animals behave in certain ways, what mechanisms enable the behaviour, a proper description of the behaviour is essential; otherwise the answers may relate other behaviours in reality. Organisms can perform a multitude of behaviours simultaneously, depending on the scales and levels, and what data is included to make the description. *Issue*... Here, I attempt to delineate the ways in which multiple descriptions of behaviour can be correct simultaneously-the domains of which descriptions can be made non-mutually exclusive. I primarily discuss behaviour of animals, but most of this framework can be used to describe behaviour of other living organisms, such as plants or cells, but also of systems we would not describe as living, such as robots or proteins. I consider this framework an analytical tool.
  parts:
    data-availability: There is not data.
  google-scholar: true
  clear-hidden-classes: none
  remove-hidden: all
  unroll-markdown-cells: true
  
[typst]: Compiling Behavioural-Grammar.typ to Behavioural-Grammar.pdf...DONE

Output created: _manuscript/Behavioural-Grammar.pdf
```

But my inquiry has been solved - thanks @mcanouil! Happy to open an issue if you think they are things that could need fixing. 😊

**Reply by mcanouil** [reply]
The log shows the metadata at reading time.
There are few other threads on this and maybe issues as well.

Note that there are kind of two types of metadata: the ones used to define the structure and the one used for templates, etc.
You can't change `format` using metadata, you need `--to`. You can't change parameters (params YAML for knitr).

**Reply by roaldarbol** [reply]
The fact that `echo` and `code-fold` are appended makes me doubt it’s at reading time though. They’re removed from the `pandoc` command and appended to the metadata, so I’d expect the same behaviour for any metadata field.

**Reply by mcanouil** [reply]
There are several "reading time" in fact at Quarto level and at Pandoc level. (and appending metadata is not the same as overwriting)[^1]
The log shows one state and not the latest state of the metadata after Quarto/Pandoc processing.
The best methods to know is using the `native` format (AST).

you'll get something like:

```
Pandoc
  Meta
    { unMeta =
        fromList
          [ ( "test" , MetaString "something" )
          , ( "title" , MetaInlines [ Str "Test" ] )
          ]
    }
  [ Para [ Str "something" ] ]
```

[^1]: this might get better in the future as the team has some plan to improve Quarto's internals.

**Reply by mcanouil** [reply]
Anyhow, I agree that the information from the log is confusing.

**Reply by roaldarbol** [reply]
Would there be a way to provide a nested metadata field? E.g. 
```
group:
	test: "Text"
```
I tried with `-M group.test:"Other text"`, but that didn't work for me.

**Reply by mcanouil** [reply]
See https://github.com/quarto-dev/quarto-cli/discussions/12313#discussioncomment-13002488
`--metadata` does not support nested field. A YAML file does.

**Reply by roaldarbol** [reply]
Ah fair enough, thanks for the swift reply. 

That would be useful though. For going through all metadata parameters, it's a bit much needing to have a YAML file for each parameter. E.g. wanting to simply test whether the following parameter works as expected when being (1) correct type, (2) the wrong type, (3) is empty. 
```yaml
parts:
  data-availability:
  funding:
  ethics:
  ...
```
Having to have 3 (or more) YAML files per parameter to do these tests racks up quite quickly.
