### DISCUSSION TITLE
How to write the YAML file that feeds listings?

### DISCUSSION THREAD

**Discussion by ramiromagno** [quarto-dev/quarto-cli#12330] [Q&A] [answered]
### Description

Hi,

Thanks for the amazing software you make.

I'm struggling with metadata file listings.

How to write the YAML file that feeds the listing? What are the "special" reserved fields? For example, I could verify that some fields are treated specially, like `description`, `date`, seemingly `image` is too, although I have not managed to indicate a path that renders the image in the website.

So, is there a list of fields that are default and what special treatment they get?

Here is a bit of context:

- `index.qmd`: quarto index file
- `oss.yml`: YAML with metadata to feed the listing
- `logo.svg`: An image in the same folder as `index.qmd` and `oss.yml`.

`index.qmd`:

```
---
title: "Open Source Software"
listing: 
  - id: oss
    contents: "oss.yml"
    type: grid
    sort:
      - "date"
---
```

`oss.yml`:

```
- name: entry_A
  description: "some description"
  Authors: "Some authors"
  href: https://quarto.org
  date: "2025-03-20"
  image: "logo.svg"
```

This is what I see:

![snap](https://github.com/user-attachments/assets/f7f5f605-bcc6-4fc1-9109-4419a54c4160)

I did read:

- https://quarto.org/docs/websites/website-listings.html#yaml-listing-content
- https://quarto.org/docs/websites/website-listings-custom.html#metadata-file-listings

**Comment by mcanouil** [comment]
Take a second reading at https://quarto.org/docs/websites/website-listings.html#yaml-listing-content

There are no `href`, `name`, or `Authors`.
If you want to use such fields, then you have a create a custom listing that uses them.
To be clear, the fields used by the default listings are the ones described on the same page: https://quarto.org/docs/websites/website-listings.html#listing-fields
Only `path` is not listed before the YAML section where an example shows it.

**Reply by ramiromagno** [reply]
There is no mention about what the default fields are. I appreciate the reply on the negative, i.e. that those fields are not default but my question was about the default ones. Are you implying that those fields below, indicated by way of example in the docs, are the default ones?

```yaml
- title: "Archived Item 1"
  author: Norah Jones
  date: 2020-01-01
  path: "archived/archived-item-.html"
  categories: [archived, technology]
```

If that is the case then it's not exhaustive because I noticed that `image` and `description` are also special and are not listed in that example.

So, my question remains: which fields are default?
