### DISCUSSION TITLE
Path handling inconsistency between output formats (typst vs. docx)

### DISCUSSION THREAD

**Discussion by davidzgli** [quarto-dev/quarto-cli#12386] [Q&A] [answered]
### Description:
I've discovered a path handling inconsistency in Quarto when using bibliography paths across different output formats. Specifically:

- When using the `typst` format, project-relative paths (starting with `/`) work correctly
- When using the `docx` format, the same project-relative paths fail - absolute paths are required instead

This creates maintenance challenges when building documents for multiple output formats.

### Minimal Working Example:

1. Create a project with this structure:
```
my_project/
├── _quarto.yml
├── index.qmd
└── references/
    └── bibliography.bib
```

2. Place this content in `_quarto.yml`:
```yaml
project:
  output-dir: _output
```

3. Place this content in `index.qmd`:
```yaml
---
title: "Bibliography Path Test"
format:
  typst:
    bibliography: /references/bibliography.bib
  docx: 
    bibliography: /references/bibliography.bib
---

Testing bibliography paths.

Here's a citation [@doe2023].
```

4. Create a minimal `references/bibliography.bib` file:
```
@article{doe2023,
  author = {Doe, John},
  title = {Example Article},
  journal = {Journal of Examples},
  year = {2023}
}
```

### Steps to Reproduce:
1. Create the above files in a new project
2. Run `quarto render index.qmd --to typst` (works correctly with project-relative path)
3. Run `quarto render index.qmd --to docx` (fails with project-relative path)
4. Change the docx bibliography path to an absolute path like `/home/username/my_project/references/bibliography.bib` (works)

### Environment information:
- Quarto version: 1.5.57
- Operating system: Rocky Linux release 9.5 (Blue Onyx)
- R version: 4.4.2

Is this the expected behavior, or should project-relative paths work consistently across output formats?
