### DISCUSSION TITLE
How to include markdown/HTML in metadata for extension

### DISCUSSION THREAD

**Discussion by royfrancis** [quarto-dev/quarto-cli#12447] [Q&A]
### Description

I have an [extension](https://github.com/royfrancis/quarto-accordion) that takes metadata text and creates an accordion layout. 

```
---
accordion:
  - acc:
    - header: Item 1
      body: This is the body content for item 1
    - header: Item 2
      body: This is the body content for item 2
    - header: Item 3
      body: This is the body content for item 3
    - header: Item 4
      body: This is the body content for item 4
filters:
  - accordion
---

{{< accordion acc >}}
```

![](https://github.com/royfrancis/quarto-accordion/raw/main/preview.jpg)

This works, but only handles plain text. [Here](https://github.com/royfrancis/quarto-accordion/blob/main/_extensions/accordion/accordion.lua) is the lua script. I would like this to handle markdown and arbitrary HTML. I would like some advice on how to make this happen. I am sure there must be existing internal functions to do this. Or perhaps there are already other existing solutions that I am not aware of.
