### DISCUSSION TITLE
How can I simplify relative paths in code cells?

### DISCUSSION THREAD

**Discussion by joelostblom** [quarto-dev/quarto-cli#12478] [Q&A] [answered]
### Description

I would like to keep all data files in one place at the root of my project. How can I reference this data from code cells in deeply nested quarto documents while avoiding paths like `../../../../data`? I realize I could create some data loaded utility script and run it in a hidden cell using something like `%run script.py`, but maybe there is a built in way in quarto that is more convenient?

For live code cells such as pyodide, I've noticed that a good workaround is to specify the data via the `resources` yaml key and then it can be references simply as `data` inside the pyodide cells. However this does not work for regular code cells (presumably since they are executed at run time and live code cells are executed after the site is built). Is there anything similar I can use for regular code cells?

## An example project

```
.
├── data
│   └── my-data.csv
├── modules
│   └── index.qmd
└── _quarto.yml
```

`_quarto.yml`

````yaml
project:
  type: website
  render:
    - modules

resources:
  - data  # It would be great if this also worked for regular code cells
````

`modules/index.qmd`

````qmd
---
title: "Quarto Python Data Example"
format: live-html
---

## Test resource paths

```{pyodide}
# pyodide
import os
os.listdir('.')
```

```{python}
# python
import os
os.listdir('.')
```
````

With this setup, the `data` folder only shows up in the live code cell and the regular code cell would still require a relative path:

![image](https://github.com/user-attachments/assets/c9e57382-cd5e-4f65-879b-8e6f71c32eb2)

**Comment by mcanouil** [comment]
Use the environment variables `QUARTO_DOCUMENT_PATH` or `QUARTO_DOCUMENT_FILE` or `QUARTO_PROJECT_ROOT`.

**Reply by joelostblom** [reply]
Thanks @mcanouil , I tried setting QUARTO_DOCUMENT_PATH to the root directory via en `_environment` file, but I still don't see the data directory show up from `os.listdir`. Could you give an example of how I can use these variables?

Note that I would ideally avoid using them directly in the python code since that would also be non-intuitive for readers. I would like to refer to `data/` directly in the code, can these env variables  help me achieve that?

**Reply by mcanouil** [reply]
Don't set it. Use it instead of using `"."`.
Or change the execution directory.

**Reply by joelostblom** [reply]
Thanks, I don't want to use the env variable in the visible code chunks as I think it will be confusing for readers. I just found out about [the quarto yaml key for setting the working dir on the project level](https://quarto.org/docs/projects/code-execution.html#working-dir), which I think is what I want. Otherwise, I will change the working dir in a hidden cell using the env variable.

**Reply by mcanouil** [reply]
You could also use the env variable in an hidden code cell and assign it to a variable.

**Reply by cderv** [reply]
> I just found out about [the quarto yaml key for setting the working dir on the project level](https://quarto.org/docs/projects/code-execution.html#working-dir), which I think is what I want.

Yes this should be what you are looking for. Please tell us if it does not work as you expect.

**Reply by joelostblom** [reply, marked as answer]
Thanks @cderv, it seems like that option is working as expected for code cells! Now I have the following in my `_quarto.yml`:


```yaml
project:
  type: website
  render:
    - modules
  execute-dir: project  # Allow regular code cells to access data without relative paths
  resources:
    - data  # Include data folder in built site

# Make data folder visible for live code cells
pyodide:
  resources:
    - data

```

I noticed that neither of these options seem to affect the paths of figures/images inside `.qmd` files, which still use relative references. I initially thought this would be the case when changing the working directory, but I realize it is only the execution / computation that is affected, which I think makes sense when I reflect on it again.
