### DISCUSSION TITLE
How to supply sidebar contents from external YAML file for page-specific sidebars

### DISCUSSION THREAD

**Discussion by fsaforo1** [quarto-dev/quarto-cli#12480] [Q&A] [answered]
### Problem Statement
I'm trying to make my website more maintainable by storing sidebar contents in external programmatically-generated YAML files instead of directly in `_quarto.yml`. This works fine for a global sidebar, but I'm having trouble getting it to work with page-specific sidebars.

### Issue
The sidebar panel appears, but it's empty - no content is displayed. If I hardcode the same structure directly in `_quarto.yml` instead of referencing the external file, it works correctly. 

### Question
What's the proper way to reference external YAML files for section-specific sidebar contents? The documentation isn't clear on this specific use case.

Below is an example of the structure of the external sidebar, `sidebar_about.yml` contents file:

```yaml
- section: Organization
  contents: about/index.qmd
- section: People
  contents:
    - text: Team Member 1
      href: about/people/member1.qmd
    # more team members...
```

And in my `_quarto.yml`, I reference it like this:

```yaml
website:
  navbar:
    pinned: true
    left:
      - text: About the Team
        href: about/index.qmd
    # other pages
  sidebar:
    - id: about
      title: "About the Team"
      style: docked
      background: dark
      contents: sidebar_about.yml
    # Other section sidebars defined here...

metadata-files:
  - sidebar_about.yml
```

I also include `sidebar: about` in the frontmatter of my about pages.

**Comment by mcanouil** [comment]
Be sure to read the documentation on sidebar: https://quarto.org/docs/websites/website-navigation.html#side-navigation

Then provide a small and simple fully reproducible example preferably as a Git repository.
Do not share your complex project.

**Reply by fsaforo1** [reply]
Here is a minimal reproducible example as requested - https://github.com/fsaforo1/quarto_sidebar_ext

**Reply by mcanouil** [reply, marked as answer]
Where did you see this?
Contents of sidebar does not take a `file` key so why would you expect it to work?

`metadata-files` include the file as if you copy/pasted them in `_quarto.yml`, meaning you are including the content of the file at the top level of the project YAML thus not at all at the right place.

Please read the documentation I have linked earlier to ensure you have a valid file or that your use of `metadata-files` will lead to a valid file.
If you use LLM, please double check that it's valid code and not made up code.

```yaml
metadata-files:
  - sidebar.yml
```

means `sidebar.yml` is:

```yaml
website:
  sidebar:
    - id: ...
```
