### DISCUSSION TITLE
Missing country-code field in the affiliations schema

### DISCUSSION THREAD

**Discussion by fredguth** [quarto-dev/quarto-cli#12543] [Feature Requests]
### Description

The affiliations schema does not have a `country-code:string` field.

```
affiliations:
  - id: string
    number: number
    name: string
    department: string
    group: string
    address: string
    city: string
    region: string
    country: string
    postal-code: string
    url: string

```
    
But this field is suposed to be used [here.](
  https://github.com/jgm/pandoc-templates/blob/f365e85b94e4d2b2e901900ff1ad48d3c514a327/affiliations.jats#L35C1-L35C95)
  
  Isn't it?

**Comment by mcanouil** [comment]
> But this field is suposed to be used [here.](https://github.com/jgm/pandoc-templates/blob/f365e85b94e4d2b2e901900ff1ad48d3c514a327/affiliations.jats#L35C1-L35C95)

Accessibility: For better accessibility, please ensure link text is descriptive and meaningful rather than using generic terms such as "here". This helps all users understand the link's destination. See [Writing meaningful link text (WCAG)](https://www.wcag.com/blog/writing-meaningful-link-text/).

Also note that what Quarto uses from Pandoc are in the Quarto CLI repository. Linking to Pandoc code has little meaning.
The `affiliations.jats` file in Quarto CLI in this case is the same and is at:
- https://github.com/quarto-dev/quarto-cli/blob/15872fcbf6ca83339e6ea8e454e04f32548e8e7a/src/resources/formats/jats/pandoc/default-templates/affiliations.jats#L35
"is supposed to be used": the template is more like "could be used". So, it's an optional field that is indeed missing in Quarto CLI in jats regards as it's not used anywhere else.

Thanks for the feature request and noticing this missing field!

**Reply by fredguth** [reply]
Ok, sorry for that. Part of the reason is not having English as first language.

**Comment by cderv** [comment]
Quarto uses a simplified version of JATS template, and so `country-code` is not supported. 

This is the main template: https://github.com/quarto-dev/quarto-cli/blob/116be8898734b71bc9bf30d25f890e5516e4f278/src/resources/formats/jats/pandoc/template.xml

and affiliation is part of `authors.xml` template and only has the simplified version
https://github.com/quarto-dev/quarto-cli/blob/6f7568b9bbd99b7d27e85075a831f3133eac9bd1/src/resources/formats/jats/pandoc/affiliation.xml#L1-L9

So `country-code` is not used in `jats` format in Quarto CLI. It is not part of the normalization. 

This would be a feature request: Is this a field you tried to use ?

**Reply by fredguth** [reply]
Yes, this is a field needed in the Scielo XML.  Scielo is JATS based, but with lots of quirks. Some of them I wasn't able to fix with lua filters  because of my own limitations with Lua and Pandoc internals. I run a python script to fix.

**Reply by cderv** [reply]
I think this means you need to provide your own JATS xml template and not really on quarto one. (`template: custom.xml`) 

Then it may work to get all the meta you have. Unless the author normalization is the problem here.

**Comment by fredguth** [comment]
I have already implemented my own custom template, but I'm encountering an issue with the `country-code` field. Despite correctly populating this field in my frontmatter YAML, when I reference `it.country-code` in my template, it always renders empty. Here's my template code and YAML for reference:

```xml
<!-- From mytemplate.xml -->
<country$if(it.country-code)$ country="$it.country-code$"$endif$>$it.country$</country>  <!-- always returns empty despite being defined in YAML -->
```

```yml
# From my frontmatter
affiliations:
  - id: nevusp
    # Other fields...
    country: Brasil
    country-code: BR    # This value isn't being passed to the template
    url: https://usp.br
```

Is there a special syntax for accessing hyphenated field names in Quarto templates, or might this be a known limitation with the Scielo XML requirements?
