### DISCUSSION TITLE
CRediT authors in a book project

### DISCUSSION THREAD

**Discussion by ccamara** [quarto-dev/quarto-cli#12557] [Q&A]
### Description

I know Journal Articles templates allow crediting authors using [CRediT](https://github.com/quarto-dev/quarto-cli/blob/f65180a75e1cf2996328cd51cb4fd5d02d391511/src/resources/filters/modules/authors.lua#L119-L144)  (see https://quarto.org/docs/journals/authors.html#roles).

I've tried to implement that into a book (see below) but either I'm doing something wrong or this feature is not (yet?) implemented for that particular type of project. I wonder if it would be possible to extend/apply that to books.

This is what I have on my `_quarto.yml`:

````yml
book:
  title: "My fancy title"
  author: 
  - name: Name Surname
    affiliation: University of Life
    role: 
    - conceptualization: lead
    - methodology: supporting
````

And this is what I get:
![image](https://github.com/user-attachments/assets/3dab0679-bd3c-46bf-95a7-b43df95a51a1)

As you can see, no information about roles at all.
