### DISCUSSION TITLE
How do I give colors to categories in documents

### DISCUSSION THREAD

**Discussion by haxfn** [quarto-dev/quarto-cli#12635] [Q&A] [answered]
### Description

Hi amazing quarto community! I was wondering if I can give colors to categories:

---

in listings:

![image](https://github.com/user-attachments/assets/7a5d8f7e-9dd2-42bb-b46f-ac0926dbac3d)

---

and also give consistent category colors inside individual pages:

![image](https://github.com/user-attachments/assets/5f006a2e-2b33-4207-96cf-8235589a4f4c)

---

I want to achieve something like this:

![image](https://github.com/user-attachments/assets/5cca99c9-7941-4676-883d-5dea188f76a8)

**Comment by mcanouil** [comment]
Probably with a bunch of (S)CSS and JavaScript.
Clearly not something trivial.

If you look at your example from GitHub, what you want implies:
1. adding classes or IDs to each category.
2. adding (S)CSS rules matching the above.

You could achieve 1. using a custom listing (EJS which uses JavaScript to compute things), but it won't have an effect to individual posts.

**Reply by haxfn** [reply]
ideally, i want categories to be from a list in a yaml file, where I would define colors for each category:

```txt
\`\`\`yaml
- id: chess
  color: yellow
  icon: :chess_pawn: 
- id: puzzle
  color: green
  icon: :jigsaw: 
\`\`\`
```

then I would use these `id`s in individual files

**Reply by mcanouil** [reply, marked as answer]
You'll have to write that logic yourself somewhere using Lua, Javascript, and (S)CSS:
Don't `` \`\`\` ``, simply enclose with more.

Example:

```sh
quarto create project blog
```

add to `_quarto.yml`

```javascript
    include-after-body:
      - text: |
          <script>
          document.addEventListener('DOMContentLoaded', function() {
            const categoryDivs = document.querySelectorAll('.listing-category, .quarto-category');
            categoryDivs.forEach(function(div) {
              let content;
              if (div.querySelector('a')) {
                content = div.querySelector('a').textContent.trim().toLowerCase();
              } else {
                content = div.textContent.trim().toLowerCase();
              }
              div.id = "quarto-category-" + content;
            });
          });
          </script>
```

and in `styles.css`

```css
#quarto-category-analysis {
  background-color: #b22222;
  border-color: #b22222;
  color: #ffffff;
}

#quarto-category-code {
  background-color: #4682b4;
  border-color: #4682b4;
  color: #ffffff;
}

#quarto-category-news {
  background-color: #228b22;
  border-color: #228b22;
  color: #ffffff;
}
````

<img width="720" alt="image" src="https://github.com/user-attachments/assets/2ca70958-e1d6-4c99-b89d-41edcaaae92b" />
<img width="721" alt="image" src="https://github.com/user-attachments/assets/81804e4c-1f49-4113-9399-4a206dba73db" />
