### DISCUSSION TITLE
"Theme file compilation failed" error upon quarto render and _quarto.yml file

### DISCUSSION THREAD

**Discussion by nmolnar-northeastern** [quarto-dev/quarto-cli#12658] [Q&A] [answered]
### Description

Hi everyone, 

I'm new to quarto, so thank you for your patience in advance. 
I'm on macOS sequoia 15.4 and am doing most of my quarto work through Rstudio 2023.06.1+524, R version 4.3.1. 

I'm trying to build a quarto website and am running into "ERROR: Theme file compilation failed:" whenever I try to render my .qmd files. I created a basic website from running **quarto create-project new-test-site --type website** in my terminal. This created a directory with four files: about.qmd, index.qmd, styles.css, and _quarto.yml. These files are unchanged from their defaults:

```qmd
---
title: "About"
---

About this site
```
for exanmple. The _quarto.yml file is set up as follows:

```yml
project:
  type: website

website:
  title: "new-test-site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
```

Whenever I try to render my qmd files (either through the RStudio interface or though terminal using quarto render) I get the following error "ERROR: Theme file compilation failed." I have tried uninstalling and reinstalling quarto, as well as clearing the quarto cache on my computer, but nothing has worked. I have run quarto check and seen no errors with my installation each time.

However, when I delete the _quarto.yml file, I can render my .qmd files no problem. Similarly, when I download .qmd files from Quarto's tutorial page, I can render these files. This leads me to believe somehthing about the existence of the _quarto.yml file is preventing me from rendering my .qmd files. This is a problem as I have learned that _quarto.yml files are integral to bulding Quarto websites.

What should I do here? Has anyone run into this problem before?
