### DISCUSSION TITLE
amsmath constructs not rendering in quarto book

### DISCUSSION THREAD

**Discussion by friendly** [quarto-dev/quarto-cli#12669] [Q&A]
### Description

[Env: quarto 1.4.550, RStudio 2024.09.1+394 , Windows 10]

This is related to issue #10545 but different, as it doesn't relate to equation numbering or the things mentioned there.

In my document, I want to use ams `\begin{cases}` ... `\end{cases}` to show dummy coding of factors, with the following.
I'm using `$$` rather than an equation environment because this shows nicely in my editor window:

```
$$
x_b = 
\begin{cases}
1 & \text{if factor = b} \\
0 & \text{otherwise}
\end{cases}

;\quad

X_c = 
\begin{cases}
1 & \text{if factor = c} \\
0 & \text{otherwise}
\end{cases}

;\quad

X_d = 
\begin{cases}
1 & \text{if factor = d} \\
0 & \text{otherwise}
\end{cases}
$$
```
I see onscreen what I want:

![image](https://github.com/user-attachments/assets/5effbae6-5836-4a56-b7ce-a63b55e03028)

Yet, when I render the book, what I see is just:

![image](https://github.com/user-attachments/assets/39b4bcaf-b6e7-4a34-b923-ac7da09d99e9)

In my `_quarto.yml` I'm using `mathjax` as:

```
format:
  html:
    html-math-method: mathjax
    theme: cosmo
    code-link: true
    filters:
      - quarto
      - line-highlight
      - parse-latex
      ...
```

What can I do to make this work?
