### DISCUSSION TITLE
How to have different sidebar tools for different sidebars

### DISCUSSION THREAD

**Discussion by haxfn** [quarto-dev/quarto-cli#12673] [Q&A]
### Description

I have two sidebars declared in my `_quarto.yml`:

```yaml
#...
website:
  #...
  sidebar:
    - id: dynamics
      contents: page2.qmd
      tools:
        - icon: github
          href: https://github.com/gyanantaran/DynamicsSimulations
      alignment: left
    - id: gyan
      contents: page1.qmd
#      tools:
#        - icon: github
#          href: https://github.com/mangoqualitee/Resources

#...
```

i.e. I want to have different tool (github href are different) for different sidebar ids. But, right now commenting the tools for the 2nd sidebar gives it the tools from the first tool bar. Is this the expected behaviour?
