### DISCUSSION TITLE
How do I display custom front matter keywords in the title-block

### DISCUSSION THREAD

**Discussion by haxfn** [quarto-dev/quarto-cli#12690] [Q&A] [answered]
### Description

I want to display my custom yml keywords on the rendered page, something like the `jats` format:

<img src="https://github.com/user-attachments/assets/cc68868b-1a44-4414-9de3-4a8a690b4e49" width="200" />

I am creating a resource database, and for that I want to define a new yml template:

```yml
---
title: Page Rank
description: Thoughts and References when Learning Page Rank.

categories: ["A-Computing","B-LinearAlgebra",]
contributors: ["Sergey Brin","Larry Page"]
status: done
urls: ["https://en.wikipedia.org/wiki/PageRank", "https://www.cis.upenn.edu/~mkearns/teaching/NetworkedLife/pagerank.pdf"]

# format:
#  html:
#    template: /_extensions/custom-template
---

# Problem

The Page Rank algorithm is..
```

I would use this template in a listing:

```yml
---
title: "Resources"
description: "Categorized Learning Resource Database"
title-block-banner: _assets/tree.jpeg

# page-layout: article
listing:
  contents: .
  fields: [status, title, categories, urls, contributors]
  sort: "date desc"
  type: table
  table-striped: true
  field-links: [title]
  sort-ui: [title, categories, status]
  filter-ui: [title, categories]
  # categories: true
  # date-format: DD MMM, YYYY
#  template: _assets/tgif.js
# css: /css/tgif.css
---

```

I want to display custom YAML frontmatter fields like status, contributors, and urls on my rendered pages, similar to how the JATS format displays metadata in academic papers.

With some digging I realized I need to hack somewhere around here:

`quarto-cli/src/resources/formats/html/pandoc/title-block.html`:

```html
<header id="title-block-header">
$if(title)$<h1 class="title">$title$</h1>$endif$
$if(subtitle)$
<p class="subtitle">$subtitle$</p>
$endif$
$for(author)$
<p class="author">$author$</p>
$endfor$

$if(date)$
<p class="date">$date$</p>
$endif$
$if(abstract)$
<div class="abstract">
<div class="abstract-title">$abstract-title$</div>
$abstract$
</div>
$endif$
</header>
```

Could someone guide? How do I make the custom keywords in yml front matter show up on my page?

**Comment by mcanouil** [comment]
There are already multiple threads about modifying partials and templates, including the documentation: https://quarto.org/docs/journals/templates.html

Please try to spend some time to understand how things work in Quarto and go through all the documentation and existing threads. This will help you with all your customisation questions.

See also: https://quarto.org/docs/websites/website-listings-custom.html

**Reply by haxfn** [reply]
I spent some time understanding these.

I can't find where the categories get added on pages in the partial templates, where is it?

https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/html/pandoc/title-block.html

**Reply by haxfn** [reply]
The categories and the description don't show up. I have:

```yaml
---
title: Page Rank
description: Thoughts and References when Learning Page Rank.

# ...

format:
  html:
    template-partials:
      - title-block.html
---
```

`title-block.html`: is the [default source code](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/html/pandoc/title-block.html)

I don't understand why, but when I do this, i.e when I overwrite the template-partial `title-block` with the default `title-block.html`, the categories and the description don't show up. Why is that?
