### DISCUSSION TITLE
Adding Git commit hash to all Quarto website pages automatically

### DISCUSSION THREAD

**Discussion by vlashada** [quarto-dev/quarto-cli#12699] [Q&A] [answered]
## Background
I'm building a website using Quarto with the `freeze: auto` option enabled. This means my scripts only rerun when I change something in a document, which is great for performance. 

## Goal
I want to display the git commit hash of the most recent commit on each page of my website (perhaps in a footer or header), to help track which version of the site is being viewed.

## Current approach
Currently, I can add this Python snippet to each `.qmd` file:

```python
``{python}
import subprocess
print(subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode().strip())
``
```

## Problem
Manually adding this code to every page is tedious and hard to maintain.

## Question
Is there a way to automatically include the git commit hash on every page of a Quarto website without copy-pasting this code into each `.qmd` file? 

I'm looking for a solution that:
- Works with the `freeze: auto` option
- Updates the commit hash whenever the site is rebuilt
- Can be configured once and applied to all pages

## My Quarto configuration
Here's my current `_quarto.yml`:

```yaml
project:
  title: "pet-dashboard"
  type: "website"
  render:
    - "*.qmd"
website:
  title: "Your Pet's Dashboard"
format: 
  html:
    self-contained: true
    code-fold: true
    code-tools: true
editor:
  render-on-save: true
css: styles.css
execute:
  freeze: auto
```

I've considered using includes, partials, or other Quarto features but I'm not sure about the best approach. Any help would be appreciated!
