### DISCUSSION TITLE
In a Quarto Book project, how do I create a link from one chapter to another?

### DISCUSSION THREAD

**Discussion by lassehjorthmadsen** [quarto-dev/quarto-cli#12703] [Q&A] [answered]
### Description

I'm having a hard time getting links from one chapter to another to work in a Quarto Book. Figure I must be making a simple mistake. Searched high and low and used a variety of chatbots. Minimal example, where I expect a link from Chapter 2 to Chapter 1 after rendering/previewing, but see none, only the literal "See @chap:one." text.

Tried with and without pandoc-args in _quarto.yml.

I'm on Windows 11, Quarto 1.7.30.

Thanks a lot for any input.

chapter1.qmd:

```
---
title: "Chapter 1"
format: html
---
# Chapter 1 {#chap:one}
Content. 
```
chapter2.qmd:
```
---
title: "Chapter 2"
format: html
---
# Chapter 2 {#chap:two}
See @chap:one.
```
_quarto.yml:

```
project:
  type: book
  output-dir: docs
book:
  title: "Test Book"
  author: "Test Author"
  date: "today"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
format:
  html:
    theme: cosmo
    number-sections: false
    pandoc-args: ["--filter", "pandoc-crossref", "--no-citeproc"]
crossref:
  chapters: true
```
