### DISCUSSION TITLE
How do I remove a subdir from website project?

### DISCUSSION THREAD

**Discussion by ltbmb** [quarto-dev/quarto-cli#12712] [Q&A] [answered]
### Description

I have a repository, that contains not only files for quarto. I want to use quarto (+profiles) to generate a website from the `/site` dir and pdf output from `/docs` dir. I want to have my `_quarto.yaml` file in the project root, so that the vs code extension works properly. 

```
- /
  - docs/
    - chaper1.qmd
    - chapter2.qmd
    - ...
  - site/
    - dir1/
      - content1.1.qmd
      - content1.2.qmd
    - dir2/
      - content2.1.qmd
      - content2.2.qmd
    - index.qmd
  - _quarto.yaml
```

With the following `_quarto.yaml`

```yaml
project:
  type: website
  output-dir: output

format:
  html: 
    theme: cosmo
    css: styles.css
    toc: true


website:
  title: "Awesome Page"
  navbar:
    left:
      - href: site/index.qmd
        text: Home
  sidebar:
    contents: site/**/*
    collapse-level: 1
  repo-url: https://gitlab.ourdomain.com/group/project
  repo-actions: [edit, source, issue]
  repo-subdir: site
  site-url: https://group.gitlab.ourdomain.com/project
```

With this setting I get a somewhat working website, however everything is located under the `site` directory inside of the `output` dir and I have to set the link in the navbar to `site/index.qmd` and sidebar contents to `site/**/*`. 

Also directly inside the output directory another `index.html` is created. This just redirects to a (random?) page inside the wiki.

I want to remove the `site` dir in the output, and use my index.qmd as landing page. How can I achieve that?
