### DISCUSSION TITLE
Multiline author block

### DISCUSSION THREAD

**Discussion by jfhawkin** [quarto-dev/quarto-cli#1271] [Q&A] [answered]
This is a simpler question than other related to author details. I simply need the author information to be over multiple lines. What is the yaml syntax for this? E.g.,
`author: Author text below...`
    Author Name 1
    University of X
    Author Name 2
    University of X

**Comment by cscheid** [comment, marked as answer]
This is not as well-documented as should be right now, but here's an example that should work going forward including our upcoming custom formats work:

```
author:
    - name: Bill Gates
      orcid: 0000-0003-1689-0557
      email: bill@gates.com
      affiliation:
        - name: Bill & Melinda Gates Foundation
          address: 440 5th Ave N
          city: Seattle
          state: WA
          country: USA
          postal-code: 98109-4631
    - name: Another Author
      orcid: 1234-5678-9012
      email: another@author.com
    - name: One More
...
```
