### DISCUSSION TITLE
How to set authors note-by-note from a complete set of authors?

### DISCUSSION THREAD

**Discussion by albertomercurio** [quarto-dev/quarto-cli#12765] [Q&A]
### Description

Hello,

I'm writing a webpage containing tutorials of a Julia package. The single tutorials can be written by different developers, so the authorship of that tutorial should be referred to only who wrote it.

Every author has many fields related to the organization, orcid and others, so I don't want to repeat the informations on every notebook. So my idea was to have a file with the definition of all the authors, showing in the home page all the authors, but then specify only who wrote the notebook.

I have tried the following configuration

### `_authors.yml` file with content

```yml
author:
  - id: albertomercurio
    name: Alberto Mercurio
    orcid: 0000-0001-7814-1936
    email: someemail@epfl.ch
    affiliations:
      - ref: 1

  - id: yitehuang
    name: Yi-Te Huang
    orcid: 0000-0002-2520-8348
    email: someemail@gmail.com
    affiliations:
      - ref: 2
      - ref: 3

  - id: lixuncai
    name: Li-Xun Cai
    orcid: 0009-0006-7644-5200
    email: someemail@gmail.com
    affiliations:
      - ref: 2
      - ref: 3

affiliations:
  - id: 1
    name: École Polytechnique Fédérale de Lausanne (EPFL)
    address: Rte Cantonale
    city: Lausanne
    state: Switzerland
    postal-code: 1015

  - id: 2
    name: National Cheng Kung University
    city: Tainan
    state: Taiwan
    postal-code: 701401

  - id: 3
    name: Center for Quantum Frontiers of Research and Technology (QFort)
    city: Tainan
    state: Taiwan
    postal-code: 701401
```

### `_quarto.yml` with content

```yml
# ... some code

metadata-files:
  - _authors.yml
 
# ... some code
```

### Specific notebook

```qmd
---
title: "Adiabatic sweep (with `QuantumObjectEvolution`)"
date: 2025-04-20  # last update (keep this comment as a reminder)

author:
    - ref: lixuncai
---

# Some text
```

While it correctly shows the complete list of authors in the home page, it doesn't show anything in the specific notebook.

## Another approach

I have also tried to make a separate file called `_lixuncai.yml` with content

```yml
author:
  - name: Li-Xun Cai
    orcid: 0009-0006-7644-5200
    email: someemail@gmail.com
    affiliations:
      - ref: 2
      - ref: 3
```

and then doing

```qmd
---
title: "Adiabatic sweep (with `QuantumObjectEvolution`)"
date: 2025-04-20  # last update (keep this comment as a reminder)

metadata-files:
  - ../../_authors/_lixuncai.yml
---

# Some text
```

This shows instead all the authors with the repeated author I selected.

I there a way to make it work?
