### DISCUSSION TITLE
New feature: Citations by Part

### DISCUSSION THREAD

**Discussion by Cidree** [quarto-dev/quarto-cli#12760] [Feature Requests]
### Description

Hi, would it be possible to implement the generation of bibliography per part of a Quarto Book?

```yaml
book:
  chapters: 
    - index.qmd
    - part: introducion_part.qmd
      chapters: 
        - 01-introduction.qmd
        - 02-introduction.qmd
        - 03-introduction-references.qmd
    - part: awesome_part.qmd
      chapters: 
        - 01-awesome.qmd
        - 02-awesome.qmd
        - 03-awesome-references.qmd
```

For instante, to generate the bibliography at the end of `introducion_part.qmd`, and then the bibliography of `awesome_part.qmd` at the end of that part.
