### DISCUSSION TITLE
Quarto blog category listing pages no longer displaying correct posts

### DISCUSSION THREAD

**Discussion by smach** [quarto-dev/quarto-cli#12770] [Q&A] [answered]
### Description

My Quarto blog's category pages are no longer showing the posts that they should. Many aren't showing any posts at all. The main blog home page is fine, but if I click any of the categories, they no longer work. They used to work. I don't know exactly when they stopped working, it may be when I upgraded my Linux server's R and RStudio versions but it could have been before.

Main index.qmd page:

```
---
title: "My Next Chapter"
listing:
  contents: posts
  sort:
    - "date desc"
    - "order asc"
    - "title asc"
  type: default
  categories: true
  feed: 
    type: partial
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
image: "path_thru_trees.webp"
image-alt: "A path through trees"
---
```
The _quarto.yaml file:

```
project:
  type: website

website:
  title: "My Next Chapter: A Retirement Journey"
  site-url: "https://NextChapter.machlis.com"
  description: "One woman's experience entering a new stage of life after decades of full-time work. What's it like leaving a professional identity (partly) behind? A blog about retiring, vibrant aging, and fighting ageism."
  google-analytics: "G-4JRE93QCHJ"
  favicon: favicon.jpg
  twitter-card: true
  open-graph: true
  body-footer: "<em><br />You can follow My Next Chapter by <a href='/email.html'>email newsletter</a> or <a href='/index.xml'>RSS feed</a>. Blog content © Sharon Machlis.</em><a rel='me' href='https://masto.machlis.com/@smach' />"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - about.qmd
      - resources.qmd
      - icon: envelope
        href: email.qmd
      - icon: rss
        text: RSS
        href: index.xml
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/smachlis.bsky.social
      - icon: mastodon
        href: https://masto.machlis.com/@smach
      - icon: linkedin
        href: https://www.linkedin.com/in/sharonmachlis

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
execute:
  freeze: auto
```

Typical blog post yaml:

```
---
title: "Almost a Year Since I Decided to Retire"
author: "Sharon Machlis"
description: "What I feared, and how things have turned out so far"
date: "2025-05-18"
categories: [Reflections, Retiring, Retirement]
image: "ChatGPT_two_desks_resized.webp"
image-alt: "Illustration image by ChatGPT of busy person on left at a desk with head in hands; calm-looking desk on right showing calendar on May and a sticky note saying time to retire"
---
```

This no longer works whether I try to render on my Linux server or locally on my Windows machine. My Linux Quarto environment:

```
Quarto 1.7.31
[✓] Checking environment information...
      Quarto cache location: /home/{myusername}/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.6.3: OK
      Dart Sass version 1.85.1: OK
      Deno version 1.46.3: OK
      Typst version 0.13.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.7.31
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: /usr/bin/chromium-browser
      Source: PATH

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)
```
