### DISCUSSION TITLE
Is there a way to overwrite at the project level a value from `_brand.yml`?

### DISCUSSION THREAD

**Discussion by mcanouil** [quarto-dev/quarto-cli#12774] [Q&A] [answered]
_As of Quarto CLI 1.8.7_

### Description

Assuming I have a `_brand.yml` for a company that has the company logo defined.
How can I use the `_brand.yml` (as is) but change logo to use another value?
I know I can set brand inside the document front matter but I would like to avoid duplicating this everywhere.

At the moment, there is still the path resolution issue that does not use project root as reference, so you can't really use the logo for instance via the shortcode or brand in a document not living at the root.

- https://github.com/quarto-dev/quarto-cli/issues/11982

### Example

- `company-brand-light.yml`

```yml
logo:
  images:
    company-logo:
      path: company.png
      alt: "Company Logo"
  medium: company-logo
```

- `_quarto.yml`

```yml
brand:
  light: company-brand-light.yml
```

How to set the following?

```yml
logo:
  images:
    company-team-logo:
      path: company-team.png
      alt: "Team Logo from Company"
  medium: company-team-logo
```

It can be set in a document frontmatter but in a context of a project with multiple documents, having to set the following is really not doable at many levels.

```markdown
---
title: document title
brand:
  logo:
    images:
      company-team-logo:
        path: company-team.png
        alt: "Team Logo from Company"
    medium: company-team-logo
---
```

**Comment by arnaudgallou** [comment]
Wouldn't the `metadata-files` option do the job here?

``` yaml
# _quarto.yml

metadata-files:
  - _brand.yml
  - _customBrandLogo.yml # file containing the new logo
``` 

I think the last logo defined should override the previous one.

**Reply by mcanouil** [reply]
No because `_brand.yml` is not regular metadata and needs to be passed to `brand` as illustrated in my original post.

And setting `brand` in `_metadata.yml` is not supported (same syntax as for document frontmatter).

Top level `brand` in `_quarto.yml` takes paths not objects.

**Comment by cscheid** [comment, marked as answer]
The short answer is "no". The long answer is "ideally there should be a way, but the semantics get complicated"

**Reply by mcanouil** [reply]
This was my guess.
Support for brand object in `_metadata.yml` would help. I think it was discussed somewhere.

**Comment by gordonwoodhull** [comment]
Although you can't override brand yml values in general, the brand.yml logo populates either the sidebar logo or the navbar logo, depending on which navigation you have set up.

So you can override the logo in the navigation configuration:

* _quarto.yml
```yaml
project:
  type: website
website:
  title: "override brand logo"
  sidebar:
    logo: company-team.png
    style: "docked"
    contents:
      - document.qmd
brand:
  light: company-brand-light.yml
```

Arguably we should allow brand.yml image resource names and small/medium/large here, as we already have in typst/revealjs/dashboard `logo` options. Right now it's just a path.

**Reply by mcanouil** [reply]
In my case I have a format extension that uses `toc-title` to brand single HTML document, so I wanted to avoid having to redefine `toc-title`, etc. by replacing the "company-logo".
In other YAML values, it's easy because it's "the last one wins", but for brand, there is no such thing as the only merging is at the document level.

```
contributes:
  formats:
    html:
      toc-title: "[{{< brand logo company-logo light >}}]{.light-content}[{{< brand logo company-logo dark >}}]{.dark-content}"
```

Note that because of the path resolution issue, I still ended up doing:

```yaml
format:
  company-html:
    toc-title: "![](/absolute/path/to/logo-light.png){.light-content}![](/absolute/path/to/logo-dark.png){.dark-content}"
```
