### DISCUSSION TITLE
Modular branding

### DISCUSSION THREAD

**Discussion by jonpeake** [quarto-dev/quarto-cli#12794] [Feature Requests]
### Description

It would be really nice to have brand.yml files and headers act in a modular way such that two (or more) files/YAML strings can be listed under a single `brand` call. Currently, everything for the brand needs to happen in either a single file or a single call to `brand` in the YAML header of a document. This includes both set-up (setting color palettes, logo paths, and font families) and document-specific configuration (assigning color schemes using foreground/background/primary, assigning logo sizes, and fonts for body and headers). It would be useful to have the ability to handle these aspects in different files or in some combination of files and YAML header keys.

I can envision an implementation that looks something like this:
`example.qmd`
```qmd
---
title: Example
format: revealjs
brand:
  - brand_setup.yml
  - slide_brand.yml
  - text: |
      typography:
        headings: Roboto
---
Hello world!
```
`brand_setup.yml`
```yaml 
color:
  palette:
    dark-blue: "#003155"
    waves: "#1EBEC7"
logo:
  images:
    company-emblem:
      path: logos/emblem.png
      alt: Company emblem
    company-logo:
      path: logos/logo.png
      alt: Company logo
    program-logo:
      path: logos/program-logo.png
      alt: Program logo
typography:
  fonts:
    - family: Arial
    - family: Open Sans
    - family: Roboto
```

`slide_brand.yml`
```yaml 
color:
  background: white
  foreground: dark-blue
  primary: waves

logo:
  small: company-logo
  medium: company-emblem

typography:
  base: Open Sans
```
