### DISCUSSION TITLE
Revealjs: hide logo on the title slide

### DISCUSSION THREAD

**Discussion by JosephBARBIERDARNAL** [quarto-dev/quarto-cli#12820] [Q&A] [answered]
### Description

Hi, 

I'm making a revealjs quarto extension, and my `_extension.yaml` looks like this:

```yaml
title: Slide deck
author: WVC
version: 1.0.0
quarto-required: ">=1.5.0"
contributes:
  formats:
    revealjs:
      theme: [default, style.scss]
      width: 90%
      height: 90%
      logo: logo.png
```

I'd like to be able to **not** display `logo.png` on the title slide. 

The main problem I encountered is what the CSS selector should look like in this case, and then I can just set `display: none;`.

Even after inspecting my browser's devtools, I feel like revealjs does not work with a "slide-1", "slide-2" logic, and so what I'm trying to do is not likely to work.

Did I miss something? Is there an easier of hidding the logo in my case?
