### DISCUSSION TITLE
Restart Chapter Numbers by Part

### DISCUSSION THREAD

**Discussion by madebyafox** [quarto-dev/quarto-cli#1283] [Q&A]
I'm using a quarto book-type project to write my dissertation.  I notice that the chapter numbers are continuing through each Part, but I'd like to have chapters be named per block.  Is there a YAML parameter to specify that the chapter numbering should restart for each part?

![image](https://user-images.githubusercontent.com/5558266/177236098-37c27d06-c374-4719-8338-2159962b4cd0.png)

Thanks!

**Comment by wzbillings** [comment]
This seems to be the only discussion of this feature that I can find online, so even though it's months later I want to second this. I think it is possible in PDF mode by doing some TeX stuff, but as far as I can tell is not possible in HTML, but I would like it to be in the future.

**Comment by bcdavasconcelos** [comment]
Just add this to the YAML header:

```yaml
format:
  pdf:
    header-includes:
      - \makeatletter
      - \@addtoreset{chapter}{part}
      - \makeatother           
```
