### DISCUSSION TITLE
How to actually change font size in beamer presentation?

### DISCUSSION THREAD

**Discussion by icarosadero** [quarto-dev/quarto-cli#12843] [Q&A] [answered]
### Description

I am using a jupyter notebook to generate a beamer presentation via quarto, [this thread](https://github.com/quarto-dev/quarto-cli/discussions/5025) says that I just have to add `fontsize: "5pt"`. So, this is what I did in a markdown cell right at the beginning of the notebook:

```
---
title: "Test"
format:
    beamer:
        theme: metropolis
        fontsize: "5pt"
        pdf-engine: pdflatex
keep-tex: true
---
```

Except that when I run `quarto preview notebook.ipynb --log quarto.log`, the size doesn't change regardless of the value I put on the font size argument.

Inspecting the tex file that is generated, it does include the right font size in the preamble

```latex
\documentclass[
  5pt,
  ignorenonframetext,
]{beamer}
```
.

So, I don't understand why it doesn't actually change.
