### DISCUSSION TITLE
code-block-bg: true has no apparent effect

### DISCUSSION THREAD

**Discussion by stuvjordan-uroc** [quarto-dev/quarto-cli#12881] [Q&A]
### Description

Here is my _quarto.yml:

```
book:
  title: "BLW Data Visualization Bootcamp"
  author: "Stu"
  date: "May 29, 2025"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_tools.qmd
    - 03_set_up_a_project.qmd
    - 04_check_out_your_assignment.qmd
    - 05_basic_html.qmd
    - 06_basic_css.qmd
    - 07_svg.qmd
    - 08_basic_javascript.qmd
    
bibliography: references.bib



format:
  html:
    theme: cosmo
    code-block-bg: true
    code-block-border-left: "#31BAE9"
  pdf:
    documentclass: scrreprt
```

Yet when I `quarto preview`, the code block backgrounds are not highlighted.  For instance, here is a screenshot of the html output of an excerpt that includes a code block:

![image](https://github.com/user-attachments/assets/69480bf7-71cc-4ac5-9ffe-15b1b29ff6e1)

What am I doing wrong?  Thanks!
