### DISCUSSION TITLE
Not Found Error During Full Project Render Despite Successful File Generation

### DISCUSSION THREAD

**Discussion by kimmy190** [quarto-dev/quarto-cli#12952] [Q&A]
### Description

Hello, I'm working a on quarto project currently on mac using vscode. 

**Issue**
when running `quarto render` it gives me the error below despite the html file being created in the `_site` folder. For all the other qmd files, the html file is created within the same folder instead of the `_site` folder, however all the html files for the qmd files in the `lecs` folder are created in the `_site` folder. 

`ERROR: NotFound: No such file or directory (os error 2): rename '/website/lecs/w01/lec01.html' -> '/website/_site/lecs/w01/lec01.html'`

This is an issue I get when I'm trying to render the whole thing altogether.  When rendering only that `lec01.qmd` file using preview it works fine(the html is given successfully) 

The lec01.qmd file has its seperate yml header inside the file and I'm suspecting that might be the issue but I'm not sure how this can be resolved

The project structure looks like this 

```
website/
└─ _site/
└─ _quarto.yml
└─ lecs/
    └─ w01/
        └─ lec01.qmd  (has separate YAML header)
    └─ .... 
```

Inside the lec01.qmd it has a seperate yml header of 
```
---
title: "Lec"
subtitle: "Lec"
format:
  revealjs:
    slide-number: true
    embed-resources: false
    show-notes: false
    chalkboard:
      src: chalkboard.json
      buttons: true
      boardmarker-width: 2
      chalk-width: 2
      chalk-effect: 1.0
    css: style.css
  html-math-method:
    method: mathjax
    url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
---
```
And the quarto.yml folder contains these: 

```
project:
  type: website
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
 
```
