### DISCUSSION TITLE
Don't want to admit how long I have been struggling to do this (even with the help of copilot - I can't get it right)

### DISCUSSION THREAD

**Discussion by ghost** [quarto-dev/quarto-cli#12951] [Q&A] [answered]
### Description

I am trying to customize the html output from quarto.  Specifically, I want each header (and only the headers - not the content beneath the headers) to have a colored fill and a border.  Also, I am only able to get the headers to span the main body of the report but I really want the headers and content to start from the main body and extend right to the right edge (with a little padding on right edge), so effectively, I don't want a right margin or there is no content on the right margin., so that main body can take up the right 2/3s of the screen.  On the left side, I want a TOC.  

The link here shows what I am trying to build (I used excel to create what I want quarto to create - can ignore the light grey cell borders)
[https://imgur.com/a/RhCRWSp](url)

**Comment by jimjam-slam** [comment, marked as answer]
Hey @bujayherster, I'll break this into two parts!

Firstly, to have your page content expand into the margin and sidebar (_if_ there's no content there already), you'll want to add [`page-layout: full`](https://quarto.org/docs/output-formats/page-layout.html#full) under `format.html`, either to your individual document frontmatter or your `_quarto.yml` (to make it the default). Since you'll have a TOC on the left, content should stay out of there even with this option turned on.

Second, you can use some CSS to colour your headings:

```css
main.content h1
main.content .h1,
main.content h2,
main.content .h2,
main.content h3,
main.content .h3,
main.content h4,.h4,
main.content h5,
main.content .h5,
main.content h6,
main.content .h6 {
  background: red;
  border: 2px solid yellow;
}
```

Save this to a CSS file and add it to your document frontmatter using the [`css`](https://quarto.org/docs/reference/formats/html.html#format-options) option under `format.html` (or add it to `_quarto.yml` to make it the default).
