### DISCUSSION TITLE
Dynamically adding a version number to the footer

### DISCUSSION THREAD

**Discussion by cliffckerr** [quarto-dev/quarto-cli#13001] [Q&A] [answered]
### Description

I'm migrating from Sphinx to Quarto for Python documentation for [Starsim](https://starsim.org). In general, loving it so far :)

However, in Sphinx, you could define variables programatically with `conf.py`, and then these could be used throughout your documentation. I know in Quarto, there's `_variables.yml`, but this is, well ... YAML, so it's a bit limited.

Specifically, for a "website", I wanted to be able to write `page-footer` as ```"Starsim version `{python} starsim.__version__`"```, and have it render as e.g. `"Starsim version 2.3.2"`. 

This didn't work, so I thought maybe I could include a `qmd` file as the footer, but that doesn't work either -- `_quarto.yml` doesn't seem to support commands like `{{< include footer.qmd >}}` (I just get that literal text, instead of the included file).

My workaround is to call a small Python script that dynamically regenerates `_variables.yml` before every Quarto build, and then I can use `"Starsim version {{< var version >}}"` in `_quarto.yml`. But I would much prefer if I could do this as part of the Quarto build process.

Appreciate any help!

**Comment by mcanouil** [comment]
As the footer of what?


Could you share a **small self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? The goal is to make it as easy as possible for us to recreate your problem so that we can fix it: please help us help you! Thanks.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

{{< lipsum 1 >}}

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image]({{< placeholder 600 400 >}}){#fig-placeholder}

{{< lipsum 1 >}}

The end after @fig-placeholder.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code block (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by cliffckerr** [comment]
Sorry, I had hoped that was enough information! It's for a "website" (Python documentation, to be specific). Here's the `_quarto.yml` file:
https://github.com/starsimhub/starsim/blob/rc3.0/docs/_quarto.yml#L24

It's more a general question rather than a specific "bug", but something like this illustrates the issue:
```
website:
  title: "Starsim"
  page-footer:
    center: "Starsim version `{python} starsim.__version__`" # does not render as qmd
    ...
    center: footer.qmd # renders as "footer.qmd" instead of the *contents* of footer.qmd
    ...
    center: {{< include footer.qmd >}} # ditto
    ...
    center: "Starsim version {{< var version >}}" # this works, and is what I ended up doing, but requires a custom script to re-generate _variables.yml each time, which I'd like to avoid
```

**Reply by mcanouil** [reply]
Then use `{{< version >}}` to get the Quarto version.

You can define your own shortcode if you want to compute something else.

You can also use pre-render script to populate your variables.

**Comment by cliffckerr** [comment]
I don't want the Quarto version, I want the version of my package :)

I suppose the [pre-render script](https://quarto.org/docs/projects/scripts.html) is the closest to what I'm looking for, although I simply have it in the opposite order (i.e. I have a script that sets the version number and then calls Quarto, rather than Quarto calling a script that sets the version number and then does the build).

Would love if you could write shortcodes in Python and R instead of Lua, though. And I'm still not clear why the `{{< include >}}` shortcode doesn't work in `_quarto.yml`.

**Reply by mcanouil** [reply]
"include" is not written in Lua (it's TypeScript) and is a copy/paste of QMD documents, so it is executed from documents only before almost everything else.


By the way, why not use [`quartodoc`](https://machow.github.io/quartodoc/get-started/overview.html)?

**Reply by cliffckerr** [reply]
I'm already using `quartodoc` (see [here](https://github.com/starsimhub/starsim/blob/rc3.0/docs/_quarto.yml#L183-L212)), but it doesn't let you dynamically update the footer -- as far as I know!

Anyway, I appreciate your responsiveness on this. It looks like what I already have is already the best option, so I'll close the discussion.

**Reply by mcanouil** [reply]
We don't close discussion because the default filter on GitHub search is `is:open`.

Accessibility: For better accessibility, please ensure link text is descriptive and meaningful rather than using generic terms such as "here". This helps all users understand the link's destination. See [Writing meaningful link text (WCAG)](https://www.wcag.com/blog/writing-meaningful-link-text/).

**Reply by mcanouil** [reply]
[Plotnine documentation](https://plotnine.org/) ([`plotnine` GitHub repository](https://github.com/has2k1/plotnine)) for instance, generates the variable and use that in title to show the version.

**Reply by cscheid** [reply]
> And I'm still not clear why the `{{< include >}}` shortcode doesn't work in _quarto.yml.

Include shortcodes need to appear in what we call "block position" or "in block context". Where do you want to use `include` in _quarto.yml? I can't think of a place where an entry in _quarto.yml would create an entire block. Can you clarify?

**Reply by mcanouil** [reply]
Like this, I believe from the earlier example. (note that `{{< lipsum >}}` and other shortcode works there)

````yaml
project:
  type: website

website:
  title: "demo-footer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    center: |
      {{< include _footer.qmd >}}

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
````

**Reply by cliffckerr** [reply]
Thanks @cscheid and @mcanouil -- this is exactly what I _want_ to work, but it doesn't seem to:

# Input
## _quarto.yml
```
project:
  type: website

website:
  title: "demo-footer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    center: |
      {{< include _footer.qmd >}}

format:
  html:
    theme:
      - cosmo
    toc: true
```
## _footer.qmd
```
© 2025 My Website.
```

## _about.qmd
```
---
title: "About"
---

Lorem ipsum
```

# Output
![image](https://github.com/user-attachments/assets/276f881c-e331-4005-854a-7d5ce734d691 "Even in block position, it's still rendering as `{{< include _footer.qmd >}}` instead of `© 2025 My Website.`")

Even in block position, it's still rendering as `{{< include _footer.qmd >}}` instead of `© 2025 My Website.`.
