### DISCUSSION TITLE
Question regarding listing pages

### DISCUSSION THREAD

**Discussion by n8craig** [quarto-dev/quarto-cli#1384] [Q&A] [answered]
I'm using a listing page for an online exhibit by the NMSU University Museum. It works great to pull a table from the database and leverage parameterized reports along with [`pixture`](https://github.com/royfrancis/pixture) galleries. Unfortunately, am experiencing some issues with Quarto's listing pages. I may not be setting up the YAML correctly.

There are presently 42 items in the collection. The development repository is [here](https://github.com/n8craig/university-museum-pfa) and GitHub pages [here](https://n8craig.github.io/university-museum-pfa/) (it will eventually be on NMSU servers).

Issue:
1. Whether using Grid or Table, there are multiple pages even though I've set `max-items` to 100.
2. When using Table, I still get large size images even though I've set `image-height` to "2". I think as the number of objects increases a table will be a better option.

Is there some error in how I've set up the YAML that's keeping `max-items`  and `image-height` from controlling layout? Also, its confusing why `max-items` wants an unquoted number but `image-height` wants a number in quotes. This makes me think something's not set up right.

Thank you in advance

Here is my YAML for the listing:

```
listing:
  contents: objects
  type: table
  fields: [image, title, description, categories]
  max-items: 100
  image-height: "2"
  sort:
    - "categories"
    - "title"
  categories: true
```

Monster thumbs on table listing
![image](https://user-images.githubusercontent.com/62002677/178845836-9e3f6806-5f2e-466d-aa5c-49ca35e80328.png)

Multiple pages (`max-items: 100`) with monster thumbs (`image-height: "2"`)
![image](https://user-images.githubusercontent.com/62002677/178845999-f1fab41d-4ce0-45f0-adac-255ea14a26bb.png)
