### DISCUSSION TITLE
quarto revealjs presentations vertically center content in columns

### DISCUSSION THREAD

**Discussion by shannonpileggi** [quarto-dev/quarto-cli#1386] [Q&A] [answered]
Is there a away to vertically center content within columns in quarto revealjs presentation?

Something like this, where the slide title stays in place in top left, but content within columns is centered.

```
---
title: "Untitled"
format: revealjs
editor: visual
---

## Quarto

::: columns

::: {.column  width="50%"}
This

is

column 

1
:::

::: {.column  width="50%"}
This is

column 2
:::

:::
```

**Comment by mcanouil** [comment, marked as answer]
The easy part is to get vertically centered the columns contents (not vertically centered in the slide though).

1. Columns vertically aligned to the top but content of the columns vertically centered
   
   <img width="400" alt="Screenshot of Quarto slide with two columns layout where the content is vertically centered" src="https://user-images.githubusercontent.com/8896044/178975740-3d428dec-c8cc-44b9-ab0d-40a4e977292d.png">
   
   <details><summary>See Quarto code + CSS</summary>

   ``` css
   /* file: style.css */
   #vcenter {
     vertical-align: middle;
   }
   ```
   
   ```
   ---
   title: "Untitled"
   format:
     revealjs:
       css: style.css
   ---
   
   ## Quarto
   
   :::: {.columns}
   
   ::: {.column #vcenter width="50%"}
   
   This
   
   is
   
   column 
   
   1
   
   :::
   
   ::: {.column #vcenter width="50%"}
   This is
   
   column 2
   :::
   
   ::::
   ```

   </details>

2. Columns and content vertically centered  
   The tricky part is now to vertically centered `<div class="columns">...</div>` which is nested in a div with `display: block;`.
   
   <img width="400" alt="Screenshot of Quarto slide with two columns layout where the content is vertically center and the columns themselves are vertical centered in the slide" src="https://user-images.githubusercontent.com/8896044/178975772-730e0bf0-8673-4f3e-b254-fdf5b192e6cf.png">
   
   <details><summary>See Quarto code + CSS</summary>
 
   ```css
   /* file: style.css */
   .v-center-container {
     display: flex;
     justify-content: center;
     align-items: center;
     height: 90%;
   }
   ```
   
   ```
   ---
   title: "Untitled"
   format:
     revealjs:
       css: style.css
   ---
   
   ## Quarto
   
   :::: {.columns .v-center-container}
   
   ::: {.column width="50%"}
   
   This
   
   is
   
   column 
   
   1
   
   :::
   
   ::: {.column width="50%"}
   This is
   
   column 2
   :::
   
   ::::
   ```

   </details>

**Reply by shannonpileggi** [reply]
Thank you @mcanouil, these are great solutions!! I really appreciate your time and both options - this is so helpful!

**Comment by michaelschulte** [comment]
Hi, 

I am trying to reproduce the second example with the css (.v-center-container) and get this: 
![image](https://user-images.githubusercontent.com/4051776/195020899-021e06d7-c0d6-46f6-a131-e6f04b2b9a45.png)

I use the above code + css example in a new file, Quarto and (R)Studio up to date ....

Thanks
Michael

**Reply by mcanouil** [reply]
Indeed, it's no longer working ...
Because, there was a change 2 months ago in the CSS for columns (d5a96ed6331a81132aea93a67aeaa3955e0433d4).

To achieve the same behaviour as before, you can use the following CSS which uses `!important`to ensure the display is `flex`:

```css
/* file: style.css */
.v-center-container {
  display: flex !important;
  justify-content: center;
  align-items: center;
  height: 90%;
}
```
