### DISCUSSION TITLE
Setting up permalinks for posts and other categories of content

### DISCUSSION THREAD

**Discussion by sciwonder** [quarto-dev/quarto-cli#1408] [Feature Requests]
I don't know if this is a feature currently (I searched but couldn't find any info on it), but is there a way to set up preferences for permalinks to things like blog posts in `_metadata.yml` in the posts folder? In my previous blog setup (using Hugo and Wowchemy), I had the following in `config.yaml`, for example: 

```
permalinks:
  event: '/talk/:slug/'
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
  post: '/post/:year/:month/:day/:slug'
```

For blog posts, this translated to a hyperlink that started off with the year, followed by month, followed by day, and then the post's slug, which was specified within the post with `slug:` in the YAML header (e.g., //blog-name.netlify.app/post/2022/07/16/slug-for-blog-post/). Others might prefer a smaller hyperlink (e.g., `'/post/:year/:slug'`) or even just the slug. I think setting this up in `_metadata.yml` might provide greater consistency. (Apologies if this feature already exists and I've just missed it in the documentation!)
