### DISCUSSION TITLE
No images in the index page with the posts

### DISCUSSION THREAD

**Discussion by ghost** [quarto-dev/quarto-cli#1418] [Q&A]
I want the default not to show images in the posts: 

For example:

![image](https://user-images.githubusercontent.com/26636184/179307780-18a0c05c-faf1-4d5c-8bbb-728550da4f47.png)

I don't want the images to appear. How I can do this? Any help ?

**Comment by dragonstyle** [comment]
You should be able to customize the field list like so:

```yaml
listing:
  type: default
  contents: posts
  fields: [title, subtitle, author, date, description]
```

HTH!

**Reply by dragonstyle** [reply]
You can learn about the fields and which are displayed by default here:

https://quarto.org/docs/websites/website-listings.html#listing-fields

**Reply by ghost** [reply]
Sadly, did not work. 

What I did is that I went to the `_quarto.yml` file and added the `fields`

**Reply by dragonstyle** [reply]
Sorry - this belongs as a child of the `listing` key, likely in your `index.qmd` file.

Something like

```yaml
---
title: "blog"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  fields: [title, subtitle, author, date, description]
page-layout: full
title-block-banner: true
---
```
