### DISCUSSION TITLE
Multiple pdf files

### DISCUSSION THREAD

**Discussion by Nenuial** [quarto-dev/quarto-cli#1473] [Q&A] [answered]
Is it somehow possible to render two different pdf files from the same document?

I use the LaTeX exam document class to create exercice documents and their solutions at the same time. In rmarkdown I had my own knit function that would iterate over the Rmd, creating the "key" file on the second render.

I tried the following in Quarto, but it only renders the second pdf definition:

````
---
title: Test

format:
  pdf:
    documentclass: exam
  pdf:
    documentclass: exam
    classoption: answers
---

A small test of a LaTeX examdoc.

```{=latex}
\begin{questions}
\question Sample question
```

::: {.solutionorbox data-latex="[2cm]"}
Solution example
:::

```{=latex}
\end{questions}
```
````

Is there any way this could be done?

**Comment by cscheid** [comment, marked as answer]
This should work:
```yaml
format:
  pdf:
    output-file: test-no-answers.pdf
    documentclass: exam
  pdf+answers:
    output-file: test-answers.pdf
    documentclass: exam
    classoption: answers
```

**Reply by Nenuial** [reply]
Works great! Thanks 🙏.

I guess the _manual_ naming of the files is unavoidable? I tried something with output-ext like ".key.pdf" but that seemed to break the pdf.

**Reply by cderv** [reply]
Just an update for recent readers who find this, the naming of the output file now uses the modifiers. 

````markdown
---
title: test
format:
  pdf:
    toc: false
  pdf+toc:
    toc: true
---

# test
````

This will use   `+toc` in the output file name.

**Reply by DOH-FAA3303** [reply]
@cderv @cscheid I'm having trouble executing two different pdf formats with figures (i think). I'm using quarto version 1.4.358. For example, I was able to output two custom pdf files but I get an error when adding a figure to the index.qmd file.

Here's what works:

_quarto.yml
````_quarto.yml
project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    citations-hover: true
    crossrefs-hover: true
    toc: true
    toc-location: left
    title-block-style: manuscript
    format-links: [pdf, pdf+other, docx]
  docx: default
  jats: default
  pdf: 
    toc: true
  pdf+other:
    toc: false

````

index.qmd:
````
---
title: Idk
authors:
  - name: Norah Jones
    affiliation: The University
    roles: writing
    corresponding: true
bibliography: references.bib
---

## Section
This is a simple placeholder for the manuscript's main document [@knuth84].
````


**Here's what does not work**

index.qmd

````
---
title: Idk
authors:
  - name: Norah Jones
    affiliation: The University
    roles: writing
    corresponding: true
bibliography: references.bib
---

## Section
This is a simple placeholder for the manuscript's main document [@knuth84].

```{mermaid}
%%| fig-width: 7
timeline
    title Timeline of Covid-19 Sequencing Efforts
    2021 : Feb - idk what happened
```

````


I am able to render to a single pdf with the above qmd, just not with two pdf formats.

This is the error

````
ERROR: NotFound: The system cannot find the file specified. (os error 2): lstat 'C:\Users\FAA3303\projects\personal-repos\idk\index_files\figure-latex'

Stack trace:
    at Object.lstatSync (ext:deno_fs/30_fs.js:343:7)
    at copySync (file:///C:/Program%20Files/Quarto/bin/quarto.js:9515:26)
    at createTexOutputBundle (file:///C:/Program%20Files/Quarto/bin/quarto.js:91881:17)
    at Object.beforeMoveOutput (file:///C:/Program%20Files/Quarto/bin/quarto.js:91710:29)
    at renderProject (file:///C:/Program%20Files/Quarto/bin/quarto.js:76621:47)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async Command.fn (file:///C:/Program%20Files/Quarto/bin/quarto.js:80606:32)
    at async Command.execute (file:///C:/Program%20Files/Quarto/bin/quarto.js:8111:13)
    at async quarto (file:///C:/Program%20Files/Quarto/bin/quarto.js:111318:5)
    at async file:///C:/Program%20Files/Quarto/bin/quarto.js:111336:9
````


**Is this an issue with outputting the same figure to multiple pdfs? is there a way specify a different figure name with each pdf format?**
