### DISCUSSION TITLE
A single extension with multiple custom formats based on the same built-in format

### DISCUSSION THREAD

**Discussion by RLesur** [quarto-dev/quarto-cli#1510] [Q&A]
Hi,

My use case is the following: I want to create and dstribute two `revealjs` custom formats in the same extension. These custom formats share some components but they use different filters and resources.

The documentation clearly explains how to do that [for different bulit-in formats](https://github.com/quarto-dev/quarto-web/blob/ac765d14513c9a4042acc1385977213e1f3416c6/docs/extensions/_formats-common.qmd#L29-L39).

On the advice of @cderv, I tried to use [modifiers](https://github.com/quarto-dev/quarto-cli/discussions/1473#discussioncomment-3193247) in the `_extension.yml` file... without any success.

Is it possible to do that for now?

**Comment by dragonstyle** [comment]
Unfortunately, right now the modifiers aren't supported in the extension yaml (it allows you to target only the core pandoc format). 

You could make more than one extension in a single repo (more directories in the `_extensions` dir). When a user installs using the repo, all the extensions contained will be installed, so that would be a nice way to distribute a couple different format extensions. 

The sharing between extensions would be worse (e.g. each extension will need its own copy of resources and so on). You could keep separate copies of those resource, or there is a notion of format extensions using embedded extensions. If they share shortcodes or filters, you can bundle those up into yet a third extension and embed that into these formats.

The command to do this is 

`quarto install extension <org>/<ext> --embed <ext-name-to-embed-within>`

You can see an example of this approach here:

https://github.com/quarto-journals/acs

Where a filter and shortcode extension are embedded within the ACS format. You can see that the `_extension.yml` can refer to the filter and shortcode extensions in its yaml to enable them.

Not a perfect answer, but hopefully this gets you a couple ideas about how you might accomplish this. Happy to chat more- extensions are very new and have some room to grow so learning about what people are doing with them is very important to us!

**Reply by mcanouil** [reply]
The common/shared part could be added to the extensions as a git submodule which kind of reproduce the "embed" option.
The submodule can be keep up to date using GitHub Action for example.

**Reply by RLesur** [reply]
Thanks a lot for the answer!

I wonder whether an extra key in the extension yaml file could help to differentiate custom formats. Something like that:

``` yaml
contributes:
  format:
    common:
      # common options
    revealjs:
      kind: internal
      # myorg-internal-revealjs specific format
    revealjs:
      kind: external
      # myorg-external-revealjs specific format
    pdf:
      kind: letter
      # myorg-letter-pdf specific format
    pdf:
      kind: report
      # myorg-report-pdf specific format
```
