### DISCUSSION TITLE
Large '_files' folder created by RStudio, causing slow version control with Git

### DISCUSSION THREAD

**Discussion by tlyim** [quarto-dev/quarto-cli#1537] [Q&A] [answered]
When using quarto in RStudio for Windows, it creates a large '_files' folder (5.49MB) causing slow version control with Git for the initial commit. A different large '_files' folder is created for each .qmd file, although the files in the folder look identical. 

![_files folder](https://user-images.githubusercontent.com/10102234/181069954-d90c9798-252d-4128-8fdd-dbabd3e9426e.png)

Such duplicated large '_files' folders (5.49MB), even for a minimum example like the following, freeze the Git version control operation.

Is there a workaround for this issue?

```
---
title: "Minimum Example"
format: revealjs
editor: visual
---

## Minimum Example

- item 1.0
  - item 1.1
  - item 1.2
- item 1.0
  - item 1.1
  - item 1.2

::: {.fragment}
- item 1.0

  ::: {.fragment}
  - item 1.1
  :::
  
  ::: {.fragment}
  - item 1.2
  :::
::: 
```

**Comment by cscheid** [comment, marked as answer]
There are a few ways to handle this:

1. Add entries such as `*_files` to your .gitignore file (see [this tutorial for information on the syntax to use](https://www.freecodecamp.org/news/gitignore-what-is-it-and-how-to-add-to-repo/)). This will prevent git from adding those build artifacts to the repository.
2. If you nevertheless want to check in build artifacts like these, and if you have a larger set of pages and you want to render all of them, you might want to consider a quarto website. This will make sure that these resource files are shared across your generated HTML files.

**Reply by jakobarendt** [reply]
@cscheid, can I also add `*_files/` to my .gitignore if I want to use GitHub Actions for publishing without executing code (i.e. by checking in the `_freeze/` directory), as described [here](https://quarto.org/docs/publishing/github-pages.html#publish-action)? Or does successful rendering in such a setup depend on the `*_files/` directories not being ignored by Git?

**Comment by tlyim** [comment]
@cscheid  Thank you for your suggestons. Very helpful.

For other beginners who also prefer the second suggestion (quarto website: https://quarto.org/docs/websites/#rstudio), I started a new quarto project for revealjs presentations under my subdirectory for git repos (eg, `D:/github/quarto/revealjs`). Next I added the global specification in the _quarto.yml file there, like

```
project:
  type: website

website:
  title: "revealjs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


include-after-body:
  text: |
    <style>
    .reveal .slide ul {
      margin-bottom: 0;
    }
    </style>
```

The last part above is due to my preference from [this discussion](https://github.com/quarto-dev/quarto-cli/discussions/1459#discussioncomment-3208017).  

Then all .qmd files created in the /revealjs subdirectory or its lower-level subdirectories will follow the global specification and will not create separate `_files` subfolders that waste storage space.

**Reply by roland-KA** [reply]
That's really helpful and avoids the generation of a revealjs-subfolder for each document.

Is it possible to bring that one step further? I'm also using Quarto to produce revealjs presentations. I.e. it isn't my intention to create a web site. Therefore my `format` section looks as follows:

```yaml
format:
  revealjs:
    theme: [default, lecture.scss]
    chalkboard: true
    scrollable: true
```

But using `format: revealjs` doesn't give me the possibility to automatically create an `index.html`-file with a navigation bar etc.

So my question is: Is it possible to create the `index.html` (in the form it is done using `format: html`) but convert the individual documents into a revealjs-presentation (using some custom theme)?
