### DISCUSSION TITLE
ERROR: The format pdf does not support providing any template partials.

### DISCUSSION THREAD

**Discussion by fuhrmanator** [quarto-dev/quarto-cli#1555] [Q&A] [answered]
I'm trying to redefine the title.tex partial to allow for a `titlehead` metadata.

I think I redefined it properly (copied from the source at https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/pdf/pandoc/title.tex) and then linked to it in my metadata:

```yaml
format:
  pdf:
    template-partials:
      - title.tex
```

Whenever I try to run (Windows, Quarto 1.0.37) a preview/render, I get the error:

> ERROR: The format pdf does not support providing any template partials.

Is this feature supported?

**Comment by dragonstyle** [comment, marked as answer]
Yes it is supported- we use it extensively in `quarto-journals` and elsewhere. Can you provide a sample project that reproduces this error for us?

**Reply by fuhrmanator** [reply]
Sorry, my other reply was by email (not realizing it would make another answer). Anyway, to customize templates with a book project, yesterday I realized it works if you use 

```yaml
format:
  pdf:
    template: my-custom-template.tex
```

I found this info misleading because https://quarto.org/docs/reference/formats/pdf.html#rendering shows a `template-partials` (if you search on the quarto site for `partials` you'll see a hit for this). I had imagined I could just customize the partial only for my book project, not realizing that this only works if you're using an extension.

**Reply by dragonstyle** [reply]
You can use partials as well. This `_quarto.yml`, for example, should work (and does when I test it locally):

```yaml
project:
  type: book

book:
  title: "Book"
  author: "Jane Doe"
  date: "10/20/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    template-partials:
      - title.tex
```

with contents of file `title.tex`

```tex
\title{Partial Says: $title$}
```

**Reply by fuhrmanator** [reply]
Thanks for the details.

It doesn't work for me, and it seems the problem is the pdf engine:

```yaml
format:
  pdf:
    pdf-engine: latexmk
```

If I use the default `pdf-engine` (don't specify) the error doesn't show. My book project requires `latexmk` because of the SVG files; it's the only engine that automagically gets them into the PDF.
