### DISCUSSION TITLE
Hybrid Navigation: Different Sidebars for sub-sections (below top level of nav menu)

### DISCUSSION THREAD

**Discussion by stuvjordan-uroc** [quarto-dev/quarto-cli#1602] [Q&A] [answered]
Hello all...

I'm building a site that's going to contain a section with a few sub-levels, like this:

Section
--Subsection 1
----article 1
----article 2
----[...more articles...]
--Subsection 2
----article 3
----article 4
----[...more articles...]
--[...more Subsections containing more articles]

I'd like to have *different* contents in the right-hand navigation for each of the Subsections above.  For instance, the side nav for 'Subsection 1' should only have links to the articles in Subsection 1.  However, I do NOT want the subsections to be top-level items in the horizontal nav across the top of the site.

It seems from the docs that this is not an option.  The explanation at https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation shows different side nav for each of the top-level items in the top nav.  It doesn't show a way to create a side nav that is specific to a site area that is only accessible as an item that appears in a dropdown from the nav.

Am I correct that a side-nav varies across different subsections is not an option?

(By the way, there will be too many subsections in my site to create a separate top-level top-nav item for each one!)

Thanks!

**Comment by stuvjordan-uroc** [comment, marked as answer]
Answering my own question!  The answer is: "No, I'm not correct!" .  Quarto DOES allow you to set up separate side nav for subsections of the site that are nested within a top-nav dropdown menu.  Here's an example of a `_quarto.yml` that has this effect:

```
project:
  type: website

website:
  title: "FANTASTIC WEBSITE!"
  navbar:
    background: primary
    right:
      - text: "Section"
        menu: 
          - text: "SubSection 1"
            file: subsection1/index.qmd 
          - text: "SubSection 2"
            file: subsection2/index.qmd
        
  sidebar:
    - title: "SubSection 1"
      contents:
        - subsection1/index.qmd
        - subsection1/article1.qmd
        - subsection1/article2.qmd
    - title: "SubSection 2"
      contents: 
        - subsection2/index.qmd
        - subsection2/article1.qmd
        - subsection2/article2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

```
The key thing seems to matching the 'title' for each sidebar to the title for the desired item from the nav dropdown menu.
