### DISCUSSION TITLE
Removing Numbering from chapters in quarto Book

### DISCUSSION THREAD

**Discussion by shafayetShafee** [quarto-dev/quarto-cli#1607] [Q&A]
Is there any global option to set in `book` so that all of the chapters are not numbered?

 As I am seeing in the docs it can be done by adding `{.unnumbered}` to each chapter's main heading. But is there any global option to do this without using `{.unnumbered}` in each case so that all of the chapters of the book will be unnumbered ?? Thanks 😊😊😊

**Comment by mcanouil** [comment]
I am not sure there is an option in any of the tools used by Quarto to skip numbering in headers of a specific level.

Although, it's possible to write a Lua filter to remove numbering at a specify level (it will just do automatically what currently has to be done manually).

**Reply by shafayetShafee** [reply]
Would you kindly point me to a direction from where I can learn how to write lua filter and use that with quarto documents. ( I don't have a tiny bit of clue about lua filter) Thanks

**Reply by shafayetShafee** [reply]
Ok found a place for knowing about [`lua filter`](https://quarto.org/docs/extensions/lua.html).

**Comment by rgaiacs** [comment]
@shafayetShafee have you try `number-sections: false`?

The following worked for me

```
project:
  type: book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "8/18/2021"
  chapters:
    - index.qmd

editor: visual

format:
  html:
    number-sections: false
```
