### DISCUSSION TITLE
Can the footer area of a Quarto (Revealjs) presentation be coloured?

### DISCUSSION THREAD

**Discussion by matt-dray** [quarto-dev/quarto-cli#1645] [Q&A] [answered]
I'm trying to create a coloured bar at the bottom of a Quarto presentation (Revealjs format), like the one that appears at the bottom of [this slide](https://matt-dray.github.io/targets-dsfest/#15):

![A screenshot of a presentation slide with a white background and a blue border on the bottom edge only.](https://user-images.githubusercontent.com/18232097/182436479-48063a6a-f465-462f-92f0-1671facda134.png)

I created that slide with {xaringan} and in [my custom CSS](https://github.com/matt-dray/targets-dsfest/blob/master/styles/custom.css) I specified it with `border-bottom` supplied to `.remark-slide-content`:

``` css
.remark-slide-content {
  color: #000;
  font-size: 40px;
  border-bottom: 35px solid #006682; 
  padding: 0 50px 0 50px;
}
```

I see [there's a `footer` option](https://quarto.org/docs/reference/formats/presentations/revealjs.html#slide-content) for the `revealjs` format—which I've seen others use for [text or links](https://github.com/jthomasmock/arrow-dplyr/blob/c2a5b529288c102bf79ba1844205c8eec3d7b9a2/test.qmd#L7)—but I'm not sure if this can be used to colour it.

Is there a way in Quarto/Revealjs to colour the footer area directly, or perhaps there's more of a hacky approach, like the one for {xaringan} above?

**Comment by melissavanbussel** [comment, marked as answer]
You can take a very similar approach with Quarto! Rather than `.remark-slide-content` in your custom CSS file, use `.reveal .footer > *`. 

Example .qmd file: 

~~~
---
title: "Your title goes here"
format: 
  revealjs:
    footer: "Footer text goes here"
    menu: false
editor: visual
css: style.css
---

## This is a slide title

This is some text.
~~~

In the `style.css` file: 

~~~
.reveal .footer > * {
	background-color: #006682;
	color: white;
}
~~~

This produces the following: 

<img width="544" alt="image" src="https://user-images.githubusercontent.com/28693927/194975803-76aa3a7d-c822-4ec8-9aab-f42288e4854f.png">

**Reply by matt-dray** [reply]
Superb, thank you for your help.

**Comment by thebigdalt** [comment]
I know this has been answered already, but the provided answer didn't work for me. Perhaps something has changed since then. Instead, the following worked for me. 

Example `.qmd` file

```md
---
title: "Your title goes here"
format: 
  revealjs:
    logo: custom-logo.png
    footer: "Footer text goes here"
    theme:
      - default
      - custom.scss
---

## This is a slide title

This is some text.
```

Example `custom.scss`

```scss
/*-- scss:defaults --*/

$custom-background: #0000ff !default;

/*-- scss:rules --*/

.reveal .footer {
    color: #ffffff;
    background-color: $custom-background;
    display: block;
    position: fixed;
    padding-bottom: 12px;
    padding-top: 12px;
    bottom: 0px !important; // Makes footer div flush with bottom of slide
    width: 100%;
    z-index: 2 !important; // Sets the footer div further down the z-index
  }
  
.reveal .slide-logo {
    margin-bottom: 6px !important; // Lowers logo more in line with rest of footer
    z-index: 5 !important; // Keeps logo above footer div
  }
```
