### DISCUSSION TITLE
Kernel died before replying to kernel_info

### DISCUSSION THREAD

**Discussion by hebertodelrio** [quarto-dev/quarto-cli#1652] [Q&A]
I am trying to run quarto on the following qmd file:

```
---
title: Unitful incompatible
author: Lightup
format:
  html:
    code-fold: true
jupyter: julia-1.7
execute:
  daemon: 60
# ipynb-filters:
#   - inline_code.py
---
```

```{julia}
using Unitful
d=40u"μm"
```

Unfortunately I get the following error:

quarto preview juliatest.qmd
ERROR:

Kernel died before replying to kernel_info

Any suggestions as to why and how to fix it?

I am running this on OS X, with conda 4.11.0, quarto 1.0.37, I installed Julia using conda, and I got version 

BTW: I ran quarto convert juliatest.qmd, and after starting Jupiter notebook I am able to execute the one code cell without any problem, so the issue is not the kernel.
