### DISCUSSION TITLE
Verbosity?

### DISCUSSION THREAD

**Discussion by hebertodelrio** [quarto-dev/quarto-cli#1671] [Q&A]
Is there any way to 'see' all the steps that quarto is going through when it runs? In order to figure out where a problem is occurring without know all the details of the design is to follow the important steps of the process.

For example, when a PDF file is produced from a QMD file, an IPYNB is produced, does an MD is produced? does pandoc calls tex to produce the PDF file? where are the auxiliary files stored? Can they be kept? etc.

Many of the issues in this discussion can be more easily debugged/treated if we were to have all these answers.

I hope someone from the quarto teams sees this post

**Comment by rgaiacs** [comment]
> Is there any way to 'see' all the steps that quarto is going through when it runs?

Yes. You can use

```
format:
  html:
    keep-md: true
    keep-ipynb: true
  pdf:
    keep-md: true
    keep-ipynb: true
    keep-tex: true
  docx:
    keep-md: true
    keep-ipynb: true
```

in the YAML.

> For example, when a PDF file is produced from a QMD file, an IPYNB is produced, does an MD is produced?

My understanding is that for a `.qmd` file with Python code using Jupyter instead of knitr + reticulate, Quarto will do something like `.qmd` > `.ipynb` (with output of code cells) > `.md` > `.tex` > `.pdf`.

> does pandoc calls tex to produce the PDF file?

Yes. The PDF files are generated using LaTeX.

**Reply by hebertodelrio** [reply]
Do you know where are the auxiliary files created by the Tex engine saved?

aux
log
etc, etc, etc

When I include the metadata you suggested:

~~~
---
title: TLMGR Problems
format:
  html:
    keep-md: true
    keep-ipynb: true
  pdf:
    keep-md: true
    keep-ipynb: true
    keep-tex: true
  docx:
    keep-md: true
    keep-ipynb: true
---

**Hello World!**

```{python}
d="Hello World!"
```
~~~

The following files are created:
-rw-r--r--  1 heberto  staff   8480 Aug  3 21:35 minimaltest.html
-rw-r--r--  1 heberto  staff   1270 Aug  3 21:35 minimaltest.ipynb
-rw-r--r--  1 heberto  staff    392 Aug  3 21:35 minimaltest.md
drwxr-xr-x  1 heberto  staff     36 Aug  3 21:35 minimaltest_files

The last one is a directory that contains three directories inside:
drwxr-xr-x  1 heberto  staff  36 Aug  3 21:35 figure-pdf
drwxr-xr-x  1 heberto  staff  36 Aug  3 21:35 libs
drwxr-xr-x  1 heberto  staff  36 Aug  3 21:35 mediabag

But none of the contains any of the auxiliary files created by TeX, which is a problem because at running
```
% quarto render minimaltest.qmd

Starting python3 kernel...Done

Executing 'minimaltest.ipynb'
  Cell 1/1...Done

pandoc
  to: html
  output-file: minimaltest.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: TLMGR Problems


Starting python3 kernel...Done

Executing 'minimaltest.ipynb'
  Cell 1/1...Done

pandoc
  to: latex
  output-file: minimaltest.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: TLMGR Problems

running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages

compilation failed- missing packages (automatic installation failed)
```

tlmgr is not able to create a PDF file since it fails to update some packages, that so far are unknown to me, which is why I am trying to figure out where the auxiliary files are saved, if they are. No PDF since it does not create a TeX file either.

**Reply by dragonstyle** [reply]
They would be in the same directory as the source qmd (with the tex file). Is there a tex file there?

**Reply by rgaiacs** [reply]
I have the following files

`_quarto.yml`:

```
project:
  title: "testlatex"

format:
  pdf:
    keep-md: true
    keep-ipynb: true
    keep-tex: true
```

`testlatex.qmd`

```
---
title: "testlatex"
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.
```

When I build it using RStudio IDE, I get

```
pandoc 
  to: latex
  output-file: testlatex.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: testlatex
  
running xelatex - 1

No TeX installation was detected.

Please run 'quarto install tool tinytex' to install TinyTex.
If you prefer, you may install TexLive or another TeX distribution.


Exited with status 1.
```

I know. I don't have LaTeX in my machine. But the files were created:

```
$ ls . -1
_quarto.yml
testlatex_files/
testlatex.md
testlatex.qmd
testlatex.Rproj
testlatex.tex
```

@dragonstyle could you

- [ ] provide the output of `quarto check`
- [ ] provide the output of  `quarto tools check`
- [ ] make sure that you have the following LaTeX package installed in your machine?

```
$ grep usepackage testlatex.tex | sort
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{float}{}{\usepackage{float}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{amsmath,amssymb}
\usepackage{calc} % for calculating minipage widths
\usepackage{etoolbox}
\usepackage{graphicx}
\usepackage{iftex}
\usepackage{lmodern}
  \usepackage[]{microtype}
    \usepackage{parskip}
  \usepackage{selnolig}  % disable illegal ligatures
  \usepackage[T1]{fontenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{unicode-math}
  \usepackage[utf8]{inputenc}
\usepackage{xcolor}
```
