### DISCUSSION TITLE
Is there a way to set table-title?

### DISCUSSION THREAD

**Discussion by Gabrielforest** [quarto-dev/quarto-cli#1727] [Q&A] [answered]
Hi! I would like to change the table title `Table 1` for Portuguese as I do with toc-title:
![image](https://user-images.githubusercontent.com/63704591/183314510-f3e52c2b-61e8-4437-8576-46c0c7e99121.png)

Unfortanely I couldn't make it using `table-title`. Is there a way to do this?

**Comment by jjallaire** [comment, marked as answer]
You should be able to use `lang: pt` to get Portuguese for all UI text: https://quarto.org/docs/authoring/language.html

If you don't like the translations then you can override them individually (the table title is controlled by `crossref-tbl-title`):

https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml

**Comment by rgaiacs** [comment]
Late for the party.

Hi @Gabrielforest. Did you try to use `lang: pt` in the YAML?

The follow minimal working example works for me!

`_quarto.yml`:

``` 
project:
  type: book

book:
  title: "Minimal Working Example"
  author: "Raniere Silva"
  date: "08/08/2022"
  chapters:
    - index.qmd

lang: pt

format:
  html:
    theme: cosmo
```

`index.qmd`:

`````` 
# Preface {.unnumbered}

Texto @tbl-sample Texto

```{r}
#| label: tbl-sample
#| tbl-cap: Sample

tibble::tibble(
  x = c(1, 2),
  y = c(1, 2)
) |> knitr::kable()
```
``````

![Screenshot from 2022-08-08 08-37-41](https://user-images.githubusercontent.com/1506457/183317933-d9305b8f-e628-453f-aa32-4b6e6cd27421.png)

Quarto uses LaTeX to generate the PDF and from my experience, changing the language will get what you want. You probably will not have to use `toc-title`! Try `pt-BR` and `pt-PT` as they have some differences.
