### DISCUSSION TITLE
YAML property to ignore HTML in website title?

### DISCUSSION THREAD

**Discussion by MayaGans** [quarto-dev/quarto-cli#1736] [Q&A] [answered]
Hi! I want to set my website title to 

```
title: maya<br>gans
```

but I want it it to show up in the title element as maya gans. I was wondering if there's like an html in title property that will treat the title as html and not a string? Is that possible?

**Comment by mcanouil** [comment]
You have to use `pagetitle` to change the title of the page in browser.
`pagetitle` is set to `title` by default.

**Reply by MayaGans** [reply]
Hi! Thanks for your response @mcanouil - I couldn't find the `pagetitle` in the docs but tried using this in my quarto website

```
website:
  title: "maya<br>gans"
  pagetitle: "Maya Gans"
```

but it looks like only the title attribute is respected? Thanks for your help!

**Reply by MayaGans** [reply]
Ooh found it here: https://quarto.org/docs/reference/formats/html.html and tried this because it's under metadata but I guess I'm still messing this up...

```
website:
  title: "maya<br>gans"
  metadata:
    pagetitle: "Maya Gans"
```

**Comment by MayaGans** [comment, marked as answer]
Oh I got it!!! 

```
project:
  type: website

website:
  title: "maya<br>gans"

.....
        
format:
  html:
    metadata:
      pagetitle: "Maya Gans"
```

**Comment by EllaKaye** [comment]
Hey @MayaGans, there's a better solution for our use case - just set the navbar title:

```
website:
  title: "maya gans"
  navbar:
    title: "maya<br>gans"
```

That way, you can do styling on how the title appears in the navbar, but the website title, as it appears in browser tabs, doesn't have any HTML and therefore we don't need `pagetitle`. Also, it solves the problem we had when using `pagetitle` of the tab titles not updating as we navigate around the site.
