### DISCUSSION TITLE
Quarto Cloudflare Pages plugin

### DISCUSSION THREAD

**Discussion by jimjam-slam** [quarto-dev/quarto-cli#1776] [Feature Requests]
The Quarto [Netlify plugin](https://github.com/quarto-dev/netlify-plugin-quarto) and [GitHub Actions](https://github.com/quarto-dev/quarto-actions) work great!

One other publisher we've been using a lot is [Cloudflare Pages](https://pages.cloudflare.com). It uses the same JAMstack model as Netlify, but it comes with some nice extras like free unlimited bandwidth and free access control for up to 50 users (although admittedly that can be a bit of a pain to configure).

Cloudflare Pages supports [plugins](https://developers.cloudflare.com/pages/platform/functions/plugins). I'm admittedly not too clear on how differently they function to Netlify's build plugins, but [anecdotes](https://pustelto.com/blog/how-and-why-i-have-migrated-from-netlify-to-cloudflare/#build-plugins) seem to indicate they're pretty similar! 😅 

You can, of course, render locally and deploy the rendered folder to Pages (just like Netlify or any other static host), but I wanted to put it on your radar!

**Comment by burgerga** [comment]
If you want to use Quarto with Cloudflare Pages, you only need to make very small changes to your Github action: since pushing to the `gh-pages` branch will automatically update your repo settings to use the `gh-pages` branch to serve Github Pages, this needs to be updated to a different branch. The steps:

1. Create your quarto site
2. Create `.github/workflows/publish.yml` from https://quarto.org/docs/publishing/github-pages.html#publish-action
3. Split render and publish into two steps 
    - Use `quarto-dev/quarto-actions/render` instead of `quarto-dev/quarto-actions/publish`
    - Use https://github.com/peaceiris/actions-gh-pages to publish to the `cf-pages` branch, from the rendered `_site` (or `_book` directory, depending on your quarto project)

Example `.github/workflows/publish.yml` file: 
```yaml
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: cf-pages
          publish_dir: _site
```

Then create the Pages application in your Cloudflare Pages dashboard and point it to the `cf-pages` branch of your repo (you can leave all the build config empty).

### Adding a password to your pages site
You can use CloudFlare Zero Access to add access control to your Pages application (free for up to 50 users), see https://developers.cloudflare.com/pages/platform/known-issues/#enable-access-on-your-pagesdev-domain. 
Alternatively, if you just want to add a password to your site, you can follow the steps at https://github.com/Charca/cloudflare-pages-auth. To make sure the `functions` directory ends up in your `cf-pages` branch, add the `functions` directory to the `resources` option (https://quarto.org/docs/reference/projects/options.html) in your `_quarto.yml`, e.g.:

```yaml
project:
  type: website
  resources:
  - functions/

...
```
