### DISCUSSION TITLE
Defining LaTeX commands for HTML and PDF rendering

### DISCUSSION THREAD

**Discussion by dmbates** [quarto-dev/quarto-cli#1793] [Q&A] [answered]
First let me again express my thanks for quarto and the skill and dedication of its developers.  It has made my life a lot easier.

In working on a book at the repository https://github.com/JuliaMixedModels/EmbraceUncertainty I have been able to create HTML output but have problems with PDF related to LaTeX macros.  An attempt to render the first chapter (intro.qmd) to PDF ends with
```
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages

compilation failed- error
Undefined control sequence.
l.362 represented by the random variable \(\mcY
                                               \). (We use upper-case 

```
At the beginning of `intro.qmd` \mcY is defined as
```
\newcommand\mcY{{\mathcal{Y}}}
```
and rendering to HTML is quite happy with that definition.

I can't decide why the HTML rendering picks up this definition but the PDF doesn't.  (I am using TinyTeX installed through `quarto tools`.)

If someone could point me in the right direction I am happy to do more debugging myself or create  an MWE (you don't want to mess around with installing Julia and Julia packages and Jupyter, etc., just to debug this.)  It's about time that I did more exploration of saving intermediates, freezing Jupyter results, etc.  I just don't quite know where to start.

**Comment by cscheid** [comment]
What I _think_ is happening here is that latex doesn't like `\newcommand` in math mode, while MathJax probably accommodates that (for obvious reasons.)

You can see roughly what's going on by this minimal example:

    ---
    title: Test
    ---
    
    ::: {.hidden}
    $$
    \newcommand\mcy{{\mathcal{y}}}
    $$
    :::
    
    Will this work? $\mcy = 3$.

Now, let's try to render this to a latex document (_not_ a pdf document):

    $ quarto render newcommand-test.qmd --to latex

Note that the output here is now a _latex_ file, which helps with debugging error messages:

```
pandoc
  to: latex
  output-file: newcommand-test.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Test

Output created: newcommand-test.tex
```

Now look at the end of this file:

```
$ tail newcommand-test.tex

\[
\newcommand\mcy{{\mathcal{y}}}
\]

Will this work? \(\mcy = 3\).

\end{document}
```

So one way to make this work is to use our format-specific hiding code:

    ---
    title: Test
    ---
    
    ::: {.content-hidden unless-format="html"}
    $$
    \newcommand\mcy{{\mathcal{y}}}
    $$
    :::
    
    ::: {.content-hidden unless-format="pdf"}
    ```{=latex}
    \newcommand\mcy{{\mathcal{y}}}
    ```
    :::
    
    Will this work? $\mcy = 3$.

This will generate the content you're expecting.
