### DISCUSSION TITLE
adding color/BG usage to the title slide (using YAML) possible?

### DISCUSSION THREAD

**Discussion by zeltak** [quarto-dev/quarto-cli#1796] [Q&A] [answered]
Hi again

I searched and googled for an hour with no success. is it possible at all to add a BG image or BG color to the rendered reveal.js presentation via the YAML section?

here is an example code:

```
---
title: "An Introduction to data science"
subtitle: ""
date: "(Updated: `r Sys.Date()`)"
format:
  revealjs:
    logo: "" 
    scrollable: true
---

I tried using the  `background-image: "IMAGE"}` option which works in headers with no success

thx so much!

Z

**Comment by mcanouil** [comment, marked as answer]
Like this? (options partially described in https://quarto.org/docs/reference/formats/presentations/revealjs.html)

```
---
title: "Untitled"
format:
  revealjs:
    title-slide-attributes:
      data-background-color: "#b22222"
---

# Header 1

## Header 2
```
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8896044/183956137-dee33fdb-c9f8-4d4b-8e2c-062a19a8350d.png">
