### DISCUSSION TITLE
url associated with a logo in the navbar

### DISCUSSION THREAD

**Discussion by hardin47** [quarto-dev/quarto-cli#1833] [Q&A] [answered]
Is there any way to connect the logo in the navbar with a url?  I'm thinking something like this:

```
website:
  navbar:
    title: "Website Title"
    logo: images/mylogo.png
       logo-href: some-url-to-go-to-when-clicking-on-logo
```

**Comment by dragonstyle** [comment, marked as answer]
Yes- the latest prerelease supports `logo-href`- give it a try!

**Reply by hardin47** [reply]
great!  meanwhile...  i'm  little bit confused about how to get a pre-release of quarto.  as far as i can tell, it isn't a *package*, right?  so it isn't the same as using a dev version of a package from github?  so does that mean i should get the latest version of RStudio?  but it isn't really the latest release, it's the latest pre-release?  can you maybe point me to a website where i can get the latest prerelease of quarto?

thank you!!

**Reply by hardin47** [reply]
ahhh!   if I go here, i just download the macos version (i'm on a mac).  https://github.com/quarto-dev/quarto-cli/releases/tag/v1.1.60

meanwhile, for anyone who wants the full syntax, this is what worked for me (with noindent and quotes):

```
website:
  navbar:
    title: "Website Title"
    logo: images/mylogo.png
    logo-href: "some-url-to-go-to-when-clicking-on-logo"
```

thank you so much for the lightening quick help!!  i really appreciate it.

**Reply by dragonstyle** [reply]
You figured it out- great! Sorry to be late, but for others who see this here is a more friendly prerelease  download page

https://quarto.org/docs/download/prerelease.html

**Comment by hardin47** [comment]
Sorry to belabor this point, but I just realized that the `logo-href` supersedes the `site-url` link.  Is that intentional?  Is there any way around it?

Previously, using distill (https://m158-lin-mod.netlify.app/), the logo has a separate URL from the site (e.g., the logo vs the words "Linear Models"):

![image](https://user-images.githubusercontent.com/7210585/184886480-4599e36b-243c-4a07-9bce-31ed01ef49c5.png)

```
name: "m158-lin-mod"
title: "Linear Models"
base_url: https://m158-lin-mod.netlify.app/
navbar:
  logo:
    image: images/st47s.png
    href: https://hardin47.netlify.app/
```

Now, (https://m152-stat-theory.netlify.app/) it seems as though the `logo-href` will take over both the logo and the words "Statistical Theory") regardless of the `site-url` value.

![image](https://user-images.githubusercontent.com/7210585/184888379-0ce8cbd1-fb3f-4e7e-9620-6cca9bc2675b.png)

Option 1:  The words "Statistical Theory" link to https://m152-stat-theory.netlify.app/ and logo does not link.

```
website:
  title: "Statistical Theory"
  favicon: "images/favicon.ico"
  site-url: https://m152-stat-theory.netlify.app/
  navbar:
    logo: images/st47s.png
```


Option 2: Both the logo and the words "Statistical Theory" link to https://hardin47.netlify.app/

```
website:
  title: "Statistical Theory"
  favicon: "images/favicon.ico"
  site-url: https://m152-stat-theory.netlify.app/
  navbar:
    logo: images/st47s.png
    logo-href: "https://hardin47.netlify.app/"
```


Preferred Option:  The logo to link to https://hardin47.netlify.app/ and the words "Statistical Theory" to link to https://m152-stat-theory.netlify.app/
