### DISCUSSION TITLE
How to to change all font to be the same for PDF output?

### DISCUSSION THREAD

**Discussion by rbcavanaugh** [quarto-dev/quarto-cli#1976] [Q&A] [answered]
I've been looking through the documentation and I'm can't find the answer (apologies, I'm not as familiar with PDF output and have minimal understanding of latex). 

In a normal pdf output, the title/header fonts are sans-serif while the text itself is a serif font. How can I make all font the same in the pdf. (e.g., all serif, such as time new roman or all sans-serif, such as Helvetica). I tried changing the `mainfont` and `sansfont` arguments without any luck. thanks!

**Comment by rbcavanaugh** [comment, marked as answer]
I was able to get this to work using the following, but I perhaps there could be a more thorough (step-by-step) guide/vignette for modifying the .pdf formatting (especially the title page, font, font-size) for those of us who don't have a strong grasp of latex. 

```
format: 
    pdf:
      shift-heading-level-by: 2
      mainfont: Times New Roman
      sansfont: Times New Roman
```
