### DISCUSSION TITLE
Quarto book - Thesis title page: text doesn't appear in the center

### DISCUSSION THREAD

**Discussion by barizona** [quarto-dev/quarto-cli#1993] [Q&A] [answered]
Hi, I am writing my thesis using Quarto, project type: book, format: pdf. I would like to create a first page includes more info, therefore I've included this section to the YAML:
header-includes:
  - \usepackage{microtype}
  - \pretolerance=10000
  - \usepackage{colortbl}
  - \usepackage{titling}
  - \predate{\begin{center}
    \textit{egyetemi adjunktus}
    \newline
    \newline
    \newline
    \newline
    \newline
    \newline
    \newline
    \newline    
    Name of the University
    \newline
    Name of the University 2
    \newline
    Name of the University 3
    \newline
    Name of the University 4
    \newline
    \newline
    \newline
    \includegraphics[width=4cm,height=4cm]{figs/University_logo.png}\LARGE\\}
  - \postdate{\end{center}}
  - \pagenumbering{gobble}

The "Name of the University" parts aligned to the center but they do not appear in the vertical center of the page. I've tried including
 - \usepackage[a4paper, total={6in, 8in}, margin=0.5in]{geometry} 
but it doesn't solve the problem. 
Do you have an idea how to solve this issue?
Thanks!
Eszter

**Comment by jjallaire** [comment]
I don't have enough LaTeX chops to say -- perhaps someone else here does?

**Reply by barizona** [reply]
Ok, I copy the content of my whole _quarto.yaml:
```
project:
  type: book

book:
  title: "Title"
  author: "My name"
  date: 2022-08-30
  date-format: "YYYY"

  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd

bibliography: references.bib
lang: hu

format:

  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    papersize: A4
    pandoc_args: --listings
    classoption: notitlepage
    keep-tex: true
    toc: true
    toc-depth: 2
    number-sections: false
    colorlinks: true
    mainfont: Calluna
    sansfont: Calluna
    urlcolor: DodgerBlue4
    fig-pos: "h"

editor: visual

header-includes:
  - \usepackage{microtype}
  - \pretolerance=10000
  - \usepackage{colortbl}
  - \usepackage{titling}
  - \predate{\begin{center}
    \textit{post doc}
    \newline
    \newline
    \newline
    \newline
    \newline
    \newline
    \newline
    \newline    
    Name of the University
    \newline
    Name of the University 2
    \newline
    Name of the University 3
    \newline
    Name of the University 4
    \newline
    \newline
    \newline
    \includegraphics[width=4cm,height=4cm]{figs/University_logo.png}\LARGE\\}
  - \postdate{\end{center}}
  - \pagenumbering{gobble}
```

**Comment by eeholmes** [comment, marked as answer]
Hi @barizona , All those \newlines are messing up the center environment.  Replace as follows

```
project:
  type: book

book:
  title: "Title"
  author: "My name"
  date: 2022-08-30
  date-format: "YYYY"

  chapters:
    - index.qmd

bibliography: references.bib
lang: hu

format:

  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    papersize: A4
    pandoc_args: --listings
    classoption: notitlepage
    keep-tex: true
    toc: true
    toc-depth: 2
    number-sections: false
    colorlinks: true
    urlcolor: DodgerBlue4
    fig-pos: "h"

editor: visual

header-includes:
  - \usepackage{microtype}
  - \pretolerance=10000
  - \usepackage{colortbl}
  - \usepackage{titling}
  - \predate{\begin{center}
    \textit{post doc}
    
    \vspace{0.025\textheight}
    
    Name of the University
    
    Name of the University 2

    Name of the University 3

    Name of the University 4

    \vspace{0.025\textheight}

    \includegraphics[width=4cm,height=4cm]{figs/University_logo.png}\LARGE\\}
  - \postdate{\end{center}}
  - \pagenumbering{gobble}
```
