### DISCUSSION TITLE
Is there any way to specify a latex template-partial file using a variable?

### DISCUSSION THREAD

**Discussion by eeholmes** [quarto-dev/quarto-cli#2006] [Q&A] [answered]
I am including a subfile within a latex template partial. I would like to choose the subfile based on a variable in the qmd document YAML. Like so:

Pertinent part of the qmd YAML where I have added the variable `tpg-theme`.
```
format: 
  pdf: 
    tpg-theme: abc
    template-partial: ["before-body.tex"]
```

Then in the latex template partial `before-body.tex`, I would have
```
$_$tpg-theme$.tex()$
```

This unfortunately does not work. Does anyone know of a way to dynamically (using a variable in the doc YAML) specify the subfile that is included in a template partial?

BTW here is what does work:
```
format: 
  pdf: 
    template-partial: 
        - "before-body.tex"
        - "_abc.tex"
```

Then in `before-body.tex`, I would have
```
$_abc.tex()$
```
Why don't I just do this? Because I can't change `before-body.tex`. It is set by my extension code.

Any solution that achieve this effect would work. I am not wedded to `$_$tpg-theme$.tex()$`. Other solutions I have thought of

* Being able to specify a subdirectory  `$tpg-theme$` where a file called `_includedfile.tex` is found.  Then `before-body.tex` would be something like
```
partial.searchpath = $tpg-theme$
$ _includefile.tex()$
```
* A lua filter that copies `$tpg-theme$.tex` to `_includedfile.tex`.  Then `before-body.tex` would be 
```
$ _includefile.tex()$
```
I have no idea how to do that though.
