### DISCUSSION TITLE
rendering files of subprojects in respective environment

### DISCUSSION THREAD

**Discussion by wiesehahn** [quarto-dev/quarto-cli#2041] [Q&A]
I have a reseach project consisting of several subproject. They are (semi)-independent RStudio-projects. 
Now I want to create a combinded documentation where files from subprojects are rendered based on their respective environment, but where the rendered output is saved on the research project level. 
Is this possible and if yes how can I do this?

The structure should be similar to this:
```
├── docs
│   ├── chapterA.html
│   └── chapterB.html
│ 
├── quarto_project
│   ├── .quarto
│   └──_quarto.yml
│ 
├── Project_A
│   ├── renv.lock
│   ├── ProjectA.Rproj
│   └── chapterA.qmd
│ 
├── Project_B
│   ├── renv.lock
│   ├── ProjectB.Rproj
│   └── chapterB.qmd
│ 
└── .gitignore
```

I tried with a `_quarto.yml` like this:
```
project:
  type: book
  output-dir: ../docs
  execute:
  freeze: auto 

book:
  title: "title"
  author: "author"
  chapters:
    - ../Project_A/chapterA.qmd
    - ../Project_B/chapterB.qmd
```
but the chapters are not rendered.

**Comment by jjallaire** [comment]
The chapters need to be beneath the quarto project file.

You can definitely do as you outline and freeze is definitely the way to do it.

In this configuration if you execute `quarto render` in a sub-project it will only build the files for that project. One hitch might be that RStudio doesn't recognize the parent project when you open RStudio in the sub-project (I haven't tried this)

**Reply by wiesehahn** [reply]
So my folder structure would not be possible?

I changed to something like this and yes, it is working. 

```
├── .quarto
├── _quarto.yml
│ 
├── docs
│   ├── chapterA.html
│   └── chapterB.html
│ 
├── Project_A
│   ├── renv.lock
│   ├── ProjectA.Rproj
│   └── chapterA.qmd
│ 
├── Project_B
│   ├── renv.lock
│   ├── ProjectB.Rproj
│   └── chapterB.qmd
│ 
└── .gitignore

```

Although this is not really what I was hoping for I tried to do this with `_quarto.yml` like:
```
project:
  type: book
  output-dir: docs
  execute:
    echo: false
  freeze: true 

book:
  title: "quarto_book"
  author: "author"
  chapters:
    - index.qmd
    - part: 
      chapters: 
        - Project_A/chapterA.qmd
        - Project_B/chapterB.qmd
 ```


And rendering files in subprojects creates output in docs. 

But what I still dont get is that code is still rendered although I inserted `echo: false` in the yml-file. 
Do I have to repeat that in each qmd-file in subprojects?

**Reply by jjallaire** [reply]
The format options don't go in the `project` key (they go at the root). For example:

```yaml
project:
  type: book
  output-dir: docs

book:
  title: "quarto_book"
  author: "author"
  chapters:
    - index.qmd
    - part: 
      chapters: 
        - Project_A/chapterA.qmd
        - Project_B/chapterB.qmd

execute:
  echo: false
  freeze: true 

```
