### DISCUSSION TITLE
R  in frontmatter with custom listing template

### DISCUSSION THREAD

**Discussion by nurfatimaj** [quarto-dev/quarto-cli#2202] [Q&A] [answered]
Hi!

I would like to create a listing item where some elements of the frontmatter depend on the output of R command like in the example below

```yaml
---
title: "title"
authors: 
  - name: "`r rmarkdown::yaml_front_matter(list.files(params[['project-path']], 'index.Rmd', full.names = TRUE))$author`"

params:
    project-path: '~/project/'
---
```

That is, I have a separate `project` folder, where I have all my work and output relevant to that project. I would like quarto to access this information when rendering the website, to minimize duplication. The idea is to access this way abstract and all relevant pdf outputs without having to copy paste them manually. 

I tried the above example and it works well when I am rendering that particular page. 
![image](https://user-images.githubusercontent.com/24235395/187322382-7d7af71f-5ea9-49fd-a29f-f5c8edeceea6.png)

But on the listing page, I get this

![image](https://user-images.githubusercontent.com/24235395/187322467-edebb473-4e4b-4cca-b021-f3e21f468143.png)

I am not sure, if there is a deeper issue why listings can't handle R code or is it an issue with my listing template. If latter, could you please let me know, how can I enable evaluation of R code in frontmatter yaml. Here is the portion of my template that prints the authors:

```ejs
<div class="quarto-title-authors">
    <ul class="listing-author">
        <% for (const athr of item.authors) {%>
            <% if (athr.url) { %>
                <li><a href="<%- athr.url %>"><%- athr.name %></a></li>
            <% } else { %>
                <li><%- athr.name %></li>
            <% } %>
        <% } %>
    </ul>
</div>
```

Thank you!

**Comment by mcanouil** [comment]
To use R code in YAML, you have to use `!expr` prefix (see <https://quarto.org/docs/computations/r.html#chunk-options>).

But the issue might also be related to <https://github.com/quarto-dev/quarto-cli/issues/1505>.

**Reply by nurfatimaj** [reply]
So, I noticed that about chunk options, but it doesn't seem to work for frontmatter yaml. Unless I am implementing it in a wrong way.

```yaml
title: "!expr rmarkdown::yaml_front_matter(list.files(params[['project-path']], 'index.Rmd', full.names = TRUE))$title"
params:
  project-path: '~/project/'
```
produces this
![image](https://user-images.githubusercontent.com/24235395/187337380-7a83bf12-17c4-45b7-9a4e-fdafc5d5c4ac.png)
both on the page of the given quarto document and on the listing page. 

I've also seen this discussion https://github.com/quarto-dev/quarto-cli/discussions/606, but was wondering if there are any new developments that allow me to do what I want.
