### DISCUSSION TITLE
in quarto book, why is META-DESCRIPTION posted on top of every page?

### DISCUSSION THREAD

**Discussion by produnis** [quarto-dev/quarto-cli#2282] [Q&A] [answered]
Hi there, 
I am creating a book, and I added a "description" in the _quarto.yaml file.
Now, the HTML file contains a META Descritpion entry, but, additionally, the text of that description is posted on top of every page of the book.

My question is:  why is that, and is there a way to turn it off?

**Comment by dragonstyle** [comment]
Try indenting the description under the book (if it is a book description you are providing). When you provide a description at the root level, it is merged with every individual page, so each page acts as if it has that description metadata.

**Reply by produnis** [reply]
No matter where I place a description, wether in quarto.yml or on a Single Page:

The description is in a meta field (which is as expected) but aditionally the description text is printed on top of the Page (which is NOT as expected).

**Reply by dragonstyle** [reply]
Could you share an example of the `_quarto.yml` file that is causing this? I tested it under the `book` key and wasn't able to reproduce the issue:

```
book:
  description: |
    This is a sample description
```

**Reply by produnis** [reply]
This is my complete yml

```
project:
  type: book

book:
  title: "Statistik mit R und RStudio"
  subtitle: "Ein Nachschlagewerk für Gesundheitsberufe"
  author: "Jörg große Schlarmann"
  date: "01 09 2022"
  date-format: "iso"
  language: de
  author-meta: "Jörg große Schlarmann"
  description: |
    Dieses Buch widmet sich an Studierende und Beschäftigte im Gesundheitswesen
    und soll als Nachschlagewerk für statistische Fragestellungen bezüglich der freien Software R dienen.
#  downloads: pdf
  favicon: favicon.ico

  sidebar:
    tools:
      - icon: file-earmark-pdf
        href: rbuch.pdf
      - icon: journal-richtext
        href: rbuch.epub
    collapse-level: 4

  chapters:
    - index.qmd
    - einleitung.qmd

    - part: "R und RStudio"
      chapters:
        - installation.qmd
        - r-und-rstudio.qmd

    - part: grundelgende-r-befehle.qmd
      chapters:
        - rechnen-mit-r.qmd
        - variablen.qmd
        - wertesequenzen.qmd
        - datentypen.qmd
        - datenklassen.qmd
        - fehlende-daten.qmd
        - umgang-mit-datensaetzen.qmd
        - daten-laden-speichern.qmd
        - arbeitsverzeichnis.qmd
        - daten-importieren.qmd
        - daten-exportieren.qmd
        - zusatzpakete.qmd
        - ausgabe-in-datei.qmd
        - verteilungsfunktionen.qmd
        - eigene-funktionen.qmd

    - part: markdown.qmd
      chapters:
        - Rmarkdown.qmd
        - quarto.qmd


    - part: "Tidyverse"
      chapters:
        - tidyverse.qmd
        - tidy-dataimport.qmd
        - tidy-datentidy.qmd
        - tidy-datenumgang.qmd
        - tidy-ergebnissekommunizieren.qmd

    - part: "Hilfsmittel"
      chapters:
        - weitere-hilfsmittel.qmd

    - part: statistik-mit-R.qmd
      chapters:
        - deskriptive-statistik.qmd
        - schliessende-statistik.qmd
        - diagramme-plotten.qmd
        - ggplot.qmd

    - part: "Was willst du machen?"
      chapters:
        - will-daten-manipulieren.qmd
        - will-diagramme-plotten.qmd
        - will-pakete-verwalten.qmd
        - will-Rmarkdown.qmd
        - will-referenztabellen.qmd
        - will-covid19.qmd


 # appendices:
    - credits.qmd

  page-footer:
    left: "Jörg große Schlarmann (2022): Statistik mit R und RStudio - Ein Nachschlagewerk für Gesundheitsberufe"
    right:
      - icon: github
        href: https://github.com/produnis
      - icon: linkedin
        href: https://www.linkedin.com/in/j%C3%B6rg-gro%C3%9Fe-schlarmann-32b3331b7/
      - icon: file-earmark-pdf
        href: rbuch.pdf
      - icon: journal-richtext
        href: rbuch.epub
  toc-depth: 4
cover-image: images/coverA4.png

site-url: https://www.produnis.de/R

bibliography: book.bib

crossref:
  fig-title: "Abb."
  fig-prefix: "Abbildung"
  tbl-title: "Tab."
  tbl-prefix: "Tabelle"
  eq-title:  "Gleichung"
  eq-prefix:  "Gleichung"
  sec-prefix: "Abschnitt"
  #ch-prefix: "Kapitel"

format:
  html:
    theme:
      - spacelab
      - produnis.scss
      - joe.css
    include-in-header: "vgwort.html"
    toc-title: "Auf dieser Seite:"
    toc-depth: 4
    cover-image: images/coverA4.png
    lang: de
  epub:
    epub-cover-image: images/coverA4.png
```
