### DISCUSSION TITLE
Possible to specify in YAML href to target="_blank"?

### DISCUSSION THREAD

**Discussion by jhchou** [quarto-dev/quarto-cli#2283] [Q&A]
Is there a way to specify `target="_blank` in `href`'s in YAML's, for example in `about.qmd` or the `navbar:` in `_quarto.yml`?

As mentioned here, it's possible in Markdown: [Is it possible to make all hrefs open in a new tab?](https://github.com/quarto-dev/quarto-web/discussions/354) as follows:

    [some text](some-url){target="_blank"}

... but I haven't been able to find a way to do so in YAML hrefs.

**Comment by dragonstyle** [comment]
Right now this isn't possible via yaml (and many of those links would evade presence in the suggested LUA filter), but perhaps it would be nice to able to specify something like:

```
about:
  ..
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
      target: _blank
```

You could write a simple js file to walk the links and set their targets in the meantime.

**Reply by mcanouil** [reply]
A Lua filter could also be used to force all external links to open in a new tab.

```lua
function Link (link)
  if link.target:match '^https?%:' then
    link.attributes.target = '_blank'
    return link
  end
end
```

Source: <https://fosstodon.org/@pandoc/109433924551943647>

**Reply by aborruso** [reply]
Hi @mcanouil I have created this file

```
function Link (link)
  if link.target:match '^https?%:' then
    link.attributes.target = '_blank'
    return link
  end
end
``` 

And I have inserted it in my [`_quarto.yml` file](https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/main/_quarto.yml#L85).

In [this page](https://ondata.github.io/italian-public-sector-pnrr-data-guide/rete-pnrr.html) I have some external links (see example below), but I do not have in these blank target.

I have applied general black target [using this](https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/main/_quarto.yml#L81). Currently [it works for all, but not for sidebar](https://github.com/quarto-dev/quarto-cli/discussions/3541#discussion-4618175), and I thought to use your nice idea to fix the problem in the sidebar. But I can't get it to work.

Thank you

![image](https://user-images.githubusercontent.com/30607/221123652-23137201-58bd-45d1-b475-8e3588f7c96a.png)

**Reply by mcanouil** [reply]
The filter is for external links, thus it can't work for internal relatives link.
You have to tweak the filter if you want it to be for any kind of links, _i.e._, the following should work:

```lua
function Link (link)
  link.attributes.target = '_blank'
  return link
end
```

**Reply by dragonstyle** [reply]
The sidebar (and navbar / footer) is a part of the 'envelope' for the document, which means that it isn't sent through pandoc. To support targets for the sidebar, we'll need to add support for that specifically as we did in the other PR (via the EJS templates that emit that 'envelope'). So sadly, a LUA filter won't be able to modify those...

**Reply by mcanouil** [reply]
Would a post-render script work? It would require to parse all HTML documents, but I believe it would work as a workaround right now.

On a side note, maybe it would be great to be able to pass href attributes directly from the yaml, do you @dragonstyle think it could be done (and a good idea)? 🤔

**Reply by dragonstyle** [reply]
I just added this to the 1.3 pre-release. You can now specify target in the sidebar definition, like:

```
website:
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        target: _blank
```

**Comment by cararthompson** [comment]
Thanks for this addition. I've just added it to my website navbar (header) and footer. It works in the nav bar, but `target: _blank` seems to be ignored for the footer icons when using the same approach. Is this deliberate? 

```
page-footer: 
    right: Some text
    left: Some more text
    center:
      - icon: github
        href: https://github.com/cararthompson
        target: _blank
```
Have I missed something obvious?
