### DISCUSSION TITLE
crossref label language > sec-prefix seems to be ignored

### DISCUSSION THREAD

**Discussion by produnis** [quarto-dev/quarto-cli#2287] [Q&A] [answered]
Hi there, I am creating a book with quatro and I am wondering how to change the crossref labels.
in my `_quarto.yml` I specified as follows:

```
crossref:
  fig-title: "Abb."
  fig-prefix: "Abbildung"
  tbl-title: "Tab."
  tbl-prefix: "Tabelle"
  eq-title:  "Gleichung"
  eq-prefix:  "Gleichung"
  sec-prefix: "Abschnitt"
  #ch-prefix: "Kapitel"
```
This works fine with figures and tables and equations, but it does not work with chapters and sections.

The `sec-prefix`-Parameter seems to be ignored, as `@sec-anywhere` still generates "Section xy" instead of "Abschnitt xy".
The `ch-prefix`-Parameter is not supported, so I have no clue how to change "Chapter" into "Kapitel".

Is there a doc listing all crossfre -titles and -prefixes?

**Comment by mcanouil** [comment, marked as answer]
I think there is an issue with the crossref schemes.

Meanwhile, the following will work:

```yaml
language:
  crossref-ch-prefix: "Kapitel"
```

See <https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language-de.yml> for all entries.

**Reply by produnis** [reply]
thanks !
This works:

```
crossref:
  fig-title: "Abb."
  fig-prefix: "Abbildung"
  tbl-title: "Tab."
  tbl-prefix: "Tabelle"
  eq-title:  "Gleichung"
  eq-prefix:  "Gleichung"
  #sec-prefix: "Abschnitt"
  #ch-prefix: "Kapitel"
language:
  crossref-ch-prefix: "Kapitel"
  crossref-sec-prefix: "Abschnitt"
```
