### DISCUSSION TITLE
Pause within slides in revealjs

### DISCUSSION THREAD

**Discussion by mlarocca-git** [quarto-dev/quarto-cli#2300] [Q&A]
I have been a Rmarkdown user for a long time. Recently I switched all Rmarkdown projects to Quarto. 

I have a minor problem and haven't found any solution in previous discussions.

In my reavealjs slides, I use a lot the pause within slides by inserting three dots separated by spaces.

There is no problem when I render a qmd file to HTML format. The "pause operator" does not appear in the final HTML. However, when I render a qmd file to a pdf via latex, the pause operator (the three dots) appears everywhere in the final pdf.

Is there any way to instruct Pandoc to ignore the string ". . ." when producing the final pdf?

Thank you so much for your help.

**Comment by mcanouil** [comment]
Could you provide a small reproducible example?
From what you are saying, I believe this to be a bug, because it is definitely supposed to work (_i.e._, <https://quarto.org/docs/presentations/beamer.html#incremental-lists>).

**Reply by ghost** [reply]
Thanks for posting, let's move the discussion here.

https://github.com/quarto-dev/quarto-cli/issues/2302

**Reply by cderv** [reply]
I don't think this is an issue so I am posting answer here: 

Pause is a slide show feature only : https://pandoc.org/MANUAL.html#inserting-pauses

@mlarocca-git We don't have much details as mentioned above so HTML and PDF are not clear. 

If by HTML you mean `format: revealjs`, then yes the pause in markdown will be converted to correct HTML. If you try `format: html`, you'll see the `. . .` in the document. 

If by PDF, you mean `format: pdf` then yes it will be like HTML and you'll see markdown as text because it means only pause in slide context. That is why if you mean instead `format: beamer` then it should work too. 

> Is there any way to instruct Pandoc to ignore the string ". . ." when producing the final pdf?

So what type of PDF you are trying to produce.  If you want a PDF version of revealjs slide, I would suggest to print to PDF (https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf) 

Hope it helps

**Comment by mlarocca-git** [comment]
Thank you for your reply. 

I post here the same reproducible example I have posted as an issue.

For my teaching, I write my slides with pauses within slides and render them using output "format: revealjs". It produces an HTML  file with my slides.

Then, I need to deliver the same material to the students in a different format, easier to read and print as compared to the slides.

If I use as output "format: HTML", to deliver the material as lecture notes, I see no problem. It is a regular HTML file with the format I have defined via CSS,  and the pause operator does not appear.
Of course, I could get a pdf from the HTML file to get a printable version. 

When I use as output "format: pdf", to deliver the lecture notes, I render the file via xelatex and Pandoc the "three dots" appear in the final pdf file. I am aware that the  "three dots" operator is just for slides. I am just wondering why it appears when I render the file in pdf and not when I render it to HTML (a general HTML, not the HTML file containing the slides). I guess in both cases there is an intermediate md file, and the translation is made via Pandoc.

In Rmarkdown, I was forced to have two slightly different source files: one for the slides (with slide-specific commands), and the other one for the lecture notes (without slide-specific commands). With Quarto, the whole process is much more convenient. I can have the very same source file that I can render as slides, as lecture notes in HTML format, as lecture notes in pdf printable format (produced via xelatex).

Here is a reproducible example.

```
author: "Author"
date: "`r Sys.Date()`"
format:
  revealjs: 
    navigation-mode: vertical
    controls-layout: bottom-right
    menu: true
    code-fold: true
    html-math-method: katex
    width: 1920
    height: 1080
    incremental: true
  html: 
    code-fold: true
    html-math-method: katex
    self-contained: true
  pdf:
    toc: true
    number-sections: true
    geometry: 
      - top=30mm
      - left=30mm
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. 

. . .

You can embed code like this:

```{r}
x <- rnorm(1000)
plot(x)
```

. . .

You can add options to executable code like this

```{r}
#| echo: false
hist(x)
```

. . .


Compute the mean as

$$
\bar x =\frac{1}{n}\sum{i=1}^n x_i
$$

. . .

The `echo: false` option disables the printing of code (only output is displayed).
```
