### DISCUSSION TITLE
Category listing on blog home page not linking to all posts in a category

### DISCUSSION THREAD

**Discussion by harrelfe** [quarto-dev/quarto-cli#2352] [Q&A] [answered]
I am converting my blog fharrell.com to Quarto.  The new test site is https://hbiostat.org/blog .  My problem is that on the home page, even though I see correct category counts, linking to one of the categories does not pop up the entire set of posts that have that category; only a subset of articles is shown.

Here's `index.qmd`:

````
---
title: "Statistical Thinking"
listing:
  - id: post
    contents: post/**/*.qmd
    sort: "date desc"
    type: default
    fields: [date, title, description, categories, author, reading-time]
    categories: true
    sort-ui: false
    filter-ui: false
    page-size: 3
  - id: talk
    contents: talk/**/*.qmd
    sort: "date desc"
    type: default
    fields: [date, title, description, categories, author]
    categories: true
    sort-ui: false
    filter-ui: false
    page-size: 3
page-layout: full
title-block-banner: false
include-in-header: meta.html
toc: true
---

## Posts

::: {#post}
:::

## Talks

::: {#talk}
:::

````

And here is `post/index.qmd`:

````
---
title: "Statistical Thinking"
listing:
  - id: post
    contents: post/**/*.qmd
    sort: "date desc"
    type: default
    fields: [date, title, description, categories, author, reading-time]
    categories: true
    sort-ui: false
    filter-ui: false
    page-size: 3
  - id: talk
    contents: talk/**/*.qmd
    sort: "date desc"
    type: default
    fields: [date, title, description, categories, author]
    categories: true
    sort-ui: false
    filter-ui: false
    page-size: 3
page-layout: full
title-block-banner: false
include-in-header: meta.html
toc: true
---

## Posts

::: {#post}
:::

## Talks

::: {#talk}
:::

````

Most of my articles have headers like this one:

````
---
title: Road Map for Choosing Between Statistical Modeling and Machine Learning
author:
  - name: Frank Harrell<br><small>`@f2harrell`</small>
    url: https://hbiostat.org
    affiliation: Vanderbilt University<br>School of Medicine<br>Department of Biostatistics
date: 2018-04-30
modified: 2021-06-04
categories: [data-science, machine-learning, prediction, 2018]
description: "This article provides general guidance to help researchers choose between machine learning and statistical modeling for a prediction project."
---

````

I created one post that uses the "one line per category" form for categories and it did not result in that post being linked from the home categories page either.

Any help appreciated.
Frank
