### DISCUSSION TITLE
Citation Metadata generation for book project

### DISCUSSION THREAD

**Discussion by jpmorr** [quarto-dev/quarto-cli#2379] [Q&A]
I'm trying to include a citation for a book document, in a similar manner as to what is described in the documentation: https://quarto.org/docs/authoring/create-citeable-articles.html#other-types-of-documents . However, I don't see the citation index created anywhere in the HTML or PDF output.

In my `_quarto.yml` I've added a citation section (right at the end):
```
project:
  type: book
  output-dir: public

book:
  title: "My Book"
  subtitle: "For when you mare bored" 
  edition: "Third"
  doi: "10.xxxxx/xxxxxxxx.00000"
  cover-image: "images/Cover.png"
  abstract: "User reference documentation for blah blah blah....."
  author:
   - name: "**Bob Smith**"
  date: "8/8/2022"
  chapters:
    - index.qmd
    - part: "Details"
      chapters:
      - 01_Intro.qmd
    - part: "Examples"
      chapters:
        - 20_Example_problem.qmd
    - References.qmd
  appendices:
    - A1.qmd
  downloads: [pdf]
  sharing: [twitter, facebook, linkedin]
  page-navigation: true
bibliography: references.bib
csl: elsevier-with-titles-alphabetical.csl

format:
  html:
    theme: cosmo
    code-line-numbers: true
  pdf: 
    code-line-numbers: true
    documentclass: scrbook
    number-sections: true
    lof: true
    lot: true
    toc: true    
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    hyperrefoptions:
      - linktoc=all
    colorlinks: true
    linkcolor: "blue"
    biblio-style: apalike
    keep-tex: true
    titlepage-geometry: 
      - top=3in
      - bottom=1in
      - right=1in
      - left=1in
    title-bg-image: "images/Cover.png"
    title-bg-location: "UL"
    title-bg-size: 0.5
    title-page-color: "041e42"
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex" 
      - "_coverpage.tex" 
    include-in-header: 
      - "in-header.tex"
            
latex-auto-install: true

citation:
  type: book
  url: https://jpmorr.gitlab.io/documentation

```

Is this the correct way of doing it for a book? Should `citation` be indented under book? Or are citations only available for articles and simple pages? 

I need to create a simple section in the preface with instructions on how to cite the document, but it would be better if it's automatic and picks up any changes I make in the `yml` rather than it being something manual.
