### DISCUSSION TITLE
Proper sansfontoptions syntax

### DISCUSSION THREAD

**Discussion by liamhaller** [quarto-dev/quarto-cli#2382] [Q&A]
In my YAML header I would like to specify a hex color for the sansfont in my document however based on the Quarto documentation it's not readily clear how to incorporate the \fontspec options.

In the code below, I would like to set the sansfont to #ff7832, but I get the error

"sansfontoptions has value text: | \fontspec[Color="#ff7832"], which must be a string"

I have tried both with and without quotation marks. Is there a different way I should be formatting this?

```
 format: 
  pdf: 
    mainfont: Calibri
    sansfont: Overpass-ExtraBold
    sansfontoptions: 
      text: | 
        \fontspec[Color="#ff7832"]{Overpass-ExtraBold}
```

I also tried to define a custom color, but did not have any success

```
 \definecolor{Foo}{rgb}{0.3,0.4,0.5}
 \fontspec[Color= Foo]{Overpass-ExtraBold}
```
