### DISCUSSION TITLE
More useful scss variables

### DISCUSSION THREAD

**Discussion by dmi3kno** [quarto-dev/quarto-cli#2391] [Q&A] [answered]
I am enjoying the easy ability to customize Quarto Reveal slides through SCSS variables, bypassing the tedious CSS work. I tend to come back and modify the same CSS properties over and over again, so I would love to see SCSS variables for them:

- Smaller text size for numbered and unnumbered lists. Proposed default `$presentation-ul-font-size: 1em` and  `$presentation-ol-font-size: 1em`. Today I do
```css
.reveal section ul {
    font-size: 0.9em;
}
```
- Smaller text size for tables. Proposed default `$presentation-table-font-size: 1em`. Today I do
```css
.reveal section table {
    font-size: 0.6em;
}
```
These are not exclusive to Reveal format and might be useful for HTML as well, hence variables might need to be repeated without the `presentation-` prefix.

**Comment by mcanouil** [comment, marked as answer]
Why don't you define those in a file you could use for all your documents, or even write a [format template extension](https://quarto.org/docs/extensions/formats.html) with that.
This way you get access to those without having to write them every time.

Edit: in your case the scss file would be something like the following.

```scss
$presentation-ul-font-size: 1em !default;
$presentation-table-font-size: 1em !default;

.reveal section ul {
    font-size: $presentation-ul-font-size;
}
.reveal section table {
    font-size: $presentation-table-font-size;
}
```
