### DISCUSSION TITLE
Modifying the MathJax size

### DISCUSSION THREAD

**Discussion by dmi3kno** [quarto-dev/quarto-cli#2392] [Q&A] [answered]
I was not able to modify the size of the inline math. For centered $$y=ax+b$$

math I use
```css
.MathJax, .MathJax_Display  {
    font-size: 80%  !important;
}
```

But this does not work for inline expressions. What is the proper way to scale the inline expressions i.e. $x$?

**Comment by mcanouil** [comment, marked as answer]
_Could you change the category to "Q&A" (via GitHub desktop/website version)?  
This way you can select an answer (if there is one) to show others there is an answer._

---

Inline math are delimited by `$`, display math are delimited by `$$`.
A display math is centered, while inline math are in line, thus following paragraph rule in which they are.

If you want to decrease the size for all math:
```css
.MathJax {
    font-size: 80% !important;
}
```

If you want more fine grained control:
```css
.math.inline .MathJax  {
  font-size: 400% !important;
}

.math.display .MathJax  {
  font-size: 50% !important;
  color: #b22222;
}
```

<img width="1624" alt="screenshot of VSCode showing how the above CSS is rendered in HTML" src="https://user-images.githubusercontent.com/8896044/189480552-6cfc07ce-f021-437f-ae18-ec0f1b6c6763.png">

**Reply by dmi3kno** [reply]
Here's my reprex. Document
```rmd
---
title: "TestDoc"
format:
  revealjs: 
    theme: [simple, test-format.scss]
    slide-number: true
---

## Math

Gathered display math

$$
\begin{gathered}
Q(u)=\mu+s\ln\left(\frac{u}{1-u}\right)\\
q(u)=\frac{s}{(1-u)u}
\end{gathered}
$$

Display math

$$
F(x)=\frac{1}{1+e^{-(x-\mu)/s}}
$$

where $F(x)$ is the CDF of logistic distribution.
```
The content of `test-format.scss`
```scss
/*-- scss:defaults --*/

// fonts
$presentation-font-size-root: 30px !default;
// colors

// headings

/*-- scss:rules --*/

.math.inline {
  font-size: 20%  !important;
}

.math.display .MathJax {
  font-size: 20%  !important;
}

```
Result

![image](https://user-images.githubusercontent.com/13419011/189503239-30715cd6-29a3-438f-a079-087896a9c051.png)

Inline works, the display doesn't

Content of `test-format.scss`

```scss
/*-- scss:defaults --*/

// fonts
$presentation-font-size-root: 30px !default;
// colors

// headings

/*-- scss:rules --*/

.math.inline {
  font-size: 20%  !important;
}

.MathJax, .MathJax_Display  {
    font-size: 20%  !important;
}
```
Result: both inline and display math work

![image](https://user-images.githubusercontent.com/13419011/189503321-808bf5e5-43c0-48b4-bf84-8c3d50298869.png)

**Reply by mcanouil** [reply]
For `revealjs`, you can simply use the top level span CSS class, _i.e._, use your browser developper mode to understand what CSS is needed and how it should be nested.
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/8896044/189519778-f7db04db-7c70-4548-a198-86071b8db38c.png">

```css
.math.inline {
  font-size: 150%;
  color: #22b222;
}
.math.display {
  font-size: 50%;
  color: #b22222;
}
```

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8896044/189519747-f2951e28-1018-4bfb-a05a-b828e7268e1d.png">

PS: you should probably read some documentation about CSS to understand the use of `,`, `>`, _etc._ in CSS definitions.

**Reply by dmi3kno** [reply]
I see. `.math.display` not `.math.display .MathJax`
I was just following your earlier example. Thanks for your help!

**Reply by mcanouil** [reply]
My earlier example was not using `revealjs` format which is slightly different from `html`.

Please mark my reply as the answer if appropriate (i.e., it does answer the questions) to let others know the question has a good answer 😉

**Comment by ChoCho66** [comment]
I would like to ask an additional question. 
I want to modify the margins of the equation for `revealjs`.
I guess it should be modified this
```
.MathJax_Display {
   margin-top: 1em 0em;
}
```

But it cannot be modified directly with scss if it has a preset value. As shown in the picture.
<img width="1269" alt="截圖 2023-07-09 18 17 16" src="https://github.com/quarto-dev/quarto-cli/assets/72805700/949bd106-c61f-4d6c-9f16-7621ba9af65c">
 
What method should be used to modify it?

Below is a small sample of mine.

- qmd
  ```
  ---
  format:
    revealjs:
      theme: style.scss
  ---
  
  Test
  $$
  \begin{aligned}
    f(x) = y.
  \end{aligned}
  $$
  ```

- sass
  ```
  /*-- scss:defaults --*/
  .MathJax_Display {
    margin: 5em 0em;
  }
  ```

**Reply by mcanouil** [reply]
Use `!important` in this particular case:

```css
.MathJax_Display {
  margin: 5em 0em !important;
}
```
