### DISCUSSION TITLE
Sections within the same chapter in separate files

### DISCUSSION THREAD

**Discussion by stephenleo** [quarto-dev/quarto-cli#2400] [Q&A] [answered]
Is there a way to have sections within the same chapter from different files? Something like this

```
chapters:
  - index.qmd
  - preface.qmd
  - part: part_1.qmd
    chapters: 
      - chapter_1.qmd
        sections:
          - section_1_1.qmd
          - section_1_2.qmd
      - chapter_2.qmd
        sections:
           - section_2_1.qmd
           - section_2_2.qmd
  - part: part_2.qmd
    chapters:
      - chapter_3.qmd
        sections:
           - section_3_1.qmd
           - section_3_2.qmd
```

**Comment by mcanouil** [comment, marked as answer]
In your chapter Quarto document use the shortcode to include the files: `{{< include section.qmd >}}`.

**Reply by stephenleo** [reply]
Thanks for the answer! It works perfectly

**Comment by birnstiel** [comment]
Sorry for bringing this up again, but I didn't manage to adapt this to my needs. Is there a way to get the same but without the *parts*? something like this:
```
chapters:
  - index.qmd
  - preface.qmd
  - chapter_1.qmd
    sections:
    - section_1_1.qmd
    - section_1_2.qmd
  - chapter_2.qmd
    sections:
    - section_2_1.qmd
    - section_2_2.qmd
```

Even better would be where something like `chapter_2.qmd` wouldn't be needed, but the title could be given in the `_quarto.yml` such that the outline becomes:

1. Chapter 1
1.1 Section 1.1
1.2. Section 1.2
2. Chapter 2
2.1 Section 2.1

while each subsection appears on one html page? Thanks for the help!
