### DISCUSSION TITLE
Icon in navbar next to text

### DISCUSSION THREAD

**Discussion by clairl** [quarto-dev/quarto-cli#2402] [Q&A] [answered]
Hi, 

Is it possible to include Bootstrap icons next to text in the navbar on a Quarto website? I am hoping to have a navbar that looks like this with icons next to the tab text:

<img width="223" alt="Screen Shot 2022-09-11 at 3 58 28 PM" src="https://user-images.githubusercontent.com/11091515/189548628-eee4d1f3-6a01-4e12-86e3-92e8922db810.png">

The directions suggested [here](https://quarto.org/docs/reference/projects/websites.html#navbar) work when `text` is not specified. E.g.,

```
navbar:
  left:
    -  href: github.com
       icon: github
```
<img width="1428" alt="Screen Shot 2022-09-11 at 3 48 39 PM" src="https://user-images.githubusercontent.com/11091515/189548459-7e575833-d604-4e7d-bb86-f6b82747e4b0.png">

However, I am unable to include icons next to text in the navbar. I tried this in the _quarto.yml file but only the text appeared:

```
navbar:
  left:
    - href: github.com
      text: Github
      icon: github
    - about.qmd
```
<img width="1425" alt="Screen Shot 2022-09-11 at 3 49 43 PM" src="https://user-images.githubusercontent.com/11091515/189548496-0dd48c14-4e54-4cb1-a3fb-e27fd75dbd8d.png">

Also, the `icon` option does not appear to work for .qmd files.

<img width="1433" alt="Screen Shot 2022-09-11 at 3 50 41 PM" src="https://user-images.githubusercontent.com/11091515/189548522-9a13fc8e-c230-48cf-b94d-3fe3f6e9104c.png">

Just wondering if it is possible to include icons next to text in the navbar and for tabs linked to .qmd files?

Thanks

**Comment by mcanouil** [comment, marked as answer]
You need for example the `fontawesome` Quarto extension, then:

```yaml
  navbar:
    right:
      - text: "{{< fa brands meetup >}} Meetup R Lille"
        href: https://www.meetup.com/R-Lille/

```
