### DISCUSSION TITLE
Chunk level format options?

### DISCUSSION THREAD

**Discussion by shabbychef** [quarto-dev/quarto-cli#2411] [Q&A]
Hi,
I _think_ in quarto I can set default options in the header YAML via something like:
```
format:
  html:
    out-width: "625px"
    out-height: "402px"
    fig-format: png
    fig-width: 10.0
    fig-height: 6.43
  pdf:
    fig-width: 11.5
    fig-height: 6.8
```

Is it possible to override these in a chunk in a way that is by output type? It seems that I can only override these options absolutely, and not conditionally on the output type.

thanks,
