### DISCUSSION TITLE
Possible to make a book from jupyter notebooks?

### DISCUSSION THREAD

**Discussion by bblais** [quarto-dev/quarto-cli#2458] [Q&A] [answered]
Can you have chapters that are .ipynb files and not .qmd files for books?  I tried the mybook tutorial, replacing all of the .qmd files with .ipynb equivalents to test, and changed the _quarto.yml file like below. There were no errors in the render, but the .ipynb files were converted to .py, and none of the content showed on the website preview.  Am I missing something?

thanks!

```yaml
project:
  type: book

book:
  title: "title"
  author: "Jane Doe"
  date: "now"
  chapters:
    - index.ipynb
    - intro.ipynb
    - summary.ipynb
    - references.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

**Comment by dragonstyle** [comment, marked as answer]
Yes that should work without any issue. For example, I just replaced the `intro.qmd` with `intro.ipynb` (with a single markdown cell which contained the contents of the qmd file) in the default book project and rendered no problem:

```
project:
  type: book

book:
  title: "j"
  author: "Jane Doe"
  date: "9/19/2022"
  chapters:
    - index.qmd
    - intro.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

```
