### DISCUSSION TITLE
List of available fonts for `mainfont` HTML option?

### DISCUSSION THREAD

**Discussion by mikemklee** [quarto-dev/quarto-cli#2487] [Q&A] [answered]
I am trying to see if I can set a different font for my Quarto website, using the `mainfont` HTML option as described here:
https://quarto.org/docs/reference/formats/html.html#fonts

The description just says that it sets the `font-family` for the HTML document.
However, I cannot find information on what might be a valid value for the property.

For example, do I need to have the font included in my repository to be able to use it?
or can I just set it to any google font name?

**Comment by mikemklee** [comment, marked as answer]
I was able to use any [google font](https://fonts.google.com/) by doing the following:

```yaml
format:
  html:
    mainfont: "'Source Serif Pro', serif"
```

**Reply by jimjam-slam** [reply]
AFAIK Quarto doesn't embed or import a Google Font if you specify it using the `mainfont` option, so you might want to check that this still works on other devices (eg. your phone) - if you have the font installed locally, you might not notice it not working!

To be safe, I'd probably add the `@import` statement from Google Fonts like:

```yaml
format:
  html:
    mainfont: "'Libre Franklin', sans"
    include-in-header:
      text: |
    <style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;800&display=swap');</style>
```

![image](https://user-images.githubusercontent.com/6520659/190937537-62b72a66-6fe5-4f88-a5c9-15feee84747a.png)
