### DISCUSSION TITLE
Is it possible to manipulate the css of PDF files using wkhtmltopdf?

### DISCUSSION THREAD

**Discussion by a0th** [quarto-dev/quarto-cli#2538] [Q&A]
Im assuming that a HTML file is created first, and that file is then converted to PDF.
Is is possible to manipulate the CSS used to generate the HTML, which would then affect the PDF?

**Comment by cscheid** [comment]
That's not how it works. Pandoc emits LaTeX that's then compiled to PDF with xelatex or a related tool.

**Reply by jimjam-slam** [reply]
The [format options section](https://quarto.org/docs/reference/formats/pdf.html#format-options) of the PDF output reference says:

> Use the specified engine when producing PDF output. If the engine is not in your PATH, the full path of the engine may be specified here. If this option is not specified, Quarto uses the following defaults depending on the output format in use:
> 
> * `latex`: `xelatex` (other options: `pdflatex`, `lualatex`, `tectonic`, `latexmk`)
> * `context`: `context`
> * `html`: `wkhtmltopdf` (other options: `prince`, `weasyprint`; see [print-css.rocks](https://print-css.rocks/) for a good introduction to PDF generation from HTML/CSS.)
> * `ms`: `pdfroff`

This definitely gave me the impression that PDF generation was possible using non-LaTeX "paged CSS" solutions, but I tried giving `html`, `wkhtmltopdf`, `prince` and `weasyprint` as various options for `pdf-engine` and got the same error for all of them:

> pandoc: weasyprint: createProcess: posix_spawnp: illegal operation (Inappropriate ioctl for device)

Have I misunderstood this?

**Reply by jimjam-slam** [reply]
Oh, I think I have - I missed the key phrase "Quarto uses the following defaults _depending on the output format in use_".

Does this mean that we can specify the following to produce a PDF?

```yaml
format:
  html:
    pdf-engine: weasyprint
```

(The above section doesn't appear in the [HTML format options](https://quarto.org/docs/reference/formats/html.html#format-options), but then I'm not sure why it'd be there at all 🤔)

**Reply by jimjam-slam** [reply]
I can see PDF engines [are discussed in the guide](https://quarto.org/docs/output-formats/pdf-engine.html), but that discussion seems to only imply that LaTeX-based engines are available. The above reference for the `pdf-engine` option appears to be verbatim from [Pandoc's documentation for the same option](https://pandoc.org/MANUAL.html#option--pdf-engine). Is it just that those other, non-LaTeX engines aren't supported by Quarto?

**Reply by jimjam-slam** [reply]
Oops! I didn't have the tools installed 😅  Once I installed `weasyprint` (using `brew install weasyprint` on my M1 Mac), both of the following worked great:

```yaml
---
title: "Test PDF report"
author: "James Goldie"
format:
  pdf:
    pdf-engine: weasyprint
---
```

```yaml
---
title: "Test PDF report"
author: "James Goldie"
format: pdf
pdf-engine: weasyprint
---
```

I was also able to add a stylesheet with the `css` option (either in the frontmatter root or under `format: pdf`). It must override some base styles in weasyprint's case, since including only `h2 { color: red }` in my `style.css` changed the layout quite a bit (no stylesheet on left; added stylesheet on right):

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/6520659/192432784-e9f4a857-a485-4b85-812d-3959bcbd8aa0.png">

Looking forward to playing with this and other engines! I also got it working with `pagedjs-cli` once I installed it with `npm install -g pagedjs-cli`. Had a similar problem adding a stylesheet, but perhaps Pandoc's default stylesheet is too opinionated anyway.

**Reply by a0th** [reply]
Thanks for the tip, @jimjam-slam .
I reproduced these with both wkhtmltopdf and weasyprint, and in both cases, adding a .css with a single style breaks the entire default css.

Did you manage to change a portion of the style without breaking the rest?

**Reply by jimjam-slam** [reply]
I think I just swallowed the breakage tbh! Here's the stylesheet I used in a recent project, where we dynamically assembled Quarto book projects: it takes a list of stories as JSON files, converts them to QMDs, throws them in a folder together, then writes a `_quarto.yml` and a `_variables.yml`. (I would link to the whole tool, but I need to be 100% sure I'm not leaking any important internals of our content management system before I do that. But it essentially creates a normal Quarto book project and sets the above format and PDF engine in the `_quarto.yml` instead of the individual document):

```css
/* add adobe fonts web project to use itc frnaklin gothic font */
@import url('https://use.typekit.net/har7kij.css');

html {
  font-family: franklin-gothic-urw, sans-serif;
}

header h1.title {
  font-size: 5em;
}

header .author {
  font-size: 2em;
  font-weight: 900;
  color: black;
  margin-block-end: 0em;
}

header .date {
  font-size: 2em;
  color: #6b767f;
  margin-block-start: 0em;
}

header {
  margin-block-end: 5em;
}

/* table of contents */

#TOC {
  padding: 1em;
  background-color: #2d3494;
  color: white;
  font-size: larger;
}

#toc-title {
  margin-block-start: 0;
}

#TOC ul {
  list-style: none;
  padding-inline-start: 0;
  margin-block-end: 0;
}

#TOC li a {
  color: white;
  font-weight: normal;
}

#TOC li + li {
  margin-block-start: 0.35em;
}

/* individual story bodies are sandwiched with a div.story or div.framing when processing so that we can have our title blocks run across the page while still having a 2 column layout for the story body */
.story, .framing {
  column-count: 2;
}

h1 {
  break-before: always;
  font-weight: 900;
  text-transform: uppercase;
  color: #36a7e9;
  margin-block-end: 0;
}

/* author after story title */

h1 + p {
  text-transform: uppercase;
  color: #6b767f;
  font-size: 1.1rem;
  margin-block-start: 0;
}

h2 {
  font-weight: 900;
  text-transform: uppercase;
}

h3 {
  font-weight: 700;
  text-transform: uppercase;
}

a {
  text-decoration: none;
  font-weight: 700;
  color: #36a7e9;
}

/* for some reason superdesk exports links as <a><u></u></a> */
u {
  text-decoration: none;
}

.title-block {
  background: yellow;
}
```

**Reply by mrworthington** [reply]
New to `weasyprint`. Can I ask how you attach a CSS file in the YAML header if you've set the `pdf-engine` to `weasyprint` like the example you provided earlier:

```r
---
title: "Test PDF report"
author: "James Goldie"
format:
  pdf:
    pdf-engine: weasyprint
---
```

**Reply by a0th** [reply]
The way I  do it by creating a `quarto.css` at the root of my project folder.
Then, I create a `_quarto.yml` right beside the .css that looks like this:
```
css: quarto.css
toc: true
toc-depth: 2
format:
  pdf:
    echo: false
    pdf-engine: pagedjs-cli
  html:
    echo: false
    embed-resources: true
```

I use pagedjs, but the css works the same way for weasyprint. All other parameters are optional, you only need the `css` attribute.
Quarto will look for a _quarto.yml in the folder you run the command `quarto`, and if it does not find it there, it will look recursively in the parent folders.

**Reply by jimjam-slam** [reply]
The `css` option also works under `format.pdf` (alongside `pdf-engine`) in the individual post's frontmatter, which might be useful if you're running off both regular HTML (for a website) and a paged CSS PDF and need different style sheets for both 😊

```yaml
---
title: "Test PDF report"
author: "James Goldie"
format:
  pdf:
    css: my-paged-pdf-styles.css
    pdf-engine: weasyprint
---
```
