### DISCUSSION TITLE
How to correctly activate biblatex/biber

### DISCUSSION THREAD

**Discussion by produnis** [quarto-dev/quarto-cli#2549] [Q&A] [answered]
Hi there, 
I would like to use biblatex and biber for my citations,
my yaml looks like this:

```
---
author: "Joe Slam"
date: 14.09.2022
lang: de
bibliography: Publikationsliste.bib

format:
  pdf:
    cite-method: biblatex
    biblatexoptions: 
      - style=apa
      - backend=biber
      - sortcites=true
      - sorting=ydnt
    keep-tex: true
---
```

My problem is, if I render the document (with xetex), I get error 
`LaTeX Error: File "biblatex.sty" not found.`

I am on Archlinux, and the package `biber` is installed and working in other plain latex projects.

Is there something I am missing to correctly activate biblatex/biber in quarto?
