### DISCUSSION TITLE
How to create a custom title slide for revealjs?

### DISCUSSION THREAD

**Discussion by marcpaterno** [quarto-dev/quarto-cli#2579] [Q&A] [answered]
I am trying to produce a custom title slide to match my institution's PowerPoint format. The title slide has a banner with a logo at the very top, a full-width image right below that, and the printed title, author, meeting name, and date in the space below the image. This text should be left-aligned.

I have been able to place the image on the slide with the following YAML:
```
format:
  revealjs:
    slide-number: true
    footer: "Short title | Marc Paterno"
    css: mfp.css
    title-slide-attributes: 
      data-background-image: "fall.png"
      data-background-position: top
      data-background-size: contain
```

I have not been able to figure out the correct YAML or CSS entries to place the text where I want it. Can anyone tell me how to do this?

I have attached (below) an example of the intended format.

[sample-title.pdf](https://github.com/quarto-dev/quarto-cli/files/9634387/sample-title.pdf)
