### DISCUSSION TITLE
Using YAML anchors and aliases in _quarto.yml

### DISCUSSION THREAD

**Discussion by jkseppan** [quarto-dev/quarto-cli#2586] [Q&A]
The following `_quarto.yml` works:

```yaml
project:
  title: "quarto-test"
  type: book

book:
  chapters:
  - index.md
  - ch1.qmd
  - ch2.qmd
  sidebar:
  - title: sidebar
    contents:
    - index.md
    - ch1.qmd
    - ch2.qmd
```

But the chapters are listed twice, which is not a big problem in this small example, but imagine a book with thirty chapters. The following passes the <http://www.yamllint.com> validator but is not accepted by Quarto:

```yaml
project:
  title: "quarto-test"
  type: book

book:
  chapters: &chapters
  - index.md
  - ch1.qmd
  - ch2.qmd
  sidebar:
  - title: sidebar
    contents: *chapters
 ```

Here are the Quarto error messages:

```
(line 12, columns 5--13) Field "contents" has empty value but it must instead be a string
11:   - title: sidebar
12:     contents: *chapters

In file _quarto.yml
(line 6, columns 3--11) Field "chapters" has empty value but it must instead be an array of values, where each element must be chapter-item
 8:   - ch1.qmd
 9:   - ch2.qmd
```

Is there a way to include the same list in two places but only have one canonical place to edit the list? Even better if there is a way to concatenate lists - this is not a YAML feature but many CI systems implement some way to specify a flattened list.

**Comment by acederberg** [comment]
I am wondering the same thing. I wanted to render ``tex`` and ``pdf`` using the same settings and it is not very dry (don't repeat yourself) to have write it again and again. I wonder what is used to parse the ``yaml``. 

Just in case anybody else runs into broken anchoring in my use case,  I just used ``format-links`` and ``keep-tex``:

```yml
format:
  html:
    toc: false
  pdf:
    toc: false
    documentclass: article
    hyperref:
      - pdfborder={0 0 0}
      - breaklinks=false
      - colorlinks=true
      - urlcolor=blue
    include-before-body:
      # NOTE: It may be possible to style links using another means.
      - text: |
          \newcommand{\hreful}[2]{
              \href{#1}{
                  \textcolor{blue}{\ttfamily\underline{#2}}
              }
          }
    geometry:
      - margin=0.7in
    keep-tex: true
    template-partials:
      - ./title.tex
format-links:
  - text: tex
    href: ./index.tex

```
