### DISCUSSION TITLE
A way for quarto to auto-detect links as in Jupyter?

### DISCUSSION THREAD

**Discussion by castorfou** [quarto-dev/quarto-cli#2609] [Q&A] [answered]
Hello,

I use quarto to blog from notebooks.
Standard behaviour of jupyter notebook is to turn url in markdown cells as html links.

`This is my url: https://github.com/quarto-dev/quarto-cli
`

However this cell will be rendered by quarto as plain text.
Only option I see for the moment would be to enter this

`This is my url: [https://github.com/quarto-dev/quarto-cli](https://github.com/quarto-dev/quarto-cli)
`

but I guess there is a smarted way?

**Comment by rgaiacs** [comment, marked as answer]
@castorfou you can use `<https://github.com/quarto-dev/quarto-cli>`, more details at https://pandoc.org/MANUAL.html#links-1.

**Comment by castorfou** [comment]
Thank you for the link
I think I need to run it with `autolink_bare_uris` extension.

Will run some tests and report it here.

**Reply by cderv** [reply]
@rgaiacs should be the way without the extension. `<link>` is the Markdown syntax to had link with not specific text
https://quarto.org/docs/authoring/markdown-basics.html#links-images

Is that working ? 

However, activating the extension would definitely work I believe.

**Comment by castorfou** [comment]
using pointly bracket works!

would like to test with `autolink_bare_uris` extension
can you guide me about how to use this extension?

my rendering/publishing process is to call `quarto publish gh-pages --no-prompt`
with this _quarto.yml

```
project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
```

**Reply by cderv** [reply]
> would like to test with autolink_bare_uris extension
can you guide me about how to use this extension?

You want to add the extension to the Reader so 
````
format:
  html:
    theme: cosmo
    css: styles.cs
    from: markdown+autolink_bare_uris
````
should be the way to do that.
