### DISCUSSION TITLE
Renaming author, title and table of contents in Quarto book format

### DISCUSSION THREAD

**Discussion by KennethGottfredsen** [quarto-dev/quarto-cli#2634] [Q&A] [answered]
Hi, 

I'm trying to write a book with Quarto. The author, title and table of contents are English by default. The language option doesn't support Danish text. In the past I did use these two commands; title-block-author-single: and title-block-published:, but these options do not solve the problem. Suppose I didn't place the options correctly in the Quarto.yml. 

I guess since im writing a book, the code still has to be written within the Quarto.yml document. The standard book template I use are:

__
project:
  type: book

book:
  title: "Bog"
  author: "Jane Doe"
  date: "27.9.2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: united
  pdf:
    documentclass: scrreprt

editor: visual
__

/ Kenneth

**Comment by mcanouil** [comment, marked as answer]
You could make a PR to support Danish by adding the proper file with the proper translation in <https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language>.

Could you also format properly your message using code blocks using regular markdown syntax?

Following documentation (<https://quarto.org/docs/authoring/language.html#alternate-language>), in `_quarto.yml`:

```
language:
  title-block-author-single: "SOmething instead author"
  toc-title-document: "A thing of things"
```

**Reply by KennethGottfredsen** [reply]
Hi, 
I'm going to make a PR next week, it surely is needed. I did copy and paste your code example into my yaml. But it didn't work. I don't understand why? I read on the Quarto homepage that it work no matter the projekt type.  
```
language:
  title-block-author-single: "SOmething instead author"
  toc-title-document: "A thing of things"
```
Below is my yaml code in code block:
```
project:
  type: book

book:
  title: "Studiebog"
  subtitle: "Opgavebesvarelse i R4D"
  author: "Kenneth Gottfredsen"
  date: 5/22/2022
  language: 
    title-block-author-single: "Forfatter"
    title-block-published: "Udgivet"

  chapters:
    - index.qmd
    - intro.qmd
    - opgaver.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt

editor: visual
```
/ Kenneth

**Reply by dragonstyle** [reply]
Will you try placing the language at the root level (versus within the project)? We generally only respect certain project specific options as children of the project (we are adding validation in these cases as well to provide an error when you specify a key that isn't expected within the project...).

```
project:
  type: book

book:
  title: "Studiebog"
  subtitle: "Opgavebesvarelse i R4D"
  author: "Kenneth Gottfredsen"
  date: 5/22/2022
  chapters:
    - index.qmd
    - intro.qmd
    - opgaver.qmd
    - summary.qmd
    - references.qmd

language: 
  title-block-author-single: "Forfatter"
  title-block-published: "Udgivet"

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt

editor: visual
```
