### DISCUSSION TITLE
Can't change mainfont in revealjs presentation

### DISCUSSION THREAD

**Discussion by mickmcq** [quarto-dev/quarto-cli#2669] [Q&A] [answered]
I have the following YAML header in a revealjs presentation.

```
---
title: Statistics, Intro
author: Mick McQuaid
date: 2022-09-29
format:
  revealjs:
    mainfont: serif
---
```
No matter what I choose in place of serif, such as Times New Roman, Georgia, or STIX, I get the fonts from the default theme. I'm rendering this by saying

```bash
quarto render index.qmd --to revealjs
```

Whenever I use any theme, its font is properly loaded, but I can't seem to change that either.
