### DISCUSSION TITLE
Website navbar logo size

### DISCUSSION THREAD

**Discussion by mikldk** [quarto-dev/quarto-cli#2754] [Q&A]
I have a website based on `_quarto.yml` containing 
```
website:
  navbar:
    title: false
    pinned: true
    logo: "logo.png"
```
Is it possible to control the height of the navbar anywhere? And/or increase the size of the logo?
