### DISCUSSION TITLE
Duplicate post summary in blog

### DISCUSSION THREAD

**Discussion by harrelfe** [quarto-dev/quarto-cli#2763] [Q&A] [answered]
In my blog at https://hbiostat.org/blog you'll see that the article summary for the most recently posted article is duplicated, with an extra entry at the top that does not contain the title, date, or author, and has reading minutes of 0.  Here's key elements of my setup:

# _quarto.yml
````
project:
  type: website

website:
  title: "Statistical Thinking"
  site-url: "https://fharrell.com"
  google-analytics: "G-...."
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Frank Harrell. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/harrelfe/
      - icon: twitter
        href: https://twitter.com/f2harrell
      - icon: envelope
        href: mailto:fh@fharrell.com
  twitter-card:
    creator: "@f2harrell"
    card-style: summary_large_image
  navbar:
    title: "Statistical Thinking"
    background: "#000000"
    foreground: "#FFFFFF"
    pinned: true
    left:
    - text: "Frank Harrell"
    right:
      - about.qmd
      - text: Posts
        href: post/
      - text: Talks
        href: talk/
      - text: Datamethods
        href: datamethods.qmd
      - text: News
        href: https://paper.li/stn
      - text: Links
        href: https://hbiostat.org
      - text: Bio
        href: https://hbiostat.org/fh
      - text: Publications
        href: https://www.zotero.org/groups/feh/items/q/Harrell
      - icon: github
        href: https://github.com/harrelfe
      - icon: twitter
        href: https://twitter.com/f2harrell

format:
  html:
    smooth-scroll: true
    theme: [litera, styles.scss]
    css: h.css
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    toc-depth: 3
    toc-title: Contents
    toc-location: left
    code-link: false
    anchor-sections: true
    code-tools: true
    code-fold: true
    code-block-bg: "#f1f3f5"
    code-block-border-left: "#31BAE9"
    reference-location: margin
    fig-cap-location: margin

comments:
  hypothesis:
    theme: clean
    openSidebar: false
    enableExperimentalNewNoteButton: true

execute:
  warning: false
  message: false
````

# index.qmd
````
---
title: "Statistical Thinking"
listing:
  - id: post
    contents: post/**/*.qmd
    sort: "date desc"
    type: default
    fields: [date, title, description, categories, author, reading-time]
    categories: cloud
    sort-ui: false
    filter-ui: false
    page-size: 3
  - id: talk
    contents: talk/**/*.qmd
    sort: "date desc"
    type: default
    fields: [date, title, description, categories, author]
    categories: cloud
    sort-ui: false
    filter-ui: false
    page-size: 3
page-layout: full
title-block-banner: false
include-in-header: meta.html
toc: true
---

## Posts

::: {#post}
:::

## Talks

::: {#talk}
:::
````

# post/index.qmd

````
---
title: ""
listing:
  - id: post
    contents: "*/*.qmd"
    type: default
    fields: [date, title, description, categories, author, reading-time]  
    sort: "date desc"
    categories: cloud
    sort-ui: true
    filter-ui: true
    page-size: 10
page-layout: full
title-block-banner: false
---



::: {#post}
:::
````

# talk/index.qmd

````
---
title: ""
listing:
  - id: talk
    contents: "*/index.qmd"
    type: grid
    fields: [date, title, description]
    sort: "date desc"
    categories: cloud
    sort-ui: false
    filter-ui: false
    page-size: 12
page-layout: full
title-block-banner: false
include-in-header: meta.html
toc: true
---

::: {#talks}
:::
````

Any help appreciated.

**Comment by dragonstyle** [comment, marked as answer]
I think the issue is very likely that we're matching some document / file in the file system that is empty (we read the description as rendered HTML out of the output file, so this would require us to both match an empty input file, but also then to somehow get fooled into using a wrong output file). I did make a change to simply ignore fully empty documents (documents with no metadata), which could potentially resolve this, though it would be great to get to the bottom of the mystery.

Can you remind me whether I could take a look at the repo to see if I could reproduce it locally and see if I can catch this one?

**Reply by harrelfe** [reply]
Thanks for the response.  I can zip up the project but to render the whole blog would require installing some R packages.  Anything I can try on a new version of Quarto that would save you the trouble?  I assume that such a try would involve running `quarto render` to let all posts be re-rendered.

**Reply by dragonstyle** [reply]
I fixed the issue with empty metadata 10 days ago, if you're using a release older than that, it is worth trying the latest pre-release just to see whether that resolves the issue (that would confirm that somehow there is an empty document matching the glob pattern for the contents of the listing).  (You can download pre-release builds here: https://quarto.org/docs/download/prerelease.html).

If you're already on a very recent build or that doesn't resolve the issue, then my whole theory is likely cooked, so our best bet remains to let me actually look at what is being resolved for the listing (if you're ok with that). I can always disable execution at least to start and if that reproduces the issue I'll get to the bottom of it quickly!

If you're up for sharing a zip, you can always email me at charles at rstudio dot com if you'd rather not post the zip here.

Perhaps as I fix this issue it will encourage me to add some permanent debug logging that we could enable in the future using `log-level` to make troubleshooting how listings match items more straightforward!

**Reply by harrelfe** [reply]
I was using release build 1.1.251.  I tried the latest pre-release and what changed is that the summary is abbreviated to 3 lines with ... at the end of the last line.  Result is on https://hbiostat.org/blog .  It's still duplicating the first post summary (in part).  If I go to hbiostat.org/blog/post there is nothing duplicated.   It's only a problem when I'm showing both posts and talks on the home page.

**Reply by dragonstyle** [reply]
I did just build an update which includes some additional debug logging that might help. If you render your site (in particular the listing pages) as so:

`quarto render listing.qmd --log-level debug 2>&1 | grep "\\[listing\\]"`

You should see debug message that will help us see what the various listings are matching (it will output each listing, the contents, the files that match, and any files that have an empty title).

This is available starting in `.205` here https://quarto.org/docs/download/prerelease.html

Do you mind giving it a try and seeing if that gives you a clue?

**Reply by harrelfe** [reply]
Hi Charles - there is no listing.qmd so I dropped that and rendered everything.  The rendering got stuck at this file and never completed: https://hbiostat.org/attach/index.qmd

The output up until that point is here: https://hbiostat.org/attach/listing - you'll see a warning there about a missing title in one file.

**Reply by dragonstyle** [reply]
OK that is great- I think I actually figured it from that debug message! I believe that the issue is that the root listing has globs that match pages that are themselves listings (in this case the post listing on the main page is itself processing the posts listing page itself).  This listing `/home/harrelfe/R/blog/q/index.qmd` is matching the listing page `/home/harrelfe/R/blog/q/post/index.qmd` (which is itself a listing page).

You could test this by updating the 'contents' glob to exclude that page in particular something like:

```
contents:
  - post/**/*.qmd
  - !post/**/index.qmd
 ```

That should cause the listing not include the sub listing page and likely resolve the issue. I'm not sure what the correct behavior for us is in this situation - on one hand, if a user provides a glob that matches a listing page it seems wrong to exclude that. On the other hand, this is very frequently going to be something that user don't want to happen! I'll give some thought to whether this is something we could detect and avoid somehow...

**Reply by harrelfe** [reply]
Now I have the following in the top level `index.qmd` 

```
title: "Statistical Thinking"
listing:
  - id: post
    contents:
      - post/**/*.qmd
      - !post/**/index.qmd
    sort: "date desc"
    type: default
    fields: [date, title, description, categories, author, reading-time]
    categories: cloud
    sort-ui: false
    filter-ui: false
    page-size: 3
  - id: talk
    contents:
      - talk/**/*.qmd
      - !talk/**/index.qmd
    sort: "date desc"
    type: default
    fields: [date, title, description, categories, author]
    categories: cloud
    sort-ui: false
    filter-ui: false
    page-size: 3
page-layout: full
title-block-banner: false
include-in-header: meta.html
toc: true
```
But I get an error:

```
ERROR: YAMLError: unknown tag !<!post/**/index.qmd> at line 8, column 5:
        sort: "date desc"
        ^
```

**Reply by dragonstyle** [reply]
Ahh apologies- can you try quoting the contents which starts with `!` (I think that is some kind of reserved YML character)

**Reply by cscheid** [reply]
Yes, `!` is a special YAML thing :( Let me see if I can improve that error message.

**Reply by harrelfe** [reply]
Quoting it got rid of the syntax problem:
```
listing:
  - id: post
    contents:
      - post/**/*.qmd
      - "!post/**/index.qmd"
  ```

But unfortunately the first 3 lines of the duplicated summary are still there with Quarto 1.2.205 on https://hbiostat.org/blog
