### DISCUSSION TITLE
Moving slide numbers to footer in revealjs

### DISCUSSION THREAD

**Discussion by produnis** [quarto-dev/quarto-cli#2766] [Q&A] [answered]
Hi there,
is it possible to move the slide numbers to footer in revealjs? (directly into the footer, not as a separate field under the footer)

Thx and greetings
Joe

**Comment by mcanouil** [comment, marked as answer]
Yes, you'll have to modify the (S)CSS for the "slide-number" and also the position for the logo.

> (directly into the footer, not as a separate field under the footer)

I don't know what you mean by that.

Take a look at one of my templates: https://github.com/mcanouil/quarto-revealjs-coeos/blob/main/_extensions/coeos/coeos.scss

**Reply by produnis** [reply]
this is exactly what I was looking for!!
THX A LOT!

**Reply by produnis** [reply]
```

// Slide numbers to the bottom-left
.slide-number, .reveal.has-logo .slide-number {
  bottom: 14px !important;
  left: 50px !important;
  top: unset !important;
  color: #777777 !important;
}

```

**Reply by mcanouil** [reply]
You also need to move the logo if there is one:

```css
.slide-logo {
  display: block !important;
  position: fixed !important;
  top: 0 !important;
  right: 10px !important;
  max-height: 15% !important;
  height: 100% !important;
  width: auto !important;
  color: $body-color !important;
}
```
