### DISCUSSION TITLE
Cross-references for multiple figures?

### DISCUSSION THREAD

**Discussion by mattocci27** [quarto-dev/quarto-cli#2792] [Q&A] [answered]
This example is rendered as `Fig. 1 and Fig. 2`. How can I get `Figs. 1-2` using cross-references ? 

````
---
title: "My document"
crossref:
  fig-title: Fig.
  fig-prefix: Fig.
format:
  html:
    toc: true
    html-math-method: katex
    css: styles.css
---

```{r}
#| label: fig-plot
#| fig-cap: "Plot"

plot(cars)
```


```{r}
#| label: fig-plot2
#| fig-cap: "Plot 2"

hist(rnorm(100))
```

@fig-plot and @fig-plot2.

````
