### DISCUSSION TITLE
Customize prefix outputs of figure/theorem/... in HTML outputs

### DISCUSSION THREAD

**Discussion by AlbertLei** [quarto-dev/quarto-cli#2798] [Q&A] [answered]
When I use cross-ref like `See @sec-gdp`, the output is `See Chapter 1`.

But my ducoment is in French. I wish the output will be `See Chapitre 1`. A work-around is to use [Chapitre -@sec-gdp]. But I am wondering if there's a direct method?
Also, that work-around does not work if I want the output of my numbered theorem environment to be `théorème 1`.

I have checked the docs on [crossref options](https://quarto.org/docs/authoring/cross-references.html#options). But the `fig-title` and `fig-prefix` options doesn't work for me. TBH, I do not really understand what the options do from the docs.

I am using quarto v1.1.251 on mac.

**Comment by AlbertLei** [comment]
More specifically, I was asking how to do ["Internationalization" like bookdown](https://bookdown.org/yihui/bookdown/internationalization.html)

**Comment by AlbertLei** [comment]
Turns out the corssref options are exactly what I need. 

I initially put the corssref options under `book:`, and it did not work.  After moving them to the `format:html:` option, everything works.

**Reply by AlbertLei** [reply]
I am relatively new to quarto, but [the documentation](https://quarto.org/docs/authoring/cross-references.html#options) seems a little bit misleading for me. 
The example implies that the `crossref` option is at the same level of `title`? 

However, I find the following not working:

```yml
project:
  type: book

book:
  title: "Économie"
  crossref:
      fig-title: FIGURE # (default is "Figure")

format:
  html:
    theme: cosmo
```

And the following works:

```yml
project:
  type: book

book:
    title: "Économie"

format:
  html:
    theme: cosmo
    crossref:
      fig-title: FIGURE # (default is "Figure")
```

**Reply by dragonstyle** [reply]
The documentation is showing a single document that is setting cross reference options (and hence the title and other elements like `crossref` are in the root. In the case of a project, I would put them in the same place. We don't read them out of the `book` key since they aren't `book` specific options, but instead general Quarto configuration options.

```
project:
  type: book

book:
  title: "book"
  author: "Jane Doe"
  date: "10/11/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

crossref:
  fig-title: FIGURE # (default is "Figure")
```
