### DISCUSSION TITLE
Including LaTeX macros from a file into a quarto book

### DISCUSSION THREAD

**Discussion by baptiste** [quarto-dev/quarto-cli#2845] [Q&A]
Maybe I've missed something in the docs, but I can't find a clear way to include an entire file of LaTeX macros. Say I have a file `_macros.tex` full of `\newcommand` macros as I'm writing a book involving lots of equations, what's the best way to make those macros known to pandoc+mathjax when it's rendering the content (either to html or pdf)?

What I currently have is this in my `_quarto.yml`:

````
  html:
    include-in-header:
       - "_dollar.tex"
       - "_macros.tex"
       - "_dollar.tex"
  pdf:
    include-in-header:
       - "_macros.tex"
````

where `_dollar.tex` is a dummy file containing `$$`. This seems to work, but the dummy `$$`s isn't very elegant. Have I missed some way to include both files and raw text in the header?

EDIT: No, actually, this works for the chapters where I do use maths, but for the others I get the raw content dumped above the page.

The alternative seems to be inserting the macros into each `qmd` file as follows:

```
::: {.content-hidden}
$$
{{< include _macros.tex >}}
$$
:::
```

which suits Mathjax. For LaTeX, the macros are still fed (once) via `include-in-header`, and the `{.content-hidden}` includes are not written in the tex file, so this seems to work.
