### DISCUSSION TITLE
Spacing around callout boxes

### DISCUSSION THREAD

**Discussion by mastoffel** [quarto-dev/quarto-cli#2847] [Q&A] [answered]
When using callout blocks, there is a really large spacing between the text and the callout, and I'd like to change that. 'm also using `.column` as I actually want two callouts side by side, which seems to increase the spacing further.
Any help is very much appreciated!

```
This is some text.

::: {.callout-warning .column collapse="true"}
# a callout
:::
```

And here my rendered html output:

<img width="587" alt="Screenshot 2022-10-14 at 08 36 22" src="https://user-images.githubusercontent.com/7348440/195789719-2f8cb606-da1f-470d-a56d-19dbb43b1847.png">

**Comment by mcanouil** [comment, marked as answer]
You can modify the `callout` CSS class.

```css
.callout {
  margin-top: 0; /* 1.25rem by default */
  margin-bottom: 0; /* 1.25rem by default */
}
```

PS: could you change the category from "General" to "Q&A"? (you have to use the desktop view of GitHub webpage to do that)
