### DISCUSSION TITLE
Using qmd files in the front matter

### DISCUSSION THREAD

**Discussion by fredguth** [quarto-dev/quarto-cli#2872] [Q&A]
I have been trying to create a Project template  for a custom thesis with the Brazilian Academic Standard (ABNT) extending dragonstyle/abnt proof-of-concept.

My problem is that I want to let people write "dedication" and "acknowledgment" pages in the frontmatter by adding qmd files.
Ideally the _quarto.yml would have a `frontmatter` section similar to `chapters`:
``` yaml
...
frontmatter:
   - frontmatter/dedication.qmd
   - frontmatter/acknowledgments.qmd
   - frontmatter/epigraph.qmd
chapters:
  - chapters/introduction.qmd
...
````
The table of contents would be rendered between the frontmatter and the body/chapters section.

Extensions like [Quarto Thesis] or [Quarto Titlepages] handle these with `tex` includes and that is how I am dealing with it now.  One could also just use metadata and include them in the tex (which I dislike because you end up with a huge yaml file).  But I wonder if it would be possible to use the `frontmatter/dedication.qmd` tex output in the `before-body.tex`.
