### DISCUSSION TITLE
"Untitled" on tablet screens

### DISCUSSION THREAD

**Discussion by stuvjordan-uroc** [quarto-dev/quarto-cli#2892] [Q&A]
Hi!

I'm building lecture notes with a quarto website.

When viewed on a tablet-sized screen, a big ugly "(Untitled)" is showing up at the top of each page.

Here's what it looks like (this is a screen shot from a simulated ipad in the chrome browser)

![image](https://user-images.githubusercontent.com/78857503/196258610-ee74e58e-bbf7-4f8c-9d12-e4ff6c5b3641.png)

In contrast, here it is on a wide screen:

![image](https://user-images.githubusercontent.com/78857503/196258832-ed4c5574-d7d1-4af8-b6c8-852dd569effb.png)

As you can see, that "(Untitled)" seems to be showing up in what appears to be a dropdown.  When I click/touch on the dropdown it expands to give a list of links to the sections on the page.  (Thus the dropdown is redundant to the floating right-hand TOC).

[You can see the site live page from which screenshots above were taken here](https://stuvjordan.digitalscholar.rochester.edu/learningppt/lesson3/lesson.html)

Here's my `quarto.yaml`:

```
project:
  type: website

execute: 
  echo: false

bibliography: references.bib

website:
  title: "Learning Positive Political Theory"
  navbar:
    right:
      - text: "Lessons"
        menu:
          - text: "Lesson 1"
            file: lesson1/lesson.qmd
          - text: "Lesson 2"
            file: lesson2/lesson.qmd
          - text: "Lesson 3"
            file: lesson3/lesson.qmd
          - text: "Lesson 4"
            file: lesson4/lesson.qmd
  sidebar: 
    - title: "Lesson 1"
      contents: 
        - lesson1/lesson.qmd
        - lesson1/cou1.qmd
        - lesson1/cou2.qmd
        - lesson1/cou3.qmd
        - lesson1/cou4.qmd
    - title: "Leaning Positive Political Theory"
      contents:
        - lesson1/lesson.qmd
    - title: "Lesson 2"
      contents:
        - lesson2/lesson.qmd
        - lesson2/cou1.qmd
        - lesson2/cou2.qmd
        - lesson2/cou3.qmd
        - lesson2/cou4.qmd
        - lesson2/cou5.qmd
        - lesson2/cou6.qmd
    - title: "Lesson 3"
      contents:
        - lesson3/lesson.qmd
        - lesson3/cou1.qmd
        - lesson3/cou2.qmd
        - lesson3/cou3.qmd
        - lesson3/cou4.qmd
        - lesson3/cou5.qmd
        - lesson3/cou6.qmd

format:
  html:
    theme: 
      light: litera
      dark: solar
    css: styles.css
    toc: true
    link-external-newwindow: true
    html-math-method: katex
```
