### DISCUSSION TITLE
How to embed a bookdown gitbook in a quarto website (as a navbar item)?

### DISCUSSION THREAD

**Discussion by lnalborczyk** [quarto-dev/quarto-cli#2913] [Q&A] [answered]
Hi all,

I have a `quarto` website and a .html file of a gitbook made with `bookdown` (located in a subfolder called `_notes` of the quarto website). How can I embed this gitbook within the `quarto` website?

The source code of the quarto website is available at: https://github.com/lnalborczyk/IMSB2022
The rendered version of the website (rendered via Github pages) is available at: https://www.barelysignificant.com/IMSB2022/

Now, I would like to redirect to the bookdown gitbook (i.e., the `index.html` file located in `_notes/docs/`) when I click on "Notes" in the navbar. Therefore, I have added the following command in my navbar options in `_quarto.yml`:

```
  navbar:
    pinned: true
    search: true
    background: "#1c5253"
    right:
      - syllabus.qmd
      - planning.qmd
      - content/index.qmd
      - resources.qmd
      - install.qmd
      - text: "Notes"
        href: "_notes/docs/index.html"
```

And also added the bookdown folder as a resource using:

```
  resources:
    - "files/"
    - "_notes/docs/"
```
    
This works locally (i.e., via "preview website"), but fails when rendering via Github pages (i.e., it gives a 404 error message).

Any idea on how to make it work online?

Thank you for your help!

Ladislas
