### DISCUSSION TITLE
Book – keep both pdf and html outputs in _book directory

### DISCUSSION THREAD

**Discussion by baptiste** [quarto-dev/quarto-cli#2960] [Q&A]
I'm a bit stumped with this: I'm using quarto to write a book, with the following Yaml (simplified):

````
project:
  type: book
  output-dir: "_book"

execute:
  echo: false

book:
  title: "stuff"
  author: "baptiste"
  date: "21/10/2022"
  chapters:
    - "index.qmd"
    - "01-introduction.qmd"
    - "02-theory.qmd"
    - "03-applications.qmd"
    - "90-appendix.qmd"
    - "99-references.qmd"

bibliography: references.bib

format:
  html:
    theme: cosmo
    keep-md: true
  pdf:
    documentclass: krantz
    keep-md: true
    keep-tex: true

engine: knitr
````

For some reason, when I render to html, the previous pdf output is deleted, and the opposite happens when I render to html. How could I keep both outputs?
