### DISCUSSION TITLE
How to create a index.xml (sitemap) for Quarto books?

### DISCUSSION THREAD

**Discussion by maikol-solis** [quarto-dev/quarto-cli#2964] [Q&A] [answered]
Hi! 

It seems that websites create automatically an index.xml (sitemap) for indexing purposes.  For example, I have this line on my website.

![image](https://user-images.githubusercontent.com/4078489/197215501-9278066c-1a29-44ad-8290-da3907546221.png)

However, the same link isn't generated by default for books. 

How could I enable this feature for them? 

Best.

**Comment by dragonstyle** [comment, marked as answer]
That link tag is actually to an RSS feed (not a sitemap). Quarto does create sitemaps at `sitemap.xml` in the root of your site, but only if the `site-url` option has been site.

Perhaps that is causing the sitemap to not be generated for your book. For example in your `_quarto.yml`:

```yml
book:
  title: "Book"
  author: "Jane Doe"
  date: "10/20/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  site-url: https://www.example.com
```

should result in the generation of `sitemap.xml` in your output directory (e.g. `_book/sitemap.xml`).
