### DISCUSSION TITLE
Quarto Custom Grid Listing

### DISCUSSION THREAD

**Discussion by mcanouil** [quarto-dev/quarto-cli#2989] [Show and Tell]
# Quarto Custom Grid Listing

A demo for a custom grid listing which adds some boxes with hyperlinks for slides and code.
Source: <https://github.com/mcanouil/quarto-grid-listing>

```yaml
slides:
  text: <default: Slides>
  url: <url>
code:
  text: <default: Code>
  url: <url>
```

Or

```yaml
slides: <url>
code: <url>
```

<img width="1624" alt="Screenshot of a rendered custom grid listing made with Quarto showing a blue navbar at the top with quarto-grid-listing as title, a Home link.
Below two cards on a three columns layout with image at the top, a title, a description, author on the left and date on the same line on the right.
Below button link hyperref links for slides and code in the first card, and my best ever slides and github custom text links." src="https://user-images.githubusercontent.com/8896044/197393954-831d74fa-ba5b-4992-9c7b-b6090f563c45.png">
