### DISCUSSION TITLE
Error In Callout Insertion

### DISCUSSION THREAD

**Discussion by samarzayan** [quarto-dev/quarto-cli#3001] [Q&A] [answered]
I am getting the following error exactly at the last `:`.
`YAMLError: end of the stream or a document separator is expected at line 7, column 3:`
when I use every callout block, for example:
`:::{.callout-note}`
`Sample note.`
`:::`
I checked online for about 2 hours but had no luck. Someone, please help. 
The syntax is correct as per the Quarto [docs](https://quarto.org/docs/authoring/callouts.html).

**Comment by mcanouil** [comment]
As is, it's not enough to help.
Could you provide a full small reproducible example document?
Can you also indicate which version of Quarto you are using?

**Reply by samarzayan** [reply]
Things have gotten worse. I am getting all sorts of YAML errors. It was fine till a few hours back. It suddenly started getting messed up. Here is the code block
```
---
title: "Lesson 0"
---
{{< video https://www.youtube.com/embed/gGxe2mN3kAg >}}
---
## About
This lesson is a perfect guide on "How To Fast.ai?"

It helps a learner in knowing:

1. How to get the most out of this course?
2. How to make sure s/he finishes it?
3. How to make sure it has been a productive learning experience?

In an overall sense, this lesson gears a learner with the best approaches to this course which Jeremy heard from various students.

Most often, some students, only after finishing the course, when they reach the end, realize what to do and what not to do and they begin again from the start. To avoid this does not happen, the tips shared in this lesson will be quite helpful.

Apart from all this, the lesson depicts the actual mechanics of setting up two environments, Google Colab and AWS EC2. This is what we will be using while actually coding.

:::{.callout-note}
The coding environment is different in the 2022 version of the course. Hence, this setup may not be relevant.
:::

```
The above is showing the following error:

<img width="732" alt="error" src="https://user-images.githubusercontent.com/115773644/197516584-a7fef4f5-0b95-47f8-aabc-2a91224efe62.png">

[This](https://codebeautify.org/yaml-validator) YAML validator can help track the errors online. 

As far as the version is concerned, I have set up v1.1.251 and v1.2.237. The latter to enable video embedding feature..

**Reply by mcanouil** [reply]
Your header is wrong.
You have an extra set of `---` which is likely the reason why YAML parsing is messed up.
Try with:

````
---
title: "Lesson 0"
---

{{< video https://www.youtube.com/embed/gGxe2mN3kAg >}}

## About

This lesson is a perfect guide on "How To Fast.ai?"

It helps a learner in knowing:

1. How to get the most out of this course?
2. How to make sure s/he finishes it?
3. How to make sure it has been a productive learning experience?

In an overall sense, this lesson gears a learner with the best approaches to this course which Jeremy heard from various students.

Most often, some students, only after finishing the course, when they reach the end, realize what to do and what not to do and they begin again from the start. To avoid this does not happen, the tips shared in this lesson will be quite helpful.

Apart from all this, the lesson depicts the actual mechanics of setting up two environments, Google Colab and AWS EC2. This is what we will be using while actually coding.

:::{.callout-note}
The coding environment is different in the 2022 version of the course. Hence, this setup may not be relevant.
:::
````

**Comment by samarzayan** [comment, marked as answer]
I included that as a break line.

**Reply by dragonstyle** [reply]
I'm not seeing an error when I render that document - are there other files that could potentially be involved (a `_quarto.yml` file or `_metadata.yml` file)?

**Reply by samarzayan** [reply]
There is a `_quarto.yml` file involved.
Here are its contents:
```
project:
  type: website

website:
  title: "Samar Zayan"
  favicon: favicon.png
  search:
    location: navbar
    type: overlay
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "fast.ai"
        file: fast.ai.qmd
      - text: "About"
        file: about.qmd
  sidebar:
    - title: "fast.ai"
      style: "docked"
      contents:
        - fast.ai.qmd
        - section: "Practical Deep Learning For Coders"
          contents:
            - section: "Lesson Notes"
              contents:
                - lesson0.qmd
                - lesson1.qmd
            - text: "---"
            - section: "Text Book Notes"
              contents:
                - chapter1.qmd
            - text: "---"
            - section: "Code Experiments"
              contents:
                - safedriving.qmd
        - section: "Live Coding"
          contents:
            - live_coding_1.qmd
            - live_coding_2.qmd
        - text: "---"
  page-navigation: true
  reader-mode: true
format:
  html:
    mainfont: "Ebrima"
    theme: theme.scss
    css: styles.css
    toc: true
```
