### DISCUSSION TITLE
Unicode missing from beamer/pdf in Julia

### DISCUSSION THREAD

**Discussion by sje30** [quarto-dev/quarto-cli#3076] [Q&A]
Hi,
I've got a small test document that I'm converting to pdf using
    quarto render temp.qmd

where the unicode characters for alpha and beta are found in the test.tex file, but not rendered in the pdf.

it seems to be using xelatex for the compilation -- what am I missing to get the unicode in the pdf?

thanks, Stephen

p.s. given how Julia uses unicode, I'd like to get this working on Julia code snippets, but have reduced it to this simpler example first.  It didn't work when I was using the unicode operator \in ∈

## Test file

```
---
title: "test of julia"
author: "SJE"
engine: jupyter
execute:
  echo: true
format:
  beamer:
    keep-tex: true
---

## Test slide

Some text with greek >>  α ϐ << here

```

## page 2 of temp.pdf
<img width="604" alt="Screenshot 2022-10-27 at 20 44 56" src="https://user-images.githubusercontent.com/1095067/198383911-c62558ce-d1fe-4d10-9e90-29947950a8da.png">

**Comment by cscheid** [comment]
The issue here is that the standard LaTeX font does not have support for text-mode unicode characters like that. You'll need to select fonts that do have that support. This is unfortunately not something that we can solve in general in Quarto itself because different fonts have access to different subsets of the Unicode code points.

It _is_ unfortunate that greek characters are commonplace in Julia code, and that they're not available in (eg) Computer Modern and Computer Modern Sans Serif. We should document that better, but this is not a quarto bug.

**Reply by sje30** [reply]
Thank you.  Yes, given that the .tex file seemed okay, I thought it would be an issue with processing of the .tex.  I'll see what I can do with changing font.  (Not a big fan of computer modern in any case...!)

**Reply by cscheid** [reply]
Ideally, xelatex would warn that some glyphs are not available, but evidently it does not.

In the meantime, I think the syntax is:

```
format:
  pdf:
    mainfont: "Times New Roman"
    monofont: "Monaco"
    sansfont: "Helvetica Neue"
```

You will, of course, need to have those fonts installed in your system.
