### DISCUSSION TITLE
[Feature Request]: Logo in Revealjs could be clickable

### DISCUSSION THREAD

**Discussion by ginolhac** [quarto-dev/quarto-cli#3082] [Feature Requests]
Hi,
In Quarto websites, all pages offer the navbar except slides. Meaning that once in a slide deck we cannot easily return to the website. That was feasible using {xaringanExtra} [logo](https://pkg.garrickadenbuie.com/xaringanExtra/logo/#2).
I was thinking about this kind of feature that would enable the logo to be a link:
``` yaml
---
title: "click logo"
format: 
  revealjs:
    logo: 
      file: https://www.r-project.org/logo/Rlogo.svg
      href: https://www.r-project.org
---

```
Or a markdown code :
``` yaml
 logo: [https://www.r-project.org/logo/Rlogo.svg](https://www.r-project.org)
```
I could be using an universal footer but I often use them to comment on the content of a specific slide.

Many thanks for this amazing tool!
