### DISCUSSION TITLE
Listing field not inherited from global _quarto.yml

### DISCUSSION THREAD

**Discussion by kris-brown** [quarto-dev/quarto-cli#3088] [Q&A]
Hi, I have a global `_quarto.yml` with a `date: last-modified` line which applies to all the `.qmd` files in my project. 

I then have a listing in my project:
```
listing: 
  categories: true
  type: table
  fields: [title, categories, date]
```
But the `date` field is rendered empty unless I explicitly put `date: last-modified` in the corresponding files. Is there anything I can do such that the listing defaults to the global `yml` file when a field isn't found?
