### DISCUSSION TITLE
Broken output from a Julia chunk

### DISCUSSION THREAD

**Discussion by sje30** [quarto-dev/quarto-cli#3091] [Q&A]
Using quarto 1.1.251 with the following file:

````
---
title: "test of julia"
author: "SJE"
engine: jupyter
execute:
  echo: true
format:
  beamer:
    keep-tex: true
    monofont: "JuliaMono"
---

## Test slide

```{julia} 
println(typeof(ones(3,2)))
```

````

generates the following output
<img width="592" alt="Screenshot 2022-10-28 at 16 56 15" src="https://user-images.githubusercontent.com/1095067/198680965-0007c6af-7674-404c-a9c3-af4d5dfa3100.png">

Here is the relevant .tex chunk

```

\begin{verbatim}
Matrix{
\end{verbatim}

\begin{verbatim}
Float64}
\end{verbatim}
```

whereas it should read `Matrix{Float64}`
