### DISCUSSION TITLE
how to use the listings package for code blocks in pdf output

### DISCUSSION THREAD

**Discussion by Achuan-2** [quarto-dev/quarto-cli#3101] [Q&A] [answered]
such as set breaklines=true

**Comment by Achuan-2** [comment, marked as answer]
```yaml
---
title: "My Document"
author:
  - 苏济雄
toc: true
number-sections: true
monofont: "Consolas"
crossref:
  chapters: true
  fig-title: 图    # (default is "Figure")
  tbl-title: 表     # (default is "Table")
  title-delim: ' '     # (default is ":")
  fig-prefix: 图   # (default is "Figure")
  tbl-prefix: 表    # (default is "Table")
format:
  pdf:
    # toc
    fig-cap-location: bottom
    toc-depth: 2
    toc-title: Contents
    # code
    code-block-bg: '#f1f3f5'
    # output
    documentclass: article # scrartcl，article, report or book
    papersize: a4 # a4, letter
    colorlinks: true
    #classoption: [twocolumn,landscape] # twocolumn, landscape
    keep-tex: true
    tbl-colwidths: false
    tbl-cap-location: top
    listings: true
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    include-in-header:
      text: |
        \usepackage{ctex}    % CJK 包
        \usepackage[dvipsnames]{xcolor}
        \setCJKmainfont[BoldFont={方正大标宋简体}]{方正宋三简体}
        \setmainfont{Times New Roman} %英文字體調整
        \lstset{basicstyle=\ttfamily,breaklines=true,keywordstyle=\bfseries\color{NavyBlue},morekeywords={}, commentstyle=\itshape\color{black!50!white}, stringstyle=\bfseries\color{PineGreen!90!black},columns=flexible,frame=single,framesep=1em
         }

---
```

**Comment by mcanouil** [comment]
I am sorry, but your post lacks contents to understand what you are asking.
Could you properly describe your question/issue, preferably with a minimal and working example?

**Reply by Achuan-2** [reply]
sorry,I have solved my problems in my last reply.
I want to highlight code block by `listings` and set styles to make sure that code blocks breakline automatically
It can be achieved by
```yaml
listings: true
include-in-header:
  text: |
    \lstset{basicstyle=\ttfamily,breaklines=true,keywordstyle=\bfseries\color{NavyBlue},morekeywords={}, commentstyle=\itshape\color{black!50!white}, stringstyle=\bfseries\color{PineGreen!90!black},columns=flexible,frame=single,framesep=1em
     }
```
