### DISCUSSION TITLE
TOC collapsed: false

### DISCUSSION THREAD

**Discussion by MohdAzmiSuliman** [quarto-dev/quarto-cli#3107] [Q&A]
Hi everyone. 

Apologised if this question is already asked.

is there any way we can keep the TOC from collapsing? i want my TOC in my html file to show full TOC.

akin to yaml for rmd below

```
---
title: "Habits"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---
```

thanks.
