### DISCUSSION TITLE
revealjs and hover footnote: how to use it?

### DISCUSSION THREAD

**Discussion by aborruso** [quarto-dev/quarto-cli#3110] [Q&A] [answered]
Hi,
in my file I have

```yml
format:
  revealjs:
    slide-number: true
    preview-links: auto
    navigation-mode: vertical
    center-title-slide: false
    code-line-numbers: false
    footnotes-hover: true
```

And in my slide I have

```
# Note in popup

Ciao^[sono una nota in popup]
```

I have no hover, I have a classic footnote. How to enable the hover?

Thank you

![image](https://user-images.githubusercontent.com/30607/198873682-f0e00ee0-9095-45f7-bd2d-61d75a16f1dc.png)
