### DISCUSSION TITLE
Create short scientific abstract

### DISCUSSION THREAD

**Discussion by cbrnr** [quarto-dev/quarto-cli#3162] [Q&A] [answered]
I would like to create a short scientific abstract (e.g. for submitting to a conference) with Quarto. I saw that there are journal templates, but this seems like too much for this use case.

All I need is support for a few (custom) header (title) fields, which I can't seem to get right:

- Title
- Authors (multiple)
- Affiliations (one per author)
- E-mail (one per author)

And then some text in the document body.

What I tried so far:

```
---
title: "Untitled"
author:
  - name: First Last
    email: first.last@some-domain.com
  - name: Another Person
  - name: Third Author
  - name: Firstly Lastly
affiliation: University of Some Place
format: html
---

## Abstract

Some text.


## Extended abstract

Some more text.
```

The problem here is that in the title block, only the authors show up. Is it possible to also render their affiliations and e-mails?

**Comment by dragonstyle** [comment, marked as answer]
Can you try:

```markdown
---
title: "Untitled"
author:
  - name: First Last
    email: first.last@some-domain.com
    affiliation: University of Some Place
  - name: Another Person
  - name: Third Author
  - name: Firstly Lastly
format: html
---

## Abstract

Some text.


## Extended abstract

Some more text.
```

More on our author and affiliation and schema here: https://quarto.org/docs/journals/authors.html

**Reply by cbrnr** [reply]
Thanks, this does show the affiliations! However, emails still don't show up. Probably because this field is not supported in the default template? If this is the case, is there an easy way to add custom fields without using or creating a full-blown extension?

**Reply by dragonstyle** [reply]
Great - I think you're right that our title block doesn't display email...

You can replace just the title portion of our output with your own template- more here:

https://quarto.org/docs/journals/templates.html#template-partials

with HTML specific partials here:

https://quarto.org/docs/journals/templates.html#html-partials

You don't need to use an extension - you can just reference the template partials directly in your document front matter like:

```markdown
---
title: My Abstract
template-partials:
  - title-block.html
---
```

Which will use a `title-block.html` template sitting next to the document when rendering the HTML title.

**Reply by cbrnr** [reply]
Thank you so much! I will try that, this looks awesome!

**Comment by raphaelbetschart** [comment]
I am also trying to add the email address to the title block, I added the following code (take from the RMarkdown template) to the title-block.html:

```
$if(author.email)$
<a class="author_email" href="mailto:#">$author.email$</a>
$endif$
```

My YAML header looks like this:

```
---
title: My Abstract
author:
  - name: First Last
    email: first.last@some-domain.com
template-partials:
  - title-block.html
 ---
```

However, the email address still doesn't appear, and the date is lost as well.

**Reply by dragonstyle** [reply]
Could you share your complete title block template? I think you'll need to write something different as we have a different author structure that rmarkdown had...

**Comment by raphaelbetschart** [comment]
The title-block.html looks like this:
```
<header id="title-block-header">
<h1 class="title">$title$</h1>
$if(subtitle)$
<p class="subtitle">$subtitle$</p>

$endif$
$for(author)$
<p class="author">$author$</p>
$endfor$

$if(date)$
<p class="date">$date$</p>
$endif$
$if(author.email)$
<a class="author_email" href="mailto:#">$author.email$</a>
$endif$
$if(abstract)$
<div class="abstract">
<div class="abstract-title">$abstract-title$</div>
$abstract$
</div>
$endif$
</header>
```

**Reply by dragonstyle** [reply]
I think this should be more what you're look for:

```
<header id="title-block-header">
<h1 class="title">$title$</h1>
$if(subtitle)$
<p class="subtitle">$subtitle$</p>
$endif$

$for(by-author)$
<p class="author">$by-author.name.literal$</p>
$if(by-author.email)$
<a class="author_email" href="mailto:#">$by-author.email$</a>
$endif$
$endfor$

$if(date)$
<p class="date">$date$</p>
$endif$

$if(abstract)$
<div class="abstract">
<div class="abstract-title">$abstract-title$</div>
$abstract$
</div>
$endif$

</header>
```

In Quarto, we normalize all the author metadata into a consistent, predictable schema (no matter how the author writes the metadata). more about that here:

https://quarto.org/docs/journals/authors.html

**Reply by cbrnr** [reply]
Can I ask two follow-up questions?

1. How can I incorporate affiliations? I tried playing around with it, but I can't get it to show up. For example, I used this header:
```
---
title: My Abstract
subtitle: Various findings
author:
  - name: John Doe
    email: john.doe@xy.z
    affiliations:
      - Institute of Stuff, University of Things, Country
  - name: Another Person
  - name: Third Author
  - name: Firstly Lastly
format: html
template-partials:
  - title-block.html
---
```

2. I assume to get emails and affiliations in a PDF, I would need to edit another partial template? How would that look like?
