### DISCUSSION TITLE
Creating custom metadata for Quarto project book

### DISCUSSION THREAD

**Discussion by eeholmes** [quarto-dev/quarto-cli#3170] [Q&A] [answered]
Background: This is for a Quarto extension. This stopped working with Quarto v1.2 https://github.com/nmfs-opensci/quarto-thesis

With the Quart 1.2 release, on-the-fly creation of metadata stopped working. So a project with this `_quarto.yml` will now throw an error saying that `custom-metadata` is not an allowed metadata variable. 

_quarto.yml
```
project:
  type: book
  output-dir: .

book:
  title: A title
  custom-metadata: "test"
```
Can I define new metadata somewhere?

The documentation page doesn't discuss defining new metadata just customizing the pre-defined metadata for a project type.
https://quarto.org/docs/extensions/project-types.html
It doesn't say if one can create a new project type either like you can create a new format type.

I am using Quarto 1.2.246 .

**Comment by eeholmes** [comment, marked as answer]
Nevermind. I got it working. I just changed to 
```
book:
  title: A title

thesis:
  custom-metadata: "test"
```
And refer to `$thesis.custom-metadata$` in my LaTeX partials.
