### DISCUSSION TITLE
Changing level 1 and level 2 heading sizes in revealjs

### DISCUSSION THREAD

**Discussion by nickriches** [quarto-dev/quarto-cli#3176] [Q&A]
Hi. I am trying to adapt an existing `.scss` file so that markdown level 2 headings (## heading) are smaller than markdown level 1 headings (# heading). Below is the code. I've figured out that `h1` refers to the title slide, and that `h2` refers to markdown level 1 headings. That's all fine. However, I cannot get markdown level 2 headings to appear smaller. The statement `$presentation-h3-font-size: 2.5em;` does not seem to do anything. Whatever I do with `h2` and `h3` the heading sizes seem to default to the larger of the 2 values.

Any suggestions?

Thanks

```scss
/*-- scss:defaults --*/

@import url(./fonts/league-gothic/league-gothic.css);
@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic);

// fonts
$font-family-sans-serif: Lato, sans-serif !default;

// colors
$body-bg: #f7f3de !default;
$body-color: #333 !default;
$link-color: #8b743d !default;
$selection-bg: rgba(79, 64, 28, 0.99) !default;

// headings
$presentation-heading-font: "League Gothic", sans-serif !default;
// $presentation-heading-text-transform: uppercase !default;
$presentation-h1-font-size: 3.77em !default;
$presentation-h2-font-size: 3em;
$presentation-h3-font-size: 2.5em;


// code blocks
$code-block-bg: transparent !default;

/*-- scss:mixins --*/

@mixin bodyBackground() {
  @include radial-gradient(rgba(247, 242, 211, 1), rgba(255, 255, 255, 1));
}


```
