### DISCUSSION TITLE
Adjusting width of about page templates

### DISCUSSION THREAD

**Discussion by nurfatimaj** [quarto-dev/quarto-cli#3190] [Q&A]
Hi!

I like using the `trestles` template for my about page. However, I find the default width to be too narrow (by the way, I couldn't get broadside template to load the about image 🤷🏽‍♀️). 

I was wondering if somebody knows a good way to adjust the width of the template to the desired level in a way that it would also work nicely with different screen sizes?

I managed to get a different width by controlling the `flex-grow`, `flex-shrink` and `flex-basis` CSS properties of `.about-contents` and `.about-entity` classes. Here, are the lines from my styles.css file
```css
.about-contents {
  flex-grow: 3 !important;
  flex-shrink: 0 !important;
  flex-basis: 80% !important;
}

.about-entity {
  flex-grow: 0 !important;
  flex-shrink: 3 !important;
  flex-basis: 20% !important;
}
```
However, these do not work very well with some screen sizes. When it is fairly large, but not full-screen, the text remains too wide and a user needs to scroll the page horizontally. For smaller screen sizes it adapts nicely without a problem. 

I'd appreciate any tip!

**Comment by mcanouil** [comment]
You can use special CSS rules:
```css
@media(max-width: 991.98px){
...
}
```

See <https://www.w3schools.com/css/css3_mediaqueries.asp> and some other online examples/documentation about this.

Also, why don't you change the default width CSS attributes for this layout by modifying the page layout (https://quarto.org/docs/output-formats/page-layout.html)? Setting `page-layout: full` should give you what you want without having to tweak (S)CSS.

FYI, the default specific SCSS for the template you are interested in is:
https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/projects/website/about/about.scss#L165-L223

**Reply by netw0rkf10w** [reply]
> Also, why don't you change the default width CSS attributes for this layout by modifying the page layout (https://quarto.org/docs/output-formats/page-layout.html)? Setting `page-layout: full` should give you what you want without having to tweak (S)CSS.

Could you please be more specific? I tried adding `page-layout: full` but nothing seems to change:

```
---
title: "About"
image: profile.jpg
about:
  id: hero-heading
  template: trestles
html:
  page-layout: full
---
```
