### DISCUSSION TITLE
rel="me" verification on About page links

### DISCUSSION THREAD

**Discussion by obrl-soil** [quarto-dev/quarto-cli#3207] [Feature Requests]
Having recently started a Mastodon account, I see there's an option to help 'verify' one's account against one or more external websites, described in the [docs here](https://docs.joinmastodon.org/user/profile/) and more generally [here](http://microformats.org/wiki/rel-me), with results that look [like this](https://mastodon.social/@Mastodon). tl;dr one adds `rel="me"` to the `<a></a>` tag when linking to one's Mastodon profile from elsewhere.

I'm not sure how to do this on my blog's About page except by editing the HTML immediately after rendering the site and before pushing it to GH pages [like this](https://github.com/obrl-soil/obrl-soil.github.io/commit/7aeb06aaf977df0edc35b2a2eb58da9f76de6afb).

Would it be possible to add an attribute to the yml in `about.qmd` to help automate this? e.g.

 ```
 links:
    - icon: mastodon
      aria-label: Mastodon
      href: https://mastodon.social/@yourhandle
      rel: "me"
```
 
There are other variations I've seen like `rel="me nofollow"` that may also need be handled.

**Comment by dragonstyle** [comment]
This is a nice suggestion -  I created an issue to track this and will try to get to it soon!

**Reply by obrl-soil** [reply]
Thanks!

**Comment by jimjam-slam** [comment]
I'd also love to see this! I tried adding a link manually to my home page body with:

```markdown
[Mastodon verification](https://aus.social/@jimjamslam){rel="me" style="display: none;"}
```

Which renders to:

```html
<p><a href="https://aus.social/@jimjamslam" rel="me" style="display: none;">Mastodon verification</a></p>
```

But it isn't getting picked up. Not sure if `display: none;` is causing it to be ignored, as the Mastodon docs don't place any conditions beyond it having `rel="me"`.

**Reply by jimjam-slam** [reply]
**Update:** the above does, in fact, work! I just had to add the link first and list it on my profile second.

**Comment by mcanouil** [comment]
This feature is in v1.3 pre-release. 🥳
See #3333

Thanks @effigies

**Comment by mjskay** [comment]
Does `rel: me` work on links in the navbar? I tried:

```yaml
website:
  navbar:
    tools:
      - icon: mastodon
        href: "https://hci.social/%40jovi"
        text: JoVI Mastodon
        rel: me
```

And the `rel` attribute doesn't seem to be added to the output HTML. 

(also, I tried `"https://hci.social/@jovi"` at first and the link came out as `"https://hci.social/"`, hence the use of url-encoded `%40` for `@` above --- not sure if that's a bug)

**Reply by cscheid** [reply]
👋 

I can't seem to repro your `@` issue, but I can totally repro the `tools` issue: we don't seem to respect `rel="me"` in the tools navbar. I'll open a bug.

**Reply by mcanouil** [reply]
For the `@` you could use raw inline code.

```yaml
website:
  navbar:
    tools:
      - icon: mastodon
        href: "https://hci.social/`@jovi`{=html}"
        text: JoVI Mastodon
        rel: me
```
