### DISCUSSION TITLE
Cross referencing book parts?

### DISCUSSION THREAD

**Discussion by fuhrmanator** [quarto-dev/quarto-cli#3218] [Q&A] [answered]
I'm trying to include exercises in my book, and I started doing it as appendices, but decided to use parts. So my _quarto.yml looks like:

```yaml
  chapters:
    - index.qmd # Preface
    - part: Theory.qmd
      chapters:
      - Intro.qmd
      # ...
    - part: Exercises.qmd
      chapters:
      - Exercise_blah.qmd
      # ...
```

In my "Theory.qmd" I'm trying to refer to the "Exercises" part via an `@sec-exercises` label that I defined on the `# Exercises {#sec-exercises}` in Exercises.qmd. But there are two problems:

- The code-completion (VSCode) doesn't find the @sec-exercises
- Quarto render/preview gives me `WARNING: Unable to resolve crossref @sec-exercises` and the PDF has **?@sec-exercises**

Is this a bug, or is there some other prefix `part-`? required for part labels?

I tried using a div like `::: {#sec-exercises}` around the part content, but it doesn't help.
