### DISCUSSION TITLE
Changing Dark Theme Toggle Icon

### DISCUSSION THREAD

**Discussion by jdc-pub** [quarto-dev/quarto-cli#3300] [Q&A]
Is there any CSS rule that could easily override the default dark theme toggle icon?

**Comment by dragonstyle** [comment]
Here's a bit of a start - not that this doesn't really address the issue of color, so you may need to provide an explicit color rather than the use of `currentColor` in the example:

```css
.quarto-color-scheme-toggle:not(.alternate) .bi::before {
  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-1-circle" viewBox="0 0 16 16"><path d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8Zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM9.283 4.002V12H7.971V5.338h-065L6.072 6.656V5.385l1.899-1.383h1.312Z"/></svg>') !important;
}
```

HTH!

**Reply by mine-cetinkaya-rundel** [reply]
For anyone else landing here, the following will make the color of the toggle icon white (`rgba(255, 255, 255, 1)`):

```scss
.quarto-color-scheme-toggle:not(.alternate) .bi::before {
  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgba(255, 255, 255, 1)" class="bi bi-toggle-off" viewBox="0 0 16 16"><path d="M11 4a4 4 0 0 1 0 8H8a4.992 4.992 0 0 0 2-4 4.992 4.992 0 0 0-2-4h3zm-6 8a4 4 0 1 1 0-8 4 4 0 0 1 0 8zM0 8a5 5 0 0 0 5 5h6a5 5 0 0 0 0-10H5a5 5 0 0 0-5 5z"/></svg>') !important;
}
```

Note: The `class` of the default toggle icon is `bi bi-toggle-off`.

**Comment by aronvandepol** [comment]
This is by no means an ideal solution, but a little hacky one.

I have both a sun.svg and moon.svg in my assets folder and use the following code to change the toggle by hidding it and using the svg as a background. 

Again this is not ideal (it hides the actual icon and puts a background there.) but it does the job.

``` 
.quarto-color-scheme-toggle {
    display: flex; /* flex container */
    justify-content: center; /* Center horizontally in the container */
    align-items: center; /* Centers vertically in the container */
  }
  .quarto-color-scheme-toggle > i {
    display: inline-block; /* Allows size adjustment */
    width: 20px; /* Set width */
    height: 20px; /* Set height */
    background-image: url(assets/moon.svg); /* Path to your icon */
    background-size: contain; /* Makes sure the image fits the element */
    background-repeat: no-repeat;
    background-position: center;
    text-indent: -9999px; /* Hides the original icon 
    transition: opacity 0.5s ease;
  }
```

**Comment by lukmayer** [comment]
Here's a plug and play solution i arrived on that's a mix of the previous answers.
All you'd have to do is change the color values according to your theme.

```css
/* add extra space to the right of the icon */ 
.quarto-color-scheme-toggle {
  margin-right: 8px !important;
}

.quarto-color-scheme-toggle:not(.alternate) .bi::before {
  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="%234a5568" class="bi bi-moon-stars-fill" viewBox="0 0 16 16"><path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/><path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/></svg>') !important;
}

body.quarto-dark .quarto-color-scheme-toggle > .bi::before {
  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="%23d1d5db" class="bi bi-sun-fill" viewBox="0 0 16 16"><path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.414a.5.5 0 1 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707z"/></svg>') !important;
}
```
