### DISCUSSION TITLE
[feature request] built-in keyboard shortcut for search option

### DISCUSSION THREAD

**Discussion by camilogarciabotero** [quarto-dev/quarto-cli#3327] [Feature Requests]
Hi all, 

Currently, the search option in the YAML has several options:

```  
website:
  search: 
    location: navbar/sidebar
    type: overlay/textbox
    limit: 20
    collapse-after: 2
    copy-button: true/false
```

And it also has the  `algolia`, a third-party search feature that requires extra configuration and has multiple current options, e.g:

```
website:
  search:
    algolia:
      index-name: <my-index-name>
      application-id: <my-application-id>
      search-only-api-key: <my-search-only-api-key>
    index-fields:
      href: url
      section: sec
      text: body
    params:
      tagFilters: ['tag1','tag2']
```

However, as you can see in the main [algolia page](https://www.algolia.com/doc/) they have a nice `ctrl + k` button to enable search focus rapidly. They provide [information](https://www.algolia.com/doc/guides/building-search-ui/resources/unified-instantsearch/tutorials/getting-started/#add-or-remove-the-keyboard-shortcut) to allow it to by just adding `export const keyboardShortcuts = ['+'];` to the `JS` search file. 

I was wondering if there is a built-in way to enable `ctrl + k` in the basic search provided by Quarto, something like:

```  
website:
  search: 
    shortcut: true/false
```
