### DISCUSSION TITLE
Book parts should not be ignored in EPUB output

### DISCUSSION THREAD

**Discussion by ptkw** [quarto-dev/quarto-cli#3332] [Feature Requests]
[According to the documentation](https://quarto.org/docs/books/book-structure.html#parts-appendices), "In EPUB […] output parts are ignored entirely".

This means that books with defined hierarchical structures (i.e. chapters nested inside parts) get a flattened version of table of contents when exported to EPUB, with only a long list of chapters presented in sequence (with no mention of parts to which they are supposed to belong).

This behavior applies to both "styles" of parts as explained in ["Parts & Appendices" section](https://quarto.org/docs/books/book-structure.html#parts-appendices):  
```
# ones with corresponding qmd files:
chapters:
  - index.qmd
  - part: dice.qmd
    chapters: 
      - basics.qmd
      - packages.qmd

# and ones declared only as names:
chapters:
  - index.qmd
  - part: "Dice"
    chapters: 
      - basics.qmd
      - packages.qmd
```

This is a severe limitation that strips the EPUB version of a publication of some very basic functionality as well as essential meaningful information that should be available to the reader. Let me emphasize that the EPUB format absolutely supports hierarchical ToCs with nested items (such as chapters within sections).

Optimally, the hierarchical structure of a book should be preserved for both styles of part declarations: with corresponding qmd files for each part and with only names provided. In the second case, additional html files with section title pages should be generated within the EPUB.

I realize the current state of affairs must result from some limitations of pandoc. I hope, however, that some workaround would be possible.

**Comment by dragonstyle** [comment]
Thanks for the feedback -  we intend to make improvements to our book support sometime soon (not sure of the timing) and I've tagged this so this remains on the radar when we make those improvements.

**Reply by ptkw** [reply]
That's great to hear! I will be looking forward to improvements in this area. Thanks for all your great work!

**Reply by cod3licious** [reply]
Is there any update on this? I'd already be happy if the parts would be included as just a normal chapter, but just ignoring them altogether is really a severe limitation.

I also noticed that in general there seems to be an issue with the ToC hierarchy when `toc-depth > 2`: as soon as, within a chapter, it switches back from a level 3 heading to a level 2 heading, this level 2 heading is instead shown like a level 1 heading. 
Not sure if this is somehow related or also a limitation from pandoc, but it results in confusing ToCs

**Reply by mcanouil** [reply]
> Is there any update on this? I'd already be happy if the parts would be included as just a normal chapter, but just ignoring them altogether is really a severe limitation.

Posts asking "Any news?" or "When will this be ready?" without specific questions or constructive feedback don't help move development forward.
They create notification noise for maintainers without providing actionable input that could influence development priorities.

Rather than asking for general updates, consider asking specific technical questions about implementation, contributing implementation suggestions, or submitting pull requests for features you need.
Consider upvoting and/or adding a "thumb up" on the original message.

The most valuable contributions focus on "here's how I can help solve this" rather than "here's what I want you to do for me."

For the latest information about progress and planned features, check the project's changelog, release notes, or issues.

Thanks for understanding and for your continued interest in the project.

> I also noticed that in general there seems to be an issue with the ToC hierarchy when toc-depth > 2: as soon as, within a chapter, it switches back from a level 3 heading to a level 2 heading, this level 2 heading is instead shown like a level 1 heading.
> Not sure if this is somehow related or also a limitation from pandoc, but it results in confusing ToCs
> We appreciate your interest in the project, but I'd like to share some guidance on how we can make discussions more productive.

This is unrelated to this feature request. Please search for a similar issue/discussion. If none, please open a new discussion with a small but fully reproducible example as described in the discussion template.

**Reply by cod3licious** [reply]
@mcanouil well, sorry for asking about an update on a feature request that was supposed to be addressed "sometime soon" almost 3 years ago. But ok, I upvoted the post instead. Also, I couldn't find any open issue for this feature request, so no idea how to actually get any information about its status except assuming that it is being ignored since there was no more activity on this post since 2022.
And if I was able to help I would, but I'm not, which is why I'm turning to such a forum in the first place....

So maybe to be a bit more specific: It would be great if it was possible to specify an alternative chapter order for epub to include parts as normal chapters instead.
For example:
```yml
# _quarto.yml
project:
  type: book

book:
  title: "Some Title"
  chapters:
    - index.qmd
    - part: part1.qmd
      chapters:
      - 01_chapter.qmd
      - 02_chapter.qmd
    - part: part2.qmd
      chapters:
      - 03_chapter.qmd
      - 04_chapter.qmd
     
format:
  html: default
  epub:
    chapters:
      - index.qmd
      - part1.qmd
      - 01_chapter.qmd
      - 02_chapter.qmd
      - part2.qmd
      - 03_chapter.qmd
      - 04_chapter.qmd
```
I don't get an error when I render to epub with such a setting and the information from `chapters` shows up in the metadata output, but unfortunately it doesn't actually seem to do anything and the resulting epub file is still missing the parts.
