### DISCUSSION TITLE
Share setup chunk across a quarto website

### DISCUSSION THREAD

**Discussion by elgabbas** [quarto-dev/quarto-cli#3388] [Q&A] [answered]
Hello,
Is it possible to allow all pages to share a common setup chunk? I would like to apply the following setup chunk to all pages without the need to copy it to each qmd file. 

Thanks, Ahmed

``````
````{r, include=F}
knitr::opts_chunk$set(
  class.output = "outStyle", results = "hold",
  engine.path = list(
  bash = "C:/Users/Ahmed/AppData/Local/Microsoft/WindowsApps/ubuntu.exe"
))

reticulate::use_condaenv("myenv", required = TRUE) # To use a specific conda environment
````
``````

**Comment by cscheid** [comment, marked as answer]
The recommended solution is to put this in a file (say, `_setup.md`), and then use the include shortcode at every page:

```
{{< include _setup.md >}}
```

**Reply by elgabbas** [reply]
This was very helpful... Thanks

**Reply by mcanouil** [reply]
`knitr` options could also be set globally in `_quarto.yml`.

```yml
knitr:
  opts_chunk:
    class.output: "outStyle"
    results: "hold"
    engine.path:
      - bash: "C:/Users/Ahmed/AppData/Local/Microsoft/WindowsApps/ubuntu.exe"
```
