### DISCUSSION TITLE
Is it possible to list content by category?

### DISCUSSION THREAD

**Discussion by aborruso** [quarto-dev/quarto-cli#3394] [Q&A]
Hi,
I'm making my first step to build my personal website in quarto. I am very excited and happy. And so thanks to all of you

This website will have some pages and a blog.

Inside the blog I will have the "TIL" (Today I have learned) category. I want to give it special attention and in the upper menu I will have both the blog entry and the TIL entry.

I have created this listing for blog

```
---
title: "Blog"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  feed: true
page-layout: full
title-block-banner: true
---
```

I have the categories and then I can insert in the upper menu the link to https://mysite/blog.html#category=til

But I would like to manage in a customized way the TIL posts.
A way is simply create a TIL folder, in which insert all the TIL posts, and create a new qmd listing file in which set `contents: til`, and then in my blog listing add also the til content.

I'm writing here to know if there is a native way to list content by category.

Thank you
