### DISCUSSION TITLE
How can I change the size of a GIF image on the blog index page that lists posts?

### DISCUSSION THREAD

**Discussion by wostrie2** [quarto-dev/quarto-cli#3396] [Q&A] [answered]
Quarto used the gif image in one of my posts as the image for that post on the blog home page that lists all the posts (as desired), but the image there is rather large, not reduced in size like the smaller images for other posts (which are generated from jpegs).

How can I control the size of images on that page? For that matter, how can I change the size images in a post?

Please forgive my beginner questions. I did spend some time searching to see how to do this, but I am new to Quarto, only using it for this blog, and there is a lot to take in. :)

[Here's my blog](https://wostrie2.github.io/blog/), where you can see the GIF is much larger than the other images.

Here's the code for that post:
````
---
title: "I made a simple iOS app."
author: "Bill Ostrie II"
date: "2022-10-22"
categories: [news]
---

I made an iOS app to use the front of my phone as a low-intensity flashlight.

I can choose the color of the screen and adjust the brightness.

This sort of thing is useful if you have a migraine, or don't want to lose your night vision, or don't want to wake someone else up. It's a Storyboard app. I might re-make it again to learn how to do the layout just in code, and also make it again with SwiftUI.



![](myLight.gif)

````

**Comment by dragonstyle** [comment, marked as answer]
You should be able to specify an `image-height` for your listing, which will set the height for images and allow the width to scale automatically.

For example:

```yaml
---
title: "blog"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  image-height: 150px
page-layout: full
title-block-banner: true
---
```
