### DISCUSSION TITLE
RevealJS How to add format option for slides delineated with a horizontal rule

### DISCUSSION THREAD

**Discussion by harrylojames** [quarto-dev/quarto-cli#3422] [Q&A] [answered]
Hi, 

I am trying to make the second slide and not the first scrollable. I'm not sure where to add {.scrollable}. I have tried the following with no success.

```
## Slide 1 

abcd

---- {.scrollable}

abcd

```

https://quarto.org/docs/presentations/revealjs/#content-overflow

Let me know if you know how to do this :)

**Comment by fuhrmanator** [comment]
I noticed you used the `----` separator, but I don't think it's necessary. I can do:

```markdown
# {.scrollable}

blah blah

blah blah 
blah blah

blah blah 
blah blah

blah blah 
blah blah

blah blah 
blah blah

blah blah 
blah blah

blah blah 
blah blah

blah blah 
blah blah

blah blah 

```

However, on the latest Chrome and with Quarto 1.3.x (prerelease), this isn't giving me the result from the documentation. It is maybe a bug. Using Inspect in Chrome, I see a css definition of:

```css
.reveal .slide.scrollable {
    overflow-y: auto;
}
```

If I change it in Chrome to add (according to https://stackoverflow.com/a/30530246/1168342) a `max-height`:

```css
.reveal .slide.scrollable {
    overflow-y: auto;
    max-height: 100vh;
}
```
I get a good result.

A workaround (in my case) was to add the above CSS to a custom .css I specified in the `format: reveal: css:` metadata for the presentation.
