### DISCUSSION TITLE
Code-folding not rendering

### DISCUSSION THREAD

**Discussion by ctdarwell** [quarto-dev/quarto-cli#3426] [Q&A] [answered]
I have an opening block in my _.qmd_ doc trying to enable ```code-folding```

```
---
title: "Example"
format:
  html:
    embed-resources: true
    code-fold: true
---
```

Followed by some example code:

``` bash

for val in $vals
  do echo $val
  done
```

When I render this (in Rstudio) the code remains visible and unfolded.
