### DISCUSSION TITLE
qmd file not rendering for book page-footer

### DISCUSSION THREAD

**Discussion by lindsay-fredrick** [quarto-dev/quarto-cli#3441] [Q&A] [answered]
I have a section in my _quarto.yml file that contains:
```
book:
  page-footer:
    center: 
      - text: "License"
        href: license.qmd
```

Where license.qmd is a super simple qmd file. This matches the example [here.](https://quarto.org/docs/reference/projects/books.html#footer) However when I try to render or preview the entire book, this page does not render, and it displays the actual qmd file instead of a rendered html file. Any suggestions?
