### DISCUSSION TITLE
Is it possible to generate a listing of all files in a specific folder?

### DISCUSSION THREAD

**Discussion by jackflorey** [quarto-dev/quarto-cli#3472] [Q&A] [answered]
In a Quarto document, I'm trying to create a page containing a table of all files in a specific folder. I'm using the following frontmatter to generate the listing.

```
title: "Listing Example"
listing:
  type: table
  contents: "Assets/DisplayFiles/*"
  fields: [filename]
```
The folder `Assets/DisplayFiles/*` contains a number of pdf files and I want to show a table with their filenames which can be clicked to preview the pdf.

The snippet above generates the page, but no entries in the table. 

Can anyone shed any light on what I might be doing wrong and how to fix this? Thanks!
