### DISCUSSION TITLE
How to change default-image-extension for one specific figure?

### DISCUSSION THREAD

**Discussion by gdietl** [quarto-dev/quarto-cli#3524] [Q&A] [answered]
I'm working on a quarto book which I'd like to render as HTML and PDF. The automatically generated figures are either SVG or PDF files, depending on the output format. This is working fine.

However, there is a problem when including other images via the command
```
![](image)
```
As far as I understood, I need to work with "default-image-extension" in order to tell quarto to use different image formats for the different output formats as follows:
```
format:
  html:
    fig-format: svg
    default-image-extension: svg
  pdf:
    fig-format: pdf
    default-image-extension: pdf
```
Now, I would like to insert an animated gif where I have prepared a screenshot in PDF format for the PDF output format. So, when calling
```
![](image)
```
quarto should choose `image.gif` when producing the HTML output and `image.pdf` when generating the PDF output.

Is there a way of changing the default-image-extension for only one specific figure?
