### DISCUSSION TITLE
How to set a page as a frontpage/homepage?

### DISCUSSION THREAD

**Discussion by ning3739** [quarto-dev/quarto-cli#3530] [Q&A] [answered]
I just set up a personal website recently. everything looks fine, but every time when l load my webiste, it alwys jump to about page. This is not import things that what i want to show my audience. I just want to show my blog page when first time load. 
Dose anyone have same problem? How to fix it ? Thanks

Here is my _quarto.ymal:
```
---
project:
  type: website
website:
  cookie-consent: 
    type: express
    style: headline
    palette: dark
  google-analytics: 
    tracking-id: "G-Y96LK2RNJD"
    anonymize-ip: true
  title: "Stats & R"
  favicon: Stats-&-R.png
  page-navigation: true
  navbar:
    logo: Stats-&-R.png
    logo-alt: "Stats-&-R.png"
    logo-href: statsr.qmd
    left:
      - href: "Blog.qmd"
        text: "Blog"
      - href: who.qmd
        text: "About"
      - text: "Works"
        menu: 
          - Datavisualization.qmd
      - href: Contact.qmd
        text: "Contact"
    pinned: true
    search: true
    
format:
  html:
    code-fold: true
    code-summary: "show the code"
    code-overflow: scroll
    code-line-numbers: true
    toc: true
    toc-title: Contents
    toc-location: left
    html-math-method: katex
    theme:
       - superhero
       - superhero.scss
    highlight-style: arrow-light
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    comments:
      hypothesis:
        theme: clean
    css: styles.css
editor: visual
---
```
