### DISCUSSION TITLE
why my blog reading time is zero minute?

### DISCUSSION THREAD

**Discussion by ning3739** [quarto-dev/quarto-cli#3534] [Q&A] [answered]
How to fix this problem?
![Screenshot 2022-12-01 at 6 48 50 PM](https://user-images.githubusercontent.com/94179273/204975945-fc2049a5-bea3-4332-97a8-64534432809f.png)
Here is my blog listing. Thanks
```
---
listing:
  contents: posts/**/*.qmd
  sort: "date desc"
  type: grid
  categories: true
  sort-ui: true
  filter-ui: true
  fields: [image, date, title, author, description, categories, reading-time]
  feed: true
page-layout: full
title-block-banner: false
---
```
