### DISCUSSION TITLE
[book] Text of PARTS.qmd are missing in epub

### DISCUSSION THREAD

**Discussion by produnis** [quarto-dev/quarto-cli#3558] [Q&A] [answered]
Hi there,
my book follows this structure:

```
  chapters:
    - index.qmd
    - part: "R und RStudio"
      chapters:
        - installation.qmd
    - part: grundelgende-r-befehle.qmd
      chapters:
        - rechnen-mit-r.qmd
```

while everything works fine with PDF or HTML output,
all text in qmd-files of a "part" (e.g. part "`grundelgende-r-befehle.qmd`") are missing in output format "epub". 

Is there a way to render to epub with these `part.qmd`-files?
