### DISCUSSION TITLE
Remove Hyperlinks

### DISCUSSION THREAD

**Discussion by carbone1853** [quarto-dev/quarto-cli#3586] [Q&A] [answered]
I am writing a book using Quatro and want to output a PDF book with no hyperlinks. When I output an HTML book I want the references to be hyperlinked, but not in the PDF book. Is there a yml option to turn the hyperlinks on and off?

**Comment by rgaiacs** [comment, marked as answer]
Thanks for the question @carbone1853. If you are rendering the PDF using the quarto's default settings, you can (1) provide [custom options to Pandoc](https://bookdown.org/yihui/rmarkdown-cookbook/latex-variables.html) or (2) [custom formats](https://quarto.org/docs/extensions/formats.html) to change the hyperlink setting in the LaTeX template.

**Reply by carbone1853** [reply]
To turn off hyper references in a PDF doc made using Quatro add the option draft to hyperrefoptions. Below is an example of a yml file format section, where the hyper references are off.   

```
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    hyperrefoptions: draft
  epub:
    cover-image: cover.png
```

To turn the hyper references back on, remove the line with hyperrefoptions: draft.

```
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
```
