### DISCUSSION TITLE
Wordwrap in Code Blocks [PDF-Export]

### DISCUSSION THREAD

**Discussion by joelvonrotz** [quarto-dev/quarto-cli#3632] [Q&A] [answered]
Hello Everyone

I'm trying to write a two column summary for a programming course at college.
Code blocks are a bit finicky, as they don't wrap around when outside the code block:

![grafik](https://user-images.githubusercontent.com/41155337/207021596-216d3d30-6a0f-4985-bdc8-f2bcf5cb7a52.png)

Inside the doc, I've used the inline-Latex commands `` `\begin{multicols}{2}`{=latex}`` & `` `\end{multicols}`{=latex}`` to start and end the columns.

Did anybody else have this issue? And how can I fix this?

Following you can find my config.tex file and quarto YAML-config.

## config.tex

```latex
\usepackage{amssymb, amsmath}
\numberwithin{equation}{section}

\usepackage[utf8]{inputenc}
\usepackage{lastpage} % counts all the pages, used in footer

% Flexible Multicolumn Option
\usepackage{multicol}
\setlength\columnsep{20pt}

% Package for enabling colors (colorful output)
\usepackage[dvipsnames]{xcolor}
\definecolor{darkgreen}{HTML}{014f32}

% Icons - http://mirrors.ctan.org/fonts/fontawesome5/doc/fontawesome5.pdf
\usepackage{fontawesome5}


\usepackage[nodisplayskipstretch]{setspace}

% Font Configuration
\usepackage{lmodern}
\renewcommand{\familydefault}{\sfdefault}
\usepackage{cmbright}

% 
\usepackage{fancyhdr}

\pagestyle{fancy}
\fancyhead{} % clear all header fields
\makeatletter
\fancyhead[R]{\@title}
\makeatother
\fancyhead[L]{HSLU T\&A}
\fancyfoot{} % clear all footer fields
\fancyfoot[C]{\thepage\ / \pageref{LastPage}}
\fancyfoot[R]{APROG}
\fancyfoot[L]{\today}
```

## Quarto Doc YAML

```yaml
title: "Blablabla"
author: "BlaBlaBla"
date: "01.01.2022"

lang: de

# [RENDER CONFIGURATION] ==============================
format:
  pdf:
    include-in-header:
      - config.tex
    keep-tex: true

pdf-engine: pdflatex

# [DOCUMENT CONFIGURATION] ============================
geometry: 
- "top=25mm"
- "bottom=30mm"
- "left=15mm"
- "right=15mm"
papersize: a4paper
fontsize: 10pt

code-block-border-left: false
code-block-bg: "#f7f7f7"

toc: true
toc-depth: 3
number-sections: true
number-depth: 3
pagenumbering: none
highlight-style: github
```
