### DISCUSSION TITLE
Label the `file-modified` in listing grid cards to differentiate it from the date published

### DISCUSSION THREAD

**Discussion by cgoo4** [quarto-dev/quarto-cli#3633] [Feature Requests]
By adding this CSS my [listing page](https://www.quantumjitter.com/project/) differentiates the date modified from the date published.

`.card-file-modified:before {
    content: "Updated: ";
}`

Worth including in the base CSS?

Note, I also changed the `file-modified` label per below to "Updated" so that the `sort-ui:` then uses the same label. I thought that would also change the meta label in each of the projects, but they still say "MODIFIED". Not sure if that's a bug?

```
listing:
  fields: [image, date, title, reading-time, description, file-modified]
  field-display-names:
    file-modified: "Updated"
```
