### DISCUSSION TITLE
Input files from a different folder with absolute path

### DISCUSSION THREAD

**Discussion by mbarison** [quarto-dev/quarto-cli#3652] [Q&A] [answered]
Hi,

I am trying to write several reports in the book format with Quarto. My main issue is that the chapter files are located on a different drive.

For example, I want to include a file named `J:\PINO\Projects\PINO_POP
\2022-2023\6-Analysis\Output\Clusters\Markdown\AB_001_doc.md`

I have tried the following configurations:

```
book:
    - index.qmd
    - J:\PINO\Projects\PINO_POP\2022-2023\6-Analysis\Output\Clusters\Markdown\AB_001_doc.md
```

```
book:
    - index.qmd
    - "J:\\PINO\\Projects\\PINO_POP\\2022-2023\\6-Analysis\\Output\\Clusters\\Markdown\\AB_001_doc.md"
```

```
book:
    - index.qmd
    - /j/PINO/Projects/PINO_POP/2022-2023/6-Analysis/Output/Clusters/Markdown/AB_001_doc.md
```

```
format: 
  docx:
    resource-path: 
      - J:\PINO\Projects\PINO_POP\2022-2023\6-Analysis\Output\Clusters\Markdown

book:
  chapters:
    - index.qmd
    - AB_001_doc.md
```

None of these configurations work, I get an error message telling me that the file cannot be found.

Is it possible to define a default input folder in the project, on a different drive? If so, how?
