### DISCUSSION TITLE
Why are my sidebar and categories collapsed by default?

### DISCUSSION THREAD

**Discussion by bryanwhiting** [quarto-dev/quarto-cli#3689] [Q&A] [answered]
My sidebar and categories are collapsed by default, and I can't figure out how to un-collapse them. I don't know what I changed. I had turned on "reader-mode", which may have enabled this, but I've since disabled reader mode. (not sure that's the problem). I've tried "collapse: false" and that doesn't solve anything.

Categories open
<img width="464" alt="Screen Shot 2022-12-16 at 9 12 56 AM" src="https://user-images.githubusercontent.com/18710907/208152331-a0d327c6-8896-41a1-b8b2-17bbd8f55ac9.png">

Categories collapsed:
<img width="475" alt="Screen Shot 2022-12-16 at 9 12 48 AM" src="https://user-images.githubusercontent.com/18710907/208152334-1d9a1571-eed8-4d08-97c9-7f9249eb2ea1.png">

Sidebar collapsed:

<img width="272" alt="Screen Shot 2022-12-16 at 9 15 24 AM" src="https://user-images.githubusercontent.com/18710907/208152710-873f6c76-c1d7-4251-b266-f616937649ae.png">

Sidebar open:
<img width="263" alt="Screen Shot 2022-12-16 at 9 15 29 AM" src="https://user-images.githubusercontent.com/18710907/208152705-e1c93fdc-db8d-4287-ab3c-f847802a7225.png">

quarto.yml:
```
project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: true

website:
  title: "Bryan Whiting"
  site-url: https://www.bryanwhiting.com
  google-analytics: "UA-85616639-1"
  open-graph: true
  twitter-card:
    creator: "@bryanwhiting"
  page-footer:
    left: "Copyright 2022, Bryan Whiting"
    right:
      - icon: github
        href: https://github.com/bryanwhiting
      - icon: linkedin
        href: "https://www.linkedin.com/in/bryan-whiting/"
      - icon: twitter
        href: "https://twitter.com/bryanwhiting"
      - icon: rss
        href: index.xml
  search: true
  body-footer: |
    _________________________ <br> _Bryan is passionate about building great products with data and empowering individuals to reach their potential. Please reach out at <a href="mailto:bryanwhitingcoaching@gmail.com">bryanwhitingcoaching@gmail.com</a> to get mentorship or coaching for your life or business._
  sidebar:
    style: "docked"
    background: light
    subtitle: Data scientist | tech | father
    tools:
      - icon: github
        menu:
          - text: This blog
            url:  https://github.com/bryanwhiting/blog
          - text: Profile
            url: https://github.com/bryanwhiting
      - icon: linkedin
        href: "https://www.linkedin.com/in/bryan-whiting/"
      - icon: twitter
        href: "https://twitter.com/bryanwhiting"
      - icon: rss
        href: index.xml
    contents:
      - index.qmd
      - about.qmd

freeze: true

# https://quarto.org/docs/reference/formats/html.html
format:
  html:
    theme: cosmo
    css: styles.css
    comments:
      # hypothesis: true
      giscus: 
        repo: bryanwhiting/blog
    toc: true
    appendix-style: none
    toc-location: "left"
    smooth-scroll: true
    code-copy: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    citations-hover: true
    # mainfont: "Lato"
    # monofont: "Fira Mono"
    # fontsize: 1em
```

index.qmd:
```
---
title: "Recent Posts"
comments: false # https://quarto.org/docs/output-formats/html-basics.html#disabling-comments
page-layout: full
listing:
  contents: 
    - posts
    - book-reviews
  feed: true
  sort-ui: [date, title]
  filter-ui: [date, title, categories]
  type: "default"
  grid-columns: 4
  grid-item-border: true
  fields: [image, date, title, description, reading-time, categories]
  categories: cloud
  page-size: 5
  date-format: "ddd MMM D, YYYY"
language:
  listing-page-field-categories: "Topics"
toc: false
#toc-location: body
#title-block-banner: false
---

"All [blogs](https://en.wikipedia.org/wiki/All_models_are_wrong) are wrong, but some are useful."

```
