### DISCUSSION TITLE
quarto book with custom navbar: how do I keep the title in the sidebar?

### DISCUSSION THREAD

**Discussion by espinielli** [quarto-dev/quarto-cli#3727] [Q&A]
Hi,
I am trying to get a Quarto book with custom main navigation bar AND with the title present at the top of the sidebar when not at the first page.

The main page is ok, the title is visible...
![main_page](https://user-images.githubusercontent.com/891692/208949048-f1467996-6831-40a1-848d-231e33ed5654.png)

... but when I navigate further I would like to keep the title in the sidebar (see snapshot below), so as to provide contextual information that we are going through the book while we are still embedded in a general website as per main navigation bar.

![other_page](https://user-images.githubusercontent.com/891692/208949510-5c7cd3a0-91d0-41eb-b81a-eccf3b2e0104.png)

I have used the default Quarto book with the `_quarto.yml` below that introduces the main nav bar and options for the sidebar.

```yaml
project:
  type: book

book:
  title: "Book with alien navbar"
  author: "Jane Doe"
  date: "09/12/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  search:
    location: sidebar
  navbar:
    background: light
    search: false
    title: false
    left:
      - text: "Ciao"
        icon: "house-fill"
        href: "https://google.com"
    right:
      - text: "About"
  sidebar:
    title: "Book with alien navbar"
    search: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

```

Unfortunately it doesn't generqate what I would like :-(

Any helps?
