### DISCUSSION TITLE
Extension with multiple “pdf” (or any) based formats?

### DISCUSSION THREAD

**Discussion by mcanouil** [quarto-dev/quarto-cli#3733] [Q&A]
Currently, a Quarto extension can define multiple formats as long as they are different:

```yaml
contributes:
  format:
    html:
      # html-specifc
    pdf:
      # pdf-specifc
```

But, how to define twice (or more) "pdf" formats?
For example:

```yaml
contributes:
  format:
    pdf:
      # letter format
    pdf:
      # thesis format
```

---

I do not think it's possible with the current API,
It would need to explicitly define the format name instead of it being define by the base format and the name of the extension.

```yaml
contributes:
  format:
    letter-pdf:
      base-format: pdf
      # letter format
    thesis-pdf:
      base-format: pdf
      # thesis format
```

Where in a Quarto document it could be used as below:

```
format: thesis-pdf
```

Am I missing something?
