### DISCUSSION TITLE
Remove pagenumbers from the TOC? And adjust page numbering to the right page?

### DISCUSSION THREAD

**Discussion by KennethGottfredsen** [quarto-dev/quarto-cli#3791] [Q&A] [answered]
Hello guys, 

How do I exclude pagenumbers from the TOC. And how do I place the pagenumber on the bottom right side? Below is the YAML code:

```
title: "Vintereksamen - Dataanalyse"
subtitle: "Januar 2023"
date: last-modified
author: "Claus Grand Bang, Anna Hald Refsgaard og Bjarne Taulo Sørensen"
format: 
  pdf:
   toc: true
   toc-title: Indholdsfortegnelse
   toc-depth: 4
   number-sections: true
   number-depth: 3
   geometry:
      - top=30mm
      - left=20mm
      - right=20mm
      - bottom=30mm
      - heightrounded
header-includes:
- \usepackage[danish]{babel} # Alle overskrifter er på Dansk.
- \usepackage[none]{hyphenat} # Fjerner bindestregsord. 
fontsize: 14pt # Tekststørrelse. 
linestretch: 1.5 # 1.5 linjeafstand 
abstract: "Her kan I skrive et abstract, som ikke bør fylde mere end en halv side. Bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaa, blaaaa, blaaaa, blaaaa, blaaaa, blaaaa, blaaaa, blaaaa, blaaaa, blaaaa, blaaaa, blaaaa, blaaaa, blaaaa......"

```

Thanks in advance!

/ Kenneth.

**Comment by mcanouil** [comment, marked as answer]
I do not think you can using the default pdf template.
Note that you question is a LaTeX question more than a Quarto question.
I believe the answer can be found on the internet.
In the end, if you wish to customise a lot, I suggest you get acquainted with the extension API, see <https://quarto.org/docs/extensions/creating.html>.

**Comment by KennethGottfredsen** [comment]
Hello, 

I want to customise the formatting aspect a lot, so your answer is correct. I'll check it out. Thank you.

**Reply by mcanouil** [reply]
If you are happy with my suggestion, could you mark it as the answer to let others know the question has been answered?

**Comment by KennethGottfredsen** [comment]
Sure! Here you go.

**Comment by cutterkom** [comment]
Just in case somebody needs the solution... It's adding the latex command `\thispagestyle{empty}` and adding a hard pagebreak `\newpage`. 

Example `.qmd` file: 

```
---
title: "Toc page has no page number"
format:
  pdf:
    toc: true
---

\thispagestyle{empty}

\newpage

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:
```

**Reply by cutterkom** [reply]
@KennethGottfredsen Is this the specific solution to your problem?

**Reply by larnsce** [reply]
Thank you for sharing that solution @cutterkom. Do you maybe also have one for removing the page number 1 from the title page?

**Reply by mcanouil** [reply]
The trick is the same but you have to modify the template to include this command in the right place.
Take a look at the template and partials: https://quarto.org/docs/journals/templates.html#latex-partials

**Reply by larnsce** [reply]
I figured it out. The following starts the page numbering with 1 on the page starting with Introduction. `{{< pagebreak >}}` moves the Introduction to the page after toc, lof, and lot. 

Repo: https://github.com/larnsce/quarto-pdf


```
---
title: "Template"
date: today
format:
  pdf: 
    toc: true
    lof: true
    lot: true
    template-partials:
        - before-body.tex
    include-in-header: 
      text: '\pagenumbering{gobble}'
---

{{< pagebreak >}}

\pagenumbering{arabic}

# Introduction
```



The `before-body.tex` was added to move the toc, lof, and lot to to the second page. It contains:

```
$if(has-frontmatter)$
\frontmatter
$endif$

$if(title)$
\maketitle
$endif$

\newpage
```
