### DISCUSSION TITLE
Ipynb Format Output Kernel Choice?

### DISCUSSION THREAD

**Discussion by jlgraves-ubc** [quarto-dev/quarto-cli#3867] [Q&A] [answered]
Hi all,

Is there any way to specify the kernel for a `.qmd` document with output format `.ipynb` _without_ using the Jupyter engine?

Basically, I have a `.qmd` file which uses R cells, which I would like to use `knitr` to render to HTML and _also_ generate a version in `.ipynb` format which uses the `irkernel`.

I can get it to generate - but it always defaults the notebook to the python kernel instead of `ir`.  If it use the `jupyter` engine, the formatting is less clean than the output version, and I _must_ specify `keep-ipynb: true` which is not desirable.

**Comment by jlgraves-ubc** [comment, marked as answer]
The answer was pandoc:

``` yaml
format: 
  html: default
  ipynb:
    jupyter:
      kernelspec:
        display_name: R
        language: r
        name: ir
```

This renders normally using knitr, then creates a jupyter notebook with this spec; presumably this can also rejig other metadata in a notebook if you want to get fancier (https://pandoc.org/MANUAL.html#jupyter-notebooks)
