### DISCUSSION TITLE
Generate website as book pdf

### DISCUSSION THREAD

**Discussion by gdolle** [quarto-dev/quarto-cli#3869] [Q&A] [answered]
Hi all, 

- Is it possible somehow to generate a unique pdf, when the quarto project is a website ? 
(Currently, PDF seems to be generated per page.. )

- Or similarly, is it possible via the CLI to modify the type of project ? Something like `quarto render /path/to/proj --type book --to pdf`, 
`quarto render /path/to/proj --type website --to html`

G.

**Comment by dragonstyle** [comment, marked as answer]
Unfortunately a website can't be rendered as a book since the structure of the project file itself isn't compatible. We don't have tools to automatically convert a website project to a book project, so your best bet is to port your website project. If you'd like there is a command to generate book project scaffolding that you could use as a starter:

`quarto create project`

HTH and good luck!

**Reply by gdolle** [reply]
Currently I have a _quarto.yml that works quite well for both website and book,
the only thing I miss is a CLI to generate one or another from command line  (using CI tools) without editing the _quarto.yml file by hand:

```yaml
project:
  type: website  # <<<======
  
website:
  title: "My website"
  navbar:
     left:
        - href: file1.qmd
          text: menu1
        - href: file2.qmd
          text: menu2
        - href: webspecific.qmd
          text: blog

book:
  title: "My book"
  chapters:
     - href: file1.qmd
       text: chapter1
     - href: file2.qmd
       text: chapter2

format:
  html:
     theme: cosmo
  pdf:
     documentclass: book   # Other problem (not configurable per project type)
```

If I create a different project, I would have to duplicate the contents.. Or maybe have a way to choose the _playbook.yml to use.
