### DISCUSSION TITLE
New navbar for qmd files within a subfolder

### DISCUSSION THREAD

**Discussion by bsureshkrishna** [quarto-dev/quarto-cli#3886] [Q&A] [answered]
Hi,

Newbie question. I am building a lab website. For individual lab member webpages, I want to use a different navbar. So I have put the lab member pages into a subfolder, then added this to _metadata.yml as well as to labmember1.qmd - but it does not change the navbar at all.  Also since the metadata is merged with that in _quarto.yml, if I want to delete the navbar links defined there and only use the ones defined for the .qmd files in this subfolder, I dont see how I can do that. Thanks !

```
---
title: "Events"
description: |
  Events and News from the NASA-Openscapes Framework Project 
website:
  navbar:
    right:
    - text: "Another navbar option"
      href: xxx.qmd
---
```
