### DISCUSSION TITLE
How to use a custom variable from _quarto.yml in templates?

### DISCUSSION THREAD

**Discussion by ThierryO** [quarto-dev/quarto-cli#3918] [Q&A]
With version 1.1.189 we could add custom variables to the book settings in `_quarto.yml` and use them in the template. The example below provided `$book.reportnr$` in the template.

```
book:
  title: my title
  reportnr: 99999
```

After upgrading to version 1.2.313 this results in an error `property name reportnr is invalid`. How can we pass custom variables to a template in an extension?

**Comment by cscheid** [comment]
The `book` field has a schema, but other parts of the namespace do not. I believe, for example, that you should be able to use the top level. I do agree that we should do a better job of documenting this (and explicitly documenting, eg, a portion of the namespace that we promise to never have a schema)

**Reply by ThierryO** [reply]
Placing the custom variable in a different portion works. Downside is that some metadata (title, author) is in the `book` portion of the namespace, while the custom meta data is in a differrent portion.

```
book:
  title: my title
  author: me
  output-file: cool-report
  downloads: [pdf, epub]
  sharing: [twitter, linkedin, facebook]

myreport:
  reviewer: myself
  reportnr: 9999
```

Would I run into problems when moving some metadata from the `book` portion to the `myreport` portion? Replacing `$book.title$` with `$myreport.title$` in the template is obviously not a problem.

```
book:
  output-file: cool-report
  downloads: [pdf, epub]
  sharing: [twitter, linkedin, facebook]

myreport:
  title: my title
  author: me
  reviewer: myself
  reportnr: 9999
```
