### DISCUSSION TITLE
Repeated yaml values

### DISCUSSION THREAD

**Discussion by ghost** [quarto-dev/quarto-cli#3920] [Q&A]
.

**Comment by mcanouil** [comment]
It would be easier to name your Quardo document `something-great.qmd` and let Quarto do the work with a more simpler yaml.

```yaml
format:
  revealjs: default
  pdf: default
  latex: default
```

The output files will be created from the Quarto document name and the extension of the file will be the appropriate one based on the format.
