### DISCUSSION TITLE
Add whitespace between figures and paragraph text in html

### DISCUSSION THREAD

**Discussion by ericpgreen** [quarto-dev/quarto-cli#3925] [Q&A] [answered]
Could someone help me with the CSS to add vertical whitespace between figures and text? I'm not sure it matters, but this would need to apply to figures created by code blocks as well as figures inserted via pathways to files.

<img width="904" alt="Screen Shot 2023-01-10 at 4 34 42 PM" src="https://user-images.githubusercontent.com/546433/211667503-c8977e51-6767-4b11-8e28-cc3360849bc2.png">

**Comment by mcanouil** [comment, marked as answer]
There are many many ways to do what you want, below is one on a per code cell basis:

````
---
format: html
include-in-header: 
  - text: |
      <style>.plot-padding { padding: 3em 0 3em 0; }</style
---

Some text

```{r}
#| label: fig-one
#| fig-cap: Caption
#| echo: false
#| classes: plot-padding
plot(1)
```

Some text
````


Another for all "figures" (the ones with labels and captions) in a document:

````
---
format: html
include-in-header: 
  - text: |
      <style>figure { padding: 3em 0 3em 0; }</style
---

Some text

```{r}
#| label: fig-one
#| fig-cap: Caption
#| echo: false
plot(1)
```

Some text
````

**Reply by ericpgreen** [reply]
Thanks @mcanouil. I did not mention that my project type is book. I tried inserting your suggestions as follows, but I get the error "TypeError: Cannot read properties of undefined (reading 'endsWith')". I don't think I'm implementing this as you intended.

```
format:
  html:
    theme: cosmo
    css: styles.css
    linkcolor: "#1f9ac9"
    include-in-header:
      - text: |
        <style>.plot-padding { padding: 3em 0 3em 0; }</style
        <style>figure { padding: 3em 0 3em 0; }</style
```

**Reply by mcanouil** [reply]
`include-*` options are top-level ones.
Also you are missing indentation for the two lines starting with "<style>" (this is the source of the error).

It should work at the right level.
This being said, since you use a css style file, you can put the content in it.

```css
.plot-padding {
  padding: 3em 0 3em 0;
}
```

or

```css
figure {
  padding: 3em 0 3em 0;
}
```

or if for some reasons you want both

```css
.plot-padding, figure {
  padding: 3em 0 3em 0;
}
```
