### DISCUSSION TITLE
Problemas with date formatting in quarto document

### DISCUSSION THREAD

**Discussion by ManuelSpinola** [quarto-dev/quarto-cli#3946] [Q&A]
If I include the following date in the yaml of a quarto document:

date: 13/01/2023
date-format: "DD/MM/YYYY"

The date in the rendered document is:

FECHA DE PUBLICACIÓN
01/01/2024

And in the citation:

Manuel Spínola. 2024. “crgeo un paquete de R con datos geoespaciales de Costa Rica.” January 1, 2024. https://mspinola-ciencia-de-datos.netlify.app/posts/2023-01-09-crgeo/crgeo.html.

**Comment by cscheid** [comment]
Can you please share a full example?

**Comment by ManuelSpinola** [comment]
````
---
title: "crgeo un paquete de R con datos geoespaciales de Costa Rica"
subtitle: Datos geoespaciales de Costa Rica
image: "imagenes/crgeo_c.png"
author:
  - name: Manuel Spínola
    url: http://www.icomvis.una.ac.cr/index.php/manuel
    affiliation: ICOMVIS - UNA
    affiliation-url: http://www.icomvis.una.ac.cr/
    orcid: 0000-0002-7839-1908
date: 13/01/2023
date-format: "DD/MM/YYYY"
citation: true
toc: true
toc-title: Tabla de contenido
toc-location: left
toc-depth: 4
bibliography: references.bib
lang: es
draft: false
execute: 
  echo: false
  include: false
categories:
  - "Análisis y Visualización de Datos"
---
````
