### DISCUSSION TITLE
Contentful sections in sidebar?

### DISCUSSION THREAD

**Discussion by johnkerl** [quarto-dev/quarto-cli#395] [Q&A] [answered]
Hello -- Using GitBook we have some content where the section labels have pages associated with them.

For example, in the screenshot here of `quarto.org`, imagine that I could click on `Authoring` and there would be page content associated with it (as is, it only toggles open/closed the listing of the section-contents pages):

<img width="1273" alt="Screen Shot 2022-03-07 at 5 35 30 PM" src="https://user-images.githubusercontent.com/2008794/157130052-dc8eb64b-5095-4c8b-8427-8d4339420567.png">

Is this possible in Quarto?

**Comment by dragonstyle** [comment, marked as answer]
Yes it is - if you provide an `href` for the section, it will link to a page as well as expand the tree...

Give something like this a try:

```yaml
- section: "Basics"
  href: section.qmd
  contents:
    - index.qmd
    - basics-knitr.qmd
```
