### DISCUSSION TITLE
Is it possible to suppress the navbar for a single page?

### DISCUSSION THREAD

**Discussion by yoctobug** [quarto-dev/quarto-cli#3951] [Q&A] [answered]
Using Quarto for website. I'd like to be able to suppress the navbar (and sidebar) navigation on a single page. I've tried adding values to YAML for that page, e.g., navbar: false, etc. but nothing seems to work. 

```
---
format:
  html:
    minimal: true
    embed-resources: true
    standalone: true
    theme: flatly
    toc: false
---

Page content here.
```

Is there a way to suppress or hide the navbar for a single page?
