### DISCUSSION TITLE
External Links in Quarto Front Matter

### DISCUSSION THREAD

**Discussion by LarryVincent** [quarto-dev/quarto-cli#3969] [Q&A]
I am trying to DRY up my code. I use the same custom stylesheet and header include on every Quarto presentation. I'd like to store them in the cloud and reference in my front matter. But every attempt has failed. For my theme, I tried:

`theme: [default, "https://link.to.my.custom.scss"]`

That didn't work. Same for this code:

`include-in-header:
   file: "https://link.to.my.cloud.insert.file"`

How might I accomplish this? I hate how fat my GitHub repository is becoming with the same files.

**Comment by mcanouil** [comment]
You can't, what you have to do is regular html linking:

```yaml
include-in-header:
  - text: |
      <link rel="stylesheet" href="style.css" type="text/css">
```
