### DISCUSSION TITLE
New title block (front-page) items via title-block.html (?)

### DISCUSSION THREAD

**Discussion by artahy** [quarto-dev/quarto-cli#3974] [Q&A] [answered]
Hello there,

This is related to some previous discussions (#3725, #3162), but let me ask a clarifying question (and apologies if there is a known trivial solution to this that have ignored, I am a newcomer to Quarto):

I'm using Jupyter Lab (and Python), and then Quarto when producing a (very simple) webpage. In particular, I am trying to customise the title block to add new items, such as an affiliation, on the front page (in addition to "Author") when rendering Quarto output to html.

I have followed the advice to use the partial [title-block.html ](https://github.com/quarto-dev/quarto-cli/blob/56888bb94984fd93f16edb42dbe5564c6dc65eaa/src/resources/formats/html/pandoc/title-block.html), but for some reason, it seems not to alter the front-matter. It is as if Quarto did not recognise that it should use title-block.htlm-file when rendering my ipynb-file.  

I have included the following in the YAML:

```
format: 
  html:
    template-partials:
      - title-block.htlm 
```    

and I am using the example for title-block.html from #3162, provided by @[dragonstyle](https://github.com/dragonstyle) to include author affiliations (which I also have in the YAML). 

What should I do to implement the desired change? 

All kinds of suggestions would be most welcome.

**Comment by cderv** [comment, marked as answer]
> I have followed the advice to use the partial [title-block.html ](https://github.com/quarto-dev/quarto-cli/blob/56888bb94984fd93f16edb42dbe5564c6dc65eaa/src/resources/formats/html/pandoc/title-block.html), but for some reason, it seems not to alter the front-matter.

Can you a reproducible example (as a Github repo maybe ? or a zip bundle ?) ? I tried to reproduce with a simple example and when modifying title block, it correctly get taken into account.  Which title block exactly are you using ? There are several shared in #3162 thread. 

Thank you

**Reply by artahy** [reply]
Hi,

Thank you for your reply.  

The following are the contents of my YAML in my Jupyter Notebook, and the title-block.html I am using:

My YAML:
```

---
title: MyTitle
subtitle: MySubTitle
jupyter: python3
author:
  - name: My Name
    email: my.email@email.com
    affiliations: 
        - name: My University
          department: My Department 
          city: My City
          state: My Country
          postal-code: 12345
    acknowledgements: My acknowledgements. It'd be great if others can see it. 
abstract: |
  This will be a great abstract. 
date: last-modified
format: 
  html:
    template-partials:
      - title-block.htlm     
---
```

My title-block.html

```
<header id="title-block-header">
<h1 class="title">$title$</h1>
$if(subtitle)$
<p class="subtitle">$subtitle$</p>
$endif$

$for(by-author)$
<p class="author">$by-author.name.literal$</p>
$if(by-author.email)$
<a class="author_email" href="mailto:#">$by-author.email$</a>
$endif$

$for(by-author.affiliations)$
<p class="affiliation">
  $if(it.url)$
    <a href="$it.url$">
  $endif$ 
  $it.name$
  $if(it.url)$
     </a>
  $endif$
</p>
$endfor$

$endfor$

$if(date)$
<p class="date">$date$</p>
$endif$

$if(acknowledgements)$
<p class="acknowledgements">$acknowledgements$</p>
$endif$

$if(abstract)$
<div class="abstract">
<div class="abstract-title">$abstract-title$</div>
$abstract$
</div>
$endif$

</header>

``` 
I also attach a zip-file, containing the notebook and the title-block. 

[Example.zip](https://github.com/quarto-dev/quarto-cli/files/10426715/Example.zip)

**Reply by artahy** [reply]
A brief follow-up (sorry for not being explicit on this): 

What I am trying to do here is to  be able to display the _acknowledgements_ as a new item on the front page. 

Thanks,

**Reply by cderv** [reply]
In your YAML you have put the `acknowledgment` field at the same level of `author`
````yaml
author:
  - name: My Name
    email: my.email@email.com
    affiliations: 
        - name: My University
          department: My Department 
          city: My City
          state: My Country
          postal-code: 12345
    acknowledgements: My acknowledgements. It'd be great if others can see it. 
abstract: |
  This will be a great abstract. 
````

but then you are calling in template as a main variable 
````html
$if(acknowledgements)$
<p class="acknowledgements">$acknowledgements$</p>
$endif$
````

So you need to either 
* put the field at first level in your YAML
	````yaml
	author:
	  - name: My Name
	    email: my.email@email.com
	    affiliations: 
	        - name: My University
	          department: My Department 
	          city: My City
	          state: My Country
	          postal-code: 12345
	acknowledgements: My acknowledgements. It'd be great if others can see it. 
	abstract: |
	  This will be a great abstract.
	````
* Call the value  by author in your template. 

Either way it should work.
