### DISCUSSION TITLE
Why is a home page (i.e., index.qmd) required for PDF books?

### DISCUSSION THREAD

**Discussion by mattwarkentin** [quarto-dev/quarto-cli#4024] [Q&A]
Hi,

Without getting too much into the weeds of my specific use case, I previously wrote an R package to provide an R Markdown format conforming to my university's thesis format. I am now trying to port this over to Quarto. This has mostly gone smoothly.

The issue I'm running into is that I apparently HAVE to have an `index.qmd` home page. My `_quarto.yml` currently looks like:
```yml
project:
  type: thesis

book:
  output-file: Last_First_MiddleInitial_Year_PhD_thesis
  title: "An Amazing Thesis Title"
  chapters:
    - index.qmd
    - chapters/01-Introduction.qmd
    - chapters/02-Background.qmd
    - chapters/03-Methods.qmd
    - chapters/04-Results.qmd
    - chapters/05-Discussion.qmd
    - chapters/references.qmd
    - chapters/appendix.qmd

bibliography: references.bib
```

The `index.qmd` file is entirely empty, but still shows up in the rendered PDF as a new chapter. If I remove `index.qmd` from the `chapers`, the build fails with the following error:
```
ERROR: Book contents must include a home page (e.g. index.md)
```

What am I missing here? I am being forced to include this file, but the inclusion adds a blank chapter to my final document. What can I do?

I could, of course, copy the contents of the actual first chapter (`01-Introduction.qmd`) into `index.qmd`, but I feel like this is kind of hacky - I want to be able to name my chapters as shown above.
