### DISCUSSION TITLE
Alternative icon packs?

### DISCUSSION THREAD

**Discussion by nurfatimaj** [quarto-dev/quarto-cli#409] [Q&A] [answered]
Is it possible to use other icon packs, such as [Academicons](https://jpswalsh.github.io/academicons/)?

**Comment by juliantao** [comment]
As a workaround, you can include the following in the yaml header:

```yaml
header-includes:  |
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
```

Or save the stylesheet line to a `html` file (e.g, academicons.html) and use

```yaml
include-in-header: 
  - path/to/academicons.html
```

**Reply by nurfatimaj** [reply]
Would I be able to use the icons using the icon option in YAML like so

```yaml

links:
    - icon: google-scholar
      text: Google Scholar
      href: some link
```

or I'd need to insert the icons manually using 

`<i class="ai ai-google-scholar-square ai-3x"></i>`?

**Reply by juliantao** [reply]
I think the first option will not work.

You may need to inert the icons manually. I know you can certainly do it in the main text of a `qmd` file, but am not sure whether you can do it in the YAML file.

**Reply by nurfatimaj** [reply]
Thanks!

I managed to insert it like this:

```yaml
links: 
    - text: <i class="ai ai-google-scholar"></i> Google Scholar
      href: some link
```

But, I think it'd be nice to be able to use the `icon` option. Is that something that will be added later?
