### DISCUSSION TITLE
$author.name$ not available in reveal.js template?

### DISCUSSION THREAD

**Discussion by ThierryO** [quarto-dev/quarto-cli#4180] [Q&A] [answered]
I'm trying to define a partial template for reveal.js. I defined the authors in the yaml header as below. For some reason `$author.name$`, `$author.firstname$` and `$author.orcid$` are empty. `$author$` contains the value which should be in `author.name`. I use this technique without problems in a quarto book project with html output.

```
author: 
  - firstname: Thierry
    name: Onkelinx
    orcid: 0000-0001-8804-4216
```

```
$for(author)$
  <p class="author">$author.name$, $author.firstname$ $author.orcid$</p>
$endfor$
```
