### DISCUSSION TITLE
Hide slide menu button when printing slides

### DISCUSSION THREAD

**Discussion by sagikazarmark** [quarto-dev/quarto-cli#4181] [Feature Requests]
I often use [decktape](https://github.com/astefanutti/decktape) to print slides that apparently does not use the `?print-pdf` query parameter and as a result the slide menu button remains visible in the PDF.

This can easily be verified by turning on the print media simulation from the inspector: the button remains visible.

Suggested change: hide the slide menu button when print media is enabled.

The following snippet does exactly that:

```css
    @media print {
        html:not(.print-pdf) .reveal .slide-menu-button {
            display: none !important;
        }
    }

```
