### DISCUSSION TITLE
Sidebar hierarchy: an item as sub content of a section content item

### DISCUSSION THREAD

**Discussion by aborruso** [quarto-dev/quarto-cli#4235] [Q&A] [answered]
Hi,
I have this kind of structure

```yaml
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: intro.qmd
        text: Intro
      - section: Sources
        contents:
          - href: one.qmd
            text: One
          - href: two.qmd
            text: Two
```

I would like to add an item one level below the "One" item. How to do it?

It's not

```yaml
        contents:
          - href: one.qmd
            text: One
            - href: sub-one.qmd
```

Do I must add a new sub contents section?

Thank you

**Comment by dragonstyle** [comment, marked as answer]
You just need to add additional sections to the contents of an item (they can nest) - for example:

```
website:
  title: "Site"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Intro
      - section: Sources
        contents:
          - href: about.qmd
            text: One
          - section: Foobar
            href: section.qmd
            contents:
              - href: section-item.qmd
```

HTH!

**Reply by aborruso** [reply]
thank you @dragonstyle , I have added it https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/main/_quarto.yml#L31-L33

But clicking on the `>` to expand it, nothing happens (the [website](https://ondata.github.io/italian-public-sector-pnrr-data-guide/)).
To explode the submenu I must click on text title. Is it normal?


![image](https://user-images.githubusercontent.com/30607/217205503-b289a4e8-6f11-4c26-823b-b741e11611a4.png)

**Reply by dragonstyle** [reply]
That looks like a bug which is fixed in Quarto 1.3 (I just tested this same scenario using the quarto.org website, which is generated using the latest pre-release and the toggles are properly interactive)...

**Reply by aborruso** [reply]
thank you @dragonstyle 

Is there a way to change the standard [quarto action](https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/main/.github/workflows/publish.yml#L18) and force a specific release?

Thank you

**Reply by aborruso** [reply]
> Is there a way to change the standard [quarto action](https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/main/.github/workflows/publish.yml#L18) and force a specific release?

Yes, there is

https://github.com/quarto-dev/quarto-actions/tree/main/setup#inputs-available

**Reply by aborruso** [reply]
> That looks like a bug which is fixed in Quarto 1.3 (I just tested this same scenario using the quarto.org website, which is generated using the latest pre-release and the toggles are properly interactive)...

@dragonstyle  I have forced the 1.3.179 version, setting it in [my action](https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/main/.github/workflows/publish.yml#L20), but I have the same result?

What am I doing wrong?

Thank you

**Reply by aborruso** [reply]
> That looks like a bug which is fixed in Quarto 1.3 (I just tested this same scenario using the quarto.org website, which is generated using the latest pre-release and the toggles are properly interactive)...

Hi @dragonstyle do you know why it doesn't work for me? I have updated all to 1.3.189 and it's in the same way. Thank you

**Reply by dragonstyle** [reply]
The is with the way the sidebar is defined in your `_quarto.yml` - the items in the tree that aren't interactive aren't marked as 'sections', so they aren't showing their child contents. I believe this should fix it:

```yml
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: introduzione.qmd
        text: Introduzione
      - section: Fonti
        contents:
          - section: OpenCUP                        # << Note that this is `section` rather than `text`
            href: fonti/opencup/index.qmd
            contents:
              - href: fonti/opencup/focus-pnrr.qmd
                text: Focus PNRR
          - section: ANAC                           # << Note that this is `section` rather than `text`
            href: fonti/anac/index.qmd
            contents:
              - href: fonti/anac/informazioni-cig.qmd
                text: Estrarre i dati ANAC
          - section: Servizio Contratti Pubblici    # << Note that this is `section` rather than `text`
            href: fonti/scp/index.qmd
            contents:
              - href: fonti/scp/informazioni-scp.qmd
                text: Estrarre i dati SCP
          - href: fonti/openbdap/index.qmd
            text: OpenBDAP
      - href: guide/procedura-esempio.qmd
        text: Esempio estrazione dati
      - text: "---"
      - href: datibenecomune.md
        text: datiBeneComune
      - href: osservatorio.md
        text: Osservatorio PNRR
      - href: openpnrr.md
        text: Open PNRR
      - href: quinto-piano-governo-aperto.md
        text: V Piano Nazionale Governo Aperto
```
