### DISCUSSION TITLE
Interactivity of rendered HTML page not working on mobile browsers

### DISCUSSION THREAD

**Discussion by thegilpatrick** [quarto-dev/quarto-cli#4243] [Q&A] [answered]
I rendered an HTML page and uploaded it on GitHub pages. Here is the [link to the webpage](https://thegilpatrick.com/blog/tidyTuesday/2023-01-31/Pet_Cats_UK.html).

The page loads fine, but none of the interactivity works on mobile (Safari or Chrome) (except for the show code button). I have some hyperlinks in markdown and you cannot click on them. I have some OJS inputs that don't work on mobile, but everything is working fine in multiple browsers (Chrome, Edge, Firefox) on desktop. I assumed at first that it was a Safari problem, but it seems to be something specific to mobile. But some of these same rendered HTML pages used to work fine on mobile before when I used a previous version of Quarto with the the `self-contained` option. I updated Quarto and now use the `embed-resources` YAML option.

Below is my YAML for the HTML page I linked. I am using Quarto version 1.2.313. I rendered this in VSCode with the extension. I have a Windows 10 Pro Operating System.

```
---
title: UK Pet Cats 
subtitle: Tidy Tuesday Week 5
date: 1/31/2023
format:
  html:
    code-fold: true
    toc: true
    toc-location: left
    embed-resources: true
    code-tools: true
    include-before-body: header.html
---
```
