### DISCUSSION TITLE
How do i make my quarto document save the figures generated in the R chunks to a folder?

### DISCUSSION THREAD

**Discussion by ejjunju** [quarto-dev/quarto-cli#4254] [Q&A]
How do i make my quarto document save the figures generated in the chunks to a folder?

Blow  is my current yaml for a book project but it is not working. I also need a solution for a simle quarto document.

````
project:
  type: book
  output-dir: Result

book:
  title: "xxxx"
  subtitle: "xxk"
  author: xx
  date: "2023.01.11"
  search: true
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_xx.qmd
    - 03_xxx.qmd
    - 04_xxxr.qmd
    - 05_xxx.qmd
    - 06_xxx.qmd
    - references.qmd
  #appendices:
  #  - appendix.qmd

bibliography: references.bib
biblio-style: apalike

format:
  html:
    theme: cosmo
    cover-image: figures/cover.png
    toc: true
    html-math-method: katex
    fig-format: png
    embed-resources: false
    keep-md: true
  epub:
    cover-image: figures/cover.png
    fig-format: png
  pdf:
    documentclass: scrreprt
    cover-image: figures/cover.png
    fig-format: png
    toc: true
    number-sections: true
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
        \usepackage{graphicx}
        \usepackage{float}
    include-after-body:
      text: |
        \printindex
  docx:
    toc: true
    number-sections: false
    highlight-style: github
    reference-doc: NVE_mal.docx
    cover-image: figures/cover.png
    prefer-html: true

editor: visual
lang: no
#https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language.yml
language:
  title-block-author-single: "Writer"
  title-block-published: "Updated"
  crossref-fig-title: "Figur"
  crossref-tbl-title: "Tabell"
  toc-title-document: "Innhold"
  crossref-sec-prefix: "kap"
  crossref-ch-prefix: "Kap"
  crossref-apx-prefix: "Vedlegg"
  crossref-eq-prefix: "Likning"
  section-title-appendices: "Vedlegg"
  section-title-apx: "Vedlegg"
  section-title-references: "Referanser"
colorlinks: true #https://www.njtierney.com/post/2022/04/11/rmd-to-qmd/
link-citations: yes
fontsize: 12pt
crossref:
  chapters: true
# https://quarto.org/docs/reference/formats/pdf.html
# monofont: "Source Code Pro"
# monofontoptions: "Scale=0.7"
# header-includes:
#   - \usepackage{graphicx}
#   - \usepackage{float}
cover-image: ""
```
#https://quarto.org/docs/books/book-output.html
`

**Comment by dragonstyle** [comment]
Can you say a little more about what you're expecting? Figures should be placed into a folder associated with the document (e.g. an `_files` directory)...

**Reply by ejjunju** [reply]
i want when the document is rednrerd that a copy of all figures in the different chucks is saved on a folder in the working directory.

**Reply by cderv** [reply]
They should be already saved to a folder as you use `embed-resources: false`. can you find them ? Is the question how to move them to another folder ? 

I am trying to clarify the question  here. Knowing more about the use case and workflow will help us give you a correct answer

**Comment by mcanouil** [comment]
You can use `knitr` `fig.path` option to define path/prefix of images in your YAML header.

```yaml
knitr:
  opts_chunk:
    fig.path: directory/to/store/figures/prefix-
```

If you don't want a prefix for your files, be sure to end the `fig.path` with a `/`.

```yaml
knitr:
  opts_chunk:
    fig.path: directory/to/store/figures/
```

**Reply by mcanouil** [reply]
In addition, you could define a new function in `fig.process`

Using the "legacy" `knitr`/`rmarkdown` syntax, you can make a copy:

```r
knitr::opts_chunk$set(
  fig.process = function(path) {
    file.copy(path, file.path(".", basename(path)), overwrite = TRUE)
    path
  }
)
```

**Comment by ejjunju** [comment]
Thanks, let me try. I have tried your earlier solution and like like you said  

```
knitr:
  opts_chunk:
    fig.path: directory/to/store/figures/prefix-
```
has worked for for the simplest of R plots and a simple qmd file after my test. It doesnt seem to work though with saving mapview/leaflet figures and DiagrammeR objects.

**Reply by mcanouil** [reply]
Interactive figures are not actual figures.
For those, you need to use explicit method to save them, likely as html fragment/widget.
These are not controlled by `fig.` or `fig-` options.

For example, the first result of a web search with "save leaflet": <https://stackoverflow.com/questions/31336898/how-to-save-leaflet-in-r-map-as-png-or-jpg-file>.

**Reply by ejjunju** [reply]
Thanks :)

**Reply by cderv** [reply]
Within **knitr**, for non HTML output, when R 📦  **webshot** or **webshot2** is available, there should be a screenshot placed in the figure folder. Snapshot can be forced in HTML output too, by adding `screenshot.force` on the chunk or globally. 

No need to pass by an external method I believe when you need a png. 

In HTML output default behavior will be no image but HTML obviously, so nothing in fig folder indeed

**Reply by ejjunju** [reply]
is this how yoo do it?
```
{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '', 
  fig.width = 6, 
  fig.height = 6,
  screenshot.force =TRUE
)
```

**Reply by mcanouil** [reply]
In Quarto, it would be the following in the YAML header:

```yaml
knitr:
  opts_chunk:
    comment: '' 
    fig.width: 6 
    fig.height: 6
    screenshot.force: true
```

Note that the following is the `knitr`/`rmarkdown` syntax which should work also in Quarto

````rmd
```{r}
knitr::opts_chunk$set(
  comment = '', 
  fig.width = 6, 
  fig.height = 6,
  screenshot.force = TRUE
)
```
````
