### DISCUSSION TITLE
Ignored render targets behave differently depending on method of ignore

### DISCUSSION THREAD

**Discussion by andrewpbray** [quarto-dev/quarto-cli#4331] [Q&A] [answered]
I've observed some surprising behavior on a website that I have and I'm curious whether this is the intended behavior or not.

Here's a simplification of the website that I'm working with.

```
/my_website
├── _quarto.yml
├── index.qmd
├── unit-1
│   └── post.qmd
│   └── other-files.qmd
├── unit-2
│   └── post.qmd
│   └── other-files.qmd
```

The `index.qmd` has a listing on it structured as

```
---
listing:
  contents:
      - "*/post.qmd"
---
```

My goal is to only render the material in the `unit-1` directory. Two approaches that I've tried.

1. Exclude `unit-2` by specifying render targets.
2. Change `unit-2/` to `_unit-2`.

Approach 1 involves changing `_quarto.yml` to read:

```
project:
  website:
    render:
      - "*.qmd"
      - "!unit-2/"
```
The result is that none of the .qmd in `unit-2/` are rendered, however, `index.qmd` throws this warning:
```
WARNING: File /unit-2/post.qmd in the listing 'listing' contains no metadata.
```
When I view the webpage, there is a blank listing field for the second post, reflecting that lack of metadata.

Approach 2 also prevents the rendering of anything in `unit-2/`, however there is no warning about the listing and it shows up as preferred, without the blank spot for the second post.

My guess is that this is a similar issue to the one that came up in #3879 . The order of operations on `quarto render` seems to be.

1. Build up the listing files (which ignores files that start with `_`)
2. Run pre-render scripts
3. Run `quarto render` on all of the qmd files controlled by `_quarto.yml`.
4. Run post-render scripts

Is this correct? If so, is it intentional that 1. doesn't consult `_quarto.yml` for ignored files?

Thanks for your help!

**Comment by mcanouil** [comment]
Did you know you can ignore files by setting a `.quartoignore` file?

I believe the negative glob is not really working as it should or not handled expectedly by Quarto when rendering the website, _i.e._, likely a bug to me.

**Reply by cderv** [reply]
> I believe the negative glob is not really working as it should or not handled expectedly by Quarto when rendering the website, i.e., likely a bug to me.

Not implemented yet - follow https://github.com/quarto-dev/quarto-cli/issues/4061

**Reply by mcanouil** [reply]
In '.quartoignore' but according to the documentation for `render` YAML key it should be already implemented.

**Comment by dragonstyle** [comment, marked as answer]
I don't believe that the `render` key is valid under the `website` key. I believe it belongs here:

```
project:
  type: website
  render:
    - "*.qmd"
    - "!welcome/*.qmd"

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
```

The above example works with our default blog to exclude the `welcome` post from being rendered, which appears to in turn not allow it to appear in a listing. I've attached a zip of that sample project so you can compare to see if there are differences that may explain this.

[blog.zip](https://github.com/quarto-dev/quarto-cli/files/10722987/blog.zip)

Depending upon your goal, you might also consider using the `draft: true` front matter of the document that you'd like to exclude from the list. This will keep it in the render list (and deploy / publish list), but exclude it from listings and search, so it would only be visible to someone who knows the URL (basically the equivalent of being 'unlisted').
