### DISCUSSION TITLE
Shortcode seems to break dark theme CSS

### DISCUSSION THREAD

**Discussion by jmgirard** [quarto-dev/quarto-cli#4341] [Q&A] [answered]
I am trying to help a user of my extension to figure out why using my shortcode breaks dark theme styling.
See the original issue here: https://github.com/jmgirard/lordicon/issues/2

## Steps to recreate the problem:

1) Create a new project in RStudio > quarto book

2) Replace `_quarto.yml` with the following:

```yml
project:
  type: book

book:
  title: "reprex_quartobook"
  author: "Jane Doe"
  date: "8.2.2023"
  chapters:
    - index.qmd
    - intro.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
```

3) Install my lordicon extension via terminal:
```
quarto install extension jmgirard/lordicon
```

4) Render the `index.qmd` file and try the dark mode slider. It works and looks like this:

![image](https://user-images.githubusercontent.com/6829033/218572285-d0a642f0-6c9a-4220-9d52-e8470313d8cf.png)

5) Now add a shortcode from my extension to `index.qmd` and re-render.

```
{{< li lupuorrc >}}
```

Note how the icon appears but some of the CSS styles are not applied correctly:

![image](https://user-images.githubusercontent.com/6829033/218573045-85977ca4-6a68-42f0-887e-0a3637eb0367.png)
