### DISCUSSION TITLE
Custom title for RSS feed not working?

### DISCUSSION THREAD

**Discussion by fortunewalla** [quarto-dev/quarto-cli#4417] [Q&A] [answered]
Hi, I have set up a quarto blog and have entered the metadata for the index.qmd page as follows:

```yaml
---
listing:
  contents: posts
  sort: "date desc"
  type: table
  categories: true
  sort-ui: true
  filter-ui: true
  feed: true
title: "RSS Title from index.qmd"
description: "RSS Descripton from index.qmd"
page-layout: full
title-block-banner: false
---
```
I'm trying to follow the instructions in the documentation. It states that we can specify the Custom title of the RSS feed through `title:` under `feed:` else it will take the Default title from _quarto.yml.

![image](https://user-images.githubusercontent.com/7158596/219844726-2cc5406d-f8d4-467c-842e-52a1eed26a69.png)

I've tried every combination possible but I cannot seem to set a custom title for the RSS Feed.

### As seen below The RSS Feed title is extracted from the _quarto.yml file Default Title.

![image](https://user-images.githubusercontent.com/7158596/219845247-1c8fa838-42f0-4112-a51e-59537ec0d16a.png)

What am I doing incorrectly? 🤔
