### DISCUSSION TITLE
ERROR: No inspectable targets with mermaid graphics

### DISCUSSION THREAD

**Discussion by tomkom** [quarto-dev/quarto-cli#4441] [Q&A]
am trying to render to PDF with some mermaid graphics. I think this triggers Quarto to return `ERROR: No inspectable targets with mermaid graphics`

How can I avoid this? I tried to add to my pdf 
```
format: 
  pdf:
    prefer-html: false
    documentclass: scrreprt
    toc: true
    toc-depth: 3
    logo: "cover.png"
    mermaid-format: png
```
but to no avail. I am on quarto 1.2.335, on Mac. I  tried installing the quarto tools chromium, but that kept crashing...

Any hints? Thanks!

**Comment by cscheid** [comment]
Can you share a complete example?

**Reply by tomkom** [reply]
Here it is - created from scratch:

- created a **new quarto project**:
```
% quarto create-project testproject
```
I altered the auto-generated `testproject.qmd` file into `index.qmd` ( needed for a book), attached (please, change extension to qmd, not allowed extension type here):

[index.txt](https://github.com/quarto-dev/quarto-cli/files/10798658/index.txt)

Then, I altered the `_quarto.yml` :
```
project:
  type: book
  output-dir: docs

book:
  title: "test"
  author: "Martin"
  date: today
  output-file: "book"
  #output-ext: "pdf"

  chapters:
    - index.qmd
   
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    navbar:
      search: true
    cookie-consent: false
  pdf:
    prefer-html: false
    documentclass: scrreprt
    mermaid-format: png
```
also attached (as txt, please rename to yml):

[_quarto.txt](https://github.com/quarto-dev/quarto-cli/files/10798662/_quarto.txt)

So we have a folder with two files, the qmd, and the yml.

**Terminal output for quarto render:**
```
%quarto render

pandoc
  to: html
  output-file: index.html
  standalone: true
  toc: true
  number-sections: true
  title-prefix: test
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  toc-depth: 3

metadata
  crossref:
    chapters: true
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  theme: cosmo
  navbar:
    search: true
  cookie-consent: false
  title: test
  author: Martin
  date: '2023-02-22T00:00:00+11:00'

ERROR: No inspectable targets
```

`quarto preview` works fine:
![image](https://user-images.githubusercontent.com/1487646/220481938-99622b90-88f1-4d5c-bbde-396fcfd6ef85.png)
