### DISCUSSION TITLE
How to select one category by default in a website listing

### DISCUSSION THREAD

**Discussion by gdurif** [quarto-dev/quarto-cli#4486] [Q&A] [answered]
I have a listing in a quarto website (c.f. yaml configuration below). I would like to select a specific category to display only the post inside this category by default (e.g. a category "ongoing" for ongoing stuff).

The reader would then need to click on "All" in the category sidebar to see all posts.

Would that be possible?

```yml
listing:
  id: my-listing-id
  contents: my-content
  sort: "date desc"
  type: default
  categories: true
  page-size: 10
  sort-ui: [date, title, author]
  filter-ui: true
```

Thanks
