### DISCUSSION TITLE
Change headline "Appendices" in TOC

### DISCUSSION THREAD

**Discussion by yann1cks** [quarto-dev/quarto-cli#4523] [Q&A]
Hello everybody,

I am creating a `book` with Quarto, which works quite well. If I add an Appendix I am not able the change/translate the "Appendices" headline in the table of contents. Quarto adds the Appendices headline automatically, with `\addcontentsline{toc}{part}{Appendices}` in LaTeX, but there is no way to translate it. 

I tried the set the following in the yaml, but I does not make a difference.
```
format:
  pdf:
    lang: de
    language:
      de:
        section-title-appendices: "Different Title"

```

Is there another way to change the "Appendices" headline in the toc?
