### DISCUSSION TITLE
`code-fold` and highlight for non executable code

### DISCUSSION THREAD

**Discussion by rleyvasal** [quarto-dev/quarto-cli#4558] [Feature Requests]
It would help presenters to have the ability to highlight code and also do `code-fold` when the code is only for demonstration in a language non executable such as `scss`.

At the moment code in R, Python, can use `code-fold`  but if  other languages are in a code block which is only highlighted, then the code is not fold-able. 

## Python code is foldable with `code-fold` but scss highlighted is not foldable as seen below:

![code-fold](https://user-images.githubusercontent.com/61335136/221746718-b26123fe-d216-4c8f-a8a3-d0405521d0a5.gif)
 

## Reproducible Code

````markdown
---
title: "My document"
format:
  html:
    code-fold: true
    code-summary: "Show code"
---

```{python}
#| eval: false

// Content.scss
@use 'colors' as colors;
body > content {
    padding: 40px;
    margin: auto;
    max-width: 100%
}
```


Show code below folded

```scss
// Content.scss
@use 'colors' as colors;
body > content {
    padding: 40px;
    margin: auto;
    max-width: 100%
}
```

````
