### DISCUSSION TITLE
Need to configure <base href> tag on all rendered pages

### DISCUSSION THREAD

**Discussion by maraschin0** [quarto-dev/quarto-cli#4597] [Q&A] [answered]
Hi,
I want to host one of my Quarto sites on Google Cloud Storage (private site for authorised users). In order to get it to work, I need to be able to add a base href tag right at the top of the `<head>` section of rendered HTML pages along the lines of:

`<base href="https://storage.cloud.google.com/<bucket>/path/to/site/root/"/>`

Is it possible at all?

Thanks

**Comment by dragonstyle** [comment, marked as answer]
You could potentially use one of the `include` options in your `_quarto.yml` file, which would place that HTML verbatim in all files:

```
format:
  html:
    include-before-body:
      - my-base-tag.html
```

Would that work?

**Reply by maraschin0** [reply]
Thank you, your answer put me on the right track. In the end I used `include-in-header` and `embed-resources: true`

```
format:
  html:
    embed-resources: true
    include-in-header:
      - custom.txt
```
