### DISCUSSION TITLE
Restore implicit section titles?

### DISCUSSION THREAD

**Discussion by johnkerl** [quarto-dev/quarto-cli#460] [Q&A] [answered]
Hi -- I did a bit of development using 0.3.114, then recently with @cderv 's great help [got CI rendering working](https://github.com/quarto-dev/quarto-cli/discussions/439) where in CI the Quarto version is [0.9.105](https://github.com/TileDB-Inc/tiledb-quarto-template/blob/main/.github/workflows/quarto-render.yml#L15).

I noticed a feature downgrade -- before, I had my `_quarto.yml` like this:

```
...

  sidebar:
    - id: what-does-this-do
      title: "What does this do?"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: "index.md"

        - section:
          href: "cloning/overview.md"
          contents:
            - href: "cloning/code-and-docs.md"
            - href: "cloning/things-to-change.md"

        - href: "installing/overview.md"
...
```

The essential point for this discussion being is that all pages have titles as `#` lines in their `.md` files, so it's a wonderful thing that I can use `href:` with an `.md` file and pick up the page title which already exists in the `.md` file without having to do "double entry". This works (rather, worked) for [sections](https://github.com/quarto-dev/quarto-cli/discussions/395) as well as contents.

However, using 0.9.105, I found I get an error unless I do this:

```
...

  sidebar:
    - id: what-does-this-do
      title: "What does this do?"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: "index.md"

        - section: "Cloning this repository" # <----------------- need to "double enter" page title from the .md file
          href: "cloning/overview.md"
          contents:
            - href: "cloning/code-and-docs.md"
            - href: "cloning/things-to-change.md"

        - href: "installing/overview.md"
...
```

It turns out implicit naming is no longer allowed. (Or, if allowed, maybe supported in a different _way_ now that I don't understand --- ?)

This is a minor nuisance for trivial-sized repos but it's a bit more of a challenge for larger ones -- we have some significant-sized legacy doc repos to import from another tool (many hundreds of `.md` files with tens of thousands of lines of Markdown code) -- in my import experiments using 0.3.114 it was wonderful being able to bring in legacy `.md` files, morph the old tool's index file into a `_quarto.yml`, and have a working docsite. Using 0.9.105 it will take more scripting to extract [section-page titles](https://github.com/quarto-dev/quarto-cli/discussions/395) out of `.md` files to "double-enter" them into `_quarto.yml`.

Is there a chance we can get bare `section:` back? Or, is there a new way to get the same result that I just don't know about?
