### DISCUSSION TITLE
Why is favicon image or social metadata not available for a standalone HTML?

### DISCUSSION THREAD

**Discussion by frscott** [quarto-dev/quarto-cli#4618] [Q&A] [answered]
Hi I noticed all of the [website tool options](https://quarto.org/docs/websites/website-tools.html) when you create a website through Quarto. But why does favicon option or social metadata not work for an HTML that is stand alone? Or is this possible?

**Comment by mcanouil** [comment, marked as answer]
It's possible, you can also add this yourself but indeed it could probably be a nice thing to have for `html` and `revealjs` formats.

For example, to add a favicon to your document it is as simple as adding the following to your yaml header: 

```yaml
include-in-header:
  - text: |
      <link rel = "shortcut icon" href = "my-favicon.svg" />
```
