### DISCUSSION TITLE
How do I get the 'service', 'id', and 'URL' if I want to publish a book to Quarto Pub?

### DISCUSSION THREAD

**Discussion by e05bf027** [quarto-dev/quarto-cli#4646] [Q&A] [answered]
I have written a book of around 100 pages or so in html. I want to publish it to Quarto Pub. When I look on the Quarto site it mentions that I should manually create a `_publish.yml` file. 

In this, the service, ID, and URL should be specified. The example shows the following:

```
- source: project
  quarto-pub:
    - id: "5f3abafe-68f9-4c1d-835b-9d668b892001"
      url: "https://njones.quarto.pub/blog"
```

I am completely unsure where on earth I find these for myself. I assume it is straightforward. Can anyone tell me?
