### DISCUSSION TITLE
Make a standalone PDF with embedded images?

### DISCUSSION THREAD

**Discussion by richardsprague** [quarto-dev/quarto-cli#4655] [Q&A]
I'm trying to make a PDF book based on some markdown files that use images linked from external URLs. Is there a way to embed the images into the PDF file, similar to how I can create an HTML file with `embed-resources: true` ?

Here's a simple example of what I mean. Is there a way to turn this into a PDF where the logo is embedded (i.e. visible offline)?
```
---
title: "Intro"
---

# Sample Page

This is a simple page with the following image:

<figure>
<img src="https://quarto.org/quarto.png" />
<figcaption>An image</figcaption>
</figure>

```

**Comment by cscheid** [comment]
Unfortunately, Pandoc will not attempt to resolve external URLs; you need to download them yourself. (And you'll need to use Markdown syntax for the images instead of HTML).

**Reply by dragonstyle** [reply]
Carlos is right for now, but...

Starting in quarto 1.3 prerelease (including the current prerelease) remote markdown images for PDF should be resolved into local images embedded in the PDF.

**Reply by richardsprague** [reply]
Thanks!  Note that pandoc standalone kinda does what I want: `pandoc -f html -t docx -o final.docx docs/index.html` will generate a Word file with embedded remote images, and then `pandoc -f docx -t pdf -o final.pdf final.docx` will convert that to PDF.   Is there no way to "chain" these pandoc calls from within Quarto?  

Here's my `_quarto.yml`:
```
project:
  title: "Sample Book"
  type: book
  output-dir: docs


book:
  title: "This is a book"
  chapters:
    - index.qmd

format:
  html:
    theme: flatly
    embed-resources: true
    standalone: true
  docx:
    fig-align: right
    toc: true
    standalone: true
    extract-media: images
    from: html
```
I tried to add:
```
 pdf:
    documentclass: scrbook
    mainfont: "Georgia"
    from: docx
 ```
 But that gives an error ` Package babel Error: Bad option `bidi=default'`

**Reply by dragonstyle** [reply]
If you build your book with Quarto 1.3, it should just work (if you're open to trying our pre-release):

https://quarto.org/docs/download/prerelease

**Reply by cscheid** [reply]
@dragonstyle TIL, thank you for setting me straight!

**Reply by dragonstyle** [reply]
It was a slight side project / sneak in for 1.3, but we actually needed to do it because Pandoc actually does the right thing for PDFs when it renders the PDF (resolving remote URLs). Since we take over PDF rendering, however, we weren't getting that feature from Pandoc which wasn't good and you were definitely right for all previous versions of Quarto!

**Comment by richardsprague** [comment]
I tried with 1.3.249, but it didn't seem to work. Do I need different pdf settings in `_quarto.yml`.  

```
format:
  html:
    theme: flatly
    embed-resources: true
    standalone: true
  docx:
    fig-align: right
    toc: true
    standalone: true
    extract-media: images
    from: html
  pdf:
    documentclass: scrbook
    mainfont: "Georgia"
    from: docx
```

I tried `from: standalone` but that didn't work either.
