### DISCUSSION TITLE
latex rendering with .bib

### DISCUSSION THREAD

**Discussion by KaiWaldrant** [quarto-dev/quarto-cli#4662] [Q&A]
I am using a `library.bib` file to create a bibliography page on the website. In this file latex commands are used for special chars such as `\textregistered`. When rendering the website these are not translated. Any idea on how to get this working ? You can find the relevant files in this small repo to reproduce https://github.com/KaiWaldrant/quarto-latex-render-issue.

```latex
@article{agrawal2021mde,
  title         = {Minimum-Distortion Embedding},
  author        = {Akshay Agrawal and Alnur Ali and Stephen Boyd},
  year          = {2021},
  journal       = {Foundations and Trends{\textregistered} in Machine Learning},
  publisher     = {Now Publishers},
  volume        = {14},
  number        = {3},
  pages         = {211--378},
  doi           = {10.1561/2200000090},
  url           = {https://doi.org/10.1561/2200000090},
}
```
![image](https://user-images.githubusercontent.com/80908902/223377150-f9ee4df2-eb7c-45a7-88ed-7ba4d5ab0ec0.png)

should be : 
![image](https://user-images.githubusercontent.com/80908902/223445959-4fed537d-1860-4a9f-8e00-e237736c502c.png)

The index.qmd has following settings
```yaml
---
title: "Bibliography"
sidebar: false
page-layout: full
bibliography: library.bib
csl: human-nature.csl
nocite: |
  @*
css: [biblio.css]
---
```
