### DISCUSSION TITLE
Separate `repo-url` for subdirectories

### DISCUSSION THREAD

**Discussion by shinneuro** [quarto-dev/quarto-cli#4664] [Q&A] [answered]
Hi,

I am building an website with multiple submodules as mentioned in #1282.
`*.qmd` files are located inside each submodules, and they are all rendered together inside `_site` folder of the main repository.

One feature I would like to implement, but seems currently not working, is separate `repo-url` for `*.qmd` files inside separate submodules. I tried creating `_metadata.yml` inside the submodule, and added a new `repo-url` for the submodule but it seemed not working.

So, `quarto.yml` inside the root directory would be like

```
website:
  title: "quarto"
  repo-url: https://github.com/quarto-dev/quarto-cli
  repo-actions: [edit]
```

and `_metadata.yml` inside the submodule would be something like

```
website:
  repo-url: https://github.com/quarto-dev/quarto-web
```

However, this approach did not work.

Would there be any way to accomplish this type of work?

Thank you in advance.

Best regards,
Minho
