### DISCUSSION TITLE
pages are breaking within individual citations in bibliography

### DISCUSSION THREAD

**Discussion by rhwrhw** [quarto-dev/quarto-cli#4686] [Q&A]
Hi, I have an issue with page breaks within individual cited articles in generated bibliographies. I am using Quarto version 1.2.335 with the Elsevier template on an Intel Mac running 13.2.1 (22D68).

Page breaks should only occur between articles in the bibliography but I cannot find a way to force this behavior. 

Here are relevant items in the YAML header:

```yml
format:
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Science of Remote Sensing
      formatting: preprint
      model: 3p
      cite-style: authoryear
csl: apa
cite-method: citeproc
bibliography: hp_edited.bib
```
