### DISCUSSION TITLE
Light and dark themes in a custom format

### DISCUSSION THREAD

**Discussion by juba** [quarto-dev/quarto-cli#4700] [Q&A] [answered]
Hi,

I'm currently developing a custom HTML format which provides both a light and dark theme. I have something like the following in my `_extension.yml` :

```yaml
      theme:
        light: [bookup.scss]
        dark: [bookup.scss, bookup_dark.scss]
```

This is working fine, but maybe the custom format users will want to only use the light theme, or only the dark theme, or even provide both but with the dark one by default. Is there a way to provide such a feature in a custom format ? I took a look at the documentation but didn't find a way to do this.

Thanks in advance !

**Comment by dragonstyle** [comment, marked as answer]
Right now I don't know if a way to conditionalize this except to provide a number of output variants like:

**_extension.yaml**
```yaml
contributes:
  formats:
    html:
       theme:
        light: [bookup.scss]
        dark: [bookup.scss, bookup_dark.scss]
    html+light:
       theme: bookup.scss
    html+dark:
       theme: [bookup.scss, bookup_dark.scss]
    html+prefer-dark:
       theme:
        dark: [bookup.scss, bookup_dark.scss]
        light: [bookup.scss]
```

The user would then have to use the format in the project/document to control the theme behavior. I think this should work...
