### DISCUSSION TITLE
monobackgroundcolor being ignored

### DISCUSSION THREAD

**Discussion by harrelfe** [quarto-dev/quarto-cli#4736] [Q&A] [answered]
I can't get monobackgroundcolor to take effect as described in https://quarto.org/docs/output-formats/html-themes.html#sass-variables.  Here is a reproducible example.

````
---
title: "Test"
format:
  html:
    monobackgroundcolor: red
    backgroundcolor: cornsilk
    self-contained: true
    toc: true
    toc-location: left
    toc-title: Contents	
---

Here is some code: `xvariable <- pi`.  Regular text follows.

````
