### DISCUSSION TITLE
Not able to insert listing

### DISCUSSION THREAD

**Discussion by ghost** [quarto-dev/quarto-cli#4813] [Q&A] [answered]
I have this in a file called "index.qmd" inside a folder called "rcd": 
```
---
title: "A title"
listing:
  date-format: iso
  feed: true
  filter-ui: false
  id: sample-listings
  contents: 
    - "rcd/*.qmd"
  sort-ui: true
  sort: "date desc"
  categories: false
  fields: [date, title]
  type: table
---

Some text here

::: {#sample-listings}
:::
```

But , after doing quarto publish the page appears without any listing. In the "rcd" folder, I have a file called "rcd-aaa.qmd" with a title and a date in its yaml. 

I do not know what I am doing wrong. I have looked [here](https://quarto.org/docs/websites/website-listings.html) first but have not found a solution. 

What I want is the .qmd files that are in my "rcd" folder to appear in the listing.
