### DISCUSSION TITLE
Can an extension contribute more than one project?

### DISCUSSION THREAD

**Discussion by ijlyttle** [quarto-dev/quarto-cli#4818] [Q&A] [answered]
I am putting together an extension for my company; my goal is to be able to write a single extension, so that I can keep all the css, assets, etc. together. In other words, I'd like to define `html` and `revealjs` formats, and be able to apply the `html` format to either a `website` or `book` project.

I'm reading the [documentation on extensions for project types](https://quarto.org/docs/extensions/project-types.html), and I see this example:

```yml
title: Lexdocs Project
author: Lexcorp, Inc.
version: 1.0.0
quarto-version: ">=1.2.0"
contributes:
  project:
    project:
      type: website
    website:
      sidebar: 
        contents: auto
        search: true
        style: docked
        background: light
        logo: lexcorp.png
      page-footer: |
        "Copyright 2022, Lexcorp, Inc." 
    format: lexdocs-html
  formats:
    html:
      theme: [default, theme.scss]
      code-overflow: wrap
      code-line-numbers: true
      filters:
        - filter.lua
```

This has the basis for *most* of what I'm trying to do. I can see where I can define an additional format by adding a `revealjs` element to `format`.

What I can't see is how to add a `book` project, i.e. I can't see how to fit it into the schema. Is this possible, or would I need to define a separate extension?

Of course I could be thinking about this all wrong; any guidance is very welcome. Thanks!
