### DISCUSSION TITLE
repo-url for Quarto website

### DISCUSSION THREAD

**Discussion by eteitelbaum** [quarto-dev/quarto-cli#4826] [Q&A] [answered]
Hi!

I am trying to set up my course website so that on the individual pages people can click on "Edit this code" to see the code in my GitHub repo. [Here](https://dataviz-gwu.rocks/modules/getting-started.html) is a link to one of the draft pages for the course website.

Here are the first 10 or so lines of my `yaml` header: 

```
project:
  type: website

website:
  page-navigation: true
  title: "PSC/DATS 2102--Summer Schedule"
  description: "Homepage for PSC/DATS 2102, George Washington University."
  site-url: "https://dataviz-gwu.rocks"
  repo-url: "https://github.com/eteitelbaum/dataviz-summer-2023"
  repo-actions: [edit, issue]
```

When I render the, site, the issue link works but not the edit link. Instead it takes the reader to [this link](https://github.com/eteitelbaum/dataviz-summer-2023/edit/main/modules/getting-started.qmd), which gives a 404 error. 

I think it has to do with the "main" vs. "master" distinction because the URL references the "main" branch whereas my local branch was set to the default "master." Not being a CS person, I was not aware of the cultural sensitivities surrounding the "main" versus "master" terminology and so did not change it when I set up the repo. How can I rectify the problem?
