### DISCUSSION TITLE
Listing additional pages within book chapters?

### DISCUSSION THREAD

**Discussion by mikemahoney218** [quarto-dev/quarto-cli#4827] [Feature Requests]
Hi all!

I'm trying to have a document listing inside a chapter of a book project. It works fine when the listing points at chapters of the book (defined in _quarto.yml), but doesn't work if they aren't explicitly included in the book structure. 

I don't want these items to appear in the table of contents, just in the listings section of this chapter. Is there a way to do that?

For instance, given a file structure:

```
chapter_1.qmd
posts/chapter_2.qmd
posts/not_a_chapter.qmd
```

Where `chapter_1` has the YAML:
```yaml
---
listing:
  contents: posts
---
```

And `_quarto.yml` includes:

```yaml
book:
  chapters:
    - chapter_1.qmd
    - posts/chapter_2.qmd
```

The listing in `chapter_1` will include chapter 2, but not `not_a_chapter`. 

This is a simplified example; in my actual case, there will be many items in the listing directory, and having them included with the book automatically (and not included in the chapter index) is my primary goal here (so "add them to the chapter structure" is rather self-defeating).

**Comment by dragonstyle** [comment]
You can do this, though listings will only render the listing for HTML output. I've attached an example project which shows this - the key is adding a `render` option to your project key which includes any files which are not in the book structure but which belongs in the project (this should be a list of globs).

In my example, something like:

```yaml
project:
  type: book
  render: 
    - resources

book:
  title: "Book"
  author: "Jane Doe"
  date: "3/14/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

and 

```markdown
---
listing:
  contents: resources/*.qmd
  type: table
---

# Summary

In summary, this book has no content whatsoever.

```


Sample Project: [book.zip](https://github.com/quarto-dev/quarto-cli/files/10972169/book.zip)

HTH!
