### DISCUSSION TITLE
plume: a simple author handler for scientific writing

### DISCUSSION THREAD

**Discussion by arnaudgallou** [quarto-dev/quarto-cli#4909] [Show and Tell]
I've just released the development version of [plume](https://arnaudgallou.github.io/plume/), a R package that aims at reducing the hassle of handling and formatting author information for scientific writing. The package also allows users to push author metadata into the yaml header of `.qmd`, following Quarto's author and affiliations schema.

I'd be happy to hear any feedback, both on the package and naming of method's parameters.

**Comment by baptiste** [comment]
Sounds useful, thanks!

I'm a bit puzzled by this:
```
author <- tibble(
  given_name = "René",
  family_name = "Descartes",
  affiliation1 = "Collège royal Henri-le-Grand",
  affiliation2 = "
  city=Poitiers
  name=Université de Poitiers
  address=15 Rue de l'Hôtel Dieu
  country=Kingdom of France
  ",
  affiliation3 = "name=Academia Franekerensis country=The Netherlands city=Franeker"
)
```

would it be possible to used nested list-columns, for affiliation2 and 3? (or nested lists instead of dataframes altogether)

**Reply by arnaudgallou** [reply]
Thank you for the suggestion.

I'm actually expecting most people using this package (many of whom are likely to have limited R skills) to make this type of tables in a spreadsheet rather than in R, which means no column nesting. I made the `author` table in R for the purpose of the example.

I added support to the complete affiliation schema because some people would probably have asked for it but I'm not sure how useful this feature is to be honest. I could be wrong but I assume it will be used in very specific cases so it might not be worth spending more time on improving it at the moment.

> or nested lists instead of dataframes altogether

What exactly would be the motivation to use JSON-like objects over rectangular data here? Typing JSON-like objects manually for 20+ authors would be tedious, inconvenient to update and harder to work with.

**Comment by arnaudgallou** [comment]
I've just released [plume](https://arnaudgallou.github.io/plume/index.html) version 0.2.0 which is now entering in a relatively stable phase. The package is particularly useful to generate author and affiliations schemas from tabular data and inject it into the YAML header of Quarto files.

Here's an example from the documentation:

```yaml
---
title: Encyclopédie
---

Qui scribit bis legit
```

```r
aut <- PlumeQuarto$new(
  encyclopedists,
  file = "file.qmd"
)
aut$set_corresponding_authors(1, 4)
aut$to_yaml()
```

```yaml
---
title: Encyclopédie
author:
  - id: aut1
    name:
      given: Denis
      family: Diderot
    email: diderot@encyclopediste.fr
    phone: '+1234'
    orcid: 0000-0000-0000-0001
    note: born in 1713 in Langres
    attributes:
      corresponding: true
    roles:
      - supervision
      - writing - original draft
    affiliations:
      - ref: aff1
  - id: aut2
    name:
      given: Jean-Jacques
      family: Rousseau
    email: rousseau@encyclopediste.fr
    orcid: 0000-0000-0000-0002
    attributes:
      corresponding: false
    roles:
      - writing - original draft
    affiliations:
      - ref: aff2
  - id: aut3
    name:
      given: François-Marie
      family: Arouet
    email: arouet@encyclopediste.fr
    note: also known as Voltaire
    attributes:
      corresponding: false
    roles:
      - writing - original draft
    affiliations:
      - ref: aff2
  - id: aut4
    name:
      given: Jean
      family: Le Rond d'Alembert
    email: alembert@encyclopediste.fr
    orcid: 0000-0000-0000-0003
    note: born in 1717 in Paris
    attributes:
      corresponding: true
    roles:
      - supervision
      - writing - original draft
    affiliations:
      - ref: aff1
      - ref: aff3
affiliations:
  - id: aff1
    name: Université de Paris
  - id: aff2
    name: Lycée Louis-le-Grand
  - id: aff3
    name: Collège des Quatre-Nations
---

Qui scribit bis legit
```
