### DISCUSSION TITLE
using mhchem in equations

### DISCUSSION THREAD

**Discussion by rputikar** [quarto-dev/quarto-cli#4931] [Q&A]
I am trying to follow [https://github.com/quarto-ext/latex-environment#example-1](https://github.com/quarto-ext/latex-environment#example-1) to write an equation containing chemical formula. 

I can't get it working within an equation block (or inline equation) though. The \ce command works fine.  Any help will be appreciated. 

Is there any way to display chemical formulae (other than using mathjax/ katex and include mhchem extension) for the rendered html (i.e. render [H2SO4]{.ce})

```
---
title: LaTeX Command
format:
   pdf:
     include-in-header: 
       text: |
         \usepackage{mhchem}
   html: default
filters:
   - latex-environment
commands: [ce]
---

This will replace spans of class `ce` with the `\ce{}` command for LaTeX output, 
but leave the spans intact for HTML output. So `[H2SO4]{.ce}` becomes [H2SO4]{.ce}.

est in text: [H2SO4]{.ce} 

Test in inline equation $[H2SO4]\{.ce\}$

Test in equation

$$
[H2SO4]{.ce}
$$

Using `\ce` inline $\ce{H2SO4}$

$$
\ce{H2SO4}
$$
```

the output: 

![image](https://user-images.githubusercontent.com/114011/227222877-705fd1ac-7e2d-4bf8-97da-17f2ea810160.png)

**Comment by bwelman** [comment]
This works for me
```
---
title: "Chemistry"
format: 
  html: default
  pdf:
    include-in-header: 
      text: |
        \usepackage{mhchem}
---

Sulfuric acid formula: $\ce{H2SO4^{2-}}$
```
