### DISCUSSION TITLE
Is there a way to place text before the icon in the navbar?

### DISCUSSION THREAD

**Discussion by tangandhara** [quarto-dev/quarto-cli#4952] [Q&A]
I have a link to Github in my navbar and wanted to show it was an external link with the _'box-arrow-up-right'_ icon but it appears before the text rather than after it, as you might expect to see elsewhere. 

![image](https://user-images.githubusercontent.com/63885085/227576889-e7060c54-fb22-45d0-b7f6-06f6cb84ef70.png)

Since I can't use _'link-external-icon: true'_ in the navbar, is there  another way around this? This is what I have so far:

![image](https://user-images.githubusercontent.com/63885085/227577157-2cfec368-dd51-425f-b24f-6b0a18075a1d.png)

**Comment by mcanouil** [comment]
Use shortcode from whatever Quarto extension to add the icon in the text field.
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8896044/227738934-fe12aabd-2908-44ad-bc01-72e1a4f2b64d.png">

```sh
quarto-dev create-project --type website
quarto add mcanouil/quarto-iconify
```

```yml
project:
  type: website

website:
  title: "quarto-playground"
  navbar:
    left:
      - href: index.qmd
        text: "{{< iconify exploding-head >}} Home"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```
