### DISCUSSION TITLE
controling author text color in revealjs

### DISCUSSION THREAD

**Discussion by ChristelSwift** [quarto-dev/quarto-cli#4975] [Q&A] [answered]
I'm trying to create a quarto revealjs presentation where the title slide has a dark background and white text, and  the rest of the presentation has black text on white background.  Taking inspiration from this post [https://stackoverflow.com/questions/73575170/quarto-revealjs-presentation-change-title-author-date-position-font-size-an](https://stackoverflow.com/questions/73575170/quarto-revealjs-presentation-change-title-author-date-position-font-size-an) I managed to get the white title by adding a `custom.css` file with these lines:

```
.title {
  font-size: 120px !important;
  color: white !important;
}

.author {
  font-size: 100px;
  color: white;
}

```

... but for some reason it doesn't apply the white color for the author element... 

Here's the yaml:

```
---
title: "Quarto presentation"
author: "me"
format: 
  revealjs:
    theme: [default, custom.css]
    title-slide-attributes:
      data-background-image: images/dark_background.jpg
      data-background-size: cover  
editor: visual
---
```

Any idea how i could control both title and author text colour please?

Thanks in advance :)

**Comment by mcanouil** [comment, marked as answer]
The theme option is for SCSS not CSS.
Below is an example to tweak title and subtitle font-size, and tweak author colour.

```scss
/*-- scss:rules --*/
#title-slide {
  .title {
    font-size: 4.5em;
    color: #ffffff;
  }

  .subtitle {
    font-size: 3em;
  }

  .quarto-title-author {
    color: #ffffff;
  }
}
```

You also have `.quarto-title-affiliation`, `.quarto-title-author-email`, `.quarto-title-author-name` to have more fine grain tuning.
