### DISCUSSION TITLE
Linkedin is not able to display or preview my jupyter notebook blog post

### DISCUSSION THREAD

**Discussion by tabacof** [quarto-dev/quarto-cli#4979] [Q&A]
Hi all, I published a blog post from a Jupyter notebook using Quarto but it's not working with Linkedin for some reason. It cannot understand it's a HTML page. I tried googling answers and couldn't find anything. Here is some relevant information:

Blog post link: https://tabacof.github.io/posts/name_classification/name_classification.html

Blog post source (jupyter notebook): https://github.com/tabacof/tabacof.github.io/blob/master/posts/name_classification/name_classification.ipynb

Post medata:
```yaml
---
title: "Name classification with ChatGPT"
subtitle: "How does it compare to machine learning language models?"
author: "Pedro Tabacof"
date: "2023-03-27"
categories: []
format: html
toc: true
description-meta: "Name classification with ChatGPT: How does it compare to machine learning language models?"
pagetitle: "Name classification with ChatGPT"
author-meta: "Pedro Tabacof"
date-meta: "2023-03-27"
keywords: "ChatGPT, name classification, machine learning, NLP, language models"
---
```

Linkedin's error:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/2151702/227917905-8ca5c27e-8a13-41ff-ad45-e7384c9b8df1.png">

I even tried to use Linkedin's [post inspector](https://www.linkedin.com/post-inspector) to understand what is happening but no dice:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/2151702/227918036-c3720ad8-874e-42ae-b828-25e381c33aac.png">

Anyone knows what is happening? Any help would be appreciated, thanks!
