### DISCUSSION TITLE
Quarto revealjs with custom figure caption size.

### DISCUSSION THREAD

**Discussion by damian-oswald** [quarto-dev/quarto-cli#5014] [Q&A] [answered]
I would like to decrease the size of the figure caption document-wide, by using an `scss` theme. However, it doesn't seem to have any impact on the figure caption size.

Here's an example code for the quarto file:

```{qmd}
---
format:
  revealjs:
    theme: theme.scss
---

![This is the figure caption. Is there any way to make it smaller?](https://quarto.org/quarto.png)
```
It uses the following simplified `scss` theme:

```{scss}
/*-- scss:rules --*/

.reveal {
  .slides {
    figcaption {
      font-size: 0.5em;
    }
  }
}
```

Yet, whatever font size I set, it doesn't change the generated figure caption size at all. Does anybody know how I have to change the `scss` file such that it works properly, or is this not possible this way?

**Comment by cderv** [comment, marked as answer]
First if you inspect the HTML, you'll see the caption text is in `p.caption` element, so `figcaption` won't catch it. 

Also, there are some [CSS specificity](https://specifishity.com/) to take into account, and you need to add a rule that will overwrite the default one. You need at least the same specificity 

So you can use 
````scss
/*-- scss:rules --*/

.reveal {
  .slides {
    .slide {
      img+p.caption {
        font-size: 0.5em;
      }
    }
  }
}
````

and also if you are just customizing a them, and not providing a full new one, you probably need to keep the default 
https://quarto.org/docs/presentations/revealjs/themes.html#customizing-themes

````yaml
format:
  revealjs: 
    theme: [default, custom.scss]
````

Hope this helps
