### DISCUSSION TITLE
Include custom css for reveal slides via link

### DISCUSSION THREAD

**Discussion by jvcasillas** [quarto-dev/quarto-cli#5043] [Q&A] [answered]
I'm looking for a way to streamline my workflow and be able to easily switch between themes I have created and hosted on github. Ideally I would like to use the yaml front matter to link to the custom scss and title-slide.html files like this: 

```
---
format: 
  revealjs:
    theme: [default, LINK_TO_SCSS_FILE]
    template-partials:
      - LINK_TO_CUSTOM_title-slide.html
engine: knitr
```

This does not work for me. Is there a way to do something similar to this without downloading a template?
