### DISCUSSION TITLE
Cover image to pdf output

### DISCUSSION THREAD

**Discussion by Boadzie** [quarto-dev/quarto-cli#506] [Q&A] [answered]
Can you add a cover image to a pdf output?

**Comment by dragonstyle** [comment, marked as answer]
Right now cover images are directly support in quarto for html or epub output, though you could provide a custom latex template for pdf using the `template` option… that would allow you to place the cover image in the latex template itself and use that when the document is rendered…

**Reply by Boadzie** [reply]
ok, thanks.

**Reply by fuhrmanator** [reply]
`template` is a very powerful way, but hard to maintain IMO. An easier workaround might be to put the image in the subtitle (if you're doing a book). This works for me in PDF output (from LaTeX using `pdf: ... documentclass: scrbook`):

```yaml
book:
  title: "My book"
  author: "Me"
  subtitle: "![word cloud](images/word-cloud.png){width=70%}"
```

You might even be able to put it in a title, but I didn't try.
