### DISCUSSION TITLE
New quarto extension--compilation failed error

### DISCUSSION THREAD

**Discussion by eteitelbaum** [quarto-dev/quarto-cli#5075] [Q&A]
I am trying to create a new quarto extension. [Here](https://github.com/eteitelbaum/apsr-quarto-test) is a link to my repo. I feel like I am close to doing it but when I render my sample .qmd file I get this error: 

```
compilation failed- error
Missing \endcsname inserted.
<to be read again> 
                   \protect 
l.8 
```

Right now I am just trying to do the .pdf and will return to .html later. Here is the code from my `_extension.yml` file: 

```
title: APSR Journal Format
author: Emmanuel Teitelbaum
version: 0.1.0
quarto-required: ">=1.2.0"
contributes:
  formats:
    pdf:
      documentclass: apsr_submission
      biblio-style: chicago-apsr
      cite-method: natbib
      format-resources:
        # Add here the resources required for the PDF rendering
        - apsr_submission.cls
        - chicago-apsr.bst
     #html:
          #css: styles.css
```

I have the `apsr_submission.cls` file and the `chicago-apsr.bst` file in the extension folder. Then I try to render it with this template.qmd file: 

```
---
title: APSR Template Test
format:
  apsr-pdf:
    keep-tex: true  
  #apsr-html: default
author:
  - name: Bullwinkle J. Moose
    affiliations:
      - name: Wassamotta U.
        department: Department of Environmental Science
        address: 1501 U.S. Highway 71
        city: Frostbite Falls
        country: USA
        postal-code: 56649
      - second affiliation
    orcid: 0000-0000-0000-0000
    email: bjm2@wossamotta.edu
    url: https://example.org/
  - name: Kathryn Janeway
    affiliations:
      - name: Starfleet Academy
      - email: k.janeway@sfa.edu
abstract: |
  "Convallis a cras semper auctor neque vitae. Id faucibus nisl tincidunt eget nullam non nisi. Eget nunc scelerisque viverra mauris. Risus sed vulputate odio ut enim blandit volutpat maecenas. Quam elementum pulvinar etiam non quam lacus. Ut tortor pretium viverra suspendisse. Id consectetur purus ut faucibus pulvinar elementum."
keywords: [template, demo]
bibliography: bibliography.bib  
---

## Introduction {#sec-intro}

*TODO* Create a template that demonstrates the appearance, formatting, layout, and functionality of your format. Learn more about journal formats at <https://quarto.org/docs/journals/>.
```

Am I missing something here?
