### DISCUSSION TITLE
Quarto try to move output file  twice - error when rendering profile

### DISCUSSION THREAD

**Discussion by danieltomasz** [quarto-dev/quarto-cli#5099] [Q&A] [answered]
In my default `_quarto.yml` profile I have
```
project:
  output-dir: _output
```

In my another profile `_quarto-thesis.yml` I have

```
project:
  type: book
  output-dir: _output
```
an then later 
```
book:
  title: Example title
  author:
    name: Daniel Borek
  chapters:
    - index.qmd
    - include/references.qmd
  #site-url: https://nmfs-opensci.github.io/quarto-thesis/
  #repo-url: https://github.com/nmfs-opensci/quarto-thesis
  #repo-actions: [edit, source, issue]
  #downloads: [pdf]
  search: true
  output-file: "thesis"
  #appendices:
  #  - include/frontmatter/AppendixA.qmd
```

When I use `quarto render --profile thesis ` the file is produced and move to output folder, but I am getting now the following error
```
ERROR: NotFound: No such file or directory (os error 2), rename '/Users/daniel/PhD/Projects/2023/DoctoralThesis2023/thesis.pdf' -> '/Users/daniel/PhD/Projects/2023/DoctoralThesis2023/_output/thesis.pdf'

NotFound: No such file or directory (os error 2), rename '/Users/daniel/PhD/Projects/2023/DoctoralThesis2023/thesis.pdf' -> '/Users/daniel/PhD/Projects/2023/DoctoralThesis2023/_output/thesis.pdf'
    at Object.renameSync (deno:runtime/js/30_fs.js:175:9)
    at renderProject (file:///Applications/quarto/bin/quarto.js:86803:22)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:90827:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:127472:5)
    at async file:///Applications/quarto/bin/quarto.js:127490:9
```

The error started to  appear when I use this yml as profile, it didnt appear when there was only one yml config.
I am using Quarto preview 1.3.306 on MacOS 13.4
