### DISCUSSION TITLE
Book projects don't generate html for linked pages not explicitly included

### DISCUSSION THREAD

**Discussion by richardsprague** [quarto-dev/quarto-cli#5124] [Q&A]
On a website version of my project, all internal links resolve correctly, whether they're explicitly in my contents or not. But the same is not true when rendering the exact same project as a book.

Here's `_quarto.yml`:
```
project:
  title: "My Project"
  type: website
  output-dir: docs


book:
  title: "This is a book"
  chapters:
    - index.qmd

website:
  title: "Sample Website"
  sidebar:
    contents:
      - section: "Basics"
        contents:
        - index.qmd
```

and here's `index.qmd`:

```
---
title: index.qmd
---
This is the main index.qmd
and here's a link to [about.md](about.md)
```

Note the link to the separate `about.md`, which is not explicitly included in the contents for either book or website format.

When I render this as a website, the `about` link correctly displays as html. But as a book, I see only the original markdown.

Is this by design?  I'd like to switch back and forth between book mode and website mode, but this won't let me do that.
