### DISCUSSION TITLE
Add Footer on Every Page on Quarto Book PDF render

### DISCUSSION THREAD

**Discussion by martinlardi** [quarto-dev/quarto-cli#5158] [Q&A]
```
project:
  type: book

book:
  title: "quarto_ex1"
  chapters:
    - index.qmd
    - chap2.qmd

format:
  pdf:
    include-in-header:
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyfoot[R]{Right Footer\\Line 2 Right Footer}
        \fancyfoot[L]{Left Footer\\Line 2 Left Footer}

editor: visual
```
https://github.com/martinlardi/quarto_ex1

I did quarto book. When I run this, It didn't have footer for first page of index.qmd and chap2.qmd.
How do I get footer for every page including first page of every chapters (index.qmd and chap2.qmd)?
