### DISCUSSION TITLE
When will or does quarto support documentsclass: article/scrartcl?

### DISCUSSION THREAD

**Discussion by eyayaw** [quarto-dev/quarto-cli#516] [Q&A] [answered]
I read the quarto book style documentation here: https://quarto.org/docs/books/book-output.html#pdf-styles.
My question is I have been trying to set up a quarto book project with an `article` document class. 
The project files render to pdf when the `documentclass : report` , but not with `article`. 

```
format:
  pdf:
    documentclass: article #scrartcl
```
```latex
compilation failed- error
Undefined control sequence.
<argument> \chapter 
                    *{Preface}\label {preface}
l.178 \chapter*{Preface}\label{preface}}
```

I have learned that the [problem](https://tex.stackexchange.com/questions/36988/regarding-the-book-report-and-article-document-classes-what-are-the-mai) occurs due to the fact that `\chapter` is not available to the `article` class. Any workaround yet?

**Comment by jjallaire** [comment]
For books, you need to use documentclass `book` or the Koma equivalent `srcbook`

You can use the article classes for single documents but not multi-chapter books

**Reply by eyayaw** [reply]
Thank you for the reply. 

I was thinking something like [single document](https://bookdown.org/yihui/bookdown/a-single-document.html#a-single-document) in bookdown.  

In bookdown, the following works:

index.Rmd
```yaml
---
title: "**House prices**"
author: "J Doe"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
documentclass: article
bibliography: references.bib
---
```
_output.yml
```yaml
---
bookdown::pdf_book:
  in_header: preamble.tex
  latex_engine: xelatex
  citation_package: default
  keep_tex: yes
  toc: no
  ---
  ```
