### DISCUSSION TITLE
remove chapter name/number in quarto pdf book proj

### DISCUSSION THREAD

**Discussion by eyayaw** [quarto-dev/quarto-cli#517] [Q&A] [answered]
Hi there, 
What is the equivalent of the below bookdown opts in quarto? Thank you. 
```yaml
language:
  ui:
    chapter_name: ""
  label:
    fig: "Figure "
    tab: "Table "
```
