### DISCUSSION TITLE
Enabled toc in _quarto.yml change the look of "about" page with disabled toc

### DISCUSSION THREAD

**Discussion by danieltomasz** [quarto-dev/quarto-cli#5203] [Q&A] [answered]
In quarto yml I defined
```
format:
  html:
    highlight-style: a11y
    theme: styles-copy.scss
    toc: true
    toc-depth: 3
    toc-location: left
```
this make the content of about page moved to the right and into the bottom of the page, 

![image](https://user-images.githubusercontent.com/7980381/232328983-7aa423b9-605c-4340-9a2e-2465be859a26.png)

this is what I try to use to mitigate this effect in yaml  about page
```
format:
  html:
    toc: false

comments: false
toc: false
```
