### DISCUSSION TITLE
Sidebar defined in _quarto.yml not rendering raw HTML in Quarto CLI 1.3.306

### DISCUSSION THREAD

**Discussion by JavOrraca** [quarto-dev/quarto-cli#5221] [Q&A] [answered]
I maintain the Southern California R User Group website ([socalr.org](https://socalr.org/)) which was developed with Quarto. I attempted to upgrade to Quarto 1.3.306 but raw HTML was not rendering as expected in the site's sidebar. For reference, our GitHub repo can be found here: [github.com/socalrug/socalr.org](https://github.com/socalrug/socalr.org)

Below an example code snippet from the `_quarto.yml` showing the raw HTML links in the `text` field under `contents`. Please advise if I should plan to update the project's `_quarto.yml` to work correctly with Quarto 1.3.306. Any pointers would be appreciated, thanks! 🙏

```
  sidebar:
    background: "#3469B6"
    logo: "images/logo_text_blue_background.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/socalrug
        text: GitHub
      - icon: slack
        href: https://socalrug.slack.com/
        text: Slack
      - icon: linkedin
        href: https://www.linkedin.com/company/socalrug/
        text: LinkedIn
      - icon: twitter
        href: https://twitter.com/oc_rug
        text: "Twitter: @oc_rug"
      - icon: instagram
        href: https://www.instagram.com/socalrug/
        text: "Instagram: @socalrug"
      - icon: youtube
        href: https://www.youtube.com/@SouthernCaliforniaRUsersGroup
        text: YouTube
      - icon: envelope
        href: "mailto:orangecounty.rug@gmail.com"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: '<a href="https://www.meetup.com/socal-rug/" target="_blank">Join our Meetups</a>'
      - href: index.qmd
        text: Events
      - text: '<a href="https://github.com/socalrug/presentations" target="_blank">Past Presentations</a>'
      - section: "Hackathons"
        contents:
          - text: '<a href="https://github.com/socalrug/hackathon-2022-04" target="_blank">2022-04</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2021-04" target="_blank">2021-04</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2020-04" target="_blank">2020-04</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2019-11" target="_blank">2019-11</a>'
          - text: '<a href="https://github.com/socalrug/hackathon-2019-05" target="_blank">2019-05</a>'
      - section: "Book Clubs"
        contents:
          - text: '<a href="https://www.meetup.com/socal-rug/events/290821300/" target="_blank">2023-01: Advanced Probabilistic ML</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/284913426/" target="_blank">2022-04: Forecasting Principles and Practice</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/283044538/" target="_blank">2022-01: Information Rules</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/280319522/" target="_blank">2021-09: Introduction to Statistical Learning</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/278765369/" target="_blank">2021-07: OpenIntro Statistics</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/278831056/" target="_blank">2021-07: Communicating with Data</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/276575373/" target="_blank">2021-03: Text Mining with R</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/275783285/" target="_blank">2021-02: Mastering Spark with R</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/275719547/" target="_blank">2021-01: R for Data Science</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/272034792/" target="_blank">2020-09: Advanced R</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/270076542/" target="_blank">2020-05: Applied Predictive Modeling</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/268226879/" target="_blank">2020-02: Feature Engineering & Selection</a>'
          - text: '<a href="https://www.meetup.com/socal-rug/events/266912350/" target="_blank">2020-01: R for Data Science</a>'
```

**Comment by jimjam-slam** [comment]
I believe [the `target` property was added to sidebar and nav links](https://github.com/quarto-dev/quarto-cli/issues/2284) for Quarto 1.3 (although I don't know precisely which pre-release version it was introduced in, so you might need to update).

According to [this comment](https://github.com/quarto-dev/quarto-cli/discussions/2283#discussioncomment-5111336), it should look something like:

```yaml
- section: "Book Clubs"
      contents:
        - text: 2023-01: Advanced Probabilistic ML
          href: https://www.meetup.com/socal-rug/events/290821300/
          target: _blank
        - text: 2022-04: Forecasting Principles 
          href: https://www.meetup.com/socal-rug/events/284913426/
          target: _blank
[etc.]
```
