### DISCUSSION TITLE
Automatically change file names by output format, using qmd filename?

### DISCUSSION THREAD

**Discussion by DBecker7** [quarto-dev/quarto-cli#5261] [Q&A] [answered]
I would like to produce lecture slides in beamer pdf, while also creating a basic pdf file with extra information in :::notes::: containers. Both pdf and beamer produce files with the same name, so the slides get overwritten.

Is there something like:
```
format:
  pdf:
    output: "[$filename]_notes.pdf"
  beamer:
    output: "[$filename]_slides.pdf"
```

I will be doing this for 20+ lectures each for two courses, so anything that reduces manual metadata entry is a plus (I am doing this within a quarto project).

**Comment by mcanouil** [comment]
The YAML option `output` does not exist.
What you want is `output-file` which is described in "reference" pages of the formats, see <https://quarto.org/docs/reference/formats/pdf.html#rendering> and <https://quarto.org/docs/reference/formats/presentations/beamer.html#rendering>.

~~Note that you can pass shortcode variable into `output-file` allowing you to use the env or meta shortcodes, see <https://quarto.org/docs/authoring/variables.html>.~~
This does not work, because I believe shortcodes are evaluated too late.

**Reply by mcanouil** [reply]
You could also use `output-ext` as an hack.

```yaml
format:
  pdf:
    output-ext: "notes.pdf"
  beamer:
    output-ext: "slides.pdf"
```

which would produce `filename.notes.pdf` and `filename.slides.pdf` if you don't mind using a `.`.

**Reply by DBecker7** [reply]
Thanks, this is a great workaround! I also saw something about post-render scripts in my searching, so I'll see about a bash script that renames files.

**Reply by mcanouil** [reply]
Indeed with post-render script you could rename the files.

Personally, I would go with `output-ext` because it's built in which mitigate or even avoid side effects.

**Reply by DBecker7** [reply]
I've been trying to implement this, but using `output-ext` results in a corrupted file. My `_quarto.yml` file includes this:

```
format: 
    beamer:
        theme: Madrid
        colortheme: spruce
        aspectratio: 169
        toc: false
        output-ext: "slides.pdf"
        execute:
            echo: false
    pdf:
        toc: true
        execute:
            echo: true
```

The file ending `.slides.pdf` cannot be opened by any pdf editor on my system. The other file is perfect.

If you could help that would be great, otherwise I might just use different output directories.

**Reply by DBecker7** [reply]
List of failures (running `quarto render` from terminal):

- `output-ext` produces a corrupted pdf
- `ouput-dir` does nothing inside the `format` block
- `latex-output-dir` creates the first pdf and then leads to an error, so the second file is never produced
  - `ERROR: NotFound: No such file or directory (os error 2)`
- `post-render` doesn't seem to run my bash script at all (I included echo commands and file dumps to test, neither appeared)
- `post-render: for f in *.pdf; mv f ../Slides; done` does nothing.

**Reply by mcanouil** [reply]
I am away from a keyboard, but could you share the post-render script and the exact yaml you used?
It should work.
For `output-ext`, I tried with html/pdf and had no issue. I did not try beamer/pdf.
`output-dir` is a project option not a format option, thus does not work in your use case.

**Reply by DBecker7** [reply]
Thanks for continuing to help me!

Content of `move-beamer.sh` (quarto project directory):

```sh
echo "Running move_beamer..sh"
pwd

for f in *.pdf;
    mv $f ../Slides;
done

echo "I moved from this directory" > tmp.txt
```

Content of `_quarto.yml`:

```
format: 
    beamer:
        theme: Madrid
        colortheme: spruce
        aspectratio: 169
        toc: false
        post-render: move_beamer.sh
        execute:
            echo: false
            fig-width: 7
            fig-height: 3.5
    pdf:
        toc: true
        execute:
            echo: true
            fig-width: 8
            fig-height: 5
```
