### DISCUSSION TITLE
why repo action always displaying in the footer?

### DISCUSSION THREAD

**Discussion by ning3739** [quarto-dev/quarto-cli#5282] [Q&A] [answered]
Hi there，

How can I prevent repo-action from always displaying in the footer on GitHub after updating Quarto from v1.2.475 to v1.3.336? Specifically, the "edit" and "report an issue" buttons are consistently appearing in the footer, and I would like to know how to prevent this.  Please see mu [repo](https://github.com/NING3739/datalabzone).

HERE IS MY CODE:

```
project:
  type: website

website:
  title: "Data Lab Zone"
  image: images/My-project-logo.png
  favicon: images/My-project-favicon.png
  twitter-card: 
    site: "@ningli3739"
  open-graph: true
  site-url: "https://datalabzone.com/"
  repo-url: "https://github.com/NING3739/datalabzone"
  repo-actions: [edit, issue]
  google-analytics: 
    anonymize-ip: true
    tracking-id: "G-Y96LK2RNJD"
  back-to-top-navigation: true
  page-navigation: true
  # navgation bar
  navbar:
    background: "#ECF2FF"
    logo: images/My-project-logo.png
    logo-alt: "Data Lab Zone brand"
    title: false
    collapse-below: lg
    right:
      - posts/index.qmd
      - series/index.qmd
      - projects/index.qmd
      - talks/index.qmd
      - about.qmd
  # page footer
  page-footer:
     background: "#ECF2FF"
     left: "&copy; 2023 [Data Lab Zone](index.qmd)"
     
     right:
       - href: https://github.com/NING3739/datalabzone
         icon: github
         aria-label: GitHub
       - href: https://twitter.com/ningli3739
         icon: twitter
         aria-label: Twitter
     
format:
  html:
    theme: [lux, dlz.scss]
    css: dlz.css
    code-overflow: scroll
    code-link: true
    code-line-numbers: true
    code-block-bg: "#F0F0F0"
    code-block-border-left: "#2192FF"
    date-format: MMM DD, YYYY
    toc: true
    grid:
      body-width: 1000px
      margin-width: 250px

comments: 
  giscus: 
    repo: NING3739/my-personal-website
    repo-id: R_kgDOIYBxAA
    category: Comments
    category-id: DIC_kwDOIYBxAM4CS2io
    mapping: url
    input-position: bottom
    theme: preferred_color_scheme

execute:
  freeze: auto
```
![Screenshot 2023-04-24 154008](https://user-images.githubusercontent.com/94179273/233895075-d3b9a057-dcb4-41fe-976c-b223aba31769.png)

Thank you so  much!!!
