### DISCUSSION TITLE
Table and Figure Caption Formatting

### DISCUSSION THREAD

**Discussion by TimOliverMaier** [quarto-dev/quarto-cli#5513] [Q&A] [answered]
Hello!

I am currently working on my thesis in a Quarto book project. (Kudos to the maintainers I really like the project!) 

For my work, I would like to have a 1.5 space between lines in the paragraphs, but not in the table and figure captions. It further would be a great bonus to have the `Figure X` or `Table X` bold.
I tried to address the captions individually by including the package `caption` but this does not change anything. 
Here is my current yml file:

```yaml
project:
  type: book

book:
  title: "my title"
  subtitle: "Master's Thesis"
  author: "Tim Maier"
  date: "7/21/2023"
  date-format: "DD.MM.YYYY"
  chapters:
    - index.qmd
    - introduction.qmd
    - methods.qmd
    - resultsanddiscussion.qmd
    - conclusionandoutlook.qmd
    - declaration.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    keep-tex: true
    include-in-header:
      - text: |
          \usepackage{noto-serif}
          \usepackage[labelfont={bf}]{caption}
    fig-cap-location: margin
    tbl-cap-location: margin
    papersize: A4
    documentclass: report
    geometry:
      - lmargin=20mm
      - rmargin=50mm
      - marginparwidth=35mm
    template-partials:
      - before-body.tex
    linestretch: 1.5
```
Do you have any Ideas on how I could configure my captions individually?

EDIT:

I noticed that using the caption package works on the figure and table captions if they are not positioned in the margin. Does anybody have ideas on how to address the margin captions?

Best regards,
Tim
