### DISCUSSION TITLE
Greek letters are not printed out correctly in PDF

### DISCUSSION THREAD

**Discussion by XinyanYang95** [quarto-dev/quarto-cli#5519] [Q&A] [answered]
Hi, I have my .qmd files written for an HTML book. In a table like this,

| $\mathbf{n}$ | $\mathbf{\omega_n}$ | $\mathbf{T_n}$| $\mathbf{\phi_{1n}}$ | $\mathbf{\phi_{2n}}$ | $\mathbf{\phi_{3n}}$ | mass |  stiffness |
|:-----------:|:---------:|:-----------:|:---------:|:-----------:|:---------:|:-----------:|:---------:|
| 1 | 3.14 | 2 | 5 | 5 | 5 | 5 | 5|
| 2 | 6.28 | 1 | 4 | 4 | 4 | 4 | 4|

Greek letters could be printed out correctly in HTML. However, when I tried to build PDF using this .qmd file. They are printed out as raw texts. I need to modify the table into the table below (replace \phi with φ, \omega with ω) and use "fontfamily: libertinus" to get these Greek letters printed out correctly. Do you know why?

| $\mathbf{n}$ | $\mathbf{ω_n}$ | $\mathbf{T_n}$| $\mathbf{φ_{1n}}$ | $\mathbf{φ_{2n}}$ | $\mathbf{φ_{3n}}$ | mass |  stiffness |
|:-----------:|:---------:|:-----------:|:---------:|:-----------:|:---------:|:-----------:|:---------:|
| 1 | 3.14 | 2 | 5 | 5 | 5 | 5 | 5|
| 2 | 6.28 | 1 | 4 | 4 | 4 | 4 | 4|

**Comment by mcanouil** [comment]
Could you share a small "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Reply by XinyanYang95** [reply]
[Quarto_files.zip](https://github.com/quarto-dev/quarto-cli/files/11472235/Quarto_files.zip)
Thx!

**Reply by mcanouil** [reply]
Please could you share either as a repository or as in plain text? As I showed?

**Reply by XinyanYang95** [reply]
````qmd
---
include-in-header:
    - text: |
        <script>
        window.MathJax = {
        tex: {
            tags: 'ams'
        }
        };
        </script>
---

| $\mathbf{n}$ | $\mathbf{\omega_n}$ (rad/s) | $\mathbf{T_n}$ (s) | $\mathbf{\phi_{1n}}$ | $\mathbf{\phi_{2n}}$ | $\mathbf{\phi_{3n}}$ | modal mass | modal stiffness |
|:-----------:|:---------:|:-----------:|:---------:|:-----------:|:---------:|:-----------:|:---------:|
| 1 | 3.14 | 2.00 | 0.33 | 0.67 | 1.00 | 88.89 | 877.33|
| 2 | 6.28 | 1.00 | -0.33 | -0.33 | 1.00 | 55.56 | 2193.33 |
| 3 | 9.42 | 0.67 | 1.00 | -0.67 | 0.33 | 148.15 | 13160.00| 

:Results from modal analysis. {#tbl-v1}

| $\mathbf{n}$ | $\mathbf{ω_n}$ (rad/s) | $\mathbf{T_n}$ (s) | $\mathbf{φ_{1n}}$ | $\mathbf{φ_{2n}}$ | $\mathbf{φ_{3n}}$ | modal mass | modal stiffness |
|:-----------:|:---------:|:-----------:|:---------:|:-----------:|:---------:|:-----------:|:---------:|
| 1 | 3.14 | 2.00 | 0.33 | 0.67 | 1.00 | 88.89 | 877.33|
| 2 | 6.28 | 1.00 | -0.33 | -0.33 | 1.00 | 55.56 | 2193.33 |
| 3 | 9.42 | 0.67 | 1.00 | -0.67 | 0.33 | 148.15 | 13160.00| 

:Results from modal analysis. {#tbl-v2}
````

So basically, my tbl-v1 works well for hmtl version. But for PDF, I need to change it to tbl-v2 and use "fontfamily: libertinus".

**Reply by mcanouil** [reply]
We need a complete Quarto document, which includes format(s).

**Comment by XinyanYang95** [comment]
````yml
project:
  type: book

book:
  title: "Dynamics"
  author: "xxx"
  date: "03/30/2023"
  chapters:
    - index.qmd
    - multidof.qmd
  search: false

anchor-sections: false
reference-location: margin

quarto:
  packages:
    - amsmath


format:
  html:
    theme: 
      - cosmo
    code-fold: true
    code-line-numbers: true
    html-math-method:
        method: mathjax
        url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    toc: true
    toc_depth: 5
    toc-expand: 1
    toc-title: On this page
    toc-location: left
    number-sections: true
    number-depth: 5
    embed-resources: false
    
  pdf:
    documentclass: book
    fontfamily: libertinus
    colorlinks: true
````

Thanks!
