### DISCUSSION TITLE
Change Appendix name in Toc

### DISCUSSION THREAD

**Discussion by vfacta** [quarto-dev/quarto-cli#5522] [Q&A] [answered]
How can I change "Appendices" to something else (such as "Apêndices") in the Toc  of html and pdf outputs?

minimal yml file:

```{yml}
project:
  type: book

book:
  title: "untitled"
  author: "Jane Doe"
  language: "pt"

  chapters:
    - index.qmd

  appendices:
    - ap.qmd
```

**Comment by mcanouil** [comment, marked as answer]
See <https://quarto.org/docs/authoring/language.html#alternate-language>.

````qmd
language:
  section-title-appendices: "Apêndices"
````

**Reply by vfacta** [reply]
Solved! 

`lang` for global changes.

`language`  for specific changes.

None of them are nested:

```
project:
  type: book

lang: pt

book:
  title: "untitled"
  author: "Jane Doe"

  chapters:
    - index.qmd

  appendices:
    - ap.qmd
  ```


or:

```
project:
  type: book

language:
  section-title-appendices: "Apêndices"
  
book:
  title: "untitled"
  author: "Jane Doe"
  
  chapters:
    - index.qmd

  appendices:
    - ap.qmd
```
