### DISCUSSION TITLE
ORCiD in author for blog-posts and links?

### DISCUSSION THREAD

**Discussion by slackline** [quarto-dev/quarto-cli#5558] [Q&A] [answered]
Hi,

Loving how smooth the experience of writing and publishing with Quarto is.

I'm using the blog and have the following in my `_quarto.yaml`

```yaml
author:
  - name: Neil Shephard
    orcid: 0000-0001-8301-6857
```

This results in the ORCiD logo appearing next to the Author on the [front-page](https://ns-rse.github.io), [about](https://ns-rse.github.io/about.html) and [links](https://ns-rse.github.io/links.html) pages but not on any of the actual posts (see [example](https://ns-rse.github.io/posts/sphinx-docs/)). Is it possible to include this on individual posts without adding the information to the YAML header of each file?

I was also curious if its possible to include an ORCiD icon and ilnk in the header of the blog alongside the Twitter/GitHub/GitLab/Mastodon buttons it is possible to include.

I've tried adding the following to `links.qmd` but it hasn't rendered, perhaps because `orcid` isn't a supported ìcon?

```yaml
about:
  links:
    - icon: orcid
      text: ORCiD
      href: https://orcid.org/0000-0001-8301-6857
      rel: me
```
