### DISCUSSION TITLE
\underbrace{}_{} error when rendering PDF

### DISCUSSION THREAD

**Discussion by XinyanYang95** [quarto-dev/quarto-cli#5564] [Q&A] [answered]
The underbrace is rendered weirdly in PDF. But this works for HTML.

```qmd
$$
\underbrace{\phi+3}_{M}
$$
```

```yml
  pdf:
    documentclass: book
    keep-tex: true
    include-in-header: 
      - symboldefinitionspdf.tex
      - text: \usepackage{mathtools}
```
<img width="277" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/55174618/6027bf15-6ff2-4085-b81c-2dc379f27f82">
