### DISCUSSION TITLE
Reveal.js Presentation: Title slide without page number and logo

### DISCUSSION THREAD

**Discussion by mchlbckr** [quarto-dev/quarto-cli#557] [Q&A] [answered]
Hi, I am building a revealjs presentation and have added a background image for my title slide:

```
---
title: "Slideshow"
author: "author"
format:
  revealjs:
    slide-number: c
    show-slide-number: all
    title-slide-attributes:
      data-background-image: img/title.png
      data-background-size: cover
logo: img/logo.png
---

## First slide

blabla

```

Now I would like to remove the page number and the logo from my title slide but keep both on all other slides. Any suggestions how to achieve that?
