### DISCUSSION TITLE
[Quarto R] Add space betweeen authors and date

### DISCUSSION THREAD

**Discussion by caiolivf** [quarto-dev/quarto-cli#5597] [Q&A] [answered]
### Bug description

I would like to add more spacing between author and publication date.

```yaml
---
title: Mesa Limpa
description: Relatório Dinâmico sobre processos abertos do SEI - SETIC
authors: 
  - name: author1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - name: author2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
date: today
format:
  html:
    theme: flatly
lang: pt
title-block-banner: true
server: shiny
---
```
![image](https://github.com/quarto-dev/quarto-cli/assets/106786010/5fca4c20-d745-440e-b086-7819ace75a26)

**Comment by mcanouil** [comment]
My guess, is that you are using HTML format thus needs to use CSS (developer mode of your favourite browser is here to help figure out which classes).

---

Could you share a small "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Reply by caiolivf** [reply]
Hi @mcanouil !

Thanks for answering!

Here's a reproducible example. Note that "author's name" and "date" are very close.

````qmd
---
title: "test"
author: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
date: 01/01/2000
format: html
editor: visual
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).

````

![image](https://github.com/quarto-dev/quarto-cli/assets/106786010/ba221e0b-a773-4de3-a02d-cf3622b31684)

**Reply by mcanouil** [reply, marked as answer]
From the developper mode:
<img width="1505" alt="Screenshot 2023-05-18 at 18 45 14" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/75d08d61-b921-44ab-af60-07e9bc673ed2">

Then you see the CSS that you can modify live, you may also have direct link to documentation (https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns):

```css
#title-block-header.quarto-title-block.default .quarto-title-meta {
  display: grid;
  grid-template-columns: 2fr 1fr;
}
```

<img width="1504" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/67195ef3-0e59-40d3-8a29-9fa3d51fde30">

<details><summary>See Quarto document.</summary>

````qmd
---
title: "test"
author: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
date: 01/01/2000
format: html
include-in-header: 
  - text: |
      <style>
      #title-block-header.quarto-title-block.default .quarto-title-meta {
        display: grid;
        grid-template-columns: 2fr 1fr;
      }
      </style>
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).

````

</details>
