### DISCUSSION TITLE
Section Numbers in Tabs and Table of Contents

### DISCUSSION THREAD

**Discussion by mojave-meow** [quarto-dev/quarto-cli#5612] [Q&A]
Hello. I was wondering if there is a way to include section numbers in the panel-tabset header names. When knitting an R Markdown file, the tabs were automatically labeled with the section number, e.g., "1.1.2 Tab B." However, Quarto does not add these section numbers automatically.

Additionally, when headers get put into tabs, they no longer appear in the table of contents. Is there a way to keep these headers in the table of contents? Thank you!

Example below. When rendered,  `### Lower Header` becomes "2.1.1. Lower Header," and it appears in the table of contents. However, the three tabs are not numbered and do not appear in the table of contents. Thank you!

```
---
title: "ToC and Tab Section Numbers"
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 2
    toc-depth: 3
    toc-title: Contents
    number-sections: true
    number-depth: 3
---

# Section

## Subsection

::: panel-tabset

### Tab A

### Tab B

### Tab C

:::

# Section

## Subsection

### Lower Header
```

**Comment by cderv** [comment]
I believe in Quarto, this is by design the heading in tabset are only use as a mean to simply configure the tabset panel title. They are not processed as header by Pandoc, so no numbering are applied to them. 

In R Markdown the tabset part was done in JS after pandoc processing, and so numbering was indeed shown. 

For the TOC this is the same, tabset panel title are not considered headers to be put in TOC when the TOC is processed. 

This would be feature request to advocate for a change of this behavior IMO

**Reply by mcanouil** [reply]
For what is worth, I don't think tabset should be numbered or part of a table of contents (it what I disliked the most in RMarkdown).

**Comment by cscheid** [comment]
> Additionally, when headers get put into tabs, they no longer appear in the table of contents. Is there a way to keep these headers in the table of contents? Thank you!

Not currently, but I'll take into account for the crossref redesign I'm currently doing. This will never happen by default, since those headers are meant to indicate the titles of the tabs, and are not actually section headers (the same thing happens for callouts). But it might be possible to "force" the header behavior. No promises, but I'll keep it in mind.

**Reply by melaniewalsh** [reply]
I wanted to follow up on this question. Is there a way to include headers within tabs in the ToC in the latest version of quarto? @mojave-meow did you ever figure this out? 

Thank you!

**Reply by cscheid** [reply]
> Is there a way to include headers within tabs in the ToC in the latest version of quarto?

No, there isn't.

**Comment by m-clark** [comment]
This seems related: it appears that while tabs are unnumbered in the html, they are numbered in the pdf, and if they are at a proper depth, they'd be included in the ToC.  I'd actually prefer they not be numbered or included in the ToC regardless of ToC depth, which seems would be consistent with the html. I tried one or two ways to remove the pdf numbering without success. Are there any suggestions for this?  I can create a header depth to get them out of the ToC, but it results in a odd numbering to do so.

Test the [above demo doc](https://github.com/quarto-dev/quarto-cli/discussions/5612#discussion-5213826) by adding the following as one example:

```yaml
  pdf:
    toc: true
    toc-title: 'Contents'
    number-sections: true
```
