### DISCUSSION TITLE
Reveal js presentation : title slide h2 not vertically centered

### DISCUSSION THREAD

**Discussion by ced75** [quarto-dev/quarto-cli#5658] [Q&A] [answered]
Hi,

I have created a reveal.js presentation with Quarto with the following global option:
    slide-level: 3

Since I did that, all my level 2 slides are vertically centered automatically (like level 1 slides).
But there are few level 2 slides in my presentation I do not want to be vertically centered.
How to achieve this?

Thanks in advance for help.

**Comment by mcanouil** [comment]
Could you share a small "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by ced75** [comment]
Thanks for your answer.

Here is an example of reproducible Quarto document :+1: 

````
---
title: "Test Reveal JS title levels"
format: 
  revealjs:
    slide-level: 3
    smaller: false
    self-contained: false
    slide-number: c/t
engine: knitr
---

# LEVEL1


## Level 2

- item 2.1
- item 2.2
- item 2.3
- item 2.4

### Level 3

- item 2.1
- item 2.2
- item 2.3
- item 2.4

## Level 2 on top ?

- item 2.1
- item 2.2

````

What I'm expecting is the top align of text in slide "Level 2 on top", as it is displayed in slide "Level 3".
With the actual code, it is vertically centered.

For the moment, slide "Level 2 on top" inherits of class "center" automatically by Reveal JS. This is related to the fact that slide-level is set to 3.

**Reply by mcanouil** [reply]
The css code block is not valid.
Is it a try?
Please only describe the issue, don't add why you tried into it.

**Comment by ced75** [comment]
OK, I have removed the CSS code block.
It is exactly the same : the "Level 2 on top" slide remains centered vertically.

**Comment by cderv** [comment]
> Since I did that, all my level 2 slides are vertically centered automatically (like level 1 slides).
But there are few level 2 slides in my presentation I do not want to be vertically centered.
How to achieve this?

I don't think you can do that easily with revealjs. The slide level will indicate to revealjs which type of slide to use. 

* Section slides which are vertically centered - these slides get the class `.title-slide` 
* Normal slides which will be top centered. 

Usually you need only two level to structure the slide. Using `##` in your setup will create section slide - so centered. The centering is done by revealjs computing dimension and apply a `top` style at element scope. 

You could use a trick to override this but it does not seem like a good solution, rather something to solve another type of need. Though you can do 
````markdown
---
title: "Test Reveal JS title levels"
format: 
  revealjs:
    slide-level: 3
    smaller: false
    self-contained: false
    slide-number: c/t
    theme: [default, styles.scss]
engine: knitr
---

# LEVEL1


## Level 2

- item 2.1
- item 2.2
- item 2.3
- item 2.4

### Level 3

- item 2.1
- item 2.2
- item 2.3
- item 2.4

## Level 2 on top ? {.top}

- item 2.1
- item 2.2

````

* styles.scss
```scss
/*-- scss:defaults --*/

/*-- scss:rules --*/

.reveal section.top {
  top: 0px !important;
}
```

Really it is a trick but after all it is CSS. 

Why do you set `slide-level: 3` ? I am curious to understand has maybe there is other solutions. 

Are you using `h1`, `h2` and `h3` to get different font size ?
