### DISCUSSION TITLE
Using underscores in links might lead to problems

### DISCUSSION THREAD

**Discussion by anatexis** [quarto-dev/quarto-cli#5679] [Q&A] [answered]
Just an observation, as this is a [pandoc related issue](https://github.com/quarto-dev/quarto-cli/issues/5641#issuecomment-1560107544) and not something quarto can control.

When I put my twitter handle [\_anatexis\_](https://twitter.com/_anatexis\_)[^1] in the navbar in _quarto.yml, it got rendered to https://twitter.com/anatexis (no underscores!). I found a work-around with this:
```
navbar:
    search: true
    right:
        (...)
      - icon: twitter
        href: 'https://twitter.com\_anatexis_'
```
the `\` is translated to `/` **and** the underscores will be displayed. This just works because there is a slash before the underscore. So don't use underscores :smiling_face_with_tear: 

[^1]: I had to escape the underscores and put the link in a markdown link. ` [\_anatexis\_](https://twitter.com/_anatexis\_)` otherwise it would have been rendered wrongly to https://twitter.com/_anatexis_ (second underscore gone in the link)

**Comment by mcanouil** [comment]
Your URL is not valid anyway even for a browser.

This being said, the issue here is that the href value is parsed as markdown, _i.e._ "twitter.com/_anatexis_" (where "anatexis" is italicise), but because it makes no sense in "src" field of a link, the `_` disappear.

**Comment by cderv** [comment]
I believe this is the same issue as 

* https://github.com/quarto-dev/quarto-cli/issues/5503
* https://github.com/quarto-dev/quarto-cli/issues/3493

@dragonstyle we discussed about this is you recall. This is because of our markdown parsing when processing navbar item. 
As we discussed last time, maybe `href` should really be ignore in that processing. What do you think ?

**Comment by mcanouil** [comment]
For the time being, here is a workaround for you to get the desired behaviour.

In `_variables.yml`:

```yml
twitter: "`https://twitter.com/_anatexis_`{=html}"
```

In `_quarto.yml`:

```yml
  navbar:
    right:
      - icon: twitter
        href: "{{< var twitter >}}"
```

**Reply by cderv** [reply]
I think escaping the underscore would work too, no ? 

```yaml
href: https://twitter.com/\_anatexis\_
```

Anyhow, the problem is indeed that we are parsing the `href` as markdown and it requires to escape or mark it as raw when special character in it. 

It has been several reports so maybe we should consider ignore `href` is this markdown processing.... but then all those tricks would break 😅

**Reply by mcanouil** [reply]
No it does not work because at some point in Pandoc or Quarto `\` are then translated to `/`.
Escaping only avoid the underscores to be used as italics tags.

**Reply by cderv** [reply]
Oh interesting. Either another issue or something due to the processing. Thanks for explaining !

**Reply by cscheid** [reply]
> Anyhow, the problem is indeed that we are parsing the href as markdown and it requires to escape or mark it as raw when special character in it.

We have the same general problem in the shortcode processing pipeline when shortcodes are declared in the metadata. Unless I'm missing something, I think that pandoc parses all metadata values as markdown.

I like @mcanouil trick of using a raw block; unfortunately, it requires making a decision about the format. I wonder if we should start teaching something like

```
"`https://twitter.com/_anatexis_`{=quarto_raw_text}"
```

Or some other purposefully "wrong" raw format, which we would then transform to "raw text" in our metadata chain.

**Reply by mcanouil** [reply]
At first I was looking for a "raw" thing, then I realise, you need an actual format.
So, I tend to agree that a discussion about a "quarto raw" format to escape anything might be a good idea in the long run.

**Reply by mcanouil** [reply]
@cscheid Using the raw inline code block directly into `href` leads `localhost` to be prepended to `href` value.

```yml
website:
  navbar:
    left:
      - href: "`https://quarto.org/`{=html}"
        text: Home
```

Will produce `http://localhost:6110/https://quarto.org/`

**Reply by cderv** [reply]
As discussed the website part of YAML config is processed a bit differently than other other fields. We have a processing internally and it is possible that is uses the host to detect local vs remote `href`. By wrapping in raw syntax, you can't do the detection as if it were a string. 

@dragonstyle know more about this pipeline for website envelope

**Reply by cscheid** [reply]
Well, this _might_ work with my

```yml
website:
  navbar:
    left:
      - href: "`https://quarto.org/`{=asis}"
        text: Home
```

proposal. I have an implementation already, I'm going to start testing it.

EDIT: the `asis` inline doesn't solve the problem :(

**Reply by anatexis** [reply]
Thank you @mcanouil, that solves it for me!

**Reply by cscheid** [reply, marked as answer]
@anatexis here's a simpler solution:

```yml
website:
  navbar:
    left:
      - href: "https://twitter.com/`_anatexis_`{=html}"
        text: Home
```

The syntax is a bit ugly, but what's happening here is that we need to tell Pandoc to not process your underlines as Markdown (hence the backticks for a raw inline syntax), but we also need quarto to recognize the URL as a "real URL", and that happens as text, and is a check of the beginning of the string.
