### DISCUSSION TITLE
Profiles with different pdf format settings

### DISCUSSION THREAD

**Discussion by baptiste** [quarto-dev/quarto-cli#5721] [Q&A]
### Description

I'm a bit confused with [project profiles](https://quarto.org/docs/projects/profiles.html): in my use-case I want to switch between:

- a regular `book.cls` class, in the default profile
- the publisher's cursed `Alon.cls` class, to produce the pdf that will go to print, using a `_quarto-alon.yml` profile

I thought the following would do the trick:

**`_quarto.yml`:** (default profile)

```
project:
  type: book
  output-dir: "docs"

book:
  title: "Classy stuff"
  author: "baptiste"
  date: today
  language: "en-NZ"
  chapters:
    - "index.qmd"
    - "01-introduction.qmd"
    - "02-theory.qmd"
    - "03-applications.qmd"

bibliography: references.bib
csl: nature.csl

format:
  pdf:
    template: _tpl.tex
    highlight-style: arrow
  html:
    theme: cosmo
    css: _style.css

engine: knitr
```

**`_quarto-alon.yml`:**

```
project:
  type: book
  output-dir: "_CRC"

book:
  title: "Classy stuff"
  author: "baptiste"
  date: today
  language: "en-NZ"
  chapters:
    - "index.qmd"
    - "01-introduction.qmd"
    - "02-theory.qmd"
    - "03-applications.qmd"

bibliography: references.bib
csl: nature.csl

format:
  pdf:
    documentclass: Alon
    classoption: 11pt, Alon2, singlecolor, a4paper
    mainfont: "Minion 3"
    monofont: "Iosevka Curly Slab"
    monofontoptions: "Scale=0.86"
    linkcolor: black
    highlight-style: bw.theme
    include-after-body:
      text: |
        \printindex
    include-in-header:
       - "_fix-alon.tex"
       - "_packages.tex"
       - "_macros.tex"

engine: knitr
```

To my surprise, the pdf produced in `_CRC` with `quarto render --profile alon` actually used `_tpl.tex` and therefore ignored all the pdf settings in `_quarto-alon.yml`.

I thought the merging of profiles between  the default `_quarto.yml` and `_quarto-alon.yml` would result in the pdf format being overwritten by the one supplied in the profile, rather than the two pdf format options being merged (which I assume is what happens here).

Is this the intended behaviour, and if so, should I adjust my strategy and have the default profile not define any pdf format output? (but that's a bit annoying, since I don't want/need to produce anything else when running `--profile alon`).
