### DISCUSSION TITLE
Multiple authors and affiliations?

### DISCUSSION THREAD

**Discussion by dmbates** [quarto-dev/quarto-cli#573] [Q&A] [answered]
It appears that only one `author:` specification can be given in the YAML.  If I wanted to specify affiliation, etc. for the authors of a book, how would I do that? I can see how this is done for a single author but it is not clear how to handle multiple authors at different institutions

**Comment by dragonstyle** [comment, marked as answer]
What we currently support is relatively limited, though I am working on improving that a lot as we speak. For now, you can provide any number of authors and limited basic information, such as:

```
author:
  - name: Norah Jones
    url: http://norahjones.com
    affiliation: Macalester College
    affiliation-url: https://www.macalester.edu
  - name: Henry Security
    url: http://websiteexample.com
    affiliation: Oberlin College
    affiliation-url: https://www.oberlin.edu
```

This will render authors and affiliations in HTML, the LaTeX only renders author names for the time being. I am working on the ability to provide custom title blocks For HTML and LaTeX which will allow you to provide both more information about authors and affiliations and customize the appearance of that output for various formats.

**Reply by dragonstyle** [reply]
In addition, I should note that you're free to use Pandoc solutions to this problem in the meantime (for example https://github.com/pandoc/lua-filters/tree/master/scholarly-metadata and https://github.com/pandoc/lua-filters/tree/master/author-info-blocks). We just recently fixed an issue that was preventing those from working properly, but they should be fine now... (here is issue for reference https://github.com/quarto-dev/quarto-cli/issues/552).

**Comment by maia-sh** [comment]
Thank you for working on more author affiliation support, @dragonstyle! Just to chime in on this feature request, it would be great to have something that allows for multiple authors to point to the same affiliation, ideally using the format in [{papaja}](http://frederikaust.com/papaja_man/r-markdown-components.html#manuscript-metadata). Also ideally allowing for something along the lines of "These authors contributed equally to this work" (see hack-y solution in papaja example below).

```
---
author: 
  - name          : "First Author"
    affiliation   : "1,*"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2,*"
    role:
      - Writing - Review & Editing

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"
  - id            : "*"
    institution   : "These authors contributed equally to this work"
---
```

**Reply by dragonstyle** [reply]
This is a great suggestion and something that we'll definitely support. It will likely look something like this:

```
author:
  - name: Norah Jones
    url: http://norahjones.com
    affiliations: 
      - ref: mac
      - ref: emory
    orcid: 0000-0003-0174-9868
  - name: Henry Security
    url: http://websiteexample.com
    affiliation: oberlin
    orcid: 0000-0001-8715-9476

affiliations:
  - id: mac
    name: Macalester College
    state: Minnesota
    url: https://www.macalester.edu
  - id: emory
    name: Emory University
    region: Georgia
    url: https://www.emory.edu  
  - id: oberlin
    name: Oberlin College
    url: https://www.oberlin.edu
```



The external affiliations will be optional (you can also just place the affiliations right inline on the authors like so):

```
author:
  - name: Norah Jones
    url: http://norahjones.com
    affiliations: 
      - id: mac
        name: Macalester Collection
        state: Minnesota
        url: https://www.macalester.edu
      - id: emory
        name: Emory University
        region: Georgia
        url: https://www.emory.edu  
    orcid: 0000-0003-0174-9868
  - name: Henry Security
    url: http://websiteexample.com
    affiliation:
      - id: oberlin
        name: Oberlin College
        url: https://www.oberlin.edu
      - ref: mac
    orcid: 0000-0001-8715-9476
```

or you can skip the refs / ids altogether and just place the affiliations with all the fields right inline.

We are definitely contemplating roles and attributes like equal contributor so will have a facility for expressing this as well. Perhaps something like:

```
author:
  name: John Hamm
  corresponding: true
  is-equal-contributor: true
```

We'll normalize all of this to a standard format for templates, so once you express authors and affiliations, it should work properly for any of the templates that we support... I'm making decent progress and hope to have some updates for you soon!
