### DISCUSSION TITLE
How do I make the menu on the left of the page folded by default?

### DISCUSSION THREAD

**Discussion by e05bf027** [quarto-dev/quarto-cli#5747] [Q&A] [answered]
### Description

I am a medical doctor and am creating a document for my hospital to help with preparing patients for operations. There are eight parts and about 40 chapters in total.

I have set the `_quarto.yml` file to give html output. On the left, the sidebar lists the parts and the chapters that make up that part. It is possible to click beside the part and fold up the chapters. I want this to be foklded by default. I have rtied altering the YAML in many ways but it seems to be having no effect. 

Here is the part of the YAML showing the structure of my book that I will render to html site::

```
book:
  downloads: [pdf, epub]
  date: last-modified
  date-format: long
  title: "**Pre-Operative Assessment**"
  chapters:
    - index.qmd 
    - overview.qmd
    - part: background.qmd 
      chapters:
        - aim.qmd
        - goals_philosophy.qmd  
        - policy_statement_purpose.qmd  
        - accountability.qmd   
        # - review_process.qmd  
        - scope.qmd   
        # - workflow.qmd
        - triage_overview.qmd   
    - part: assessment_process.qmd  
      chapters:
        - how_to.qmd   
        - assess_medical.qmd  
        - importance_of_exercise_tolerance.qmd
        - assessing_allergy.qmd
        # - assess_nursing.qmd 
    - part: investigations.qmd
      chapters:
        - standard_investigations.qmd 
        - hba1c.qmd 
        - cardiorespiratory_tests.qmd  
        - ecgs.qmd 
        - chest_xrays.qmd
    - part: scoring_intro.qmd 
      chapters:
        - scoring.qmd
        - sort_scoring.qmd  
    - part: medications.qmd   
      chapters:
        - med_approach.qmd 
        - cardiovasc_meds.qmd   
        - resp_meds.qmd  
        - neuro_sys_meds.qmd   
        - endocrine_meds.qmd  
        - gastro_gu_meds.qmd  
        - immune_meds.qmd
        - chemo_meds.qmd  
        - herbal_meds.qmd   
        - anticoags_regional.qmd 
    - part: specific_circumstances.qmd  
      chapters:
        - timing_cardiac.qmd  
        - implanted_devices.qmd   
        - metalwork.qmd   
        - jehovahs.qmd   
        - active_infection.qmd   
    - part: test_results.qmd  
      chapters:
        - test_approach.qmd
        - vitals.qmd  
        - bloods.qmd 
        - ecg_interpretation.qmd  
    - part: outcome.qmd 
      chapters: 
        - next_steps.qmd  
        - criteria_nurse_clearance.qmd 
        - referrals_process.qmd   
        - fasting.qmd 
    - references.qmd
```

Next is the portion outlining the html:

```
format:
  html:
    theme: minty
    toc: true
    toc-depth: 1
    toc-location: right
    toc-expand: false
    link-external-icon: true
    link-external-newwindow: true
    mainfont: 'Georgia'
    fontsize: '6'
    standalone: true
    smooth-scroll: true
    embed-resources: false
    linestretch: 1.5
```

As mentioned, the contents displays 'unfolded' as in the screenshot. I cannot work out how to make it display as folded by default. I have attached both.

I would love if someone could point me in the right direction!
<img width="247" alt="Screenshot 2023-05-30 at 17 26 43" src="https://github.com/quarto-dev/quarto-cli/assets/62836608/57b48b93-45ae-4fa9-aee9-dea2cdd264a0">
<img width="253" alt="Screenshot 2023-05-30 at 17 26 58" src="https://github.com/quarto-dev/quarto-cli/assets/62836608/c10a13b2-9466-491c-bf87-d27fa3b66d97">

**Comment by dragonstyle** [comment, marked as answer]
You should be able to use `collapse-level` to accomplish this, like:

```yaml
website:
  sidebar:
    collapse-level: 1
```

Really cool to see this use of Quarto - hope this solves your issue!

**Reply by e05bf027** [reply]
I thought you might be interested in the [finished result](https://beaconpreassessment.quarto.pub/pre-op-assessment/) you helped me create. Thank you!

**Reply by bramvandijk88** [reply]
> I thought you might be interested in the [finished result](https://beaconpreassessment.quarto.pub/pre-op-assessment/) you helped me create. Thank you!

I've been trying to recreat this myself, but so far no matter where I put this the side-bar remains expanded. Where am I supposed to put this YAML exactly?

**Reply by mcanouil** [reply]
The option controls how to collapse the headers/menu in the sidebar, not the sidebar itself.
The option is a Project level option as `website` is present. `website` is only valid in `_quarto.yml`.

There are no straight way/option to collapse the sidebar itself, but since it's HTML JavaScript/CSS should work.

**Reply by bramvandijk88** [reply]
But the example posted by the commenter above is exactly what I would like to do: show the highest levels (parts) but not lower levels (chapters/sections).

**Reply by mcanouil** [reply]
edit: I've noticed the OP was a book project but the link is a website project.

It could work to have the option under `book` instead of `website`.

**Reply by bramvandijk88** [reply]
I will try. I put the option under “html” as that’s what I associated with “website”, but maybe that was a bit naive. I’ll post an update if it works.

**Reply by mcanouil** [reply]
From a default book project created with:  `quarto create project book`.

In `_quarto.yml`:

```yml
project:
  type: book

book:
  title: "demo"
  author: "Norah Jones"
  date: "10/22/2024"
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - intro.qmd
    - part: "Summary"
      chapters:
        - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```
