### DISCUSSION TITLE
How to use normalized author metadata in Pandoc template

### DISCUSSION THREAD

**Discussion by rgaiacs** [quarto-dev/quarto-cli#5778] [Q&A] [answered]
### Description

https://quarto.org/docs/journals/authors.html says

> Quarto processes and normalizes the author and affiliation data into the keys described below.
>
> - `author`
> - `authors`
> - `affiliations`
> - `by-author`
> - `by-affiliation`

I expect the keys to be available in Pandoc but, based in the follow example, they are **not**.

Considering the [minimal working example](https://github.com/quarto-dev/quarto-cli/files/11625174/mwe.zip) with `_quarto.yaml` as

```
project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  md:
    template: mytemplate.md
```

`index.qmd` as

```
---
title: MWE
author:   
  - Norah Jones   
  - Bill Gates
---

## Section
This is a simple placeholder for the manuscript's main document.
```

and `mytemplate.md` as

```
$for(by-author)$
- $by-author.name.family$
$endfor$

$body$
```

Executing `quarto render --to md` displays, in the terminal,

```
{ ghContext: { git: true, repo: false } }
pandoc 
  to: >-
    markdown_strict+raw_html+all_symbols_escapable+backtick_code_blocks+fenced_code_blocks+space_in_atx_header+intraword_underscores+lists_without_preceding_blankline+shortcut_reference_links
  output-file: index.md
  template: mytemplate.md
  standalone: true
  default-image-extension: png
  
metadata
  manuscript:
    article: index.qmd
    notebooks:
      - notebook: mytemplate.md
    mecaFile: index-meca.zip
  notebook-preview-options:
    back: true
  title: MWE
  author:
    - Norah Jones
    - Bill Gates
  google-scholar: true
  clear-hidden-classes: none
  remove-hidden: all
  
Output created: _manuscript/index.md
```

and output file contains

```

## Section

This is a simple placeholder for the manuscript’s main document.
```

What am I missing?
