### DISCUSSION TITLE
How do I build my Quarto book as both HTML and PDF?

### DISCUSSION THREAD

**Discussion by bcongelio** [quarto-dev/quarto-cli#5784] [Q&A] [answered]
### Description

Hello - 

I am trying to build my book in both HTML and PDF format.

The HTML version of the book works just fine ([An Introduction to NFL Analytics with R](https://bradcongelio.com/nfl-analytics-with-r-book/)).

However, when I attempt to render the book as PDF, it creates the files and then places them throughout my directory. This is an issue as when I go to push my HTML files, the 'index.pdf' file - for example - is much too large and the push fails.

My `_quarto.yml` file looks like this:
```
project:
  type: book
  output-dir: docs

book:
  title: "An Introduction to NFL Analytics with R"
  author: "Bradley J. Congelio"
  site-url: https://bradcongelio.com/nfl-analytics-with-r-book
  repo-url: https://github.com/bcongelio/nfl-analytics-with-r-book
  repo-branch: origin
  sharing: [twitter, facebook, linkedin]
  publisher: "CRC Press"
  publisher-place: "Boca Raton, FL."
  chapters:
    - index.qmd
    - 01-nfl-analytics-and-r.qmd
    - 02-nfl-analytics-tidyverse.qmd
    - 03-nfl-analytics-functions.qmd
    - 04-nfl-analytics-visualization.qmd
    - 05-nfl-analytics-advanced-methods.qmd
    - references.qmd
  appendices: 
    - a1-nfl-analytics-dictionary.qmd
    - a2-nfl-further-reading.qmd
  google-analytics: "G-0ZLEFZL898"
  search: true
  page-footer: 
    left: |
      NFL Analytics with R was written by Bradley J. Congelio.
    right: |
      This book was built with <a href = "https://quarto.org/">Quarto</a>
bibliography: citations.bib

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    documentclass: krantz
    keep-tex: true
    output-file: pdf-book
```
I was hoping that using `output-file: pdf-book` would cause all the PDF files to be placed in that folder, so I could use `.gitignore` to avoid pushing that entire folder live. 

All this to say: I am very confused about how to handle building and rendering the book in two separate formats and how the structure of the `yml` file is supposed to reflect this.

Any help/advice is greatly appreciated.
