### DISCUSSION TITLE
How to use custom icons?

### DISCUSSION THREAD

**Discussion by netw0rkf10w** [quarto-dev/quarto-cli#5816] [Q&A] [answered]
### Description

Hello,

I have been porting my personal website to Quarto and I'm currently facing an issue.

In the exemple website created by `Quarto: Create Project > Blog Project`, the navigation bar contains a GitHub icon and a Twitter icon. I would like to add a Google Scholar one, but it turns out that this is no obvious because there's no such icon in Bootstrap 5 (which is supported by Quarto).

So what I did is to install the Academicons extension (following http://blog.schochastics.net/post/academicons-my-first-quarto-extension/):

```
quarto install extension quarto-ext/fontawesome
quarto install extension schochastics/academicons
```

then in `_quarto.yml`:

```lml
website:
  title: "blog-quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.fr/citations?user=xxx
```

but the result is very ugly: the added icon is too small and does not have the same color as the existing ones:

<img width="294" alt="Screenshot 2023-06-05 at 16 20 40" src="https://github.com/quarto-dev/quarto-cli/assets/8569515/de308bb6-3564-4faf-8008-7931c156f85b">

Therefore, my question is how to use customs icons (i.e., those not supported by Bootstrap) in Quarto?

Thank you in advance for your help!

**Comment by mcanouil** [comment, marked as answer]
This is likely an issue with the extension you are using and how the icons are added via shortcode.

I personally use the Iconify framework to include icons.
For instance, academicons and font awesome icons are in it.
See <https://github.com/mcanouil/quarto-iconify>.

```yaml

  navbar:
    title: "MCU"
    search: true
    logo: media/logo.svg
    right:
      - text: About
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Projects
        href: projects.qmd
      - text: Talks
        href: talks.qmd
      - text: Publications
        href: publications.qmd
      - text: "{{< iconify fa6-brands mastodon >}}"
        href: "https://fosstodon.org/@MickaelCanouil"
        rel: me
      - text: "{{< iconify fa6-brands twitter >}}"
        href: "https://twitter.com/MickaelCanouil"
      - text: "{{< iconify fa6-brands linkedin >}}"
        href: 'https://www.linkedin.com/in/mickaelcanouil'
      - text: "{{< iconify fa6-brands github >}}"
        href: "https://github.com/mcanouil"
      - text: "{{< iconify fa6-regular heart >}}"
        href: "https://github.com/sponsors/mcanouil?o=esb"
```

If you get the same output with this extension, then the issue is the icon itself, which mean you have to manually style it to fit your needs.
Note that my extension has a size attribute as well as other funny/useful attributes.
