### DISCUSSION TITLE
How do I use modified partials in website ?

### DISCUSSION THREAD

**Discussion by lakonis** [quarto-dev/quarto-cli#5817] [Q&A] [answered]
### Description

I have created a quarto journal template with modified partials (`metadata.html` and `title-block.html`), and i installed this journal template into my website project.

I was hoping to apply this template to certain pages of the website, but the partials are not applied, although the css is working. It seems to be using the default template despite my YAML declaration:

```yaml
---
format:
  mytemplate-html:
    template-partials:
      - metadata.html
      - title-block.html
... 
```

So I am wondering if Quarto allow the use of different template into the same website. And if it is, what is the procedure to create, use et apply a specific template to a specific page of the website. Maybe I misunderstood the principle of journal template ?

For your information, since my Yaml schema is different than the one used by Quarto (the reason why I am trying to apply my own template), I had to add `validate-yaml: false` (see [advice](https://github.com/quarto-dev/quarto-cli/issues/552#issuecomment-1573883976)) in order to render my page.

**Comment by dragonstyle** [comment]
Normally, I would expect the extension itself to register and provide these partials, like:

```yaml
contributes:
  formats:
    html:
      template-partials:
        - metadata.html
        - title-block.html
```

Then users of the extension could simple write:

```yaml
format:
  mytemplate-html: default
```

You may be trying to accomplish something different, but wanted to highlight this in case it is helpful.

**Reply by lakonis** [reply]
Thank you, i tried both indeed but neither is working (meaning: neither is taking my partials into account).

**Reply by cderv** [reply]
@lakonis please do share a git repo with a demo website and your extension so that we can clone and reproduce the issue you are encountering. Thank you !

**Reply by lakonis** [reply]
Here it is. Sorry, it is my first steps with quarto and templating : https://github.com/lakonis/stylo-quarto
I have created a journal template using `quarto create extension journal`, hoping I could use such extension in a website project. Let me know if I did something wrong !

**Reply by lakonis** [reply]
Maybe this repo is not enough for you to debug ? Let me know if I can provide something else. Thanks!

**Reply by dragonstyle** [reply, marked as answer]
In your example repo, I corrected the paths in the `_extension.yml` file to point to the partials:

```yaml
title: Stylo
author: Nicolas Sauret
version: 1.0.0
quarto-required: ">=1.4.0"
contributes:
  formats:
    common:
      toc: true
      filters:
        - stylo.lua
    pdf:
      include-in-header: header.tex
    html:
      template-partials:
        - partials/metadata.html
        - partials/title-block.html
      css: styles.css
```

then in the `template.qmd` file I simplified the format:

```yaml
---
title: Stylo Template
format:
  stylo-pdf:
    keep-tex: true  
  stylo-html: default
...
---
```

and finally I run the command as follows to preview using the `style-html` format:

`quarto preview template.qmd --to stylo-html`

and all appears to be working. HTH!
