### DISCUSSION TITLE
Globally define open-graph and twitter-card fallback-defaults

### DISCUSSION THREAD

**Discussion by gadenbuie** [quarto-dev/quarto-cli#5865] [Feature Requests]
### Description

Currently, if you have `description` or `image` set in `open-graph` and `twitter-card` in the `_quarto.yml` for a website project, these become the primary description for any link in the website.

```yaml
# _quarto.yml
website:
  open-graph:
    description: A default description about this project
    image: https://example.com/my-website-logo.png
  twitter-card:
    description: A default description about this project
    image: https://example.com/my-website-logo.png
```

This is helpful in a very large website, especially one that has been migrated from another static site generator to Quarto. 

But setting these values in `_quarto.yml` introduces the problem that these values are **preferred over the normal lookup procedure for post-specific values**. In other words, if these values are not set, quarto will pick up `image` and `description` from the appropriate places in post.

To correct this in the post, you need to repeat your image and description 3 times (or use super advanced YAML features):

```yaml
title: My Post
description: A blog post about something
image: feature.png

open-graph:
  description: A blog post about something
  image: feature.png
twitter-card:
  description: A blog post about something
  image: feature.png
```

What I'd really like is for the `open-graph` and `twitter-card` fields in `_quarto.yml` to be used last rather than first in the lookup. I'm having a hard time thinking of a situation in which someone would _want_ the post-specific image and description to be overwritten, so I'm inclined to think it's okay to break existing behavior, at least for these fields. 

If changing current behavior isn't possible, it'd be helpful to ensure `image` and `description` at the `website` level are used as the final fallback value, e.g. 

```yaml
website:
  description: A default description about this project
  image: https://example.com/my-website-logo.png
```
