### DISCUSSION TITLE
How to set a group of custom default options?

### DISCUSSION THREAD

**Discussion by pipme** [quarto-dev/quarto-cli#5903] [Q&A]
### Description

In a `qmd` file we specify the format as below:
```qmd
format:
  html: default
  pdf:
    toc: false
    cite-method: biblatex
```

My question is, can we instead specify with:
```qmd
format:
  html: default
  pdf: custom-pdf
```
where `custom-pdf` is defined in `_metadata.yml` like:
```yaml
custom-pdf:
    toc: false
    cite-method: biblatex
```

**Comment by cderv** [comment]
I think best way would be to define a custom format as Extension to use with your projects.  See more at https://quarto.org/docs/extensions/formats.html

You can use extension several ways: https://quarto.org/docs/extensions/managing.html and distribute them also several ways https://quarto.org/docs/extensions/distributing.html

**Comment by pipme** [comment]
Thanks. I tried a bit but weirdly it seems not working for `toc: false` but working for `number-sections: true`. Not sure if it's a bug or some mistakes from my side. My quarto version is 1.3.361.

The procedure I followed was:
* set up the extension via `quarto create extension format:pdf` with extension name `custompdf` 
* install it by running `quarto add custompdf`. 

The `_extension.yml` is:
```
title: Custompdf
author: pipme
version: 1.0.0
quarto-required: ">=1.3.0"
contributes:
  formats:
    pdf:
      toc: false
      number-sections: true
      include-in-header: header.tex
```

Also I don't quite like the suffix in the output. Just `pdf` would be better :D
![image](https://github.com/quarto-dev/quarto-cli/assets/30783979/58d1b3a4-f8c1-4a36-bb26-cf75d385e58a)
