### DISCUSSION TITLE
How to change the tippy style for code annotations?

### DISCUSSION THREAD

**Discussion by muellerzr** [quarto-dev/quarto-cli#5976] [Q&A] [answered]
### Description

I've modified my css to achieve the following:

![image](https://github.com/quarto-dev/quarto-cli/assets/7831895/e91aa618-c472-4daf-8a69-6deca8650ffe)

via:

```css
code.sourceCode .code-annotation-anchor {
   margin-top: 2px;
   margin-left: 2px;
   left: -12px;
   position: absolute;
}

.sourceCode > .python {
   padding-left: 1em;
}
```
But it'd be *really* nice if there were a way to change the tippy style so that it can be on the left, not the right and actually work with the CSS. (and not cover the code!) In all my digging of the HTML being used, I couldn't find where to modify it at. Where does quarto set the style that it uses for tippy? Even if I have to manually modify it for the time being until Quarto supports something like this, it'd be wonderful if I could be shown how.
