### DISCUSSION TITLE
Where does 'resources:' go and what is the format of the value for a book in html?

### DISCUSSION THREAD

**Discussion by bryanhanson** [quarto-dev/quarto-cli#5986] [Q&A] [answered]
### Description

My question is for a book project in html format, what is the correct place to specify a path to a folder containing images?  And how do we give that path, is it quoted or not?  I don't see any examples in the documentation, but the option is mentioned [here](https://quarto.org/docs/reference/projects/books.html#project).

Related issues/discussion are https://github.com/quarto-dev/quarto-cli/issues/5084 which doesn't seem to apply to books as `resource-path:` is not (apparently) not used with books, and https://github.com/quarto-dev/quarto-cli/discussions/3763 which might have never been resolved.

Specifically, in `_quarto.yml` do we do

```
project:
  type: book
  resources: imgs # or /imgs?
```

or 

```
project:
  type: book
  resources: "imgs" # or "/imgs"?
```
or does the option belong at the same level as "projects"?  Note that https://github.com/quarto-dev/quarto-cli/discussions/3763 uses both positions with varying degrees of success.

```
project:
  type: book

resources: imgs # or /imgs etc?
```

In my experimentation none of these seem to work (no errors during previewing until one navigates to a page with an image stored in `/imgs` and then it's not found.  So I fully expect the answer is "none of the above silly..."

Testing with the latest version obtained yesterday by`git pull` and then `./configure.sh`.

**Comment by mcanouil** [comment]
See <https://quarto.org/docs/websites/website-tools.html#site-resources>.

"References" pages are basically the list of "all" the options".
"Guide" pages contain examples, tutorials, etc.

**Reply by bryanhanson** [reply]
Thanks.  Can you look at this example created by `quarto create-project --type book` followed by moving `cover.png` to a new folder `imgs`?  I think I'm doing what the instructions say, but the image 404s.

[test-book.zip](https://github.com/quarto-dev/quarto-cli/files/11805900/test-book.zip)

**Reply by dragonstyle** [reply, marked as answer]
I think the path to the image itself is wrong. With this `_quarto.yml` it should work without the explicitly included `resources`:

```yaml
project:
  type: book

book:
  title: "test-book"
  author: "Norah Jones"
  date: "6/20/2023"
  image: imgs/cover.png # < note the corrected path
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo


```
