### DISCUSSION TITLE
How do I restart the numbering from 1 in each chapter?

### DISCUSSION THREAD

**Discussion by kangning0125** [quarto-dev/quarto-cli#5987] [Q&A]
### Description

I'm creating a book and would like to reset the numbering of headers in each chapter.

_quarto.yml
```
book:
  title: "My Book 1"
  date: "6/15/2023"
  chapters:
    - index.qmd
    - part: "Book Part 1"
      chapters:
      - 01_model_policy.qmd
      - 02_model_standard.qmd
    - part: "Book Part 2"
      chapters:
      - 2023_bulletins.qmd
      - 2022_bulletins.qmd
```
Within each chapter, I have a set of level 1 headers and level 2 headers. How can I let the level 1 header restart at 1 in each chapter?
