### DISCUSSION TITLE
quarto how to use tabset pills

### DISCUSSION THREAD

**Discussion by Liripo** [quarto-dev/quarto-cli#5991] [Q&A]
### Description

When I try to use it like this, there are some extra borders around.
```qmd
---
format:
  html
---

::: {.nav-pills}
::: {.panel-tabset}

## Summary

message

## Analysis

message

:::
:::
```
![image](https://github.com/quarto-dev/quarto-cli/assets/54770415/84b84ccf-8e09-4d62-b467-6c147c4fcee2)

**Comment by mcanouil** [comment]
You need to add the class to the same div as the tabset.

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr>
<td>

````qmd
---
format: html
---

::: {.panel-tabset .nav-pills}

## Summary

message

## Analysis

message

:::
````

</td>
<td>
<img width="578" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/e85da931-4e55-4eed-a03f-c497551290ac">
</td>
</tr>
</table>

Although I don't quite understand what you call "extra border", see below.

<table>
<tr><th>Default</th><th>Pills</th></tr>
<tr>
<td>
<img width="579" alt="Screenshot 2023-06-23 at 22 21 53" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/347ccf06-4996-4cca-85df-06a375360bc9">
</td>
<td>
<img width="579" alt="Screenshot 2023-06-23 at 22 22 00" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/91381811-728a-4787-9b3d-610b926c2d1b">
</td>
</tr>
</table>

If you wish to remove the panel border:

<table>
<tr><th>Default</th><th>Pills</th></tr>
<tr>
<td>

````qmd
---
format: html
include-in-header:
  - text: |
      <style>
      .panel-tabset > .nav-tabs,
      .panel-tabset > .tab-content {
        border: none;
      }
      </style>
---

::: {.panel-tabset .nav-pills}

## Summary

message

## Analysis

message

:::
````

</td>
<td>
<img width="579" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c2c8240a-c828-4f0c-b823-58248e8c59db">
</td>
</tr>
</table>

**Reply by Walser52** [reply]
This doesn't work for revealjs slides. Any idea how to go about it in that case?

**Reply by cderv** [reply]
`.nav-pills` is Bootstrap feature: https://getbootstrap.com/docs/5.0/components/navs-tabs/#pills

It works for HTML based document because they have Bootstrap. 

For revealjs - no bootstrap. So it does not work.

**Reply by mcanouil** [reply]
Note that you could manually import Bootstrap but you'll have to deal with possible (S)CSS conflicts yourself.

**Reply by Walser52** [reply]
Can't seem to get it to work. Just for clarity, I downloaded the bootstrap css files from [here](https://getbootstrap.com/docs/5.3/getting-started/download/) and copied `bootstrap.css` into my presentation folder.  

This is my yaml header and code. 

```
---
title: "Getting pills"
format:
    revealjs:
        width: 1600
        height: 900
        margin: 0.1
        theme: [default, style.scss]
        incremental: TRUE
        auto-animate-easing: ease-in-out
        auto-animate-unmatched: false
        auto-animate-duration: 1.5   
        css: bootstrap.css
        transition: convex
        background-transition: fade
editor: visual
---

## Pills Tabset

::: {.panel-tabset .nav-pills}

### Tab A

Content for `Tab A`

### Tab B

Content for `Tab B`

:::

```

![image](https://github.com/quarto-dev/quarto-cli/assets/101308173/138ad983-84fc-47fc-a541-dd1219169404)

**Reply by mcanouil** [reply]
It can't work if you don't tell Quarto to use the file.
Check the documentation to see how to use CSS/SCSS.

**Reply by Walser52** [reply]
I'm sorry if I'm missing something but the yaml does have the line `css:bootstrap.css`. Isn't that what you're supposed to do?

**Reply by mcanouil** [reply]
My bad, I did not expect it in the middle and far from `theme` key.
Note that this is exactly why we ask for small reproducible example and not example with dozens of unrelated options.

```yaml
title: "Getting pills"
format:
  revealjs:
    css: bootstrap.css
```

See a related discussion: https://github.com/quarto-dev/quarto-cli/discussions/7356

Note that if Bootstrap is not a dependency or Reveal.js it means it is up to you to handle the issues that comes with including it yourself.

> you'll have to deal with possible (S)CSS conflicts yourself.
