### DISCUSSION TITLE
Wrap Execution Output

### DISCUSSION THREAD

**Discussion by betanalpha** [quarto-dev/quarto-cli#6017] [Q&A] [answered]
### Description

When rendering on my machine configuration options like `code-overflow: wrap` ensure that long lines of code in a code block are wrapped, but they don't seem to have any affect on the rendered output when those blocks are executed.  Instead the long output lines end up wrapped in a slider bar in HTML or truncated for PDF formats.

Is there anyway to force the rendered output to wrap to the screen length (or even a default max width) like the input code blocks?  Apologies if I'm missing an obvious configuration.

Thanks!

**Comment by mcanouil** [comment, marked as answer]
For PDF, see:

- #4121

---

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Reply by betanalpha** [reply]
Great thanks.  I think that discussion addresses my question in the negative, for understandable reasons.  Just happy that I wasn't missing an obvious configuration.

**Reply by mcanouil** [reply]
Not necessarily a negative answer, but you did not provide a concrete example showing how you extension expected the option to work.

**Comment by betanalpha** [comment]
Apologies -- I made the naive mistake thinking that the request may have been boilerplate given the discussion in the link.  To avoid any confusion I threw together a minimal example.


First we have the markdown file, note the long continuous line of code:
````
---
title: "Test"
highlight: pygments
format:
  html:
    code-overflow: wrap
  pdf:
    code-overflow: wrap
knitr:
  opts_chunk:
    comment: ''
format-links: false
---

```{r}
cat('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
```

````

Rendering with `quarto render test.qmd --to html,pdf` using Quarto 1.3.191 gives HTML and PDF outputs as expected.  The HTML output wraps the source code appropriately but not the output, instead putting everything on one line with a scroll bar.

<img width="789" alt="html_output" src="https://github.com/quarto-dev/quarto-cli/assets/1527190/59aa2872-d364-4354-b241-5efd8246d4ff">

The PDF output doesn't wrap either the source or the output.

<img width="1124" alt="pdf_output" src="https://github.com/quarto-dev/quarto-cli/assets/1527190/856dc3dd-baef-4c35-9ecc-1d5050b97023">

I was hoping to have both input and output wrapped, similar to the output in the RStudio console.

<img width="919" alt="rstudio_output" src="https://github.com/quarto-dev/quarto-cli/assets/1527190/57b1a273-18fa-4b6d-a1d3-f9b0f6b477a7">

Naively I thought that the TeX configuration would be rigid enough for the rendered code width to be known and hence any text in input/output blocks automatically wrappable but I appreciate that this could be much more complicated in practice.
