### DISCUSSION TITLE
References at top level in TOC after appendices

### DISCUSSION THREAD

**Discussion by fredzenker** [quarto-dev/quarto-cli#6019] [Q&A]
### Description

Thanks for your awesome work on this project! I am writing a thesis in Quarto, and I am currently having trouble getting the references to print after the appendices while still being listed as a top-level heading in the table of contents (TOC).

First, I tried this in the _quarto.yml file of my Quarto book project:
```
project:
  type: book
book:
  title: ""
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
  appendices: 
    - appendices.qmd
    - references.qmd # I put the references here
bibliography: references.bib
csl: apa.csl
toc: true
format:
  pdf:
    documentclass: report
```
The references were printed after the appendices, but they were included in the TOC as a final appendix (only obvious when looking at the "document outline" pane in the pdf output).

Then I tried this:
```
project:
  type: book
book:
  title: ""
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
  appendices: 
    - appendices.qmd
  references: references.qmd # I put the references here
bibliography: references.bib
csl: apa.csl
toc: true
format:
  pdf:
    documentclass: report
```
Although the references were included as a top-level heading in the TOC/document outline this time, they were also printed before the appendices (which is undesirable for me).

The contents of references.qmd are as follows:
```
# References {.unnumbered}

::: {#refs}
:::
```

Is there anything I can do in the _quarto.yml file or elsewhere to achieve the desired result?

BTW, the same question has been asked before on the following page (but as far as I can tell it was never fully answered either there or here in the GitHub discussions): https://community.rstudio.com/t/quarto-references-chapter-section-at-top-level-in-toc-after-appendices/144332

Thank you for your assistance with this.
