### DISCUSSION TITLE
Reveal.js Presentation: how to change background for one slide?

### DISCUSSION THREAD

**Discussion by aborruso** [quarto-dev/quarto-cli#603] [Q&A] [answered]
Hi,
I have the below hello world code. I use the black theme.

If I apply `{background-color="#006dae"}` to a slide I have it always in black. How to change background for one slide?

Thank you

```
---
title: "🧮 A title"
author: "me"
format:
  revealjs:
    theme: dark
    auto-stretch: false
    center: true
    footer: "A title"
    transition: fade
    fig-responsive: true
    slide-number: true
    navigation-mode: vertical
    slide-level: 0
    hash-type: number
---

# Hello {background-color="#006dae"}

World

---

# Lorem ipsum
```

**Comment by cderv** [comment, marked as answer]
This is the correct way to add it: `{background-color="#006dae"}` needs to be added on the section levels. 

However, you are using `slide-level: 0` and this makes only `---` structure your slideshow and create the section. Unfortunately attributes can't be added on horizontal rule - this is a limit from Pandoc. So if you want to set attributes on slides, you should be using headers to structure the slides, and you can use empty header if you don't want title on a slide. 

If you remove `slide-level: 0`, you should get the correct color. 

Is there any specific reason for  `slide-level: 0` usage here ?

**Reply by aborruso** [reply]
Thank you

> Is there any specific reason for `slide-level: 0` usage here ?

I use in my real slide `slide-level: 0`, because using headers only, I can't always figure out how to create vertical sections and horizontal sections. I would like to have an hello world example that mix horizontal and vertical slides using only headers.

**Reply by cderv** [reply]
Did you try this already ? https://quarto.org/docs/presentations/revealjs/advanced.html#vertical-slides
````yaml
format:
  revealjs:
    navigation-mode: vertical
````
