### DISCUSSION TITLE
How to access variables from _quarto.yml inside index.qmd?

### DISCUSSION THREAD

**Discussion by dense-set** [quarto-dev/quarto-cli#6047] [Q&A] [answered]
### Description

I create a fresh Quarto Website project, and edit `_quarto.yml` so that it looks like:

````yml
project:
  type: website

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

description-meta: "description"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

````

I try to access the `$description-meta` variable from the `index.qmd` file, which looks like so:

````qmd
---
title: "Website"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

{{< meta description-meta >}}
````

However, this gives the following preview:
<img width="703" alt="Screenshot 2023-06-28 at 6 23 29 PM" src="https://github.com/quarto-dev/quarto-cli/assets/102873841/83f6d183-8150-4ef4-9ebf-f8af8b6c30c8">

**Question:** What is going on here? Are `meta` variables not shared across pages?
