### DISCUSSION TITLE
Not able to dereference using the dot (.) delimiter

### DISCUSSION THREAD

**Discussion by dense-set** [quarto-dev/quarto-cli#6049] [Q&A]
### Description

In creating a website project, my `_quarto.yml` file looks like so:
````yml
project:
  type: website

website:
  title: "website title"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
````

And my `index.qmd` file is this:
````qmd
---
title: "index title"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

{{< meta website.title >}}
````

However, the output I get is this:
<img width="610" alt="Screenshot 2023-06-28 at 7 51 13 PM" src="https://github.com/quarto-dev/quarto-cli/assets/102873841/83361bda-09fe-4840-8012-951268598128">

**Question:** I was expecting "website title" to be there instead of "index title" (according to the Quarto documentation [here](https://quarto.org/docs/authoring/variables.html#meta)). So, what is happening?
