### DISCUSSION TITLE
The styling is different in local development versus published to Github Pages.

### DISCUSSION THREAD

**Discussion by thegilpatrick** [quarto-dev/quarto-cli#6059] [Q&A] [answered]
### Description

Here is my [Blog's repository](https://github.com/thegilpatrick/Blog). 

This is my local development view with `quarto preview`. Quarto Version 1.4.176
![Local screenshot](https://github.com/quarto-dev/quarto-cli/assets/61705820/f4024c3b-f40e-413f-bf61-a58b9737c0e7)

As you can see the blog listings are centered on the page. 

Below is a picture of my email newsletter form in local development. It has a gray button and it is centered.
![local_email](https://github.com/quarto-dev/quarto-cli/assets/61705820/2c7a5521-4fd1-41fc-8f3d-a40c276ba7f5)

Below is the view when you go to my [blog](https://thegilpatrick.com/) hosted on Github Pages with the same QMD and CSS files. It is off center to the left.
![Github_Pages](https://github.com/quarto-dev/quarto-cli/assets/61705820/2a6b265a-9a18-4e6f-a28d-b21c58664ae8)

Below is the picture of my email newsletter form it is off center to the left and the button is white and off in alignment with the text box.

![Github_Pages_Email](https://github.com/quarto-dev/quarto-cli/assets/61705820/3d1aa0f1-d211-4767-8a54-60abefecda46)

I am not sure what is going on here.

**Comment by cscheid** [comment]
You could try inspecting the elements in the developer tools of your browser, specifically to look at the list of computed styles.

**Reply by cscheid** [reply]
This is the source of your problem right here:

<img width="2520" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/8e8eda29-253d-4e82-a5b2-75cd2e06f9db">

Specifically this comes from `subscribe.html`:

```
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
```

It seems that the `mc-validate.js` script needs to know how to resolve the CSS from HTTPS.

**Reply by thegilpatrick** [reply]
Thank you! This fixes my email subscription input form. 

But somehow the alignment of the page is still off to the left? When I inspect it with my mouse it looks like when it is published to Github Pages it has extra margins to the right?

![github_pages_inspect](https://github.com/quarto-dev/quarto-cli/assets/61705820/61515540-9954-40c5-b6db-a6f0544cb2ff)

Below is the local version.

![local_inspect](https://github.com/quarto-dev/quarto-cli/assets/61705820/cfe5ea18-b966-4247-8ca5-683edc741c6e)

**Reply by cscheid** [reply]
@jjallaire I think our preview server is doing something wonky here. I can't quite figure out what's happening, but I do see different layouts when running under `quarto preview` vs. running `quarto render` and looking at the files from a static local server.

@thegilpatrick with that said, when I run your site through a local static server (such as `python -m http.server`), then I see the "wrong" alignment on the columns, same as what's on https://thegilpatrick.com/.

**Reply by jjallaire** [reply]
The lack of an https prefix on the script will result in it using http, perhaps add the https prefix?

**Reply by dragonstyle** [reply, marked as answer]
I think that the issue is that the 'grid' isn't a per page option - there is a shared grid for the entire website. When it is placed on a page like this and served with the preview server, the local, individual page render will override the grid and appear fine in the preview (it's basically 'last page wins'). When rendered or deployed, however, it will use a shared grid definition provided by the site (from the `website` key).

If you have other pages that use the grid layout (and so don't want to set the sizes globally to 0px), you can use article layout to position the listing across the columns, like:

```
---
title: The Gilpatrick
listing:
  id: posts
  page-size: 6
  contents: posts
  sort: "date desc"
  type: grid
  categories: true
  sort-ui: true
  filter-ui: true
  feed: true
  fields: [image, date, title, author, description, categories, reading-time]
format:
  html:
    css: no-title.css
---

:::{#posts .column-page-inset}

:::
```

(more about available options here<https://quarto.org/docs/authoring/article-layout.html#overflowing-content>).

Alternatively, you could move that grid definition under your `website` key in `_quarto.yml` and it will control the grid for the whole website.

HTH

**Reply by dragonstyle** [reply]
Note - this is made complicated by the fact that the grid _is_ allowed in a standalone HTML page (above I said it wasn't allowed per page, but it really isn't allowed per page of a website or book), it's just that in the case of a website or blog, it will ultimately use the grid defined by the containing site.

**Reply by thegilpatrick** [reply]
Hey @dragonstyle when I change the grid layout in the `website` key in `_quarto.yml` it messes with my table of contents in my left margin of my blog posts.
Here is an example:
![blog-post-example](https://github.com/quarto-dev/quarto-cli/assets/61705820/c2cad31d-47a3-4b0c-a180-86639f43c68c)


I tried your suggestion for `index.qmd` and it is still not centering the grid?
```
---
title: The Gilpatrick
listing:
  page-size: 6
  contents: posts
  sort: "date desc"
  type: grid
  categories: true
  sort-ui: true
  filter-ui: true
  feed: true
  fields: [image, date, title, author, description, categories, reading-time]
page-layout: full
format:
  html:
    css: no-title.css
---

:::{#posts .column-page-inset}

:::
```
Produces this:
![column-page-inset](https://github.com/quarto-dev/quarto-cli/assets/61705820/fd60307c-c2c7-4509-8775-4c38b5d6105f)

**Reply by thegilpatrick** [reply]
I changed the index.qmd to

```
---
title: The Gilpatrick
listing:
  page-size: 6
  contents: posts
  sort: "date desc"
  type: grid
  categories: false
  sort-ui: true
  filter-ui: true
  feed: true
  fields: [image, date, title, author, description, categories, reading-time]
page-layout: article
format:
  html:
    css: no-title.css
---

:::{#posts .column-page-inset}

:::
```
and it worked. Basically just had to do `categories: false` to get rid of the sidebar I was hiding in the css.
