### DISCUSSION TITLE
Got a gap between consecutive outputs of a cell

### DISCUSSION THREAD

**Discussion by hopezh** [quarto-dev/quarto-cli#6066] [Q&A]
### Description

In the example `quarto` book [here](https://oat.quarto.pub/pytorch-tutorial/quickstart.html), I got a gap between consecutive outputs of a `pytorch` training session.

I did some test, and it seems that it's not related to the `print()` used in the code. 

May I ask what might be causing this display issue? 

(I also asked the question [here](https://forums.fast.ai/t/quarto-render-options-jupyter-notebook-python-code-cell/104690/6?u=oat) on the `fast.ai` forum.)

![35909931e7937df57901cd0930797902404b2abf_2_794x1000](https://github.com/quarto-dev/quarto-cli/assets/23435810/c300d913-aa44-424e-9228-7864cf24b11f)

The `style.css` I used is:
```css
.cell-output pre {
    margin-left:             0em;
    margin-top:              0em;
    /* background:              #303030; */
    background:              rgba(200, 200, 200, 0.1);
    border-left:             35px solid rgba(200, 200, 200, 0.1);
    border-top-left-radius:  0;
    border-top-right-radius: 0;
    /* font-size:               0.8em; */
    /* padding-left:            0.em; */
    /* padding-top:             0.em; */
}

.cell-output .sourceCode {
    background: none;
    margin-top: 0;
}

.cell > .sourceCode {
    margin-bottom: 0em;
    /* font-size:     0.875em; */
}
```
