### DISCUSSION TITLE
Not able to use Iconify icons in the navbar

### DISCUSSION THREAD

**Discussion by dense-set** [quarto-dev/quarto-cli#6078] [Q&A] [answered]
### Description

I installed @mcanouil's [iconify](https://github.com/mcanouil/quarto-iconify) extension so that I could use the [StackExchange icon](https://icon-sets.iconify.design/mdi/stackexchange/) in my navbar. Though I am able to use that in the `index.qmd` file using the shortcode `{{< iconify mdi stackexchange >}}`, I am not able to use it as a Nav item icon via this code:

```yml
website:
  navbar:
    right:
      -icon: "{{< iconify mdi stackexchange >}}"
```
