### DISCUSSION TITLE
How do I implement citations properly?

### DISCUSSION THREAD

**Discussion by Gewerd-Strauss** [quarto-dev/quarto-cli#6090] [Q&A]
### Description

Hello,

I am slowly loosing my mind, because this makes zero sense to me.

Assume the following file

````qmd
---
author: g s
bibliography: "D:/Dokumente neu/Zotero_Papers/Zotero_papers_autosync.bib"
cite-method: citeproc
creation date: 2023-07-02 09:26
csl: "D:/Dokumente neu/Obsidian NoteTaking/The Universe/003 PandocAssets/Citationstyles/cite-them-right-12th-edition-Harvard.csl"
cssclass: clean-embeds, writing
modification date: 2023-07-02 22:01
---

cite-method: citeproc

---

```{dot}
digraph G {
  start [shape=Mdiamond,color=red,bgcolor=red,style=filled];
  subgraph cluster_0 {
    color=red
    bgcolor=violet
    node [style=filled,color=white];
    a0 -> a1 -> a2 -> a3;
    label = "process #1";
  }

  subgraph cluster_1 {
    node [style=filled];
    b0 -> b1 -> b2 -> b3;
    b0 -> a3
    label = "process #2";
    color=yellow
    bgcolor="red"
  }
  end [shape=Msquare,color=green,style=filled];
  
  
  start -> a0;
  start -> b0;
  a1 -> b3;
  b2 -> a3;
  a3 -> b0
  a3 -> a0;
  a3 -> end;
  b3 -> end;
    
}
```


```{r}
#| label: fig-mtcars
#| fig-cap: "MPG vs horsepower, colored by transmission."
#| column: margin

library(ggplot2)
mtcars2 <- mtcars
mtcars2$am <- factor(
  mtcars$am, labels = c('automatic', 'manual')
)
ggplot(mtcars2, aes(hp, mpg, color = am)) +
  geom_point() +  geom_smooth(formula = y ~ x, method = "loess") +
  theme(legend.position = 'bottom')
```


# Methods

## Choosing a sequence

## BLAST Algorithm

Blast [@altschul2001blast] (Basic Local Alignment Search Tool) is an alignment algorithm frequently used for determining small, local alignments between a query-sequence and dife one letter after each word is created.  
It is pretty nice, right[^1]  

## Protein Secondary Structure Predictions

For the initial sequence _ID6400_, several predictions were performed:

### Amino acid composition

### Secondary structure

age [PredictProtein.org](https://predictprotein.org) [@Bernhofer2021.02.23.432527] was used. As there are no , see "[2.2.1 Amino acid composition ]".

### Prediction of Hydropathicity via Kyte-Dolittle

_Kyte-Dolittle_-scale [@kyte1982simple] of [Expasy's ProtScale](https://web.expasy.org/cgi-bin/protscale/protscale.pl) [@gasteiger2005protein]. The scale was not normalised. Positive values indicate hydrophobic regions, negative ones indicate hydrophilic regions.

### Coiled Coil Prediction

The presence of coiled coils can be determined using the COILS-program [@lupas1991predicting] at [Expasy](https://www.expasy.org/resources/coils)  
([Direct Link](https://embnet.vital-it.ch/software/COILS_form.html)).  

## Protein Domain Determination

PFAM [@10.1093/nar/gkaa913] is a library of protein domains and libraries.  

## Secondary structure comparison vs similarly structured proteins

In order to determine and compare the secondary structure of the chosen sequence with similarly structured proteins, a blastp-search [@altschul2001blast] was performed with the _ID6400_form secondary structure predictions as explained in "[2.2 Protein Secondary Structure Predictions ]", and those predictions were compared to the one created for _ID6400_.

## Similar sequences using BLAST

The _blastp_-suite [@altschul2001blast] was user to [2.1 BLAST Algorithm ].

The results were sorted after _percen

## Multiple-Sequence alignments

The mult [@PMID:30976793]. Default settings were applied (cf. below), the output format was set to FASTA.  

## Phylogenetic Tree

A phylogenetic tree was constructed between the sequences used in the MSA performed in step 6 (cf. [2.6 Multiple-Sequence alignments ]) using the [_Clustal Omega_](https://www.ebi.ac.uk/Tools/msa/clustalo/)-web interface [@PMID:30976793], during the creation of the MSA.

[^1]: And let there be a footnote here. DUDUDUUUh

````

And the following rscript being run for compilation:

```R
getwd()
if (getwd() != "C:/Users/Claudius Main/Desktop/TempTemporal/Graphviz Playground")
{
setwd("C:\\Users\\Claudius Main\\Desktop\\TempTemporal\\Graphviz Playground")
getwd()
}
getwd()
sprintf('Chosen Output formats:')
sprintf('quarto::html')
sprintf('bookdown::html_document2')

version

rmarkdown::render("index.rmd",bookdown::html_document2(
df_print = "kable",
fig_caption = TRUE,
fig_height = 6,
fig_width = 8,
global_numbering = TRUE,
highlight = "tango",
keep_md = FALSE,
number_sections = TRUE,
pandoc_args = ,
toc = TRUE,
toc_depth = 5,
toc_float = TRUE
),"Graphviz Playground (bookdown)")


yaml::write_yaml(list('citation-location' = "margin",
'code-fold' = "true",
df_print = "kable",
'email-obfuscation' = "none",
'fig-cap-location' = "margin",
'fig-height' = 6,
'fig-title' = "Figure",
'fig-width' = 8,
'number-depth' = 99,
'number-sections' = TRUE,
'reference-location' = "margin",
'tbl-cap-location' = "margin",
toc = TRUE,
'toc-depth' = 5,
'toc-location' = "right",
'toc-title' = "Table of Contents"),"C:/Users/Claudius Main/Desktop/TempTemporal/Graphviz Playground/yaml_html.yaml")

yaml_content <- readLines("C:/Users/Claudius Main/Desktop/TempTemporal/Graphviz Playground/yaml_html.yaml")
yaml_content <- stringr::str_replace(yaml_content,": no\"",": FALSE\"")
yaml_content <- stringr::str_replace(yaml_content,": yes\"",": TRUE\"")
yaml_content <- stringr::str_replace(yaml_content,": no\"",": FALSE\"")
yaml_content <- stringr::str_replace(yaml_content,": yes",": TRUE")
yaml_content <- stringr::str_replace(yaml_content,": 'true'",": TRUE")
yaml_content <- stringr::str_replace(yaml_content,": 'false'",": FALSE")
writeLines(yaml_content,"C:/Users/Claudius Main/Desktop/TempTemporal/Graphviz Playground/yaml_html.yaml")

quarto::quarto_render("index.qmd",pandoc_args = c("--metadata-file","C:/Users/Claudius Main/Desktop/TempTemporal/Graphviz Playground/yaml_html.yaml"),output_format = "html",output_file = "Graphviz Playground (quarto).html")
print(all_times)
```

The results are really confusing. 

- Case 1: `RScript`, run from the command line: ![grafik](https://github.com/quarto-dev/quarto-cli/assets/80548781/5615e21d-ff33-48a0-b237-284035919424)
- Case 2: `RScript`, run from within RStudio: same results
- Case 3: manually running the script file via `Ctrl+Shift+K` within RStudio: same results
- Case 4: manually converting the qmd-file (_not the script_) via `Ctrl+Shift+K` within RStudio:e

- _sometimes_ running it via rstudio works. Even more confusingly, doing it again outside RStudio will then not re-break it... No clue whatsoever why.

In RStudio, this is the cl-output I get back when running the script:

````

processing file: index.qmd
1/3             
2/3 [fig-mtcars]
3/3             
output file: index.knit.md

pandoc --output Graphviz Playground (quarto).html
  to: html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  email-obfuscation: none
  number-sections: true
  reference-location: margin
  toc: true
  toc-depth: 5
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  citation-location: margin
  df_print: kable
  fig-cap-location: margin
  fig-title: Figure
  number-depth: 99
  tbl-cap-location: margin
  toc-location: right
  toc-title: Table of Contents
  author: Claudius Appel
  bibliography:
    - 'D:/Dokumente neu/Zotero_Papers/Zotero_papers_autosync.bib'
  csl: 'D:/Dokumente neu/Obsidian NoteTaking/The Universe/003 PandocAssets/Citationstyles/cite-them-right-12th-edition-Harvard.csl'
  creation date: '2023-07-02 09:26'
  cssclass: 'clean-embeds, writing'
  modification date: '2023-07-02 23:01'
  code-fold: true
  email-obfuscation: none
  fig-height: 6
  fig-width: 8
  number-sections: true
  reference-location: margin
  toc: true
  toc-depth: 5
 
````

Expected result:

![grafik](https://github.com/quarto-dev/quarto-cli/assets/80548781/2e2fac89-caad-48c9-bb05-fd91dd939123)
(resulting from running in RStudio). Sometimes it works. Sometimes it even works when running my build-script from the explorer. Most of the times it does not work. And it's not consistent, or consistent in a way I can't understand.
---

Using the same format for bookdown works flawlessly.  
I also attempted this with a local bib file in the document/working directory.

What am I doing wrong for quarto here? 
I just don't see what is the issue.

Any help is appreciated.  

Thank you.
Sincerely,
~Gw

**Comment by mcanouil** [comment]
Your YAML frontmatter has many issues:

- keys with spaces.
- keys that do not exist in Quarto.
- key/value outside of the frontmatter (_i.e._, the third `---` is read as "horizontal rule").

````yaml
---
author: g s
bibliography: "D:/Dokumente neu/Zotero_Papers/Zotero_papers_autosync.bib"
cite-method: citeproc
creation date: 2023-07-02 09:26
csl: "D:/Dokumente neu/Obsidian NoteTaking/The Universe/003 PandocAssets/Citationstyles/cite-them-right-12th-edition-Harvard.csl"
cssclass: clean-embeds, writing
modification date: 2023-07-02 22:01
---

cite-method: citeproc

---
````


Take a/another look at:
- <https://quarto.org/docs/authoring/footnotes-and-citations.html>
- <https://quarto.org/docs/reference/dates.html>
