### DISCUSSION TITLE
Add  option to allow yaml-file keys to overrule their duplicates in the frontmatter/overrule-by-default

### DISCUSSION THREAD

**Discussion by Gewerd-Strauss** [quarto-dev/quarto-cli#6119] [Feature Requests]
### Description

Hello,

this might sound odd, so let's assume a very basic scenario. We have a simple document 

```qmd
---
author: "conssectetur adipiscing elit"
date: now
date-format: "rev. DD.MM.YYYY HH:mm:ss"  
subtitle: "dolor sit amet"
title: "LOREM IPSUM"
---

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

```

with a default date and date-format.

Now, we convert it with to let's say `html` while feeding the following yaml file:

```yaml
citation-location: margin
code-fold: TRUE
date: now
date-format: DD.MM.YYYY
df_print: kable
email-obfuscation: none
fig-cap-location: margin
fig-height: 6.0
fig-title: Figure
fig-width: 8.0
number-depth: 99.0
number-sections: TRUE
reference-location: margin
tbl-cap-location: margin
toc: TRUE
toc-depth: 5.0
toc-location: right
toc-title: Table of Contents
```

This will result in the following output:

![grafik](https://github.com/quarto-dev/quarto-cli/assets/80548781/76020cc9-8f51-41a8-98ae-05b074ac98cc)

Referring to the documentation on [`metadata-files`](https://quarto.org/docs/reference/formats/html.html#includes), frontmatter keys will overrule those fed via a yaml-file with the argument key `metadata-file`:

    quarto::quarto_render("<manuscriptname>.qmd",pandoc_args = c("--metadata-file","<yamlPath>.yaml"),output_format = "html",output_file = "<filename>.html")
    

---

To me at least, this doesn't make a lot of sense. Or rather, it is limiting where it doesn't need to be.

From my understanding, quarto will parse the frontmatter keys and then add any non-duplicate keys it will find in the yaml file. However, this brings home the simple disadvantage that you must outsource all keys you might want to change often (or vary between output formats) into the yaml file. So if you need to export to e.g. html, docx and pdf you must specifically define these keys in the yaml file for each and ensure that the frontmatter doesn't contain it.

But what if I need only a single file with a different value for that key? Say I need to hand in a report to three different places for review, and two people want a docx-file with a german-formatted date `DD.MM.YYYY`, while the third one rather had an html and needs the specific revision `date-format: "rev. DD.MM.YYYY HH:mm:ss"`.  
Instead of setting the general assumption to the frontmatter and specifying the deviation when converting to html in its respective yaml-file, I now need call quarto at least twice; and manually edit the file inbetween. 

I don't know, that seems unnecessarily complicated to me.

If yaml-file keys would overrule frontmatter ones, this would not be an issue. From my perspective, the negative aspects are almost nonexistent, this would only result in perceived-wrong output if the user uses a random yaml file and doesn't know what keys they are overwriting at-random while doing so. That is an extremely unlikely scenario.

In principle, this would (and imo should) be applicable to all format-agnostic keys.

I hope I could explain my confusion here well enough.

Thank you,  
Sincerely,  
~Gw
