### DISCUSSION TITLE
How to use reverse alphabetical order in automatically generated navigation links for Quarto website?

### DISCUSSION THREAD

**Discussion by banskt** [quarto-dev/quarto-cli#6129] [Q&A]
### Description

In a Quarto website, I am using the Diátaxis Framework for navigation, as explained in the [hybrid navigation](https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation). For the sidebars, I am using [automatically generated links](https://quarto.org/docs/websites/website-navigation.html#auto-generation). The relevant section of my YAML file looks like:
```yaml
  sidebar:
    - title: "Journal"
      style: "docked"
      collapse-level: 1
      search: true
      background: light
      contents:
        - journal/index.qmd
        - auto: journal/*
```
WIthin the `journal` directory, I create entry for each day with filename `YYYY-MM-DD.qmd`. As mentioned in the documentation, 
> Order is alphabetical (by filename) unless a numeric `order` field is provided in document metadata.

I want the latest documents at the top, therefore I need a reverse alphabetical order. Is it possible to use reverse alphabetical order in automatically generated navigation links?
