### DISCUSSION TITLE
name output pdf file as foldername.pdf

### DISCUSSION THREAD

**Discussion by rputikar** [quarto-dev/quarto-cli#6149] [Q&A] [answered]
### Description

I have following structure. 

```
notes/
- folder1/index.qmd
- folder2/index.qmd
```

I want to create pdf and docx output along with html 

my `_quarto.yml` file has:

```
output-dir: _site
format:
   html: default 
   pdf: default
   docx: default
```

this creates

```
_site/
  - folder1/index.html
  - folder1/index.pdf
  - folder1/index.docx
  - ...
```

how do I create

```
_site/
  - folder1/index.html
  - folder1/folder1.pdf
  - folder1/folder1.docx
  - ...
```

I can write
 
```
format:
  pdf:
    output-file: folder1.pdf
 docx:
    output-file: folder1.docx
```

in each `.qmd` file, but is there an way to do this generically? using post-render in the `_quarto.yml` file does not change the links in the html file.
