### DISCUSSION TITLE
Is there a way to serve all the content in a folder as root?

### DISCUSSION THREAD

**Discussion by dweng0** [quarto-dev/quarto-cli#6198] [Q&A]
### Description

Hey, I have all my content in a directory called `content` and would like to keep it there for tidyness. However, when i go to render the site, my sidebar only shows "content" as the navigation item, and the url has "content" as the base.
![image](https://github.com/quarto-dev/quarto-cli/assets/5268627/0d0b55ba-3293-45fb-8e11-84d0e9b6af50)

My question is, is there a way to tell quarto to treat all the content in the `content` folder as root? I've tried the following, but they done seem to work:

``` yml
website:
  title: "" 
  favicon: "assets/favicon.svg"
  google-analytics: ""
  site-url: "https://localhost:3000/content/"
```

and 
``` yml
website:
  title: "" 
  favicon: "assets/favicon.svg"
  google-analytics: ""
  site-path: /content/
```

I have looked in the [Quarto yml](https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml) for the doc site, but couldn't find anything that looked like it would set the site root.

Is it possible to do?
