### DISCUSSION TITLE
Why social button alway showing up on footer?

### DISCUSSION THREAD

**Discussion by ning3739** [quarto-dev/quarto-cli#6219] [Q&A] [answered]
### Description

I installed the social share extension from Quarto. And I added the following code in my YAML:

```
filters:
  - social-share
share:
  permalink: "https://mr.schochastics.net/"
  description: "awesome page"
  twitter: true
  facebook: true
  reddit: true
  stumble: true
  tumblr: true
  linkedin: true
  email: true
  mastodon:true
```
However, I found that the social button always overlaid on the footer. Is it possible that I can put the social button before the blog or just put it between the comments and the end of the blog?

[repo](https://github.com/NING3739/datalabzone)

![Screenshot 2023-07-15 at 3 31 06 PM](https://github.com/quarto-dev/quarto-cli/assets/94179273/1425ef01-d7d4-4ebb-8702-79557aec11d6)
