### DISCUSSION TITLE
Inline R code in _extension.yml elements, possible?

### DISCUSSION THREAD

**Discussion by ramiromagno** [quarto-dev/quarto-cli#6222] [Q&A] [answered]
### Description

Hi!,

I am trying to develop a Quarto Journal Template, or actually, trying to learn on how to do that :)

It seems I cannot include inline R code to be executed in the `_extension.yml`? Do you confirm? Or am I doing something wrong?

Look at the `copy-year` element:

```
title: Wiley's New Journal Design (NJD) Latex Authoring Template
author: Ramiro Magno
version: 1.0.0
quarto-required: ">=1.3.0"
contributes:
  formats:
    common:
      toc: true
      filters:
        - wiley-njd.lua
    pdf:
      documentclass: WileyNJDv5
      classoption: [AMA, Times1COL]
      template: wiley-njd-template.tex
      cite-method: natbib
      article-type: ""
      received: "Date Month Year"
      revised: "Date Month Year"
      accepted: "Date Month Year"
      journal: "Journal"
      volume: "00"
      copy-year: "Last update : `r Sys.Date()`"
      present-address: ""
      abbreviations-note: ""
      template-partials:
        - "partials/title.tex"
        - "partials/biblio.tex"
      format-resources:
        - wiley-njd-v5/WileyNJDv5.cls
        - wiley-njd-v5/LETTERSP.STY
        - wiley-njd-v5/wileyNJD-AMA.bst
        - wiley-njd-v5/wileyNJD-AMS.bst
        - wiley-njd-v5/wileyNJD-APA.bst
        - wiley-njd-v5/wileyNJD-APS.bst
        - wiley-njd-v5/wileyNJD-Chicago.bst
        - wiley-njd-v5/wileyNJD-Harvard.bst
        - wiley-njd-v5/wileyNJD-MLA.bst
        - wiley-njd-v5/wileyNJD-MPS.bst
        - wiley-njd-v5/wileyNJD-Vancouver.bst
        - wiley-njd-v5/wileyNJD-WCMS.bst
    html:
      css: styles.css
```

in the generated PDF I get:

![snap](https://github.com/quarto-dev/quarto-cli/assets/19862384/164abaac-baae-48cc-852e-1ceab68ebd97)

**Comment by mcanouil** [comment]
Syntax `` `r ` `` is not officially supported in YAML by Quarto.
The supported syntax is `!expr 'code'`.

Quarto has a date features why not use it?
See <https://quarto.org/docs/reference/dates.html>.

**Reply by cderv** [reply]
@ramiromagno This syntax using `!expr` only works inside [R code chunks](https://quarto.org/docs/computations/r.html#chunk-options) 

You won't be able to use it in `_quarto.yaml` or `_extension.yml`

**Comment by ramiromagno** [comment]
Could you please provide a concrete example? Because I've tried:

```yaml
copy-year: !expr 'date()'
```

and 

```yaml
copy-year: !expr 'r date()'
```

and both yield `true` in the generated PDF:

![snap](https://github.com/quarto-dev/quarto-cli/assets/19862384/d7e952da-65f1-4359-9e12-07a778f5254c)

And in the intermediate latex file I can confirm that:

```latex
\copyyear{true}
```

The reason why I don't use something like `date` instead of my own custom `copy-year`:

```yaml
---
date: 03/07/2005
date-format: "YYYY"
---
```

is because then I would not be able to use date element except as the year of the date. It would be nice if I could have different dates and format them individually:

```yaml
---
birth-date: 03/07/2005
birth-date-format: "DD MM YYYY"
graduation-date: 03/07/2005
graduation-date-format: "YYYY"
---
```
but as far as I understand that is not possible.
