### DISCUSSION TITLE
Can I use R variables in quarto YAML?

### DISCUSSION THREAD

**Discussion by giabaio** [quarto-dev/quarto-cli#6262] [Q&A]
I may be missing something obvious, but I would like to do that. I'm working on a quarto slide presentation (formatted in revealjs) and I have defined a bunch of objects in the `params` variable in my YAML
```
---
...
params:
   title: "My title"
   author: Gianluca Baio
   date: 27 November 2022
   institute: "[My work](Their website)"
   conference: "Where I'm speaking"
   location: "What town"
...
---

HERE GOES THE REST OF MY SLIDES
```

What I would like to do is to use the elements of `params` to feed to the `footer` that I want to use for the slides, something like
```
...
format: 
   revealjs:
      footer: `r params$author` | `r params$title` | `r params$date`
```
but it seems like I can't use the 
```
`r command`
```
tag inside the yaml, as it returns an error
```
bad indentation of a mapping entry at line 9, column 10:
       footer: `r params$author`
```

Like I said, it's possible I am not doing this right --- but can anyone explain why and how I can do it instead?

Thanks
Gianluca

**Comment by mcanouil** [comment]
Hi,

in theory, you have to use the keyword `!expr` as for the yaml chunk options and described in https://quarto.org/docs/computations/r.html#chunk-options

**Comment by giabaio** [comment]
I'll check again to make absolutely sure, but I think I have tried that, to no avail...

Gianluca Baio

Professor of Statistics & Health Economics
Department of Statistical Science  |  University College London
1-19 Torrington Place, London WC1E 6BT, UK
Twitter: @stats_UCL<https://twitter.com/stats_UCL>  |  Instagram: @stats_UCL<https://instagram.com/ucl.stats/>

Telephone +44(0)20 7679 1248 (internal: 41248)
Website: http://www.homepages.ucl.ac.uk/~ucakgba
Blog: https://gianluca.statistica.it/blog/
Book a meeting with me: https://book.morgen.so/gianlucabaio/book-me

[Twitter]<https://twitter.com/gianlubaio>       [LinkedIn (Personal)] <https://linkedin.com/in/gianluca-baio-b893879/>  [Github] <https://github.com/giabaio>   [Zoom] <https://ucl.zoom.us/j/9904462616>       [ORCID] <https://orcid.org/0000-0003-4314-2570>         [Soundcloud] <https://soundcloud.com/uclsound/sets/sample-space>



____________________________________________________
For Head of Department correspondence, please use ***@***.******@***.***>

[https://s1g.s3.amazonaws.com/3f32ef1962be41fb8943ee58d28cf3aa.png]

This email may reach you outside of your working hours. If that's the case, please do not feel pressure to reply immediately.


On July 14, 2022 at 17:05 GMT, Mickaël Canouil ***@***.******@***.***>> wrote:


⚠ Caution: External sender


Hi,

you have to use the keyword !expr as yaml chunk option pour and described in https://quarto.org/docs/computations/r.html#chunk-options<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fquarto.org%2Fdocs%2Fcomputations%2Fr.html%23chunk-options&data=05%7C01%7Cg.baio%40ucl.ac.uk%7C9a4b8f1b1a1b402629cd08da65bb0eec%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637934151322405288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n5qhRtd1HiEjKNRmOmRHIjUQjvATMWcNWSB3HE3Qojo%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://github.com/quarto-dev/quarto-cli/issues/1391#issuecomment-1184681637>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACCRVSN5R6V6ZFGMB2FMXITVUBCFVANCNFSM53SCUOVA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

[https://bolt.im/t/?ect38EoTVQh_lAkg2qy2q-u7rEZBNQ2ewQXPj3cLC2KPyKIsiF4zjiIIHit1nJZ5bcerYhyMOBgjZsobl8O1nA]

**Comment by mcanouil** [comment]
I tried it and it does not work as for `rmarkdown` ...

```
---
params:
  title: "My title"
  author: Gianluca Baio
  date: 27 November 2022
  institute: "[My work](Their website)"
  conference: "Where I'm speaking"
  location: "What town"
title: !expr params$title
format: revealjs
---
```

produced an error:

```
Error: object 'params' not found
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Could not evaluate expression: params$title
Calls: .main ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted
```

**Comment by giabaio** [comment]
Nope --- I've tried again. I can specify in my YAML
```
---
params:
   title: Title here
   shorttitle: Short title here
   author: Gianluca Baio
   date: 27 November 2022
   institute: "[My department](the website) | My institution"
   conference: "Some conference"
   location: "Some place"
   shortlocation: "A shorter version of the place"
format: 
   revealjs:
     header-includes: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet"/>
     theme: [ucl-stats.scss]
     slide-number: true
     chalkboard: 
      buttons: false
      theme: whiteboard
     preview-links: auto
     width: 1800
     height: 1000
     footer: |
        &copy; !expr params$author
# Includes various LaTeX macros
     include-in-header: "latex_macros.html"
     css: styles.css
from: markdown+emoji
---

## Just to check that the text gets parsed OK
`r rmarkdown::metadata$params$author`
```
but what happens is that the footer is parsed "verbatim", so it appears as 
```
© !expr params$author
```
but the text is parsed correctly in the slide body (so it turns the object `params$author` into my name, as given in the YAML).

I don't know if there's an issue with how the `footer` is defined --- in that it doesn't allow **R**markdown, but only markdown? If so, would it be possible to implement a different strategy? I can, for example, create a footer for a specific slide, something like
```
...
::: footer
&copy; `r rmarkdown::metadata$params$author | 
`r some_function_to_add_my_twitter()` `r some_function_to_add_my_github()` | 
`r rmarkdown::metadata$params$shorttitle` |
`r rmarkdown::metadata$params$shortlocation` |
`r rmarkdown::metadata$params$date`
:::
```
and that works **perfectly**. But then I would need to copy the same text for each slide, which is obviously not ideal...

Any suggestions?

Many thanks again!
Gianluca
