### DISCUSSION TITLE
How does Quarto position the footer?

### DISCUSSION THREAD

**Discussion by dense-set** [quarto-dev/quarto-cli#6305] [Q&A] [answered]
### Description

Hi. I was wondering how Quarto ensures that the footer is always at the bottom of the webpage. I couldn't find any CSS rules in the generated `site_libs/bootstrap/bootstrap.min.css` that ensure this.

Here is a concrete minimal example:

`_quarto.yml`:
```yml
project:
  type: website

website:
  title: "Quarto lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
  
  page-footer: Footnote content

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

`index.qmd`:
````qmd
---
title: "Quarto lab"
---

Main content.
````

The relevant portion of the generated `index.html` just before `</body>`:
```html
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Footnote content</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
```

However, I couldn't find anywhere in `bootstrap.min.css` that ensures that the above chunk actually appears at the page's bottom. (I checked all the CSS rules that contained the keyword `nav-footer`.)

What am I missing?
