### DISCUSSION TITLE
Redirect a blog post to an external link (while having the blog card)

### DISCUSSION THREAD

**Discussion by e-alizadeh** [quarto-dev/quarto-cli#6309] [Q&A] [answered]
### Description

Is there a way to redirect a blog post to an external link, while having the post card in the my blog page?  

Context: I have published a post on medium and instead of re-writing it on my website, I want to add a blog card to my post, such that when a reader clicks on it, the website takes it to the medium post page (which is an external link).

I've tried the following
1. using `aliases` in the frontmatter (I saw this in the documentation)
```
---
title: "Learning More"
aliases:
  - "https://example.org"
---
```

2. Include the following HTML code -> This technically works but it take a second or two after to redirect. Basically the user would see an empty post and then would redirect to the target link.
````
```{=html}
<!DOCTYPE html>
<meta charset="utf-8">
<title>Redirecting to ealizadeh.com</title>
<meta http-equiv="refresh" content="0; URL=https://example.org">
<link rel="canonical" href="https://example.org">
```
````

**Comment by mcanouil** [comment, marked as answer]
Don't redirect (remove your Quarto document).
Add an external link to your listing content.

```yaml
listing:
  contents:
    - path: https://github.com/mcanouil/quarto-version-badge
      image: /projects/quarto-extension.png
      title: "Version Badge"
      description: "Version Badge is an extension for Quarto to provide a shortcode to display software version."
      date: "2023-06-20"
      categories: [Quarto, Extension, HTML]
```

**Reply by e-alizadeh** [reply]
Thanks @mcanouil.

**Reply by ANP-Oxy** [reply]
Did this work for you sir? I tried the same solution but it's giving me os error. providing href argument instead of path argument doesn't work either. 
![image](https://github.com/quarto-dev/quarto-cli/assets/94713251/654905db-2625-4bb7-b140-f015a10caa4c)

**Reply by e-alizadeh** [reply]
The suggestion worked for me. Here I'm providing what I have in my `blog.qmd`. It might help you 

```
---
listing:
  contents: 
    - "blog/*/index.qmd"
    - path: https://example.org
      title: "THE TITLE"
      image: "blog/assets/FILE.jpg"
      subtitle: "SUBTITLE"
      description: ""
      date: "2023-07-19"
      reading-time: 10
      categories: [X, Y, Z]
  sort: "date desc"
  type: grid
  categories: false
  filter-ui: false
  sort-ui: false
  feed: true
  fields: [image, date, title, subtitle, reading-time]
margin-header: subscribe.html
---
```

**Reply by th0ger** [reply]
The documentation suggests "href", which must be wrong then?
https://quarto.org/docs/websites/website-listings.html#yaml-listing-content

I changed "href" to "path", which turned the card into an external link. Unfortunately the full "path: ..." is printed on the card.

**Reply by mcanouil** [reply]
Could you double check it does not work and then open an issue with a reproducible example?

**Reply by th0ger** [reply]
https://github.com/quarto-dev/quarto-cli/issues/6903

**Comment by harishb00** [comment]
> Don't redirect (remove your Quarto document). Add an external link to your listing content.
> 
> ```yaml
> listing:
>   contents:
>     - path: https://github.com/mcanouil/quarto-version-badge
>       image: /projects/quarto-extension.png
>       title: "Version Badge"
>       description: "Version Badge is an extension for Quarto to provide a shortcode to display software version."
>       date: "2023-06-20"
>       categories: [Quarto, Extension, HTML]
> ```

@mcanouil The suggested fix is not working for me. Could you help me?

![image](https://github.com/quarto-dev/quarto-cli/assets/43300971/30418804-5cf0-45a0-b2d1-ed7a1c279ccc)

**Reply by mcanouil** [reply]
I can't help with only a screenshot and not knowing which version of Quarto you are using.

As far as I can tell it works: https://mickael.canouil.fr/projects

**Reply by drganghe** [reply]
This is very helpful. Open external link in new window seems not working under default type of listing:
See an example here:
https://drganghe.github.io/media.html
Source file:
https://github.com/drganghe/drganghe.github.io/blob/main/media.qmd
link-external-newwindow: true is active both in the file and in _quarto.yml
Is this by design or a bug? Thanks.

**Reply by mcanouil** [reply]
I cannot reproduce (using latest version) your issue using a simple default project:
1. `quarto create project blog demo Demo`
2. Replace content of `index.qmd`

````qmd
---
title: "Demo"
listing:
  contents:
    - path: https://www.nature.com/articles/d41586-024-00692-7
      image: /files/images/media/nature.png
      title: "China–US climate collaboration concerns as Xie and Kerry step down"
      author: Smriti Mallapaty
      description: "Gang's quote on the importance to continue the research exchange and colloboration 'If the river freezes over, water will still flow underneath.'"
      date: "2024-03-12"
      categories: [Nature]
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---
````

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/3322cfb0-1b29-4607-8c6c-3a519fc75467">

**Reply by drganghe** [reply]
Thank you @mcanouil , I tried version 1.5.31 and the issue still persist. In your demo, the image was not shown. Maybe you can reproduce the issue with an workable image? The link-external-newwindow: true in listing in grid and table works as expected.

**Reply by mcanouil** [reply]
Did you try exactly what I did and shared?
How is the image path relevant here? I simply copied and pasted your "content" to show that it works.
`link-external-newwindow: true` has no incidence on listings links when default, but the links do work.

Edit: Now I understand that you were rising an issue a bit unrelated to this thread, *i.e.*, "`link-external-newwindow: true` is not respected by default listing."

I opened an issue to track this:
- https://github.com/quarto-dev/quarto-cli/issues/9468

Thanks @drganghe for the report which I did not understood at first, my apologies for that.

**Reply by dambach** [reply]
My understanding is that this works (in the file we want the listing to appear):

```
---
listing
    - id: pubs
      contents: pubs
      type: grid
      fields: [image, title]
      contents: 
        - path: https://doi.org/XXX
          title: a title
          description: some description
          image: img/logo.png
---
```

but having a index.md in a subfolder (for instance pubs/pub1/index.md) with :


```
---
path: https://doi.org/XXXX
title: a title
description: some description
image: featured.png
---
```

and in the file where we want the listing to appear : 

```
---
    - id: pubs
      contents: pubs
      type: grid
      fields: [image, title]
---
```

does not work. Is this correct @mcanouil  ?
