### DISCUSSION TITLE
How do you link to multiple pages in a single sidebar navigation item?

### DISCUSSION THREAD

**Discussion by melissavanbussel** [quarto-dev/quarto-cli#6319] [Q&A] [answered]
### Description

I'm wondering if there's a way to have multiple clickable URLs displayed in a single sidebar navigation item on a Quarto website. For example, I currently have something like this: 

```
sidebar: 
    title: My title
    contents:
      - href: page_example_english.qmd
        text: Page Example EN
      - href: page_example_french.qmd
        text: Page example FR
```

And I'd like to have something like this:

```
sidebar: 
    title: My title
    contents:
      - href: [page_example_english.qmd, page_example_french.qmd]
        text: Page Example [EN] [FR]
```

So that when it renders, it would look something like this in the sidebar navigation: 

Page Example [[EN]()] [[FR]()]

Is there a way to do this? 

(**Note:** I'm already using `lang: en` and `lang: fr` and have a button to switch over to the opposite-language version of the site, but hoping there's a way to have the direct links to all the pages of both languages in the sidebar)

Thank you in advance for your help!

**Comment by mcanouil** [comment]
Use JavaScript to change the URL when you toggle your button to switch languages.

**Reply by melissavanbussel** [reply]
Thank you for your help! Is there an example of how to do that? Right now, I've got a "en" and a "fr" folder with identical structure, and this (in the `_quarto.yml` file within the "en" folder): 

```
    tools: 
      - icon: translate
        href: ../fr/
        text: Français
```

At the moment, clicking on the translate icon just redirects the user to the homepage of the opposite language site.

**Reply by mcanouil** [reply]
Not currently, but the idea is the same as to switch between image files, see <https://mickael.canouil.fr/posts/2023-05-30-quarto-light-dark/>.

**Reply by melissavanbussel** [reply]
Thank you, the link is very helpful. 

I don't have any javascript experience, but this is what I tried: 

1) Added this to the bottom of my `/en/_quarto.yml` file: 

```
include-after-body:
  text: |
    <script type="application/javascript" src="switch-languages.js"></script>    
```

2) Modified the translate button in the `en/_quarto.yml` to say: 

```
    tools: 
      - icon: translate
        href: ../fr/
        text: Français
        id: switchlanguages
```

3) Created `en/switch-languages.js` that includes this (based on [this](https://debug.to/3093/how-to-replace-string-in-current-url-with-javascript) tutorial): 

```
$("#switchlanguages").on('click', function() {
    window.location = location.href.replace('/en/','/fr/') ;
  });
```

When I click the translate button, though, it still leads to the root of the `fr` folder (`fr/index.qmd`) rather than replacing the `fr` in the current URL with `en`. Any help is greatly appreciated!  

(**Edit:** I also tried removing the `href: ../fr/` from the `en/_quarto.yml` and then the button doesn't do anything upon click)
