### DISCUSSION TITLE
Create a single revealjs presentation from multiple qmd files

### DISCUSSION THREAD

**Discussion by m-guggenmos** [quarto-dev/quarto-cli#6333] [Q&A] [answered]
### Description

I would like to combine a set of qmd files into a single revealjs presentation. What would be the easiest way to achieve this in Quarto?

Currently my `_quarto.yml` looks something like this:

```
project:
  output-dir: _slides
  render:
    - slidedeck1.qmd
    - slidedeck2.qmd
    - slidedeck3.qmd

format:  revealjs
```

.. and as a result I want a single slide deck comprising slidedeck1.qmd to slidedeck3.qmd.
