### DISCUSSION TITLE
Using a `navbar` in Quarto book hides downloads and social links

### DISCUSSION THREAD

**Discussion by agrogan1** [quarto-dev/quarto-cli#6342] [Q&A] [answered]
### Description

Hello, I have encountered an issue where including a navbar in a quarto book seems to hide the social links and download links. I've tried to prepare a minimal example at https://github.com/agrogan1/bookdemo. The built version of the book is at https://agrogan1.github.io/bookdemo/. Please note the links to the GitHub repo, to download a PDF version, and social media links all in the upper left hand cornder. If I included a `navbar` e.g.

```yaml
website:
  navbar:
    background: primary
```
I would see the `navbar` but the links to GitHub repo, PDF download and social media sharing would all be obscured. NB I don't *need* to include a `navbar`, they just look nice and seem to add definition and functionality to a site.  Thanks for the great Quarto book format. It's very valuable, and I appreciate all of the hard work that went into it.

**Comment by dragonstyle** [comment, marked as answer]
Using Quarto 1.4, writing this:

```yaml
project:
  type: book
  output-dir: docs


book:
  title: "bookdemo"
  author: "Jane Doe"
  date: "today"
  downloads: [pdf]
  search: true
  repo-url: https://github.com/agrogan1/bookdemo
  repo-actions: [issue]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  navbar:
    background: primary
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

and rendering I see:

![Screenshot 2023-07-26 at 2 51 22 PM](https://github.com/quarto-dev/quarto-cli/assets/261654/f7ecbcac-c800-4458-a736-3af877690a59)

Which I think(?) looks correct. Are you seeing something different or can you suggest what you're expecting that you aren't seeing?
