### DISCUSSION TITLE
Relative paths in pdf format

### DISCUSSION THREAD

**Discussion by mmelko-profinit** [quarto-dev/quarto-cli#6347] [Q&A] [answered]
### Description

Hello, sorry if this topic was addressed elsewhere, but I couldn't find the answer.

## Description

I have a custom quarto extension, supporting 3 formats (html, reveal js, pdf). In order to introduce users to quarto and give
them some quick tutorials, I created documentation as a quarto website project. This documentation is located on the same level as the extension.
Example file structure is as follows:

```
_extensions/custom/
-- _extension.yml
-- styles.scss
-- styles.tex
-- logo.pdf

docs/
-- _extensions/ <----- symlink to _extensions in parent directory
-- some_pages.qmd
-- examples/
    -- template.pdf
-- _quarto.yml

template2.pdf   <------ copy of docs/examples/template.pdf, to show the issue
```

Example _extensions/custom/_extension.yml

```yml
quarto-required: ">=1.2.0"  
contributes:
  formats:
    pdf:
      include-before-body: 
         text: |
            \thispagestyle{fancy}
            \fancyhead{}
            \fancyhead[R]{\includegraphics[width=4cm]{_extensions/custom/logo.pdf}}
```

## Problem

Each pdf file should contain a logo, bundled in the _extension. Problem is, that with include-before-body option, path to logo
gets pasted at the beginning of the intermediate .tex file. Therefore, rendering template2.pdf on the upper level works, because path is correct. 
But rendering website project fails from docs/ folder, because quarto is looking for the logo from directory of the template.pdf
(docs/examples/). Based on quarto docs, I thought it would be solved by setting execute-dir to docs/, but it didn't help,
intermediate template.tex file was still created in docs/examples.

Only solution I found was to add new path to docs/_quarto.yml, like this:

```yml
project:
  type: website
  execute-dir: project
format:
  custom-pdf:
    include-before-body: 
        text: |
          \thispagestyle{fancy}
          \fancyhead{} % clear all header fields
          \fancyhead[R]{\includegraphics[width=4cm]{../_extensions/custom/logo.pdf}}
```

Which overwrites setting in _extension.yml. But this breaks the encapsulation of logo.pdf and if the user of the custom extension creates his own file structure (similar to mine with docs), he will have to change the path himself.

Is there any way to set relative path to logo.pdf, which will be independent on the location of .pdf templates?
Thank you!
