### DISCUSSION TITLE
\usepackage{cancel} in html book

### DISCUSSION THREAD

**Discussion by yairmau** [quarto-dev/quarto-cli#6348] [Q&A] [answered]
### Description

In a quarto html book, I need to write

$$
\cancel{abcd}
$$

```
$$
\cancel{abcd}
$$
```

The preview works great, but when I render I get

compilation failed- error
Undefined control sequence.
l.203 \cancel
             {abcd} 

I tried writing the following in _quarto.yml, but this didn't work. Can someone please help?

```
format:
  html:
    include-in-header:
      - text: |
          \usepackage{cancel}
```
