### DISCUSSION TITLE
How to enable utterances in a quarto website

### DISCUSSION THREAD

**Discussion by BB1464** [quarto-dev/quarto-cli#6362] [Q&A] [answered]
### Description

I am trying to enable utterances in my quarto website, and I have installed the app on my website, but I dont know how to get this working in quarto. Here is a link to my quarto website: Thank you very much!!!

https://github.com/BB1464/oluwafemi-oyedele

**Comment by dragonstyle** [comment]
We cover this here:

https://quarto.org/docs/output-formats/html-basics.html#commenting

Adding this to your HTML format key should enable it:

```yaml
format:
  html:
    comments:
      utterances:
         repo: BB1464/oluwafemi-oyedele
```

HTH!
