### DISCUSSION TITLE
Support for R Markdown extensions like `pagedown`?

### DISCUSSION THREAD

**Discussion by pat-alt** [quarto-dev/quarto-cli#640] [Q&A] [answered]
@yihui and others have contributed many amazing R Markdown extensions in the past including `pagedown`, for example. Is there a way to use those with Quarto? I'm imagining something along these lines:

```YAML
format:
    pagedown::html_resume:
        self-contained: true
```

Of course, you can still use existing extensions in the same way as before, but in an ideal world you could specify options as above and then use `quarto render` with it (which I haven't got to work). Is there an efficient workaround?
