### DISCUSSION TITLE
fig-format for Notebook generated plots

### DISCUSSION THREAD

**Discussion by PascalGitz** [quarto-dev/quarto-cli#6416] [Q&A] [answered]
### Description

Hey

I'm currently using a book structure to create a pdf that contains some jupyter notebooks. I would like to include the code generated plots as vector graphics (SVG or PDF).

This is my structure
```
project:
  type: book

book:
  title: "Beispielsammlung"
  subtitle: "Komplettiert die Vorlesung Baudynamik"
  author: "Pascal Gitz & Dr. Stephan Gollob"
  date: "2023-08-02"
  date-format: full
  chapters:
    - index.qmd
    - U1_rayleigh.ipynb
    - U2_EMS.ipynb
    - Untitled-1.qmd
    - references.qmd

bibliography: references.bib


format:
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    fig-pos: 'H'
    fig-format: pdf
    lang: de
```

In my Untitled-1.qmd file i have the following plot, which gets included as desired (as a PDF).

```
title: "test"
format: pdf
execute:
  echo: false
  warning: false
```

## Results

```{python}
#| echo: false
#| label: fig-mew
#| fig-cap: Awesome figure.
import matplotlib.pyplot as plt
plt.plot([1, 2, 3], [1, 2, 3])
plt.show()
````

Plotting the same plot in my U2_EMS.ipynb results in a non vector graphic (probably .png).

How can i change the fig-format for Notebooks?
