### DISCUSSION TITLE
Nested drop-down menus in top navigation bar for Quarto website?

### DISCUSSION THREAD

**Discussion by andreashandel** [quarto-dev/quarto-cli#6461] [Q&A] [answered]
### Description

I currently have [an R Markdown website](https://andreashandel.github.io/MADAcourse/) hosted on Github that has nested dropdown menus in the navbar. E.g. I have a main "Modules" entry, with dropdown entries "module 1", "module 2", etc. and each of those has their own dropdown entries, e.g., "module 1" might contain "lesson 1", "lesson 2". (Those are not the real names of the entries, but I hope the structure is clear).

I'm trying to port that website to Quarto and get the error message **ERROR: "module 1" menu: this menu does not support sub-menus**. I do know that Distill was never able to do nested sub-menus (which is why I never used it). Looking on the Quarto documentation website in the [Website Navigation](https://quarto.org/docs/websites/website-navigation) section, it kinda sounds as if Quarto also only allows one level of dropdown in the top navigation menu, and if one wants deeper nesting, one needs to use side navigation. 

But it's not explicitly spelled out, and searching online I also didn't find a definite answer, so I'm still wondering: Is there a way to get more then one level of dropdown menus in the main navbar with Quarto? Or do I have to embark on the tedious task of restructuring everything to use a mix of top navigation and side navigation? Thanks!

**Comment by OsKaR31415** [comment]
This is an example `_quarto.yml` file to reproduce the problem : 

```yml
website:
  title: "Nested drop down menu"
  navbar:
    right:
      - text: "Menu Title"
        menu:
          - text: submenu
            menu:
              - text: "Submenu Title"
                href: whatever.qmd
          - text: "Item title"
            href: whatever.qmd
          - text: "Item title"
            href: whatever.qmd
```

The message will say : 

> **Error** : 
> "Menu Title" menu: this menu does not support sub-menus
