### DISCUSSION TITLE
Reveal.js Presentation: how to have only image (no text) in the title slide?

### DISCUSSION THREAD

**Discussion by JeffreyRStevens** [quarto-dev/quarto-cli#652] [Q&A] [answered]
I have a question related to question #605. How do I make the first (title) slide have only a background image with no title, author, etc.? I've tried the following:
* Remove `title:` entry from YAML header. Result: no title slide
* Include `title:` with no argument included. Result: error `ERROR: Render failed due to invalid YAML.`
* Include `title: ""`. Result: no title slide
* Include `title: " "`. Result: no title slide

It seems as though you have to have a non-space character in the title for this to work. For instance, if I use `title: "."`, it works, but of course there is a dot in the middle of the slide. Here's an example YAML header that works:
```
---
title: "."
format: 
  revealjs:
    title-slide-attributes:
      data-background-image: https://psychology.unl.edu/symposium/images/2022_banner.jpg
      data-background-size: contain  
---
```
How do I have just an image on the title slide?
