### DISCUSSION TITLE
R-Ladies theme for Quarto remark.js presentation

### DISCUSSION THREAD

**Discussion by beatrizmilz** [quarto-dev/quarto-cli#653] [Show and Tell]
Hi!
Today I started to use Quarto presentations, and I I'm trying to change the style to have a similar theme as the rladies theme in xaringan (made by @apreshill 💜  ), so we can use in future presentations on the meetups.

The original xaringan theme is here: https://www.apreshill.com/slides/rladies-demo-slides.html

This is a first attempt to change the style of the presentation in order to have an R-Ladies theme for Quarto:
https://beatrizmilz.github.io/quarto-rladies-theme/

This is my first time using `.scss`and [the code](https://github.com/beatrizmilz/quarto-rladies-theme/blob/main/custom.scss) is based on what I found on the docs.  I did not figure out how to change the background for the title slide.

If anyone has more ideas to improve it, I appreciate it!

Thanks 😄

**Comment by lucio-cornejo** [comment]
Great job with the theme recreation.
About changing the background for the title slide, the following **CSS** code works for me:

```css
div.backgrounds > 
div.slide-background:first-child >
div.slide-background-content {
  background-color: purple;
}
```

**Comment by cderv** [comment]
I don't think there is a CSS rule specific to change that but the answer above (https://github.com/quarto-dev/quarto-cli/discussions/653#discussioncomment-2581126) can do it. As you can guess from the CSS rule, revealjs as a specific way of managing the background. 

Otherwise, what RevealJS and Quarto offers is that you can change background color on a per-slide basis using `background-color` attributes 
https://quarto.org/docs/presentations/revealjs/#slide-backgrounds

You could then not use a automatic title slide but have your own and add the attributes on it. See https://quarto.org/docs/presentations/revealjs/#title-slide for custom title-slide. 

To customize the automatic title slide you can use the `title-slide-attributes` variable (see in references https://quarto.org/docs/reference/formats/presentations/revealjs.html)

````yaml
---
title: "Slideshow"
author: "author"
format: revealjs
title-slide-attributes:
  data-background-color: red
---
````

This is done through the default Pandoc template. When custom format will be available in Quarto, this could also be an option to have some custom elements to use within the template to fit your theme. 

Hope it helps
