### DISCUSSION TITLE
Word gives 'unreadable content' error when trying to open a Quarto-rendered book

### DISCUSSION THREAD

**Discussion by friendly** [quarto-dev/quarto-cli#6544] [Q&A]
### Description

First, I greatly appreciate the help of Posit/Quarto staff and the community in solving problems and responding
to requests from users. You guys & gals are amazing!!

I'm working on a book project in RStudio (2022.07.2 Build 576) using quarto (v. 1.1.189) and pandoc (v. 2.19.2).
I am trying to compile to `docx`.

My `_quarto.yml` file looks like this:

```
project:
  type: book

book:
  title: "Visualizing Multivariate Data and Models in R"
  author:
    - name: Michael Friendly
      url: https://datavis.ca
      affiliation: Department of Psychology<br>York University
  date: today
  cover-image: images/cover-ellipse.jpg
  favicon: images/favicon/favicon.ico
  ...

   chapters:
    - index.qmd
    - intro.qmd
    - getting_started.qmd
	...

format:
  html:
    html-math-method: mathjax
    theme: cosmo
    code-link: true
	...

  docx:
    toc: true
    toc-depth: 2
    number-sections: true
    highlight-style: github
    code-link: true
	...	
```

when I use Render Book > MS Word Format, there are no errors (except for an unresolved cross reference).
Here is what appears in the Build console

```
pandoc 
  to: docx
  output-file: Visualizing-Multivariate-Data-and-Models-in-R.docx
  toc: true
  number-sections: true
  default-image-extension: png
  toc-depth: 2
  
metadata
  crossref:
    chapters: true
  bibliography:
    - bib/references.bib
    - bib/R-refs.bib
    - bib/packages.bib
  biblio-style: apalike
  link-citations: true
  page-footer: 'Copyright 2022, Michael Friendly'
  knitr:
    opts_chunk:
      fig.path: figs/
  title: Visualizing Multivariate Data and Models in R
  author:
    - name: Michael Friendly
      url: 'https://datavis.ca'
      affiliation: Department of Psychology<br>York University
  date: '2023-08-16T00:00:00-04:00'
  
WARNING: Unable to resolve crossref @sec-mlevene
Output created: _book\Visualizing-Multivariate-Data-and-Models-in-R.docx
```

I try to open the resulting `.docx` file, and I get the error shown in the screenshot below.

![word-error1](https://github.com/quarto-dev/quarto-cli/assets/456353/75b6f3d2-d555-4a03-9acc-634a86310c3d)

I click `Yes` to try to recover the contents of the document, and I get a new error panel, below

![word-error2](https://github.com/quarto-dev/quarto-cli/assets/456353/a9e5caf8-fdca-4658-961e-d1811df9fba0)

There are no permissions or disk space problems, and as suggested, I try to Open the file using Text Recovery, and still get the same error. I have tried this on several machines, with the same result.

I've examined the [troubleshooting guide](https://quarto.org/docs/troubleshooting/), but there is nothing that
seems relevant. In particular, I can't tell if this is a problem from Quarto or pandoc.

What can I do to track down and fix this problem?
