### DISCUSSION TITLE
Escaping Automatic Section Title Capitalization?

### DISCUSSION THREAD

**Discussion by betanalpha** [quarto-dev/quarto-cli#6546] [Q&A] [answered]
### Description

As always thanks to all the developers for a fantastic project.

I'm currently using the `lux` theme for my notebooks.  One style feature is that the section titles are automatically capitalized; this is fine for pure text but it can have unintended consequences for any LaTeX in the section title.  For example in the following notebook 

```
---
title: "Test"
author: "Test"
toc: true
number-sections: true
format:
  html:
    html-math-method: katex
    theme:
      - lux
      - custom.scss
format-links: false
---

# $\sigma$

$\sigma$, not $\Sigma$.
```

it appears that the `$\sigma$` in the section title is covered to `$\SIGMA$` _before_ the LaTeX is rendered, resulting in a capital "Sigma" in the rendered notebook instead of the lowercase "sigma" as intended.

<img width="893" alt="Screen Shot 2023-08-16 at 6 09 07 PM" src="https://github.com/quarto-dev/quarto-cli/assets/1527190/f757abb2-0109-4969-9918-c87415cb87fb">

On the other hand `$\sigma$` renders correctly in the body and table of contents.

I'm just curious if there is any way to escape the LaTeX in the section title in some way so that it is not automatically capitalized by the style.  Definitely not a critical issue but wanted to check to see if there's a proper solution before trying to find a workaround.

Thanks!
