### DISCUSSION TITLE
How can I get plots to display fullpage in a rendered book?

### DISCUSSION THREAD

**Discussion by peedubdub** [quarto-dev/quarto-cli#6547] [Q&A]
### Description

I am totally new to quarto and r. I am a librarian assisting a prof with a book he has written in r markdown using r studio. 

This is an example of the plot code:
````
Estimates <- data.frame(Estimate=rep(0, 30000), Type=rep("", 30000))

for(r in 1:10000) {
  x <- runif(30, max = 3)
  
  Estimates[3*(r-1)+1, 1] <- 2*mean(x)
  Estimates[3*(r-1)+2, 1] <- sqrt(mean(x^2)*3)
  Estimates[3*(r-1)+3, 1] <- max(x)
}

Estimates[,2] <- rep(c("t1", "t2", "tML"), 10000)
Estimates$Type <- as.factor(Estimates$Type)

ggplot(Estimates, aes(x=Estimate, colour=Type, group=Type)) +
  geom_density(size=1.3) + 
  geom_boxploth(
    aes(x=Estimate, colour=Type, group=Type, y=as.integer(Type)+8),
    notch = TRUE) +
  xlab("Estimates") +
  ylab("Empirical densities of the estimates")
````

**Comment by peedubdub** [comment]
I understand (from chat gpt) that Quarto provides options to automatically size the plots to the page dimensions. "You can use the fig.fullwidth and fig.fullheight options to achieve this." [https://chat.openai.com/share/8be95b96-b7d0-4e89-b3fb-bf9cd7dd6c56](url)
So I think my question is not about the plot code at all, but about how to modify the author's r markdown code to achieve what he wants. I have a copy of all the book manuscript files which I can play with.

**Reply by rgaiacs** [reply]
Dear @peedubdub, have a look at https://quarto.org/docs/computations/execution-options.html#figure-options.

You will use something like

``````
```{r}
#| fig-cap: "My full page plot"
#| fig-alt: "Awesome plot"
#| fig-width: 8
#| fig-height: 6

ggplot()
```
``````

`fig-width` and `fig-height` is your page text width and height as illustrated in https://sharelatex-wiki-cdn-671420.c.cdn77.org/learn-scripts/images/f/fc/Layout-dimensions.png. `fig-width` and `fig-height` **must** be in inches! Because you are using R, be familiar with https://yihui.org/knitr/options/#plots.

**Reply by mcanouil** [reply]
Setting `fig-width` and `fig-height` will not necessarily make the figure use the full width of the page, see <https://quarto.org/docs/computations/execution-options.html#figure-options>.

To fully answer the question, additional information are required:
- is the book project format PDF or HTML?
- is the book project using Quarto default format templates? (especially if the format is PDF).

Depending on the answers to these questions:
- https://quarto.org/docs/authoring/article-layout.html
- https://quarto.org/docs/authoring/figures.html#latex-figures
- #4399

**Reply by cscheid** [reply]
**I will also warn you against using ChatGPT for quarto questions**. ChatGPT (and I'm sure other AI assistants) uses old versions of our documentation in their corpus, and we consistently find users in this forum asking questions which imply they've been given misleading information. Please consult https://quarto.org instead.

**Reply by peedubdub** [reply]
Thank you @mcanouil 
To answer your questions:
1. the book project will use HTML more than PDF, as the prof wants to use it as an interactive learning  tool for students (Though my work on the book is to publish it in Pressbooks)
2. I can't answer if the project is using Quarto default format templates. Where would I look to check on that?

**Reply by rgaiacs** [reply]
Dear @peedubdub, check the `_quarto.yml` file to discover the template being used.

Given that you are targeting HTML and PDF and want the same code to produce both outputs, you might need to use conditional content (https://quarto.org/docs/authoring/conditional.html) to avoid side effects.

**Reply by peedubdub** [reply]
Thanks @rgaiacs. No template that I can see. This is the _quarto.yml file:

```yaml
project:
  type: book

book:
  title: "Multivariate Statistics: Theory and Interactive Practical Applications"
  author: "Alejandro C. Frery"
  date: "3/08/2022"
  cover-image: ./Figures/PNG/lilies.png
  chapters:
    - index.qmd
    - intro.qmd
    - linearalgebra.qmd
    - gaussiandistribution.qmd
    - inference.qmd
    - mahalanobisdistancerobustnessalgorithms.qmd
    - principalcomponentsanalysis.qmd
    - factoranalysis.qmd
    # - discriminantanalysis.qmd
    - references.qmd

bibliography: references.bib

format: #epub 
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header:
      text: |
        \usepackage{siunitx}
        \usepackage{float}
        \usepackage{bm,bbm}
        \usepackage{algorithm2e}
        \usepackage{color}
```
