### DISCUSSION TITLE
Link to local file on Quarto website?

### DISCUSSION THREAD

**Discussion by maxdrohde** [quarto-dev/quarto-cli#655] [Q&A] [answered]
In my website created with distill, I was able to link to a local PDF file from the navbar using this code in the site YAML file. The PDF is located in the top-level folder.

### Distill YAML

```
navbar:
  right:
    - text: "Resume"
      href: resume.pdf
```

However, when I try the same thing in a Quarto website, it doesn't link to the file and returns "not found".

### Quarto YAML

```
navbar:
  right:
    - href: resume.pdf
      text: "Resume"
```

Am I doing this wrong, or has the feature not been implemented?

**Comment by jjallaire** [comment]
That definitely should be working! I tested a similar config locally on Mac OS X (w/ the very latest Quarto) and it did work as expected. Could you provide a link to the full source code of your site and let us know what platform you are on and what version of Quarto you are running?

**Reply by maxdrohde** [reply]
I was fiddling with it more this morning and discovered the issue. In my site YAML file I had the `self-contained` option here.

```
format:
  html:
    self-contained: true
```
It seems that with `self-contained: true`, the PDF wasn't being copied into the `_site` folder. When I deleted that YAML option, I was able to link to my PDF file with the same code above.

**Comment by jjallaire** [comment, marked as answer]
Yeah, we turn off automatic resource discovery for self-contained files (if we didn't do this then we'd end up copying a bunch of other files to `_site` that we don't need to). If you absolutely require self-contained then a workaround is to list your file explicitly as a site resource (or list all pdf files as resources). For example:

```yaml
project:
   type: website
   resources: 
        - resume.pdf
```
