### DISCUSSION TITLE
Is it possible to specify render source files to have a custom output path / url?

### DISCUSSION THREAD

**Discussion by aaronsgithub** [quarto-dev/quarto-cli#6561] [Q&A] [answered]
### Description

I'm using v1.4.322

I'm wondering if its possible to change the output path of a directory of src files, perhaps via _metadata.yml?

The `notebooks/` below is actually a git subtree which is why there is an extra directory.

I would like `example.ipynb` to be rendered at `<domain>/articles/example.html` instead of `<domain>/notebooks/articles/example.html`.

```
.
├── README.md
├── _quarto.yml
├── about.qmd
├── assets
│   └── js
│       └── listing.ejs
├── index.qmd
├── notebooks
│   └── articles
│       └── example.ipynb
├── profile.jpg
├── styles.css
└── theme.scss

```
Then the listing in `index.qmd` should reflect the change in paths:
```
---
listing:
  - id: articles
    contents: 
      - "notebooks/articles/**/*.ipynb" # somehow get rid of notebooks
    categories: false
    sort: "date desc"
    type: table
---
```

I realise that this might not be possible out of the box but any suggestions would be most welcome.
