### DISCUSSION TITLE
How can I modify the search section of the navbar?

### DISCUSSION THREAD

**Discussion by benruijl** [quarto-dev/quarto-cli#6564] [Q&A] [answered]
### Description

I would like to modify the search part in the navbar so that it will look like this (found on [this](https://docs.bitfinex.com/docs/rest-auth) website):

![nice_search](https://github.com/quarto-dev/quarto-cli/assets/280089/94b7fe5d-774a-4e32-9cba-f769b2a8367b)

I like this more than the default Quarto small icon, since search is an important feature on my website and I want to highlight that. Since Quarto 1.4 will have shortcuts to open up the search window, I want to display the shortcut as well.

I know I can change the CSS of the current search button, `.navbar .aa-DetachedSearchButton .aa-DetachedSearchButtonIcon` but I don't quite know how I can add elements to the DOM, i.e., I don't know how to add "Search" and the shortcut ("Ctrl-k" in the image).

Can someone help me out?

**Comment by mcanouil** [comment, marked as answer]
You could use `.aa-InputWrapperPrefix` and `.aa-InputWrappeSuffix`.

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/d8962d7d-5eb9-4f77-844c-c71294271c3a">

**Comment by benruijl** [comment]
I would like to have it added to the navigation bar on top, which still
only has the icon in your screenshot.

**Reply by mcanouil** [reply]
You can use inspect/developer mode to tweak this.
The search bar is JavaScrip/CSS.
And switch the type of the search bar, see <https://quarto.org/docs/websites/website-search.html>.

**Comment by benruijl** [comment]
Thanks! I managed to produce the following (I am bad at CSS):

![image](https://github.com/quarto-dev/quarto-cli/assets/280089/4320c668-9c4a-45da-8f14-2221cb712adc)


```css
.navbar #quarto-search.type-overlay .aa-Autocomplete {
    width: 120px;
}

.navbar .aa-DetachedSearchButton .aa-DetachedSearchButtonIcon {
    font-size: medium;
    border: 2px solid #b9b4b4;
    border-radius: 5px;
    display: flex;
    flex: 1 1 auto;
    padding: 5px;
}

body.quarto-light .navbar .aa-DetachedSearchButton .aa-DetachedSearchButtonIcon {
    color: #838689;
    border: 2px solid #ccc6c6;
}

body.quarto-dark .navbar .aa-DetachedSearchButton .aa-DetachedSearchButtonIcon {
    color: #d9e3eb;
    border: 2px solid #b9b4b4;
}

.aa-DetachedSearchButtonIcon::after {
    margin-left:10px;
    content: "  Shift-F";
}
```
