### DISCUSSION TITLE
`_quarto.yml` not loaded

### DISCUSSION THREAD

**Discussion by rgaiacs** [quarto-dev/quarto-cli#6582] [Q&A]
### Description

I have the following files in my directory:

```
./index.ipynb
./index.aux
./index.log
./index.tex
./index_files
./index_files/mediabag
./index.md
./index.qmd
./_quarto.yml
```

`_quarto.yml` has

```
format:
  pdf:
    pdf-engine: lualatex
```

Run `quarto render index.md --to pdf --output index.pdf` results in

```
pandoc --output index.tex
  to: latex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
```

Note that `pdf-engine` should be `lualatex`.

I tried different things and the problem continues. Any help?

**Update**

A minimal working example is provided at https://github.com/quarto-dev/quarto-cli/issues/6583.
