### DISCUSSION TITLE
Custom Website Navigation

### DISCUSSION THREAD

**Discussion by rgaiacs** [quarto-dev/quarto-cli#6597] [Q&A] [answered]
### Description

Quarto has a default [website navigation](https://quarto.org/docs/websites/website-navigation.html) and support [custom formats](https://quarto.org/docs/extensions/formats.html).

How do I create a custom website navigation for my custom format?

## Example

Consider that `_quarto.yml` has

```
project:
  type: website

website:
  title: "My Awesome Website"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - talks.qmd
      - about.qmd 

format:
  my-custom-html: default
```

`_extensions/my-custom/_extension.yml` has

```
title: My Custom
author: Raniere Silva
version: 1.0.0
quarto-required: ">=1.4.0"
contributes:
  formats:
    html:
      template: _templates/my-custom.html
```

and `_templates/my-custom.html` has

```
<!DOCTYPE html>
<html lang="en">
<body>
    $body$
</body>
</html>
```

How can I access the `website.navbar` from Pandoc template?
