### DISCUSSION TITLE
Different body-widths on a website

### DISCUSSION THREAD

**Discussion by snhansen** [quarto-dev/quarto-cli#6615] [Q&A] [answered]
### Description

I'm creating a website project with the following `_quarto.yml`:

```
project:
  type: website

website:
  title: "Title"
  sidebar:
    contents:
      - href: index.qmd
        text: "Index"
      - href: page.qmd
        text: "Page"

format:
  html:
    theme: cosmo
    toc: true
```

and contents of `index.qmd` and `page.qmd` are as follows:
```
---
title: "Title"

format:
  html:
    grid:
      body-width: 1000px
---

## Header
```

and

```
---
title: "Title"

format:
  html:
    grid:
      body-width: 1600px
---

## Header
```
Now, when I preview this using `quarto preview`, the index page is loaded with the correct width. When I navigate to the other page this is also loaded with the correct width. But when I navigate back to the index page then the width is "stuck" at 1600 px. What am I doing wrong?

Another thing I noticed is that when the site is deployed, the width of both pages is 1600 px (see https://biostat.au.dk/stefan/test/).
