### DISCUSSION TITLE
SQL highlights in RevealJS presentation

### DISCUSSION THREAD

**Discussion by ced75** [quarto-dev/quarto-cli#6644] [Q&A] [answered]
### Description

Hi,

I'm trying to display SQL code with highlighted syntax in a reveal JS presentation.

Here is my .qml code:

````
---
title: "test"
format: 
  revealjs:
    theme: beige
    smaller: false
    self-contained: true
    slide-number: c/t
    code-line-numbers: false
date: "septembre 2023"
date-format : "MMM YYYY"
---

```sql
select * from table1;
```
````

But my SQL keywords "select" and "from" are not highligthed (different color on keywords) in the HTML rendered doc (I'm using RStudio to compile the HTML document).
Did I miss something to achieve this?

Thanks in advance for your help.
