### DISCUSSION TITLE
HTML: Is it possible to add a date with "last-modified" field in the sidebar?

### DISCUSSION THREAD

**Discussion by pglpm** [quarto-dev/quarto-cli#6671] [Q&A] [answered]
### Description

I am happily using Quarto for the site/lectures of a course, in HTML. The material is often updated, so I'd like to include a "**Last modified: ...**" in the sidebar (the bar typically on the left), just below the title.

I could do this by hand, by adding that line to the title, for instance like this:
```
sidebar:
    title: "Course Title<br> Last modified: 2023-08-31"
```
but this would require to manually change the date every time some page is modified.

I was wondering if there's any way to make this more automatic. I tried:

- adding a `date: last-modified` under `sidebar:`, but no date appears at all
- adding `last-modified` to the `title:`, outside the title string, but this yields an error.

Thank you!

**Comment by mcanouil** [comment, marked as answer]
Use the `meta` shortcode: `title: "Course Title<br> Last modified: {{< meta date >}}"`.

**Reply by pglpm** [reply]
Thank you! I get a warning instead:
```
WARNING: Unknown meta key date specified in a metadata Shortcode
```
Maybe I need to add something more to the `.yml` file?

**Reply by mcanouil** [reply]
You have to define `date: last-modified` as well.

If you don't define `date`, there is no `date` to retrieve hence the warning.

**Reply by pglpm** [reply]
I did. My yml file looks as follows:
```
  sidebar:
    date-format: iso
    date: last-modified
    title: "Course Title <br>updated {{< meta date >}}"
```

**Reply by pglpm** [reply]
Ah maybe I have to do that under `html:` rather than under `book:`. Will try now.

**Reply by mcanouil** [reply]
I don't know your whole setup but the following works just fine:

```sh
quarto create project website mywebsite
```

Then modify `_quarto.yml`:

```yaml
project:
  type: website

website:
  title: "Mywebsite"
  sidebar:
    title: "{{< meta date >}}"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


date: last-modified
```

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/beb58181-e950-4e27-b020-0ae3035af73b">

PS: when asking questions or reporting issues, providing context is in 99 % of cases an absolute requirements, otherwise it's just back and forth while making/invalidating assumptions.
Providing a reproducible example as a plain text document in the post (not attached) or a Git repository help ensure your question/context is understood.
