### DISCUSSION TITLE
Set 'date: last-modified' on project level

### DISCUSSION THREAD

**Discussion by allefeld** [quarto-dev/quarto-cli#6694] [Q&A] [answered]
### Description

I have a large collection of Markdown notes which I process into a website using Quarto. I would like to have the last modified date of each note displayed on the generated page.

Is there a way to do so without setting this in the metadata block of each document, i.e. to set it on the project level (`_quarto.yml`)? I searched for information on this and did some experiments, but without success.

If this does not exist, I propose to add this feature.

**Comment by mcanouil** [comment]
Simply add `date: last-modified` at whatever level you need it.
See:
- https://quarto.org/docs/projects/quarto-projects.html#shared-metadata
- https://quarto.org/docs/projects/quarto-projects.html#directory-metadata

**Reply by allefeld** [reply]
The description under 'Project Metadata', which sounds like what I want, says to put it at the top level of my `_quarto.yml`. The effect is that the date gets added to the index page, but not any other page.

I tried some other variants:
Below `project`: Error message about invalid property.
Below `website`: Error message about invalid property.
Below `website` / `sidebar`: No effect.
Below `format`: Error message.
Below `format` / `html`: The date gets added to the index page, but no other page.

This is my `_quarto.yml`:
```yaml
project:
  type: website
  output-dir: docs

date: last-modified

website:
  title: "Nerd Notes"
  favicon: favicon.svg
  sidebar:
    logo: /favicon.svg
    title: "Nerd Notes"
    search: true
    contents: auto

format:
  html:
    from: markdown+hard_line_breaks
    theme: cosmo
    css: styles.css
    toc: true
    toc-expand: true
    code-overflow: wrap
    grid:
      sidebar-width: 350px
      margin-width: 350px
```
