### DISCUSSION TITLE
crossref labels language

### DISCUSSION THREAD

**Discussion by produnis** [quarto-dev/quarto-cli#6712] [Q&A]
Hi there, I am creating a book with quatro and I am wondering how to change the crossref labels.
in my `_quarto.yml` I specified as follows:

```
crossref:
  fig-title: "Abb."
  fig-prefix: "Abbildung"
  tbl-title: "Tab."
  tbl-prefix: "Tabelle"
  eq-title:  "Gleichung"
  eq-prefix:  "Gleichung"
  sec-prefix: "Abschnitt"
  #ch-prefix: "Kapitel"
```
This works fine with figures and tabels and equations, but it does not work with chapters and sections.

The `sec-prefix`-Parameter seems to be ignored, as `@sec-anywhere` still generates "Section xy" instead of "Abschnitt xy".
The `ch-prefix`-Parameter is not supported, so I have no clue how to change "Chapter" into "Kapitel".

Is there a doc listing all crossfre -titles and -prefixes?
