### DISCUSSION TITLE
Make Bootswatch paired light and dark themes available

### DISCUSSION THREAD

**Discussion by allefeld** [quarto-dev/quarto-cli#6740] [Feature Requests]
### Description

For many of the Bootswatch themes there seem to be paired light and dark versions. For example, on the Cosmo theme page <https://bootswatch.com/cosmo/> there is a switch in the upper right corner which toggles between the standard light version and a version which retains fonts, formatting, and many colors, but has light-on-dark text.

I tried to implement that for my own website using

````yaml
    theme:
      light: cosmo
      dark: cosmo
````

and

````yaml
    theme:
      light: cosmo
      dark: cosmo-dark
````

or

````yaml
    theme:
      light: cosmo
      dark: cosmo_dark
````

but none of these work.

I downloaded the source code from the light and the dark version of the Cosmo theme page and compared the files, and the only difference seems to be that the `html` element has an additional attribute  `data-bs-theme="dark"`. Manipulating that manually via the inspector works on the Bootswatch theme page, but it does not work on Quarto-generated pages.

It would be nice if there was a way to take advantage of these paired themes in Quarto, instead of pairing two different light and dark themes.
