### DISCUSSION TITLE
Enforcing the filter order with a custom format

### DISCUSSION THREAD

**Discussion by multimeric** [quarto-dev/quarto-cli#6747] [Q&A] [answered]
### Description

I'm writing a custom format which uses a custom filter. This generally works okay, but I've noticed that my filter is definitely running before the Quarto filters, [which contradicts what the docs say]( https://quarto.org/docs/extensions/filters.html#:~:text=By%20default%2C%20user%20filters%20are%20run%20after%20Quarto%E2%80%99s%20built%2Din%20filters). Is that a mistake?

In any case, I want to force my filter to run *after* Quarto, because my filter needs to modify the Quarto-generated content. This works in the document YAML if I do something like this:
```yaml
format:
  my-format-docx:
    filters:
      - quarto
      - my_extension.lua
```

However, I'm making a custom format I want to distribute. If in my `_extension.yaml`, I try to do the same, I get an error:
```yaml
title: my-extension
author: Michael Milton
version: 1.0.0
quarto-required: ">=1.3.0"
contributes:
  filters: 
    - my_extension.lua
  formats:
    common:
      filters:
        - quarto
        - my-extension.lua
```
```
ERROR: Failed to resolve referenced filter quarto - path does not exist.
If you are attempting to use another extension within this extension, please install the extension using the 'quarto install --embedded' command.

Error: Failed to resolve referenced filter quarto - path does not exist.
If you are attempting to use another extension within this extension, please install the extension using the 'quarto install --embedded' command.
    at validateExtensionPath (file:///Users/milton.m/Applications/quarto/bin/quarto.js:59806:15)
    at resolveFilter (file:///Users/milton.m/Applications/quarto/bin/quarto.js:59781:13)
    at file:///Users/milton.m/Applications/quarto/bin/quarto.js:59652:20
    at Array.flatMap (<anonymous>)
    at file:///Users/milton.m/Applications/quarto/bin/quarto.js:59651:57
    at Array.forEach (<anonymous>)
    at readExtension (file:///Users/milton.m/Applications/quarto/bin/quarto.js:59639:8)
    at async readExtensions (file:///Users/milton.m/Applications/quarto/bin/quarto.js:59457:35)
    at async loadExtensions (file:///Users/milton.m/Applications/quarto/bin/quarto.js:59373:32)
    at async Object.extensions (file:///Users/milton.m/Applications/quarto/bin/quarto.js:59283:28)
```

Is this a bug? Is there a recommended way to do this?
