### DISCUSSION TITLE
How can I use a Quarto variable to include a code block?

### DISCUSSION THREAD

**Discussion by hugo-pires** [quarto-dev/quarto-cli#6768] [Q&A] [answered]
### Description

I am trying to de-clutter a Quarto markdown document, using variables to include code blocks. I've created a `_variables.yml` file with

    view:
        arvores: |
        {python}
        #| echo: false
        #| label: tbl-test
        #| tbl-cap: Volumes
        Markdown(tabulate(data,headers=data.columns,showindex=False))

with the following code in the `report.qmd` file:

    {{< var view.arvores >}}

But the code is not executed. Is it possible to do this? Do I need to escape any character? Would it be easier to use Quarto **includes** instead of **variables**? Nevertheless it would be more convenient to use variables, since it will allow to store multiple code chunks in a single `.yaml` file

Thank you

**Comment by mcanouil** [comment]
I believe you want to store your code cell in a Quarto document and use the include shortcode which is the tool to include and evaluate, see <https://quarto.org/docs/authoring/includes.html>.

For more, please provide a complete and small reproducible example to work with, _i.e._, a complete Quarto document or a Git repository.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by hugo-pires** [comment]
Thank you for your response

the `_variable.yaml` has the following code

````yaml
view:
    arvores: |
    {python}
    #| echo: false
    #| label: tbl-test
    #| tbl-cap: Volumes
    Markdown(tabulate(data,headers=data.columns,showindex=False))
````

and the `document.qmd` has the following code:

````qmd
# Volume

{{< var view.arvores >}}

````

**Reply by mcanouil** [reply]
Your code cell is not even a code cell.

Your file should at least looks like:

````yaml
view:
  arvores: |
    ```{python}
    #| echo: false
    #| label: tbl-test
    #| tbl-cap: Volumes
    Markdown(tabulate(data,headers=data.columns,showindex=False))
    ```
````
