### DISCUSSION TITLE
Access to nested YAML front matter values as listings fields

### DISCUSSION THREAD

**Discussion by the-solipsist** [quarto-dev/quarto-cli#6777] [Feature Requests]
### Description

Currently, I can access nested YAML front matter values in template partials. E.g., I can use `citation.container-title` in this manner:

``` 
  $if(citation.container-title)$
  <div>
    <div class="quarto-title-meta-heading">Publication</div>
    <div class="quarto-title-meta-contents">
      <p class="publication">$citation.container-title$</p>
    </div>
  </div>
  $endif$
```

However, I cannot use `citation.container-title` in the listings fields:
```
listing:
  contents: press
  type: table
  sort: date
  categories: numbered
  fields:
  - date
  - title
  - citation.container-title
  - publication
  - categories
  field-display-names: 
    citation.container-title: "Publication"
    publication: "Publication"
```

While I know I can modify the entire listings template, I'm wondering if there's an easier way to get access to the contents of `citation.container-title` for use in listings.  

Note: I can gain access to custom fields like `publication` above without any hassle.  But that would mean I copy-paste every `container-title` value into a separate 1st level YAML key called `publication`, and I'm trying to avoid doing that.
