### DISCUSSION TITLE
Parts not accepted when compiling a book

### DISCUSSION THREAD

**Discussion by ptram** [quarto-dev/quarto-cli#6786] [Q&A]
### Description

Hi,

I'm trying to create a Quarto book from a series of .md files. I'm using Quarto v1.4.355 with Pandoc v1.4.355 on Mac Monterey.

The _quarto.yml file declares at the beginning:

```
project:
  type: book

format:
  pdf:
    documentclass: scrbook

```

And then I've a book structure like this:

```
chapters:
    - Safety.md
    - Legal.md
    - part: "First part"
      chapters:
        - part: "First Part"
          chapters:
            - First_Chapter.md
            - Second_Chapter.md

```

When rendering, Quarto warns me that

```
ERROR: Project _quarto.yml validation failed.

property name part is invalid
11:     - Legal.md
12:     - part: "First Part"

```

("part" is underlined).

According to the Quarto manual, the syntax should be correct. What may I have been done wrong?

Paolo
