### DISCUSSION TITLE
Is it possible to add reading time to blog post

### DISCUSSION THREAD

**Discussion by jarrodscott** [quarto-dev/quarto-cli#6883] [Feature Requests]
### Description

Hello. I was wondering if it is possible to add reading time to individual blog posts? The times show up on the listing page but not the posts. Thanks!

**Comment by cscheid** [comment]
Yes. Go to quarto.org, click on the search button, type "Reading Time", and the first hit is this:

https://quarto.org/docs/websites/website-listings.html#listing-fields

**Comment by jarrodscott** [comment]
Thank you @cscheid . I did see that post but it is unclear to me how to get reading time on the individual post page. For example, my listing page looks something like this:

```
---
title: "Welcome to Quarto "
listing:
  field-display-names:
    title: "Lessons"
  contents: 
    - "lesson-1/index.qmd"
    - "lesson-2/index.qmd"    
  fields: [image, date, title, reading-time, description]  
  sort: "title desc"
  type: default
date-format: long
---
 ```

And then for every post a reading time is listed on the landing page. But I cannot figure out how to get reading time displayed on each post. For example, here is the `yml` header for one of the posts. 

```
---
title: "Lesson 1"
author: "me"
description: |
  In this lesson we go through the steps for creating your first site. 
date: "2024-01-03"
categories: [news, code, analysis]
image: "files/feature.png"
reading-time: true
---
```

Here I get author, description, title,and date but no reading time. For the record I am using the most up-to-date versions of Quarto, RStudio and R :)
