### DISCUSSION TITLE
Is there a recommended method to setup github workflow to publish to confluence.

### DISCUSSION THREAD

**Discussion by kristian-relectrify** [quarto-dev/quarto-cli#6915] [Q&A]
### Description

I have tried searching the docs and quarto's github repo but I could not find a guide on how to setup a workflow that publishes to confluence on merge. There are guides on how to setup a github workflow to publish to github pages, netlify, etc. but there isn't one for confluence.

**Comment by cderv** [comment]
Did you try to do what is described in https://quarto.org/docs/publishing/confluence.html but inside github action ? 

We may be missing some non-interactive configuration options. like for passing a API key as secret in a GHA workflow 🤔 

It would help to have the list of everything that may not work...

**Reply by kristian-relectrify** [reply]
I actually managed to make it work by doing what you suggested. The main challenge was finding the environment variables that the `quarto publish confluence` command was using.

**Reply by cderv** [reply]
> The main challenge was finding the environment variables that the quarto publish confluence command was using

I bet! I am not sure I know them... can you share what you did so that it can be documented in this discussion before we update our documentation ?

**Reply by kristian-relectrify** [reply]
Sure. The workflow publishes a quarto project to confluence. 

I updated the example workflow file [here](https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml) and added a publish to confluence job. The job sets up the environment variables using Github secrets and then runs the `quarto publish confluence`. 

```
    - name: Publish to confluence
      env: 
        CONFLUENCE_USER_EMAIL: ${{ secrets.CONFLUENCE_ACCOUNT_EMAIL }}
        CONFLUENCE_AUTH_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        CONFLUENCE_DOMAIN: ${{ secrets.CONFLUENCE_DOMAIN }}
      if: ${{ github.event.pull_request.merged == true }}
      run: |
        echo "Publishing quarto project to Confluence..."
        quarto publish confluence --no-browser --no-prompt 
```
