### DISCUSSION TITLE
How can I make a "boring" callout that is collapsible?

### DISCUSSION THREAD

**Discussion by DOH-SRE1303** [quarto-dev/quarto-cli#6978] [Q&A]
### Description

I am trying to make an scss rule that will make a "boring" callout that can collapse similar to how normal callouts use `collapse="true"`. However, I can't figure out how to give this functionality to a modified callout box scss rule. My modifications are just trying to make a boring callout alongside my BS Cosmo theme with:

- A title
- No background title color
- No icon
- No colors except a light gray

```scss
/*-- scss:rules --*/
.callout-boring {
  margin-left: 0em;
  padding: 0em 0.5em;
  border-left: solid #dee2e6 .3rem;
  border-right: solid 1px #dee2e6;
  border-top: solid 1px #dee2e6;
  border-bottom: solid 1px #dee2e6;
  border-radius: 5px;
}
```

Example with normal collapsing callouts inside boring one:

![image](https://github.com/quarto-dev/quarto-cli/assets/84819789/9e30bdc4-f940-4caf-8846-771f17058ffb)

```qmd
---
title: "Can I make a boring callout collapse?"
format:
  html:
    theme:
      light: [cosmo, custom.scss]
---

:::{.callout-boring}
### Boring Section

:::callout-note
### Not boring
:::

:::callout-warning
### Not boring
:::

:::callout-tip
### Not boring
:::

:::

```

How might I add a collapse functionality here similar to default callouts with `collapse="true"`?

Quarto version: `1.3.353`
