### DISCUSSION TITLE
How do I hide blog post body excerpts from the main page?

### DISCUSSION THREAD

**Discussion by patgd** [quarto-dev/quarto-cli#6995] [Q&A] [answered]
### Description

These are the excerpts I would like to hide:

<img width="1080" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/88806542/024a011d-300a-452e-877f-9e94fa70840b">

I've tried this `blog:…` snippet in the `_quarto.yml` file without success:
```yml
project:
  type: website

website:
  title: "patgd"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/

blog:
  preview:
    show_excerpt: false

format:
  html:
    theme: cosmo
    css: styles.css
```
