### DISCUSSION TITLE
How to add author's name and date on each slide of my presentation ?

### DISCUSSION THREAD

**Discussion by ddotta** [quarto-dev/quarto-cli#7007] [Q&A] [answered]
### Description

In a quarto presentation, I'd like to display the author's name and date at the bottom of each slide.  

I've added this to my CSS, but it only works on the first page of my revealjs presentation.

````css
p.date{
  font-size: 65%;
  position: absolute;
  bottom: -3%;
  right: 0%;
}

.quarto-title-author-name {
  font-size: 65%;
  position: absolute;
  bottom: -3%;
  left: 0%;
}
```` 
Any idea ?
Many thanks in advance !
