### DISCUSSION TITLE
PDF table output styles

### DISCUSSION THREAD

**Discussion by GabeNazario** [quarto-dev/quarto-cli#7015] [Q&A]
### Description

Hello! I'm new to quarto and I'm trying to create a PDF report using Jupyter Lab as I progress with my EDA.
I want to format my output tables, but since I'm working on Jupyter the examples online don't help much. And since I'm new I might be missing the message.

In my YAML header I have:

```
---
title: "**Title Here**"
subtitle: "Subtitle here"
author: "**_It'sa Me!_**"
toc: true
number-sessions: true
highlight-style: pygments
urlcolor: blue
latex-engine: xelatex
format:
    pdf:
        documentclass: report
        echo: false
        geometry:
            - top=30mm
            - left=20mm
            - right=20mm
        color-links: true
        
jupyter: python3
---
```

Than for my output I have a normal looking table like this: [https://quarto.org/docs/authoring/images/crossref-table-knitr.png](https://quarto.org/docs/authoring/images/crossref-table-knitr.png)
However, I want to alternate the rows color, adding a grey background to facilitate reading. Like this one: [https://pbs.twimg.com/media/FWWdWvwX0AEEGAC?format=jpg&name=900x900](https://pbs.twimg.com/media/FWWdWvwX0AEEGAC?format=jpg&name=900x900)

I understand that the second image uses R, and I'm using Python o Jupyter, but I just wanted to exemplify the type of table I want. I could not figure out a way to work with knitr or kable using only python. not even sure if that is possible.

This formatting would help me a bunch, because I also have a Multi Indexed table I want to tabulate nicely before printing, but I'm struggling to layer the rows inside the index.

I appreciate any help and apologize if there is a major oversight on my part. 

Cheers,
Gabe
