### DISCUSSION TITLE
Can the _quarto.yml file be defaulted to output notebooks with a render?

### DISCUSSION THREAD

**Discussion by jlperla** [quarto-dev/quarto-cli#7122] [Q&A] [answered]
### Description

I have a `_quarto-solutions.yml` file something like this:

```yaml
project:
  output-dir: .solutions_output
  render:
    - assessments/problem_set_1.qmd
    - assessments/problem_set_2.qmd
  post-render:
    - python utilities/rename_solution_files.py
```
I only really want the jupyter notebooks.  Calling with `quarto render --profile solutions --to ipynb` works fine, but is there any way to pass in the `format:` metadata to make that the default?  I tried to put a

I want to run this outputing the ipynb only by default, if that is possible?    I tried putting `format: ipynb` at the bottom and the yml validates but it generates HTML files.  Is there a better `type` as well to put for the project when I just want a collection of jupyter notebooks?
