### DISCUSSION TITLE
How do I "include other formats" in a quarto book.

### DISCUSSION THREAD

**Discussion by n8craig** [quarto-dev/quarto-cli#7124] [Q&A] [answered]
### Description

I don't understand how to obtain the "[other formats](https://quarto.org/docs/output-formats/html-multi-format.html)" link in the TOC as part of a quarto book. I can get this functionality to work on individual pages, but not within a book.

I created a brand new default quarto book project, and made two minor edits. Following documentation for [including other formats in HTML documents at the project level](https://quarto.org/docs/output-formats/html-multi-format.html#controlling-formats-at-a-project-level), I edited `_quarto.yml` to include `toc: true` to the front matter such that it looks like:

```
---

format:
  html:
    toc: true
    theme: cosmo
---

```

Then in the `index.qmd` file, I added the following sample front matter from the documentation:

```
---
format: 
  html: default
  pdf: default
---
```

I expected the other formats link to appear in the TOC, but it does not. I'm running quarto v1.3.450.

If I copy the `index.qmd` file to another directory and add the following to the front matter the other formats link appears when previewing.

```
---
title: Sample Page
author: Norah Jones
date: last-modified
toc: true
format: 
  html: default
  pdf: default
---
```

**Comment by dragonstyle** [comment, marked as answer]
Currently books have their own mechanism for advertising alternative formats of the book (since it is a top level concept in books [e.g. a PDF of the whole book is produced, not individual pages], it is slightly different than 'other formats'). You can control this using `downloads` like so:

```yaml
project:
  type: book

book:
  title: "Book"
  author: "Norah Jones"
  date: "10/3/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  downloads: [pdf]

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```
