### DISCUSSION TITLE
How can I get this gtsummary object to print as Latex?

### DISCUSSION THREAD

**Discussion by e05bf027** [quarto-dev/quarto-cli#7170] [Q&A] [answered]
### Description

I am writing up a thesis document, and am using Quarto to render the document as a pdf.

I have a table that summarises the characteristics of a sample of patients. I have used `gtsummary` to create it. I believe I am following all instructions correctly. I can render the table if I remove the `as_latex()` command from my piped workflow.

The code to create the is below, and works correctly without the `as_latex()` command.

```
demo_summary%>% 
  select(-c(patient_id,
            pathogenic_factor,
            ards_risk_factor,
            adm_date,
            adm_location,
            dc_date_time,
            ventilator)) %>% 
  relocate(bmi, .after = weight_kg) %>% 
  tbl_summary(by = NULL,
              statistic = list(all_continuous() ~ "{mean}, ({sd})",
                               all_categorical() ~ "{n} ({p}%)"),
              digits = list(all_continuous() ~ 1,
                            all_categorical() ~ 0),
              label = list(gender ~ 'Gender',
                           age_years ~ 'Age (years)',
                           height_cm ~ 'Height (cm)',
                           weight_kg ~ 'Weight (kg)',
                           bmi ~ 'BMI',
                           ards_type ~ 'ARDS classification',
                           adm_location ~ 'Admitting location',
                           los_days ~ 'LOS (days)',
                           apache_ii ~ 'Apache II',
                           total_proning_sessions ~ 'Proning sessions',
                           outcome ~ 'Outcome'),
              missing = 'ifany',
              missing_text = 'Not recorded') %>%
  bold_labels() %>% 
  as_gt() %>% 
  as_latex()
```
The `gtsummary` package states a number of dependencies required to ensure the table can indeed be rendered as Latex. It states:

> LaTeX packages required to generate tables are: booktabs, caption, longtable, colortbl, array.
>
> In the event packages are not automatically added during the render phase of the document, please create and include a style file to load them.
>
> Inside the document's YAML metadata, please include:
>
> output:
>   pdf_document: # Change to appropriate LaTeX template
>     includes:
>       in_header: 'gt_packages.sty'
> The gt_packages.sty file would then contain the listed dependencies above:
>
>   \usepackage{booktabs, caption, longtable, colortbl, array}

I have executed this step slightly differently, but the dependencies are indeed there. My YAML is a bit more complicated because I need to create an entire document of a few hundred pages, and output it as both Word and PDF. However, it does work correctly. The relevant portion of my YAML is:

```
format:
  pdf:
    documentclass: scrreprt
    papersize: a4
    mainfont: Baskerville
    sansfont: Baskerville
    linestretch: 1.5
    monofont: 'JetBrains Mono'
    monofontoptions: 
      - Scale=0.6
    microtypeoptions:
      - protrusion=true
      - verbose=true
    fontsize: 11pt
    include-in-header: 
      text: |
        \usepackage{booktabs}
        \usepackage{caption}
        \usepackage{longtable}
        \usepackage{colortbl}
        \usepackage{array}
        \usepackage{tabulary}
        \usepackage{siunitx}
        \usepackage{multirow}
        \usepackage{graphicx}
        \usepackage{setspace} \onehalfspacing
    template-partials: 
      - toc.tex
      - before-body.tex
    toc: true
    toc-depth: 3
    toc-title: Contents
    lot: true
    lof: true
    number-sections: true
    geometry: 
    - top=30mm
    - bottom=30mm
    - left=30mm
    - right=30mm
    link-bibliography: false
    link-citations: false
```
As you can see, the Latex dependencies are there. In the final pdf the table is absent. Anyone any idea what I am doing wrong?
