### DISCUSSION TITLE
How do I get  `issue-url` to work?

### DISCUSSION THREAD

**Discussion by Aariq** [quarto-dev/quarto-cli#7203] [Q&A] [answered]
### Description

I'd like to specify a particular issue template that is opened with the "Report an issue" link in a Quarto book. The [documentation](https://quarto.org/docs/websites/website-navigation.html#github-links) says to use the `issue-url` parameter, but it doesn't seem to be working.  No matter what I put in that field, the "Report an issue" link opens a blank issue.

Here's the top of my `_quarto.yml`

```yaml
project: 
  type: book

book:
  title: "CCT Data Science Group Procedures"
  # cover-image: cover.png
  search: true
  site-url: https://cct-datascience.github.io/group-procedures/
  repo-url: https://github.com/cct-datascience/group-procedures
  repo-actions: [edit, issue]
  issue-url: https://github.com/cct-datascience/group-procedures/issues/new?template=suggest-edit.md
```
