### DISCUSSION TITLE
How to cross reference an entire chapter in a book with pdf output?

### DISCUSSION THREAD

**Discussion by nonsciencemark** [quarto-dev/quarto-cli#7226] [Q&A]
### Description

If I have a book project with the `_quarto.yml` file:

```
project:
  type: book

book:
  title: "A book"
  chapters:
    - index.qmd
    - introduction.qmd
    - main.qmd
    - conclusion.qmd
format:
  pdf:
    documentclass: scrreport
```

how can I reference an entire chapter? I know that I can reference sections _inside_ chapters (e.g. `See Chapter @sec-introduction-section1`) but that gives `See Chapter 1.1` rather than just `Chapter 1`. Since the chapters are defined in the YAML, I can't (to my knowledge) add a `{#sec-name}` identifier for use later, so not sure what to do?
