### DISCUSSION TITLE
Is it possible to add `reading-time` to a regular (non-listing) webpage?

### DISCUSSION THREAD

**Discussion by jonjoncardoso** [quarto-dev/quarto-cli#7248] [Q&A]
### Description

I know I can add `reading-time` to pages within [listings](https://quarto.org/docs/websites/website-listings.html) but I wonder if it is possible, even if it requires a bit of hacking, to add reading time to regular pages that are not under a blog-like structure?

I've tried:

```yaml
---
title: "🧐 My page"
reading-time: true
---
```

But nothing happens, of course.
