### DISCUSSION TITLE
When rending profiles for a website, .qmd files that are not in the profile yml still render in the docs output folder.

### DISCUSSION THREAD

**Discussion by Barnes7599** [quarto-dev/quarto-cli#7263] [Q&A] [answered]
### Description

I've set up multiple profiles, each with its own output folder. For example, the "hr" profile outputs to an "hr" folder, while the "vp" profile outputs to a "vp" folder. In the "vp" profile, a scorecard is generated, and its link is visible in the navbar. On the other hand, the "hr" profile doesn't generate this scorecard link, and that's exactly how I want it. The issue arises when I search for "people score", once the site is rendered.  Despite not having the scorecard link in the navbar, the "hr" profile's document folder still shows it in search results. How can I prevent this scorecard link from appearing in the search results for the "hr" profile?

_quarto.yml
```
project:
  type: website

profile: 
  default: hr

website:
  title: "Insights"
  favicon: "images/favicon.png"
  back-to-top-navigation: true
  search: 
    location: navbar
    type: textbox
    copy-button: true
    collapse-after: 3
  page-footer:
   background: black
   foreground: white
   left: 
     - icon: images/left-footer.png
       href: learn-more/about/about.qmd
       aria-label: "learn more"
   right:
     - icon: github
       href: https://......
       aria-label: "GitHub Account"
  navbar:
    title: false
    pinned: true
    logo: images/logo.png
    alt-logo: "Website logo"
    collapse-below: lg
    background: black
    foreground: white


format:
  html:
    theme: css/styles.scss
    toc: false
    anchor-sections: false

from: markdown+emoji
editor: source
link-external-newwindow: true
```

In the below hr profile there is no link to the scorecard

_quarto-hr.yml
```
project:
  output-dir: hr
execute: 
  freeze: false

website:
  navbar:
    right:
      - text: "Insights"
        menu:
        - href: insights-vault.qmd
          text: "Insights Vault"
        - href: insights/weekly/weeklyreport.qmd
          text: "The Daily Report"
        - href: insights/quarterly/quarterly-updates.qmd
          text: "The Quarterly"
        - href: insights/competitor-guides/index.qmd
          text: "Competitive Intelligence"
      - text: "Data"
        menu:
        - text: "Dashboards"
          href: data/dashboards/index.qmd
        - text: "Excel Tools"
          href: data/excel-tools/index.qmd
      - text: "Topics"
        menu:
        - text: "Hiring"
          href: "data/#category=Talent Acquisition"
        - text: "Workforce Composition"
          href: "data/#category=Workforce Composition"
        - text: "Attrition"
          href: data/#category=Attrition
      - text: "Learn More"
        menu:
        - text: "Our Team"
          icon: bi-person-heart
          href: learn-more/about/about.qmd
        - text: "Our Methodology"
          icon: bi-file-spreadsheet
          href: learn-more/methodology.qmd
        - text: "How to Partner"
          icon: bi-people-fill
          href: learn-more/parnter.qmd
        - text: "Enablement / CoP"
          icon: bi-gear-wide-connected
          href: learn-more/enablement.qmd
        - text: "Report a Bug"
          icon: bug-fill
          href: "https://....../issues/new/choose"
        - text: "Definitions"
          icon: book-fill
          href: "definitions.qmd"
```

In the below vp profile there is a link to the scorecard

_quarto-vp.yml
```
project:
  output-dir: vp
execute: 
  freeze: false

website:
  navbar:
    right:
      - text: "Insights"
        menu:
        - href: insights-vault.qmd
          text: "Insights Vault"
        - href: insights/weekly/weeklyreport.qmd
          text: "The Daily Report"
        - href: insights/quarterly/quarterly-updates.qmd
          text: "The Quarterly"
        - href: insights/competitor-guides/index.qmd
          text: "Competitive Intelligence"
        - href: score-card/people-scorecard.qmd
          text: "People Scorecard"
      - text: "Data"
        menu:
        - text: "Dashboards"
          href: data/dashboards/index.qmd
        - text: "Excel Tools"
          href: data/excel-tools/index.qmd
      - text: "Topics"
        menu:
        - text: "Hiring"
          href: "data/#category=Talent Acquisition"
        - text: "Workforce Composition"
          href: "data/#category=Workforce Composition"
        - text: "Attrition"
          href: data/#category=Attrition
      - text: "Learn More"
        menu:
        - text: "Our Team"
          icon: bi-person-heart
          href: learn-more/about/about.qmd
        - text: "Our Methodology"
          icon: bi-file-spreadsheet
          href: learn-more/methodology.qmd
        - text: "How to Partner"
          icon: bi-people-fill
          href: learn-more/parnter.qmd
        - text: "Enablement / CoP"
          icon: bi-gear-wide-connected
          href: learn-more/enablement.qmd
        - text: "Report a Bug"
          icon: bug-fill
          href: "https://.../issues/new/choose"
        - text: "Definitions"
          icon: book-fill
          href: "definitions.qmd"

```
