### DISCUSSION TITLE
Including JS from _quarto.yml not working

### DISCUSSION THREAD

**Discussion by neeldhara** [quarto-dev/quarto-cli#7283] [Q&A] [answered]
### Description

I had this issue in my main repo, so recreated a MWE as follows: made a new quarto project (I'm using the VSCode extension) and changed `_quarto.yml` to:

```
project:
  type: website
  
website:
  title: "FooBar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    js: scripts.js
    css: styles.css
    toc: true
```

which is to say, I only added the line `js: scripts.js` and added a file called `scripts.js` in the root directory. I haven't made any other changes to the barebones repo.

However, this doesn't seem to get picked up when I render the project? However, this seems to work fine on [my website](https://github.com/neeldhara/quartosite) (but not on my local notes repo), so I am left a little puzzled. Sorry if I am missing something obvious 😬

To be honest I don't remember where I picked this up from when I was working on my website: I can't find this directive in the docs any more. Maybe it's not a thing (any more)?

**Comment by mcanouil** [comment, marked as answer]
I never saw `js` key in Quarto.
Usually, JavaScript are included with for example:

```yaml
include-after-body:
  text: |
    <script type="application/javascript" src="myscript.js"></script>
```

Note that the `include-*` key to use will highly depends on what your JavaScript script does (mainly why `js` does not seem right at all).

If Quarto does not pick up the dependency to your website location, see <https://quarto.org/docs/websites/website-tools.html#site-resources>.
