### DISCUSSION TITLE
Updating twitter icons in quarto to that of X

### DISCUSSION THREAD

**Discussion by dweng0** [quarto-dev/quarto-cli#7284] [Q&A] [answered]
### Description

Hi all, in the footer of our  `_quarto.yml` file, we leverage the built in icons by describing them like this:

``` yml
 left:
      - icon: github
        href: https://github.com/...
      - icon: twitter
        href: https://twitter.com/...
      - icon: discord
        href: https://discord.com/invite/...
      - icon: youtube
        href: https://www.youtube.com/channel/...
```

My question is, now that twitter has been "rebranded" is there any roadmap or plan to change the twitter icon? If not what would be a good work around to maintain the same look and feel?

I'm aware that [Font Awesome](https://fontawesome.com/icons/x-twitter?f=brands&s=solid) do have an x logo in circulation at the moment.
