### DISCUSSION TITLE
Remove trailing space in custom crossref prefix and name

### DISCUSSION THREAD

**Discussion by grasshoppermouse** [quarto-dev/quarto-cli#7317] [Q&A] [answered]
### Description

Supplementary figures and tables are often numbered like so: Figure S1, Figure S2, Table S1, Table S2, and so forth (see attached image). The new custom crossref feature in the pre-release version of Quarto adds a space after the prefix and name, so the numbering comes out: Figure S 1, Figure S 2, ...

Is there a way to remove the space between the S and the number?

````
crossref:
  custom: 
    - kind: float # crossreferenceable elements with captions are `float`
      prefix: Figure S # used as the prefix for reference in output ("In Figure 1, ..")
      name: Figure S # used as the prefix for captions ("Figure 1: ..")
      ref-type: sfig # used as the prefix for the reference identifier ("In @fig-1, ...")
````

![Screenshot 2023-10-20 at 4 28 36 PM](https://github.com/quarto-dev/quarto-cli/assets/7534138/882890a1-c246-4718-aaeb-f65b834ab730)

**Comment by cscheid** [comment, marked as answer]
Thanks for the question. It's a totally reasonable request and part of #4944 that we hadn't gotten around to. I added the feature just now, currently only tested in LaTeX and HTML. Once the [test suite passes](https://github.com/quarto-dev/quarto-cli/pull/7320), this will be in our 1.4 pre-release.

We're still working on documentation, but here's how a minimal example will look:

<table>
<tr><td>

````
---
title: Proposed syntax for custom crossrefs
format: pdf
keep-tex: true
crossref:
  custom:
    - kind: float
      reference-prefix: Diagram
      caption-prefix: Diagram
      key: dia
      latex-env: diagram
      latex-list-of-file-extension: lod
    - kind: float
      reference-prefix: Table S
      space-before-numbering: false
      caption-prefix: Table S
      key: supptbl
      latex-env: supptbl
      latex-list-of-file-extension: lost
      latex-list-of-description: Supplementary Table
---

## Lists test

```{=latex}
\listofsupptbls
\listofdiagrams
```

## Content

::: {#dia-1}
![](../img/surus.jpg)

A diagram
:::

See @dia-1.

::: {#supptbl-1}

```{=html}
<table>
  <thead>
    <tr><td>a</td><td>b</td></tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>2</td></tr>
    <tr><td>3</td><td>4</td></tr>
  </tbody>
</table>
```
A caption.

:::

See @supptbl-1.
````
</td><td>
<img width="469" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/bcadc0f9-e160-4d7a-90c3-4f66bf2e4ae0">

<img width="471" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/60f5a61d-9891-48c8-8098-671baa3d5f40">

</td></tr></table>

Do note the changes on the YAML metadata.
