### DISCUSSION TITLE
How do I add multiple lines to a page-footer in Quarto book?

### DISCUSSION THREAD

**Discussion by jbrick55** [quarto-dev/quarto-cli#7342] [Q&A] [answered]
### Description

I would like to add another line to the page-footer in a Quarto book. 
In my yml file I have...

`page-footer:
    
    center:
          - text: "first line of text"
          - text: "second line of text"`     

This seems to align the text horizontally. Any other ideas?

**Comment by mcanouil** [comment]
Use multiline yaml markup.

```yaml
page-footer:
  center: |
    One line.
    A second line.
```

**Reply by jbrick55** [reply]
Thanks!
That still doesn't work for me. 
Is the 'pipe' one space from the colon after center?

**Reply by mcanouil** [reply]
Copy the code use the copy button.

> That still doesn't work for me.

It's not really helpful.
Could you elaborate a bit.

**Reply by jbrick55** [reply]
They still just show up as one line. I even copied the code from your reply.
<img width="223" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/54671911/12c2384f-0c52-4983-8870-ca0cb7896ebd">
This is my code...
```yaml
page-footer:
    background: light
    center: |
      One line.
      A second line.
```
I'm also using Rstudio.

**Reply by jbrick55** [reply, marked as answer]
I added <br> at the end of the first line and it worked!
```yaml
page-footer:
    background: light
    center: |
      One line. <br>
      A second line.
```

**Reply by jimjam-slam** [reply]
@jbrick55 In Markdown, you need two new lines to start a new paragraph:

```yaml
page-footer:
    background: light
    center: |
      One line.
      
      A second line.
```

(if you do it this way, make sure the blank line in between is still indented up to where the text starts!)

Inserting a manual HTML line break with `<br>` might also be fine for your purposes, though!
