### DISCUSSION TITLE
Add custom link to a listing site

### DISCUSSION THREAD

**Discussion by sagikazarmark** [quarto-dev/quarto-cli#7376] [Q&A] [answered]
### Description

I use quarto to write most of my presentation slides. I publish them here: https://slides.sagikazarmark.hu/

From time to time, though, I need to use another solution to create a slide deck (Google Slides, Powerpoint, etc).

I'd still love to link to those presentations from my slides index.

Is there a way to do that (add custom links or redirections)?

I wouldn't mind creating a qmd file and adding something to the frontmatter if I can make Quarto generate a link to an external URL.

Any pointers would be appreciated. Thanks!

**Comment by mcanouil** [comment, marked as answer]
Use something below as documented in <https://quarto.org/docs/websites/website-listings.html#yaml-listing-content>:

```yaml
listing:
  sort: "date desc"
  type: grid
  categories: true
  sort-ui: true
  filter-ui: true
  max-description-length: 300
  fields: [image, title, description, categories]
  contents:
    - path: https://github.com/mcanouil/quarto-version-badge
      image: /projects/quarto-extension.png
      title: "Version Badge"
      description: "Version Badge is an extension for Quarto to provide a shortcode to display software version."
      date: "2023-06-20"
      categories: [Quarto, Extension, HTML]
```
