### DISCUSSION TITLE
link-citation suppress-bibliography doesn't compile since pandoc 3.1.7

### DISCUSSION THREAD

**Discussion by danieltomasz** [quarto-dev/quarto-cli#7431] [Q&A] [answered]
### Description

I am using quarto 1.4.451, I am wrtiing my my thesis via quarto and latex, recently something changed so I cannot compile my document with

```
suppress-bibliography: true
citeproc: true
```
I need to to set `suppress-bibliography: false`, additionally when I downgrade to 1.3.x I can compile the same document.
The document was fine 1 month ago.
I can paste Minimal reproducible example, but maybe there is a quick reply?

**Comment by cscheid** [comment]
> I can paste Minimal reproducible example

Please do that, thank you.

**Comment by danieltomasz** [comment]
I isolated the lines causing troubles
1. create the default project in vscode

replace format with thos code chunk
```
format:
  pdf:
    link-citations: true
    pdf-engine: xelatex

suppress-bibliography: true
citeproc: true
```

so `_quarto.yml` looks like this
```
project:
  type: book

book:
  title: "test"
  author: "Norah Jones"
  date: "10/31/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    link-citations: true

suppress-bibliography: true
citeproc: true
```

the the default example (with knuth citation) will not compile via ` quarto preview`


```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
Undefined control sequence.
l.172 See Knuth (\citeproc
                          {ref-knuth84}{1984}) for additional discussion of 
```
