### DISCUSSION TITLE
About the `when-meta` and `unless-meta` features

### DISCUSSION THREAD

**Discussion by sbrisard** [quarto-dev/quarto-cli#7463] [Q&A] [answered]
### Description

When browsing through the Quarto sources, I stumbled upon this test: https://github.com/quarto-dev/quarto-cli/blob/1bfd06d1f59153ddd9785faadb1cf93467f91c57/tests/docs/smoke-all/conditional-content/meta.qmd

The feature seems to implement exactly what I was looking for (conditional content based on the value of a metadata flag).

However, I was unable to make this feature work.

```
---
lang: fr
title: "TD1 – Hypothèses pour le calcul en flexion simple"
date: last-modified
author: Sébastien Brisard
filters:
  - latex-environment
crossref:
  eq-prefix: ""
  sec-prefix: ""
  exr-title: "Question"
toc: true
number-sections: true
number-depth: 2
format:
  latex:
    documentclass: scrartcl
    classoption: [DIV=15, headsepline, footsepline, parskip=half, fleqn]
    papersize: A4
    mainfont: XITS
    mathfont: XITS Math
    include-in-header: ./header.tex
    include-before-body:
      text: \thispagestyle{scrheadings}
showsol: false
---

::: {.content-visible when-meta="showsol"}
Voici la solution du problème.
:::
```

always displays the conditional, regardless of the value `showsol`.

Am I doing something wrong? Is this feature not yet functional? I am running `Quarto 1.3.450`.

Thanks!
