### DISCUSSION TITLE
How to add tooltip to navbar icons?

### DISCUSSION THREAD

**Discussion by LSYS** [quarto-dev/quarto-cli#7510] [Q&A]
### Description

How do I add a tooltip to custom icons in the navbar?

I'm following the Quarto doc, adding a GitHub icon into the navbar:
```qmd
---
website:
  navbar:
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
---
```
(From: [https://quarto.org/docs/reference/projects/websites.html#nav-items](https://quarto.org/docs/reference/projects/websites.html#nav-items))

But if I hover my mouse cursor, no tooltip appears. 

The tooltip I want is something that looks like this: when I hover the mouse cursor over the **Downloads icon**:
![image](https://github.com/quarto-dev/quarto-cli/assets/10510571/d4e3bf82-6a83-4026-8522-3d298d3401ff)

**Comment by mcanouil** [comment]
I don't think there is an easy way.
You could use JavaScript to use `aria-label` as tooltip value.

Here is a quick and dirty script as an example:

```yaml
include-after-body:
  - text: |
      <script type="text/javascript">
      var elements = document.querySelectorAll('[aria-label]');

      for (var i = 0; i < elements.length; i++) {
        var ariaLabel = elements[i].getAttribute('aria-label');
        elements[i].setAttribute('data-bs-title', ariaLabel);
        elements[i].setAttribute('data-bs-toggle', 'tooltip');
      }
      const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
      const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
      </script>
```

**Reply by davidleitch1** [reply]
In a similar vein is it possible to have hover over a menu item? I would like to advise viewers that there will be delay on click

**Reply by mcanouil** [reply]
You'll have to develop a solution in a similar way as the proposed solution for tooltip.

**Reply by davidleitch1** [reply]
Thanks. Quarto is a revelation to me. Got to it via reference from Holoviz Blog where I have been using Panel. Now have to think about how to integrate Holoviz Panel app with 9 templates into a Quarto website rather than redirect to a separate server. Too much chat..

**Reply by e-miz** [reply]
Thank you for the workaround!

I was using this when I noticed that when the menus are hidden (e.g. when viewing on a phone), the buttons are unusable. Clicking or tapping instead shows the tooltip. Right clicking/long press doesn't work to expose any kind of hyperlink.

![image](https://github.com/quarto-dev/quarto-cli/assets/12023516/f7cfdcce-c222-483a-a95c-d050e974fb6a)

Unfortunately I don't know much javascript so I can't provide a fix. Advice is appreciated, but I can also live without this.

**Reply by mcanouil** [reply]
@e-miz Could you share a small reproducible setup with this and the Quarto version you used?

**Reply by e-miz** [reply]
Sure. I can reproduce this in quarto 1.4.550 using the default website project generated by the VSCode Extension.

The only I changed was the `_quarto.yml`:

```yml
project:
  type: website

website:
  title: "quarto-navbar-icon-tooltip"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body:
    - text: |
        <script type="text/javascript">
        var elements = document.querySelectorAll('[aria-label]');

        for (var i = 0; i < elements.length; i++) {
          var ariaLabel = elements[i].getAttribute('aria-label');
          elements[i].setAttribute('data-bs-title', ariaLabel);
          elements[i].setAttribute('data-bs-toggle', 'tooltip');
        }
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
        </script>
```
