### DISCUSSION TITLE
How to properly embed cells from Jupyter notebook with R kernel?

### DISCUSSION THREAD

**Discussion by lisa-wm** [quarto-dev/quarto-cli#7515] [Q&A] [answered]
### Description

I'm trying to build an `html` document that has tabsets for R and Python code. Both code snippets are to be embedded from (two different) Jupyter notebooks (with R and Python kernels resp.). However, embedding from the R `ipynb` causes quarto code to be displayed in a weird manner (see screenshot), and also breaks the tabset layout. How can I avoid this? Thank you! 🙏🏻 (PS: there is quite some nesting of conditional output and HTML options going on.)

![html_output](https://github.com/quarto-dev/quarto-cli/assets/63582944/c6a1e2c3-9ea0-4390-8852-9643fdc66a75)

```
---
title: "foo"
subtitle: "bar"
---

::: {.content-hidden when-format="pdf"}
::: {.hidden}
{{< include baz.qmd >}}
:::
:::

## Exercise 1

(@) Do this
  
::: {.content-visible when-profile="solution"}
<details> 
<summary>**Solution**</summary>

::: {.panel-tabset}
### R
{{< embed _r.ipynb#hro echo=true >}}

### Python
{{< embed _python.ipynb#hro echo=true >}}
:::
</details> 
:::
```

Notebook metadata for notebook with Python kernel:
```
"metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 }
```

Notebook metadata for notebook with R kernel:
```
"metadata": {
    "kernelspec": {
      "display_name": "R",
      "name": "ir"
    },
    "language_info": {
      "name": "R"
    },
    "colab": {
      "provenance": []
    }
  }
```

Other `quarto` options used (in `_quarto.yml`):
```
theme:
  light: [flatly, _quarto/theme.scss]
  dark: [darkly, _quarto/theme.scss]
format: 
  html:
    toc: true
    code-fold: false
    mathspec: true
    latex_engine: pdflatex
jupyter: python3
notebook-links: global
```
`theme.scss` merely defines
```
/*-- scss:defaults --*/
$link-color: #6495ed;
```
