### DISCUSSION TITLE
Let sidebar automatic listing respect sorting options

### DISCUSSION THREAD

**Discussion by homerhanumat** [quarto-dev/quarto-cli#7532] [Feature Requests]
### Description

In pages with a listing, one can specify criteria by which to sort the items to be listed.  I find that when one attempts to specify sorting criteria for automatic listing of sidebar items, the relevant material in `_quarto.yml`, e.g., 

```yml
sidebar:
    - id: none
      style: "docked"
      background: light
      collapse-level: 2
      contents: posts
      sort:
        - "date desc"
```

processes without error, but the sorting option is ignored.  See [this repo](https://github.com/homerhanumat/test-ojs) for a minimal example.
