### DISCUSSION TITLE
Disable comments/utterances on an individual post

### DISCUSSION THREAD

**Discussion by bryanhanson** [quarto-dev/quarto-cli#754] [Q&A] [answered]
I can turn on commenting via utterances using

```
website:
  comments:
    utterances:
      repo: bryanhanson/CSR
```

but what is the incantation to disable comments on individual blog posts?  Neither `disable_comments: true` not `disable-comments: true` works.

**Comment by jjallaire** [comment, marked as answer]
Thanks for the feedback! We didn't have a way to do this but I just added it: https://github.com/quarto-dev/quarto-cli/commit/7d386d4c38bfd998e24f6c5db246a7d827727b07

This should work on an individual page:

```yaml
---
title: "My Document"
comments: false
---
```
