### DISCUSSION TITLE
quarto-blog article: Author and Affiliation not linked to a url

### DISCUSSION THREAD

**Discussion by ManuelSpinola** [quarto-dev/quarto-cli#764] [Q&A]
Do the Author and Affiliation should be linked to a url like in a distill article?

**Comment by dragonstyle** [comment]
Yes they can (I meant to note this in my reply to your original issues since you shared the sample document- sorry!). Ideally, you would write it like:

```yaml
  - name: "Cat Memes"
    url: http://example.com/catmemes
    affiliation:
      name: Univ of Massachusetts
      url: http://www.umass.edu/
    orcid: 0010-0332-7843-9328
```

though you could also write:

```yaml
  - name: "Cat Memes"
    url: http://example.com/catmemes
    affiliation: Univ of Massachusetts
    affiliation-url: http://www.umass.edu/
    orcid: 0010-0332-7843-9328
```
