### DISCUSSION TITLE
Add a custom icon from the local drive to the navbar.

### DISCUSSION THREAD

**Discussion by dalmijn** [quarto-dev/quarto-cli#7640] [Q&A] [answered]
### Description

It's maybe a bit of a silly question, but how could I set an icon in the navbar that is based on an image (e.g. .svg) from the local drive.

So for example this is easily done for a github link:
```yaml
  navbar:
    right:
     - icon: github
       href: <some link to github>
```

But if I cannot get it to work with a local image, for instance:
(This wont show any image, but will leave something to click on in the navbar)
```yaml
  navbar:
    right:
     - icon: _static/<some local image>.svg
       href: <some link to somewhere>
```

I'm wondering if this is possible and whether I'm missing something. 
It's most likely that I just don't know...

Running on quarto 1.3.450 (stable release from the website).
(fontawesome extension is ofcourse installed.)

Thanks in advance!

**Comment by cderv** [comment]
I believe this fields only support Bootstrap icons as documented: https://quarto.org/docs/reference/projects/websites.html#nav-items

> Name of bootstrap icon (e.g. github, twitter, share) See https://icons.getbootstrap.com/ for a list of available icons

@dragonstyle any plans of making custom icons available ?

**Comment by mcanouil** [comment]
You can use the 'text' key wich supports markdown, thus anything you want.

**Reply by cderv** [reply]
Awesome ! Thanks @mcanouil !

**Reply by mcanouil** [reply]
Side note: there are few places where the key does not support markdown such as in 'tools' (an issue is opened)

**Comment by dalmijn** [comment]
@mcanouil and @cderv, thanks for the quick responses, I'll try it out and I'll get back to you.

**Comment by EllaKaye** [comment]
Hello! As per the suggestion above, I'm trying this:

```
  navbar:
    right:
      - text: ![](images/posts.png)
        href: posts.qmd
```

but I'm getting the error `ERROR: YAMLException: tag suffix cannot contain flow indicator characters (_quarto.yml, 9:36)`. Is there a way to use an image in this way? I've also tried with a .svg file, but go the same error.

**Reply by mcanouil** [reply]
Did you try using double quotes around your text for `text`?

**Reply by EllaKaye** [reply, marked as answer]
Ah, yes, that's it @mcanouil. I had tried quotes around the file name, but not around the entire chunk of text. The latter works, i.e.

```
  navbar:
    right:
      - text: "![](images/posts.png)"
        href: posts.qmd
```

Thanks for your prompt and helpful reply (as ever!)

**Reply by dalmijn** [reply]
@mcanouil, terribly sorry for not having responded afterwards. Ill mark this as the awnser. Thanks you!

**Reply by burgerga** [reply]
Don't forget to include a `/` in front to use the absolute image path, otherwise the icons only load on the front page but not when you go to a page that is in a subfolder.

**Comment by astrowonk** [comment]
I had to tweak this to get it work. Initially, markdown pointing to an SVG showed nothing (though the SVG was loading successfully in devtools). I converted the SVG to PNG and that .. sortof worked except the image was gigantic.  The YAML below worked for both SVG and PNG: specifying the height:

```
  navbar:
    right:
    - text: "![](bluesky-brands-solid.svg){height=1em}"
      href: https://github.com/astrowonk
    - text: "![](bluesky-brands-solid.png){height=1em}"
      href: https://bsky.app

```

I had initially solved my specific issue by installing the excellent [Fontawesome extension](https://github.com/quarto-ext/fontawesome) which has a Bluesky brand icon. (Then the solution is just `"{{< fa brands bluesky >}}"`).

Using an image via markdown as above also works, but it doesn't get mouse-over color changes like a BI or FA icon. (The Bluesky icon should come to Bootstrap [some day](https://github.com/twbs/icons/issues/1886)).
