### DISCUSSION TITLE
Sidebar contents: Recursive with glob pattern

### DISCUSSION THREAD

**Discussion by sda030** [quarto-dev/quarto-cli#7652] [Q&A]
### Description

I have a subfolder Publications, containing multiple sub-folders (reports x,y,z) and in each of these I have chapter documents that I want to list in a sidebar (all starting with digits), an index.qmd, and a full_report.qmd which stitches together all the chapters. Having them all listed is trivial. Having Quarto exclude full_report.qmd from the sidebar listing seems tricky. The following glob pattern would include files directly in the first folder (Publications) but not in any subfolders of that? How could I set up an arbitrary folder depth where only certain _files_ are listed? P.S. I am aware that underscore filenames would be excluded, but then they would also not be rendered.

````yaml
# _quarto.yaml
  sidebar:
    - id: Publications
      title: "Publications"
      contents: "*(Publications/^[[:digit:]]_|Publications/index"
````
