### DISCUSSION TITLE
Bibliography is present twice in `docx`

### DISCUSSION THREAD

**Discussion by lorenzoFabbri** [quarto-dev/quarto-cli#7654] [Q&A] [answered]
### Description

I am using the following options in my Quarto document:

```
format:
  docx:
    reference-doc: reference_document.docx
    citeproc: true
```

and then I generate the bibliography with:

```
\newpage

# References {.unnumbered}

::: {#refs}
:::
```

But in the render document the bibliography is present twice. I thought that by using `citeproc` this would be avoided...

I am using R version 4.3.1 (2023-06-16) and Quarto version 1.4.487.
