### DISCUSSION TITLE
How to divide a chapter in two files for pdf output?

### DISCUSSION THREAD

**Discussion by Walser52** [quarto-dev/quarto-cli#7669] [Q&A] [answered]
### Description

I'm using quarto version 1.3.433 to generate a pdf output. I was wondering if there is a way to divide my chapter into two files. `ch1a.qmd` and `ch1b.qmd`. 

This is my _quarto.yaml file:
```
project:
  type: book

book:
  title: "Temp"
  author: "Norah Jones"
  date: "11/2/2023"
  chapters:
    - index.qmd
    - ch1a.qmd
    - ch1b.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
    keep-tex: true
```

I want `ch1a.qmd` to have some level 1 headings like so:

```

# Chapter Begins

## Section begins

Some text here.
```

But not in `ch1b.qmd`:

```
## Remaining Chapter 1

This qmd file has no level 1 heading. 
```

I posted this on SO but haven't had much help. The [solution](https://stackoverflow.com/a/77522696/17889492) which adds the file at the end using `cat` brings the text in but does not render the pdf headings.
