### DISCUSSION TITLE
Apply `auto-animate` to `background-image` in revealjs

### DISCUSSION THREAD

**Discussion by stephan-koenig** [quarto-dev/quarto-cli#7709] [Q&A] [answered]
### Description

Hi all!

I would like to animate a fullscreen background image to slide from the top end towards the bottom.
Is it possible to apply `auto-animate` to a `background-image`. The code below does not seem to work. I see either the top or the bottom of the images, but there is no transition between the slides.

```qmd
---
title: "Auto-animate does not seem to apply to background image"
format: revealjs
---

## {background-image="image.png" background-position="top" auto-animate=true}

## {background-image="image.png" background-position="bottom" auto-animate=true}

```

Thanks!

**Comment by mcanouil** [comment, marked as answer]
I don't think you can (animate is for content not for layout component such as background), but since it is HTML, you could try to make this work using CSS/JavaScript.

**Comment by jimjam-slam** [comment]
You could use a [parallax background](https://revealjs.com/backgrounds/#parallax-background) instead! Here's one I did using a very narrow picture of a gradient ([slides](https://jimjam-slam.github.io/quarto-experiments/vertical-slides), [code](https://github.com/jimjam-slam/quarto-experiments/tree/main/vertical-slides)):

https://github.com/quarto-dev/quarto-cli/assets/6520659/16c19a81-9cf3-49f1-b382-6081e27cf353

You just need a very wide or very narrow background 🙂  Here's the Quarto doc frontmatter (I used the `slide` transition to complete the illusion):

```yaml
format:
  revealjs:
    width: 1300
    controls: true
    transition: slide
    theme: [default, style.scss]
    parallax-background-image: narrow.png
    parallax-background-size: "28px 6000px"
```
