### DISCUSSION TITLE
Does the RSS feed include the categories?

### DISCUSSION THREAD

**Discussion by bryanhanson** [quarto-dev/quarto-cli#772] [Q&A]
It looks like it does not.  This is (really) important for instance in promoting one's blog on R-Bloggers, which screens the RSS feed for [R] tags.

**Comment by dragonstyle** [comment]
Our current default feeds should include category metadata within them (not 100% if this is what you're asking though). (For example, our own Quarto blog uses categories minimally, but they each appear in the RSS feed as well as on the blog page and individual post). Do you have an example of them not appearing in a feed? If so, happy to take a look as they most certainly should!

You may be asking about category specific feeds (e.g. a feed created only for posts tagged `[R]`. If you're asking about this, right now it looks like we don't allow you to create these (though actually we done all the work with the exception of validation and documentation). I'm going to address at least the validation right now (here 47cf88e279d45746235291928242c34523d6446a) - a fresh release is building now. If you'd like to generate category feeds, you can do so as:

```yaml
feed:
  categories:
    - categeory1
    - category2
```

Which should result in feeds being created alongside your default feed with names like `index_category1.xml`, etc...

Let us know if this works for you!

**Reply by bryanhanson** [reply]
Where does this go in `_quarto.yml`?  Like, what level, under `Project:`, `Website:`?

**Reply by dragonstyle** [reply]
Sorry- it goes right under your listing definition (perhaps right on the index page in the front matter, like):

```yaml
---
title: "blog"
listing:
  contents: posts
  categories: true
  feed: 
    categories: news
page-layout: full
title-block-banner: true
---
```
which will create a single additional feed `index_news.xml`.

or 

```yaml
---
title: "blog"
listing:
  contents: posts
  categories: true
  feed: 
    categories: 
      - news
      - posts
page-layout: full
title-block-banner: true
---
```

which will create `index_news.xml` and `index_posts.xml`
