### DISCUSSION TITLE
Adding a fav-icon to a blog website

### DISCUSSION THREAD

**Discussion by mcewenkhundi** [quarto-dev/quarto-cli#773] [Q&A] [answered]
I have followed instructions on adding fav-icon  but but the icon is still not appearing in the browser bar, would someone point me where I am getting it wrong?
Thanks in advance.

Below is my _quato.yml specification

```yaml
project:
  type: website
  output-dir: docs

website:
  title: "McEwen Khundi's Blog"
  repo-url: https://github.com/mcewenkhundi/mcewenkhundi
  fav-icon: dice-4.png
```

Here is the link to the website repo https://github.com/mcewenkhundi/mcewenkhundi

Session info:
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.1.0  fastmap_1.1.0   cli_3.2.0       htmltools_0.5.2 tools_4.1.0     yaml_2.2.1      rmarkdown_2.13  knitr_1.37      xfun_0.30      
[10] digest_0.6.27   rlang_1.0.2     evaluate_0.14
