### DISCUSSION TITLE
How to decrease footer height in quarto website?

### DISCUSSION THREAD

**Discussion by royfrancis** [quarto-dev/quarto-cli#7742] [Q&A]
### Description

What is the best way to decrease the footer height? The area marked below.

![Screenshot 2023-11-29 at 11 44 31](https://github.com/quarto-dev/quarto-cli/assets/5083500/e99aeb14-65f8-4b9f-8b6a-5a9118dbf3a2)

**index.qmd**

```
---
title: "Title"
format: html
---

Some content
```

**_quarto.yml**
```
project:
  type: website

website:
  navbar:
    left:
      - text: "Home"
        href: "index.html"
  page-footer:
    border: false
    left: "2023 | Org"
    right: "Published with Quarto"
```

```
▸ quarto --version
1.4.506
```
