### DISCUSSION TITLE
How to modify a native command like `text` or > text in quarto pdf?

### DISCUSSION THREAD

**Discussion by CDucloux** [quarto-dev/quarto-cli#7767] [Q&A] [answered]
### Description

# Header of my `.qmd` file

```yaml
title: "**Some document**"
author: "Mr Blue Sky"
format:
    pdf:
        toc: true
        number-sections: true
        include-in-header: 
        - "config.tex"
        colorlinks: true
        linkcolor: highlight
        urlcolor: highlight
```
I have a very basic need in my pdf document - when using the commands : 
> text

or 

`text`

I would like to style it like in github/stackoverflow. I currently have a `config.tex` file that I pass in the header of the document

```tex
\newcommand{\code}[1]{\colorbox{StackOgray}{\texttt{#1}}}
```

which allows me to create a similar \code{} command to style text...however, I would like to modify the native `` (which produces only a \texttt{text} and > commands. Is there a way to do it ?
