### DISCUSSION TITLE
Clickable section header

### DISCUSSION THREAD

**Discussion by JosiahParry** [quarto-dev/quarto-cli#7771] [Q&A]
### Description

I have a section of my sidebar defined like so in yaml.

```yaml
      - section: Location Services
        contents:
          - location-services/connecting-to-a-portal.qmd
          - location-services/read-data.qmd
          - location-services/publishing.qmd
          - location-services/workflows/add-delete-update.qmd
          - location-services/workflows/overwrite-feature-service.qmd
```
It renders like so: 
<img width="245" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/13534508/611e8d75-5908-4710-847b-44c395b9efb6">

I would really liked to be able to click the section heading and navigate to a very simple page that just lists out all of the links specified by the `contents` in the yaml. For example when I'm on a page 
<img width="429" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/13534508/ddbfaa2a-4c29-4258-b6cf-37fd533cef16">

Source repo: https://github.com/R-ArcGIS/r-bridge-site
