### DISCUSSION TITLE
output-dir in different volume

### DISCUSSION THREAD

**Discussion by yonicd** [quarto-dev/quarto-cli#7802] [Q&A]
### Description

i have read the docs regarding the opml and am getting stuck in win os

```
> quarto::quarto_version()
[1] ‘1.3.433’
```

my project is in volume c:\ and i want the output-dir to be in volume g:\

i cant traverse up the volume tree to get out of the original volume 

```yml
project:
  output-dir: "G:/My Drive"

format:
  pdf:
    include-in-header:
      - text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}

```

```
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'C:\projects\sows\G:\My Drive'

Error: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'C:\projects\sows\G:\My Drive'
    at Object.lstatSync (deno:runtime/js/30_fs.js:305:9)
    at existsSync (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:492:14)
    at projectOutputDir (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:58260:9)
    at renderProject (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:86697:27)
    at render (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:90675:20)
    at async renderForPreview (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:102415:26)
    at async render (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:102310:20)
    at async preview (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:102316:21)
    at async Command.fn (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:103767:9)
    at async Command.execute (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:8437:13)
```

```yml
project:
  output-dir: "../../../G:/My Drive"

format:
  pdf:
    include-in-header:
      - text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}

```

```
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'C:\G:\My Drive'

Error: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'C:\G:\My Drive'
    at Object.lstatSync (deno:runtime/js/30_fs.js:305:9)
    at existsSync (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:492:14)
    at projectOutputDir (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:58260:9)
    at renderProject (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:86697:27)
    at render (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:90675:20)
    at async renderForPreview (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:102415:26)
    at async render (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:102310:20)
    at async preview (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:102316:21)
    at async Command.fn (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:103767:9)
    at async Command.execute (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:8437:13)
```
