### DISCUSSION TITLE
Change background of breadcrumbs

### DISCUSSION THREAD

**Discussion by royfrancis** [quarto-dev/quarto-cli#7810] [Q&A]
### Description

This is really a minor problem when using custom `title-block-banner` and `$navbar-bg`, breadcrumbs stick out since they have a white background.

Here is an example;

![Screenshot 2023-12-06 at 09 37 03](https://github.com/quarto-dev/quarto-cli/assets/5083500/a5b3623d-0057-4d2a-8423-e3a20900e31a)

```
.
├── _quarto.yml
├── index.qmd
├── reports
│   └── report.qmd
└── styles.scss
```

**_quarto.yml**

```
project:
  type: website

format:
  html:
    theme: styles.scss
    title-block-banner: d7bde2

website:
  title: Website
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reports/report.qmd
        text: Report
  sidebar:
    contents:
      - section: Reports
        contents: "reports/*"
```

**styles.scss**

```
/*-- scss:defaults --*/

$navbar-bg: #d7bde2;

/*-- scss:rules --*/
```

**index.qmd**

```
---
title: Home page
---

Here is some text.
```

**report.qmd**

```
---
title: Report
---

Here is a report.
```

One option would be to disable the bread-crumbs  #6183. If I want to keep them, how do I change the background color of bread-crumbs? Changing the `background-color` of the class `quarto-page-breadcrumbs` doesn't fill the margins.

![Screenshot 2023-12-06 at 11 57 47](https://github.com/quarto-dev/quarto-cli/assets/5083500/d6c489c3-019e-413b-b6d3-91d261355e26)

`quarto 1.4.506`
