### DISCUSSION TITLE
Use `date` shortcode without triggering title blocks

### DISCUSSION THREAD

**Discussion by th0ger** [quarto-dev/quarto-cli#7827] [Q&A] [answered]
Hi! I would like to include the [meta date](https://quarto.org/docs/authoring/variables.html#meta) shortcode in all webpage footers:

```yaml
date: now
date-format: iso
website:
  page-footer: "Build: {{< env VERSION >}} @ {{< meta date >}} "
```

But the existence of `date: now` triggers the insertion of a [title block](https://quarto.org/docs/authoring/title-blocks.html).

Is it possible to insert `now` into a [var](https://quarto.org/docs/authoring/variables.html#var) or a custom `x-date` meta to work around this trigger?

A subset of my .qmd pages (blog posts) still need title blocks enabled. (Here `date`s are pinned values.)
