### DISCUSSION TITLE
Sidebar not available on mobile device or in narrow browser windows

### DISCUSSION THREAD

**Discussion by vincentarelbundock** [quarto-dev/quarto-cli#7846] [Q&A]
Thanks a lot for your work on Quarto!

The sidebar of my Quarto website hosts the table of contents. On mobile phones or in a browser with a narrow window, the sidebar disappears and is replaced by an icon. However, when I click on the icon, nothing happens.

How can mobile users or people with narrow browser windows access the sidebar with table of contents?

The live website is here: https://marginaleffects.com

The full `_quarto.yml` is:

```yml
project:
  type: website
website:
  title: Marginal Effects Zoo
  favicon: images/favicon.png
  page-navigation: true
  navbar:
    background: '#eeeeee'
    search: true
    logo: images/marginaleffects_icon.png
    logo-alt: marginaleffects logo
    left:
      - text: Get started
        href: vignettes/get_started.qmd
    right:
      - icon: github
        href: https://github.com/vincentarelbundock/marginaleffects
        aria-label: marginaleffects GitHub
      - icon: twitter
        href: https://twitter.com/vincentab
  sidebar:
    collapse-level: 1
    contents:
      - vignettes/get_started.qmd
      - section: Tutorials
        contents:
          - vignettes/predictions.qmd
          - vignettes/comparisons.qmd
          - vignettes/slopes.qmd
          - vignettes/hypothesis.qmd
          - vignettes/plot.qmd
      - section: Case studies
        contents:
          - vignettes/brms.qmd
          - vignettes/bootstrap.qmd
          - vignettes/categorical.qmd
          - vignettes/conformal.qmd
          - vignettes/elasticity.qmd
          - vignettes/equivalence.qmd
          - vignettes/experiments.qmd
          - vignettes/gam.qmd
          - vignettes/gcomputation.qmd
          - vignettes/heterogeneity.qmd
          - vignettes/ipw.qmd
          - vignettes/logit.qmd
          - vignettes/lme4.qmd
          - vignettes/machine_learning.qmd
          - vignettes/marginalmeans.qmd
          - vignettes/matching.qmd
          - vignettes/mrp.qmd
          - vignettes/multiple_imputation.qmd
          - vignettes/svalues.qmd
      - section: Technical notes
        contents:
          - vignettes/faq.qmd
          - vignettes/meme.qmd
          - vignettes/alternative_software.qmd
          - vignettes/extensions.qmd
          - vignettes/links.qmd
          - vignettes/performance.qmd
          - vignettes/python.qmd
          - vignettes/supported_models.qmd
          - vignettes/tables.qmd
          - vignettes/uncertainty.qmd
      - section: Functions
        contents:
          - man/predictions.qmd
          - man/comparisons.qmd
          - man/slopes.qmd
          - man/plot_predictions.qmd
          - man/plot_comparisons.qmd
          - man/plot_slopes.qmd
          - man/hypotheses.qmd
          - man/inferences.qmd
          - man/marginal_means.qmd
          - man/posterior_draws.qmd
          - man/datagrid.qmd
          - man/print.marginaleffects.qmd
      - NEWS.md
      - LICENSE.md
      - CITATION.md
format:
  html:
    toc: true
    theme:
      light: flatly
    code-copy: true
    code-overflow: scroll
```

And here is a screenshot from my mobile device (I tried both Android and iPhone), with the non-working icon circled in red.

![Screenshot_20231208-101927](https://github.com/quarto-dev/quarto-cli/assets/987057/9d6dd86f-192b-42ae-a804-50cef26dba5b)
