### DISCUSSION TITLE
How to include multiple links in format:html:link-external-filter?

### DISCUSSION THREAD

**Discussion by Qepanna** [quarto-dev/quarto-cli#7860] [Q&A] [answered]
### Description

Hi, I'm very new to Quarto and I need help to understand some coding basics.

In my -quarto.yml file, I would like to use the options for external links as follows:

```
project:
  type: website

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
```

This works.

But I would also like to add more links to the link-external-filter option. I tried something like this:

```
project:
  type: website

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter:
      - '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
      - '^(?:http:|https:)\/\/www\.doi\.org\/custom'
```    

But I get the following error message:

```
Project _quarto.yml validation failed.

In file C:\goFlux-workshop\_quarto.yml
(line 12, column 7 through line 13, column 53) Field "link-external-filter" has value

- '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
  - '^(?:http:|https:)\/\/www\.doi\.org\/custom'

The value must instead be a string.
11:     link-external-filter:
12:       - '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
13:       - '^(?:http:|https:)\/\/www\.doi\.org\/custom'
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x The value

- '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
  - '^(?:http:|https:)\/\/www\.doi\.org\/custom'

is of type an array.
i The error happened in location format:html:link-external-filter.
```

I don't understand what it is suggesting me to do.

Thank you for your help!

Best,
Karelle
