### DISCUSSION TITLE
Quarto Custom Format Issue

### DISCUSSION THREAD

**Discussion by jlgraves-ubc** [quarto-dev/quarto-cli#7961] [Q&A] [answered]
### Description

Hi all,

I'm trying to create a custom format, called exam, which automates a bunch of the annoying stuff I have to do when creating exams using Quarto.  However, I can't see to get it to work.

For a minimal example, I have then `exam` latex package installed, and have a document which looks like this:

```
---
title: Sand Counties
date: 2023-07-03
version: 0.1
filters:
  - latex-environment
format:
    pdf: 
      documentclass: exam
      classoption:
      - addpoints
      - 12pt
commands: [question, part]
environments: [parts, questions]
toc: false

---
::: {.questions}

\question[5] Which words did you not recognize?  Write down a list and give a short definition of each.

:::
```

This works fine.  It compiles to PDF appropriate and everything works.

But when I try to turn it into a format, as follows:

```
---
title: Example Exam or Assignment
format:
  exam-pdf: default
author: Jonathan Graves
date: last-modified
---

:::{.questions}

\question[5]  What is the capital of Spain?

:::

```

with the extension YML file:

```
title: exam
author: Jonathan Graves
version: 1.0.0
quarto-required: ">=1.4.0"
contributes:
  formats:
    pdf:
      toc: false
      documentclass: exam
      classoption:
      - addpoints
      - 12pt
      include-in-header: header.tex
      filters:
      - latex-environment
      commands: [question, part]
      environments: [parts, questions, solution]
```

It does not create a document of class `exam` - instead defaulting back to the standard format (`scarticle`).  I cannot figure out what I'm doing wrong here, since this seems very straightforward.

I check the embedded install of the `latex-environment` filter and it seems fine, so I'm at a loss.

**Comment by cderv** [comment]
Do you have the extension available online in a github repo so we can install get access to it ? 
See https://quarto.org/docs/extensions/distributing.html

Also I see you are trying to use another extension `latex-environment`. Did you embed it correctly ? https://quarto.org/docs/extensions/formats.html#extension-embedding

About the configuration, I don't know exactly from the extension file how they should be set... I wonder if we allow only setting in the main doc 🤔 Talking about this part

````
      commands: [question, part]
      environments: [parts, questions, solution]
````

Being able to have access to your extension will help us help you

**Reply by jlgraves-ubc** [reply]
Here's the file:

[latex-exam.zip](https://github.com/quarto-dev/quarto-cli/files/13720880/latex-exam.zip)

**Reply by cderv** [reply, marked as answer]
I can't reproduce. I see this when I run `quarto render` from the folder you shared

 ```
> quarto render .\template.qmd
pandoc 
  to: latex
  output-file: template.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  toc: false

metadata
  block-headings: true
  documentclass: exam
  classoption:
    - addpoints
    - 12pt
  commands:
    - question
    - part
  environments:
    - parts
    - questions
    - solution
  title: Example Exam or Assignment
  author: Jonathan Graves
  date: last-modified
````

We see `documentclass: exam` and it will install exam in latex
```
finding package for exam.cls
> 1 package to install
> installing exam (1 of 1)
```

I get other error after though 
````
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.171 \end{parts}
                  
````

**Reply by jlgraves-ubc** [reply]
What if you do `quarto render template.qmd`?

This is what I was doing and it failed.  This is relevant since not all uses of this format would include a project renderable with `quarto render`

**Reply by cderv** [reply]
I redownloaded, unzipped, and ran. It works for exam class

Full log
````
> quarto render template.qmd
pandoc 
  to: latex
  output-file: template.tex
  standalone: true
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  toc: false
  
metadata
  block-headings: true
  documentclass: exam
  classoption:
    - addpoints
    - 12pt
  commands:
    - question
    - part
  environments:
    - parts
    - questions
    - solution
  title: Example Exam or Assignment
  author: Jonathan Graves
  date: last-modified


Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.171 \end{parts}


see template.log for more information.
ERROR: Error
    at renderFiles (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-files.ts:346:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async render (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-shared.ts:99:18)
    at async Command.fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:155:3)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:186:5
````

**Reply by jlgraves-ubc** [reply]
You are right - it does seem to be working.  The error is strange though: quarto parses the /part command in the environment not as a latex command but as text.  If I use: []{.part options="5"} instead it works.

Thanks though.

**Reply by cderv** [reply]
This is a pandoc thing - it seems `\part` is not seen raw LaTex by Pandoc 

````
> quarto pandoc --to latex
\question Answer the following parts.                                     

\part[5]  What is the capital of Canada?

\part another test
^Z
\question Answer the following parts.

\textbackslash part{[}5{]} What is the capital of Canada?

\textbackslash part another test
````

It means you need to mark it as raw LaTeX using 
````markdown
`\part[5]`{=latex} 
````

Or indeed use the `latex-environment` extensions that support a Span markdown syntax for it. As you defined in YAML
````yaml
commands: [question, part]
````

it will work with span syntax

**Reply by momenezes** [reply]
Hi,
I'm trying this and still got the same error related to `\part` not being properly parsed by Pandoc.  I've downloaded the .zip file and just typed:
```
$ quarto render template.qmd
```

The .tex file ended up with `\textbackslash part{[}5{]}` instead of `\part[5]`

I'm using Kubuntu 22.04 LTS, with the following version of Pandoc and Quarto:

```
$ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.2, skylighting 0.8.5
$ quarto --version
1.4.554
```
Any suggestions?

**Reply by mcanouil** [reply]
Did you try the suggestion made before your reply?

**Reply by momenezes** [reply]
You mean, adding `part` to the `commands` in the latex-environment? From what I checked , if I understood correctly, it was there already:
```
title: exam
author: Jonathan Graves
version: 1.0.0
quarto-required: ">=1.4.0"
contributes:
  formats:
    pdf:
      toc: false
      documentclass: exam
      classoption:
      - addpoints
      - 12pt
      include-in-header: header.tex
      filters:
      - latex-environment
      commands: [question, part]
      environments: [parts, questions, solution]
```
This is the `_extension.yml` file in the .zip. 

Anything else I should do? Sorry if I missed something.
