### DISCUSSION TITLE
RSS feed for listing page with multiple listings and YAML listing content

### DISCUSSION THREAD

**Discussion by blenback** [quarto-dev/quarto-cli#8063] [Q&A] [answered]
### Description

Hello, I am trying to add an RSS feed to a listing page on a quarto website. The website already has two other listing pages with functioning feeds (for presentations and a blog) however this last listing page is slightly different as it contains multiple listings and the listing contents are created as inputs in the YAML. A repro would be like this: 

````
---
title: "Publications"
page-layout: full
title-block-banner: false
format: 
  html: 
    css: css/publications.css
listing:
  - id: Journal-articles
    template: publication.ejs
    contents:
    - name: Archetypes
      title: test
      Authors: Wicki, S., <b>Black, B</b>., Kurmann, M., Grêt-Regamey, A.
      Title: Archetypes of social-ecological-technological systems for managing ecological infrastructure.
      Journal: Environ. Res. Lett.
      href: https://doi.org/10.1088/1748-9326/ad1080
      Bibtex: media/Archetypes.bib
  - id: Theses
    template: publication.ejs
    contents:
    - name: MSc
      Authors: <b>Black, B</b>.
      Title: "Assessing the ecological effectiveness of protected areas in Cambodia: a quasi-experimental counterfactual estimation of avoided deforestation."
      Journal: Masters thesis. Central European University.
      href: https://doi.org/10.13140/RG.2.2.28621.10727
      Bibtex: media/MSc_thesis.bib
    feed: true
---
````

An rss file is created (docs/publications.xml) when the page is rendered but it does not contain the listing contents: 
````
<?xml version="1.0" encoding="UTF-8"?>
<rss  xmlns:atom="http://www.w3.org/2005/Atom" 
      xmlns:media="http://search.yahoo.com/mrss/" 
      xmlns:content="http://purl.org/rss/1.0/modules/content/" 
      xmlns:dc="http://purl.org/dc/elements/1.1/" 
      version="2.0">
<channel>
<title>Ben&lt;br&gt;Black</title>
<link>https://blenback.github.io/publications.html</link>
<atom:link href="https://blenback.github.io/publications.xml" rel="self" type="application/rss+xml"/>
<description>Personal website for Ben Black</description>
<generator>quarto-1.3.450</generator>
<lastBuildDate>Fri, 29 Dec 2023 09:22:08 GMT</lastBuildDate>
</channel>
</rss>
````

I also tried to put ```feed:true``` as an indented option under one of the listing ```- id:```'s

Quarto version: 1.3.450
OS: Version: Windows 10.0.19045 Build 19045
Rstudio: 2023.09.1 Build 494
