### DISCUSSION TITLE
Quarto publish to GH-pages: How to publish only one format while having multiple defined in "_quarto.yml"?

### DISCUSSION THREAD

**Discussion by Gewerd-Strauss** [quarto-dev/quarto-cli#8074] [Q&A] [answered]
### Description

Hello there,

I am currently setting up a quarto project. Regarding outputs, I will primarily render to html. However, I will need to semi-regularly render (certain files) to docx as well. I also require online-hosting, which I satisfy via `quarto publish gh-pages` (cf [docs](https://quarto.org/docs/publishing/github-pages.html#publish-command))

I have issues understanding if/how I can selectively control output formats when calling `quarto publish`. 
On the one hand, depending on how much this balloons in scope rendering multiple formats will become very time-consuming rather quickly; particularly because binary files and `git` are not the best match. I have a long-running git repo that is merely used for backup purposes that contains quite a number of binary files; and it has ballooned the repo. It's fine, but I'd just rather prevent it if possible.

Now. The _simple_ solution is to remove the format-definition:

```yml
format:
  docx:
    author: GS
    toc: false
    toc-depth: 3
    number-sections: true
    number-depth: 2
    df-print: kable
    fig-dpi: 96
    fig-height: 6
    fig-depth: 8
    reference-doc: refdoc.docx
```

from `_quarto.yml` before publishing. 

However, this is much more annoying and time-consuming than doing something like

```cmd
quarto publish gh-pages --format html
/// OR
quarto publish gh-pages --to html
```
 
to render specific formats defined in `_quarto.yml`, and

```cmd
quarto publish gh-pages
```

to render all formats defined in `_quarto.yml`. 

I couldn't find anything in the docs regarding this. Is this just not possible/not implemented, or am I just very _blind_ right now?
I should mention that my experiences with quarto publishing are somewhat limited, I am just testing things out for a couple days now. I don't _think_ I missed something, but that's also entirely possible.

---

Thank you.  
Sincerely, 
~Gw
