### DISCUSSION TITLE
Featured image not showing in listing

### DISCUSSION THREAD

**Discussion by royfrancis** [quarto-dev/quarto-cli#8094] [Q&A] [answered]
### Description

Featured image doesn't show up on the listings page when `image:` is specified through `_quarto.yml`.

![Screenshot 2024-01-03 at 00 14 39](https://github.com/quarto-dev/quarto-cli/assets/5083500/7e83b1ee-5ce3-4e39-bf4c-e41f151f21d5)

I have recreated a minimal version of my setup:

```
.
├── assets              (shared resources)
│   └── image.jpg       (featured image)
├── index.qmd           (home page)
├── _quarto.yml
└── reports
    ├── a
    │   └── index.qmd   (a report)
    └── index.qmd       (listing page for reports)
```

**_quarto.yml**

```
project:
  type: website
  output-dir: docs

format:
  html:
    image: "../../assets/image.jpg"
```

**index.qmd**

```
---
title: Featured image test
format: html
---

- [Reports listing](reports/index.html)
```

**reports/index.html**

```
---
title: Reports
listing:
  type: grid
  fields: [image, title]
format: html
---
```

**reports/a/index.html**

```
---
title: Report A
format: html
---

This is report A.
```

`quarto 1.3.433`

**Comment by mcanouil** [comment]
image is a website option not an html format option.
Trying putting it under website.

Also use absolute path when you want to set things like the image here.
`image: /assets/image.jpg`.

Why setting the format in every file when you already set it at the project level?

Finally, you are not using the latest stable release. Please upgrade at least to latest 1.3 and report back.

**Reply by royfrancis** [reply]
Tried again with `quarto 1.4.533` and only using absolute path.

## Doesn't work
### In _quarto.yml

```
website: 
  image: /assets/image.jpg
```

- assets folder not copied over

### In reports/index.qmd

`image: /assets/image.jpg`

- assets folder not copied over

### In _quarto.yml

```
project:
  resources: /assets

website: 
  image: /assets/image.jpg
```

- assets folder is copied over

## Works
So far, the working options are directly in the final qmd.

### In reports/a/index.qmd

`image: /assets/image.jpg`

### In reports/a/index.qmd

`![](/assets/image.jpg)`

**Reply by mcanouil** [reply]
Could you share a Git repository with your example project? Thank you.
it would be better than asking to copy/paste everything in the "correct" location.

**Comment by royfrancis** [comment, marked as answer]
The solution is to use `image-placeholder` on the listing page.

```
---
listing:
  type: grid
  fields: [image, title]
  image-placeholder: /assets/image.jpg
format: html
---

```

This is documented [here](https://quarto.org/docs/websites/website-listings.html#listing-options). This solves the issue for me.

But since this discussion involved setting the default listing image from _quarto.yml, I am not really sure if this can be specified from _quarto.yml without turning every page into a listing page.
