### DISCUSSION TITLE
refer to author information from metadata

### DISCUSSION THREAD

**Discussion by anielsen001** [quarto-dev/quarto-cli#8097] [Feature Requests]
### Description

I'm trying to find an easy way to refer to author by id from the meta data for forming the author section of a document. For a project, I'd like to define the author metadata in a yaml and just list the authors for a particular document by their id's. 

Something like this is a quarto yaml file:
````yml
author: 
  - id: jd
    name: John Doe
    email: jd@example.com
  - id: fb
    name: foo bar
    email: fb@example.com
````

and then referred like this in a document:
````yml
author:
    - ref: 
      - jd
      - fb
````

The documentation does not say this is possible and it doesn't work, is there any sort of work around that people have used in this situation?
