### DISCUSSION TITLE
Giving different sidebar contents in subdirectories

### DISCUSSION THREAD

**Discussion by ChrisJefferson** [quarto-dev/quarto-cli#8117] [Q&A]
### Description

I have been trying to set `sidebar: contents:` to different values. I was trying to follow the guide in: https://quarto.org/docs/websites/website-navigation.html but couldn't understand how to have different sidebars on different pages.

What I would like is, for every file inside the sub-directory `book`, to have a specific sidebar (which shows the full outline of the book), but a different `sidebar: contents` for other files. I tried setting `sidebar: contents:` inside `_metadata.yml` in the `book` directory, but that did not seem to change the contents of the sidebar?

**Comment by mcanouil** [comment]
Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.
Also while trying to make a small and simple reproducible example, make sure to try 1.4 pre-release.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by ChrisJefferson** [comment]
I generated a default blog, then edited the `_quarto.yml` as below. Note that `cheese` and `badger` are just random strings. I've decided my issue is that I don't know how quarto decides which of the sidebars to use on each page (I thought I did, but I don't, the only doc or example I can find is on https://quarto.org/docs/websites/website-navigation.html , but does lots of things at the same time). I'd like to be able to understand and control which sidebar is used on which page.

It looks like from this sample it uses whichever sidebar the page is in the contents of? (as in this case the 'cheese' is used for 'about.qmd', and 'badger' is used by 'index.qmd'?

```
project:
  type: website

website:
  title: "Testblog"
  sidebar:
    - title: "cheese"
      style: "docked"
      background: light
      contents:
        - text: "------"
        - text: "------"
        - about.qmd

    - title: "badger"
      contents:
        - text: "------"
        - text: "------"
        - text: "------"
        - index.qmd
        # navigation items


  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
```
