### DISCUSSION TITLE
How to add text in other languages when hovering over icons in side navbar?

### DISCUSSION THREAD

**Discussion by luifrancgom** [quarto-dev/quarto-cli#8125] [Feature Requests]
### Description

I am developing a book in a language other than English. I need to know if it's possible to modify the tooltip text that appears when hovering over the icons in the side navbar, specifically for the 'Share' and 'Source Code' options.

While the tooltip text for the 'Reader Mode' and 'Light/Dark Theme' icons correctly adapts to different languages, this isn't the case for the aforementioned icons.

![video_question](https://github.com/quarto-dev/quarto-cli/assets/50002526/8a0f4867-e4ad-45f3-8c99-cdd80021e39c)

I have many elements in the yalm but this are the relevant elements:

```yaml
project:
  type: book

lang: pt-BR

book:
  sharing: [twitter, linkedin, facebook]
  site-url: https://luifrancgom.github.io/estatistica-descritiva-R-1ed/
  repo-url: https://github.com/luifrancgom/estatistica-descritiva-R-1ed
  repo-branch: main
  issue-url: https://github.com/luifrancgom/estatistica-descritiva-R-1ed/issues
  reader-mode: true

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
```
Where according to [Quarto Localization](https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language) `pt-BR` is supported with the following [translation](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language-pt-BR.yml).

Is there a way to modify the tooltip text for the 'Share' and 'Source Code' options or it is a feature I need to request so the developers can add this option in [Quarto Localization](https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language)?
