### DISCUSSION TITLE
pdf: page number doesn't corresponde to the page number in the table of content

### DISCUSSION THREAD

**Discussion by MichelDSchmid** [quarto-dev/quarto-cli#8133] [Q&A] [answered]
### Description

Dear all

I'm using quarto-1.3.450 on windows 10 to produce html and pdf output. Now I have seen that in the pdf output
the page number doesn't corresponde with the page numbers in the TOC. 
My yaml section for the pdf output looks like:
```yaml
pdf:
    quarto-required: ">=1.3.306"
    filters: [lua_filters/remove_title.lua, lua_filters/convertSVG.lua]  # remove_title.lua removes the default title page
    language: gsw # swiss german
    latex-auto-mk: true
    toc-title: Inhaltsverzeichnis
    default-image-extension: svg
    documentclass: scrreprt
    classoption: [table]
    keep-tex: true
    papersize: A4
    hyperrefoptions:
      - linktoc
      - "anchorcolor=green"
    linkcolor: blue
    urlcolor: cyan
    filecolor: magenta
    citecolor: red
    link-citations: true
    # cite-method: biblatex
    include-in-header:         
      - file: latex/custom_header.tex
      - text: |
          \def\authors{ {{< meta book.author >}} }
          %\renewcommand{\solution}[1]{#1}  
    include-before-body:
      - latex/pre_defColorChapFrame.tex
      - latex/title.tex
```

Even if I keep the *.tex output file and run another tex-editor to compile it to pdf I have the same beahviour. The page numbers are shiftet by two, means the page number 3 in the TOC jumps to the title page etc.

Any suggestions what I'm doing wrong?

Thanks in advance 
Mike
