### DISCUSSION TITLE
if, on a custom listing, I use the `field-types` key in the front matter, can I still have it respect the `date-format`?

### DISCUSSION THREAD

**Discussion by danmackinlay** [quarto-dev/quarto-cli#8134] [Q&A] [answered]
### Description

I am trying to create a custom listing which adds some custom numerical rating  (`usefulness`) to some blog posts  and displays the listing using that custom metadata. I would like to  sorting by either date or by rating using the sort ui.

The frontmatter on my listing page looks like this:

```yaml
title: Notebooks
listing:
  page-size: 50
  sort: "date-modified desc"
  type: default
  categories: true
  sort-ui:
    - title
    - date
    - date-modified
    - usefulness
  filter-ui:
    - title
    - subtitle
  template: theme/living_listing.ejs
  contents:
    - notebook
  feed: true
  # field-types:
  #   date: date
  #   date-modified: date
  #   usefulness: number
  field-display-names:
    title: "Title"
    date: "Created"
    date-modified: "Modified"
    usefulness: "Usefulness"
  date-format: YYYY-MM-DD
```

This nearly works, in that it displays some blog posts; A formatted example is show here:

<img width="827" alt="Screenshot 2024-01-05 at 21 08 38" src="https://github.com/quarto-dev/quarto-cli/assets/21740/7bf6e530-f05b-4926-888f-af9ffe5b3239">

The problem is that I cannot really sort by `usefulness` here, since I have not declared that it is a numerical rating, I need to declare the metadata to be numerical, so I uncomment the `field-types` section:

```yaml
title: Notebooks
listing:
  page-size: 50
  sort: "date-modified desc"
  type: default
  categories: true
  sort-ui:
    - title
    - date
    - date-modified
    - usefulness
  filter-ui:
    - title
    - subtitle
  template: theme/living_listing.ejs
  contents:
    - notebook
  feed: true
  field-types:
  #   date: date
  #   date-modified: date
    usefulness: number
  field-display-names:
    title: "Title"
    date: "Created"
    date-modified: "Modified"
    usefulness: "Usefulness"
  date-format: YYYY-MM-DD
```

Now I *can* sort by usefulness, but the date formatting has gone haywire:

<img width="917" alt="Screenshot 2024-01-05 at 21 10 01" src="https://github.com/quarto-dev/quarto-cli/assets/21740/ec0b86bf-a308-44ee-89a8-a28466fbb09f">

I.e. using the `field-types` key at all causes date display to ignore the specified simple clean date format `YYYY-MM-DD`, e.g.  `2020-01-22` to some kind of  maximalist alternate `Wed Jan 22 2020 11:28:53 GMT+0800 (GMT+08:00)`. (The timezone so nice we mention it twice)
I can further uncomment the `date`, `date-modified` entries in the front matter, but that does not restore the date formatting.

```yaml
title: Notebooks
listing:
  page-size: 50
  sort: "date-modified desc"
  type: default
  categories: true
  sort-ui:
    - title
    - date
    - date-modified
    - usefulness
  filter-ui:
    - title
    - subtitle
  template: theme/living_listing.ejs
  contents:
    - notebook
  feed: true
  field-types:
    date: date
    date-modified: date
    usefulness: number
  field-display-names:
    title: "Title"
    date: "Created"
    date-modified: "Modified"
    usefulness: "Usefulness"
  date-format: YYYY-MM-DD
```

I can present the template as well if this will help clarify the problem. This already feels like a long post though, so I will for now just include the part that displays the date:

```ejs
        <div class="metadata"><a href="<%- item.path %>" class="no-external">
            <span class="archive-item-date">
                <span class="listing-date">
                    <%= item.date %>
                </span>
                <% if (item['date-modified']) { %>
                    — <span class="listing-date-modified">
                        <%= item['date-modified'] %>
                    </span>
                <% } %>
            </span>
        </a></div>
```

What is going on here? Have I missed some basic understanding of how to apply `date-format`? Or is this a bug?
