### DISCUSSION TITLE
Better way than manually converting PDF to SVG images while using typst

### DISCUSSION THREAD

**Discussion by psads-git** [quarto-dev/quarto-cli#8180] [Feature Requests]
### Description

Consider the code:

```
---
title: Page Layout
format:
  typst:
    papersize: a4
    margin:
      x: 1cm
      y: 1cm
    # columns: 2
---

# Introduction

![My image](excel01.pdf){width=80%}
```

When compiling, I get the error:

```
[typst]: Compiling Untitled-1.typ to Untitled-1.pdf...error: unknown image format
    ┌─ Untitled-1.typ:251:16
    │
251 │ #box(width: 80%,image("excel01.pdf"))
    │                 ^^^^^^^^^^^^^^^^^^^^
```    

I am aware that `typst` does not accept PDF images.

My question is: Is there another way to insert `PDF` images with `quarto` than manually convert them to, say, `SVG`? Thanks!
