### DISCUSSION TITLE
I would like to create an index for a book I'm writing but the code below fails with the following error: compilation failed- error Undefined control sequence. l.4714 \printindex

### DISCUSSION THREAD

**Discussion by jonwake** [quarto-dev/quarto-cli#8251] [Q&A]
### Description

project:
  type: book

book:
  title: "Spatial Modeling of Health and Demographic Variables"
  author: "Jon Wakefield"
  date: today
 
  chapters:
    - index.qmd
    - intro.qmd
    - disease-mapping-count.qmd
    - disease-mapping-point.qmd
    - sae-survey-sampling.qmd
    - sae-area-level.qmd
    - sae-unit-level.qmd
    - spatialregression.qmd
    - spacetime.qmd
  appendices: 
    - bayes.qmd
    - inla.qmd
    - pc-priors.qmd
    - references.qmd
    
bibliography: spatepi.bib
csl: biometrics.csl

crossref: 
  chapters: true

format:
  pdf:
    - definitions.tex
    documentclass: scrreprt
    number-sections: true
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeidx
    include-after-body: 
      text: |
       \printindex

  html:
    theme: cosmo
    number-sections: true
    include-in-header: 
      - definitions_html.tex

    execute:
      cache: true

editor: visual

**Comment by cscheid** [comment]
You're adding `\printindex`, so I'm not sure what you're expecting to get when the error is that `\printindex` is undefined.

**Reply by jonwake** [reply]
I'm going from this:
https://quarto.org/docs/books/book-structure.html
which gives:
    include-after-body: 
      text: |
        \printindex

**Reply by mcanouil** [reply]
@jonwake please could you use code blocks markdown syntax to insert code. Currently, your posts are very hard to read. Than you.

**Reply by jonwake** [reply]
Is there a button that I can this with? And should I start a new discussion? Thanks

**Reply by mcanouil** [reply]
Use the edit button on GitHub.
Then either use the tool menu just above the comment area or use markdown as you would in a Quarto document.

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by jonwake** [comment]
Restating the question, to hopefully make easier to read  (thanks for the suggestion):

```
  pdf:
    documentclass: scrreprt
    number-sections: true
    include-in-header: 
      - definitions.tex
    text: |
       \usepackage{makeidx}
       \makeidx
    include-after-body:
      text: |
       \printindex
```

When I render this, I get the error

compilation failed- error
Undefined control sequence.
l.4711 \printindex

**Reply by mcanouil** [reply]
Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Reply by cderv** [reply]
````yaml
include-in-header: 
    - definitions.tex
  text: |
     \usepackage{makeidx}
     \makeidx
````

This is not indented properly. `makeidx` is not added in the .tex template I think. 

You can confirm with adding `keep-tex: true` and looking at the intermediate tex file, and by checking the log printed when you `quarto render`: My guess is that `test` will be seen as a variable under `metadata` 

The example you followed at https://quarto.org/docs/books/book-structure.html#creating-an-index is just showing how to include one element (`text` here), but as you add also `definitions.tex` as a file, you need to adapt. 

Look at the documentation for correct indentation and syntax: https://quarto.org/docs/output-formats/html-basics.html#includes

Hope it helps

## Other note: 

````yaml
    text: |
       \usepackage{makeidx}
       \makeidx
````

`\makeidx` is not the right command I think - as in our example on website it should be 
````yaml
      text: |
        \usepackage{makeidx}
        \makeindex
````

**Reply by jonwake** [reply]
Thanks for explaining this so carefully! Based on your explanation and the website you suggested, I was able to solve the problem! The index section appears after the references, which is not the usual way, and it is not in the table of contents, but they are minor issues

**Reply by cderv** [reply]
> It is not in the table of contents

This is not by default. You need to find solutions online like https://tex.stackexchange.com/questions/57427/how-to-add-printindex-to-tableofcontents

> The index section appears after the references

did you try placing `\printindex` inside the document ? 
https://fr.overleaf.com/learn/latex/Indices

By placing it in after body, I believe you are asking for it to be last

**Reply by jonwake** [reply]
Thanks for the message. The link you suggested helped - now the code below gives an index in the table of contents - it's after  references (though this is not so critical). When I click on "Index" in toc it goes to "References" but that also not terrible.
Thanks again
```    
format:
  pdf:
    documentclass: scrreprt
    number-sections: true
    include-in-header: 
      - definitions.tex
    include-after-body: 
      text: |
        \addcontentsline{toc}{chapter}{\indexname}
        \printindex
```
