### DISCUSSION TITLE
How to provide different logos for light and dark modes on a Quarto website?

### DISCUSSION THREAD

**Discussion by maelle** [quarto-dev/quarto-cli#8379] [Q&A]
### Description

I'm working on a website with both light and [dark mode](https://quarto.org/docs/output-formats/html-themes.html#dark-mode). I'd like to use a different logo for the dark mode. At the moment this is how I add the log

```yml
website:
  navbar:
    logo: <path-to-logo>
```

how to add a specific logo for dark mode? Thank you.
