### DISCUSSION TITLE
merging of metadata-files with _quarto.yml

### DISCUSSION THREAD

**Discussion by anielsen001** [quarto-dev/quarto-cli#8396] [Q&A] [answered]
### Description

I'm trying to merge some sidebar information from a metadata-files with an existing _quarto.yml file. 

my _quarto.yml looks like this:
```yaml
project:
  type: website

metadata-files:
  - _sidebar.yml

website:
  title: "Test-sidebar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

```

and the _sidebar.yml file looks like this:
```yaml
website:
  sidebar:
    - contents:
        - index.qmd
        - about.qmd
```

when I do this, I get a docked style sidebar, but it's empty. If I comment out the sidebar information in the _quarto.yml, I get the sidebar information from the _sidebar.yml file. The [docs](https://quarto.org/docs/projects/quarto-projects.html#metadata-includes) indicate that these should merge, but maybe I'm misunderstanding. What's the expected behavior here? 

Heres my quarto check out put
```bash$ quarto check
Quarto 1.4.533
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.533
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2019

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.3
      Path: /home/apn/sw/bin/python3
      Jupyter: 4.10.0
      Kernels: julia-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib/R
      LibPaths:
        - /home/apn/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK

```

**Comment by cderv** [comment]
@dragonstyle could there be something regarding merging nested levels of website? 

From our doc: https://quarto.org/docs/projects/quarto-projects.html#metadata-includes, I wonder if we do really expect merging nested content, of if we replace the whole `sidebar` key instead of merging its content. 

Do you know what is the expected behavior ? Can't say if this is an issue, a documentation problem or something we don't support yet and need to improve. 

Thanks !

**Reply by dragonstyle** [reply, marked as answer]
I think we're not expecting the `sidebar` definition in the `_sidebar.yml` file to be an array- it should be an object, like so:

```yaml
website:
  sidebar:
    contents:
      - index.qmd
      - about.qmd
```

When I do this, everything appears to be merging properly.

It's likely that the use of the `metadata-files` is somehow getting past validation, but if you think about it, merging into this:

```yaml
  sidebar:
    style: docked
    - contents:
            - index.qmd
            - about.qmd    
```

wouldn't really make sense, so I'm guessing that we're discarding the contents when attempting to merge the unexpected array with an object.
