### DISCUSSION TITLE
Change website root path

### DISCUSSION THREAD

**Discussion by lz100** [quarto-dev/quarto-cli#8513] [Q&A] [answered]
### Description

Hello Quarto folks,

I have a repo to store website content, it's like:

.
├── index.qmd
├── _qaurto.yml
├── .git
├── assets
│   ├── ...
├── section 1
│   └── ... qmd
├── section2
│   ├──... qmd
├── _extensions
│   └── ...
└── about.qmd
├──  many other things

All the qmds are stored in the root or one directory under root. This makes the root messy. I want to place all qmds into one directory and use that as my root for the website. How do I change the config?

.
├── index.qmd
├── assets
│   ├── ...
├── content
│           ├── index.qmd
│           ├── section 1
│                ├── ....qmd
│           └── about.qmd
├──  many other things

my config look like this:

```yml
project:
  type: website
  
website:
  reader-mode: false
  site-path: "/content"
  navbar:
    left:
      - text: "DSM Workflows Wiki"
        file: content/index.qmd
```
1. I still have to use `content` prefix for all qmds, otherwise not found. 
2. when I preview the website, no matter I set `site-path` to "/" or "/content", it's always giving me "localhost:1234/content/xxx"

All I want is to put all qmds to `/content` but when it website builds, the root is `localhost:1234/`.
