### DISCUSSION TITLE
Custom lua script seems to break in quarto 1.4

### DISCUSSION THREAD

**Discussion by royfrancis** [quarto-dev/quarto-cli#8571] [Q&A] [answered]
### Description

With 1.3, it looks like this:

![Screenshot 2024-02-02 at 20 42 09](https://github.com/quarto-dev/quarto-cli/assets/5083500/0c0c191f-fed7-426e-a04b-0dfad2fb8542)

With 1.4, it looks like this:

![Screenshot 2024-02-02 at 20 46 22](https://github.com/quarto-dev/quarto-cli/assets/5083500/ce28787e-5c6e-4bc9-a349-061271fb12fd)

Here is a reproducible example:

**custom.lua**

```
function RawInline (raw)
    if raw.format:match 'html' and raw.text == '<?quarto.version?>'then
      return tostring(quarto.version)
    end
    if raw.format:match 'html' and raw.text == '<?lua.date?>'then
      return tostring(os.date("%d-%m-%Y"))
    end
    if raw.format:match 'html' and raw.text == '<?lua.year?>'then
      return tostring(os.date("%Y"))
    end
    if raw.format:match 'html' and raw.text == '<?lua.time?>'then
      return tostring(os.date("%H:%M:%S"))
    end
  end
```

**_quarto.yml**

```
project:
  type: website

website:
  page-footer:
    left: "<?lua.year?> Brand"
    right: "Published with [Quarto](https://quarto.org/) v<?quarto.version?>"

format: html

filters:
  - custom.lua

```

**index.qmd**

```
---
title: Footer test
---

year: <?lua.year?>  

version: <?quarto.version?>

::: {style="background-color: red;"}
This is div with style.
:::

```

I run them like this:

```
docker run --platform=linux/amd64 -v ${PWD}:/work ghcr.io/quarto-dev/quarto:1.3.450 quarto render /work
docker run --platform=linux/amd64 -v ${PWD}:/work ghcr.io/quarto-dev/quarto:1.4.549 quarto render /work
```

Here is a repo with these files: https://github.com/royfrancis/quarto-footer-error  
Rendered view: https://royfrancis.github.io/quarto-footer-error
