### DISCUSSION TITLE
Why do I see "data-bs-theme='dark'" for the light version of my website?

### DISCUSSION THREAD

**Discussion by maelle** [quarto-dev/quarto-cli#8601] [Q&A]
### Description

I have created an example website https://github.com/maelle/darklight (https://maelle.github.io/darklight/)

With custom.css, dark.scss and light.scss introduced in `_quarto.yml` like so

```yml
format:
  html:
    code-link: true
    highlight-style:
      light: arrow
      dark: arrow-dark
    theme:
      light: [cosmo, light.scss, custom.scss]
      dark: [cosmo, dark.scss, custom.scss]
```

The links in the light navbar are white on white. When inspecting the elements to find what I did wrong, I see ".navbar[data-bs-theme=dark]" which is puzzling to me. 

I might be missing something obvious. :sweat_smile: 

![image](https://github.com/quarto-dev/quarto-cli/assets/8360597/9af7bfca-b175-4e2d-a88a-ac8c2761d945)
