### DISCUSSION TITLE
How can I use variables in custom formats?

### DISCUSSION THREAD

**Discussion by liyongg** [quarto-dev/quarto-cli#8631] [Q&A] [answered]
### Description

Hello.

For a custom RevealJS format I would like to be able to switch between some colours and ideally it would be with a variable in the yaml header.

For example, the `template.qmd` and a `.scss` file could look like this:

```
---
title: Untitled
format:
  customformat-revealjs: 
    theme_colour: '#FFFFFF'
date: last-modified
---

## Introduction
```

```
/*-- scss:defaults --*/
$theme_colour: {theme_colour};

$presentation-heading-color: $theme_colour;
```

Is this somehow supported already? Maybe with some Lua scripting?
