### DISCUSSION TITLE
Rendering PDF with Authors information

### DISCUSSION THREAD

**Discussion by riosavila** [quarto-dev/quarto-cli#8647] [Q&A] [answered]
### Description

Im trying to include some authors meta data in the PDF title-page.
Specifically , say that I have this information in the YAML

```
author:
  - name: Frios
    email: frios@frios.org
    affiliations: 
        - id: levy
          name: Frios LTDA
          city: Frios, LP
          country: USA   
    pdf: default
```
Now Im using PDF output. When I render the page, i see my name as the author of the paper, but I cant find a way to include the email or affiliation (other than typing it as "thanks"). Is there any way around it?
