### DISCUSSION TITLE
RSS feed. no index.xml file but there is a sitemap.xml

### DISCUSSION THREAD

**Discussion by davidleitch1** [quarto-dev/quarto-cli#8682] [Q&A] [answered]
### Description

I converted a Quarto blog to a website by changing the index.qmd to posts.qmd. and creating a new index.md landing page.
The _quarto.yaml has
```
project:
  type: website
website:
  title: "ITK Research" # logo-href: "ITK_logo.jpg"
  description: "Electricity markets analysis"
  site-url: https://itk.quarto.pub/itk_articles
  search: True
  comments:
  hypothesis: true
  navbar:
    background: primary
    left:
    - text: "Data"
      href: http://www.itkservices2.com
    - text: "Articles"
      file: posts.qmd
    - text: "Energy Insiders Podcast"
      href: https://soundcloud.com/reneweconomy-646697966
    right:
  - icon: rss
    href: index.xml
  - about.qmd
  ```

  but there is no index.xml. I do have a sitemap.xml. 
       Do I just change the index.xml in the yaml file to sitemap.xml? I apologise for such a space cadet question and would like to state how much fun it is working with Quarto, to the extent its getting in the way of my day job such as it is.
