### DISCUSSION TITLE
How to include additional info from authors

### DISCUSSION THREAD

**Discussion by lorenzoFabbri** [quarto-dev/quarto-cli#8690] [Q&A]
### Description

I have created a `yml` file of authors metadata:

````yaml
authors:
  - name: Lorenzo Fabbri
    email: lorenzo@something.com
    orcid: 0000
    affiliations:
      - ref: isg
    role:
      - conceptualization
      - methodology
      - data curation
      - software
      - formal analysis
      - writing - original draft
````
I then have a `qmd` file with the following:

````qmd
---
title: "Some title"
metadata-files:
  - authors.yml
format:
  html:
    embed-resources: true
---
````

In the resulting HTML I only see the author name, affiliation, and email/ORCID. I would like to include also the roles. I thought about including a template partial (`template-partials: - partials/metadata.html`):

````html
<meta charset="utf-8" />
$if(quarto-version)$
<meta name="generator" content="quarto-$quarto-version$" />
$else$
<meta name="generator" content="quarto" />
$endif$

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />

$for(author-meta)$
<meta name="author" content="$author-meta$ - $author-meta.role$" />
$endfor$
$if(date-meta)$
<meta name="dcterms.date" content="$date-meta$" />
$endif$
$if(keywords)$
<meta name="keywords" content="$for(keywords)$$keywords$$sep$, $endfor$" />
$endif$
$if(description-meta)$
<meta name="description" content="$description-meta$" />
$endif$

<title>$if(title-prefix)$$title-prefix$ – $endif$$pagetitle$</title>
````

But it does not work. I reasd on the website of Quarto that more advanced metadata elements are not currently implemented. Is this possible to achieve easily? Thank you.
