### DISCUSSION TITLE
How can I add a relative path to an image in my extension?

### DISCUSSION THREAD

**Discussion by DOH-FAA3303** [quarto-dev/quarto-cli#8724] [Q&A] [answered]
### Description

related post that did not work for me https://github.com/quarto-dev/quarto-cli/discussions/5694

I have a [quarto extension](https://github.com/coe-test-org/purpledoc) for an html theme and it has images included, along with the images referenced in the custom scss. I have another project that I want to add the extension to. When using `quarto add extension` everything works fine **ONLY if I reference the image in the scss like this `url(_extensions/coe-test-org/purpledoc/images/nwpage_tree_logo.png)`, notice the github org is added in the url :**

```scss
  /* Add logo to title block margin */
  .quarto-title-block .quarto-title-banner {
    background-image: url(_extensions/coe-test-org/purpledoc/images/nwpage_tree_logo.png);
    background-size: 140px;
    background-position: left;
    background-repeat: no-repeat;
    padding-left: 3%;
    background-origin: content-box;
  }
```

However, this file path cannot work when rendering the template.qmd or when creating a new project via `quarto use template` because the file path in those contexts use `_extensions/repo-name/images/image.png` and not `_extensions/github-org/repo-name/images/image.png` 

So, is there no way to reference the image in scss and also use the scss in both `quarto add` _and_ `quarto use template`? I have tried other's examples using `../../../../../image` but that will just up directories and will not find the image at all. 

This person has a work around that references the github image itself. Is that the only way? https://github.com/pat-alt/quarto-tudelft/blob/b324cee4a6860a5ed5385dc607330d49de052875/_extensions/tudelft/custom.scss#L12

and the inrae extension uses the full extension path including the github-org name. I noticed they don't have a template html, probably because it doesn't erros when rendering https://github.com/davidcarayon/quarto-inrae-extension/blob/main/_extensions/inrae/ressources/beamercolorthemeinrae.sty#L87
