### DISCUSSION TITLE
How to manage author template, default author and custom authors posts?

### DISCUSSION THREAD

**Discussion by aborruso** [quarto-dev/quarto-cli#8860] [Q&A] [answered]
### Description

Hi,
I have a default author in a blog. I set him in [`_metadata.yml`](https://github.com/aborruso/aborruso.github.io/blob/main/posts/_metadata.yml#L13-L19) file:

```yml
# Default author
author:
  - name: Andrea Borruso
    url: https://twitter.com/aborruso
    affiliations:
      - name: Associazione onData
        url: https://ondata.it
```

Sometime I need to add another author in a blog post, and I edit [the front matter](https://github.com/aborruso/aborruso.github.io/blob/main/posts/_metadata.yml#L13-L19):

```
author:
  - name: "Andrea Borruso"
    affiliation:
      - name: Associazione onData
        url: https://ondata.it
    url: https://twitter.com/aborruso
  - name: "Davide Taibi"
    affiliation:
      - name: "Istituto per le Tecnologie Didattiche - CNR"
        url: https://www.itd.cnr.it/
    url: https://www.linkedin.com/in/davide-taibi-b6825113/
```

I have these outputs:

- the two authors correctly rendered, in the [single post](https://aborruso.github.io/posts/leggere-interrogare-file-parquet/)

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/bbe6e26d-f319-4b3e-a8c6-7001e898f93d)

- the default author rendered twice, in the [overview view](https://aborruso.github.io/blog.html)

![image](https://github.com/quarto-dev/quarto-cli/assets/30607/8e4b64ff-f292-47fc-a89b-0796338052a4)

The blog list is based on [it](https://github.com/aborruso/aborruso.github.io/blob/main/blog.qmd):

```yml
title: "Blog"
listing:
  contents:
    - posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  feed: true
page-layout: full
title-block-banner: true
```

Is it a bug, or is there any way not to have the duplicate in the blog view?

Thank you
