### DISCUSSION TITLE
Why is code folding enacted for Python but not Bash?

### DISCUSSION THREAD

**Discussion by ctdarwell** [quarto-dev/quarto-cli#8865] [Q&A] [answered]
### Description

I enabled code folding for Bash in Quarto (in RStudio) with the following block:

```
execute:
  output: false
format:
  html:
    embed-resources: true
    code-fold: true
editor: visual
```

Now I have another doc built on top of that - it features both Python and Bash code. With the following block it code-folds the Python chunks but renders the Bash scripts as text - even though they've been called as 'executable':

```
execute:
  output: true
  echo: true
  eval: true
  error: true
jupyter: python3
format:
  html:
    fig-align: center
    fig-responsive: true
    embed-resources: true
    code-fold: true
    code-summary: "Show the code"
editor: visual
editor_options: 
  chunk_output_type: inline
```

How can I get both to display in html as folded code?
