### DISCUSSION TITLE
qmd files are not rendered in preview, but are shown after searching

### DISCUSSION THREAD

**Discussion by hopezh** [quarto-dev/quarto-cli#8869] [Q&A]
### Description

# Source code
I have the following quarto website published on github pages: [oatNotes](https://github.com/hopezh/oatNotes). 

# Issue
1. After cloning the git repo locally, `quarto preview` doesn't render any `qmd` files I added to `_quarto.yml`

```yaml
project:
  type: website
  output-dir: docs

website:
  title: "OatNotes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    title: "Contents"
    style: "floating"
    search: true
    contents:
      - section: "Quarto"
        contents:
          - quarto_tabset.qmd
      - section: "Deep Learning"
      - section: "Plotly"
        contents:
          - plotly_data_structure.qmd
```

<img width="1441" alt="Screenshot 2024-02-24 at 22 51 30" src="https://github.com/quarto-dev/quarto-cli/assets/23435810/6e10dc17-e910-4828-a073-942ba47968d2">

3. However, I can still search the `qmd` file I added, e.g. the notes on how to create `quarto tabeset` in this case: 
<img width="1441" alt="Screenshot 2024-02-24 at 22 51 45" src="https://github.com/quarto-dev/quarto-cli/assets/23435810/8554cf2c-3654-408e-bfe8-2ed7912c0780">

4. ...and hit `enter` will render the qmd file, and the sidebar is shown correctly:
<img width="1441" alt="Screenshot 2024-02-24 at 22 52 11" src="https://github.com/quarto-dev/quarto-cli/assets/23435810/5377ea86-74b5-4147-896f-448f7a4dcbe5">

5. However, clicking the `Home` button, or the `title` of the website, will make everything disappear: 
<img width="1441" alt="Screenshot 2024-02-24 at 22 51 30" src="https://github.com/quarto-dev/quarto-cli/assets/23435810/2ecc6738-bbc4-492b-8376-8d830a814f74">

6. This applies to the other file `plotly_data_structure.qmd` I added to the project, i.e., can only be rendered after seaching it: 
<img width="1441" alt="Screenshot 2024-02-24 at 22 52 28" src="https://github.com/quarto-dev/quarto-cli/assets/23435810/2fb9fa58-ce33-4185-ad45-d86b6748b713">

<img width="1441" alt="Screenshot 2024-02-24 at 22 52 35" src="https://github.com/quarto-dev/quarto-cli/assets/23435810/c34efa42-92e1-4d5b-b689-c92d142d6aec">

# Question
May I ask if I have missed anything import here that has led to this "renderable only after searching" issue? 

(I have another quarto website, [test_quarto_dashboard](https://github.com/hopezh/test_quarto_dashboard) also published as [github pages](https://hopezh.github.io/test_quarto_dashboard/), which doesn't seem to have such issue.)

Thanks.

# `quarto check` output
```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/oatmini/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.13 (Conda)
      Path: /Users/oatmini/anaconda3/envs/ai/bin/python
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
