### DISCUSSION TITLE
Render pdf one file at a time

### DISCUSSION THREAD

**Discussion by memeplex** [quarto-dev/quarto-cli#8895] [Q&A]
### Description

When I'm working on a pdf project, I would like to quickly preview the current chapter/section. I assume this means that I need to render just a small piece of the entire project, so I split the project in many small files to begin with. Now, I've read about [Incremental rendering](https://quarto.org/docs/projects/code-execution.html#incremental-render) and [Render targets](https://quarto.org/docs/projects/quarto-projects.html#render-targets) but I'm not sure whether I'm understanding what they bring to the table, specially for a pdf project.

For example, suppose this is my project config:

```
project:
  type: book

book:
  title: "mybook"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd

format:
  pdf:
    keep-tex: true
```

If I run `quarto render chapter1.qmd --to pdf` both chapters are included in the generated tex file.

If I add:

```
project:
  ...
  render:
    - chapter1.qmd
 ```

to the config and run `quarto render --to pdf` again both chapters are included.

The only way I found to work on a file by file basis is to comment out all other documents in the chapters section.

Is this right or am I missing something?

Thanks.
