### DISCUSSION TITLE
Allow rendering of manuscript notebook files in other formats

### DISCUSSION THREAD

**Discussion by bethanyhgardner** [quarto-dev/quarto-cli#8896] [Feature Requests]
### Description

I'm testing out manuscripts for a new paper, and overall I'm a fan! Ideally I would like to be able to render notebook files in PDF/docx, not just HTML. I think my ideal use case would be to have one or more of the notebook files be the manuscript supplement (generally includes more tables/figures etc), so it would be great to have the option of rendering in the same format(s) as the manuscript, since I'm going to have collaborators/journal submission portals that want a PDF, not an HTML file or link to site hosted on GitHub. Currently, adding additional formats to the YAML header of a notebook file or specifying an output format when rendering from command line don't have any effect.

**Comment by mcanouil** [comment]
I am not sure to follow.

Below is the default Manuscript project YAML file `_quarto.yml`.
As you can see there are several formats.

```yaml
project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true
```

You can also use Quarto CLI directly: `quarto render my-file.qmd --to docx`.


Could you share some minimal example we can use to play around and check what you tried and did not work? It's possible, there is a bug, but without code we can't know.
