### DISCUSSION TITLE
Problems with background colors when Quarto website is displayed on mobile phone.

### DISCUSSION THREAD

**Discussion by rruiz-s** [quarto-dev/quarto-cli#8916] [Q&A] [answered]
### Description

Hi,

I am trying to set the background of a quarto website white. When the website published using github is displayed in the computer, the background is white. This also applies when I display the website from the device view using also the computer. However, when I view the website with my mobile phone, the background is black.

In a .scss file I set the background white by adding these 2 variables:
```
.body{
  background-color: white;}
$body-bg: white; 
```

Additionally, in the quarto.qmd file I used:
```
format:
  html:
    page-layout: article
    backgroundcolor: white

```

I verified that the second chunk of code in the qmd file works when I render it in RStudio.  

The _quarto.yml section that defines the html format is:
```
format:
  html:
    theme: [./css/custom.scss]
    mainfont: Joan
    css: styles.css
    toc: true
```

The styles.css file is empty, only the default 
```
/* css styles */
```
I cross-checked and it seems to be related to the "dark mode" of some mobiles phones. Basically the website looks gray in some phones or directly black in others.  Any idea how I can ensure a good display of the website?
