### DISCUSSION TITLE
References in Quarto

### DISCUSSION THREAD

**Discussion by jameswoodgeog** [quarto-dev/quarto-cli#8959] [Q&A]
Hi,  I am trying to render a quarto pdf in RStudio. I have a number of references to add to the references section at the end of the document. These get added, but I would like to have each item separated by a blank line to make it more readable please.

````
---
title: "Coursework submission"
subtitle: "My title "

output:
  pdf_document:
    number_sections: true
mainfont: Calibri
author: "Student ID"
bibliography: refs.bib
---
````
