### DISCUSSION TITLE
How do I make multiple documents with a single external bibliography?

### DISCUSSION THREAD

**Discussion by postylem** [quarto-dev/quarto-cli#9026] [Q&A] [answered]
### Description

Say I have a number of different markdown files `summary.qmd`, `background.qmd`, `strategy.qmd`, that I want to each be rendered to a separate PDF file, and in each one I make references to citations, which I want to be rendered as a master references file (comprising a fourth PDF).

I can sort of get this to work like follows, but it's hacky, and isn't actually correct (see note below on why it doesn't work):

`_quarto.yml` lookes like this, where I have my three files, plus one more for the bibliography:
```yaml
project:
  render:
    - summary.qmd     # contains a reference to @item1
    - background.qmd  # contains a reference to @item2
    - strategy.qmd    # contains a reference to @item3, @item4
    - references.qmd

bibliography: mybibliography.bib
suppress-bibliography: true

format: pdf
```

`references.qmd` looks like this: (I copy all the references from the three content files in by hand)

```qmd
---
nocite: |
  @item1, @item2, @item3, @item4
---

### Bibliography

::: {#refs}
:::
```

That almost works, but the in-text references might be wrong, in the documents (for instance if citation `@item1` and `@item2` are by different authors with the same last name, they won't get disambiguated because only one is present in a given file, or, if you're using numbered-style citations, the numbers wont match across the files).

This feels like a rather common use case (writing reports, grants, etc).  Is there a way to do this with _book_ or _manuscript_ type project, maybe?  I can't see it, but I'm not well acquainted with what's possible.  It seems like rendering as a book would be almost perfect, but it introduces chapter structure to the documents, and prints them all in one pdf.  Maybe that's the only choice here?
