### DISCUSSION TITLE
script rendering without explicit preamble

### DISCUSSION THREAD

**Discussion by aronatkins** [quarto-dev/quarto-cli#9037] [Feature Requests]
### Description

It would be useful to support script rendering without requiring an explicit preamble. This would let folks take their existing scripts and use Quarto to run them.

For example, we have heard from many folks that they have existing R and/or Python scripts that are run by `cron` or some other scheduling system. Historically, they have found it inconvenient to restructure these scripts to run as R Markdown documents or Jupyter notebooks.

If Quarto were to support rendering without code updates, many of these existing scripts could be published (to systems like Posit Connect). 

```bash
quarto render script.R
```

This is a standalone script, outside the context of a project. When deployed, it but may receive a `_quarto.yml` in order to control the rendering output directory -- making it appear like a project.

Proposal:

* Quarto is able to render explicitly targeted scripts without requiring any preamble.
    1. `quarto render script.R` renders the script as-is.
    2. `quarto render` (project) renders specific `*.R` and `*.py` files enumerated in the project YAML.
* Quarto continues to require a preamble when _discovering_ scripts within a project.
    1. `quarto render` (project) renders any `*.R` and `*.py` when those scripts have a preamble (subject to other `render` restrictions).
 
```yaml
# Unconditionally renders etl.py
project:
    render: 
    - "*.qmd"
    - "etl.py"
```

```yaml
# Renders only *.R and *.py when they have a preamble.
project:
    render: 
    - "*.{qmd,R,py}"
```
