### DISCUSSION TITLE
repeaturl.com/repeaturl.com in RSS feed.  Is it me or is it Quarto?

### DISCUSSION THREAD

**Discussion by apsteinmetz** [quarto-dev/quarto-cli#9038] [Q&A] [answered]
### Description

My quarto-based blog has an RSS feed.  When I click on a link to a post in the rendered XML file [like so](https://simplepie.org/demo/?feed=https%3A%2F%2Foutsiderdata.netlify.app%2Findex.xml), it constructs a URL with the domain duplicated so instead of 
```
https://outsiderdata.netlify.app/posts/2024-03-10-the-truth-about-tidy-wrappers/
```
I get
```
https://outsiderdata.netlify.app/outsiderdata.netlify.app/outsiderdata.netlify.app/posts/2024-03-10-the-truth-about-tidy-wrappers/
```
which doesn't exist of course.  Is there something I need to fix in my YAML headers or is this a Quarto problem?  Thanks.

The YAML header of my index.qmd file looks like this:
```
title: "Outsider Data Science"
listing: 
  contents: posts
  sort-ui: true
  sort: 
    - "date desc"
    - "title desc"
  type: default
  categories: true
  feed:
    type: full
    items: 1
    description: "Putting what's in there, out there. With R!"
```
which generates this XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<rss  xmlns:atom="http://www.w3.org/2005/Atom" 
      xmlns:media="http://search.yahoo.com/mrss/" 
      xmlns:content="http://purl.org/rss/1.0/modules/content/" 
      xmlns:dc="http://purl.org/dc/elements/1.1/" 
      version="2.0">
<channel>
<title>Outsider Data Science</title>
<link>outsiderdata.netlify.app/</link>
<atom:link href="outsiderdata.netlify.app/index.xml" rel="self" type="application/rss+xml"/>
<description>Putting what&#39;s in there, out there. With R!</description>
<generator>quarto-1.4.549</generator>
<lastBuildDate>Sun, 10 Mar 2024 05:00:00 GMT</lastBuildDate>
<item>
  <title>The Truth About Tidy Wrappers</title>
  <dc:creator>Art Steinmetz</dc:creator>
  <link>outsiderdata.netlify.app/posts/2024-03-10-the-truth-about-tidy-wrappers/</link>
  <description><![CDATA[ 
```
...and so forth

FWIW, this is the _quarto.yml file for the site.  The `styles.css` file is empty.
```
project:
  type: website

website:
  title: "Outsider Data Science"
  site-url: "outsiderdata.netlify.app"
  twitter-card: true
  navbar:
    left:
      - text: Blog
        file: index.qmd
      - text: About
        file: about.qmd
      - icon: linkedin
        href: "https://www.linkedin.com/in/asteinmetz/"
      - icon: twitter
        href: "https://twitter.com/adababbage"
      - icon: mastodon
        href: "https://fosstodon.org/@adababbage"
      - icon: github
        href: "https://github.com/apsteinmetz"
      - icon: rss
        href: index.xml
      - text: "{{< fa blog >}}"
        file: blogroll.qmd

format:
  html:
    theme:
      dark: darkly
      light: cerulean
    css: styles.css
    toc: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

editor: source
freeze: auto
```
