### DISCUSSION TITLE
Why is my document title not being rendered as a level 1 heading in Word?

### DISCUSSION THREAD

**Discussion by nickriches** [quarto-dev/quarto-cli#9039] [Q&A]
### Description

I am trying to compile a document into Word. My document title is not being rendered in Word as a Level 1 heading. It is being rendered as "normal"

My yaml looks like this:

```
---
title: "General Introduction"
# bibliography: references.bib
editor:
  render-on-save: true
format:
  html:
    theme:
    - cosmo
    - callouts.scss
    toc: true
    number-sections: true
    shift-heading-level-by: 1
    embed-resources: true
    self-contained: true
    grid:
      sidebar-width: 180px
      margin-width: 180px
      gutter-width: 10px
  docx: #https://quarto.org/docs/reference/formats/docx.html
    toc: false
    number-sections: true
    reference-doc: custom-reference-doc.docx
    shift-heading-level-by: 1
---

# Introduction

Blah blah blah

```

This should absolutely work. My yaml file is identical to that of other people who do not report any issues. It works fine in html. Why is it not working in Word?

I wonder if this is something to do with Word on Mac?

(MacOs 14.2.1 (23C71), latest version of Quarto CLI downloaded, Client is VSCode)
