### DISCUSSION TITLE
How to Pass Custom Metadata Value to LaTeX Partials?

### DISCUSSION THREAD

**Discussion by TomBener** [quarto-dev/quarto-cli#9060] [Q&A] [answered]
### Description

Thanks for the kind reply of @cderv.

 #7692 has discussed the relevant issue about how to pass custom metadata value to LaTeX Partials. I encountered a similar issue that with this. The value of custom metadata in `before-body.tex` was expanded, but the same content in `title.tex` didn't.

The content in `_quarto.yml` is as follows. As the comment indicates, `before-body.tex` worked well, while `title.tex` didn't work:

```yml
title: A Quarto Example
author: Author Name
id-number: 230106
major: Computer Science
format:
  pdf:
    template-partials:
      - before-body.tex # Working
      # - title.tex # Not working
    # keep-tex: true
```

This is the Git repository of all files: https://github.com/TomBener/quarto-cli-9060

And I have also uploaded as a zip file below. Could you help to diagnose the issue. Thanks very much.

[test.zip](https://github.com/quarto-dev/quarto-cli/files/14588016/test.zip)
