### DISCUSSION TITLE
Rendering URLs as footnotes

### DISCUSSION THREAD

**Discussion by harrelfe** [quarto-dev/quarto-cli#907] [Q&A] [answered]
What is the preferred way to automatically convert inline URLs to footnotes when creating a PDF report?  I was using
```
pdf:
  header-includes:
    \renewcommand{\href}[2]{#2\footnote{\url{#1}}}
```
but with a recent `Quarto` update I'm getting an error because `hyperref` is not attached before `href` is redefined.

**Comment by cderv** [comment, marked as answer]
I think you have found a bug in Pandoc. 

With Pandoc, to add links as footnotes, it should be as easy as adding `links-as-notes: true` in YAML header.  https://pandoc.org/MANUAL.html#links 
However this is not working with recent version, probably because of a change in there template where the command declaration (same as yours) is made before package is loaded. 

I'll report an issue in Pandoc repo about that.

**Reply by cderv** [reply]
Reported in https://github.com/jgm/pandoc/issues/8077

> but with a recent Quarto update I'm getting an error because hyperref is not attached before href is redefined.

@harrelfe By the way you are getting an error in header-include because you are presupposing that `hyperref` is available. But with recent pandoc, it is not anymore loaded before header-includes. (following this change https://github.com/jgm/pandoc/commit/f3fcdd52c8bc722862ea73958d41fe53ec03ec1d) See 2.18 release note from Pandoc https://github.com/jgm/pandoc/releases/tag/2.18

You need to explicitly load hyperref. This should work 
````yaml
format: 
  pdf:
    header-includes: |
      \usepackage{hyperref}
      \renewcommand{\href}[2]{#2\footnote{\url{#1}}}
````

Once fixed in Pandoc and bundled in Quarto you'll be able to do this 
````yaml
format: 
  pdf:
    links-as-notes: true
````
