### DISCUSSION TITLE
Unable to reproduce YAML Listing Content example

### DISCUSSION THREAD

**Discussion by dspm** [quarto-dev/quarto-cli#9071] [Q&A] [answered]
### Description

Hello! I'm trying to reproduce the example from [YAML Listing Content](https://quarto.org/docs/websites/website-listings.html#yaml-listing-content) section in Guide > Websites > Listing Pages, but with no success. It looks like inputs that match a glob and inputs provided explicitly via YAML file are not getting merged and glob inputs take priority.

After creating a fresh project with `quarto create project blog testing` (version 1.4.551) I make a file `archived-items.yaml` in root directory which looks like this:

```
- title: "Archived Item 1"
  author: Norah Jones
  date: 2020-01-01
  path: "archived/archived-item-.html"
  categories: [archived, technology]
```

... and a file `custom.qmd` which looks like this:

```
---
title: "Listing Example"
listing:
  id: sample-listings
  contents: 
    - posts
    - archived-items.yaml
  sort: "date desc"
  type: table
---
```

... but the resulting listing shows only `.qmd` files from `posts` directory, not the entry from `archived-items.yaml`. The documentation says that sources of content should be merged, but it's not the case. 

If I comment out posts (`#- posts`) as a content source, item from `archived-items.yaml` is displayed.

Further and building from the example in documentation, if I create another YAML file as a source of content and edit `custom.qmd` accordingly:

```
---
title: "Listing Example"
listing:
  id: sample-listings
  contents: 
    #- posts
    - archived-items.yaml
    - archived-items-2.yaml
  sort: "date desc"
  type: table
---
```

... it will display items merged from both YAML sources. However, including `- posts` as a source will again display only posts and ignore explicit YAML sources.

Am I missing out on something or there is a problem in the documentation?
