### DISCUSSION TITLE
Suppress end of doc bibliography when using biblatex...

### DISCUSSION THREAD

**Discussion by olearydj** [quarto-dev/quarto-cli#9075] [Q&A] [answered]
### Description

When using biblatex as a citation engine (for backlinks), and generating the bibliographies where required using `printbibliography`, the rendered pdf is as expected, except that it includes a second copy of the bibliography at the end of the document.

This is the default behavior when using citeproc alternatives, but I can't find a way to disable it and only generate the refs where I want them. The `appendix-style: none` option only works with citeproc.

Here's my "minimal" example...

`_quarto.yaml`:

```yaml
project:
  title: "quarto-tests"
  type: book

bibliography: references.bib

book:
  chapters:
    - index.qmd
    - chapter.qmd
    - refs.qmd

format:
  pdf:
    link-citations: true
    cite-method: "biblatex"
    biblio-style: "apa"
    biblatexoptions: 
      - "backend=biber"
      - "backref=true"
    documentclass: scrbook
```

`index.qmd` is empty (which is the source of a future discussion...)

`chapter.qmd`:

```qmd
## Chapter

This is my chapter, which includes the now classic insider reference [@vaswani].
```

`refs.qmd`, where I need the bib to be included, before appendices (not included in this example):

```qmd
# References {.unnumbered}

\begingroup
\raggedright
\printbibliography[heading=none]
\endgroup
```

The resulting pdf includes the expected front-matter, chapter page with citation, and then the references:
<img width="828" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/42705243/61a6696d-0c6a-41d4-ba8d-a8447097bba0">

Followed by the duplicated, unwanted bibliography:
<img width="802" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/42705243/8eb2a42d-9ecf-439b-bee1-e8bbaca9382b">

Quarto version 1.4.550
MacOS 14.3.1

Thanks for any suggestions you might have!
