### DISCUSSION TITLE
Can I skip generating a title slide with reveal.js?

### DISCUSSION THREAD

**Discussion by aidanmontare-fed** [quarto-dev/quarto-cli#9084] [Q&A]
### Description

Hi! I've seen that not specifying a `title` in the yaml block is supposed to disable the generation of a title slide in reveal.js. But it seems like quarto will find the first heading of the document and use that as the title anyway. Is there a way I can disable this so that I can start my presentation with a custom slide?

**Comment by jimjam-slam** [comment]
Not sure if this is the canonical way of doing it, but I put in an empty second-level Markdown header (usually so that I can make a "custom" title slide, but I don't see why you can't use it to put any content. [For example](https://github.com/jimjam-slam/talk-ssavic-feb2024/blob/main/index.qmd):

````yaml
---
format:
  revealjs: 
    theme: [default, style/style.scss]
    highlight-style: github
    width: 1400
code-annotation: select
filters:
- webr
- pyodide
webr:
  packages: ["ggplot2"]
---

## {.center}

<div style="margin-top: 150px;">

<h1>No installation required<h1>

<h3 class="deck-subtitle">
Instant coding demos and workshops using<br>**dev containers** and **WebR**
</h3>
````
