### DISCUSSION TITLE
Is it possible to add a favicon to a Quarto dashboard?

### DISCUSSION THREAD

**Discussion by melissavanbussel** [quarto-dev/quarto-cli#9118] [Q&A] [answered]
### Description

Is it possible to add a favicon to a Quarto dashboard? I couldn't find any with favicons on the [examples page](https://quarto.org/docs/dashboards/examples/). For example, assume this is `dashboard.qmd`: 

```
---
title: "My Quarto Dashboard"
format: 
  dashboard:
    favicon: logo.png
    logo: logo.png
---
```

The logo shows up on the dashboard, but the favicon doesn't. 

Thank you in advance for your help!
