### DISCUSSION TITLE
[profile group] how to use profiles and profiles group to render multiple distinct documents?

### DISCUSSION THREAD

**Discussion by kompre** [quarto-dev/quarto-cli#9152] [Q&A]
### Description

I have the need to produce multiple distinct documents that share common metadata and sections of text, so it make sense to me to have just one project folder that contains these multiple documents and common resource, without having too much overhead (e.g. the python virtual environment).

To achieve so I started playing with the profile feature, defining multiple profiles for each document. I'm using the `book` type and the structure of the project is roughly so:

1. a `_quarto.yaml` file where common properties are defined
2. a `_quarto-basic.yaml` file where are defined the `chapters` for the `basic` document

```yaml
# _quarto-basic.yaml
book:
  chapters:
    - index.qmd
    - basic/chapter_1.qmd
    - basic/chapter_2.qmd
    - conclusion.qmd
``` 

3. a `_quarto-advanced.yaml` file where are defined the `chapters` for the `advanced` document

```yaml
# _quarto-advanced.yaml
book:
  chapters:
    - index.qmd
    - advanced/chapter_1.qmd
    - advanced/chapter_2.qmd
    - conclusion.qmd
``` 

So far so good. Each profile produce a different document as intended.

Now I don't understand what defining the profile group actually does. I've added the following the `_quarto.yaml`

``` yaml
profile: 
  group: 
    - [basic, advance] # a nested list?
```

To my understanding it will set the `basic` profile as the default one, so that the preview and `quarto render` command will render the basic profile by default. **I don't understanding what listing the other profiles in the group actually does or when it comes into play?**

I erroneously thought that when calling `quarto render` command in the terminal, all documents in the list would be rendered, but it's not the case.

I even tried `quarto render --profile basic,advanced`, but only one document is rendered, and the `basic` and `advanced` profile are merged together, which is not what I'm looking for.

Is there a way to render all the different profile as individual documents with just one command call instead of calling each document to be rendered?

```bash
# compress all these command into one?
quarto render --profile basic
quarto render --profile advance
```

By the way I will not be too distraught if it's not possible, but I really don get why we define the profile group as a nested list.
