### DISCUSSION TITLE
link color in quarto

### DISCUSSION THREAD

**Discussion by reddylee** [quarto-dev/quarto-cli#9175] [Q&A]
### What would you like to do?

Give feedback or suggest an improvement

### Description

I tried add color to highlight the link, citation in typst in quarto, but failed.

**Comment by mcanouil** [comment]
See <https://typst.app/docs/> and you likely add what you find using `include-in-*` options.

**Comment by cderv** [comment]
Once a way to do this in typst is shared, it could be worth asking Pandoc to include in template to mimic the `linkcolor` variable available from HTML and LaTeX.

Currently for typst, I don't think they support it.

**Comment by joelostblom** [comment]
I haven't tested with citations, but the following works to color regular links:

```yaml
format:
  typst:
    include-in-header:
        - text: |
            /* Color links */
            #show link: set text(fill: rgb(0, 0, 255))
```

You could also specify a hex color instead of numbers inside `rgb` as per https://typst.app/docs/reference/visualize/color/
