### DISCUSSION TITLE
allow {py} or {} instead of {python} in .qmd files

### DISCUSSION THREAD

**Discussion by dfolch** [quarto-dev/quarto-cli#9177] [Show and Tell]
### Description

The new inline code feature added in 1.4 is amazing. However, typing out `{python}` all the time in `.qmd` files can get annoying. 

Add the following to the YAML to create a `py` alias for python.
```{markdown}
jupyter: 
  kernelspec:
    name: "python3"
    language: "py"
    display_name: "Python"
```
This will allow the following syntax to work.
```{markdown}
    ```{py}
    hours = 8 * 5
    ```

    There are `{py} 8 * 5` hours in a workweek. 
```

You can use the following if you want to shorten the syntax to `{}`. Note: this only works for code chunks, not inline code within Markdown.
```{markdown}
jupyter: 
  kernelspec:
    name: "python3"
    language: ""
    display_name: "Python"
```
