### DISCUSSION TITLE
How can I insert external links in the left sidebar?

### DISCUSSION THREAD

**Discussion by joelostblom** [quarto-dev/quarto-cli#9222] [Q&A] [answered]
### Description

In JupyterBook, I can have links to external sites directly in the left sidebar, like this:

![image](https://github.com/quarto-dev/quarto-cli/assets/4560057/85633a86-6385-4f7a-b369-2487051d4a52)

```yaml
  - caption: Resources
    chapters:
      - url: https://dash.plotly.com/tutorial
        title: Dash documentation
      - url: https://open-resources.github.io/dash_curriculum/part1/chapter1.html
        title: Dash tutorials
```

Is it possible to do something similar in Quarto? Or do I have to create a separate markdown document with the links?
