### DISCUSSION TITLE
Is it possible to load the `theme` file from a URL?

### DISCUSSION THREAD

**Discussion by VladimirAlexiev** [quarto-dev/quarto-cli#9227] [Q&A] [answered]
### Description

We're building a library of `revealjs` presentations, and want all resource files to be shared globally on a server, rather than being copied to individual presentation folders. This works for all files except the `theme` css:

```yaml
format:
  revealjs:
    theme: https://presentations.ontotext.com/resources/ontotext.scss
```
It interprets it as a local file (I am on Windows):
```
quarto render presentation.qmd --to revealjs
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'https:\presentations.ontotext.com\resources\ontotext.scss'
```
I also tried with `resource-path`:
```yaml
format:
  revealjs:
    resource-path: [https://presentations.ontotext.com/resources/]
    theme: ontotext.scss
```
but it still doesn't work:
```
make
quarto render presentation.qmd --to revealjs
ERROR: NotFound: The system cannot find the file specified. (os error 2)
NotFound: The system cannot find the file specified. (os error 2)
```
