### DISCUSSION TITLE
Getting the meta shortcode to produce an array

### DISCUSSION THREAD

**Discussion by andrewpbray** [quarto-dev/quarto-cli#9232] [Q&A] [answered]
### Description

Hello!

I'm trying to use the `meta` shortcode to, in effect, rearrange some of the meta data in a project, and it looks like it currently doesn't quite fit my use-case. I'm looking for guidance for how to make it produce an array.

Here is the `_quarto.yml` for the website:
```yml
project:
  type: website

website:
  title: "Proj-shortcode"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - section: Pages
        contents:
          - page 1
          - "{{< meta foo >}}"

metadata-files: 
  - contents.yml
```
where `contents.yml` is 
```yaml
foo:
  - page 2
  - page 3
```
This produces a sidebar nav like:
<img width="254" alt="Screenshot 2024-03-29 at 10 41 01 AM" src="https://github.com/quarto-dev/quarto-cli/assets/1627362/70c0dcc5-df39-4f7d-bee3-6f2f687e85eb">

This isn't too surprising based on the [source for the shortcode](https://github.com/quarto-dev/quarto-shortcodes/blob/a52478fe03f7bcbcf132003ba03db8cb461a5902/shortcodes.lua#L815-L820) (I assume this is the same source used in `quarto-cli`):

```lua
-------- meta shortcode --------
-- Implements reading values from document metadata
-- as {{< meta title >}}
-- or {{< meta key.subkey.subkey >}}
-- This only supports emitting simple types (not arrays or maps)
```
My question: should I go ahead and write my own shortcode to emit an array or should I see if I can add this to the existing implementation? I imagine how in non-metadata settings, emitting an array is tough to know how to format, so maybe its best to keep `meta` as simple types only?

Minimal repo: [https://github.com/andrewpbray/proj-shortcode](https://github.com/andrewpbray/proj-shortcode)

**Comment by cscheid** [comment, marked as answer]
> I imagine how in non-metadata settings, emitting an array is tough to know how to format, so maybe its best to keep meta as simple types only?

Yes, that's part of the problem; we need to teach shortcodes to resolve differently based on their context. Resolving the "meta" shortcode so it expands into arrays and objects properly in a meta context would be ideal.

Unfortunately, let me be a bit frank here. This would be a large implementation effort for a fairly narrow payoff. I'd love to do it, but it's not going to be high in our priority list.

**Reply by andrewpbray** [reply]
Makes sense. I’ll try writing my own narrowly scoped short code and will be happy to switch over to meta if/when this gets implemented.

**Reply by andrewpbray** [reply]
@cscheid While trying to implement my own, I bumped into a separate issue: the shortcode gets executed after paths to files get resolved into links.

If `_quarto.yml` looks like
```yml
website:
  title: "Proj-shortcode"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - section: Pages
        contents:
          - about.qmd
          - "{{< meta foo >}}"
          - "{{< meta bar >}}"
```
and `contents.yml` looks like
```yml
foo:
  - page 2
  - page 3
bar: about.qmd
```
the result is 
<img width="259" alt="Screenshot 2024-03-29 at 1 59 23 PM" src="https://github.com/quarto-dev/quarto-cli/assets/1627362/a9864a07-28e3-4d77-97e5-c4b92bddce57">
i.e. that final "about.qmd" item is not a link.

I tried writing my own shortcode and using `pre-ast` to hopefully catch the path->link stage, but no dice. Was `pre-ast` only implemented for filters?

**Reply by cscheid** [reply]
Yes - pre-ast is a filter setting. That's by design, because shortcode resolution is itself a filter.

**Reply by andrewpbray** [reply]
I noticed that - very clever!

Would something like this work if I had the correct path to the (non-contributed) shortcodes filter?
```yml
contributes:
  filters:
    - at: pre-ast
      path: shortcodes.lua
  shortcodes:
    - auto-nav.lua
```
Or can you only fiddle with the order of your own filters?
