### DISCUSSION TITLE
It is possible to disable/edit the href link to the sidebar logo  for independent sidebars on _quarto.yml ?

### DISCUSSION THREAD

**Discussion by paulobarros** [quarto-dev/quarto-cli#9257] [Q&A]
### Description

I have individuals sidebars created for specific sections of the quarto website, it is possible to change/disable the link from the sidebar logo for each specific sidebar in the `_quarto.yml`? 

The `logo-href` option only allows for a global change for all logos on every sidebar, I guess...

**Comment by mcanouil** [comment]
Would you mind sharing a repository with a small example of the setup of your project?
You could tweak the default website project created via: `quarto create project website`

**Reply by paulobarros** [reply]
Sure. Let me try to explain my setup first. [This is my current website](www.paulobarros.com.br), you can check my [repo settings here](https://github.com/paulobarros/pb-quarto/tree/main).

In the branch I am currently working on, I've created a folder called `education` where I intend to have separate folders for different classes. In those folders, I will use a different layout for the website page, with a fixed sidebar with the logo.  [Here is the repo for the branch](https://github.com/paulobarros/pb-quarto/tree/teaching).

My issue is that the logo on the sidebar will point to the site homepage, and I was wondering if there is a way to set an individual `href` for each sidebar logo. My suggestion would be something in the `sidebar` portion of the `_quarto.yml` , like this:

Current `_quarto.yml`

```
sidebar:
      - id: genquant
        logo: education/genquant/images/genquant.png
        style: docked
        collapse-level: 3
        contents:
          - section:  "Genética Quantitativa"
            contents: education/genquant/*
```

Suggestion:

```
sidebar:
      - id: genquant
        logo: education/genquant/images/genquant.png
        logo-href: # here I would point to index.qmd of my class folder, or other link
        style: docked
        collapse-level: 3
        contents:
          - section:  "Genética Quantitativa"
            contents: education/genquant/*
```
My solution this far was to use CSS to disable the link on the sidebar, since the first entry on the sidebar menu is linked to the `index.qmd` of the folder, this works for me now, but it would be useful to have a way to set individual links for each sidebar logo. I don't know if my case is very specific, sorry about that.

**Reply by mcanouil** [reply]
> My solution this far was to use CSS to disable the link on the sidebar, since the first entry on the sidebar menu is linked to the index.qmd of the folder, this works for me now, but it would be useful to have a way to set individual links for each sidebar logo. I don't know if my case is very specific, sorry about that.

For now, it would be the only solution I believe.

FYI, There is an issue when using logo in the sidebar where the active nav link does not change.
- https://github.com/quarto-dev/quarto-cli/issues/9277

**Reply by mcanouil** [reply]
Sorry, I don't understand the whole issue here.
I just tested by adding logo-href and it works.
Did you try to use the option?

Edit: this is a 1.5 change which is listed in the changelog, but not yet documented, as 1.5 is a pre-release.

```yaml
website:
  sidebar:
    - id: first
      logo: https://quarto.org/quarto.png
      logo-href: about.qmd
    - id: second
      logo: https://quarto.org/quarto.png
      logo-href: index.qmd
```

https://github.com/quarto-dev/quarto-cli/assets/8896044/fea58439-af94-4875-96d1-126c4098487a
