### DISCUSSION TITLE
Is there a way to use thematic package in a quarto document so that your ggplots change with dark /light mode?

### DISCUSSION THREAD

**Discussion by usrbinr** [quarto-dev/quarto-cli#9331] [Q&A] [answered]
### Description

Hi!
I'm getting used to bslib and thematic libraries which are fantastic but most of the documentation appears directed towards rmarkdown or shiny.

For the most part I'd say most of the functionality of the bslib package works in quarto (eg. bslib::value_box()) however when it comes to thematic, I can't get it to work with my two themes

In my `_quarto` document I have the below settings and this works perfectly for toggling dark and light mode. However when I add a thematic argument `thematic::thematic_rmd()` or `thematic::thematic_on()`, I get an error and the quarto document won't compile.

Any thoughts on how to get a ggplot2 theme to change between the different themes in the quarto document

```
format:
  html:
    code-fold: true
    theme: 
      light: [cosmo,style.css]
      dark: [darkly,sytle.css]
```
Misc info:
$ quarto --version
1.3.433

$ uname
MINGW64_NT-10.0-19045
