### DISCUSSION TITLE
Quarto book pdf failing with 'sectsty' included

### DISCUSSION THREAD

**Discussion by pbradl42** [quarto-dev/quarto-cli#9339] [Q&A] [answered]
### Description

Hello - I've been chasing this error for a couple of hours. Any help would be appreciated.

The issue is when compiling in books xelatex, or laulatex, for that matter, it fails when I include the package sectsty.  

This _quarto.yml fails with: 
```Undefined control sequence.
\NR@part ...elax \refstepcounter {part}\@maybeasf 
                                                  \addcontentsline {toc}{par...
l.233 \part{part1}
```

The _quarto.yml is this:
```
project:
  title: "Minimal example of failure - book Quarto"
  type: book
book:
  author: "Jane Doe"
  date: "5/9/2021"
  chapters:
    - index.qmd
    - part: part.qmd
      chapters: 
        - template.qmd

format: 
  pdf:
   include-in-header:
      text: |
        \definecolor{light}{HTML}{e0f3f8}
        \usepackage{sectsty}
        \usepackage{titlesec}
```

**But** this one works:

```
project:
  title: "Minimal example of failure - book Quarto"
  type: book
book:
  author: "Jane Doe"
  date: "5/9/2021"
  chapters:
    - index.qmd
    - part: part.qmd
      chapters: 
        - template.qmd

format: 
  pdf:
   include-in-header:
      text: |
        \definecolor{light}{HTML}{e0f3f8}
#        \usepackage{sectsty}
#        \usepackage{titlesec}

```

It also only fails when 'part' is included in book, as the error indicates. So this one works:

```
project:
  title: "Minimal example of failure - book Quarto"
  type: book
book:
  author: "Jane Doe"
  date: "5/9/2021"
  chapters:
    - index.qmd
    - part.qmd
#      chapters: 
    - template.qmd

format: 
  pdf:
   include-in-header:
      text: |
        \definecolor{light}{HTML}{e0f3f8}
        \usepackage{sectsty}
        \usepackage{titlesec}
```

Same files compiled in the same order. Failure ONLY when '- part:' is included. Any ideas?
