### DISCUSSION TITLE
How to include `format-links` in html of the book project?

### DISCUSSION THREAD

**Discussion by TomBener** [quarto-dev/quarto-cli#9352] [Q&A] [answered]
### Description

With the command `quarto create project book mybook`, I created a demo book project. But by running `quarto render --to html`, the generated html does not include other formats (docx, pdf), even if the `format-links: true` was added in `_quarto.yml`. Also, I found that by running `quarto render --to html`, the prior outputs under `_book` would be removed. Is this a bug or feature?

What I want to achieve in the book project:

1. Include other format links in html with `format-links: true`.
2. Include multiple kinds of file formats in the generated folder (`_book` by default) at the same time.

I use Quarto 1.5.9 on macOS 14.4.1:

```
$ quarto check

Quarto 1.5.29
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.29
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/username/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /Users/username/.pyenv/versions/3.10.10/bin/python3
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /opt/homebrew/Cellar/r/4.3.3/lib/R
      LibPaths:
        - /Users/username/.R/packages
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.3/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
For `format-links` to work, you need to render all formats involved.
Why do you specify `--to html`?

> Also, I found that by running quarto render --to html, the prior outputs under _book would be removed. Is this a bug or feature?

You should not have anything under `_book` that is not defined in your book.
Use `resources` to list external resources and ensure they are copied to the output location, see <https://quarto.org/docs/websites/website-tools.html#site-resources>.

**Reply by TomBener** [reply]
Thanks. But by executing `quarto render` to render all format still didn't include `format-links` in html. The `_quarto.yml`:

```yaml
project:
  type: book

book:
  title: "My Book"
  author: "Norah Jones"
  date: "4/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    format-links: true
  pdf:
    documentclass: scrreprt
```
