### DISCUSSION TITLE
Quarto book generates docx, header, and footer issues

### DISCUSSION THREAD

**Discussion by chuxinyuan** [quarto-dev/quarto-cli#9372] [Q&A]
### Description

I want to finish my thesis through Quarto, but I do not know how to set the header and footer. The following is the format requirements of the school.

- Headers start in the chapter after the summary, and odd and even pages have different headers.

- Page numbers are numbered from the chapter following the summary and are displayed in the center of the footer.

### Take Quarto book, which comes with RStudio

First, I added '\newpage' at the end of each chapter. I need to set the header and page number starting from the Introduction chapter.

Second, yaml file added docx format

```yaml
project:
  type: book

book:
  title: "Book header and footer"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  docx:
    toc: false
```

At present, my book generates both html and docx, please ask everyone how I can achieve it, thank you.
