### DISCUSSION TITLE
How can I escape double quotes ("") when executing shell command in the post render phase?

### DISCUSSION THREAD

**Discussion by kompre** [quarto-dev/quarto-cli#9391] [Q&A] [answered]
### Description

Hi, 

I'm going mad trying to exectute some shell command (`pwsh`) that require double quotes `"`, because it seems that they simply disappear when passed to `deno`. I think the parser is to blame, since I can't replicate the same behaviour feeding directly the command to a pwsh terminal session (with some adjustment)

Is it possible to escape the double quotes?

- the `_quarto.yml`:

```yaml
project:
  title: "double quotes"
  output-dir: _book
  post-render: 
    - |
      pwsh -Command & {
        $filename = 'some file with space.pdf' 
        Copy-Item -Force -Path _book/*pdf -Destination $filename 
        Start-Process -FilePath 'C:\Program Files\SumatraPDF\SumatraPDF.exe' -ArgumentList `"$filename`"
      }
```

- the `qmd`:

```qmd
---
title: "double_quotes"
format: pdf
---

## double quotes


the post render does the following, in pwsh
1. set the variable $filename
2. copy the pdf file generated by quarto with $filename
3. open the copied file with SumatraPDF

things falls apart at #3 because the filename has space in it, and `-ArgumentList` will spit a string containing space into a list of arguments. In this case $filename should really be passed enclosed in the double quotes, but the double quotes simply disappears, and I'm not able to escape them so that the string will be formatted correctly
```
