### DISCUSSION TITLE
Can I embed an extension in a custom project type?

### DISCUSSION THREAD

**Discussion by andrewpbray** [quarto-dev/quarto-cli#9393] [Q&A]
### Description

Hello!

I've created a custom project type and when I went to embed an extension, I got an unexpected error:
```bash
quarto add quarto-ext/fancy-text --embed lexdocs

ERROR: The extension lexdocs does not contribute a format.
You can only embed extensions within an extension which itself contributes a format.
```
I'm curious: why are extensions not embeddable within custom project types?

Here is a minimal repo that you can use to run the above command and reproduce the error:
<https://github.com/andrewpbray/custom-project-type>

**Comment by cscheid** [comment]
(cc @dragonstyle)

**Comment by andrewpbray** [comment]
A follow-up: it looks like you can fool this check throwing in a blank custom format alongside your custom project type and `_extensions.yml`:

```yml
contributes:
  project:
    project:
      type: website
    website:
      page-footer: |
        "Copyright 2022, Lexcorp, Inc." 
  formats:
    html:
      toc: true
```

`quarto add quarto-ext/fancy-text --embed lexdocs` now goes through without an error.
