### DISCUSSION TITLE
Website: not able to disable search

### DISCUSSION THREAD

**Discussion by aborruso** [quarto-dev/quarto-cli#940] [Q&A] [answered]
Hi,
in a single page [website](https://aborruso.github.io/ivg-datibenecomune/), I have

```yaml
  navbar:
    search: false
```

but the search bas is active. The repo is this https://github.com/aborruso/ivg-datibenecomune

How to disable the search?

Thank you

**Comment by jjallaire** [comment, marked as answer]
This option goes at the `website` level. e.g.

```yaml
website:
  title: "website-search-feature"
  search: false
  navbar:
    background: primary
```

See https://quarto.org/docs/websites/website-search.html#disabling-search
