### DISCUSSION TITLE
how to define a navbar partials for a custom extension (project: website)

### DISCUSSION THREAD

**Discussion by ThierryO** [quarto-dev/quarto-cli#9467] [Q&A] [answered]
### Description

I'm trying to customize the navbar of website project extension. Below is what I tried. It adds my version of the navbar instead of replacing it. I'm using quarto 1.4.550 on Ubuntu 22.04.

## `_extension.yml`

``` 
title: my extension title
author: me
version: 0.1.0
quarto-required: ">=1.4.0"
contributes:
  project:
    project:
      type: website
  website:
    sidebar:
      style: docked
  format:
    html:
      template: "partials/template.html"
      template-partials:
        - "nav-container.html"
```

## `template.html`
Only the relevant snippet

``` 
<body>
${nav-container.html()}
$for(include-before)$
$include-before$
$endfor$
$body$
$for(include-after)$
$include-after$
$endfor$
</body>
```

## `nav-container.html`

```
    <div class="navbar-brand-container"> test
    </div>
```
