### DISCUSSION TITLE
QuartoPub view statistics

### DISCUSSION THREAD

**Discussion by jpmorr** [quarto-dev/quarto-cli#9501] [Q&A] [answered]
### Description

I'm wondering if it is possible to see number of visits or views or downloads for presentations shared on QuartoPub? It's so simple to use, but it would be nice to be able to track views or usage.

**Comment by mcanouil** [comment, marked as answer]
You'll to setup such analytical tools for your website.
Quarto Pub cannot add this to your website.

See for example <https://quarto.org/docs/websites/website-tools.html#google-analytics>.
You can of course use other framework and add them manually to your website via `include-in-*` YAML keys.

**Comment by muhaksim** [comment]
Is there a secure way I can use Google Analytics tracking code if I am using GitHub pages to host my blog? I have to make the blog repo public to use GitHub pages for free. 

I found this in the docs but it is not secure:

```
website:
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-XXXXXXX"
    anonymize-ip: true
```

Do you have any solution, @mcanouil?
