### DISCUSSION TITLE
When previewing a project, how to hide the output notebooks (out.ipynb) by prefix'ing the file names with a '.', or redirect them to a different folder?

### DISCUSSION THREAD

**Discussion by rraadd88** [quarto-dev/quarto-cli#9506] [Q&A] [answered]
### Description

I am previewing a website using this command:

```
quarto preview index.ipynb
```
This file embeds outputs from notebooks located in `notebooks` folder 

```
_quarto.yaml
index.ipynb
notebooks/
  nb1.ipynb
  nb2.ipynb
```
When previewing, the output `.out.ipynb` files are stored in this way
```
_quarto.yaml
index.ipynb
notebooks/
  nb1.ipynb
  nb1.out.ipynb <--
  nb2.ipynb
  nb2.out.ipynb <--
```
In attempt to control the location of these (redundant) files, I set `output-dir` in `_quarto.yaml`.
```
project:
  type: website
  output-dir: _output/
  render:
  ## ignore
    - "!data/"  
  preview:
    port: 8000
    browser: false
    
website:
  sidebar:
    search: true
    
format:
  html:
    toc: true
notebook-links: false
```
But this does not have any effect, I suppose because I am previewing not rendering.

Therefore I would like to either 
1. **Hide** those `out.ipynb` files by adding a '.' prefix. Could [output-ext, output-file](https://quarto.org/docs/reference/formats/html.html#rendering) parameters help in this regard?
**OR**
2. **Redirect** these files to `_outputs` folder as indicated in the `_quarto.yaml`. 

**Could either of these be possible?**

---
Quarto 1.4.553 on Ubuntu
