### DISCUSSION TITLE
How to make the grid items circular correctly

### DISCUSSION THREAD

**Discussion by camilogarciabotero** [quarto-dev/quarto-cli#9509] [Q&A] [answered]
### Description

So I am trying to create a list of people in a website using the grid `type`.  And my `people.qmd` starts like this:
```
---
title: ""
toc: false
page-layout: article
listing:
  - id: current-members
    type: grid
    categories: false
    grid-item-align: center
    grid-columns: 4
    fields: [image, subtitle, title]
    grid-item-border: false
    image-placeholder: imgs/default.png
    contents: 
    - people/current-members/*.qmd
---
```

I could not find the discussion, bit I once asked how to make the items (cards) appeared circular. I was pointed to edit the `.casrd-img` element in my `style.css`:

```
.card-img {
  border-radius: 50%;
}
```

The result looks nice (apparently):

![Screenshot 2024-04-27 at 8 42 22 PM](https://github.com/quarto-dev/quarto-cli/assets/25586362/b7261462-d17d-4e35-ab51-62c376d01859)

But then, when playing around with the page, I noticed that if I changed the window width, the circle cards just became (ugly) ovals:

![Screenshot 2024-04-27 at 8 43 52 PM](https://github.com/quarto-dev/quarto-cli/assets/25586362/65a5d665-2260-4fd9-990f-02474b7bc0a0)

How can I make the `card-img` play nice when changing the size of the windows, or even when displaying on a mobile?

**Comment by mcanouil** [comment]
You need to use your favourite browser inspect/developer mode to see what's the rule at play and update yours accordingly.
The inspect/developer mode allows to display according to different devices.

Note that this is an HTMl/CSS question which is only indirectly related to Quarto. 

<img width="1624" alt="Screenshot 2024-04-28 at 13 12 15" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c0a2bc67-1de9-4993-8333-83859e29c779">

**Comment by camilogarciabotero** [comment]
Thanks, 

Yeah, this is an HTML/CSS-related question. I will play around with what you suggest, but shouldn't this be a simple adjustment under the `grid` option? Something as simple as:

```yaml
listing:
    type: grid
    image-shape: [rectangle, round, rounded]
```

This is already a default feature in the `about` pages, with a consistent circular card for the desired image when using the `jolla` template.

**Reply by mcanouil** [reply]
"As simple" is not as simple.
Feel free to open a feature request describing this specific idea.

Some related opened issues:
- https://github.com/quarto-dev/quarto-cli/issues/2999
- https://github.com/quarto-dev/quarto-cli/issues/7027
- https://github.com/quarto-dev/quarto-cli/issues/7028
- https://github.com/quarto-dev/quarto-cli/issues/6383

**Reply by camilogarciabotero** [reply]
Right, never said easy to implement, just that it seems like a common user decision. Thanks for pointing out all the open issues.

**Reply by mcanouil** [reply]
You also have the freedom to use a custom EJS template for your listing which will offer way more flexibility.
For instance the "speaker" listing and generally the following conference website template: https://github.com/satRdays/quarto-satrdays-template/blob/main/program/speakers/speakers.ejs

**Reply by camilogarciabotero** [reply]
Cool example, thanks!

**Comment by camilogarciabotero** [comment, marked as answer]
I might have found a simple tweak to the `.card-img` class, that helped in my case:


```yaml
.card-img {
  border-radius: 50%;
  height: 10em; 
  width: 10em;
} 
```
