### DISCUSSION TITLE
How do I set the correct paths when using local fonts in a website theme?

### DISCUSSION THREAD

**Discussion by chiragraman** [quarto-dev/quarto-cli#9516] [Q&A] [answered]
### Description

Hello! 

This is most likely a basic question but I'd appreciate any help. I am trying to use custom fonts in a website project, and am running into errors arising from incorrect paths. I have set up a minimal example here with Fira Code as an example: https://github.com/chiragraman/quarto-fonts-test.

So far, I have followed the steps outlined in Issue #4387:
- add the fonts as resource files
- specified the `@font-face` declarations under `/*-- scss:rules --*/`
- turned off the web-font paths by setting `$web-font-path: "No";`

The errors are most likely arising because I am trying to import the font stylesheet in a `fonts.scss` file and specify this as a theme file in `_quarto.yml`. I'm doing this so I can keep all import statements for multiple font stylesheets in one place. 

Previewing yields the following errors:
```
GET: /
  /site_libs/bootstrap/fonts/Fira-Code/fira_code.css (404: Not Found)
GET: /site_libs/bootstrap/No (404: Not Found)
```

I'd appreciate any help in understanding how the paths work. Thanks!

**Comment by mcanouil** [comment]
Related previous discussions:

- https://github.com/quarto-dev/quarto-cli/discussions/8036
- https://github.com/quarto-dev/quarto-cli/discussions/1769

**Comment by chiragraman** [comment]
Thanks @mcanouil! I did find #8036 but the suggested solution of adding the files as a site resource was already covered by the suggestion in #4387 so I didn't tag it as well. I've been tinkering with the paths in the import in the minimal example but no dice.

I suspect I don't fully understand where the resources are copied to, it seems it's looking for the files under `_site/site_libs/bootstrap/` while the resources seem to be placed under `_site/assets/fonts` which is actually empty.

**Reply by mcanouil** [reply, marked as answer]
See <https://github.com/Klesel/QuartoIssueGoogleFonts/pull/1> for the correction of #4387.

You did not follow Carlos structure. Adding `/*-- scss:rules --*/` inside four `Fira_Code.css` is not a hack you can use.
`/*-- scss:rules --*/` is for the SCCS file.

Your SCCS file should look like:
````css
/*-- scss:defaults --*/

$font-family-sans-serif:     "Fira Code", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
$font-family-monospace:      "Fira Code", SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
$web-font-path:              "No";

/*-- scss:rules --*/
@font-face{
  font-family: 'Fira Code';
  src: url('./assets/fonts/Fira-Code/eot/FiraCode-Light.eot');
  src: url('./assets/fonts/Fira-Code/eot/FiraCode-Light.eot') format('embedded-opentype'),
       url('./assets/fonts/Fira-Code/woff2/FiraCode-Light.woff2') format('woff2'),
       url('./assets/fonts/Fira-Code/woff/FiraCode-Light.woff') format('woff'),
       url('./assets/fonts/Fira-Code/ttf/FiraCode-Light.ttf') format('truetype');
  font-weight: 300;
  font-style: normal;
}

@font-face{
  font-family: 'Fira Code';
  src: url('./assets/fonts/Fira-Code/eot/FiraCode-Regular.eot');
  src: url('./assets/fonts/Fira-Code/eot/FiraCode-Regular.eot') format('embedded-opentype'),
       url('./assets/fonts/Fira-Code/woff2/FiraCode-Regular.woff2') format('woff2'),
       url('./assets/fonts/Fira-Code/woff/FiraCode-Regular.woff') format('woff'),
       url('./assets/fonts/Fira-Code/ttf/FiraCode-Regular.ttf') format('truetype');
  font-weight: 400;
  font-style: normal;
}

@font-face{
  font-family: 'Fira Code';
  src: url('./assets/fonts/Fira-Code/eot/FiraCode-Medium.eot');
  src: url('./assets/fonts/Fira-Code/eot/FiraCode-Medium.eot') format('embedded-opentype'),
       url('./assets/fonts/Fira-Code/woff2/FiraCode-Medium.woff2') format('woff2'),
       url('./assets/fonts/Fira-Code/woff/FiraCode-Medium.woff') format('woff'),
       url('./assets/fonts/Fira-Code/ttf/FiraCode-Medium.ttf') format('truetype');
  font-weight: 500;
  font-style: normal;
}

@font-face{
  font-family: 'Fira Code';
  src: url('./assets/fonts/Fira-Code/eot/FiraCode-Bold.eot');
  src: url('./assets/fonts/Fira-Code/eot/FiraCode-Bold.eot') format('embedded-opentype'),
       url('./assets/fonts/Fira-Code/woff2/FiraCode-Bold.woff2') format('woff2'),
       url('./assets/fonts/Fira-Code/woff/FiraCode-Bold.woff') format('woff'),
       url('./assets/fonts/Fira-Code/ttf/FiraCode-Bold.ttf') format('truetype');
  font-weight: 700;
  font-style: normal;
}
````
