### DISCUSSION TITLE
Show slide boundaries for presentations

### DISCUSSION THREAD

**Discussion by skwde** [quarto-dev/quarto-cli#9520] [Q&A]
### Description

I would like see slide boundaries + margin in preview (revealjs presentation), but cannot find an option to view that.
This is useful to easily detect when there is to much stuff on a slide (or if a bullet point or new line still fits onto the existing slide).

I am looking for something similar to the LaTeX package `layout` or the `geometry` option `showframe`.

How to draw a line for slide boundaries? In addition showing the margin can be quite helpful.

**Comment by mcanouil** [comment]
Reveal.js is HTML thus you can use (S)CSS to target the slide section and add a border rule.
You can use your favourite browser inspect/developer mode to see precisely what to target.

Not tested:

```css
.reveal .slide {
  outline: thick double #B22222;
}

/* or */

.reveal .slide {
  border: thick double #B22222;
}
```

Note that since it is HTML and elements are resized, you still need to preview your slides on a sufficient screen display size to display the slides at the right size, see <https://quarto.org/docs/presentations/revealjs/advanced.html#presentation-size>.

**Reply by skwde** [reply]
Thanks for your immediate response!

I tested the first both and they seem to work.

The fact with resizing is exactly the point why I asked for it in the first place.

It would be nice if one could e.g. specify a `debug.css` on the command line of `quarto preview`, e.g. via `--debug-css debug.css` instead of adding it to the frontmatter in the `.qmd` as

````qmd
---
<...>
css: debug.css
---
````

or maybe even have a `--debug` option which automatically uses some sensible defaults.

**Reply by mcanouil** [reply]
Create a Project Profile with whatever settings you feel will help you "debug", see <https://quarto.org/docs/projects/profiles.html>.

Or use the metadata flag to add the CSS file.

**Reply by skwde** [reply]
Profiles look like exactly what I am looking for.

I have following directory layout

```sh
_quarto-debug.yml
debug.css
_test
  - talk.qmd
  - _quarto.yml
```

with `_test/talk.qmd`

````qmd
---
title: "Quarto talk"
---

# test slide

## aabc

adfadsf
````

and `_quarto.yml`

```yml
date: last-modified
date-format: long
author:
  - name: skw
format:
  revealjs:
    # ## use aspectratio 1610
    width: 1280 # default: 970
    height: 800 # default: 700
    auto-stretch: false
    navigation-mode: vertical
    controls: true
    progress: true
    slide-number: h.v
    toc: true
    toc-depth: 1
```

then I have

`_quarto-debug.yml` with content

```yml
css: debug.css
```

and the `debug.css` with

```css
.reveal .slide {
    outline: thick double #B22222;
}
```

Now I run

```sh
quarto preview _test/talk.qmd --no-browser --port 8030 --profile debug
```

but it does not show that the `css: debug.css` is added to the `pandoc` option after running the preview command.
It works only when moving `_quarto-debug.yml` and the `debug.css` into the `_test` folder.

What do you mean by metadata flag?
