### DISCUSSION TITLE
Multiple source URLs with code-tools

### DISCUSSION THREAD

**Discussion by grantmcdermott** [quarto-dev/quarto-cli#9529] [Q&A] [answered]
### Description

Apologies if I missed it---my search didn't turn anything up---but is it possible to include multiple `source` locations in the `code-fold` YAML entry?

My immediate use-case relates to the fact that I have a Quarto HTML document with both R and Python code chunks. I'd like to link to pure script versions of both languages, so that my users can easily test the languages separately. Something like the following (which doesn't work):

```yaml
code-tools:
  - caption: "R code"
    source: https://myurl.com/code.R
  - caption: "Python code"
    source: https://myurl.com/code.py
```

I can imagine similar use cases for linking to, say, both the `.qmd` and pure `.R` files in the same document.

Thanks in advance.
