### DISCUSSION TITLE
How to change the font colour on the slide with background image in quarto pptx?

### DISCUSSION THREAD

**Discussion by udurraniAtPresage** [quarto-dev/quarto-cli#9564] [Q&A] [answered]
### Description

I have blue and black colours for my slide title and body fonts. How do I change these colours for only that slide where I have a background image?

The qmd includes:

```
---
title: "Title"
subtitle: "subtitle."
format:
  pptx:
    reference-doc: template.pptx
    incremental: true   
---

## Slide with background image {background-image="william-hook-Wtn654UyGYA-unsplash.jpg"}

I am a [red]{style="color:green;"} word.
```
This produces the following result:

![image](https://github.com/quarto-dev/quarto-cli/assets/142413619/3ac5222e-57fe-4670-896e-6c661ff74bac)
