### DISCUSSION TITLE
How to temporarily override two column layout of KOMA class?

### DISCUSSION THREAD

**Discussion by jan-abel-inwt** [quarto-dev/quarto-cli#9590] [Q&A] [answered]
### Description

Hello,

I am currently working on developing a Quarto PDF extension/template that incorporates a global two-column layout.

For this purpose, I am utilizing `scrreprt` as the `documentclass` and `twocolumn` as the `classoption`.

Could you advise if there is an elegant method to temporarily bypass the two-column layout for larger content, such as images or extensive tables? I am looking for a solution that would allow these elements to be displayed more effectively within the layout.

---

Here is a minimal example:

the `_extension.yaml`

```yaml
title: Twocolumn-test
version: 1.0.0
quarto-required: ">=1.4.0"
contributes:
  formats:
    pdf:
      documentclass: scrreprt
      classoption: twocolumn
      fig-pos: H
      fontsize: 10pt
```

and the some text using the `_extension` file:

```markdown
---
title: Untitled
format:
  twocolumn-test-pdf: default
date: last-modified
---

# Est hinc simul vinclo in voluit

## Tuorum refugis ille Mulciber Prochytenque deorum

Lorem markdownum probat adsueto nostri. Et animal limine ius maiora tempore
temporis turpes adsternunturque induruit: respicit vestra victricemque surgit
erepta; est cursu cui. Danda tot inter submersum, lumbis de plagis coniunx
coronant languore Acrota.

> Semel iustius ne careat locus? Pressit leto, infractaque forsitan Procne
> Emathion concava perlucentibus; ad, paucis ille misit his at, sinistrae?
> Sepulcris ab molire quamvis: contulit Cadmi: aut Bacchus tandem regis; iste
> quo *litore*, est.

Declinat regem in dies virginis, at, at intra! Confessis quae in gaude per
terrae spargit aquis similem antiquas corpora, sub *in regionis rictus*
designat, arbore cum. Fatigat possit sitim unda putat te **acto me** cetera
videnda per.

## Coronas contrarius ostendit fugit qui praemia rogat

Diu deus ad quoque novat et intumuit profecto, [dolorem hoc
movere](http://aerias.io/alis-poscitur) vestes dabat, una. Magis *quod
paulatim*, prospicio est in aversum femur propiore et. Leves vulnus **non non
qua** do Teucri clamato currus haesit inpune et nostro circumspexit sumit et
derepta. Narret turres posset pugnabant, qua ac pulsarunt factis salutifer.

1. Currere urbes quam pavens Troezen molliri
2. Qui animoque stirpi palmis
3. Fuerant aquarum esse
4. Linigera ostendere nusquam
5. Caput rigidum
6. Undis collegit vindice Tirynthius fortibus vultusque Dianae

**Non** mihi vinco! Sub cum, in redemit delectat rerum matres paratior. Caperet
eripiunt, moderator sonantem sonarent; quisque et aurea senilibus undae ait.

Res pactique parentis fuit respicit quodque munera rudem posce in formidabile
quodque flores quoque. Viribus oris cornua secuti putas, videri, dedit vel
viderat precantum manus Cenchreis porta et.

## Caeli pollicita vultu

Lorem markdownum, et citharaque dotem; exorabilis nec insidias serpens linguaque
miserata? Quae palmae, qua vultus servitura centum; et est: velant fovesque
spiritus genus raptor. Effusus ut inter coronant erat praebuit adacto aliquid,
atque iussi alta quam, unum illo edita nec altae, duorum.

Neque gregibus medium distinguunt labi, hoc umquam signa *percepit calcitrat*,
relictum. Movebatur quae ipsaque, inmotas, huc [necetur
fugiebat](http://tristisque.net/harena-corpora) suisque et capellae. Moventem
obprobrium ferarum, aris hic hiatus, vultumque, nec quove deprensa, habebat
argenteus plebe licet cognoscere.

## Femina voluit aliquid factaque ad digessit

Sumit sit erat falsi dignas perosa simulac servatrix ille crepuscula fixum
spectacula. Exigit populusque tenent harpen Cerealia pudor, nec si postquam alta
incunabula, procul, lignoque? Arce potes pressant, ipsa cum; terram et oculos
nisi. Ait mox praebuerat Silvius Cithaeron *virgo* Dulichiae o sertis pampineae.

Dextro idem [Illyricos](http://pan-in.io/ver) videtur, corona Tyriis quaeque
Polyxena tibi duplicataque arsit. Iphis rerum invitum illo. Prior similis dixit
omnia spectabat, vatemque temptare corpore, Finierat, quam hoc.

Dissimiles caeca dixerat oculi omnes tangat furens vulnere sceptro acceptior
latus. Saniemque hoc cornua, conplexu quid vimque armis. Sum natis, voluptas
utque fecundior revelli honore unda, scire; tibi obscura gelidos respicio nostra
at quam! Est praeterque velante vulnus ferrugine non gemina mille capillos
placidissime primum.

```

Thanks for your help!

**Comment by mcanouil** [comment, marked as answer]
That's a LaTeX question.
The answer can easily be found on the internet, *i.e.*, use `\onecolumn` and `twocolumn`.

````qmd
---
title: Untitled
format:
  pdf:
    documentclass: scrreprt
    classoption: twocolumn
date: last-modified
---

# Est hinc simul vinclo in voluit

## Tuorum refugis ille Mulciber Prochytenque deorum

{{< lipsum 3 >}}

`\onecolumn`{=latex}

## Caeli pollicita vultu

{{< lipsum 2 >}}

`\twocolumn`{=latex}

## Femina voluit aliquid factaque ad digessit

{{< lipsum 2 >}}
````

<img width="716" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/088ac30f-ddbd-4eff-a9bf-ff46cc24327b">

**Reply by mcanouil** [reply]
Also:

- https://github.com/quarto-dev/quarto-cli/discussions/4399

All these are pure LaTeX.
It's best to look for those on the internet in places more dedicated to this language.

**Reply by dmnkf** [reply]
Hey @mcanouil 

Having a similar problem and while this solves the multi classoption situation it introduces a new mistake for rendering using a quarto book layout. 

using `\onecolumn`{=latex} puts the section content on a new page of the section title

<img width="543" alt="Screenshot 2024-08-11 at 15 06 37" src="https://github.com/user-attachments/assets/e07757b5-37b5-48e7-8f5e-58ee3ebb8662">

Here the corresponding code. 

```
`\twocolumn`{=latex}

# LO1: Visualization Basics and Chart Types
```

Also tried to use a yaml title instead of markdown and put the command after and before the title, unfortunately without any success.

Here is my _quarto.yml:

```
project:
  type: book

book:
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - sections/lo1.qmd
    - sections/lo2.qmd
    - sections/lo3.qmd
    - sections/lo4.qmd
    - sections/lo5.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    echo: false
  pdf:
    documentclass: scrreprt
    # classoption: twocolumn
    fontsize: 8pt
    echo: false
    latex-auto-install: true
    include-in-header: 
      text: |
        \usepackage{multicol}
    plotly-connected: true
```
I assume it has something to do with how Quarto prepares the document in render, but is there a solution to this? 

Didn't find anything online that worked.
