### DISCUSSION TITLE
The text of `<li class="fragment">` temporarily loses its CSS style (in revealjs)

### DISCUSSION THREAD

**Discussion by ChoCho66** [quarto-dev/quarto-cli#9643] [Q&A] [answered]
### Description

As title, in revealjs, when `<li class="fragment">`(previous level) becomes `<li class="fragment visible current-fragment">`, the text of `<li class="fragment">` temporarily loses its CSS style.

Below is a video of this situation.

https://github.com/quarto-dev/quarto-cli/assets/72805700/514667ec-b5ec-460f-873c-d36b71e7182a

A small sample of `qmd` is
```qmd
---
title: "Test"
format: 
  revealjs:
    theme: [default, styles.scss]
incremental: true
---

## Test

- A  
  - B 
  - $\color{red}{B}$
  - B 
    - B 
  - B 
```

and my `styles.scss` file is
```scss
/*-- scss:defaults --*/

/*-- scss:rules --*/

.fragment {
  opacity: 1 !important;
  visibility: visible !important;
  filter: brightness(0.01)  invert(0.8) !important;
  &.visible {
    filter: none !important;
  }
}
```

In revealjs(https://revealjs.com/fragments/#custom-fragments-4.5.0), this can be easily achieved by the following html without this situation.

```html
<style>
  .fragment.blur {
    filter: invert(75%);
  }
  .fragment.blur.visible {
    filter: none;
}
</style>
<section>
  <p class="fragment custom blur">One</p>
  <p class="fragment custom blur">Two</p>
  <p class="fragment custom blur">Three</p>
</section>
```

Is there any good way to solve it?
I checked the related issue here (https://github.com/quarto-dev/quarto-cli/discussions/4794) but I still can't solve the problem

---

My quarto version is 1.4.554 and my system is macOS 14.4.1 (23E224).
