### DISCUSSION TITLE
How to call for -it.thanks-

### DISCUSSION THREAD

**Discussion by friosavila** [quarto-dev/quarto-cli#9653] [Q&A]
### Description

Hi,
Im trying to access into the "thanks" within Authors Attribute to create a template.
I tried few things, but neither seems to be working.
This is my Authors Set up in YAML

```
authors:
  - name: "Author1"
    thanks: Thanks1
    affiliations:
      - name: "Affiliation1"
        city: "City1"
  - name: "Author2"
    thanks: "Thanks2"
    affiliations:
      - name: "Affiliation2"
        city: "City2"
```

And Im trying to use that in my template with the following code:

```
\author{$for(authors)$$it.name.literal$\thanks{$it.thanks$}$sep$ \and $endfor$}
```

However, Every time I run the code, nothing comes out in the rendered PDF, nor the underlying TEX file.
Any suggestions how to work this around?

**I found the answer myself. There is no "thanks" attribute on author, and there is no way to create such field. Instead one should use acknowledgement.**
