### DISCUSSION TITLE
Select default style of variable font family

### DISCUSSION THREAD

**Discussion by grantmcdermott** [quarto-dev/quarto-cli#9716] [Q&A] [answered]
### Description

Hi folks,

Hopefully this isn't a duplicate, but is there a way to select the default style (e.g. "light" instead of "regular") for [variable font](https://www.sitepoint.com/variable-fonts-introduction/) families? I'm specifically interested in a solution for the Typst engine, but hopefully the answer would apply more generally. Perhaps a `font-style` flag to go along with `font-path` and co.?

P.S. My rather hackish workaround at the moment is to download the font family of interest (i.e.,including all styles), but then only copy across the subset of selected styles to my system font book.

**Comment by mcanouil** [comment, marked as answer]
Did you look at Typst documentation? https://typst.app/docs/

Then you'll likely need to tweak the partials: https://quarto.org/docs/output-formats/typst-custom.html#advanced-customization

For other formats, the approach is the same and require to know the language used as there is no direct YAML option for this in Pandoc and Quarto.

**Comment by grantmcdermott** [comment]
Thanks @mcanouil. Looks like this lacks upstream support in Typst at the moment, regardless of custom partials. https://github.com/typst/typst/issues/185

I'll stick with my workaround for the moment and hopefully revisit once Typst gets better native support for variable fonts.

**Comment by grantmcdermott** [comment]
**UPDATE:** For most variable fonts, I've found that setting the weight "manually" as part of `include-before-body` in the YAML works pretty well.

For example, here using the Amazon Ember fonts ([zip link](https://m.media-amazon.com/images/G/01/mobile-apps/dex/alexa/branding/Amazon_Typefaces_Complete_Font_Set_Mar2020.zip)):

```yaml
format:
  typst:
    mainfont: "Amazon Ember Cd RC"
    include-before-body:
      - text: |
          #set text(font: "Amazon Ember Cd RC", weight: "light")
```

... unfortunately, this doesn't pertain to any pre-body elements like the abstract. So these elements will still be in the regular font, rather than the variable option that you specified as part of your yaml (here: "light" weight).

**Reply by mcanouil** [reply]
Did you try adding this in the header?
Or setting this in a partial?

**Reply by gordonwoodhull** [reply]
Currently as of Quarto 1.5 and Pandoc 3.2, the Pandoc Typst template puts "headers" at the top of the body, after the show rule that displays the title and abstract. So our Quarto Typst template does this too.

I have opened an issue and hope to get this changed in Pandoc, after which we can make the change in Quarto 1.6: 
https://github.com/jgm/pandoc/issues/9996

For now you could add your `#set text(...)` line to the top of the `typst-show.typ` partial to get the same effect.
https://quarto.org/docs/journals/templates.html#typst-partials

___Or___  copy `template.typ` from here:
https://github.com/quarto-dev/quarto-cli/blob/cd3c8e69b8b3fd97d1960e9c704ea63e9a751da5/src/resources/formats/typst/pandoc/quarto/template.typ

and use `include-in-header` and `template` like so:
```yaml
format:
  typst:
    template: template.typ
    mainfont: "Amazon Ember Cd RC"
    include-in-header:
      - text: |
          #set text(font: "Amazon Ember Cd RC", weight: "light")
```
