### DISCUSSION TITLE
Publishing Quarto Website on Gitlab pages

### DISCUSSION THREAD

**Discussion by anaelDelorme** [quarto-dev/quarto-cli#973] [Q&A]
I would like to publish a quarto site on gitlab pages. I found the doc for github (which works very well, thanks) but not for Gitlab. 
Is it possible to do it ? Do you have recommendations or a guide?
Thank you.

**Comment by cderv** [comment]
I don't think we have yet a template for Quarto project rendered on Gitlab CI to use gitlab pages. This is definitely something we can add to our documentation.

However, yes it is definitely possible to do it and maybe there is already example around the web. 

I see two ways: 
- Use quarto to render locally your website and commit the outputs. Then use Gitlab CI with Gitlab pages to only deploy the content of the output directory. Only requirement I believe is for the output directory to be called `public` for Gitlab pages to work. 
- Use Gitlab CI to build your website using Quarto and then deploy. Same requirement on the output folder name, but you'll also need to setup Gitlab CI with any computation environment required. Example: for R user, using gitlab ci with docker images for rocker project seems the easiest like this image https://hub.docker.com/r/rocker/verse.

I'll try to add one demo repository soon.

If you already try something, please share and I'll probably be able to help.

**Comment by sbalci** [comment]
I use gitlab pages with quarto over github actions.

in `_quarto.yml` add

```
  output-dir: public
```

consider adding resources as well:


```
project:
  type: website
  resources:
    - "css/"
    - "js/"
    - "*.html"`
```





add a file named `.gitlab-ci.yml` to main repo

```
# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - echo "start"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 ``` 

if you want to use github and mirror to gitlab use this action

```
  quarto-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
      - name: Render website
        run: |
          quarto render


  build-togitlab:
    needs: quarto-build-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/ name / repo"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: ""
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} # // Generate here: https://gitlab.com/profile/personal_access_tokens
        GITLAB_PROJECT_ID: "" # // https://gitlab.com/<namespace>/<repository>/edit
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # // https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
```
