### DISCUSSION TITLE
Unnecessary page break

### DISCUSSION THREAD

**Discussion by ambarja** [quarto-dev/quarto-cli#9747] [Q&A] [answered]
### Description

Hi recently I have been using quarto to be able to write some academic papers, however in the university they ask me for some features such as:

Chapter I
1. INTRODUCTION
1.1 Introduction
1.2 Problem statement
1.3 Objectives of the problem
1.4 Importance and Scope of the Research
1.5 Limitations of the research

So the index quarto I am using is as follows:

```yml
---
title: |
  \textbf{\fontsize{12pt}{24pt}\selectfont{\textbf{UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS}}} \
  \vspace{5pt}
  \textbf{Universidad del Perú, Decana de América}\
  \vspace{5pt}
  \textbf{FACULTAD DE INGENIERÍA GEOLÓGICA, MINERA, METALÚRGICA Y GEOGRÁFICA}\
  \vspace{5pt}
  Escuela Profesional de Ingeniería Geográfica
author: \authorinfo
titlepage: formal
titlepage-logo: "logo/unmsm.png"
titlepage-theme:
    elements: ["\\titleblock", "\\logoblock", "\\titulo", "\\modelo", "\\descrip", "\\grado", "\\presentado", "\\asesor", "\\authorinfo", "\\region", "\\footerblock"]
    page-align: "center"
    title-style: "plain"
    title-fontstyle: ["normalsize"]
    title-space-after: "1.0cm"
    title-subtitle-space-between: "0.5cm"
    author-style: "plain"
    author-sep: "newline"
    author-fontstyle: "textbf"
    author-space-after: "2\\baselineskip"
    affiliation-style: "numbered-list-with-correspondence"
    affiliation-fontstyle: "large"
    affiliation-space-after: "0pt"
    footer-style: "plain"
    footer-fontstyle: ["Large", "textsc"]
    footer-space-after: "0pt"
    logo-size: "0.35\\textwidth"
    logo-space-after: "1cm"
toc: true
toc-title: "\\setmainfont{Times New Roman} Índice general"
toc-spacing: "1.5pt"
toc-depth: 3
number-offset: 3
lang: es
mainfont: "Times New Roman"
sansfont: "Times New Roman"
font-weight: 400
preamble: | 
  - \titleformat{\section}{\Large\bfseries\fontfamily{ptm}\selectfont}{\thesection}{1em}{}
  - \titleformat{\subsection}{\large\bfseries\fontfamily{ptm}\selectfont}{\thesubsection}{1em}{}
  - \newcommand{\titulo}{\vspace{0.5cm}\centering{\Large\textbf{\fontsize{14}{24}\selectfont{TITULO}}}\par\vspace{1.5cm}\vspace{1.8cm}}
  - \newcommand{\modelo}{\vspace{0.5cm}\centering{\Large\textbf{\fontsize{14}{24}\selectfont{TRABAJO DE INVESTIGACIÓN}}}\par\vspace{0cm}}
  - \newcommand{\descrip}{\vspace{0.5cm}\centering{\Large\fontsize{12}{24}\selectfont{Para optar el grado de Bachiller en Ingeniería Geográfica}}\par\vspace{0.5cm}\vspace{0.8cm}}
  - \newcommand{\grado}{\vspace{0.5cm}\centering{\Large\textbf{\fontsize{12}{24}\selectfont{AUTOR}}}\par\vspace{0.5cm}\vspace{0.8cm}}
  - \newcommand{\presentado}{\vspace{0.2cm}\centering{\Large\fontsize{12}{24}\selectfont{Antony Marcos BARJA INGARUCA }}\par\vspace{1.5cm}\vspace{1.8cm}}
  - \newcommand{\asesor}{\vspace{1cm}\centering{\Large\textbf{\fontsize{12}{24}\selectfont{ASESOR}}}\par\vspace{0.5cm}\vspace{0.2cm}}
  - \newcommand{\authorinfo}{\vspace{0.2cm}\centering{\Large\fontsize{12}{24}\selectfont{Francisco Alejandro ALCANTARA ROJAS}}\par\vspace{0.5cm}}
  - \newcommand{\region}{\vspace{4cm}\centering{\Large\fontsize{12}{24}\selectfont{Lima, mayo del 2024}}\par\vspace{0.5cm}\vspace{0.2cm}}
format: 
  titlepage-pdf:
    coverpage: false
    papersize: A4
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    number-sections: true
    fontsize: 12pt
    spacing: onehalf
    geometry: 
      - top=3.0cm
      - bottom=2.5cm
      - left=3.0cm
      - right=2.5cm
    extension-limit: 20
    output-file: 'plan_tesis_2024' 
---

# CAPÍTULO I {.unnumbered}
{{< include capitulo_01.qmd >}}

# CAPÍTULO II {.unnumbered}
{{< include capitulo_02.qmd >}}

# CAPÍTULO III {.unnumbered}
{{< include capitulo_03.qmd >}}

# CAPÍTULO VI {.unnumbered}
{{< include capitulo_04.qmd >}}

# CAPÍTULO V {.unnumbered}
{{< include capitulo_05.qmd >}}
```
Note that I am using an extension called [nmfs-opensci-titlepages](https://nmfs-opensci.github.io/quarto_titlepages)
Now my file capitulo01.qmd  is configured as follows

```qmd
# INTRODUCCIÓN 
## Introducción
### Planteamiento del problema
### Descripción de la problemática
### Formulación del problema
## Objetivos de la investigación
## Importancia y alcance de la investigación
```
![image](https://github.com/quarto-dev/quarto-cli/assets/23284899/1c2745e0-0b49-4e95-85b9-f731c9ef996a)
Does anyone know how I can correct this structure? 🙏  😢 
The version of quarto is 👇 
![image](https://github.com/quarto-dev/quarto-cli/assets/23284899/e73da422-3e0d-4c1f-b0d6-8107688a2e06)
