### DISCUSSION TITLE
Shiny dashboard... get rid of mysterious empty panel? (Quarto + Python + Shiny + Jupyter)

### DISCUSSION THREAD

**Discussion by mmchugh87** [quarto-dev/quarto-cli#9758] [Q&A] [answered]
### Description

Hi there.

I'm on a windows machine.
Python 3.
Recent version of Shiny.
quarto-1.4.554-win.
I have installed the Jupyter-Quarto extension via jupyterlab extension manager.

I'm trying to develop my skills at building Shiny dashboards.

Here is a notebook:

**CELL 1 (Markdown)**
````
---
title: "Football"
author: "Rashford"
date: "March 22nd, 1887"
format: 
  dashboard:
    theme: united
server: shiny
jupyter: python3
execute: 
  enabled: true
  echo: false
---
````

**CELL 2 (Markdown)**
````
Page 1
````

**CELL 3 (Markdown)**
````
Page 3
````

**CELL 4 (Code)**
````
import seaborn as sns
from shiny import render, reactive, ui
penguins = sns.load_dataset("penguins")

@render.plot
def depth():
    return sns.displot(
        filtered_penguins(), x = "bill_depth_mm", 
        hue = "species", kind = input.dist(), 
        fill = True, rug=input.rug()
    )
````

See the following picture for how this is rendered in Chrome when I run "quarto preview".

![quarto_panel](https://github.com/quarto-dev/quarto-cli/assets/66922291/9b36524b-ec2a-47e1-8872-c8e3664b676f)

Based on my experiments, I can see that any time I insert a new "Page" (even if I provide it with no content, no plots etc), it will always have an empty "panel" there. And then, when I do actually add some content to the page, that content is inserted below the empty panel. The empty panel is a problem.
