### DISCUSSION TITLE
The hierarchy of the menu items on the left side of the Reference page is not obvious

### DISCUSSION THREAD

**Discussion by chuxinyuan** [quarto-dev/quarto-cli#9777] [Feature Requests]
![202405251400](https://github.com/quarto-dev/quarto-web/assets/26940042/e9080267-eea2-44e8-a05d-fccfc138d724)

Two empty characters might be better. It may also be the cause of looking at the R code at ordinary times.

**Comment by jimjam-slam** [comment]
A border might help:

```css
.sidebar-menu-container .sidebar-section {
  border-left: 1px solid lightgrey;
}
```

![image](https://github.com/quarto-dev/quarto-cli/assets/6520659/304f5f02-6507-41ee-afc4-9816d0fb204b)
