### DISCUSSION TITLE
Issue with Sidebar Sorting in Quarto Blog

### DISCUSSION THREAD

**Discussion by BrotherJiang** [quarto-dev/quarto-cli#9782] [Q&A]
### Description

Hi,

I'm using Quarto to create my blog and I'm encountering an issue with sorting the contents in the sidebar. In my index.qmd file, I use the listing feature to sort the contents in the posts folder by date in descending order, which works perfectly. However, when I try to apply the same sorting logic in the _quarto.yml file for the sidebar, the sidebar fails to show up. If I use contents: "posts/AI-news/*.qmd" in the _quarto.yml file, the sidebar appears, but the file order is incorrect. As a workaround, I have been naming each file sequentially (e.g., 01post1.qmd, 02post2.qmd, where 02post2 is later than 01post1), but this is not ideal as it doesn't allow for sorting by date.

Here is a small reproducible example of my setup:

_quarto.yml:
```
project:
  type: website

website:
  navbar:
    background: primary
    foreground: light
    pinned: true
    search: true
    left:
      - text: "homepage"
        href: index.qmd
      - text: "about"
        href: about.qmd
      - sidebar: ai

  sidebar:
    - id: ai
      title: "AI news"
      style: "docked"
      background: light
      collapse-level: 2
      contents: "posts/AI-news/*.qmd"
```

index.qmd:
```
---
title: "Data Scientist"
listing: 
  - id: ai-news
    contents: "posts/AI-news/*.qmd"
    type: table
    sort: date desc
    fields: [date, title]
page-layout: full
title-block-banner: true
---

## AI news

:::{#ai-news}
:::
```

And the folder structure:
```
posts/AI-news/
  ├── index.qmd
  ├── 01post1.qmd
  ├── 02post2.qmd
```

Attached is an image showing the current issue. The file 02post2 (titled "Introduction to Linear Regression2") is later than 01post1 (titled "Introduction to Linear Regression1"), and I want 02post2 to be shown first.  If I change it to:
```
sidebar:
  - id: ai
    title: "AI news"
    contents: 
      - listing:
          contents: "posts/AI-news/*.qmd"
          type: items
          sort: date desc
```
Then the sidebar disappears.

Could you please advise on how I can modify the _quarto.yml file to enable the sidebar to display the files sorted by date in descending order, similar to how it works on the homepage table using sort: date desc?

Thank you for your assistance.
![blog](https://github.com/quarto-dev/quarto-cli/assets/47761076/8d6720bb-d0eb-4f24-b7af-df0fa4ee2e44)

**Comment by haxfn** [comment]
Its 2025.

Try adding this to your _quarto.yml:

```yml
project:
  # ...
  render:
    - "*.qmd"
```
