### DISCUSSION TITLE
How to generate intermediate LaTeX when converting qmd to pdf?

### DISCUSSION THREAD

**Discussion by dpo** [quarto-dev/quarto-cli#9787] [Q&A] [answered]
### Description

I have the preamble

```yaml
---
title: "My Title"
author:
  - name: Me
format:
  pdf:
    documentclass: scrartcl
---
```

When converting my `qmd` document to PDF, I would like to inspect the intermediate LaTeX (including the template). The only command I found to convert from `qmd` to `tex` uses the pandoc executable bundled with Quarto:
```bash
quarto pandoc -o mydoc.tex --standalone mydoc.qmd
```
However, Pandoc says
```
[WARNING] Could not deduce format from file extension .qmd
  Defaulting to markdown
```
and the preamble of the LaTeX file uses the `article` document class, not `scrartcl`.

What's the correct incantation?
