### DISCUSSION TITLE
fig-pos for custom cross-reference types

### DISCUSSION THREAD

**Discussion by mdrnao** [quarto-dev/quarto-cli#9806] [Q&A] [answered]
### Description

I'm struggling to understand how to make custom cross reference floats stay in the specified place. 

For figure types, I know I can do: 

````
---
title: Float Specifier
format:
  pdf:
    fig-pos: H
---
````

Or:

`![A placeholder image](https://placehold.co/600x400.png){fig-pos='H'}`

However, with a custom one defined in the yaml header:
````
crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
````
Neither of these in the .tex file added the `[H]` to `\begin{suppfig}` as we see for the figure type `\begin{figure}[H]`

Any pointers in the right direction would be appreciated! 

## Basic repo:

````qmd
---
title: Float Specifier
format:
  pdf:
    fig-pos: H
    keep-tex: true
crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
editor: source
---

![A placeholder image](https://placehold.co/600x400.png){#fig-1 fig-pos="H"}

![A placeholder image](https://placehold.co/600x400.png){#suppfig-1 key="suppfig" fig-pos="H"}

````

## basic info
Quarto version: 1.4.554
OS: Linux Ubuntu
