### DISCUSSION TITLE
In a book, how do I remove the sidebar & scale the visualisations?

### DISCUSSION THREAD

**Discussion by shellandbull** [quarto-dev/quarto-cli#9837] [Q&A]
### Description

Hello peeps!

You can find the [quarto code for my issue here](https://github.com/shellandbull/higher-risk-higher-rewards/tree/main/docs) and the [output here](https://shellandbull.github.io/higher-risk-higher-rewards/)

I'd like to remove the navbar on the left hand side and make the visualisations scale to the width of its container so the user doesn't have to deal with overflowing issues by scrolling

my `_quarto.yml` looks like this currently:

```
format:
  html: {toc: true, toc-depth: 4, theme: cosmo}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  title: "On higher risks yielding higher rewards"
  chapters: [index.qmd]
  page-navigation: false
website:
  navbar: false
  page-navigation: true
```

And here's a few images for reference

![Screenshot 2024-06-01 at 7 48 54 AM](https://github.com/quarto-dev/quarto-cli/assets/3522106/5139c1db-cf3f-4f8c-beb8-90230b2d21a3)

![Screenshot 2024-06-01 at 7 49 06 AM](https://github.com/quarto-dev/quarto-cli/assets/3522106/4dbfd6ea-5b3b-4161-9e3c-6a46fa785b34)

**Comment by mcanouil** [comment]
Why do you have book and website configuration in your `_quarto.yml`?

Books uses the sidebar (left) as default and as far as I know as the only possible navigation. That's the book project design.
Website uses the navbar (top) as default, but you can use hybrid navigation or using only sidebar.

You cannot disable something that is not there in the first place.
You cannot use `website` for Book project or `book` for Website project, or more accurately they are completely ignored as they have no meaning in the wrong context.

Regarding your question about layout:
- https://quarto.org/docs/authoring/article-layout.html
- https://quarto.org/docs/output-formats/page-layout.html

**Comment by shellandbull** [comment]
@mcanouil 

I switched to use this `_quarto.yml` and I still have the same layout

```yaml
format:
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
  html:
    toc: true
    toc-depth: 4
    theme: "cosmo"
    page-layout: article
project:
  type: book
book:
  chapters: [index.qmd]
  author: "Mario Gintili - @shellandbull on Github"
  page-navigation: false
  navbar: false
  sidebar: false
```

https://shellandbull.github.io/higher-risk-higher-rewards/
