### DISCUSSION TITLE
Remove author from listing page

### DISCUSSION THREAD

**Discussion by werkstattcodes** [quarto-dev/quarto-cli#9957] [Q&A] [answered]
### Description

For some reason, I have suddenly the name of the author displayed on my listing page.  Any idea how to remove it? 
![author_listing_page](https://github.com/quarto-dev/quarto-cli/assets/9595585/118a729a-3f10-47c8-9655-3155e9fa1765)

Below the content of my index.qmd 

```
---
listing:
  type: grid
  grid-columns: 4
  grid-item-border: true
  contents: posts
  sort: "date desc"
  categories: false
  sort-ui: false
  filter-ui: false
  # fields: [image, date, title, description, categories]
  fields: [title, description, date, categories]
  feed:
    type: full
    title: "werk.statt.codes feed"
    categories: [r]
    description: "RSS feed to relevant posts"
    items: 2
  image-height: 150px
  page-size: 20
  image-align: right
  date-format: D MMM YYYY
  
page-layout: full
title-block-banner: false
---


```
