### DISCUSSION TITLE
EJS templates working with things other than an `items` array

### DISCUSSION THREAD

**Discussion by andrewpbray** [quarto-dev/quarto-cli#9985] [Q&A] [answered]
### Description

The documentation on[ listing templates](https://quarto.org/docs/websites/website-listings-custom.html#listing-templates) is clear that it can ingest a `contents.yml` file that consists of an array of items. That array is then accessible in the EJS template as `items`.

If `contents.yml` is not a flat array but has an array nested under a top-level key, is there any way to include that in the EJS template? In my reading of the docs, EJS itself has that capability, but it seems Quarto only makes an `items` object accessible and it must be an array.

An example of what I'd like to do for a `contents.yml` file:

```yaml
days:
  - gift: partridge in a pear tree
  - gift: turtle dove
```

With an ejs that would allow access to `"partridge in a pear tree"` via something like `days[0].gift`

Thanks!

**Comment by cderv** [comment, marked as answer]
Are you looking for what we call `template-params` (https://quarto.org/docs/websites/website-listings-custom.html#template-parameters) ? 

This would be 
````yaml
template-params:
  days:
    - gift: partridge in a pear tree
    - gift: turtle dove
````

That we pass to custom listings as `templateParams` 

it should allow you to do whatever you need with ejs.

**Reply by andrewpbray** [reply]
Hmm, that is very close to what I'm looking for, but not quite. Essentially I want to be store the `template-params` in an external file a la `contents`. I suppose I could use `_metadata.yml` as that external file 🤔 .

I can work with this - thanks!

**Reply by cderv** [reply]
Oh I see. Probably _metadata.yml could work, but I believe we could also support a file for `template-params`, same way we support for contents. something like 

````yaml
  contents:
    - items.yml
  template-params:
    - listing-meta.yml
````

would that be what you want ?
