### ISSUE TITLE
Allow shortcodes expansion in `icon` attribute/YAML/code cell option

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#10004]
For other Quarto components, you can use the `text: "{{< iconify octicon:issue-opened-16 >}} Opened Issues"` to get an icon from a shortcode in most places (instead of `icon: name`), but for value box, you can't do that as the icon gets a particular treatment for it to appear on the left of the content of the value box.

It would be nice to be able to use more icons than the limited set of Bootstrap in particular in value box in dashboard as there are no alternatives/workarounds:

````qmd
::: {.valuebox icon="{{< iconify octicon:log-24 >}}" color="blue"}
Articles per day

`{python} articles`
:::
````

The approach of allowing shortcode inside `icon` could also be expanded to all `icon` everywhere in Quarto.

**Comment by cderv** [comment]
Is shortcode allowed on Div syntax attributes in general ? Your issue is quite specific to dashboard and valuebox, but I think using shortcodes on Fenced Div attributes is not working in general. 

Shortcode replacement for this happens in AST processing, but our reader does not see initially a Div. 

Take this 
````markdown
---
title: test
keep-md: true
format: html
---

::: {.custom title="{{< meta title >}}"}
Content
:::
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/654b1306-f8ad-411e-a081-ef909e0077f4)


But using trace, the starting Doc is a Para first 
````
blocks:
  - t: "Para"
    content:
      - "::: {.custom title="
      - t: "Quoted"
        content:
          - "\""
          - t: "Span"
            attr: "('', ['quarto-shortcode__'], ['data-is-shortcode,1', 'data-raw,{{< meta title >}}'])"
            content:
              - t: "Span"
                attr: "('', ['quarto-shortcode__-param'], ['data-is-shortcode,1', 'data-value,meta', 'data-raw,meta'])"
                content: []
              - " "
              - t: "Span"
                attr: "('', ['quarto-shortcode__-param'], ['data-is-shortcode,1', 'data-value,title', 'data-raw,title'])"
                content: []
      - "}Content:::"
````

So I don't know enough about Shortcode handling to see how / if this could be supported
