### ISSUE TITLE
Giscus light/dark theme yaml example incorrect

### ISSUE THREAD

**Issue by ozanozbeker** [quarto-dev/quarto-cli#10003]
### What would you like to do?

Report an issue on quarto.org

### Description

In the Giscus section, https://quarto.org/docs/reference/projects/websites.html#giscus, the documentation shows:
```
website:
  comments:
    giscus:
      light: light # giscus theme used for light website theme
      dark: dark_dimmed # giscus theme used for dark website theme
```

But it should be:
```
website:
  comments:
    giscus:
      theme:
        light: light # giscus theme used for light website theme
        dark: dark_dimmed # giscus theme used for dark website theme
```
