### ISSUE TITLE
[Feature Request] Allow RevealChalkboard on self-contained slides `revealjs`

### ISSUE THREAD

**Issue by rleyvasal** [quarto-dev/quarto-cli#1003]
It would be great if Chalkboard can be used in self-contained slides. One of the great features of presentations is the ability to make notes on the screen and this is not currently possible with self-contained.

I get the following error message when trying to render `revealjs` slides in self-contained mode. 

`Reveal plugin 'RevealChalkboard is not compatible with self-contained output`

**Code to replicate**
```yaml
---
format:
  revealjs:
    self-contained: true
    incremental: true
    transition: convex
    slide-number: true
    chalkboard: 
      buttons: false

---
```
