### ISSUE TITLE
dark mode broken for my website

### ISSUE THREAD

**Issue by daniellga** [quarto-dev/quarto-cli#10070]
For some time now dark mode looks broken for my website. Could someone check what is happening?

Link for the githubpages with the generated website:
https://daniellga.github.io/harmonium/

Link for the repo
https://github.com/daniellga/harmonium

The quarto generated website is in the docs folder while the inputs to generate this website is in _docs folder.

quarto_yml
```
project:
  type: website
  output-dir: ../../docs

website:
  title: "Harmonium"
  navbar:
    tools:
      - icon: github
        href: https://github.com/daniellga/harmonium
        text: GitHub
  sidebar:
    style: "docked"
    contents:
      - section: "Classes"
        contents: contents/* 

format:
  html:
    theme:
      dark: litera
      light: litera
    css: styles.css
    toc: true
    grid:
      body-width: 1000px
```

Image of the dark mode generated:

![image](https://github.com/quarto-dev/quarto/assets/43149605/f2907f8b-9106-44bb-9caf-f9c577a718fa)

Thanks in advance!
