### ISSUE TITLE
About page's links are simple link

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#1008]
I tried the About page (https://quarto.org/docs/websites/website-about.html), but the rendered results seem to be different from those on the reference page.

The reference page shows links like that.

![image](https://user-images.githubusercontent.com/50911393/170826451-8f4d0760-bae7-478c-9c3c-9243092b6e43.png)

But I get this one (simple linked text).

![image](https://user-images.githubusercontent.com/50911393/170826467-ce9deefb-cc24-49ca-b7c1-fb7e44491997.png)

```yaml
about:
  template: marquee
  links:
    - icon: github
      text: GitHub
      href: https://github.com/
```
