### ISSUE TITLE
Different theme configuration for some page within a website does impact the whole website

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10087]
Reported once again for custom themed html page in website this time: https://forum.posit.co/t/directory-level-yaml-gets-applied-to-entire-quarto-website/188328/4

````powershell
> quarto create project website test-subdir
````

Then add a `subdir` directory with `subdir/index.qmd`
````
{{< lipsum 1-2 >}}
````
and `_metadata.yml`
````
format:
  html:
    fontcolor: red
````

User is expecting to modify only the theme for this page. 

In `_quarto.yml`
````yaml
project:
  type: website

website:
  title: "example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: subdir/index.qmd
        text: Subdir

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
````

The results is that all Quarto theme information are merged in the same file moved in `site_libs/bootstrap/bootstrap.min.css` 

So red will be set for `$body-color`
https://github.com/quarto-dev/quarto-cli/blob/6b0728c9a284e68364afd736057afde29447612f/src/format/html/format-html-scss.ts#L467

and applies to the whole site. 

--- 

### Some notes: 

- @mcanouil remembers a discussion with @dragonstyle about this being by design because all pages in a single website should share the same theme.  @dragonstyle if you pass around here, maybe you can share again the full story. thanks. 
 
- If a single theme for all page is intended, we probably need to warn about or even prevent that a theme set one of the website page within the website is impacting the whole website. Really unexpected as a user. 

- We have a variant of this problem of themes being merged in a single file for revealjs presentation. Presentations included in a website can only use one single theme because of this.
	- https://github.com/quarto-dev/quarto-cli/issues/8383
