### ISSUE TITLE
Support `announcement` in books

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#10114]
### Bug description

In 1.5, websites support the `announcement` option. Books probably should too.

### Steps to reproduce

```
quarto create project book announcement
```

Add `announcement` `_quarto.yml` to:
```yaml
project:
  type: book

book:
  title: "Announcement"
  author: "Norah Jones"
  date: "6/24/2024"
  announcement: 
    content: "**Alert** - this is some information that you should pay attention to"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

```
quarto preview
```

### Expected behavior

An announcement bar should appear at the top of the book page:
<img width="1435" alt="Screenshot 2024-06-24 at 9 26 38 AM" src="https://github.com/quarto-dev/quarto-cli/assets/25964/2898b08f-2b75-488a-9ee8-bb63888a6aa8">

### Actual behavior

No announcement appears:
<img width="1227" alt="Screenshot 2024-06-24 at 9 25 16 AM" src="https://github.com/quarto-dev/quarto-cli/assets/25964/81c2b183-fb56-4d77-922f-f73dbb304e00">

### Your environment

OS: Mac Sonoma 14.4.1

### Quarto check output

```bash
quarto check
Quarto 1.5.45
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.45
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.03.13
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/charlottewickham/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: /Users/charlottewickham/Documents/posit/quarto-web/.venv/bin/python
      Jupyter: 5.7.2
      Kernels: julia-1.10, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources
      LibPaths:
        - /Users/charlottewickham/Library/R/arm64/4.4/library
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```
