### ISSUE TITLE
svg logo is not displayed

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-cli#10161]
I have used svg for logo field: https://github.com/xability/xability.github.io/blob/7581f617e1f859bb5d88ca6209dfbee2e5a0887a/_quarto.yml#L45-L46

However, it is not displayed in the navbar: https://xabilitylab.ischool.illinois.edu/

Is there any special parameter that I need to adjust?

**Comment by mcanouil** [comment]
The logo is displayed.

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/4a10fc51-2c11-4f32-9270-e6a4131c6444">

(I don't know yet why like this though)

**Comment by mcanouil** [comment]
Quick workaround:

```scss
/*-- scss:defaults --*/

/*-- scss:rules --*/
.navbar-logo {
  height: 1em;
}
```

```yml
format:
  html:
    theme: [cosmo, styles.scss]
```
