### ISSUE TITLE
[WARNING] Could not load translations for ua

### ISSUE THREAD

**Issue by truecluster** [quarto-dev/quarto-cli#10178]
### Bug description

This seems a variant of #5197 for language ua

When I run quarto render

    in a book project
    with a project-wide lang: ua setting in quarto.yml,

I see:
```
[WARNING] Could not load translations for ua
  data file translations/ua.yaml not found
[WARNING] The term Abstract has no translation defined.
```
And the language-relevant elements in the rendered documents ARE translated.

_quarto_yml:

```
project:
  type: book

book:
  title: "mytitle"
  author: "Norah Jones"
  date: "30.6.2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

lang: ua
```

### Steps to reproduce

I installed the recent version of RStudio rstudio-2024.04.2-764-amd64.deb, installed the most recent version of quarto quarto-1.5.52-linux-amd64.deb, created a new book project and set `lang: ua`.

### Expected behavior

no warning

### Actual behavior

[WARNING] Could not load translations for ua
  data file translations/ua.yaml not found
[WARNING] The term Abstract has no translation defined.

### Your environment

-OS Ubuntu 20.04.6 LTS 
-IDE RStudio 2024.04.2-764
-Quarto 1.5.52

### Quarto check output

Quarto 1.5.52
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.52
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/jo/.TinyTeX/bin/x86_64-linux
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /home/jo/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
