### ISSUE TITLE
publish.yml: Incorrect type. Expected "array".

### ISSUE THREAD

**Issue by ozanozbeker** [quarto-dev/quarto-cli#10207]
### What would you like to do?

Report an issue on quarto.org

### Description

Using the documentation to publish on Netlify via GitHub Actions, the .github/workflows/publish.yml gives the Problem: `Incorrect type. Expected "array".` when using:

```yml
on:
  workflow_dispatch:
  push:
    branches: main
```

I believe it's supposed to be:

```yml
on:
  workflow_dispatch:
  push:
    branches: 
      - main
```

**Comment by mcanouil** [comment]
Could you provide?
- the link to where in the documentation you think there is a mistake
- the log of your workflow showing the error

What you shared is unfortunately not enough especially because it has no errors, see <https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags>.

**Comment by cderv** [comment]
@ozanozbeker Thanks a lot for the feedback. All our doc uses this syntax, which does not seem to be valid (anymore?)
Doc page example: https://quarto.org/docs/publishing/netlify.html#publish-action

It should be 

````
on:
  workflow_dispatch:
  push:
    branches: 
      - main
````

or 
````
on:
  workflow_dispatch:
  push:
    branches: [main]
````

we'll update
