### ISSUE TITLE
Allow opting out extension name part in `format-link` text when customizing content

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10273]
It seems not possible today to really customize fully the text as the extension name will always be appended in parenthesis if the format comes from an extension

https://github.com/quarto-dev/quarto-cli/blob/9724c3dd403d4e723bcb0a7e7bef6e49d23a353a/src/format/html/format-html-links.ts#L95-L104

Should we add a new option to allow overriding this ? 

Or should just an example showing the `href` form be used instead for those situation ? 
https://quarto.org/docs/output-formats/html-multi-format.html#specifying-formats-to-link

To think about. 

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/10270

<div type='discussions-op-text'>

<sup>Originally posted by **aaronschiff** July 11, 2024</sup>
### Description

This is pretty minor but ... I care about details 😅

I have a project that produces html and pdf output via a custom Typst template. I have used `format-link` in the project's `_quarto.yml` file to change the way the link to the Typst output is displayed in the html table of contents, but it still includes the template's name in brackets. Is there a way to remove the template name?

Here is the relevant part of the project `_quarto.yml`, where my template is called "cheatsheet": 

```
format:
  html:
    toc: true
  cheatsheet-typst:
    toc: false

format-links:
  - html
  - format: cheatsheet-typst
    text: PDF
    icon: file-pdf
```

Here's link in the rendered html: 

<img width="152" alt="Screenshot 2024-07-11 at 17 13 39" src="https://github.com/quarto-dev/quarto-cli/assets/10150126/1b0e74be-a953-4e8e-8509-d617eb8520b8">

I'd like it to just say "PDF".</div>

**Comment by aaronschiff** [comment]
Thanks for considering this. I’m not sure if you need to add another option for this case? If the user has specified the `text` parameter in `format-links` you can take that directly as what the user wants to be shown in the link output. That was how I assumed it would work based on the documentation.

**Comment by mcanouil** [comment]
I agree `text` value should be left untouched.

**Comment by EirikTengesdal** [comment]
I would also like it if this automatic addition of `(kExtensionName)` (yielding, e.g., `PDF (preprint)`) to the document can be overridden, since it prevents me from using it for purposes like submitting manuscripts.

(Of course, I could just edit/remove the resulting ` (preprint)` part of string from the HTML source code, but for reproducibility and consistency reasons, it would be good to have the option to make Quarto generate it like that in the first place.)

**Comment by mattyg-ds** [comment]
This feature would be good to have.

For now I have been using javascript in a html block at the end of my quarto files to remove formats I don't want, similar to what @EirikTengesdal suggested.
```
<script>
  document.querySelectorAll('.quarto-alternate-formats a').forEach(a => {
    if (a.textContent.trim().toLowerCase() === 'typst') a.closest('li').remove();
  });
</script>
```

**Comment by andrewheiss** [comment]
Hi! Chiming in to say that I'd love some sort of feature like this too

My workaround is to use javascript as well, but more generic, removing all parenthetical (extension) names. Like here, I'm using [this hikmah-pdf format](https://github.com/andrewheiss/hikmah-academic-quarto), so I customize the text with `html: format-links: format: text` and then use a script in `include-after-body` to take out the "(hikmah)" that's added:

```yaml
format:
  hikmah-typst: default

  html:
    format-links:
      - html
      - format: hikmah-typst
        text: PDF version
        icon: file-pdf
    include-after-body: 
      - text: |
          <script>
          document.querySelectorAll('.quarto-alternate-formats a').forEach(a => {
            a.childNodes.forEach(node => {
              if (node.nodeType === Node.TEXT_NODE) {
                node.textContent = node.textContent.replace(/\s*\(.*?\)\s*$/, '');
              }
            });
          });
          </script>
```
