### ISSUE TITLE
Variable substitution via shortcodes fails in `about` links. 

### ISSUE THREAD

**Issue by connortwiegand** [quarto-dev/quarto-cli#10289]
### Bug description

Suppose you have an item `baz` in `_variables.yml`, which contains named subitems `foo` and `bar`. If one uses the shortcode `{{<var baz.foo >}}` in the `links` subkey of an `about` page, such as:
```
title: About Page
about:
  links:
    - icon: {{<var baz.foo >}}
      href: {{<var baz.bar >}}
```
No variable substitution is performed. 

This relates to #1627, #8987, and #4680. 

**Thank You!**

### Steps to reproduce

`_variables.yml`, in project root:
````
gh: 
  txt: GitHub
  lnk: https://github.com/
  icn: "github"
    
lnkdn:
  txt: Linkedin
  icn: "linkedin"
  lnk: "https://www.linkedin.com/in/"
````

`about/index.qmd`:

````
---
title: "More About Me"
image: ../imgs/bio-photo-1.jpg
sidebar: false
about:
  id: about-content
  template: trestles
  image-shape: round
  image-width: 250px
  links:
    - icon: github
      text: ""
      href: "{{< var gh.lnk >}}"
    - icon: linkedin
      text: "[]({{< var lnkdn.lnk >}})"
---

:::{#about-content}
<!-- stuff -->
:::
````

I've tried various flavors of the above `links` key based on similar issues. I've also tried this using an `about.qmd` in the root of the project. I am not able to get variable substitution to work as expected. 

For completeness, here is a portion of my root `_quarto.yml`:
````
project:
  type: website

website:
  title: "Connor T. Wiegand"
  description: ""

  navbar:
    title: "Me"
    left:
      - text: About Me
        href: about/index.qmd
````
FWIW, adding `repo-url: https://github.com/connortwiegand/` and replacing one of the link options with "{{< meta website.repo-url >}}" produces the following:

```
WARNING (/opt/quarto/share/filters/main.lua:17471) Unknown meta key website.repo-url specified in a metadata Shortcode.
```

### Expected behavior

`var` shortcodes are substituted with their values from `_variables.yml`. 

### Actual behavior

No variable substitution is performed. 

### Your environment

- VSCode `1.91.1`
- Linux Mint 21.3 (Ubuntu 22.04 -- Jammy)

### Quarto check output

```
Quarto 1.5.52
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.52
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/cwiegand/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6 (Conda)
      Path: /home/cwiegand/miniconda3/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /home/cwiegand/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
FYI, there is nowhere in Quarto where `icon` supports shortcodes because it's supposed to be a string giving the name of the Bootstrap icon.
If Quarto is going to support shortcodes in `icon` then it should allow for any possible content.

**Comment by cscheid** [comment]
In my view, this is really halfway between a bug and an enhancement. Technically the fix is to add support for shortcode expansion in these contexts (so an "enhancement"), but the fact that we fail to expand shortcodes in these cases is incredibly unintuitive, so a bug.

**Comment by eyayaw** [comment]
Hi there, 

I ran into this issue today. The thing is that var shotcode expansion works inside `_quarto.yml` but it does not in yaml headers in `qmd` files. However, expansion works with 'raw HTML' in headers, e.g, `subtitle: '<img src="{{< var quarto-icon >}}" width="50px">` .  Any update on this? Thank you. 

`_quarto.yml`
````yml
project:
  type: website

website:
  title: "test-var-shortcodes with ![]({{< var quarto-icon >}}){width=50px}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
````

`_variables.yml`
````yml
quarto-icon: https://quarto.org/quarto.png
````

`index.qmd`
````yml
---
title: "test-var-shortcodes![Image](https://github.com/user-attachments/assets/c729cc15-7a3c-49ef-bd6b-9ac1d589ddce)
"
subtitle: '<img src="{{< var quarto-icon >}}" width="50px">  | ![]({{< var quarto-icon >}}){width=50px}'
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

Quarto is amazing ![]({{< var quarto-icon >}}){width=100px}.
````
## Result
![Image](https://github.com/user-attachments/assets/d06aa95c-ea3e-490f-bd0b-2c3df9885104)

**Comment by cderv** [comment]
@eyayaw where did you use `{{< var site-url >}}` in your configuration before publishing ?  I would guess the `site-url` inside the `_quarto.yml`

For `site-url` there, it won't be possible to use shortcode because right now those configuration are not all resolved at rendering time with Pandoc. This configuration is read by `quarto publish` to know the website url. 

We don't expect this to be a variable inserted using a shortcode right now; so this is an enhancement as explained above (https://github.com/quarto-dev/quarto-cli/issues/10289#issuecomment-2231989122)
> Technically the fix is to add support for shortcode expansion in these contexts (so an "enhancement")

**Comment by eyayaw** [comment]
@cderv Thank you, I understand. It's in `_quarto.yml`. However, var expansion works in the same file. 

```yml
project:
  type: website
  output-dir: _site

website:
  title: Eyayaw Beze
  description: "Eyayaw Beze's website"
  site-url: https://eyayaw.github.io/ #"{{< var site-url >}}"
  repo-url: https://github.com/eyayaw/eyayaw.github.io #"{{< var repo-url >}}"

  page-footer:
      left: |
        <span><i class="fa-solid fa-copyright"></i> {{< var year >}} Eyayaw Beze | እያያው ተካ በዜ</span>
```
