### ISSUE TITLE
revealjs title slide partial

### ISSUE THREAD

**Issue by kbvernon** [quarto-dev/quarto-cli#10308]
### Bug description

If I use the default template-partial for the title slide in a revealjs presentation _but make no changes to the template-partial_, shouldn't it have the same formatting as a presentation that doesn't use the template-partial at all?

### Steps to reproduce

test-with-partial.qmd
```yaml
---
title: "Critical Role"
subtitle: "Nerdy Ass Voice Actors Playing DnD"
author: 
  - name: Nott the Brave
    affiliation: The Mighty Nein
    orcid: 0000-0002-1825-0097
  - name: Fresh Cut Grass
    affiliation: Bells' Hells
    orcid: 0000-0002-1825-0097
date: last-modified
format:
  revealjs:
    template-partials:
      - title-slide.html
---
```
title-slide.html
```html
<section id="$idprefix$title-slide"$for(title-slide-attributes/pairs)$ $it.key$="$it.value$"$endfor$>
  <h1 class="title">$title$</h1>
$if(subtitle)$
  <p class="subtitle">$subtitle$</p>
$endif$
$for(author)$
  <p class="author">$author$</p>
$endfor$
$for(institute)$
  <p class="institute">$institute$</p>
$endfor$
$if(date)$
  <p class="date">$date$</p>
$endif$
</section>
```

### Expected behavior

I would expect these to produce the same output as

test-without-partial.qmd
```yaml
---
title: "Critical Role"
subtitle: "Nerdy Ass Voice Actors Playing DnD"
author: 
  - name: Nott the Brave
    affiliation: The Mighty Nein
    orcid: 0000-0002-1825-0097
  - name: Fresh Cut Grass
    affiliation: Bells' Hells
    orcid: 0000-0002-1825-0097
date: last-modified
format: revealjs
---
```

### Actual behavior

Yaml options author.orcid and author.affiliation get dropped and formatting is removed.

### Your environment

- IDE: RStudio 2024.04.2 Build 764 (also happens for Positron 2024-07.0-52)
```r
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/Denver
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.1 tools_4.3.1 
```

### Quarto check output

```bash
$ quarto check
Quarto 1.4.545
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.545
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.01
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\kenne\AppData\Roaming\TinyTeX\bin\win32\
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Users/kenne/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/kenne/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.47
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK
```

**Comment by kbvernon** [comment]
For reference, I was hoping to add 
```yaml
github: kbvernon/my-revealjs-repo
```
to the yaml and then this to title-slide.html
```html
$if(github)$
    <p>GitHub: <a href="https://github.com/$github$">$github$</a></p>
$endif$
```
on the assumption that there's not a better way to do this...

**Comment by cderv** [comment]
> If I use the default template-partial for the title slide in a revealjs presentation but make no changes to the template-partial, shouldn't it have the same formatting as a presentation that doesn't use the template-partial at all?

It should, but you need to use the right title-slide partial. Since Quarto 1.2, where this partial has been introduced, Quarto is using an improved version of title slide partials. So the exact one to provide would be 
- https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/revealjs/pandoc/title-fancy/title-slide.html

The one you provided explicitely is the default pandoc title slide 
- https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/revealjs/pandoc/title-slide.html

That is why you get a difference. 

The usual one from Pandoc can be opt-in by `title-slide-style: pandoc` (See https://quarto.org/docs/reference/formats/presentations/revealjs.html#slides)

So if you do 

````
---
title: "Critical Role"
subtitle: "Nerdy Ass Voice Actors Playing DnD"
author: 
  - name: Nott the Brave
    affiliation: The Mighty Nein
    orcid: 0000-0002-1825-0097
  - name: Fresh Cut Grass
    affiliation: Bells' Hells
    orcid: 0000-0002-1825-0097
date: last-modified
format: 
	revealjs:
		title-slide-style: pandoc
---
````

I believe you will get the same output. 

> then this to title-slide.html

You would need to provide a copy of this partial modified (https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/revealjs/pandoc/title-fancy/title-slide.html) and it would work as you expect. 


I'll see where we can add more about this in our documentation. Probably at: https://quarto.org/docs/journals/templates.html#revealjs-partials
