### ISSUE TITLE
Jupyter code block style not preserved when `quarto render`

### ISSUE THREAD

**Issue by hodgesmr** [quarto-dev/quarto-cli#10343]
### Bug description

Certain code block styles (eg, `code-block-border-left` and `highlight-style`) appear properly in `quarto preview` but are absent in `quarto render` when rendering a Jupyter notebook.

### Steps to reproduce

In `posts/_metadata.yml`:
```yaml
freeze: auto
title-block-banner: true
format:
  html:
    link-external-newwindow: true 
    code-block-bg: true
    code-block-border-left: "#3459e6"
    highlight-style: github
title-prefix: ""
```

In `posts/2024-07-21-code-notebook/index.ipynb`:
```ipynb
{
 "cells": [
  {
   "cell_type": "raw",
   "metadata": {
    "vscode": {
     "languageId": "raw"
    }
   },
   "source": [
    "---\n",
    "author: \"Firstname Lastname\"\n",
    "title: \"Code Rendering Test\"\n",
    "jupyter: python3\n",
    "date: 2024-07-21\n",
    "---"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def foo(x):\n",
    "    y = 5\n",
    "    return x + y"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

```

When running `quarto preview`:

<img width="1050" alt="Screenshot 2024-07-21 at 11 03 02 AM" src="https://github.com/user-attachments/assets/60b38d79-caae-4cb7-8097-75e415eb49ca">

When running `quarto render`:

<img width="1057" alt="Screenshot 2024-07-21 at 11 04 01 AM" src="https://github.com/user-attachments/assets/01e6c44b-5cd8-48c9-8300-20c445e5dada">

### Expected behavior

The output from `quarto render` should implement the code formatting options.

### Actual behavior

The code formatting options are not implemented when `quarto render`.

### Your environment

- macOS Sonoma 14.5

### Quarto check output

```bash
quarto check
Quarto 1.5.55
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.55
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.0
      Path: /Users/hodgesmr/.virtualenvs/lambda_calculus/bin/python3
      Jupyter: 4.11.1
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[✓] Checking Jupyter engine render....OK
```

**Comment by mcanouil** [comment]
Unfortunately, your example is not reproducible as you omitted nearly all the structure of your project.
Please share a small and fully reproducible example.

As of right now, I cannot reproduce. preview = render.

| Render | Preview |
|--------|--------|
| <img width="1624" alt="image" src="https://github.com/user-attachments/assets/03ad8d58-23f6-40de-88a3-c9d065ea5bc9"> | <img width="1624" alt="image" src="https://github.com/user-attachments/assets/4c671418-b18c-4ba6-98aa-0a65ad226168"> |

**Comment by hodgesmr** [comment]
Let me know if this is a useful way to provide my reproducible structure.

```sh
.
├── _quarto.yml
├── index.qmd
├── posts
│   ├── _metadata.yml
│   └── dummy-post
│       └── index.ipynb
└── posts.qmd
```

### `_quarto.yml`:

```yml
project:
  type: website
  output-dir: docs

website:
  title: "Test Site"
  navbar:
    right:
      - posts.qmd

format:
  html:
    theme:
      - cosmo
    header-includes: |
      <link href="https://fonts.googleapis.com/css?family=Overpass:300,900" rel="stylesheet">
    mainfont: Overpass
    toc: true
    link-external-newwindow: true
    title-prefix: ""
```

### `index.qmd`:
```qmd
---
title: "Test Home"
pagetitle: "Test Home"
about:
  template: trestles
---

This is a test site.
```

### `posts.qmd`:
```qmd
---
title: "Posts"
pagetitle: "Posts on Test Site"
listing:
    contents: posts
    type: default
    sort: "date desc"
    fields: [date, title]
    date-format: iso
    filter-ui: true
---
```

### `posts/_metadata.yml`:

```yml
freeze: auto
title-block-banner: true
format:
  html:
    link-external-newwindow: true 
    code-block-bg: true
    code-block-border-left: "#3459e6"
    highlight-style: github
title-prefix: ""
```

### `posts/dummy-post/index.ipynb`:

```json
{
 "cells": [
  {
   "cell_type": "raw",
   "metadata": {
    "vscode": {
     "languageId": "raw"
    }
   },
   "source": [
    "---\n",
    "author: \"Firstname Lastname\"\n",
    "title: \"Code Rendering Test\"\n",
    "jupyter: python3\n",
    "date: 2024-07-21\n",
    "---"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def foo(x):\n",
    "    y = 5\n",
    "    return x + y"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

```


With the above structure I see with `quarto preview`:

<img width="914" alt="Screenshot 2024-07-21 at 5 12 56 PM" src="https://github.com/user-attachments/assets/6a11a8d5-8c3a-4208-b395-ad5eb0dbc491">

But with `quarto render`:

<img width="931" alt="image" src="https://github.com/user-attachments/assets/5b0dbcef-f9af-4864-812f-d756d8e77277">
