### ISSUE TITLE
dashboard in a website sharing scss from an extension

### ISSUE THREAD

**Issue by xtimbeau** [quarto-dev/quarto-cli#10369]
### Bug description

Building a website with a dashboard in one page functions well ; but things get messy when trying to style it through an extension (and the logic is not easy to grasp). In this exemple, the html format is styled with an extension (called ext), setting some yaml and refering to a `.scss` file. Everything is fine, but the dashboard is not styled. However, when adding in the extension `_extension.yml` a dashboard section, using the same theme/.scss as the html part, then the theming and scss are applied everywhere including the dashboard. That's working, but a bit circonvoluted and not coherent with theming directly html format in the `_quarto.yml`. I may be missing something however.

A exemple:

`_quarto.yml:`
````yml
project:
  type: website

website:
  title: "test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - about.qmd

format:
  html: 
    theme: cosmo
````

`index.qmd`
````qmd
---
title: "test"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{r}
1 + 1
```
````

`dashboard.qmd`
````qmd
---
format:
  dashboard: default
---
## Row
::: {.valuebox title="title" color="green"}
42
:::

::: {.valuebox title="title" color="orange"}
76
:::
````

a random `about.qmd`

But if I use an extension, in 

`_extension/ext/ext/_extension.yml` with a scss file setting some elements (as a matter of fact it is not needed)
````yml
title: myext
author: me
version: 0.1.0
quarto-required: ">=1.6.3"
contributes:
  formats:
    html:
      theme: 
        - cosmo
        - myscss.scss
      mainfont: Open Sans
      toc-location: left
      lightbox: true
      title-block-style: default
````

and then use the folowing `_quarto.yml`, then the styling works everywhere except on the dashboard
````yml
project:
  type: website
website:
  title: "test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - about.qmd
format:
  ext-html: 
    theme: cosmo
````

### Your environment

RStudio 2024 08
Quarto 1.6.3
Mac OS

### Quarto check output

```bash
Quarto 1.6.3
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.3
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/local/bin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
```
