### ISSUE TITLE
Freeze seems to be ignored in projects

### ISSUE THREAD

**Issue by skwde** [quarto-dev/quarto-cli#10447]
### Bug description

```yml
exectute:
  freeze: true
```

has no effect in projects (`_quarto.yml` / `_metadata.yml` / frontmatter in `document.qmd`)

### Steps to reproduce

The following example is just taken from the related discussion https://github.com/quarto-dev/quarto-cli/discussions/10429

Here is a minimal working example:

Use the `revealjs-slides/_metadata.yml`

```yml

jupyter: python3
execute:
  echo: true
  output: true
  freeze: true
  # cache: true
  keep-ipynb: false
format:
  revealjs:
    # ## use aspectratio 1610
    width: 1280 # default: 970
    height: 800 # default: 700
    auto-stretch: false
    navigation-mode: vertical
    controls: true
    progress: true
    slide-number: h.v
    toc: true
    toc-depth: 1
```

and the `revealjs-slides/slides.qmd`

````qmd
---
title: TEST
---

# ABC

```{python}
# | tags: [parameters]
bound = 1000000
```

starting at `0`

There are of course severals ways to do this.

Using a simple `for` loop

```{python}
# | freeze: true
%%timeit
s = []
for i in range(bound):
    s.append(i*i)
sum(s)
```
````

The `_quarto.yml` just has

```yml
date: last-modified
date-format: long
```

Running this via

```sh
quarto preview revealjs-slides/slides.qmd --no-browser  --port 8000
```

Shows that the cells are still executed.

Moreover it doesn't really matter where I put the block

```yml
execute:
  echo: true
  output: true
  freeze: true
  # cache: true
  keep-ipynb: false
```

it is just ignored.

Moreover when I add an additional file `revealjs-slides/sub.qmd` and use `{{< include sub.qmd >}}` in `revealjs-slides/slides.qmd` it also has no effect. Though I think it should have following the logic of  https://quarto.org/docs/projects/quarto-projects.html#metadata-merging.

### Expected behavior

Do not execute the code blocks no matter where `freeze: true` is set

### Actual behavior

`freeze: true` is ignored, codeblocks are executed independet of this setting.

### Your environment

- VSCode: 1.92.0
- debian bookworm in a devcontainer running on MacOS

### Quarto check output

```bash
# quarto check
Quarto 1.5.54
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.54
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /root/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.4 (Conda)
      Path: /opt/conda/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
