### ISSUE TITLE
Download PDF from GitHub Pages Hosted Site

### ISSUE THREAD

**Issue by s2t2** [quarto-dev/quarto-cli#10468]
### Bug description

I have a Quarto book project. I have enabled downloading of PDF file. Locally when I click the download button, it works. However on the GitHub pages hosted site, there is no PDF.

How can I ensure the PDF generation and download capability works on GitHub Pages?

### Steps to reproduce

Use the following "_quarto.yml" file (abbreviated):

```yml
project:
  type: book
  output-dir: _build

book:
  title: "My Book"
  downloads: [pdf, epub, docx] # enabling download link
  
  chapters:
    - index.qmd
    - chapter-2.qmd
    - chapter-3.qmd
   
  # ...

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

Run `quarto render` and see the site locally. See the download PDF link in the sidebar. Click, and see the PDF in the browser.

Push to GitHub, triggering the following GitHub Actions workflow file:

```yml

name: quarto-pages

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3

    #
    # PYTHON STUFF
    #

    # INSTALL PYTHON
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # INSTALL DOCUMENTATION DEPENDENCIES
    - name: Install docs dependencies
      run: |
        pip install -r docs/requirements.txt

    #
    # QUARTO STUFF
    #

    # INSTALL QUARTO
    # https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        # To install LaTeX to build PDF book
        # (to get past errors on the CI build)
        tinytex: true

    # RENDER WEBSITE CONTENTS TO DOCS/_BUILD
    - name: Build the book
      run: |
        quarto render docs/

    #
    # GITHUB PAGES STUFF
    #

    # UPLOAD CONTENTS OF DOCS/_BUILD
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "docs/_build"

    # DEPLOY WEBSITE CONTENTS TO GITHUB PAGES
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

```

Wait for the build to finish. See passing build.

Visit the hosted site. See the download PDF link in the sidebar. Click, but see a 404 error because the PDF does not exist at the expected location.

How can I change my quarto YML or my github pages workflow file to get the PDF download working on GitHub Pages site?

Thank you!

### Expected behavior

When I click the download PDF link in the sidebar of my GitHub Pages hosted site, I should see / download a PDF of the book.

### Actual behavior

When I click the link, it leads to a 404 error (could not find the PDF file).

### Your environment

VS Code

Mac OS Ventura 3.1

### Quarto check output

```
--->> quarto check
Quarto 1.4.554
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.554
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/local/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.9 (Conda)
      Path: /opt/anaconda3/envs/quarto-env/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/local/Cellar/r/4.3.1/lib/R
      LibPaths:
        - /usr/local/lib/R/4.3/site-library
        - /usr/local/Cellar/r/4.3.1/lib/R/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")


```
