### ISSUE TITLE
Question: Is it possible to use shortcodes in LaTeX macros?

### ISSUE THREAD

**Issue by ramiromagno** [quarto-dev/quarto-cli#1047]
Let us say my `_quarto.yml` has this snippet:

```yml
format:
  pdf:
    documentclass: book
    include-in-header:
      - tex/preamble.tex
      - tex/macros.tex
    include-before-body:
      - tex/firstpages.tex
```

And inside `macros.tex` I have:

```latex
\newcommand{\mytitle}{{{< meta title >}}}
\newcommand{\myfullname}{{{< var author.fullname >}}}
\newcommand{\myshortname}{{{< var author.shortname >}}}
```

This won't work... Is there any way of replacing these shortcodes in the LaTeX files..?
