### ISSUE TITLE
`search-box-placeholder` not effective

### ISSUE THREAD

**Issue by hodgesmr** [quarto-dev/quarto-cli#10485]
### Bug description

When setting a `search-box-placeholder` value for a textbox search on a website, no placeholder text appears.

### Steps to reproduce

Create a new site:

```sh
quarto create project website mysite
```

Update _quarto.yml to include a textbox search with placeholder text:

```yml
project:
  type: website

website:
  title: "test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  search: 
    location: navbar
    type: textbox

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


language: 
  search-box-placeholder: "test"
```

Preview:

```sh
quarto preview mysite
```

### Expected behavior

The search box should show the placeholder text, "test".

### Actual behavior

The search box shows no placeholder text.

<img width="243" alt="image" src="https://github.com/user-attachments/assets/2af46e88-ad7d-4042-9f12-152326f60646">

### Your environment

MacOS Sonoma 14.5

### Quarto check output

```sh
$ quarto check
Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /Users/hodgesmr/.virtualenvs/quarto/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
