### ISSUE TITLE
Question: Do PDF books always require an index.qmd?

### ISSUE THREAD

**Issue by ramiromagno** [quarto-dev/quarto-cli#1050]
I am writing a PDF book using LaTeX. I have my chapters indicated in `_quarto.yml`:

```
book:
  title: "This is a title"
  author: "Jane Doe"
  date: "6/2/2022"
  chapters:
    - index.qmd
    - cover.qmd
    - acknowledgements.qmd
    - resumo.qmd
    - abstract.qmd
    - toc.qmd
    - abbreviations.qmd
    - mainmatter.qmd
    - introduction.qmd
    - discussion.qmd
    - conclusion.qmd
    - bibliography.qmd
```

Is there a way to get rid of `index.qmd`? I understand that if the output format is HTML it makes more sense to always have such a file. Currently I just keep this file to avoid the error:

![snap](https://user-images.githubusercontent.com/19862384/171788047-9bace872-e09f-4d7d-94d3-680358a4d53f.png)
