### ISSUE TITLE
Overwrite of css function `contrast` in scss output

### ISSUE THREAD

**Issue by acederberg** [quarto-dev/quarto-cli#10528]
Thank you for `quarto`, it is great!

I am having trouble defining a css filter for some animations using scss:

```scss
/*-- scss:rules*/
.animation img,
.figure img {
  filter: invert(1) hue-rotate(135deg) saturate(2) contrast(0.75);
}

.anim-controls button i,
.anim-buttons button i .fa-flip-horizontal,
.anim-buttons button i .fa {
  filter: invert(1) !important;
}
```

I then run ``quarto render .`` and get the following error:

```stdout
ERROR: Theme file compilation failed:

Error: Missing argument $front.
      ╷
993   │ @function contrast($back, $front) {
      │           ━━━━━━━━━━━━━━━━━━━━━━━ declaration
...   │
12804 │   filter: invert(1) hue-rotate(135deg) saturate(2) contrast(0.75);
      │                                                    ^^^^^^^^^^^^^^ invocation
      ╵
  /tmp/quarto-session5c303ab593d3f7d1/97a8ea7c5b44a2b3/f75acea562ddeb6a.scss 12804:52  contrast()

Stack trace:

Error: Missing argument $front.
      ╷
993   │ @function contrast($back, $front) {
      │           ━━━━━━━━━━━━━━━━━━━━━━━ declaration
...   │
12804 │   filter: invert(1) hue-rotate(135deg) saturate(2) contrast(0.75);
      │                                                    ^^^^^^^^^^^^^^ invocation
      ╵
  /tmp/quarto-session5c303ab593d3f7d1/97a8ea7c5b44a2b3/f75acea562ddeb6a.scss 12804:52  contrast()
    at dartCommand (file:///opt/quarto/bin/quarto.js:43445:15)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async dartCompile (file:///opt/quarto/bin/quarto.js:43407:5)
    at async compileWithCache (file:///opt/quarto/bin/quarto.js:43636:17)
    at async compileSass (file:///opt/quarto/bin/quarto.js:43497:12)
    at async resolveSassBundles (file:///opt/quarto/bin/quarto.js:65862:27)
    at async resolveExtras (file:///opt/quarto/bin/quarto.js:69904:18)
    at async runPandoc (file:///opt/quarto/bin/quarto.js:69425:24)
    at async renderPandoc (file:///opt/quarto/bin/quarto.js:70717:26)
    at async Object.onRender (file:///opt/quarto/bin/quarto.js:78268:36)

```

The above code implies that the declaration of ``contrast`` on 993 overwrites the built in ``css`` function of the same name, which is not great. Am I doing something wrong or is this a bug? Is the source of this error from ``bootstrap``, is this even something under control within this repository?
