### ISSUE TITLE
Question: Can book parts be unnumbered?

### ISSUE THREAD

**Issue by ramiromagno** [quarto-dev/quarto-cli#1055]
I have a qmd file named `appendix_cmd.qmd`:

```qmd
# Appendices {.unnumbered}

\appendix
```

which does not translate to 

```
\part*{Appendices}
```

but to 

```
\part{Appendices}
```

In my `_quarto.yml` I do have something like:

```yml
book:
  title: "This is my title from the YAML"
  output-file: "some_book"
  author: "Jane Doe"
  date: "6/2/2022"
  chapters:
    - index.qmd
    - cover.qmd
    - acknowledgements.qmd
    - abstract.qmd
    - toc.qmd
    - abbreviations.qmd
    - mainmatter.qmd
    - introduction.qmd
    - part: part1.qmd
      chapters:
        - chp01.qmd
        - chp02.qmd
    - part: part2.qmd
      chapters:
        - chp03.qmd
    - discussion.qmd
    - conclusion.qmd
    - bibliography.qmd
    - part: appendix_cmd.qmd
      chapters:
        - appendix.qmd
    - colophon.qmd
```

Is there a way to get unnumbered book parts?
