### ISSUE TITLE
Unable to configure bilingual website with separate _quarto.yml files for each language (RTL and LTR same )

### ISSUE THREAD

**Issue by alirezach** [quarto-dev/quarto-cli#10601]
I'm trying to create a bilingual website using Quarto, with a main website in English and a separate blog in Persian with RTL direction. I've created separate _quarto.yml files for each language, but I'm unable to get the configuration to work as expected.

Here's what I've tried:

- Created a main _quarto.yml file in the root directory with English language settings
- Created a separate _quarto.yml file in the fa directory with Persian language settings and RTL direction
- Created separate index.qmd files for each language

** main _quarto.yml edit:
```
languages:
  en:
    title: "Example"
    author: "John doe"
  fa:
    title: "Persian Title"
    author: "Persian Name"
    language: fa.yml
    html:
      theme:
        light: sandstone, ../styles/persian.css
        dark: sandstone, ../styles/persian.css
      dir: rtl

files:
  english:
    site: en/_quarto.yml
  persian:
    site: fa/_quarto.yml 
```
** Persin (RTL) _quarto.yml:
```
website:
  title: "Persian blog"
  language: fa
  dir: rtl

format:
  html:
    theme:
      light: sandstone
      dark: sandstone
    css: ../../styles/persian.css 
```

Off course I try to an other way But Not working and only on style.css can Show on all website

**Comment by cderv** [comment]
@alirezach what is this part about exactly ? 
````yaml
files:
  english:
    site: en/_quarto.yml
  persian:
    site: fa/_quarto.yml
````

Where did you find example of this configuration ? Or what are you trying exactly ? 

It is not clear to me if you are doing two Quarto projects, and you render each one separately, or that you are expecting two quarto projects to render at once. 

Usually, there is only one `_quarto.yml` per project, this is why i am a bit puzzled here. 

> I edit again and I think it must be solved.

You edited only the code part. You did not edited your issue to provide a full reproducible example. You can share for example a github repo of what you tried, with the commands you tried and that leads to your problem. 

Asking to solve something without providing all asked information is not that useful and won't bring more results. 
As a reminder, our guidelines: https://quarto.org/bug-reports.html

Thanks
