### ISSUE TITLE
css style ignored in revealjs presentation

### ISSUE THREAD

**Issue by jpmorr** [quarto-dev/quarto-cli#10633]
### Bug description

I'm defining css attributes to reduce the spacing between a paragraph and a bullet list in a `revealjs` presentation but it appears to be ignored by the various browsers and possibly overwritten by an internal style.

### Steps to reproduce

I have the following added to `custom.scss`

```css
.reveal .slide ul li {
    margin-top: 0.2em;
    margin-bottom: 0.2em;
}

.reveal .slide ol li {
    margin-top: 0.2em;
    margin-bottom: 0.2em;
}

.reveal .slide ul li,
.reveal .slide ol li {
    margin-top: 0.2em;
    margin-bottom: 0.2em;
}
```

My `_quarto.yml` is like this:
```yml
project:
  title: "An Experiment"

format:
  revealjs:
    chalkboard:
      theme: whiteboard
      boardmarker-width: 5
      buttons: true
    navigation-mode: vertical
    reference-location: document
    incremental: true  
    transition: slide
    transition-speed: default
    slide-number: c
    history: false
    width: 1600 
    height: 900
    margin: 0.075
    theme: [default, custom.scss]
    highlight-style: github-dark

```

### Expected behavior

Gap between paragraph and `<ul> should reduce to 0.2em for top margin but it stays at 0.4em. Default seems to be overriding custom value.

### Actual behavior

![image](https://github.com/user-attachments/assets/bcb23f31-c774-4577-abf6-0032209dd8f1)

custom.css seems to be ignored and default is used. Other styling in my css file such as font sizes and colours are respected.

### Your environment

Windows 10/WIndows 11
VSCode

### Quarto check output

```
Quarto 1.5.53
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.53
      Path: C:\Users\user1\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: C:/Users/user1/Anaconda3/python.exe   
      Jupyter: 5.7.2
      Kernels: julia-1.2, julia-1.4, python3, iota

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-4.3.2
      LibPaths:
        - C:/Users/user1/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Your SCSS file is incorrect, see the documentation about the structure of the SCSS file: https://quarto.org/docs/presentations/revealjs/themes.html

**Comment by jpmorr** [comment]
I think the scss file is correct based on the description on the quarto page - css for modifying `.slide` properties in the rules section?

I've added the minimum required to reproduce the problem here: https://github.com/jpmorr/quarto_css_revealjs 

Question - how did you format the code example above? Is that just a code block within a table cell?

**Comment by mcanouil** [comment]
CSS is not SCSS. SCSS needs compilation and for that to happen properly, you need to follow the structure described in the documentation.
If you want to use pure CSS, then use `css` not `theme`.

**Comment by jpmorr** [comment]
I still don't understand what the problem is and why my `scss` is not valid as it's exactly what is shown in the documentation (https://quarto.org/docs/presentations/revealjs/themes.html#customizing-themes) - any css rule defined after `/*-- scss:rules --*/`.

It's also the same as your example, just with much less defined in it? It would be useful if you could point out why it's not valid when to me it looks exactly like the example in the documentation.

**Comment by mcanouil** [comment]
You shared the following as the content of the SCSS file:

```scss
.reveal .slide ul li {
    margin-top: 0.2em;
    margin-bottom: 0.2em;
}

.reveal .slide ol li {
    margin-top: 0.2em;
    margin-bottom: 0.2em;
}

.reveal .slide ul li,
.reveal .slide ol li {
    margin-top: 0.2em;
    margin-bottom: 0.2em;
}
```

Either you did not share at all the real content of your file or the content is wrong.
