### ISSUE TITLE
Can't place `index.qmd` in subdirectory?

### ISSUE THREAD

**Issue by ramiromagno** [quarto-dev/quarto-cli#1065]
I'd like to move qmd files (book chapters) to a subdirectory as shown in `_quarto.yml`:

```
book:
  title: "This is my title from the YAML"
  author: "Jane Doe"
  date: "6/2/2022"
  chapters:
    - index.qmd
    - frontmatter/cover.qmd
    - frontmatter/acknowledgements.qmd
    - abstract.qmd
    - toc.qmd
```

Both `cover.qmd` and `acknowledgements.qmd` seem to be read just fine from the `frontmatter/` directory. When I move `index.qmd` I then get a rendering error:

![snap](https://user-images.githubusercontent.com/19862384/172023170-366dc63d-ec84-4092-a96c-3d3c320f4f7f.png)

Does this mean that `index.qmd` and `_quarto.yml` need to be in the same directory?
