### ISSUE TITLE
xelatex not found when using profile

### ISSUE THREAD

**Issue by skwde** [quarto-dev/quarto-cli#10731]
### Bug description

`xelatex` is not found when a profile is used.

### Steps to reproduce

Use the `test.qmd`

````qmd
---
title: "Test"
---

# abc
````

and `_quarto.yml`

```yml
format:
  latex:
    output-ext: tex
  pdf:
    output-ext: pdf
```

with the `_quarto-test.yml`

```yml
format:
  latex:
    output-ext: test.tex
  pdf:
    output-ext: test.pdf
```

and the `_metadata.yml`

```yml
format:
  latex: default # requires such that .tex file is moved to output
  pdf:
    keep-tex: true
    documentclass: scrartcl
```

then run

```sh
quarto render test.qmd
```

which works fine.

Next run

```sh
quarto render test.qmd --profile test
```

which fails with 

```out
xelatex not found. Please select a different --pdf-engine or install xelatex
```

### Expected behavior

Proper rendering when `--profile test` is used, because obviously `xelatex` is available (otherwise the default profile would have failed as well)

### Actual behavior

`xelatex` not found when using `--profile test` on rendering

### Your environment

- VSCode 1.93.0
- devcontainer using debian bookworm on MacOS

### Quarto check output

Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/user/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
