### ISSUE TITLE
Standardize way for affiliations

### ISSUE THREAD

**Issue by raffaem** [quarto-dev/quarto-cli#10749]
### Bug description

Hello Quarto devs!

My understanding is that, for articles, we specify affiliations like this ([reference](https://quarto.org/docs/authoring/front-matter.html)):

```
author:
  - name: Norah Jones
    affiliation:
      - ref: cmu
      - ref: chicago
  - name: John Hamm
    affiliation:
      - ref: cmu
affiliations:
  - id: cmu
    name: Carnegie Mellon University
  - id: chicago
    name: University of Chicago
```

While for beamer presentations we have to use ([reference](https://stackoverflow.com/questions/75965560/multiple-authors-and-their-affiliations-on-quarto-beamer-presentation-title-slid)):

```
author: 
  - John Doe\inst{1}
  - John Roe\inst{2}
institute: 
  - \inst{1} affiliation for John Doe
  - \inst{2} affiliation for John Roe
```

Otherwise the affiliations will not appear in the title slide.

The latter syntax however causes the affiliation to be displayed in the bottom left corner.

I propose to standardize the way we specify affiliations so it's always the same across the two backends.

Related #1658

### Steps to reproduce

See above

### Quarto check output

```bash quarto check
➜  quarto check
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.5
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: ir, python3

(\) Checking Jupyter engine render....[IPKernelApp] WARNING | Config option `autoindent` not recognized by `ZMQInteractiveShell`.  Did you mean `autoawait`?
[✓] Checking Jupyter engine render....OK

Using 18 cores for parallelisation
[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/raffaele/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```
