### ISSUE TITLE
Draft banner missing, draft text fully rendered

### ISSUE THREAD

**Issue by graf47** [quarto-dev/quarto-cli#10753]
### Bug description

The drafting of websites seems not to work properly in 1.5.57:
- The "Draft"-banner is missing
- The site gets always fully renderd/created even if `draft-mode=gone`

![image](https://github.com/user-attachments/assets/7a109130-32a1-4200-aa8c-752f408d395d)

### Steps to reproduce

Create new website-project, then add draft.qmd and modify _quarto.yml

draft.qmd:
````md
---
title: This is a draft
draft: true
---

This is text. Should it breally be rendered as well when draft-mode=gone?
````

_quarto.yml:
````yml
project:
  type: website

website:
  title: "Quarto_Test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: draft.qmd
        text: Draft
    draft-mode: gone

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
````

### Expected behavior

Acc to the guide, the text shouldn´t be rendered. there also should appear a "Draft"-banner.

### Actual behavior

See description

### Your environment

- Win 11 23H2
- VSCode 1.93.0
- Quarto 1.5.57

### Quarto check output

````
Quarto 1.5.57
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.57
      Path: C:\Users\grafs1\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by mcanouil** [comment]
Could you properly format your post using code blocks for code and terminal outputs? Thanks.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.
See <https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us>.

**Comment by cscheid** [comment]
You're setting `draft-mode: gone` inside the navbar field, instead of the website field.

**Comment by graf47** [comment]
Hi Carlos, thanks for looking into this and your reply! I put my draft.qmd into the navbar for this example as it is done that way in your docs. In my project I added it into the sidebar, but the banner (as shown here:  https://quarto.org/docs/websites/website-drafts.html#appearance-of-drafts) does not appear in both ways. Also things don´t change if I don´t set any `draft-mode` to use the defaults or if I set it. Maybe you can look at this in the future. We can keep this closed, we will handle this differently in our team.

**Comment by mcanouil** [comment]
What are you referring to? `drafts` and `draft-mode` are not in the navbar in the documentation. They are at the top-level of `websit`. Please read
carefully the documentation.

**Comment by graf47** [comment]
Should this be working? Becaue it doesn´t show a banner:

````yml

project:
  type: website

website:
  title: "Quarto_Test"
  draft-mode: gone
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: draft.qmd
        text: Draft

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

````

````qmd

---
title: This is a draft
draft: true
---

This is text. Should it breally be rendered as well when draft-mode=gone?

````

![image](https://github.com/user-attachments/assets/1886344d-f48f-42c1-8daf-079f6424d244)
