### ISSUE TITLE
PDF book: chapters are falsely grouped within a "part" (hierarchy wise)

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#1075]
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?

- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?

- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

- [x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

## Issue

References listed at the same hierarchy level as a part are getting grouped within the last "Part" instead of appearing at the same level (in the Toc). 

![image](https://user-images.githubusercontent.com/8430564/172135451-7c86a07c-1146-4ad4-baeb-de4cd63308d7.png)

## Reprex

1. `quarto create-project mybook --type book`
2. Adjust `_quarto.yml` with content below
3. `quarto render --to pdf`

```
project:
  type: book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "6/6/2022"
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
      - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: book
```

## Metadata

```
quarto check

[✓] Checking Quarto installation......OK
      Version: 0.9.515
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.13
      Path: /opt/homebrew/opt/python@3.9/bin/python3.9
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/pjs/Library/R/arm64/4.2/library
        - /opt/R/4.2.0-arm64/Resources/site-library
        - /opt/R/4.2.0-arm64/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by jjallaire** [comment]
I wonder if there is a whitespace issue in your YAML? When I make this change I get this output:

<img width="224" alt="Screen Shot 2022-06-06 at 6 05 10 AM" src="https://user-images.githubusercontent.com/104391/172140614-181023b8-6ab3-4faf-88a5-9014c5a8e188.png">

Here is my `_quarto.yml`:

```yaml
book:
  title: "mybook42"
  author: "Jane Doe"
  date: "6/6/2022"
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - summary.qmd
    - references.qmd
```

**Comment by pat-s** [comment]
Only applies to PDF, HTML output is fine.

**Comment by jjallaire** [comment]
This gets into some LaTeX that is beyond what I'm familiar with (it seems like by default w/o hacks that LaTeX does indeed slurp up subsequent chapters into previous parts as `\part` exists at the global level not in a hierarchy). Here is some related discussion:

https://tex.stackexchange.com/questions/355472/how-can-i-exclude-a-chapter-from-part-in-hyperref-bookmarks

@dragonstyle Could you have a look at this when its convenient to see if there is any special incantation we can make to exclude subsequent chapters from the part. 

@pat-s If you want to hack on this as well just add `keep-tex: true` to the `pdf` format and then you can play with the generated LaTeX (the RStudio Compile PDF command or any LaTeX editor's similar command should be able to render the `keep-tex` output to PDF.

**Comment by jjallaire** [comment]
Thanks! We'll see if we can make this automatic.

**Comment by dragonstyle** [comment]
Thanks for reporting and providing a great solution and diagnosis. This should be automatic for you now!

**Comment by pat-s** [comment]
Thanks.
In v0.9.531 I now see

```
Error running filter /Applications/quarto/share/filters/quarto-post/quarto-post.lua:
Block expected, got Attr
        while retrieving MetaValue
        while retrieving value
        while retrieving key-value pair
        while retrieving Map
        while retrieving MetaValue
        while retrieving value
        while retrieving key-value pair
        while retrieving Map
        while retrieving MetaValue
        while retrieving index 1
        while retrieving list
        while retrieving MetaValue
        while retrieving value
        while retrieving key-value pair
        while retrieving Map
        while retrieving Meta
        while retrieving function argument meta
        while retrieving arguments for function Pandoc
stack traceback:
        ...cations/quarto/share/filters/quarto-post/quarto-post.lua:1166: in function 'compileTemplate'
        ...cations/quarto/share/filters/quarto-post/quarto-post.lua:1770: in local 'fn'
        ...cations/quarto/share/filters/quarto-post/quarto-post.lua:1063: in function <...cations/quarto/share/filters/quarto-post/quarto-post.lua:1057>
make: *** [pdf] Error 1
```

My config is like

```yml
book:
  chapters:
    - part: part.qmd
      chapters:
        - chapter1.qmd
        - chapter3.qmd
    - references.qmd
```

**Comment by pat-s** [comment]
Sure! The source can be found [here](https://github.com/mlr-org/mlr3book/tree/quarto/book) - the README should hopefully get you going quickly!

**Comment by dragonstyle** [comment]
Ok I managed to get cloned and running but am not seeing the issue when I build (albeit using the _very_ latest which definitely has fixes for our part handling which wasn't really working well in the version I originally pointed you at). Are you able to successfully render with the very latest?

**Comment by pat-s** [comment]
Nope, same issue with v0.9.533 - but I'll check what the CI does.

**Comment by dragonstyle** [comment]
Ok I have zoomed out and (hopefully) have resolved all of these issues (including the new ones I introduced). A new release is being built now and should be available shortly...

**Comment by pat-s** [comment]
Confirmed in v0.9.545! Thanks for the quick fixes!

**Comment by pat-s** [comment]
FYI this triggers a side-effect for the specification of appendices: instead of

```yml
    - 99-references.qmd
    - appendices:
      - some.qmd
```

these now also need to be nested within a part, otherwise `some.qmd` will be moved to the same level as references. 

```yml
    - 99-references.qmd
    - part: "Appendices"
      chapters:
      - some.qmd
```

**Comment by jjallaire** [comment]
@dragonstyle It seems like this isn't quite what we want (i.e. extra YAML required and mis-labeling of appendices). Re-opening to dig into those issues.

**Comment by dragonstyle** [comment]
Great catch, thank you! This should be fixed here:

80d70b8264ffd711498a172d6b1630d145043610

A fresh release is building now...

**Comment by pat-s** [comment]
Thanks! The following now works as desired (v0.9.550)

```yml
book:
  chapters:
    - 99-references.qmd
  appendices:
    - some.qmd
```
