### ISSUE TITLE
Overlaping text and page number in pdf output

### ISSUE THREAD

**Issue by kostadinoff** [quarto-dev/quarto-cli#10786]
### Bug description

Hello everybody,

I'm encountering an issue with Quarto, and I feel stuck. When rendering the document, the page numbers overlap with the text and figures on several pages. Unfortunately, using \newpage isn't an option right now, as the document is under review, and I frequently need to add new sections.

Has anyone faced this before or have any advice on how to resolve it?

I've attached the YAML file for reference.

Thanks in advance!

![image](https://github.com/user-attachments/assets/03d33980-87df-4fdd-907f-47e2f9eb67bd)

```yaml

project:
  type: book
book:
  chapters:
    - index.md
    - 01.md
    - 03.md
    - 04.md
    - 05.md
    - 06.md
    - 07.md
    - 08.md
    - 09.md
bibliography: "references.bib"
citeproc: true
suppress-bibliography: true
lof: false
lot: false
link-citations: true
linkReferences: true
csl: "intext.csl"
filters: [pandoc-quotes.lua]
quot-lang: en
toc: true
toc-depth: 2
geometry: "a4paper, left=2cm, right=2cm, top=2cm, bottom=2cm, heightrounded"
number-sections: true
format:
  pdf:
    mainfont: Times New Roman
    monofont: Times New Roman
    sansfont: Times New Roman
    fontsize: 11pt
    include-before-body: tex/title_page.tex
    include-in-header: tex/in_header.tex
```

in_header.tex

```tex
\renewcommand\arraystretch{0.9}
\usepackage{setspace}
\usepackage{placeins}
\usepackage{float}   
\raggedbottom
\flushbottom

```

### Steps to reproduce

![image](https://github.com/user-attachments/assets/03d33980-87df-4fdd-907f-47e2f9eb67bd)

### Your environment

Windows 11

### Quarto check output

Quarto 1.5.55
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.55
      Path: C:\Users\drkos\AppData\Local\Programs\Quarto\bin
      CodePage: 1251

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: C:/Users/drkos/AppData/Local/Programs/Python/Python312/python.exe
      Jupyter: 5.7.2
      Kernels: python3

(/) Checking Jupyter engine render....Traceback (most recent call last):
  File "C:\Users\drkos\AppData\Local\Programs\Quarto\share\jupyter\jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\Users\drkos\AppData\Local\Programs\Quarto\share\jupyter\notebook.py", line 15, in <module>
    from yaml import safe_load as parse_string
ModuleNotFoundError: No module named 'yaml'
[>] Checking Jupyter engine render....OK
