### ISSUE TITLE
Create og:image:alt from fig-alt

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#10864]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/10857

<div type='discussions-op-text'>

<sup>Originally posted by **leofontenelle** September 21, 2024</sup>
### Description

I missed this feature when I was working on my Quarto blog. [Documentation says](https://quarto.org/docs/websites/website-tools.html#preview-images) the OpenGraph preview image can be picked from the page content by adding the `preview-image` to an image. It works!

It would be even better if this feature also reused the image's `fig-alt` as the `og:image:alt`, so that I don't have to copy and paste the alternative text into the YAML header for every single blog post.

I guess this is not exactly a bug report, but I'll add steps to reproduce:

```bash
quarto create project website mysite
```

The `_quarto.yml`:

```yaml
project:
  type: website

website:
  title: "Test"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

The `about.qmd`:

```qmd
---
title: "About"
---

About this site

![](https://quarto.org/quarto.png){fig-alt="Quarto logo" .preview-image}
```

The resulting HTML file:

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.11">

<!-- snip -->

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="About – Test">
<meta property="og:description" content="">
<meta property="og:image" content="https://quarto.org/quarto.png">
<meta property="og:site_name" content="Test">
</head>

<body class="nav-fixed">

<!-- snip -->

<p>About this site</p>
<p><img src="https://quarto.org/quarto.png" class="preview-image img-fluid" alt="Quarto logo"></p>

<!-- snip -->

</body></html>
```

I guess I wanted was the same but with an added

```html
<meta property="og:image:alt" content="Quarto logo">
```

Thanks!</div>
