### ISSUE TITLE
website toc no number section

### ISSUE THREAD

**Issue by Liripo** [quarto-dev/quarto-cli#1089]
Hello Developer:
yaml settings are as follows, but in the web site when toc no number, while a single document will show the number.
```
format: 
  html:
    toc: true
    number-sections: true
```

![image](https://user-images.githubusercontent.com/54770415/172373521-47dd2411-3e0b-4399-a14f-ac9cf51499fd.png)

![image](https://user-images.githubusercontent.com/54770415/172374780-6742838d-014c-4393-9d65-de2a4a0bb103.png)
