### ISSUE TITLE
Version 0.9.536 for Mac OS do not display the author information specified in the yaml

### ISSUE THREAD

**Issue by ManuelSpinola** [quarto-dev/quarto-cli#1090]
Dear list members,

The last version 0.9.536 for Mac OS do not display the author information specified in the yaml.

```
---
title: "Visualizando datos en escala de Likert"
subtitle: Como visualizar datos en escala de Likert
image: "likert.png"
author:
  - name: Manuel Spínola
    url: http://www.icomvis.una.ac.cr/index.php/manuel
    affiliation: ICOMVIS - UNA
    affiliation-url: http://www.icomvis.una.ac.cr/
    orcid: 0000-0002-7839-1908
date: 2022-06-07
citation: true
toc: true
toc-title: Tabla de contenido
toc-location: left
toc-depth: 4
bibliography: references.bib
lang: es
draft: false
categories:
  - "Escala Likert"
  - "Visualización de datos"
---
```
