### ISSUE TITLE
Quarto Word notes-after-punctuation

### ISSUE THREAD

**Issue by bpffjl** [quarto-dev/quarto-cli#10935]
I'm trying to get more control over citations in Quarto when rendering to work, `notes-after-punctuation`. The [documentation](https://quarto.org/docs/reference/formats/docx.html#references) says that a citation should appear as a footnote, but that's not the behavior I'm seeing. 

Below is my YAML header. 

```
---
title: "testing citations"
format: docx
bibliography: references.bib
link-citations: true
notes-after-punctuation: false
editor: 
  markdown: 
    wrap: sentence
---
```

This is the results I'm seeing:

![image](https://github.com/user-attachments/assets/1f6a966b-6e58-4f80-95c9-72dd1481a090)

I'm expecting that the reference would appear as a footnote. What am I missing?
