### ISSUE TITLE
figure alignment not honored in all layouts

### ISSUE THREAD

**Issue by ericpgreen** [quarto-dev/quarto-cli#10943]
### Bug description

Figures appear left aligned when setting column: page AND fig-align: center.

Originally posted [here](https://forum.posit.co/t/figure-alignment-not-honored-in-all-layouts/191574). Asked to open an issue.

### Steps to reproduce

````
---
title: "Test"
format:
  html: 
    embed-resources: true
    smooth-scroll: true
    theme: cosmo
    fontcolor: black
    toc: true
    toc-expand: 2
    toc-title: Contents
    toc-location: left
    toc-depth: 3
    number-sections: true
    number-depth: 3
---

## Page

This aligns left to page, despite setting fig-align.

```{r}
#| label: fig-1
#| fig-cap: "A caption." 
#| column: page
#| fig-align: center

plot(mtcars)
```

## Not specified

This aligns center in main

```{r}
#| label: fig-2
#| fig-cap: "A caption." 

plot(mtcars)
```
````

### Expected behavior

Center alignment

### Actual behavior

Left alignment

### Your environment

R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1

### Quarto check output

Quarto 1.5.56

**Comment by ericpgreen** [comment]
I didn't think so, but was just trying to find a solution. Thanks @cscheid

**Comment by Lauler** [comment]
This bug applies to all [article layouts](https://quarto.org/docs/authoring/article-layout.html), not just `.column-page` @cscheid . 

Users need to use `justify-self` in order to apply alignment on `grid-column` grid items. 

For anyone who is wondering how to default to center alignment instead, add the following to your styles.css: 

```css
.quarto-figure-center .column-page-inset,
.quarto-figure-center .column-page,
.quarto-figure-center .column-screen-inset,
.quarto-figure-center .column-screen {
    justify-self: center;
}
```

Ideally the advice in the documentation to use `fig-align` should work regardless of whether the image is in the regular body or in a `grid-column` layout.
