### ISSUE TITLE
[IPKernelApp] ERROR | No such comm target registered: quarto_kernel_setup

### ISSUE THREAD

**Issue by ngocanhk27** [quarto-dev/quarto-cli#10960]
### Bug description

I encounter this error message: **ERROR: SyntaxError: Unexpected token '', ""... is not valid JSON** when trying to render a simple qmd document. 

### Steps to reproduce
````
 ---
title: "NUMPY 2"
date: "9/22/2023"
date-modified: "9/23/2024"
toc: true 
toc-location: left 
format: 
  html:
    code-fold: true
categories:  

  - PYTHON
---
# Introduction

# References
````

### Your environment

RStudio-2024-09.0

### Quarto check output

````
 Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2019

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12 (Conda)
      Path: /Users/nguyenngocanh/opt/anaconda3/bin/python
      Jupyter: 5.7.2
      Kernels: julia-1.10, julia-1.9, python3, jupyter_matlab_kernel

(|) Checking Jupyter engine render....[IPKernelApp] ERROR | No such comm target registered: quarto_kernel_setup
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
````
