### ISSUE TITLE
Undefined control sequence when render to pdf

### ISSUE THREAD

**Issue by chrissikath** [quarto-dev/quarto-cli#11016]
### Bug description

```
---
title: "Data quality assessment by sample clustering/visualization"
author: "Fraunhofer IZI, Christina Kuhn"
date: "09/26/2024"
format:
  pdf:
    toc: true
---
``` 

### Expected behavior

I want  to generate a pdf report. 

### Actual behavior

```
---
title: "Data quality assessment by sample clustering/visualization"
author: "Fraunhofer IZI, Christina Kuhn"
date: "09/26/2024"
format:
  pdf:
    toc: true
--- 
```

`quarto render my_script.qmd --to pdf`

leads to:

```
ERROR: 
compilation failed- error
Undefined control sequence.
l.180 {\centering \pandocbounded
                                {\includegraphics[keepaspectratio]{sample_cl... 

see sample_clustering.log for more information.

```

### Your environment

- IDE VSCode
- Ubuntu 20.04.6 LTS

### Quarto check output

```
Quarto 1.5.55
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.1: OK
      Dart Sass version 1.58.3: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.55
      Path: /homes/olymp/christina.kuhn/.conda/envs/car-flow/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2019

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.14 (Conda)
      Path: /homes/olymp/christina.kuhn/.conda/envs/car-flow/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /homes/olymp/christina.kuhn/.conda/envs/car-flow/lib/R
      LibPaths:
        - /homes/olymp/christina.kuhn/.conda/envs/car-flow/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK

```
