### ISSUE TITLE
Feature request: Custom start for arabic cross reference numbering scheme

### ISSUE THREAD

**Issue by maptv** [quarto-dev/quarto-cli#11038]
It would be great to add the ability to set the starting point for the arabic cross reference numbering scheme: https://quarto.org/docs/authoring/cross-reference-options.html#numbering

This is already possible for all of the other cross reference numbering schemes.

The two use cases for this would be to start a new document with zero-based numbering and to continue the numbers from an existing document in a subsequent document:

```yaml
---
title: "New document with zero-based numbering"
crossref:
  labels: arabic 0
---
```

```yaml
---
title: " Continuation to a document with X figures, Y tables, and Z code listings"
crossref:
  fig-labels: arabic X
  tbl-labels: arabic Y
  lst-labels: arabic Z
---
```

I can volunteer to work on a pull request if someone could direct me to the place where the cross reference numbering logic lives.
