### ISSUE TITLE
Manuscripts -- `notebooks:` mask `render:` property in _qarto.yml

### ISSUE THREAD

**Issue by LGraz** [quarto-dev/quarto-cli#11084]
### Bug description

There is a very weird behaviour in Manuscripts. Consider the following `_quarto.yml` file

```yml
project:
  type: manuscript
  execute-dir: project
  render:
    - "notebooks/analyse_hypothesis.Qmd"

manuscript:
  article: index.qmd
  # notebooks:
  #   - notebook: notebooks/cars-plot.Qmd
  #     title: "hypothesis analysis"
  #     download-url: notebooks/cars-plot.Qmd
```
currently `notebooks/analyse_hypothesis.Qmd` and `index.qmd` are rendered. If I uncomment the notebooks section then `notebooks/analyse_hypothesis.Qmd` is no longer rendred  (despite mentioning it explicitly).

---
**side note**: when I manually execute `quarto render notebooks/analyse_hypothesis.Qmd --to html` it gets executed in the directory `notebooks` which contradicts the `execute-dir: project`. Is this expected behavior?

### Your environment

Quarto: 1.5.57

### Quarto check output

```
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.7
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/lukas/Work/LentilOatMixedCropping/renv/library/linux-arch-rolling/R-4.4/x86_64-pc-linux-gnu
        - /home/lukas/.cache/R/renv/sandbox/linux-arch-rolling/R-4.4/x86_64-pc-linux-gnu/9a444a72
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```
