### ISSUE TITLE
Quarto doesn't jump to a new line when we have multiple authors

### ISSUE THREAD

**Issue by fabriciofx** [quarto-dev/quarto-cli#11119]
Hi! I think i found a bug in Quarto when I'm trying put multiple auhtors. Example:

```
title: "Some title"
authors:
  - name: "Author One"
  - name: "Author Two"
  - name: "Author Three"  
date: "`r format(Sys.Date())`"
output: pdf_document
```

Desired output:

     Some title

    Author One
    Author Two
    Author Three

I'm using Quarto 1.5.57.
