### ISSUE TITLE
Multiple rendered html Quarto Books cannot be put under a single local web server.

### ISSUE THREAD

**Issue by mickeykawai** [quarto-dev/quarto-cli#11115]
### Bug description

Upon request by cderv at Posit Community (https://forum.posit.co/t/is-there-an-easy-way-or-option-to-host-multiple-rendered-html-quarto-books-under-a-single-local-web-server/186888/4), I re-post the issue here. 

Bug: 
- Multiple rendered html Quarto Books cannot be set under a single local web server by default.

Workaround: 
- Add a post-render script in yml file and put the script by hand, to add `<base href="...">` tag during Render HTML (e.g. `<base href="http://localhost:3000/mybook2/">`.
  - Or just modifying the `index.html` by hand to add the tag manually is enough. 

### Steps to reproduce
- The `mybook1` and `mybook2` contents are uploaded as `Archive.zip` below. 

##### `mybook1` (where default QuartoBook behavior does not work)
- On RStudio.app on macOS, File > New Project ... > New Directory > Quarto Book > `mybook1` (at any directory you like). 
- Open `index.qmd`
- Hit Render (Render HTML). 

##### `mybook2` (where my script is added and `_quarto.yml` is modified to include `project: post-render: ` before Render)
- On RStudio.app on macOS, File > New Project ... > New Directory > Quarto Book > `mybook2` (at any directory you like). 
- Add `scripts/add-base.sh` in the `mybook2/` directory. 
  - `add-base.sh`: 
  
```
#!/bin/bash
mv _book/index.html _book/index.orig.html
name=$(basename "$(pwd)")
perl -spe 's!\<head\>\n!\<head\>\n\<base href\="http://localhost:3000\/$name/">\n!;' -- -name=$name _book/index.orig.html > _book/index.html
ln -s -f "$(pwd)"/_book ~/Sites/$name
#cd ~/Sites
#npx serve .
#http://localhost:3000
```

- Open `_quarto.yml`
  - Add following two lines after `type: book` (l.2)

  ```
    post-render: 
      - scripts/add-base.sh
  ```

  - Whole `quarto.yml` is now as follows.  

    ```
    project:
      type: book
      post-render: 
        - scripts/add-base.sh
    
    book:
      title: "mybook2"
      author: "Norah Jones"
      date: "10/19/2024"
      chapters:
        - index.qmd
        - intro.qmd
        - summary.qmd
        - references.qmd
    
    bibliography: references.bib
    
    format:
      html:
        theme: cosmo
      pdf:
        documentclass: scrreprt
    ```

- Open `index.qmd`
- Hit Render (Render HTML). 

##### Difference between the original `index.html` and the one post-rendered. 
```
% diff index.html index.orig.html 
3d2
< <base href="http://localhost:3000/mybook2/">
```

##### Soft link the two quarto books in html to `~/Sites/` (where you set up web server document root). 

```
mkdir ~/Sites
cd ~/Sites
ln -s <your_mybook1_topdir>/_book mybook1
ln -s <your_mybook1_topdir>/_book mybook2
# It is not necessary to do these `ln -s` commands by hand if you used above mentioned `add-base.sh` file as it also does this step. 
```

```
~/Sites % ls -lh
total 0
lrwxr-xr-x  1 <account>  staff    57B Oct 19 17:46 mybook1 -> <working_dir>/mybook1/_book
lrwxr-xr-x@ 1 <account>  staff    57B Oct 19 17:45 mybook2 -> <working_dir>/mybook2/_book
~/Sites % 
```

##### Examine on browser. 
- Start web server

```
cd ~/Sites
npx serve .
# npx serve /Users/<your_account>/Sites
```
- Open browser
- Enter url as `http://localhost:3000`
- Click the link of `mybook1` and `mybook2`. 

[Archive.zip](https://github.com/user-attachments/files/17444493/Archive.zip)

### Expected behavior

HTML is formatted correctly with JS search functionality working. 
![Image](https://github.com/user-attachments/assets/50128aec-1dd6-4083-a58a-58338b52b969)
![Image](https://github.com/user-attachments/assets/6ade7447-b5dc-4fa5-8268-c941c8c15b21)

### Actual behavior

HTML is not formatted correctly. 

![Image](https://github.com/user-attachments/assets/2a1b0b8b-d278-4805-828c-57d21c646843)

### Your environment

- macOS Sonoma 14.7 (on M2mac)
- RStudio.app Version 2024.09.0+375 (2024.09.0+375)
- R.app R version 4.4.0 (2024-04-24) -- "Puppy Cup"
- Chrome.app Version 129.0.6668.101 (Official Build) (arm64)

### Quarto check output

```bash
$ quarto check
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/<account_name>/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
      Jupyter: 5.5.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.47
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

$ 
```

**Comment by mcanouil** [comment]
You need to set `site-url` to the root of your book: https://quarto.org/docs/websites/website-tools.html#social-metadata

If you don't set it, then the default is to take the root of the domain which of course will break your site/book if it is not at the root.

**Comment by mickeykawai** [comment]
I tried two yml as below but either does not work. 

### Procedure. 
- I added the `site-url: <url>` just below the `book:` in yml. 
  - This modification of yml by hand is done before hitting Render HTML. 
  - Other steps are the same as the one for `mybook1` described as above. 
  - The `mybook3` and `mybook4` contents are attached as `Archive 2.zip` below. 

### `mybook3` where `site-url: http://localhost:3000/mybook3` is added. 

- `_quarto.yml`

```
project:
  type: book

book:
  site-url: http://localhost:3000/mybook3
  title: "mybook4"
  author: "Norah Jones"
  date: "10/19/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

### `mybook4` where `site-url: http://localhost:3000` is added. 

- `_quarto.yml`

```
project:
  type: book

book:
  site-url: http://localhost:3000
  title: "mybook4"
  author: "Norah Jones"
  date: "10/19/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

### Results

```
~/Sites % ls -lh
total 0
lrwxr-xr-x  1 mickey  staff    57B Oct 19 17:46 mybook1 -> <working_dir>/mybook1/_book
lrwxr-xr-x@ 1 mickey  staff    57B Oct 19 17:45 mybook2 -> <working_dir>/mybook2/_book
lrwxr-xr-x  1 mickey  staff    57B Oct 19 18:38 mybook3 -> <working_dir>/mybook3/_book
lrwxr-xr-x  1 mickey  staff    57B Oct 19 18:41 mybook4 -> <working_dir>/mybook4/_book
~/Sites % 
```

![Image](https://github.com/user-attachments/assets/c3031499-8e46-489b-8922-33caba9574b5)
![Image](https://github.com/user-attachments/assets/90e086fb-1f9a-4b3e-923e-9014cd711204)

[Archive 2.zip](https://github.com/user-attachments/files/17444590/Archive.2.zip)

**Comment by mcanouil** [comment]
I cannot reproduce.
Note that your workflow is not really simple.

1. `quarto create project book Issue-11115 Issue-11115`
2. Modify `_quarto.yml`:
   ```yml
       project:
     type: book
     output-dir: ../docs/subfolder
   
   book:
     site-url: subfolder
     title: "subfolder"
     author: "Norah Jones"
     date: "10/19/2024"
     chapters:
       - index.qmd
       - intro.qmd
       - summary.qmd
       - references.qmd
   
   bibliography: references.bib
   
   format:
     html:
       theme: cosmo
     pdf:
       documentclass: scrreprt
   ````
3. `quarto render`
4. Setup GitHub Pages to deploy the site. 
   ![Image](https://github.com/user-attachments/assets/a31ed5ee-b3ac-4812-ba46-3494457d7e00)
5. Check out the perfectly rendered book: https://m.canouil.dev/quarto-cli-11115/subfolder/

Repository: https://github.com/mcanouil/quarto-cli-11115

**Comment by mcanouil** [comment]
Even with a slightly different configuration and multiple books, it runs just fine when deployed: https://github.com/mcanouil/quarto-cli-11115/tree/multiple-books

**Comment by mickeykawai** [comment]
Thank you, the yml that you showed worked perfectly!: 

- Add `site-url: mybook7`, not `site-url: http://localhost:3000/mybook8`. 
- Change output dir by adding `output-dir: ` at `project:` such that rendered dir should be output directly under the desired web server document root. 

```
project:
  type: book
  output-dir: /Users/<account>/Sites/mybook7

book:
  site-url: mybook7
  title: "mybook7"
  author: "Norah Jones"
  date: "10/19/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

For future self note, softlink approach does not work, despite the file contents are the same. That is, `output-dir: <document_root>/mybook7` is mandatory. (It might possibly be because of CORS security issue of recent browser/javascript...)

Also I wonder some detailed documentations elsewhere might had been helpful to fix this by myself, in addition to the example `site-url: https://example.com` described [there](https://quarto.org/docs/websites/website-tools.html#social-metadata). 

P.S. The reprex you made on github repo is helpful for me to learn how to do on github. I didn't understand the phrase "a reprex on github repo" that cderv suggested on posit.. Thank you again for taking time to clarify this.
