### ISSUE TITLE
Quarto improperly merges metadata for Lua filter use

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#11139]

**Comment by cscheid** [comment]
## Repro

### _quarto.yml

````
... # default project metadata from `quarto create project website`

mymeta:
  key1: projectwise_value
  key2: projectwise_value_2
````

### index.qmd

````
---
title: "This is the page title"
filters:
  - test.lua
mymeta:
  key1: projectwise_value_override
---

Hello.
````

## Discussion

The problem is here:

https://github.com/quarto-dev/quarto-cli/blob/740829733499855335a7861e3c4f1333a09db45d/src/command/render/pandoc.ts#L994-L1015

In the repro above, we have the following values for pandocMetadata and engineMetadata:

```
pandocMetadata:
  ...
  title: "This is the page title"
  mymeta:
    key1: "projectwise_value_override"
    key2: "projectwise_value_2"

engineMetadata:
  title: "This is the page title"
  mymeta:
    key1: "projectwise_value_override"
```

The code exists so that if an execution engine emits metadata, we can merge it appropriately against the metadata that we send to Pandoc. (Because of reasons described elsewhere, we can't just send the YAML metadata to Pandoc.)

The problem, then, is how to merge the data in engineMetadata into pandocMetadata. If we simply replace values (the current behavior), then we run into this bug. If we instead use mergeConfigs (which is more or less the _intended_ behavior), then merged string values become arrays. That's clearly wrong as well.

This is quite annoying, and I don't think we can fix it well at all in the present state of the codebase.
