### ISSUE TITLE
Greek symbols in dataframe column heading - Quarto output

### ISSUE THREAD

**Issue by konnerhorton** [quarto-dev/quarto-cli#1118]
Dataframe headings (produced from a Jupyter/python code cell) show greek symbols:

![Screenshot 2022-06-09 124555](https://user-images.githubusercontent.com/95249835/172901275-97e3338d-d978-4df7-b21c-fb731576232e.jpg)

When I use Quarto to render the pdf, column headings are shown with the Latex command:

![Screenshot 2022-06-09 124630](https://user-images.githubusercontent.com/95249835/172901335-c8eb09f2-199e-4eb6-9995-5c71bcf5347a.jpg)

I would like the Quarto output to display the Greek symbols. Do you know how I can do this?

Quarto version: 0.09.495

**Comment by jjallaire** [comment]
Could you provide a minimal reproducible example for us then we can take a look?

**Comment by konnerhorton** [comment]
Input:
```
title: "Concrete Jacking Pipe Maximum Jacking Force - Staheli Method"
subtitle: "Proj. # - Project Name"
title-block-style: default
execute:
  echo: false
format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: false
```

```
import pandas as pd
data = {'$\sigma$': [3, 2, 1, 0],
        '$\sigma^{\prime}_v$': ['a', 'b', 'c', 'd']}
pd.DataFrame.from_dict(data)
```
Notebook output:
![image](https://user-images.githubusercontent.com/95249835/172907858-10830861-f381-46c0-83ed-287c330bded4.png)


Quarto pdf output:
![image](https://user-images.githubusercontent.com/95249835/172908636-a1a2de20-cb7c-4d9f-9525-e8d66091e891.png)
