### ISSUE TITLE
Allow `brand` content directly in document metadata

### ISSUE THREAD

**Issue by gordonwoodhull** [quarto-dev/quarto-cli#11192]
It would be nice not to need a separate `brand.yml` file but be able to use those features in a standalone document, by embedding them in the metadata.

E.g.

```yaml
---
title: Hello
brand:
  color:
    palette:
      blue: "#718190"
    foreground: blue
---
```
