### ISSUE TITLE
Bug in postBuild shebang line

### ISSUE THREAD

**Issue by she3o** [quarto-dev/quarto-cli#11213]
### Bug description

The shebang line in `postBuild` generated by `quarto use binder` is:
```bash
#!/usr/bin/env bash -v
```

On mybinder.org, I get this log:

```yaml
Step 62/67 : RUN ./postBuild
 ---> Running in 3084941ca008
[91m/usr/bin/env: â€˜bash -vâ€™[0m[91m: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
[0m ---> Removed intermediate container 3084941ca008
The command '/bin/sh -c ./postBuild' returned a non-zero code: 127
```

### Steps to reproduce

```bash
$ # git clone 'http://github.com/she3o/whyR'

$ quarto use binder
...

$ git add apt.txt postBuild runtime.txt
...

$ # Go to mybinder.org
# Paste Github URL
# press launch
# on step 62, the build fails
```

### Expected behavior

binder images should be built successfully.

### Actual behavior

```yaml
Step 62/67 : RUN ./postBuild
 ---> Running in 3084941ca008
[91m/usr/bin/env: â€˜bash -vâ€™[0m[91m: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
[0m ---> Removed intermediate container 3084941ca008
The command '/bin/sh -c ./postBuild' returned a non-zero code: 127
```

### Your environment

```bash
$ uname -a
Linux HOSTNAME 6.10.11-skylake-xanmod1-1 #1 SMP PREEMPT_DYNAMIC Fri, 20 Sep 2024 13:11:19 +0000 x86_64 GNU/Linux

$ nvim --version
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info
```

### Quarto check output

```yaml
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/she3sha3y/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```
