### ISSUE TITLE
banner and sidebars

### ISSUE THREAD

**Issue by xtimbeau** [quarto-dev/quarto-cli#11286]
### Bug description

When using a sidebar menu in hybrid navigation without bread-crumbs, the title of the content referenced in the sidebar is not placed inside the banner in mobile width.
Using bread-crumbs brings the correct behavior.

### Steps to reproduce

`_quarto.yml`
````yml
project:
  type: website

website:
  title: "banner"
  bread-crumbs: false 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:sidebar
      
  sidebar:
    - id: sidebar
      title: sidebar
      contents: 
        - text: content1
          file: content1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    title-block-banner: 966-600x200.jpg
    

editor: visual
````

ìndex.qmd``
````qmd
---
title: "index"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{r}
1 + 1
```
````

`content1.qmd``
````qmd
---
title: "content1"
---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

```{r}
1 + 1
```
````

### Expected behavior

The title for `content1.qmd` should be inside (above) the banner.

### Actual behavior

![Image](https://github.com/user-attachments/assets/d3aad4cc-4671-48e6-9fa0-54121e10e19c)

### Your environment

RStudio 2024.09.1 396
R 4.4.1
MacOS 15.1

### Quarto check output

```bash
Quarto 1.6.32
[✓] Checking environment information...
      Quarto cache location: /Users/xt/github/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.32
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/local/bin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```
