### ISSUE TITLE
Text is blurry for Reveal.js when `incremental: true` in Safari

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto-cli#11297]
When creating a Reveal.js presentation with `incremental: true`, text is blurry in Safari:

![Image](https://github.com/user-attachments/assets/2a84e11d-3c00-45ac-92e1-b606ce921d53)

This is not the case in Chrome:

![Image](https://github.com/user-attachments/assets/a1cb39c8-bb4c-4532-bdda-a0a244b1decd)

Here's an example to reproduce:

```
---
title: "Test"
format:
  revealjs:
    theme: default
    incremental: true
---

## Quick intro

- First bullet point
- Another bullet point
- Yet another bullet point
```

Run `quarto` on this example and open the HTML in Safari and Chrome. Note that the text is rendered perfectly OK when `incremental: False` in Safari. I'm not sure if this is a Quarto issue, but at least in the [Reveal.js demo](https://revealjs.com/#/fragments/0), fragments (text rendered incrementally) are rendered correctly in Safari.
