### ISSUE TITLE
embedded brand metadata does not show logo in html output

### ISSUE THREAD

**Issue by gordonwoodhull** [quarto-dev/quarto-cli#11309]
This does not show the logo in html, but it works for typst:

#### logo-embedded.qmd
````
---
title: logo across formats
format:
  html: default
  typst:
    keep-typ: true
brand:
  logo:
    images:
      quarto:
        path: quarto.png
        alt: quarto logo
      posit:
        path: posit-logo-2024.svg
        alt: posit logo
    medium: quarto
    large: posit
---

{{< lipsum 4 >}}
````

#### _quarto.yml
````
project:
  type: website
website:
  sidebar:
    style: "docked"

    contents: []
````

However if I move `_brand.yml` to its own file

#### _brand.yml
````
logo:
  images:
    quarto:
      path: quarto.png
      alt: quarto logo
    posit:
      path: posit-logo-2024.svg
      alt: posit logo
  medium: quarto
  large: posit
````

#### logo-embedded.qmd
````
---
title: logo across formats
format:
  html: default
  typst: default
---

{{< lipsum 4 >}}
````

This displays the logo in both formats.

(I have a feeling I have created some cross-format compatibility bugs by allowing logo to be an object for typst, ran into this bug on the way.)
