### ISSUE TITLE
Access denied with RSS-feed when blog listing is not index.html

### ISSUE THREAD

**Issue by AlbertRapp** [quarto-dev/quarto-cli#1131]
### Bug description

# Problem description
I am trying to include an RSS feed for my blog listing. This works all fine with the blog setup that you get when you create a new quarto blog from within RStudio. But it breaks if I tweak the landing page. Then, I get

```
## Error 1

ERROR: PermissionDenied: Zugriff verweigert (os error 5), rename 'C:\Users\Alber\Desktop\feed-test\site_libs' -> 'C:\Users\Alber\Desktop\feed-test\_site\site_libs'

## Error 2

PermissionDenied: Zugriff verweigert (os error 5), stat 'C:\Users\Alber\Desktop\feed-test\_site\blog.feed-full-staged'
```

Note that I have tried operating with admin rights but that did not help. Let me describe a minimal example.

# Minimal example that works

Create new quarto blog via RStudio. Then modify `index.qmd` and `_quarto.yml` as described in [Quarto docs](https://quarto.org/docs/websites/website-blog.html#rss-feed) to include an RSS feed.

### index.qmd

```
---
title: "feed-test"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  feed: true
page-layout: full
title-block-banner: true
`---`
```

### _quarto.yml 

```
project:
  type: website

website:
  title: "feed-test"
  site-url: https://www.myblogexample.io
  description: 'Great blog'
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: blog.xml 
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

``
``` 

# Changes that break the blog

Now, I want my blog to have a landing page that is different from the blog listing. So, I renamed

* `index.qmd` > `blog.qmd`
* `about.qmd` > `index.qmd`

This causes `blog.qmd` to not render anymore with one of the above error. Sometimes it renders without a problem but accessing `blog.html` then errors out with the second error (above).

# System Information

### OS

I am using Windows 10 

### R

```
R version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
```

### RStudio

```
RStudio
2022.02.3 Build 492
© 2009-2022 RStudio, PBC
"Prairie Trillium" Release (1db809b8, 2022-05-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
```

### Quarto

```
      Version: 0.9.566
      Path: C:\Users\Alber\AppData\Local\Programs\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.8.2
      Path: C:/Users/Alber/AppData/Local/Programs/Python/Python38/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.0.3
      Path: C:/PROGRA~1/R/R-40~1.3
      LibPaths:
        - C:/Users/Alber/Documents/R/win-library/4.0
        - C:/Program Files/R/R-4.0.3/library
      rmarkdown: 2.13

[>] Checking Knitr engine render......OK
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by dragonstyle** [comment]
Hi,

I'm sorry that you've run into these errors. I haven't been able to reproduce any of these issues with a clean blog or by renaming files. In general, permission issues when rendering are pretty unexpected. The fact that you're seeing them not just when trying to generate a feed, but also when trying to copy `site_libs` into the output `_site` directory is definitely unexpected. Is there anything that could be causing more general permissions issues when rendering?

Are you able to reproduce this issue on a different machine?

**Comment by jjallaire** [comment]
If one render was done w/ sudo privileges then it could leave subsequent renders unable to write over the files from the first render. I would agree w/ @dragonstyle that this is unlikely to be an issue w/ Quarto as we don't really do anything with file permissions (reading or writing).

**Comment by AlbertRapp** [comment]
I've just tested this on an Ubuntu 20.04 system. There, I cannot reproduce this issue either. So, maybe it is a Windows thing. Nevertheless, I can solve the problem by not rendering but previewing the website from within RStudio (after rendering the website separately of course). Even though I get rid of the permission denied error, this feels like odd behavior. So, on my Windows machine I have investigated this behavior a bit further.

During the building process, the files `blog.feed-full-staged` and `blog-listing.json` are created in the project's main directory. Shortly after the files are created, they disappear again. They cannot be found in the `_site` or in the `site_libs` directory either.
At this point, everything is ok. The landing page loads just fine and if I wish, I can access `MY_URL/blog.xml` via my browser.

The problems begin when I access the listing page of the blog posts. I once again get the error
```
PermissionDenied: Zugriff verweigert (os error 5), stat 'C:\Users\Alber\Desktop\feed-test\_site\blog.feed-full-staged
```
and what is strange is that the files `blog.feed-full-staged` and `blog-listing.json` reappear in my main directory. From within RStudio, I cannot access `blog.feed-full-staged` because it is in use by another process. Opening it with notepad++ reveals that it contains the content of `blog.xml`. Clicking `Preview Website` in RStudio will remove the two files from my main directory once I access the blog listing page (but not before). Then everything seems to be in order.

Just a rudimentary guess: Could it be that `Render Website` in RStudio misses some final steps relating to the two files (or blocks the two files so that Windows cannot move them properly) and `Preview Website` concludes these final steps?

**Comment by drbenvincent** [comment]
I believe I am running into a very similar issue. I changed my site in a similar way so that there is a static home page (`index.qmd`) and the the blog post listing page is now `posts.qmd`. 

## index.qmd
So now the home page is a static page like this:
```
---
image: img/profile.png
about:
  template: marquee
---

# My home page

Blar blar
```

## posts.qmd
And there is a separate blog post listing file, this is it in it's entirety:
```
---
title: "Blog"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  feed: false
page-layout: full
title-block-banner: true
---
```

Now, when I change to `feed: true` and preview (or try to publish with `quarto publish gh-pages`), then I get an error
```
[7/8] posts.qmd
ERROR: Not a png file
```

Not an expert on RSS feeds, but it certainly seems like there's an issue with generating the RSS feed when the the blog listing is not `index.html`.
