### ISSUE TITLE
Improve line and border color on webpages when brand is used

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#11500]
### Steps to reproduce

Preview this webpage project: `index.qmd` and `_quarto.yml`

`index.qmd`:
````md
---
title: "lines"
toc: true
brand:
  color:
    background: "#222"
    foreground: "#ee7"
    primary: "rgb(238, 163, 0)"
---

## Section

```{.r filename="Filename"}
# CODE
```

## Another section
````

`_quarto.yml`:
````md
project:
  type: website

website:
  sidebar:
    contents:
      - href: index.qmd
        text: Home
````

### Expected behavior

Borders and lines should probably inherit from `foreground`, or the element they are surrounding.

### Actual behavior

![Image](https://github.com/user-attachments/assets/653ab884-1d77-44e7-a185-4e3a39a249d6)
![Image](https://github.com/user-attachments/assets/4fdd8958-f2a0-43a6-b475-dfa4d4c89b7b)

Lots of lines and borders aren't a great color by default:

* TOC border on in-active sections
* Border around search box
* Line under `<h2>` header
* Border around a code cell
* Line under the sidebar when it is collapsed on a small screen

Some of these can be controlled by `$table-border-color`, e.g:
````
brand:
  color:
    background: "#222"
    foreground: "#ee7"
    primary: "rgb(238, 163, 0)"
  defaults:
    bootstrap:
      defaults:
        table-border-color: black
````
But, it's unintuitive to use something called `table-border-color` (especially since it doesn't actually change the color in `<table>` elements).

### Quarto check output

```bash
$ quarto check
Quarto 99.9.9
[✓] Checking environment information...
      Quarto cache location: /Users/charlottewickham/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      commit: bf93178346e68f721714ef4c7f792943b4d80f6e
      Path: /Users/charlottewickham/Documents/posit/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.03.13
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/charlottewickham/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: /Users/charlottewickham/Documents/posit/quarto-web/.venv/bin/python
      Jupyter: 5.7.2
      Kernels: julia-1.10, ark, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources
      LibPaths:
        - /Users/charlottewickham/Library/R/arm64/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```
