### ISSUE TITLE
Allow to configure `repo-actions` at directory level

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#11563]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/11562

<div type='discussions-op-text'>

<sup>Originally posted by **mark-andrews** November 28, 2024</sup>
### Description

In a directory level `_metadata.yml`, we can have a new `repo-url`  key that overrides the `website/repo-url` that is set in the top level `_quarto.yml`. See https://github.com/quarto-dev/quarto-cli/issues/4668 and https://github.com/quarto-dev/quarto-cli/commit/3870d39db199d81de65e06e6055b0a49e4309f05 .

However, it seems like I can not do the same thing with `repo-actions`. In other words, I can not set a `repo-actions` value in a directory level `_metadata.yml` that overrides the value set in `website/repo-actions` in `_quarto.yml`. For example, if my `_quarto.yml` has

```yml
website:
  repo-url: "https://github.com/foobar/barfoo"
  repo-actions: [source, edit]
````

if I have the following in a directory `_metadata.yml`

```yml
website:
  repo-url: "https://github.com/foobar/bazfoo"
  repo-actions: [source]
````

then the URL for the GitHub repo on pages in that sub-directory will change from `barfoo` to `bazfoo`, but the actions will not have from view source and edit source to just view source.

Ultimately what I would like is to have pages in some subdirectories to have the button to view the source code on GitHub, and pages in some other subdirectories to not have any buttons to link to the source code on GitHub, which I am trying to do by setting `repo-actions: none` in `_metadata.yml` in some directories.

Is there a way to to have directory level different values of `repo-actions`, or is there some other way of turning off these repo actions in all pages in some subdirectories?
</div>

**Comment by cderv** [comment]
We allow to opt out at document level using `repo-actions: false` but we don't offer to configure it differently
https://github.com/quarto-dev/quarto-cli/blob/37bc223282d9e239d1245575100c7dbf3de74a52/src/project/types/website/website-navigation.ts#L642-L660

Possibly this could be done too

**Comment by coatless** [comment]
I think this might be related to merging the same YAML key dropping data. E.g.

**_quarto.yml**
```yml
custom-code:
   my-numbers: [1, 2, 3]
   enable-output: true
```

**document.qmd**

```md
---
title: My Document
custom-code:
   enable-output: false
---
```

Causes `my-numbers: [1, 2, 3]` to be unset

I've seen it before as well. 

https://github.com/quarto-dev/quarto-web/pull/924#issuecomment-1939945110
