### ISSUE TITLE
Brand documentation should include information about how `brand` interacts with `theme`

### ISSUE THREAD

**Issue by gadenbuie** [quarto-dev/quarto-cli#11604]
### What would you like to do?

Report an issue on quarto.org

### Description

Originally pointed out here: https://github.com/posit-dev/brand-yml/issues/56

The brand documentation at https://quarto.org/docs/authoring/brand.html should include information about how `theme` and `brand` interact, in particular to describe the difference between the following three scenarios:

```yaml
format:
  html:
    theme: yeti

format:
  html:
    theme:
      - brand
      - yeti

format:
  html:
    theme:
      - yeti
      - brand
```
