### ISSUE TITLE
Sidebar configuration either errors or is intuitive

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#11641]
### Bug description

I have the following folder structure for an internal project:

```
├── home
│   ├── projects
│   │   ├── foo-bar
│   │   └── baz-qux
│   └── faq
│       ├── environment-variables
│       ├── git-bash
│       ├── hidden-files
│       ├── python
│       └── conda
└── developer-guide
```

And I would like a sidebar where I have manual control of the top level but `auto` generate the contents of sub levels

---

On Windows (but not on MacOS) the following errors:

```
  sidebar:
    contents:
      - section: Software
        contents: home/projects/
```

```
ERROR: TypeError: Cannot convert undefined or null to object

Stack trace:
    at Function.keys (<anonymous>)
    at findIndexFile (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:94015:19)
    at nodesToEntries (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:93991:35)
    at sidebarItemsFromAuto (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:93919:31)
    at expandAutoSidebarItems (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:93841:37)
    at expandAutoSidebarItems (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:93860:39)
    at resolveSidebarItems (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:94873:32)
    at sidebarEjsData (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:94864:11)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async sidebarsEjsData (file:///C:/Users/USERNAME/AppData/Local/Programs/Quarto/bin/quarto.js:94848:26)

....

GET: /home/
```

---

I expected this to work but doesn't work:

```
  sidebar:
    style: docked
    contents:
      - auto: home/software/*
```

---

This is the only way I was able to get quarto to read all the files just one level deep:

```
  sidebar:
    contents:
      - href: home/index.qmd
        text: Home
      - section: Projects
        contents: home/projects/**/*
      - section: FAQ
        contents: home/software/**/*
```

I'm using the latest quarto:

```
quarto --version
1.6.39
```

### Steps to reproduce

1. quarto create project website
2. make folder structure as shown with an index.qmd file in each of them

### Expected behavior

Quarto should never error. `auto` doesn't seem to work in a sublevel. If it can't generate a sidebar, it would be nice if it could explain why. 

### Quarto check output

```
$ quarto check
Quarto 1.6.39
[>] Checking environment information...
      Quarto cache location: C:\Users\USERNAME\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.6.39
      Path: C:\Users\USERNAME\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.5 (Conda)
      Path: C:/Users/USERNAME/miniforge3/python.exe
      Jupyter: 5.7.2
      Kernels: python-localvenv, python3

(/) Checking Jupyter engine render....
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Cannot start python-localvenv kernel:

Expected folder ".venv" in notebook directory C:\Users\USERNAME\AppData\Local\Temp\quarto-session4e81de456f3f6040\bd1a910c856c0074
(or any parent directory)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(\) Checking Jupyter engine render....2024-12-09 11:12:47,291 - traitlets - ERROR - Error occurred while starting new kernel client for kernel 4ad7a9ad-7a67-47b1-b12a-ef9739c5a38c: Kernel died before replying to kernel_info


Kernel died before replying to kernel_info
[>] Checking Jupyter engine render....OK

```

**Comment by cscheid** [comment]
Agreed on all counts.

**Comment by brianthelion** [comment]
@kdheepak I could not get the following to work:

```
  sidebar:
    contents:
      - href: home/index.qmd
        text: Home
      - section: Projects
        contents: home/projects/**/*
      - section: FAQ
        contents: home/faq/**/*
```

This threw an error:
```
In file website/_quarto.yml
(line 16, columns 19--35) Key contents has value "home/projects/**/*", which must be an array of values, where each element must be at least one of: navigation-item, a string, an object
```

What actually worked was:
```
  sidebar:
    contents:
      - href: home/index.qmd
        text: Home
      - section: Projects
        contents:
          - auto: home/projects/**/*
      - section: FAQ
        contents:
          - auto: home/faq/**/*
```
Can you confirm?

**Comment by kdheepak** [comment]
This definitely works for me right now:

```
  sidebar:
    style: docked
    contents:
      - href: home/index.qmd
        text: Home
      - section: Projects
        contents: home/projects/**/*
```

**Comment by kdheepak** [comment]
To add another feature request here, I would like for more fine grained control of the sidebar in deeply nested folder structures. At work, I have a quarto page that looks something like this:

```
home
├── team-abc
│   ├── subteam-1
│   │   └── modeling-tools
│   │       └── simulation-tool-1
│   │           └── tutorial
│   └── subteam-2
│       └── modeling-tools
│           ├── simulation-tool-2
│           │   ├── developer-guide
│           │   ├── install-instructions
│           │   ├── reference
│           │   └── user-guide
│           │       ├── creating-a-project
│           │       ├── getting-results
│           │       └── visualize-results
│           └── simulation-tool-3
│               ├── api-reference
│               └── user-guide
│                   └── tutorial
└── team-xyz
    └── modeling-tools
        └── simulation-tool-4
```

I would like to have just the following show up when a user is on the `/home/` page

```
home
├── team-abc
└── team-xyz
```

but when the user is on `/home/team-abc/` I'd like a sidebar to reflect just that "team"'s structure (i.e. no elements from `team-xyz` should show up in the sidebar):

```
home
└── team-abc
    ├── subteam-1
    └── subteam-2
```

And then opening `/home/team-abc/subteam-1/modeling-tools/simulation-tool-1`, I'd like to show all the folders in `simulation-tool-2` alone.

If this would be possible AND have pattern matching + order work on a sub folder level that would be amazing.

**Comment by kdheepak** [comment]
Another feature request that I'd like to do add it is that sometimes I want to add a `revealjs` file to a folder that already contains a `index.md`, and I don't want the revealjs file to show up in the sidebar when using something like this in the `_quarto.yml` file:

```
    - title: "Resources"
      contents:
        - section: Resources
          contents: home/resources/**
```
