### ISSUE TITLE
YAML bibliographies should accept list format, currently requires a dictionary with `references`

### ISSUE THREAD

**Issue by dhimmel** [quarto-dev/quarto-cli#11656]
### Bug description

NA

### Steps to reproduce

Define the following two files.

`document.qmd`:

````qmd
---
title: "Quarto bibliography.yml references"
bibliography: bibliography.yml
---

Making a citation to citation key `osmnx` [@osmnx].
````

`bibliography.yml`:

```yaml
- id: osmnx
  DOI: 10.1016/j.compenvurbsys.2017.05.004
  type: article-journal
  title: 'OSMnx: New methods for acquiring, constructing, analyzing, and visualizing complex street networks'
  author:
  - given: Geoff
    family: Boeing
```

Run:

```
quarto render document.qmd
```

Note the logged error:

```
[WARNING] Citeproc: citation osmnx not found
```

Prepending the following to `bibliography.yml` solves the issue:

```yml
references:
```

IIRC Pandoc accepts CSL JSON (as JSON or YAML) when formatted a list of dictionaries rather than a top-level dictionary with a `references` key.

### Expected behavior

NA

### Actual behavior

NA

### Your environment

NA

### Quarto check output

NA
