### ISSUE TITLE
YAML validation appears to not be failing for closed objects

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#11666]
Minimal repro on `main`. `_quarto.yml`, note `secion` (sic):

````yml
project:
  type: website

website:
  title: "test-yaml"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    contents:
      - secion: 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



````
