### ISSUE TITLE
`background` doesn't work as a color in `revealjs` unless it's explicitly set

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#11665]
repro:

```qmd
---
title: Hello, `_brand.yml`!
brand:
  typography: 
    monospace:
      family: Inconsolata
      size: 1em
      color: foreground
      background-color: background
    base:
      family: Open Sans
    headings:
      family: Montserrat
    fonts:
      - family: Inconsolata
        source: google
      - family: Open Sans
        source: google
      - family: Montserrat
        source: google
---

## Links

Download the Positron Beta here: <https://positron.posit.co/download.html>

Docs for `_brand.yml`: <https://posit-dev.github.io/brand-yml/>, <https://quarto.org/docs/authoring/brand.html>

## Placeholder text

This is an example document with a [number](https://quarto.org) of `features` to help you come with a nicely branded document.

Duis ornare ex ac iaculis pretium. Maecenas sagittis odio id erat pharetra, sit amet consectetur quam sollicitudin. Vivamus pharetra quam purus, nec sagittis risus pretium at. Nullam feugiat, turpis ac accumsan interdum, sem tellus blandit neque, id vulputate diam quam semper nisl. Donec sit amet enim at neque porttitor aliquet. Phasellus facilisis nulla eget placerat eleifend. Vestibulum non egestas eros, eget lobortis ipsum. Nulla rutrum massa eget enim aliquam, id porttitor erat luctus. Nunc sagittis quis eros eu sagittis. Pellentesque dictum, erat at pellentesque sollicitudin, justo augue pulvinar metus, quis rutrum est mi nec felis. Vestibulum efficitur mi lorem, at elementum purus tincidunt a. Aliquam finibus enim magna, vitae pellentesque erat faucibus at. Nulla mauris tellus, imperdiet id lobortis et, dignissim condimentum ipsum. Morbi nulla orci, varius at aliquet sed, facilisis id tortor. Donec ut urna nisi.
```

`quarto render --to html` works, `quarto render --to revealjs` doesn.t

**Comment by cderv** [comment]
FWIW I can handle revealjs issue, even if they are brand related.

**Comment by cderv** [comment]
This is the error with revealjs
````
quarto render index.qmd --to revealjs
ERROR: Theme file compilation failed:

Error: $color: background is not a color.
     ╷
2195 │   color: rgb(red($code-block-bg), green($code-block-bg), blue($code-block-bg));
     │              ^^^^^^^^^^^^^^^^^^^
````

When I look into the SCSS saved from `QUARTO_SAVE_SCSS` I see 
```scss
/* typography variables from _brand.yml */
// quarto-scss-analysis-annotation { "action": "push", "origin": "_brand.yml typography" }
$font-family-monospace: Inconsolata !default;
$code-font-size: 1em !default;
$code-color: foreground !default;
$pre-color: foreground !default;
$code-block-font-size: 1em !default;
$code-block-color: foreground !default;
$code-bg: background !default;
$code-block-bg: background !default;
$headings-font-family: Montserrat !default;
$presentation-heading-font: Montserrat !default;
$font-family-base: Open Sans !default;
$mainFont: Open Sans !default;
$mermaid-font-family: Open Sans !default;
// quarto-scss-analysis-annotation { "action": "pop" }
$theme: "brand" !default;
````

So `foreground` and `background` are insereted, but not as variable... 🤔 
They should right ? 

I think this is the same issue with `--to html` as I get the same 
````scss
/* typography variables from _brand.yml */
// quarto-scss-analysis-annotation { "action": "push", "origin": "_brand.yml typography" }
$font-family-monospace: Inconsolata !default;
$code-font-size: 1em !default;
$code-color: foreground !default;
$pre-color: foreground !default;
$code-block-font-size: 1em !default;
$code-block-color: foreground !default;
$code-bg: background !default;
$code-block-bg: background !default;
$headings-font-family: Montserrat !default;
$presentation-heading-font: Montserrat !default;
$font-family-base: Open Sans !default;
$mainFont: Open Sans !default;
$mermaid-font-family: Open Sans !default;
````

but somehow this is hidden 🤷‍♂ 

So I have looked into it, but not should what is expected with brand:

- We could expect `$foreground` to be inserted in the SCSS but we do insert without `$`
	https://github.com/quarto-dev/quarto-cli/blob/e67ce56e5960ae6c94378a940067849b1f4effd5/src/core/sass/brand.ts#L545-L553
- This is probably because we usually resolve the color in `getColor()`
	https://github.com/quarto-dev/quarto-cli/blob/e67ce56e5960ae6c94378a940067849b1f4effd5/src/core/brand/brand.ts#L175-L202
	but `foreground` or `background` is not defined in the brand config, so it is assumed to be a color value. 

Example in specification shows how to use `color` in brand
https://posit-dev.github.io/brand-yml/brand/typography.html#example-with-color-definitions

Is something missing in the example ? I am unsure if the error is this one, or the fact that setting `brand.color` may not work.
