### ISSUE TITLE
[Feature Request] Wildcards in navigation content lists

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#117]
In the `render targets` yaml it is possible to specify targets using wild cards (https://quarto.org/docs/projects/quarto-projects.html#render-targets). This would also be very handy for specifying content layouts in the sidebar, e.g.

```
  sidebar:
    - id: hello
      style: floating
      title: Hello
      contents:
        - section: Hello
          contents:
             - hello/*.md
```

**Comment by dragonstyle** [comment]
This is great suggestion - we'll definitely take a look...

**Comment by fire** [comment]
I have a list of 30-50 files and it is impractical for me to write a script to force generate the contents list via.. a yml template engine.

**Comment by dragonstyle** [comment]
We haven't yet gotten to this for the sidebar / navigation, but we are just finishing up a listing feature that will allow you to generate pages with tables, grids, etc... of items generated from a glob. Something like

```
---
title: "Lab Reports"
toc: false
listing: 
  - contents: "reports/*.qmd"
    type: table
---
```

This should be landing shortly- any chance it will help out?
