### ISSUE TITLE
crossref values are displayed in html but not in pdf

### ISSUE THREAD

**Issue by bergsmat** [quarto-dev/quarto-cli#11772]
### Bug description

`crossref` attributes `appendix-title` and `appendix-delim` are not implemented in pdf.

### Steps to reproduce

* Create a new quarto project in RStudio by invoking the default template as project "example".
* Add `details.qmd` in project directory with content "# Details".
* Tweak `_quarto.yml` as below.
* Run `quarto render` from terminal in project directory.

````
project:
  type: book

book:
  title: "example"
  author: "Norah Jones"
  date: "1/2/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  appendices: 
    - details.qmd

crossref:
  appendix-title: "Attachment"
  appendix-delim: ":"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  

editor: visual
````

### Expected behavior

I expect to see "Attachment A: Details" in `example/_book/details.html` and in `example.pdf`.

### Actual behavior

I see "Attachment A: Details" in `example/_book/details.html`  but in `example.pdf` I just see "A Details".

### Your environment

- IDE: RStudio 2023.06.2 Build 561
- OS: Windows Version	10.0.19045 Build 19045

### Quarto check output

```bash
quarto check
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.353
      Path: C:\Program Files\RStudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.3
      Path: C:/Users/tim.bergsma/AppData/Local/Programs/Python/Python310/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.4.2
      Path: C:/PROGRA~1/R/R-44~1.2
      LibPaths:
        - C:/Users/tim.bergsma/AppData/Local/R/win-library/4.4
        - C:/Program Files/R/R-4.4.2/library
      knitr: 1.42
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
@bergsmat Could you update your Quarto version? You are using a fairly old one (1.3). Current version is 1.6.

**Comment by bergsmat** [comment]
Thanks.  I updated to 1.6.  But now I have the empty refs problem discussed in #6819 .  Perhaps I need a matching version of pandoc?  Still trying, and the “no cite” workaround did not help.

**Comment by mcanouil** [comment]
Quarto handles its dependencies and you should not interfere with that.

The issue you mentioned and closed thus has been resolved. Without a small reproducible example showing your new issue, we cannot do anything to help.

**Comment by bergsmat** [comment]
@mcanouil Duly noted, thanks.  I have updated RStudio as suggested, and I have updated Quarto to 1.6 (.39) as requested. I confirm that the behavior originally reported for Quarto 1.3 persists after updating to 1.6.  This seems consistent with your finding above for  1.7.5 pre-release.

**Comment by mcanouil** [comment]
```yaml
crossref:
  appendix-title: "App."
  appendix-delim: ":"
```

From <https://quarto.org/docs/books/book-structure.html#parts-appendices> does indeed not seem to work.

This was introduced somewhere for 1.2 but even using 1.2.475, it does not do anything.

I’ve created a book using quarto create project book.
- `_quarto.yml`

```yaml
project:
  type: book

book:
  title: "11950"
  author: "Norah Jones"
  date: "1/27/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
  appendices: 
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

crossref:
  appendix-title: "Whatever"
  appendix-delim: ":"
```

- `summary.qmd`

```yaml
# Summary {#sec-summary}

In summary, this book has no content whatsoever.
```

- `intro.qmd`

```yaml
# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

See @sec-summary.
```

Here is a directory/repository for convenience: https://github.com/mcanouil/quarto-issues-experiments/tree/main/quarto-cli-11950

| PDF | HTML |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/3b92eb33-b832-4429-8307-369949240ffd)  | ![Image](https://github.com/user-attachments/assets/6ec3db15-160a-488d-bbbd-d06a52f279ec) |


---


I find the two `crossref` options in the codebase:

- https://github.com/quarto-dev/quarto-cli/blob/4685082eef75df74f2b9755250af4e709393c3b3/src/config/constants.ts#L620-L622

Which is used in

- https://github.com/quarto-dev/quarto-cli/blob/4685082eef75df74f2b9755250af4e709393c3b3/src/project/types/book/book-chapters.ts#L147-L150

But if you set the language option instead which is used at the same place, then it works:

```yaml
language:
  crossref-apx-prefix: Something
```

Note that even the delimiter does not work but it cannot be set via language.

| PDF | HTML |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/c2c2e74d-7f8a-4c52-a81e-d629a6a47240) | ![Image](https://github.com/user-attachments/assets/0ab4970c-0cef-4ce3-8aed-a6ce54ebc05c) | 

---

It seems the info is lost somewhere.

![Image](https://github.com/user-attachments/assets/36f5a8fa-4669-4b2e-8ee0-77198753785f)

What is produced at some point by the code clearly doesn’t end up in the final document.
The markdown span is `Whatever A: Summary` and we have a span with text value being `Appendix A`.

---

I have tested this inside a Dev Container back to 1.2.475 (configuration inside the directory/repository linked earlier in this message.
