### ISSUE TITLE
Bug in sitemap generation

### ISSUE THREAD

**Issue by ludwigHoon** [quarto-dev/quarto-cli#118]
Hello, there's possibly a bug in the sitemap generation. (or perhaps I configured the _quarto.yml incorrectly).

One of the slash after the `http://` seem to have been removed.

Sitemap result:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https:/ludwighoon.github.io/about.html</loc>
    <lastmod>2021-09-29T15:05:26.300Z</lastmod>
  </url>
  <url>
    <loc>https:/ludwighoon.github.io/index.html</loc>
    <lastmod>2021-09-29T15:06:46.730Z</lastmod>
  </url>
```

What I defined in _quarto.yml:
```yml
project:
  type: site
  output-dir: docs

site:
  site-url: https://ludwighoon.github.io
  repo-url: https://github.com/ludwigHoon/ludwighoon.github.io
  repo-actions: [edit, issue]
  page-navigation: true
....
```
