### ISSUE TITLE
Behavior of arrays of sidebars is unclear

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#11870]
Opening after talking to @cscheid 

This may be a bug or documentation issue, but this callout on the [Webpage Nav](https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation) docs:

> A page that doesn’t appear in any `sidebar` will inherit and display the first sidebar without an`id` or `title` - you can prevent the sidebar from showing on a page by setting `sidebar: false` in its front matter.

This implied to me that the sidebar displayed on a page (unless otherwise set with `sidebar` in the header) would be:

1. The sidebar in which it is an element
2. If not an element in any sidebar, the first sidebar without a title (or id)

Here's an example that doesn't seem to follow these rules.

Consider this sidebar:
```yaml
website:
  sidebar:
    - title: Research
      contents:
        - project-1.qmd
        - project-2.qmd
    - title: Teaching
      contents: 
        - course-1.qmd
        - course-2.qmd
    - contents:
        - index.qmd
        - about.qmd
```

I would expect that `project-1.qmd` would get the "Research" sidebar, and `course-1.qmd` to get the "Teaching" sidebar.  Instead, they both get the last sidebar.

I've documented this example, and many others (some that almost work, some that don't) at: https://github.com/cwickham/sidebar-array?tab=readme-ov-file#sidebar-behavior
