### ISSUE TITLE
`_brand.yml`: google returning different font names confuses us

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#11947]
This works:

```yml
typography: 
  fonts:
    - source: google
      family: 'Source Sans Pro'
  base: 
    family: 'Source Sans Pro'
```

This doesn't:

```yml
typography: 
  fonts:
    - source: google
      family: 'Source Sans 3'
  base: 
    family: 'Source Sans 3'
```

Even though "Source Sans 3" is the [name of the font](https://fonts.google.com/specimen/Source+Sans+3) on Google Fonts. The issue appears to be that the CSS query returns `Source Sans Pro` as the name of the font, but we try to use `Source Sans 3`, and faceplant.
