### ISSUE TITLE
Extra `#block[ ]` when translating column-block to typst

### ISSUE THREAD

**Issue by ihrke** [quarto-dev/quarto-cli#11964]
### Bug description

When creating a block with multiple columns using `:::{layout-ncol=2}`, for example, the Typst output uses the Typst function `grid()` as expected. However, just before the `grid()`, the conversion inserts an empty block and that messes up the spacing in the output. See MWE below.

### Steps to reproduce

Minimal file that produces the bug:

````qmd
---
format: 
    typst: 
        keep-typ: true
---

:::{layout-ncol=2}

Test 1

Test 2

:::
````
translating this file to Typst using `quarto render test.md` produces this Typst file:

```typst
// ... default Typst template stuff

#block[
]
#grid(
columns: (50.0%, 50.0%), gutter: 1em, rows: 1,
  rect(stroke: none, width: 100%)[
Test 1

],
  rect(stroke: none, width: 100%)[
Test 2

],
)
```

The first `block[ ]` is erroneous and should not be there (its presence introduces spacing there which messes up the rest of the page).

### Expected behavior

The Typst file should look like this:

```typst
// ... default Typst template stuff

#grid(
columns: (50.0%, 50.0%), gutter: 1em, rows: 1,
  rect(stroke: none, width: 100%)[
Test 1

],
  rect(stroke: none, width: 100%)[
Test 2

],
)
```

### Actual behavior

As described above, the Typst file looks like

```typst
// ... default Typst template stuff

#block[
]
#grid(
columns: (50.0%, 50.0%), gutter: 1em, rows: 1,
  rect(stroke: none, width: 100%)[
Test 1

],
  rect(stroke: none, width: 100%)[
Test 2

],
)
```

### Your environment

- IDE: VSCode (irrelevant)
- Linux (Ubuntu 24) (irrelevant)
- Typst: 0.12.0

### Quarto check output

```bash
Quarto 1.7.1
[✓] Checking environment information...
      Quarto cache location: /home/mmi041/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.12.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.7.1
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2 (Conda)
      Path: /home/mmi041/miniconda3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /home/mmi041/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report.
I can reproduce.

**Comment by cderv** [comment]
If we look at trace for our lua chain we can see an empty Div at the end which is not removed 
````
blocks:
  - t: "Div"
    attr: "('', [], [])"
    content: []
  - t: "RawBlock"
    format: "typst"
    text: "#grid("
  - t: "RawBlock"
    format: "typst"
    text: "columns: (1fr, 1fr), gutter: 1em, rows: 1,"
  - t: "RawBlock"
    format: "typst"
    text: "  rect(stroke: none, width: 100%)["
  - t: "Para"
    content: "Test 1"
  - t: "RawBlock"
    format: "typst"
    text: "],"
  - t: "RawBlock"
    format: "typst"
    text: "  rect(stroke: none, width: 100%)["
  - t: "Para"
    content: "Test 2"
  - t: "RawBlock"
    format: "typst"
    text: "],"
  - t: "RawBlock"
    format: "typst"
    text: ")\n"
````

This block is the result for panel layout process indeed 

This
````
blocks:
  - t: "Div"
    attr: "('', [], ['layout-ncol,2'])"
    content:
      - t: "Para"
        content: "Test 1"
      - t: "Para"
        content: "Test 2"
````

is transformed to  this custom ast node 

```
blocks:
  - customAST: true
    attributes:
      layout-ncol: "2"
    classes: []
    identifier: ""
    is_float_reftarget: false
    layout:
      - []
    t: "PanelLayout"
    scaffold:
      - t: "Div"
        attr: "('', [], ['__quarto_custom_scaffold,true'])"
        content:
          - t: "Div"
            attr: "('', [], [])"
            content: []
      - t: "Div"
        attr: "('', [], ['__quarto_custom_scaffold,true'])"
        content:
          - t: "Div"
            attr: "('', [], [])"
            content:
              - t: "Div"
                attr: "('', [], [])"
                content:
                  - t: "Div"
                    attr: "('', [], ['width,1fr', 'layout-align,left'])"
                    content:
                      - t: "Para"
                        content: "Test 1"
                  - t: "Div"
                    attr: "('', [], ['width,1fr', 'layout-align,left'])"
                    content:
                      - t: "Para"
                        content: "Test 2"
````

And see this part
````
      - t: "Div"
        attr: "('', [], ['__quarto_custom_scaffold,true'])"
        content:
          - t: "Div"
            attr: "('', [], [])"
            content: []
````

which leads to empty div, not removed. 

This should not be produced at all in layout IMO. However, I thought empty div are also supposed to be removed 🤔 

but it seems we do it only for LaTex: No class, no id, not attributes on a div means we do like a scaffolded div and we don't return the Div.
https://github.com/quarto-dev/quarto-cli/blob/1dc41fab2e7839c36f55aa0ba21d93c9c9a43ffa/src/resources/filters/quarto-finalize/finalize-combined-1.lua#L34-L39

So there is two ways to deal with that:

- Specifically in Layout Panel to make sure we don't produce empty div
- More generally in our finalizer to make sure we do remove empty div in LaTeX to 
 
I think the latter should done s we don't want empty block generally in typst
