### ISSUE TITLE
can't import custom module utils.py (Error: Got unexpected extra argument (utils.py)) when using quarto preview and `server: shiny`

### ISSUE THREAD

**Issue by Eli-78-fas** [quarto-dev/quarto-cli#12059]
### Bug description

I am experimenting with Quarto to create a dashboard with shiny. 
My dashboard runs well when I have all the code in the same file. 
However, since I refactored the code and moved functions and classes into the script utils.py, I have encountered some errors.

In the documentation, I found this solution: https://quarto.org/docs/computations/render-scripts.html. 

So I created the following _quarto.yml file:
```yaml
project: 
  title: "dashboard_quarto"
  render:
    - "*.qmd"
    - "!utils.py"
author: "x"
format: 
  dashboard:
    theme: morph
    nav-buttons: [github]
server: shiny
```

Now I always have the same error : 

![Image](https://github.com/user-attachments/assets/45d4bdef-a666-4e40-aef8-0dd12b48900f)

Thank you for your help :) 

### Steps to reproduce
main  file 
```{python}
from shiny import render, reactive, ui
from shinywidgets import output_widget, render_widget
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "notebook"

from utils import plot_x_y

np.random.seed(0)
n = 10  
salaries = np.random.randint(3000, 12000, size=n)
expenses = np.random.randint(1000, 8000, size=n)
data = {
    'Salaries': salaries,
    'Expenses': expenses
}
df = pd.DataFrame(data)

# Study
@render.data_frame
def dataview():
    return render.DataGrid(df, width="100%",height="100%")


@render_widget
def plot():
    fig = plot_x_y(df, "Salaries","Expenses")
    return  fig 
```

file utils.py 
```{python}
import pandas as pd
import plotly.express as px
def plot_x_y(
    df: pd.DataFrame, x_col: str, y_col: str
):
    return px.scatter(df, x_col, y_col)
```

file _quarto.yml
```
project: 
  title: "dashboard_quarto"
  render:
    - "*.qmd"
    - "!utils.py"
author: "x"
format: 
  dashboard:
    theme: morph
    nav-buttons: [github]
server: shiny
```

### Expected behavior

I will finally this dashboard : 

![Image](https://github.com/user-attachments/assets/40388c43-0659-4610-853d-fb938aef98e5)

### Your environment

- quarto Version: 1.5.57
- pyhton 3.10

### Quarto check output

![Image](https://github.com/user-attachments/assets/02325144-c83d-45e6-a618-ef81d55d020c)
