### ISSUE TITLE
Author name doesn't render correctly with YAML listing content when using extended author schema

### ISSUE THREAD

**Issue by irmoodie** [quarto-dev/quarto-cli#12052]
### Bug description

When using a YAML listing content file, the first two examples render correctly, but the third does not.

Renders correctly:
``` yaml 
- title: "Item 1"
  author: Bob Smith
``` 

Renders correctly:
``` yaml
- title: "Item 1"
  author: 
    - Bob Smith
    - Anna Smith
```

Renders author names as [object Object]:

```yaml
- title: "Item 1"
  author: 
    - name:
        family: Smith
        given: Anna
    - name:
        family: Smith
        given: Bob
```

The bug is identical to closed issue: https://github.com/quarto-dev/quarto-cli/issues/4881#issue-1630364099

### Steps to reproduce

`listing.qmd`:
```qmd
---
title: "Listing Example"
listing:
  id: sample-listings
  contents: listing.yaml
  sort: "date desc"
  type: table
---
```

`listing.yaml`:

```yaml
- title: "Item 1"
  author: 
    - name:
        family: Smith
        given: Anna
    - name:
        family: Smith
        given: Bob
```

### Expected behavior

The author list processed and names appear as [documented in the Quarto docs](https://quarto.org/docs/journals/authors.html#author-schema).

### Actual behavior

The reprex is rendered with author names as [object Object]:

<img width="668" alt="Image" src="https://github.com/user-attachments/assets/4a9c6fc6-2271-4aa8-b23c-b5dc5ab9d07b" />

### Your environment

OS: macOS 15.2 24C101 arm64
IDE: VSCode 1.96.3

### Quarto check output

```bash
quarto check
Quarto 1.6.40
[✓] Checking environment information...
      Quarto cache location: /Users/iain/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.40
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12 (Conda)
      Path: /opt/homebrew/Caskroom/miniforge/base/bin/python
      Jupyter: 5.7.2
      Kernels: julia-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
```
