### ISSUE TITLE
Affiliations not rendered in PDF

### ISSUE THREAD

**Issue by danbebber** [quarto-dev/quarto-cli#12087]
### What would you like to do?

Report an issue on quarto.org

### Description

Affiliations and other metadata are rendered in HTML, but not in PDF.
Please ensure that rendering to PDF shows affiliations etc.

Example below:
```
---
title: "Toward a Unified Theory of High-Energy Metaphysics: Silly String Theory"
date: 2008-02-29
author:
  - name: Josiah Carberry
    id: jc
    orcid: 0000-0002-1825-0097
    email: josiah@psychoceramics.org
    affiliation: 
      - name: Brown University
        city: Providence
        state: RI
        url: www.brown.edu
format: pdf
editor: visual
---
```
