### ISSUE TITLE
false Citeproc warning about missing citation

### ISSUE THREAD

**Issue by ThierryO** [quarto-dev/quarto-cli#12136]
### Bug description

URLs containing an `@` like https://mastodon.online/@inbo result in a false citeproc warning

```
[WARNING] Citeproc: citation inbo not found
```

### Quarto check output

Quarto 99.9.9
[✓] Checking environment information...
      Quarto cache location: /home/thierry/.cache/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      commit: 3aec7d36ed43b455b6d67d15a819e9d0d83c834c
      Path: /home/thierry/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.12
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/thierry/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: /usr/bin/google-chrome
      Source: PATH

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3
      Path: /usr/bin/python3
      Jupyter: 5.3.2
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/home/thierry/quarto-cli/src/resources/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/home/thierry/quarto-cli/src/resources/jupyter/notebook.py", line 20, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK

**Comment by mcanouil** [comment]
@ThierryO Thank you for reaching out. To best assist you, we kindly request that you complete the issue template with all necessary information. This will enable us to reproduce the issue and provide a timely and effective solution. Currently, the information provided is insufficient for us to begin troubleshooting. We appreciate your cooperation.

---

For reference:

- https://github.com/quarto-dev/quarto-cli/issues/3493

**Comment by ThierryO** [comment]
We use it in the [navbar](https://github.com/inbo/flandersqmd-book/blob/ea554cc8905f418e36d1e7ab51402ee9a56954d9/_quarto.yml#L137) of a html book. The link provides a link to the relevant line in `_quarto.yml`. The file is part of a working example of a quarto extension.

**Comment by cderv** [comment]
It seems exactly same usage as initial problem
- https://github.com/quarto-dev/quarto-cli/issues/3493

Would it mean this is a regression 🤔 ? 

We need to come up with a simple example to reproduce and add as a test project

**Comment by mcanouil** [comment]
I can't reproduce on a website.

Note that the project is far from a default project.
A book cannot have a navbar but here it has one.
My guess is that the issue comes from the extension rather than Quarto itself.

**Comment by ThierryO** [comment]
> Note that the project is far from a default project.

Yes. This is an extension providing our corporate identity.

> A book cannot have a navbar but here it has one.

The documentation says [otherwise](https://quarto.org/docs/reference/projects/books.html#navbar)

**Comment by mcanouil** [comment]
Indeed, sorry, I missed that, but now I confirm the issue is not Quarto.

1. `quarto create project book`
2. `_quarto.ml`
```yaml
project:
  type: book

book:
  title: "demo"
  author: "Norah Jones"
  date: "2/25/2025"
  navbar:
    pinned: true
    right:
      - text: Mastodon
        href: https://fosstodon.org/@MickaelCanouil
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
```

<img width="657" alt="Image" src="https://github.com/user-attachments/assets/4fc83f6b-759d-4dee-80b7-60cb057f92e3" />

**Comment by ThierryO** [comment]
I've created a minimal examples without extensions.

`_quarto.yml`
```
project:
  type: book

bibliography: references.bib

format:
  html: default

book:
  chapters:
    - index.md
  navbar:
    left:
      - text: Cover
        file: index.md
    right:
      - icon: mastodon
        href: https://mastodon.online/@inbo
```

`index.md`
```
# Abstract {-}

Excerpt on ecology taken from [Wikipedia](https://en.wikipedia.org/wiki/Ecology)
```

`references.bib`
```
@Misc{R-3.0.1,
  Title                    = {{R: A language and environment for statistical computing. Version 3.0.1}},

  Author                   = {{R Core Team}},
  Year                     = {2013},

  Address                  = {Vienna, Austria},
  Publisher                = {R Foundation for Statistical Computing},
  Url                      = {http://www.r-project.org/}
}
```

## Console output of `quarto render`

```
pandoc 
  to: html
  output-file: index.html
  standalone: true
  toc: true
  number-sections: false
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  variables: {}
  
metadata
  crossref:
    chapters: true
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  bibliography:
    - references.bib
  
[WARNING] Citeproc: citation inbo not found
Output created: _book/index.html
```

**Comment by cderv** [comment]
This still happen in this case because we do pass the `book` metadata (we do not for `website` nor for `about` which previous #3493 was about. 
https://github.com/quarto-dev/quarto-cli/blob/cbea271e84a6f541a7c3235a2953db7b94e7dad3/src/command/render/pandoc.ts#L1264-L1302

Pandoc parses Metadata string as Mardown, and so it will resolve citation syntax in there unless escaped. 

Unfortunately, escaping like 
````yaml
href: https://mastodon.online/\@inbo
````

does not work either because of #3493 fix as it will escape again 
```yaml
href: https://mastodon.online/\\@inbo
```

which modify the intent. 

So this could be fixed in a scoped manner by also escaping in the pandoc metadata. 

Or we could also see why `book` metadata is not deleted. But I think now it is too late to remove it as users expect `meta` shortcode to work on book meta. 

For reference, this is the intermediate metadata file we pass to pandoc 
````yaml
crossref:
  chapters: true
document-css: false
link-citations: true
quarto-template-params:
  title-block-categories: 'true'
date-format: long
lang: en
fig-responsive: true
quarto-version: 99.9.9
bibliography:
  - references.bib
book:
  chapters:
    - index.md
  navbar:
    left:
      - text: Cover
        file: index.md
      - icon: mastodon
        href: https://mastodon.online/@inbo
    tools: []
  render:
    - type: chapter
      file: index.md
      depth: 0
toc-title: Table of contents
````

and why `@inbo` is parsed. 

We could try escape, or use `pandoc-native` too maybe.
