### ISSUE TITLE
Error When Rendering Quarto Book with Abstract to PDF

### ISSUE THREAD

**Issue by IULibScholComm** [quarto-dev/quarto-cli#12239]
### Bug description

My Quarto book has an abstract. Rendering it to HTML and/or EPUB works, but rendering it to PDF with the PDF yaml option `documentclass: book` or `documentclass: scrbook` causes the following error: `ERROR: compilation failed- error LaTeX Error: Environment abstract undefined.` 

This may be because those documentclasses do not include an abstract environment. However, I believe this was not an issue in previous Quarto versions, and this is not an issue when I use quarto titlepages/titlepage-pdf (the abstract is not included in the PDF book). 

This issue is similar to [11193](https://github.com/quarto-dev/quarto-cli/discussions/11193).

### Steps to reproduce

````yml
project:
  type: book

book:
  title: "pdf"
  author: "Norah Jones"
  abstract: abstract goes here yada yada yada
  date: "3/7/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrbook
````

````qmd
# Preface {.unnumbered}

This is a Quarto book.

To learn more about Quarto books visit <https://quarto.org/docs/books>.
````

### Actual behavior

The PDF version of the book does not render due to the following error: `ERROR: compilation failed- error LaTeX Error: Environment abstract undefined.` 

### Expected behavior

The PDF version of the book should render but not include an abstract.

### Your environment

- IDE: VSCode: Version: 1.98.0 (user setup)
- OS: Windows_NT x64 10.0.19045.5487

### Quarto check output

````bash
Quarto 1.7.14
[>] Checking environment information...
      Quarto cache location: C:\Users\amazel\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.7.14
      Path: C:\Users\amazel\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\amazel\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: C:\Program Files\Google\Chrome\Application\chrome.exe
      Source: Windows Registry

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: C:/Users/amazel/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.5.0
      Kernels: ir, python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.4.2
      Path: C:/PROGRA~1/R/R-44~1.2
      LibPaths:
        - C:/Users/amazel/AppData/Local/R/win-library/4.4
        - C:/Program Files/R/R-4.4.2/library
      knitr: 1.48
      rmarkdown: 2.29

[>] Checking Knitr engine render......OK
````
