### ISSUE TITLE
target= _blank breaking webpage

### ISSUE THREAD

**Issue by sciencecasey** [quarto-dev/quarto-cli#12305]
### Bug description

```
project:
  type: website

website:
  title: "The Body Forgot"
  #subtitle: "A Fun Children's Book about Chronic Illness & Friendshp"
  favicon: 9798992578812.jpg
  image: 9798992578812.jpg
  twitter-card: true
  description: "A fun children's book about chronic illness and disability, written by a disabled and chonicallly ill author"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About this Book
      - href: author.qmd
        text: About the Author
      - href: illustrator.qmd
        text: About the Illustrator
      - href: faq.qmd
        text: Book Q&A
    right:
      - text: "![amazon](amazon.svg)"
        target: _blank
        href: https://www.amazon.com
        aria-label: Amazon
      - href: https://www.barnesandnoble.com/w/the-body-forgot-casey-jayne/1147087554?ean=9798992578805
        aria-label: Barnes & Noble
        text: BN
      - icon: instagram
        href: https://instagram.com/bodyforgot
        aria-label: Instagram
      - text: "Email"
        url: mailto:bodyforgot@gmail.com

    execute:
      freeze: auto

format:
  html:
    theme: quartz
    css: styles.css
    toc: true


editor: visual
```

I tried adding target: _blank with and without quotations to each navbar item separately and all of them broke the site

### Steps to reproduce

I'm trying to get my navbar links to open to a new page and my site is working perfectly until I add the option 

```
target: _blank
```

I've tried closing "_blank" in quotation marks as well and both break it.  I also tried on text, icons, and svg icons within the navbar separately and all break.  

here is the github: https://github.com/sciencecasey/body_forgot/tree/main
here is the website: bodyforgot.com

### Actual behavior

![Image](https://github.com/user-attachments/assets/e467bfc7-2b8f-4cf4-9007-edfd9ed3e6fa)

### Expected behavior

I expected the links to work but with them opening in a new page

### Your environment

MacOS 15.3.2
quarto version 1.1.251
R version 4.2.1

### Quarto check output

[✓] Checking Quarto installation......OK
      Version: 1.1.251
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.5 (Conda)
      Path: /Users/casey/miniconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

(|) Checking Jupyter engine render....Traceback (most recent call last):
  File "/Applications/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/Applications/quarto/share/jupyter/notebook.py", line 16, in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
[✓] Checking Jupyter engine render....OK

**Comment by mcanouil** [comment]
Please upgrade your Quarto version before opening issues.
You are using a version that is more than two years old.
Version: 1.1.251

Current stable version is 1.6.42.

**Comment by mcanouil** [comment]
I'm going ahead and close as I cannot reproduce any issues.

```sh
quarto create project website 12305
```

- `_quarot.yml`

```yaml
project:
  type: website

website:
  title: "12305"
  navbar:
    left:
      - href: index.qmd
        text: Home
        target: _blank
      - href: about.qmd
        text: About
        target: _blank

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
```
