### ISSUE TITLE
WARNING "Unknown var ... specified in a var shortcode." with _variables.yml

### ISSUE THREAD

**Issue by Lulliter** [quarto-dev/quarto-cli#12308]
### Bug description

I have a couple a couple variables set in `_variables.yml` file 

```
websites:
  web_site: https://daviderossetti.net # "https://lulliter.github.io/nerd-help"
  gh_repo: https://github.com/Lulliter/daviderossetti
```
that enter in my `_quarto.yml` file 

```
website:
   title: "Davide Rossetti"
  description: "Personal website of Davide Rossetti"
  site-url: "{{< var websites.web_site >}}" # "https://daviderossetti.net"
  repo-url: "{{< var websites.gh_repo >}}" # "https://github.com/Lulliter/daviderossetti"
  page-footer:
    left: |
      {{< fa copyright >}} Copyright 2025, Davide Rossetti
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) <br>
      [Code at {{< fa brands github >}} GitHub]({{< var websites.gh_repo >}})

```

The website renders OK, but gives me a Warning message:

```
Rendering:
[1/3] index.qmd
WARNING (/Users/luisamimmi/Applications/quarto/share/filters/main.lua:17761) Unknown var websites\.web_site specified in a var shortcode.
[2/3] news.qmd
```

I think this started appearing after updating quarto (v 1.6.42). 

### Steps to reproduce

The whole repo is  [here](https://github.com/Lulliter/daviderossetti)

### Actual behavior

Renders but gives warning

### Your environment

I am running  
- R version 4.4.2 (2024-10-31) 
- using RStudio 2024.09.1+394
- on macOS Sequoia 15.1.1. T

### Quarto check output

Quarto 1.6.42
[✓] Checking environment information...
      Quarto cache location: /Users/luisamimmi/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.42
      Path: /Users/luisamimmi/Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/luisamimmi/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.13.0
      Path: /usr/local/opt/python@3.13/bin/python3.13
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.49
      rmarkdown: 2.29

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
For reference, if not duplicate of:

- https://github.com/quarto-dev/quarto-cli/issues/11782

**Comment by cderv** [comment]
I think this is related to 
- https://github.com/quarto-dev/quarto-cli/issues/10289#issuecomment-2231989122

and @cscheid comment's 
> In my view, this is really halfway between a bug and an enhancement. Technically the fix is to add support for shortcode expansion in these contexts (so an "enhancement"), but the fact that we fail to expand shortcodes in these cases is incredibly unintuitive, so a bug.


Resolving shortcodes in the project configuration context is not something straightforward. This would be an enhancement. 

We've made possible such a use case by allowing a user to use the `pre-render` script to modify the `_quarto.yml` configurations. Project configurations will be reloaded after the `pre-render` step, so you could use a script to read your `_variables.yml` and `_quarto.yml` and modify the latter accordingly before writing it back. 

@cscheid I am tempted to close this as duplicate and re-title the other issue to clearly state the enhancement of enabling shortcode logic inside configuration. 

Another way to see this is that both cases involve the `var` shortcode, which makes sense, really to be used in a config file. So maybe there is a way to support the [variables](https://quarto.org/docs/authoring/variables.html#var) defined in `_variables.yml` another way that `{{< var ... >}}` shortcode. 

Tags are YAML feature we could leverage.  Something like 
````yaml
website:
  site-url: !var websites.web_site
````

where our YAML reader would handle the `!var` tag by retrieving value in `_variables.yml`


The other one is anchors (&) and aliases (*) but this would mean merging the `_variables.yml` will the `_quarto.yml` before resolution under a specific key (like `_variables` ?) with anchor and then allow user to use `*` to retrieve. But this would be another syntax to learn

For example, `_quarto.yml`
````yaml
website:
  site-url: *quarto_var.websites.web_site
````

and in `_variables.yml`


Which would require the preprend of `_variables.yml` this way 
````yaml 
_quarto_vars: &quarto_var
  websites:
	web_site: https://daviderossetti.net/
	gh_repo: https://github.com/Lulliter/daviderossetti

website:
  site-url: *quarto_var.websites.web_site
````

Honestly, just ideas to see and tackle the problem differently than "we need to allow shortcodes to resolve in `_quarto.yml`. 😅 🤷‍♂
