### ISSUE TITLE
when using double brackets for code , highlight doesn't work

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1236]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1228

<div type='discussions-op-text'>

<sup>Originally posted by **ggous** June 27, 2022</sup>
Hi, 

If I use highlight style:

```
format:
  html:
    theme: cosmo
  pdf:
    include-before-body: 
        - colors.tex
    documentclass: scrreprt
    code-block-bg: true
    code-block-border-left: "#E9E9E9"
    keep-tex: true
    highlight-style: tango
```

and use double brackets for python code that I don't want to run:

`{{python}}`

 then the highlight style doesn't work.

Is there any workaround for this?
</div>
