### ISSUE TITLE
bad syntax highlighting with arrow highlighting style, javascript disabled, and dark mode

### ISSUE THREAD

**Issue by gordonwoodhull** [quarto-dev/quarto-cli#12399]
Our fix for flashing in dark mode in #12173 requires us to load both stylesheets and disable one in JavaScript at the top of the body.

Because of, we are susceptible to stylesheet bleed when JavaScript is disabled. The stylesheet for the default mode is always loaded second, but if it doesn't redefine everything, especially background colors, then styles from the non-default stylesheet can be seen.

One symptom is bad syntax highlighting with the default [highlighting style](https://quarto.org/docs/output-formats/html-code.html#highlighting) in this document.

````
---
format: html
theme:
  light: united
  dark: slate
_quarto:
  tests:
    html:
      ensureHtmlElements:
        - []
        - ["link[href*=\"-dark-\"]"]
---

## Hello

```markdown
![asdf](asd.png)
```
````

When JavaScript is disabled, this looks like

<img width="826" alt="Image" src="https://github.com/user-attachments/assets/df169454-96cf-410c-a5df-c47bc10ff657" />

This only seems to be an issue with arrow, but arrow is the default.

A workaround is to use a different `highlighting-style`. I tested the styles listed as working with light and dark mode, and the others all work.

(Note: Highlighting for links has an intentionally dark background in atom-one, gruvbox.)
