### ISSUE TITLE
How to supply sidebar contents from external YAML file for page-specific sidebars

### ISSUE THREAD

**Issue by fsaforo1** [quarto-dev/quarto-cli#12479]
### Problem Statement
I'm trying to make my website more maintainable by storing sidebar contents in external programmatically-generated YAML files instead of directly in `_quarto.yml`. This works fine for a global sidebar, but I'm having trouble getting it to work with page-specific sidebars.

### Issue
The sidebar panel appears, but it's empty - no content is displayed. If I hardcode the same structure directly in `_quarto.yml` instead of referencing the external file, it works correctly. 

### Question
What's the proper way to reference external YAML files for section-specific sidebar contents? The documentation isn't clear on this specific use case.

Below is an example of the structure of the external sidebar contents file:

```yaml
- section: Organization
  contents: about/index.qmd
- section: People
  contents:
    - text: Team Member 1
      href: about/people/member1.qmd
    # more team members...
```

And in my `_quarto.yml`, I reference it like this:

```yaml
website:
  sidebar:
    - id: about
      title: "About the Team"
      style: docked
      background: dark
      contents: sidebar_about.yml
    # Other section sidebars defined here...

metadata-files:
  - sidebar_about.yml
```

I also include `sidebar: about` in the frontmatter of my about pages.
