### ISSUE TITLE
quarto dashboard yaml refresh

### ISSUE THREAD

**Issue by antoine4ucsd** [quarto-dev/quarto-cli#12482]
### Bug description

Hello
I have developed a quarto dashboard that includes several maps and plots
it looks as expected BUT I often need to click on the refresh button of my webbrowser to 'load'  the map the first time
I tried to include the 'self-contained' option in my yaml but it does not change anything

```
format: 
  dashboard:
    self-contained: true  # Bundles everything into one file
    scrolling: true
    nav-buttons:
      - icon: globe
fig-width: 10
fig-asp: 0.3
editor_options: 
  chunk_output_type: console
```

### Quarto check output

Quarto 1.6.42
[✓] Checking environment information...
      Quarto cache location: /Users/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.42
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2025.01
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12
      Path: /Users/.virtualenvs/r-reticulate/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.49
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK
