### ISSUE TITLE
Support `brand-mode` in `revealjs`

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#12550]
With the introduction of `light` and `dark` brand, `typst` gained the option `brand-mode` to select which brand is applied to Typst outputs.

It would be nice to extend this to  `revealjs`, so that all formats that support brand, have some implementation of light/dark brand.

**Comment by gordonwoodhull** [comment]
Where this stands: `revealjs` does not support the equivalent feature with light and dark *themes*. 

We currently just take the light brand:

https://github.com/quarto-dev/quarto-cli/blob/4771b8c2e308e0241d28a9ee6060797df6f7edda/src/core/sass/brand.ts#L636-L640

Arguably, maybe this should take the author-preferred brand instead:

```ts
  const brandMode = darkModeDefault(format.metadata) ? "dark" : "light";
  return (await brandSassLayers(
    input,
    project,
    defaultColorNameMap,
  ))[brandMode];
```

`typst` defaults to `light` but `brand-mode` can make it `dark`.

**Comment by cderv** [comment]
Does it make sense for revealjs to have a dark / light switched ? This is not natively supported by RevealJS framework - one presentation is using one theme.  So there are light theme, and some dark theme too. Quarto offers both, but only one theme can be chosen. 

Is the question behind brand-mode rather how to apply one of the brand (dark or light) to a presentation?
I can see someone having a `_brand.yml` with both, and making either a presentation with a light revealjs theme requiring light brand, or either a presentation with a dark revealjs theme, requiring the use of dark brand instead. 

So it is not about switching, but rather how to apply the desired brand content. Does it make sense ? 

Regarding what we have today - there is a SASS mixin that allows to detect a darker them, and switch some style
https://github.com/quarto-dev/quarto-cli/blob/07c32fbdc9d138c3c747403184202349ede7669d/src/resources/formats/revealjs/quarto.scss#L225-L235

So we could also use this to decide when to use the dark brand 🤷‍♂ 

Hopefully I am not understanding this wrong - I acknowledge that this dark / light topic start to became quite confusing to me 😅

**Comment by mcanouil** [comment]
Last time I checked, you cannot do:

```yaml
format:
  typst:
    brand: _brand-dark.yml
  revealjs:
    brand: _brand-dark.yml
  html:
    brand:
      - light: _brand-light.yml
      - dark: _brand-dark.yml
```

The specification has to be top-level and you cannot really choose what brand is applied to formats that does not support switching.

**Comment by cderv** [comment]
I am unfamiliar with what `brand-mode` does exactly, but I see you are not using it for `typst`. And I believe this is probably why it may have been introduced. 


```yaml
format:
  typst:
    brand-mode: dark
  html: default
brand:
  - light: _brand-light.yml
  - dark: _brand-dark.yml
```

So this issue is about 
````yaml
format:
  revealjs:
    brand-mode: dark
````

However, I see your point. Almost all other configurations can be set at the format level and are "triaged" to the right top-level setting. I wonder if this is an oversight that what you share does not work... 🤔
