### ISSUE TITLE
Binder link doesn't redirect to notebook file

### ISSUE THREAD

**Issue by albertomercurio** [quarto-dev/quarto-cli#12761]
### Bug description

I followed the simple guide to implement Binder in quarto. I have successfully set the binder container and everything seems to work.

When I click the "Launch Binder" button, it correctly open Binder, but it doesn't open the related notebook. Moreover, if I open I manually, by navigating the folders, I cannot run python, as it requires the Jupyter extension for VSCode.

### Steps to reproduce

My `_quarto.yml` file:

````yml
project:
  type: book
  output-dir: _output

book:
  title: "Numerical Methods for Quantum Optics and Open Quantum Systems"
  author:
    - name: Alberto Mercurio
      orcid: 0000-0001-7814-1936
      email: alberto.mercurio@epfl.ch
      affiliations:
        - id: 1
          name: École Polytechnique Fédérale de Lausanne (EPFL)
          address: Rte Cantonale
          city: Lausanne
          state: Switzerland
          postal-code: 1015
    - name: Daniele De Bernardis
      orcid: 0000-0002-9618-0389
      email: daniele.debernardis@cnr.it
      affiliations:
        - id: 2
          name: Istituto Nazionale di Ottica (INO-CNR)
          address: Largo Enrico Fermi, 6
          city: Firenze
          state: Italia
          postal-code: 50125
  date: "15/05/2025"
  downloads: [pdf]
  navbar:
    search: true
    tools:
      - icon: github
        href:  https://github.com/Daniele-PyBECTN/Computational_quantum_optics_lectures
  chapters:
    - index.qmd
    - introduction.qmd
    - lecture1/lecture1.qmd
    - bibliography.qmd

number-depth: 3
bibliography: bibliography.bib

# default format for all files
format:
  html:
    theme:
      light: flatly
      dark: darkly
    highlight-style: atom-one
    css: styles.css
    toc: true
    published-title: Last Update
    date-format: iso
    code-line-numbers: true
    colorlinks: true
    footnotes-hover: true
    fig-align: center
    fig-responsive: true
  pdf:
    documentclass: scrreprt
    toc: true
    # keep-tex: true            # lets you inspect the .tex if you need to
    margin-left: 1.2in
    margin-right: 1.2in
    margin-top: 1.2in
    margin-bottom: 1.8in
    link-citations: true
    template-partials:
      - partials/title.tex    # our custom title block
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}   % author–affiliation macros
        \usepackage{orcidlink}
        \usepackage{hyperref}            % clickable e-mails
        \renewcommand\Authfont{\Large}
        \renewcommand\Affilfont{\small}

jupyter: python3

execute:
  eval: true
  cache: true
  freeze: false
````

My `introduction.qmd` file:

````qmd
---
code-links: binder
---

# Introduction

Some text...

```{python}
import numpy as np

# Vectorized array operations
x = np.linspace(0, 10, 20)
y = np.sin(x) + 0.5 * x**2
print(y[:5])  # show first five results
```

One line performs a million floating‑point operations in compiled code—often orders of magnitude faster than an explicit Python loop.

````

### Quarto check output

```bash
Quarto 1.7.23
[✓] Checking environment information...
      Quarto cache location: /Users/alberto/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.6.3: OK
      Dart Sass version 1.85.1: OK
      Deno version 1.46.3: OK
      Typst version 0.13.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.7.23
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2025

[✓] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
      Source: MacOS known location

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.16 (Conda)
      Path: /opt/homebrew/Caskroom/miniconda/base/envs/computational-quantum-optics-lectures/bin/python
      Jupyter: 5.7.2
      Kernels: julia-1.11, julia-1.10, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
