### ISSUE TITLE
Link to source of embedded code cell doesn't work for `book` project

### ISSUE THREAD

**Issue by albertomercurio** [quarto-dev/quarto-cli#12771]
### Bug description

I followed [the guide](https://quarto.org/docs/authoring/notebook-embed.html#linked-source-notebooks) to embed code cells of another notebook. It correctly embeds the code and the output, but I cannot see the link to the source notebook when I work with a `book` project. It works properly if I set a `website` project.

## `_quarto.yml`

```yml
project:
  type: book
  output-dir: _output

# website:
#   title: Quarto Test

#   navbar:
#     title: Quarto Test
#     left:
#       - href: index.qmd
#         text: Home
#       - href: introduction.qmd
#         text: Introduction
#       - href: some_notebook.qmd
#         text: Some Notebook

book:
  title: "Numerical Methods for Quantum Optics and Open Quantum Systems"
  author:
    - name: Alberto Mercurio
    - name: Daniele De Bernardis
  chapters:
    - index.qmd
    - introduction.qmd

# default format for all files
format:
  html:
    toc: true

jupyter: python3

execute:
  eval: true
```

## `introduction.qmd`

```qmd
# Introduction

Some text...

{{< embed some_notebook.qmd#some_code echo=true >}}
```

## `some_notebook.qmd`

````qmd
# Some Notebook

```{python}
#| label: some_code
import numpy as np

# Vectorized array operations
x = np.linspace(0, 10, 20)
y = np.sin(x) + 0.5 * x**2
print(y[:5])  # show first five results
```
````

### Actual behavior

The code and the output are rendered properly, but no link to the source notebook is generated.

### Expected behavior

A link to the source notebook, as for the `website` case.

### Your environment

- OS: MacOS Sequoia

### Quarto check output

```bash
Quarto 1.7.31
[✓] Checking environment information...
      Quarto cache location: /Users/alberto/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.6.3: OK
      Dart Sass version 1.85.1: OK
      Deno version 1.46.3: OK
      Typst version 0.13.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.7.31
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2025

[✓] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
      Source: MacOS known location

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.16 (Conda)
      Path: /opt/homebrew/Caskroom/miniconda/base/envs/computational-quantum-optics-lectures/bin/python
      Jupyter: 5.7.2
      Kernels: julia-1.11, julia-1.10, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
