### ISSUE TITLE
unified light and dark brand.yml syntax

### ISSUE THREAD

**Issue by gordonwoodhull** [quarto-dev/quarto-cli#12797]
Allow light and dark brands to be specified in one brand.yml file. The only light/dark customization allowed will be colors (and logos as already specified in brand.yml and to be implemented in dark logo #12341 alongside this).

@gadenbuie wrote

> Instead of 
```yaml
brand:
  light:
    color:
      background: "#ffffff"
      foreground: "#333333"
  dark:
    color:
      background: "#333333"
      foreground: "#ffffff"
```
> it could be

```yaml
brand:
  color:
    background: 
      light: "#ffffff"
      dark: "#333333"
    foreground: 
      light: "#333333"
      dark: "#ffffff"
```

Similarly we'll have

```yaml
brand:
  typography:
    heading:
      color:
        light: "#222"
        dark: "#fef"
    link:
      background-color:
        light: "#eef"
        dark: "#112"
```

The schema will be a bit messy/repetitive, because we will allow either syntax but not a combination of the two.

Internally, we will convert the unified brand.yml to separate light and dark brand metadata and use it as before.

We'll only do this for colors. If users want to customize other options between light and dark mode, they can use separate light and dark brands.
