### ISSUE TITLE
Error when affiliations are identical other than id

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#1286]
### Bug description

The below produces an error because the affiliation fields are identical.

```
affiliations:
  - id: aff1
    name: Affiliation Dept/Program/Center, Institution Name
    city: City
    state: State
    country: Country
  - id: aff2
    name: Affiliation Dept/Program/Center, Institution Name
    city: City
    state: State
    country: Country
  - id: aff3
    name: Affiliation Dept/Program/Center, Institution Name
    city: City
    state: State
    country: Country

```

### Checklist

- [ ] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, self-contained, and reproducible example?
- [ ] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?
