### ISSUE TITLE
Lua API - expose authors / affiliation normalization function

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#12879]
The idea came up for Quarto Extension and custom format while looking at 
- https://github.com/quarto-dev/quarto-cli/discussions/12876#discussioncomment-13356473

The usage is to have a way to separate list of authors from list of reviewers. 

Our Authors & Affiliations normalization handles multiple authors and roles, but Pandoc's template does not have a mechanism to fill-in template based on something like `$if(roles == "editing")$`. 

So be able to have several HTML divs in title-block for different authors' roles, currently this should be done using a Lua filter to process the metadata, normalize it, and create multiple variable to use in the template. 

Another way is to use another YAML like 

````
secondary-authors:
  - name: Stephen McGregor
    orcid: 0000-0001-6560-5586
    email: semcgregor@hotmail.com
    url: https://www.tenfive.ai
````

But it can't be used with the `_title-meta-author.html` partial because it is not normalized metadata. 

So YAML would need to be 
````
 secondary-authors:
  - name: 
      literal: Stephen McGregor
    orcid: 0000-0001-6560-5587
    email: semcgregor@hotmail.com
    url: https://www.tenfive.ai
````

So I am wondering if a `quarto.author` in API could be a good idea to allow a custom format to duplicate `author` logic. 

Highly hypothetical and probably not trivial work but at least the idea is now out there. We link to potential use case and decide if this could be helpful or not.
