### ISSUE TITLE
Document renders correctly in linux but not in windows

### ISSUE THREAD

**Issue by SolarDifference** [quarto-dev/quarto-cli#1288]
### Bug description

I developed a qmd document in linux (popOS 22.10) but recently switched to a windows machine. On linux, the qmd document renders without issue. When running the same document in windows, the following issues don't work:

1. Title does not appear
2. Table of contents does not appear
3. Font styles from the styling template are not correct
4. Bibliography (.bib) and csl documents do not generate a references page. 

The text and figures within the quarto document work as expected. Is there something specific I should be doing in windows that I didn't have to do in linux?

````
title: "Project Title"
format: 
  docx:
    reference-doc: styling_template.docx
    toc: true
    toc-title: Table of Contents
fig-cap-location: bottom
tbl-cap-location: top
bibliography: references.bib
csl: apa.csl
````

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?
