### ISSUE TITLE
graphviz diagrams are rendered incorrectly 

### ISSUE THREAD

**Issue by trinhdhk** [quarto-dev/quarto-cli#1296]
### Bug description

**Description**: the graphviz diagrams using _dot_ engine are rendered incorrectly - get chopped off at the bottom - if the outputs are too long in size. Previewing is unaffected.

**How to reproduce?**:  Draw a long graphviz

```dot
//| label: pathology
//| fig-cap: Pathology of TBM
//| fig-align: center

digraph pathology {
 
    Aerosol -> Lung 
    Lung:e -> Lung:e
    Lung -> Blood
    Blood -> {Organ:n CNS}
    Blood:w -> Lung:w
    Organ:s -> Organ:s

    CNS -> Latent
    CNS -> Rich:n
    Latent -> Rich:n
    Rich -> Subarchnoic
    Subarchnoic:s -> Subarchnoic:n
}   

```

quarto version 0.9.644
dot - graphviz version 3.0.0 (20220226.1711)
Environment/IDE: VSCode 1.68.1/darwin x64 21.5
No R computation involved yet.

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Can you please provide us a full .qmd file? It helps to know which format you're using, other options, etc.

**Comment by trinhdhk** [comment]
Here is the _quarto.yml
Basically that were everything. Other parts were just header and some listed text.

```yaml
project:
  type: book
  output-dir: render

book:
  title: 'Some title'
  author: 'Myself'
  repo-url: 'https://github.com/repo/repo'
  chapters:
    - index.qmd
    - introduction.qmd

bibliography: 
  includes/references.bib

format:
  pdf: 
    toc: true
    number-sections: true
    documentclass: scrbook
    keep-tex: true
    latex-auto-install: true
    pdf-engine: xelatex

```

Here is the introduction.qmd. index.qmd is empty.

````md
# Heading 1
## Heading 2

- Point 1
- Point 2
- Point 3

```{dot}
//| label: pathology
//| fig-cap: Pathology of TBM
//| fig-align: center

digraph pathology {
 
    Aerosol -> Lung 
    Lung:e -> Lung:e
    Lung -> Blood
    Blood -> {Organ:n CNS}
    Blood:w -> Lung:w
    Organ:s -> Organ:s

    CNS -> Latent
    CNS -> Rich:n
    Latent -> Rich:n
    Rich -> Subarchnoic
    Subarchnoic:s -> Subarchnoic:n
}   

```

````
