### ISSUE TITLE
document-defined light logo should prevail in dark mode, if the brand has no dark logos

### ISSUE THREAD

**Issue by gordonwoodhull** [quarto-dev/quarto-cli#12982]
This is an edge case that Claude Code found when writing tests for dark logo:

````
---
title: Yes dark logo if theme enables dark mode
format:
  dashboard:
    theme:
      light: default
      dark: darkly
brand:
  logo:
    images:
      light-logo:
        path: light-logo.png
        alt: light logo
    small:
      light: light-logo
logo:
  light: quarto.png
_quarto:
  tests:
    dashboard:
      ensureHtmlElements:
        -
          - 'img[src="quarto.png"][alt=""][class="navbar-logo light-content d-inline-block"]'
          - 'img[src="light-logo.png"][alt="light logo"][class="navbar-logo dark-content d-inline-block"]'
        - []
---

{{< lipsum 4 >}}

````

The brand did not specify any dark components, but there are light and dark themes, so we need to use the light brand as a dark brand to fix  #12981.

Arguably we should show quarto.png as the dark logo in this case, but by that time we have forgotten that the brand metadata does not have any explicitly dark logos, only dark logos that have been populated from light logos.

And the fix is

```
logo: quarto.png
```

So I don't think this is worth worrying about, but I'm filing it to have something to point to in corresponding tests.
