### ISSUE TITLE
Include icons and text in navbar

### ISSUE THREAD

**Issue by jhelvy** [quarto-dev/quarto-cli#1323]
Perhaps I am missing something, but I am unable to include an icon with text in navbar items. 

In a simple rmarkdown site, I can include both icons and text like this:

```yaml
- text: "Schedule"
  icon: fa fa-calendar-alt
  href: schedule.html
```

This looks like this when rendered
<img width="102" alt="Screen Shot 2022-06-30 at 9 20 02 AM" src="https://user-images.githubusercontent.com/9012994/176687569-c1993a86-3c97-4598-b357-6b86f2d51d1e.png">

In quarto, I can only get an icon or text to render, but not both. Is there a way to do this that I am missing, or is this not supported?
