### ISSUE TITLE
`quarto render` still rendering ignored folders

### ISSUE THREAD

**Issue by jhelvy** [quarto-dev/quarto-cli#1394]
I am trying to follow the [render targets](https://quarto.org/docs/websites/#render-targets) instructions for ignoring a folder in a Quarto website, but it seems Quarto is still rendering everything in that folder. Here's my example:

After creating a demo website with `quarto create-project mysite --type website`, I edit the `_quarto.yml` file as follows:

```
project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!dontrender/"

website:
  title: "quarto-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
```

I then created a folder called `dontrender` and inserted a `test.qmd` containing the following:

```
---
title: "test"
---
```

When I use `quarto render`, the `test.qmd` file still gets rendered despite my `"!dontrender/"` command in the `_quarto.yml` file.
