### ISSUE TITLE
website unable to put plain text entry into sidebar, like R4DS

### ISSUE THREAD

**Issue by machow** [quarto-dev/quarto-cli#1400]
### Bug description

Pages like https://quarto.org/docs/guide/ have a sidebar with sections of content. I'm looking to recreate that kind of sidebar, but with text headings for each section, similar to R for Data Science:

![image](https://user-images.githubusercontent.com/2574498/179067337-a9403b42-d123-4b06-bfc4-5e39d6bc0111.png)

It looks like if you add a content item to the sidebar that's just text (e.g. "Some header"), then it doesn't appear:

```
  sidebar:
    - id: get-started
      # ...
      contents:
        - text: "Some header"
```

However, if you add a horizontal rule, then it shows up in the sidebar:

```
  sidebar:
    - id: get-started
      # ...
      contents:
        - text: "----------------"
```

### `quarto check` Output

Note that this is on Mac OSX

```bash
[✓] Checking Quarto installation......OK
      Version: 1.0.20
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: /Users/machow/.virtualenvs/pyshiny-site/bin/python3
      Jupyter: 4.10.0
      Kernels: venv-siuba, venv-pins-python, venv-vetiver-test, venv-intro-to-siuba, venv-vetiver-python, venv-shiny-examples, venv-pyshiny-site, venv-notes, venv-siuba-docs, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```bash
[✓] Inspecting tools

Tool         Status            Installed     Latest
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by machow** [comment]
Thanks for the pointer! When I create a  without content--like in the example--it doesn't appear. I wonder if this and the issue with `text` are related?

Something like this:

```
website:
  sidebar:
    contents:
      - section: "First Section"
      - contents:
        - href: document1.qmd
        - href: document2.qmd
        - href: document3.qmd
      - section: "---"
      - section: "Second Section"
        contents:
          - href: document4.qmd
          - href: document5.qmd
          - href: document6.qmd
```

Produced a sidebar missing "First section" and the content items listed after it.

**Comment by jjallaire** [comment]
@dragonstyle Could you take a look at this?

**Comment by dragonstyle** [comment]
Will do.

**Comment by dragonstyle** [comment]
I reproduced this issue (we basically we ignoring sections or items that were empty / text only). I have a proposed fix for review... Thanks for reporting!

**Comment by machow** [comment]
Thanks for the quick response here! I tested with the latest quarto release and it looks like:

* fixed: adding a section with no contents
* broken: adding only contents

Here is what I'm seeing marked on the [separators example](https://quarto.org/docs/websites/website-navigation.html#separators) in the docs.

```yaml
website:
  sidebar:
    contents:
    
    
      # WORKS ----
      
      - section: "First Section"


      # BROKEN: none of these content items get put in sidebar ----
      
      - contents:
        - href: document1.qmd
        - href: document2.qmd
        - href: document3.qmd


      # WORKS -----
      
      - section: "---"
      - section: "Second Section"
        contents:
          - href: document4.qmd
          - href: document5.qmd
          - href: document6.qmd
```

**Comment by jjallaire** [comment]
I changed the docs to use `text: "---"` and the separator works:

@dragonstyle This code from our docs currently does not work:

```yaml
  sidebar:
    contents:
      - section: "First Section"
      - contents:
        - href: document1.qmd
        - href: document2.qmd
        - href: document3.qmd
      - text: "---"
      - section: "Second Section"
        contents:
          - href: document4.qmd
          - href: document5.qmd
          - href: document6.qmd
```

<img width="515" alt="Screen Shot 2022-07-15 at 1 41 03 PM" src="https://user-images.githubusercontent.com/104391/179280370-ff2aef04-8a6f-47f4-bca5-2e1f6bcc6a48.png">
