### ISSUE TITLE
Self-contained HTML with block banner figure

### ISSUE THREAD

**Issue by GilHenriques** [quarto-dev/quarto-cli#1496]

**Comment by cderv** [comment]
quarto-r repo issue board is dedicated to R package issues. So I transferred to quarto-cli. 

It seems Pandoc is failing to apply self-contained on this 
````css
<style>
.quarto-title-block .quarto-title-banner {
    background-image: url(<file>)
}
</style>
````
when it is included in the HTML file. 

I don't know if this is a limitation or a bug. 

It possible the Pandoc consider that the CSS is already inline and will not process it. If the CSS is added using an external file, it seems to be processed correctly.
