### ISSUE TITLE
Better support and documentation for footnotes at the end of a presentation

### ISSUE THREAD

**Issue by asmaier** [quarto-dev/quarto-cli#1498]
In my opinion it doesn't make sense to present footnotes at the bottom of a slide in a presentation. Not only do they often cause issues with the layout because there is simply not enough space for them on the slide. It also doesn't make sense to show footnotes which cannot be read by the viewer anyway, because the fontsize is so small. Also in presentations I use footnotes mostly just as replacement for citations, because for a presentation I do not want to deal with a second file just for a very small bibliography.  

That said, I was happy to see that - although it is not documented at https://quarto.org/docs/presentations/revealjs/#asides-footnotes - it is possible to move footnotes to the end of a quarto presentation with 
```
---
title: "Some presentation"
format: 
    revealjs:
        reference-location: document
    beamer:
        reference-location: document         
section-title-footnotes: References        
---
```
However there are several issues with that:
1. It doesn't work for beamer
2. In revealjs clicking on a footnote number navigates you to the title page, but not to the footnote at the end of the document (But the hover shows the content of the footnote nicely). The footnote link is somehow messed up.
3. The footnotes at the end of the document are missing a backlink to the footnote. 
4. It seems to me that although the footnote is not shown on the slide, adding a footnote to a slide can still break the layout. For example in the following presentation the image on the `middle` slide will appear much smaller than on the `start` side. The reason is the footnote:
```
---
title: "Some presentation"
format: 
    revealjs:
        reference-location: document
section-title-footnotes: References        
---

## start 

![](some_image.png)

- text without footnote

## middle

![](some_image.png)

- text with footnote^[important footnote]

## end
```
Changing the layout if a footnote is present makes sense, if the footnotes are on the same slide, but it shouldn't be done if the footnotes are collected at the end of the document.
