### ISSUE TITLE
Release Notes?

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#1503]
Is it necessary to write release notes for the released version? It is not easy to know what bugs have been fixed.

https://github.com/quarto-dev/quarto-cli/releases/tag/v1.0.36

**Comment by mcanouil** [comment]
May I suggest to migrate to https://github.com/ncipollo/release-action which is maintained? It has the "generate release notes which add PRs and the comparison URL between release and release-1.
https://github.com/quarto-dev/quarto-cli/blob/79b7dfc4ca88e55a49d8e9d6020309e606b7d3e6/.github/workflows/create-release.yml#L226-L237

```
- name: Create Release
  Id: create_release
  uses: ncipollo/release-action@v1
    with:
      tag: ${{needs.configure.outputs.tag_name}}
      name: ${{needs.configure.outputs.release}}
      generateReleaseNotes: true
      prerelease: ${{ github.event.inputs.pre-release }}
      draft: ${{ github.event.inputs.draft }}
      token: ${{ secrets.GITHUB_TOKEN }}
```
