### ISSUE TITLE
Commands like $\ket{A}$ work in main body but not in abstract

### ISSUE THREAD

**Issue by joshjob42** [quarto-dev/quarto-cli#1595]
### Bug description

Functions like `$\ket{A}$` and `$\bra{C}$` work just fine in main body, but fail in abstract when compiling to both HTML and PDF.

The if one deletes the end quote and uncomments the end of line 13 below (the abstract), the build fails, error given is " ERROR: YAMLError: unknown escape sequence at line 13, column 32:
    abstract: "We test `$1+1$` and `$\ket{j}$`." "

I just installed Quarto on Mac Ventura and using VSCode with the Quarto extension v1.29.0.

Example .qmd file:
```
---
title: "Testing, testing 1,2"
author: 
    name: "Auhor Name"
    affiliation: "Places"
date: "07/29/2022"
format:
    html:
        code-fold: true
    pdf:
        include-in-header:
            text: \usepackage{physics}
abstract: "We test $1+1$ and $\ket{j}$." uncomment that bit to test
---

$\ket{j}$ works here as does $\bra{H}$.

```

### `quarto check` Output

```zsh
% quarto check

[✓] Checking Quarto installation......OK
      Version: 1.0.37
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.5 (Conda)
      Path: /Users/joshjob42/opt/anaconda3/bin/python
      Jupyter: 4.6.3
      Kernels: julia-1.6, julia-1.8, julia-1.7, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### `quarto tools check` Output

```zsh
% quarto tools check
[✓] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685  
tinytex      Not installed     ---           v2022.07
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?
