### ISSUE TITLE
project level `_variables.yml` not rendering in navbar

### ISSUE THREAD

**Issue by jhelvy** [quarto-dev/quarto-cli#1627]
I love the [variables](https://quarto.org/docs/authoring/variables.html#var) feature and am using it all over my websites. I'm getting it to work in some parts of the `_quarto.yml` file, but not all. 

For example, I am using `repo` in my `_variables.yml` file stores the url to a Github repo. In the footer, I can use `{{< var repo >}}` and it replaces `{{< var repo >}}` with the url, but it won't render if I put it in the navbar like this:

```r
      - icon: github
        href: "{{< var repo >}}"
```

I just get the text `{{< var repo >}}` instead of the replaced text.

**Comment by jhelvy** [comment]
Very excited this is being supported!

I'm just doing some quick testing and I'm seeing the variables properly render for `text` items but not `href`.

I made a simple `_variables.yml` with the following:

```yaml
test_text: This is a link
test_url: https://jhelvy.com

```

Then this for `_quarto.yml`:

```yaml
project:
  type: website

website:
  title: "mysite"
  navbar:
    left:
      - text: "{{< var test_text >}}"
        href: "{{< var text_url >}}"

format:
  html:
    theme: cosmo
    toc: true
```

The `var test_text` works - the navbar text is "This is a link". But `var text_url` renders as `%7B%7B%3C%20var%20text_url%20%3E%7D%7D`. So it's not replacing the code with the url.
