### ISSUE TITLE
Institute field comes after Date field in the YAML of Quarto Beamer Presentations

### ISSUE THREAD

**Issue by gulinan** [quarto-dev/quarto-cli#1658]
### Bug description

Hi, I am preparing a Beamer presentation in Quarto which will be rendered into pdf later. When I include date of the talk and my institute in the YAML, it prints date before the institution in the pdf version. We generally prefer the date after the institution. In the source files of Quarto Beamer presentation, I have seen a source `.tex` file where the author and date fields are embedded together. I guess, for that reason, they get printed out together. I cannot modify the Quarto source files since they are read-only. I would appreciate if this can be fixed. I have another question on how to break long titles into two lines in the YAML too. I would like to thank you very much in advance.

```yaml
---
title: "My talk title"
author: "My name"
institute: "My institute"
date: "August 02, 2022"
mathspec: true # for metropolis theme
execute: 
  enabled: true
  warning: false
  error: false
comments:
  hypothesis: 
    theme: clean
format: 
  beamer: 
    aspectratio: 32
    navigation: horizontal
    theme: metropolis
    colortheme: crane
    colorlinks: true
    highlight-style: tango
[question.pdf](https://github.com/quarto-dev/quarto-cli/files/9250720/question.pdf)

editor: visual
---
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [ ] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [ ] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?
