### ISSUE TITLE
Cannot set lang from command-line

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#175]
With quarto 0.2.232 I could set the `lang` metadata by calling `quarto render -M lang=fr` (see https://github.com/quarto-dev/quarto-cli/issues/146#issue-1033671251 for a description of the use case). This doesn't work anymore in 0.2.258.

For example with

```
# File _quarto.yml
project:
  type: book

book:
  title: Title
  chapters:
    - index.qmd

filters:
  - checklang.lua
```

```
-- File checklang.lua
function Meta(meta)
    print('@@@ Metadata lang:', meta.lang)
    return nil
end
```

Calling `quarto render -M lang=fr` with the older version would print `@@@ Metadata lang:	fr`. Now it prints `@@@ Metadata lang:	nil`.
