### ISSUE TITLE
Wick's contractions 

### ISSUE THREAD

**Issue by Belyor** [quarto-dev/quarto-cli#1754]
### Bug description

System: Windows10

`_quarto.yml`:
```
project:
  type: book
  output-dir: docs
  
book:
  title: "My Title"
  author: "My Author"
  chapters:
    - index.qmd 


format:
  html: 
    theme: cosmo
    code-link: true
    include-before-body: 
      \usepackage{mathtools, simpler-wick}
    toc: true
    toc-title: Spis sekcji
    toc-depth: 2
    html-math-method: katex
    number-sections: true
    number-depth: 1
    anchor-sections: true
    smooth-scroll: true
```

which contains the [CTAN](https://ctan.org/pkg/simpler-wick) _simpler-wick_ package. According to [documentation](https://jpellis.me/projects/simpler-wick/simpler-wick/simpler-wick.pdf) ine should put `*.sty` file in project root directory (it works when tested on [overleaf.com](https://www.overleaf.com). However, when one `quarto render`'s `index.qmd` file with the codeblock of:

``` latex
$$
\wick{\c\phi A \c\phi}
$$
```
that is expected to produce: 
![image](https://user-images.githubusercontent.com/36810933/183629902-ed3651f8-d6b3-4f13-bb42-ca7de7d5a4b5.png)

it renders this:
![image](https://user-images.githubusercontent.com/36810933/183629964-43e226a2-4bbc-41c0-b9e6-285d3622602c.png)

### `quarto check` Output

> quarto check
```
[>] Checking Quarto installation......OK
      Version: 1.0.38
      Path: C:\Program Files\Quarto\bin\
      CodePage: 1250

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.8.13 (Conda)
      Path: C:/Users/andrz/AppData/Roaming/jupyterlab-desktop/jlab_server/python.exe
      Jupyter: 4.9.2
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.1.0
      Path: C:/PROGRA~1/R/R-41~1.0
      LibPaths:
        - C:/Users/andrz/OneDrive/Dokumenty/R/win-library/4.1
        - C:/Program Files/R/R-4.1.0/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
```

### `quarto tools check` Output

> quarto tools check
```
[>] Inspecting tools

Tool         Status            Installed     Latest  
chromium     Not installed     ---           869685
tinytex      Not installed     ---           v2022.08
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by Belyor** [comment]
I did not know where to ask a community. Is there a specific webpage?

Now with:
```
format:
  html: 
    theme: cosmo
    include-before-body: 
      \usepackage{mathtools, simpler-wick}
    html-math-method: mathjax
```
Still not rendered: 
![image](https://user-images.githubusercontent.com/36810933/183720497-b7ddf403-5f86-4f7b-aa26-240013bdd8d7.png)

Any indication where `*.sty` should be copied?

PS
Can I render one `*.qmd` with a different **html-math-method** ? Katex is prerendered (am I right?)
