### ISSUE TITLE
how to tweak quarto render process to be compatible w/ latex glossaries package?

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1782]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1780

<div type='discussions-op-text'>

<sup>Originally posted by **chrizz89** August 10, 2022</sup>
I am considering transitioning from latex to quarto for my current project. One thing I have not been able to get going is **making use of the latex glossaries package in quarto**. It does work as far as commands (which rely on my definitions inside `glossary.tex`) are processed and displayed correctly but **printing my glossary does absolutly not work**.
I have tried `keep-tex: true`as well as `latex-clean: false` as my web search suggests it has some thing todo with glossaries requiring multiple latex compilations in order to work, but non if it seemed to work so far. (I tried pdflatex as well as xelatex for rendering)

Any suggestions how to tackle this?

as small example how I implemented it in my _quarto.yml:

```
format:
  pdf:
    documentclass: scrbook
    include-in-header: 
      - \usepackage[acronym, nonumberlist]{glossaries}
      - \makeglossaries
    include-before-body:
      - \input{glossary.tex}
    include-after-body: 
      - \printglossary[type=\acronymtype]
    keep-tex: true
    latex-clean: false
    latex-min-runs: 3
```

</div>
