### ISSUE TITLE
Use "image" schema

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#1794]
We should audit our schemas and code for places where we expect an image, and replace what's currently a `string` with a

```yaml
- name: image
  schema:
    anyOf:
      - string
      - object:
          properties:
            src: path
            alt: string
          required:
            - src
```

We should also have a typescript type that matches the schema, and then have our code treat these uniformly, including tracking the alt text automatically.
