### ISSUE TITLE
Auto animations not working when text is bulleted

### ISSUE THREAD

**Issue by kwakuduahc1** [quarto-dev/quarto-cli#1823]
I observed a rather weird behavior using auto-animations with quarto.

Given this yaml headers
``` 
title: "revealjs animation"
author: "kwakuduahc1"
format: 
  revealjs: 
     incremental: true 
     code-fold: show
     show-slide-number: all    
 ```

_This works as expected. The code block is preserved on the same page and the animation effects work correctly._

## Variables (refresher) {#vects auto-animate=true}
The quick brown fox

```{r}
#| echo: true
#| code-line-numbers: true
ctry <- "Ghana"

```

## Variables (refresher) {#vects auto-animate=true}
The quick brown fox

```{r}
#| echo: true
#| code-line-numbers: "2"
#| output-location: fragment
ctry <- "Ghana"
ctry
```

_But this does not work. On animation, the bulleted line disappears before the animation completes._

## Variables (refresher) {#vects auto-animate=true}
1. The quick brown fox

```{r}
#| echo: true
#| code-line-numbers: true
ctry <- "Ghana"

```

## Variables (refresher) {#vects auto-animate=true}
1. The quick brown fox

```{r}
#| echo: true
#| code-line-numbers: "2"
#| output-location: fragment
ctry <- "Ghana"
ctry
```

An interim solution is to surround the second code block with fragment but that means pressing the next button twice before the desired animation is showed.
