### ISSUE TITLE
Gitlab: Create Static Sites

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#1994]
Gitlab has the ability to create static sites from a template (https://gitlab.com/pages).  Quarto isn’t listed.  These are the steps of setting that up: https://gitlab.com/pages/pages.gitlab.io/-/blob/master/CONTRIBUTING.md

**Comment by matthewfranglen** [comment]
this `.gitlab-ci.yml` file allows me to publish a blog. It would be nice to have a good cache setting to skip installing quarto every time:

```yaml
image: ubuntu:latest

variables:
  QUARTO_VERSION: "1.0.38"

pages:
  script:
  - apt-get update
  - apt-get -y install wget ca-certificates
  - wget "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb" -O quarto.deb
  - dpkg -i quarto.deb
  - quarto render . --output-dir public
  artifacts:
    paths:
    - public
```

**Comment by cderv** [comment]
I see Gitlab is working on docker images. We could provide one maybe with Quarto pre-installed, and build the image at each release ? 

Otherwise, I know that some projects already include Quarto (but also more) like the Rocker project (https://rocker-project.org/images/ with the `verse` image)  useful for R users. There may be some around python already too. 

But Quarto installation is quite fast, and on Github action we do not cache the installation. We could probably do it using cache setting for the tools, and checking the API version for release to know if we should update to not the installed version. 
Gitlab may also have a cache system that could allow such logic. 

Anyway, just wanted to share the docker image idea.

**Comment by rgaiacs** [comment]
I created https://gitlab.com/quarto-forge/docker and I will be building some Docker images to be used primarily by GitLab Pages users. Contributions are welcome!

**Comment by zachcp** [comment]
@rgaiacs , I came across this issue due to a similar need. Thank you for setting up the docker image! Can I make a request to rebuild/push? I was exploring the use of `shinylive-ext` which requires a newer Quarto version: 

```sh
ERROR: The extension Embedded Shinylive applications is incompatible with this quarto version.
Extension requires: >=1.2.198
Quarto version: 1.2.79
```

Do you think you can schedule a CI build & Push of the images in your repo?

**Comment by rgaiacs** [comment]
@zachcp Thanks for the message. I'm looking to figure out why GitLab isn't updating the image in their registry. You will find a copy of the images in https://hub.docker.com/u/quarto2forge and they have been updated.

**Comment by zachcp** [comment]
thanks @rgaiacs but Dockerhub does not seem to be updating:

```sh
docker pull quarto2forge/quarto
docker run -it --entrypoint /bin/bash quarto2forge/quarto
# quarto -v
# 1.2.79
# expect 1.3.XX
```

**Comment by rgaiacs** [comment]
@zachcp I fixed the issue due some cache.

```
$ docker pull quarto2forge/quarto
Using default tag: latest
latest: Pulling from quarto2forge/quarto
Digest: sha256:705ba1cdcdf35c7f5930af92376c99d3c41d0a70c8d0edb159f7fe43d5c3bd03
Status: Downloaded newer image for quarto2forge/quarto:latest
docker.io/quarto2forge/quarto:latest
$ docker run quarto2forge/quarto quarto check

[✓] Checking Quarto installation......OK
      Version: 1.3.34
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

In January, I will have time to re-organise things and include a image with stable release of Quarto.

**Comment by allenmanning** [comment]
https://github.com/quarto-dev/quarto-cli/discussions/973

**Comment by Bisaloo** [comment]
If someone stumbles on this issue, here is the minimal `gitlab-ci.yml` file I'm currently using:

```yml
image: ghcr.io/quarto-dev/quarto:latest
create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: _site
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - quarto render
```
