### ISSUE TITLE
For PDF, hyperrefoptions being overridden by \hypersetup

### ISSUE THREAD

**Issue by eeholmes** [quarto-dev/quarto-cli#2017]
RStudio 2022.07.1 Build 554
OS Mac M1 Air

### Bug description

What happens depends on the document class. Described below.

If one passes in `hyperrefoptions: `

```
  pdf:
    documentclass: scrbook
    keep-tex: true
    hyperrefoptions: 
      - "colorlinks=true"
      - "linkcolor=blue"
      - "urlcolor=cyan"
```
This is correctly passed to hyperref in the tex output. At top of generated tex:
```
\PassOptionsToPackage{unicode,colorlinks=true,linkcolor=blue,urlcolor=cyan}{hyperref}
```
But below that (after line 100  in the generated tex) is this `\hypersetup` command which overrides that.

**`documentclass: scrbook` and `book`**

No hyperlink color are seen because the `\hyperref` setup is not changed and includes `hidelinks`.
```
\hypersetup{
  pdftitle={title},
  pdfauthor={author},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
```

**`documentclass: scrarticle`, `article`, `krantz`, `svmono`, `report`, `memoir`**

Passing in any `hyperrefoptions: `, including `colorlinks=false`, triggers a change to `\hypersetup` to turn on colorlinks but none of the info in `hyperrefoptions` is used.

The code the generated tex is this
```
\hypersetup{
  pdftitle={title},
  pdfauthor={the author},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}
```
whether one puts this
```
    hyperrefoptions: 
      - "colorlinks=false"
```
or this (or anything else)
```
    hyperrefoptions: 
      - "colorlinks=true"
      - "urlcolor=red"
```
in the format pdf YAML.

Note in all cases the hyperref options are passed to hyperref at the top of the tex file, it's just that they are being overridden later by `\hypersetup`

Personally as a LaTeX user, I find this preferable

```
    hyperrefoptions: 
      - "colorlinks=true"
      - "linkcolor=blue"
      - "urlcolor=cyan"
```
over this 
```
    colorlinks: true
    linkcolor: blue
    urlcolor: cyan
```
The former is what I use for `classoptions` and `geometry` and it is 100% clear what I am doing, i.e. I am setting the hyperref package options and I can look up all the possible options for that package. But the can co-exist just need the `\hyperrefoptions` commands to make it into `\hypersetup`.

### `quarto check` Output

```
[✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12
      Path: /opt/homebrew/opt/python@3.9/bin/python3.9
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.1.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/eli.holmes/Library/R/x86_64/4.1/library
        - /Library/Frameworks/R.framework/Versions/4.1/Resources/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

### `quarto tools check` Output

```
[✓] Inspecting tools

Tool         Status                    Installed     Latest  
chromium     Not installed             ---           869685  
tinytex      External Installation     ---           v2022.08
```

MWE qmd
```
---
title: title
author:
  - name: the author
editor: source
format:
  pdf:
    documentclass: scrbook
    keep-tex: true
    hyperrefoptions: 
      - "colorlinks=true"
      - "linkcolor=blue"
      - "urlcolor=cyan"
---

# Intro

[Quarto](https://quarto.org/) is great.

```

### Checklist

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [x] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [x] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [x] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Thanks for reporting, we'll take a look at this in the next release (v1.2)

**Comment by jpmorr** [comment]
I think I've come across the same bug. In my `_quarto.yml` I've added the following lines:
```
    hyperrefoptions:
      - linktoc=all
      - urlcolor=cyan 
      - linkcolor=blue
      - filecolor=magenta
      - citecolor=red 
      - anchorcolor=green
      - colorlinks=true
```

Which seems to be parsed correctly into the the `.tex` file. On line 2 I get:
```
\PassOptionsToPackage{unicode,linktoc=all,urlcolor=cyan,linkcolor=blue,filecolor=magenta,citecolor=red,anchorcolor=green,colorlinks=true}{hyperref}
```

Later in the file, `hypersetup` is called with the following options (note that cyan has changed to blue for some reason):
```
\hypersetup{
  pdftitle={MyBook},
  pdfauthor={John Doe},
  colorlinks=true,
  linkcolor={blue},
  filecolor={magenta},
  citecolor={red},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}
```

That results in a pdf called `MyBook.pdf` being created but not as expected. All my table of content links are blue. The `url` link colour in the preface of the document is blue as per `\hypersetup` and not `\PassOptionsToPackage`. Then in the first chapter where I have citations, there are no hyperlinks, just plain black text. Cross references for figures, equations, sections, etc are working and Blue.

url links in the reference section are also working correctly and blue. 

It just seems that some options are not getting passed correctly and that citations seem completely broken.

I'm using Quarto Version: 1.2.71 from Windows.

**Comment by dragonstyle** [comment]
I think the overarching issue is that Pandoc (and consequently Quarto) are expecting these values to be set via yaml (see https://quarto.org/docs/reference/formats/pdf.html#colors). The underlying Pandoc template that is being used to output the LaTeX has behavior driven by these YAML values. Unfortunately the template isn't aware of the internal values that you're setting via `hyperrefoptions` (the value of hyperrefoptions is opaque to the template), so it doesn't respect those (and in fact proceeds with whatever the default behavior is in addition to outputting the hyperrefoptions).

Can you try setting the values using YAML above? This is, in general, a preferred approach for Quarto because this creates the possibility for sharing the values across formats (e.g. `linkcolor` is actually shared for HTML, PDF, and ConTeXt).

@jpmorr I would expect the following to provide you desired behavior:

```
format:
  pdf:
    hyperrefoptions:
      - linktoc
      - "anchorcolor=green"
    linkcolor: blue
    urlcolor: cyan
    filecolor: magenta
    citecolor: red
```

**Comment by eeholmes** [comment]
Is the underlying Pandoc template from Pandoc or is that one that is customized for Quarto? If so, then the template can be written so that this

```yaml
format:
  pdf:
    hyperrefoptions:
      - linktoc=all
      - urlcolor=cyan 
      - linkcolor=blue
      - filecolor=magenta
      - citecolor=red 
      - anchorcolor=green
      - colorlinks=true
```

Has the same behavior as this:
```yaml
format:
  pdf:
    hyperrefoptions:
      - linktoc
      - "anchorcolor=green"
    linkcolor: blue
    urlcolor: cyan
    filecolor: magenta
    citecolor: red
```

Whether using `linkcolor: ...` is preferred would seem to depend on the objective. Sure if you want to set up colors that are the same across formats then use
```yaml
format:
  linkcolor: blue
  urlcolor: cyan
  filecolor: magenta
  citecolor: red
  pdf:
     hyperrefoptions:
        - linktoc
        - "anchorcolor=green"
```
Personally, I rarely want my html and pdf link colors to be the same. There are different standards for each format. The fact that my explicit instructions in the YAML regarding `hyperrefoptions` are ignored, it really confusing. Actually, it's not ignored. As @jpmorr noted, the correct instructions are put in the tex file. It is just that there is a later `\hyperrefsetup` instruction that overrides that.

But perhaps a helpful, interim is to update the tooltip for `hyperrefoptions:` to alert the user that urlcolor, linkcolor, filecolor, citecolor (any others?) are ignored and that these should be passed in separately as `urlcolor: cyan` etc.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/2545978/189429165-9657bdb4-2d22-4250-bfc0-eba1731e3249.png">

**Comment by dragonstyle** [comment]
> Is the underlying Pandoc template from Pandoc or is that one that is customized for Quarto?

It is the underlying pandoc template (which we generally abide by with minimal customization). I understand your preference for more LaTeX native syntax, but for at least the time being Quarto/Pandoc is best set up to express this as you suggest:

```
format:
  pdf:
    hyperrefoptions:
      - linktoc
      - "anchorcolor=green"
    linkcolor: blue
    urlcolor: cyan
    filecolor: magenta
    citecolor: red
```

I agree that both Quarto and Pandoc documentation around this could be improved. Thanks for the suggestion - I'll leave this open to track that change. It may be a challenge to fit an explanation within the autocomplete suggestion, but I will give something a try and see if we can improve that!

**Comment by dragonstyle** [comment]
By default citation linking in PDF is off by default. The following gives me colored links as you'd expect (note that I also added a color to the TOC to test that linking as well).

```
format:
  pdf:
    code-line-numbers: true
    papersize: a4
    documentclass: scrbook
    hyperrefoptions:
      - linktoc=all
      - "anchorcolor=green"
      - "pagebackref=true"
      - "breaklinks=true"
    colorlinks: true
    linkcolor: blue
    urlcolor: cyan
    citecolor: red
    filecolor: magenta
    toccolor: red
    keep-tex: true
    link-citations: true
```

Does this get you going?
