### ISSUE TITLE
multiplex secret published in presentation.html

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-cli#209]
1. I create a Quarto presentation from RStudio new file menu.
2. I add

```yaml
format: 
  revealjs:
    multiplex: 
      id: 'ID'
      secret: 'SECRET'
```

to the YAML.
3. I render.
4. In presentation.html I can see the secret.

The [docs](https://quarto.org/docs/presentations/revealjs/presenting.html#multiplex) state

> Note that the secret value will be included in only the speaker version of the presentation.
