### ISSUE TITLE
hash-number not working as expected

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-cli#211]
I suspect it is an option clash of some sort. If I create a presentation and change to the following YAML, slides do not have numbers

```yaml
---
title: "test"
format:
  revealjs:  
    multiplex: true
    self-contained: true
    hash-type: number
    slide-number: true
    controls: auto
    from: markdown+emoji
    menu:
      width: full
---
```

When numbers are used (so, not with these options), I saw the first slide is still "title-slide" while I would expect it to be 1 (or 0).

Docs https://quarto.org/docs/presentations/revealjs/presenting.html#navigation-options
