### ISSUE TITLE
Using metadata under `book` key cannot be referenced anymore

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2148]
the solution from that thread  https://github.com/quarto-dev/quarto-cli/discussions/2060#discussioncomment-3455375 no longer works with the latest version 1.1.132. I've uninstalled that version and gone back to 1.1.57 which works fine with the `book.isbn` solution from the windows terminal. That's a workaround for me now.

_Originally posted by @jpmorr in https://github.com/quarto-dev/quarto-cli/issues/2143#issuecomment-1228607822_

**Comment by cderv** [comment]
@jpmorr I have open a new issue to not clutter the other one. 

Please give more context and possible a reproducible example about the issue from the thread. 

My understanding is that you tried 

````
book:
  title: "My book"
  subtitle: "A really good book" 
  edition: "Third"
  isbn: xxx-xxxxxxxx
  author:
   - name: Mr. Jones
````

Then use `$book.isbn$` in your custom template. And that does not work anymore. Is that the complete issue ?
