### ISSUE TITLE
(Small) Bug: Twitter card description not copied from twitter-card metadata

### ISSUE THREAD

**Issue by dpsimpson** [quarto-dev/quarto-cli#2159]
### Bug description

Hi, 
I _think_ this is a bug and not a case of user error (if it's the latter, sorry!).

I am using the pre-release CLI 1.2.15 on an intel Mac (running 12.5.1) from the command line. This happens with both R and python posts.

I am trying to change the default twitter card (blog_title:title doesn't work for me because my blog has a long and stupid title. The title is also included elsewhere on the card). I can change the title but I can't make the description change. I've tested it on R and Python blogs and blogs with and without rendered maths in the title (because you never know). Both cases read the title from the twitter-card metadata but use the post description rather than the meta-card description.

A minimal reprex is here https://github.com/dpsimpson/blog/tree/quarto_bug

The full .qmd for the post is [(link)](https://github.com/dpsimpson/blog/blob/4103ca2b3762db9c33359c556e7c1518d1b8d643/posts/post_bad/post_bad.qmd)

```
---
title: "$(n-1)$-sane in the membrane (bad twitter card)"
subtitle: |
 Windmills? Tilted. Topic? Boring. (n-1)? No.
date: 10-14-2021
categories: [Teaching, Fundamentals, Opinionated]
twitter-card:
  title: "twitter title"
  description: "twitter description"
  creator: "@dan_p_simpson"
citation: 
  url: https://dansblog.netlify.app/n-sane-in-the-membrane
---
Stuff
```
but the generated html code is [(link)](https://github.com/dpsimpson/blog/blob/4103ca2b3762db9c33359c556e7c1518d1b8d643/_site/posts/post_bad/post_bad.html#L70)

```
<meta name="twitter:title" content="twitter title">
<meta name="twitter:description" content="Windmills? Tilted. Topic? Boring. (n-1)? No.">
<meta name="twitter:creator" content="@dan_p_simpson">
<meta name="twitter:card" content="summary">
```
which is using the default description.

 I can't possibly imagine this being an important bug, but it's slightly odd behaviour.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
