### ISSUE TITLE
Freeze directory not formed on windows 11

### ISSUE THREAD

**Issue by Rahuketu86** [quarto-dev/quarto-cli#2185]
### Bug description

<img width="960" alt="image" src="https://user-images.githubusercontent.com/786803/187203159-ab45f23a-5612-483e-8006-b719c47350dd.png">

 I am generating a blog site with quarto on windows 11 using vscode. Freeze directory is not generated on running quarto render command on cmd.exe or using Quarto render project command in vscode.  (Additionally, I  tried creating a _freeze directory manually before rendering . That directory got deleted after render command was executed)

My _quarto.yml is as follows 

```

project:
  type: website
  pre-render: custom2qmd.py

website:
  title: "qblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
```

and _metadata.yml in posts directory is as follows:-
```

# options specified here will apply to all posts in this folder

# freeze computational output
# (see https://quarto.org/docs/projects/code-execution.html#freeze)
freeze: auto

# Enable banner style title blocks
title-block-banner: true

comments:
  utterances:
    repo: quarto-dev/quarto-docs

```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.
