### ISSUE TITLE
Hugo code folding and linking

### ISSUE THREAD

**Issue by cgoo4** [quarto-dev/quarto-cli#2186]
Would it be possible to enable the quarto options for code folding and linking to the hugo format (as per html)?

```
format: 
  hugo:
    code-fold: true
    code-link: true
```
