### ISSUE TITLE
Enhancement:  Min HTML Template / full reset with no scripts

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#2206]
### Context
In looking to develop a [Format for Confluence](https://github.com/quarto-dev/quarto-cli/issues/2038), I've been investigating a minimal HTML reset format.  It seems that some `link`s can't currently be removed from the HTML format when `minimal=true`.  These scripts would be stripped out by Confluence so it seems wise to update the CLI to support a true HTML reset.

### Steps to Reproduce

1.  Build the following example format

      _extension.yml
      ```yaml
      title: Min HTML Format
      author: Al Manning
      version: 0.0.1
      contributes:
        format:
          html:
            theme: none
            minimal: true
            template: min-template.html
      ```
      
      min-template.html
      ```html
      
      $body$
 
      ```

      min-example.qmd
      ``` quarto
      ---
      title: "Min HTML Format"
      format: min-html
      ---
      ```

2.  Expected Render
      min-example.html
      ``` html
     <html><body></body></html>
      ```

3.  Actual Render

      min-example.html
      ``` html
      <html><head>
      <link href="example_files/libs/quarto-html/quarto-html.min.css" rel="stylesheet" data-mode="light">
      <link href="example_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles"></head><body></body></html>
      ```
