### ISSUE TITLE
Support for revealjs template partials?

### ISSUE THREAD

**Issue by ryanraaum** [quarto-dev/quarto-cli#2236]
### Bug description

While there are no partials in the revealjs pandoc template directory, there *seems* to be some support for them. In particular, if you try to specify a template partial in the document YAML header, such as:

````yaml
format:
  revealjs:
    template-partials:
      - my-partial.html
````

The error that is thrown is:

```
ERROR: The format 'revealjs' only supports the following partials:
metadata.html
title-block.html
toc.html
```

Suggesting that there was at least a thought at some point to support those template partials. However, `template.revealjs` does not support those partials.

BUT, if I copy over `template.revealjs` and edit it to have support for a title block partial like so:

````html
$if(title)$
$title-block.html()$
$endif$
````

And set up my YAML header with:

````yaml
format:
  revealjs:
    template: modified-template.revealjs
    template-partials:
      - title-block.html
````

Then it all works as expected and my custom title block is substituted into the main template.

Is there any plan to make this the default behavior?

(FWIW, I'm trying to do some different title page layouts using grid/flex and while I **can** manage it using some ugly javascript munging, it would be a lot easier and cleaner to just be able to sub in a new title template.)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
