### ISSUE TITLE
website: dark mode as default: toggle to light mode not kept between pages

### ISSUE THREAD

**Issue by jcolomb** [quarto-dev/quarto-cli#2248]
### Bug description

using the element below in _quarto.yml

```
format:
  html:
    theme: 
      dark: darkly
      light: flatly
```
the page shows in dark mode per default, but if toggled to light mode, the site goes back to dark mode when navigating to  a different page.
(This does not happen if light mode is the default)

I tested  safari and firefox on OSX

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by freimanninwt** [comment]
### Bug description

My _quarto.yaml looks quiet similar. I leave out some extras  like book specifications, because I don't think affect this bug:

```
project:
  type: book
  output-dir: "_book"
  execute-dir: project

format:
  html:
    anchor-sections: true
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    code-tools: true
    filters:
      - lightbox
    highlight-style: github
    lightbox: auto
    self-contained: false
    smooth-scroll: true
    theme:
      light: [flatly]
      dark: [darkly]
    toc-depth: 3
    toc: true
```

- klicking on parts and chapters in light mode quickly flickers the list, but it stays in the default light mode
- klicking on parts and chapters in dark mode changes the theme to default

### System
- I use Pop!_OS 22.04 LTS 
- R version 4.3.0 (2023-04-21)
- Quarto version 1.3.238, but a colleague has the same problem for 1.3.353
- generally, I implemented custom.scss for dark and light mode, but removing them doesn't change anything
- tested it with Chrome

Checklist:
 

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
