### ISSUE TITLE
`lang` provided under `format` key not respected when rendering books

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#2285]
When the `lang` is specified under a format, like:

```
format:
  html:
    lang: zh
```

We don't respect that lang when rendering a book (it must instead be at the root level).

See #251

**Comment by dragonstyle** [comment]
Incorrect- this error is still happening as of Quarto 1.3.

**Comment by dragonstyle** [comment]
Note to self: This issue ultimately is a result of the book project context being initialized very early in the rendering process. The book project type synthesizes things like a sidebar for use in a website, and the issue with this is that the synthesized sidebar needs access to localized strings. The `lang` that is active for the format hasn't yet been determined (too early in the rendering process), so we look for a global `lang` flag and use that if present.

We'll need to defer and break up the book initialization to fix this.

**Comment by mcanouil** [comment]
I cannot reproduce on latest Quarto CLI version. I get the expected lang.

I tried at both project and document level of `index.qmd` from `quarto create project book`.

**Comment by cderv** [comment]
If you read carefully about the OP and the last post with root cause, you can reproduce with the following

```
quarto create project book test-book
cd test-book
````

Then change `_quarto.yml` to 

- set a `lang` inside a format
- set a global `lang` to see if this is correctly taken over by format value. 

````yaml
project:
  type: book

book:
  title: "test-book"
  author: "Norah Jones"
  date: "15/07/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
  appendices:
    - references.qmd

lang: zh

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    lang: es
````

And you'll notice

<img width="1423" height="503" alt="Image" src="https://github.com/user-attachments/assets/857a5787-1c29-4650-8945-77e6713f44a5" />


`lang` set on the format is taken into account for the document part like date. 

But for book project part like Appendix (https://quarto.org/docs/books/book-structure.html#parts-appendices), the global lang is still used. I used `lang: zh` to make it obvious. 

So explanation at https://github.com/quarto-dev/quarto-cli/issues/2285#issuecomment-1450817715 is still valid, and this is to be fixed.
