### ISSUE TITLE
Pause within slides in revealjs

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#2302]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2300

<div type='discussions-op-text'>

<sup>Originally posted by **mlarocca-git** September  5, 2022</sup>
I have been a Rmarkdown user for a long time. Recently I switched all Rmarkdown projects to Quarto. 

I have a minor problem and haven't found any solution in previous discussions.

In my reavealjs slides, I use a lot the pause within slides by inserting three dots separated by spaces.

There is no problem when I render a qmd file to HTML format. The "pause operator" does not appear in the final HTML. However, when I render a qmd file to a pdf via latex, the pause operator (the three dots) appears everywhere in the final pdf.

Is there any way to instruct Pandoc to ignore the string ". . ." when producing the final pdf?

Thank you so much for your help.
</div>

**Comment by allenmanning** [comment]
This may be a bug, so I'm opening this issue.

**Comment by mlarocca-git** [comment]
Here is a short reproducible example. I have tried "incremental: true" and "incremental: false".

```
---
title: "Reproducible example"
author: "Author"
date: "`r Sys.Date()`"
format:
  revealjs: 
    navigation-mode: vertical
    controls-layout: bottom-right
    menu: true
    code-fold: true
    html-math-method: katex
    width: 1920
    height: 1080
    incremental: false
  html: 
    code-fold: true
    html-math-method: katex
    self-contained: true
  pdf:
    toc: true
    number-sections: true
    geometry: 
      - top=30mm
      - left=30mm
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. 

. . .

You can embed code like this:

```{r}
x <- rnorm(1000)
plot(x)
```

. . .

You can add options to executable code like this

```{r}
#| echo: false
hist(x)
```

. . .


Compute the mean as

$$
\bar x =\frac{1}{n}\sum{i=1}^n x_i
$$
```
