### ISSUE TITLE
Can quarto specify input format like --read= in pandoc?

### ISSUE THREAD

**Issue by Serenade600** [quarto-dev/quarto-cli#2309]
I am not sure if it's the right place to ask this question. Many issues are about bugs. But any comment is appreciated.

In quarto, the qmd file may contain bit of latex syntax witch can be treated later by pandoc itself or additional filters. The function of filter is introduced by [quarto online guide](https://quarto.org/docs/extensions/filters.html). So my curiosity is could quarto specify input format like this in pandoc
`pandoc -read=latex test.md -o test.docx` for rendering latex (if not specified, the pandoc or filter will nor render it, and the latex syntax is missed in the final docx file). I met something about format like this
```
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png
```
in __quarto.yml_ but I thought it is for output. Am I right?
