### ISSUE TITLE
FR: customization options for cross references in book project

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#2356]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2345

<div type='discussions-op-text'>

<sup>Originally posted by **rgaiacs** September  7, 2022</sup>
It's common for academic articles to have "supplementary material"/"supporting information" that publishers process as a different document. The main article will reference the supplementary material, for example

> Table S1 has additional statistics

Will be great for Quarto to support more customization for cross reference.

# Minimal Working Example

[Download all files](https://github.com/quarto-dev/quarto-cli/files/9522747/mwe.zip)

`_quarto.yml`:

``` 
project:
  type: book

book:
  title: "MWE"
  author: "Raniere Silva"
  chapters:
    - index.qmd
  appendices:
    - data.qmd

crossref:
  appendix-title: "Supporting Information"

format:
  docx:
    toc: false
    number-sections: false
```

`index.qmd`:

```
# Material and Methods

Some text, see @tbl-iris in @sec-data for details.
```

`data.qmd`:

`````` 
# Data Processing {#sec-data}

```{r}
#| label: tbl-iris
#| tbl-cap: Iris

iris |>
  head() |>
  knitr::kable()
```
``````

# Observed Output

![Screenshot from 2022-09-08 09-31-12](https://user-images.githubusercontent.com/1506457/189014070-9ba3369f-8a32-46a0-9b81-a7547a6a2ed0.png)

# Expected Output

- Tables and Figures be numbered with `S` as prefix.

![Screenshot from 2022-09-08 09-36-20](https://user-images.githubusercontent.com/1506457/189014262-5d0d7fa8-e717-4050-8786-bbb3c818104f.png)

</div>
