### ISSUE TITLE
Quarto Website: Prevent margin-sidebar from blocking code copy to clipboard

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#2388]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2173

<div type='discussions-op-text'>

<sup>Originally posted by **nickjhathaway** August 28, 2022</sup>
When creating a Quarto website project with the code copy to the clipboard turned on I noticed that I couldn't actually get to the copy button and it appears to be an issue with the margin-side bar on the right side. When hovering over the code block the clipboard button appears.  

<img width="1053" alt="Screen Shot 2022-08-28 at 2 56 53 AM" src="https://user-images.githubusercontent.com/2828038/187061686-f9780aad-b031-4919-b01f-5893d2b0c3ef.png">

but as you approach it, it then disappears. 
<img width="1061" alt="Screen Shot 2022-08-28 at 2 56 57 AM" src="https://user-images.githubusercontent.com/2828038/187061692-eaa6b8f1-396c-4d22-a397-fe12fff85adc.png">

This seems to happen where the margin-sidebar on the right is. 
<img width="1899" alt="Screen Shot 2022-08-28 at 2 17 19 AM" src="https://user-images.githubusercontent.com/2828038/187061184-58bed578-845e-42d5-8581-8524b5fc0065.png">

When I use the dev tools to delete the sidebar, then I'm able to get over to the copy to clipboard button and I tested this in chrome, firefox, and safari. 

<img width="1141" alt="Screen Shot 2022-08-28 at 2 18 04 AM" src="https://user-images.githubusercontent.com/2828038/187061226-b3cf1333-371b-4b0b-b7fd-a33815b916bd.png">

I'm wondering if I'm doing anything wrong with the setup and if there is anything I can do to fix this. I'm not currently using anything in the right margin sidebar and wonder if there's a straightforward way to just delete it on every page by default, I'm not very familiar with quarto yet.  

My YAML for the site looks like this 

```yaml
project:
  type: website
  output-dir: SeekDeep
  bibliography: references.bib
  resources: ["images"]
  render: 
    - index.qmd
    ...... 
    ...... 
    ...... 
    ...... 

website:
  title: "SeekDeep"
  navbar:
    left:
      - text: "{{< fa home >}} Home"
        href: index.html
    ...... 
    ...... 
    ...... 
    ...... 

format:
  html:
    toc: true
    toc-depth: 4 
    toc-title: Contents
    toc-location: left 
    anchor-sections: true
    smooth-scroll: true
    self-contained: true
    theme: flatly
    highlight-style: textmate
    code-fold: show
    fig-width: 12
    fig-height: 8
    page-layout: full
    bibliography: references.bib
```  
</div>
