### ISSUE TITLE
Quarto doesn't accept date-format in book project

### ISSUE THREAD

**Issue by bhattmaulik** [quarto-dev/quarto-cli#2398]
### Bug description

I am trying to create a quarto book in RStudio. When I add date-format field in the YAML, the book cannot be rendered. When I remove the date-format field, I can render it successfully. A sample YAML specification (in` _quarto.yml` file of the project) is as follows:
```
project:
  type: book

book:
  title: "My Random Book Title"
  author: 
    - name: "Maulik Bhatt"
  date: today
  #date-format: "MMM D, YYYY"
  page-footer:
    border: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
nocite: |
  @*

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    fig-align: center
    fig-width: 6
    fig-height: 5
    fig-pos: 'h'
    fig-cap-location: bottom
    tbl-cap-location: top
    pdf-engine: lualatex
    keep-tex: true
    linestretch: 1.5
    toc: true
    toc-depth: 2
    toc-title: Contents
    lof: true
    lot: true
    number-sections: true
    number-depth: 6
    colorlinks: true
    cite-method: biblatex
    csl: apa7.csl
    callout-appearance: simple
    callout-icon: true
```
When I keep date-format field commented, I can render this book in any format (HTML/PDF), but when I uncomment date-format field, I cannot render it to any format.

My quarto version is 1.2.90, and RStudio version is RStudio 2022.11.0-daily+170 "Elsbeth Geranium" on Windows 10 OS. In the previous version of Quarto, I could render both PDF and HTML while keeping the date-format field also (I prefer either long format or DD/MM/YYYY for the date format).

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
