### ISSUE TITLE
Remove anchor link from sidebar title, or ensure title text is centered

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#24]
Here is my sidebar:

```
  sidebar:
    title: "Quarto Demo"
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
          - url:  https://code.com
          - text: Report a Bug
          - url:  https://bugs.com
```

I don't think the anchor link is actually necessary for that header, but it is also causing the title to not be centered, and the icon alignment looks off because of it:

<img width="665" alt="Screen Shot 2021-04-23 at 10 19 40 AM" src="https://user-images.githubusercontent.com/12160301/115907378-a4c03980-a41d-11eb-8c28-3605d9fd7d7e.png">

The subtitle is centered because it does not have a header tag, and hence no anchor link.
