### ISSUE TITLE
Website sidebar auto generation renders differently on Windows vs Linux

### ISSUE THREAD

**Issue by RalfG** [quarto-dev/quarto-cli#2409]
## Description

Using the sidebar auto generation feature, I get different results between Windows and Linux. I have two nested folder structures with `index.qmd` files along content files for each section. On Windows, the index pages are added to the sidebar as expected, while on Linux, they are omitted.

## Side-by-side comparison

![quarto-sidebar-both](https://user-images.githubusercontent.com/26458971/189691363-a97ee3f1-dcf3-4a2a-b9ac-e485edc06e0a.png)

## Version and OS info

Using Quarto v1.2.90 on
- Windows 11 Pro 21H2 build 22000.856
- Ubuntu 20.04.3 LTS through WSL2
- GitHub Actions `ubuntu-latest` using the official quarto-setup action

## Minimal, fully reproducible example

Directory structure:
```
.
├── _quarto.yml
├── home.qmd
└── section1
    ├── index.qmd
    ├── page1.qmd
    └── page2.qmd
```

`_quarto.yml`
```yml
project:
  type: website

website:
  sidebar:
    contents:
      - text: "Home"
        file: home.qmd
      - "---"
      - auto: section1
```

`home.qmd`
```md
# Home
Homepage content
```

`section1/index.qmd`
```md
# Section 1
Section 1 content
```

`section1/page1.qmd`
```md
# Page 1
content page 1
```

`section1/page2.qmd`
```md
# Page 2
content page 2
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jjallaire** [comment]
Thanks for reporting! This is fixed here: https://github.com/quarto-dev/quarto-cli/commit/5a0779465211a488df96de3dee50281be2284072

Should be available in our next v1.2 pre-release (in ~ 1hr) which you'll be able to get here: https://quarto.org/docs/download/prerelease.html

For better or worse, the Linux behavior is what is intended. If you want the Windows behavior you will need to do this instead:

```yaml
website:
  sidebar:
    contents:
      - text: "Home"
        file: home.qmd
      - "---"
      - section: Section 1
        contents: section1
```

**Comment by elgabbas** [comment]
Hello,

I think I am having the same issue using quarto 1.3.18 on windows. Has this issue already been solved @jjallaire ? 

I am trying to use auto page generation to list pages using a glob. The resulting list shows the parent folders, which is not what I need. Here, I am using `- auto: "section1/section1_1/page*"` to list all files starting with the word 'page' in the folder 'section1/section1_1/'

![image](https://user-images.githubusercontent.com/7375051/203078156-70f12bd8-0e73-4bf3-b9f0-59cce89ba96c.png)

The correct pages were listed, but as a tree with all parent subfolders. Is there a way to suppress this and only keep the resulting pages?

***

For example, I want to have a section called `Section1`, and beneath it, I want to use `"section1/section1_1/index.qmd` first and then automatically create pages from a subdirectory (**"section1/section1_1/"**, without mentioning their parents): any page starting with `page_C`, then all pages start with `page_A`. 

```
      - section: "Section1"
        contents:
          - "section1/section1_1/index.qmd"
          - auto: "section1/section1_1/page_C*.qmd"
          - auto: "section1/section1_1/page_A*.qmd"
```

Thanks, Ahmed
