### ISSUE TITLE
chunk options conditional to output format ? 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2416]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2411

<div type='discussions-op-text'>

<sup>Originally posted by **shabbychef** September 12, 2022</sup>
Hi,
I _think_ in quarto I can set default options in the header YAML via something like:
```
format:
  html:
    out-width: "625px"
    out-height: "402px"
    fig-format: png
    fig-width: 10.0
    fig-height: 6.43
  pdf:
    fig-width: 11.5
    fig-height: 6.8
```

Is it possible to override these in a chunk in a way that is by output type? It seems that I can only override these options absolutely, and not conditionally on the output type.

thanks,
</div>

This was also tried 

````
```{r 'plot_foo'}
#| html: out-width: "625px"
#| html: out-height: "402px"
#| pdf: out-width: "\\textwidth"
#| pdf: out-height: "0.64\textwidth"
````
````
