### ISSUE TITLE
Website: Pagination/filter not working when categories is set to false?

### ISSUE THREAD

**Issue by giabaio** [quarto-dev/quarto-cli#2466]
### Bug description

Hi all,
I can provide more detailed reprex but I wonder whether this is something that has been explored and has a simple solution? In a nutshell, in a listing page, if I set `categories` to `false`, the pagination and filter box still appear on the page, but they are not clickable. The first page of the many that get created (because I set `page-size: 7`) are simply not shown.

When I set `categories` to `true`, then things work as expected; I can use the filter by clicking on the box and typing whatever I want and I can click on the numbers to navigate to the other group of items.

Is this an obvious bug?
Thanks

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
It doesn't seem quite as simple as just turning off categories. The following listing page (for me) supports sorting and filtering without issue:

```
---
title: Test Listing
listing: 
  - id: post
    contents: "blog/**/*.qmd"
    feed: true
    categories: false
    sort:
      - "date desc"
    max-description-length: 250
    filter-ui: true
    sort-ui: true
    page-size: 3
page-layout: full
title-block-banner: true
---

::: {#post}
:::
```

I tried various types of listings. If you have an example with source I could look at that would help immensely.
