### ISSUE TITLE
Numbered appendix causes extra dot in figure and table captions

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#247]
For example, take the book template with quarto 0.2.438 and add an `appendices` line in the `_quarto.yml`:

```
book:
  title: "d" 
  author: "Jane Doe"
  date: "1/6/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
  appendices:             # <-- add this line
    - references.qmd
```

Then edit `intro.qmd` to add a table with caption:

```
# Introduction

This is a book created from markdown and executable code.

|a|b|
|-|-|
|1|2|

: Some table.

See @knuth84 for additional discussion of literate programming.                                                          
```

and edit `references.qmd` to enable numbering:

```
# References

::: {#refs}
:::
```

The PDF now has an extra `.` after the table number:

![image](https://user-images.githubusercontent.com/2412819/148379048-8fdc6f50-8efd-4fb6-9857-c6ba23e6e38d.png)

Here we have "Table 1.1.:" instead of "Table 1.1:" (there is also some vertical space missing between the caption and the table, but I don't have that problem in my real document for some reason).

The extra dot also appears in figure captions.
