### ISSUE TITLE
Empty callout leads to an error in PDF

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [quarto-dev/quarto-cli#252]
While a callout without content doesn't make much sense in the end-document, this may be the case during working on the text. 

A repro example: 

```
---
title: Title
author: User
date: 05/01/22
format: 
    pdf: 
        pdf-engine: pdflatex
        fontenc: T2A
        header-includes:
        - \usepackage{amsmath}
---
## Section
::: {.callout-warning}

:::
```

`$ quarto render sample.qmd` yields 
```
Error running filter C:/Users/User/AppData/Local/Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:
.../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:2542: attempt to index a nil value (field '?')     
stack traceback:
        .../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:2542: in function 'calloutLatex'
        (...tail calls...)
        .../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:699: in function <.../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:693>
```

This is both on `xelatex` and `pdflatex` from quarto's tinytex of  `v2022.01`. 
On quarto 0.2.399
pandoc 2.16.2
Compiled with pandoc-types 1.22.1, texmath 0.12.3.3, skylighting 0.12.1,
citeproc 0.6, ipynb 0.1.0.2

Empty callouts in `.docx` and `.html` files do not cause issues.
