### ISSUE TITLE
twitter-card doesn't render `twitter:site` metadata which prevents cards from being rendered on Twitter

### ISSUE THREAD

**Issue by radekosmulski** [quarto-dev/quarto-cli#2544]
### Bug description

I have the following information in my `_quarto.yml`:
![image](https://user-images.githubusercontent.com/2444926/191661563-a9fbd219-0906-4c75-a685-acdeb9d13b4b.png)

But when you go to my website: https://www.tabularmusings.com/, you can see that the twitter-card site information is not rendered in the header:
![image](https://user-images.githubusercontent.com/2444926/191661741-03490d36-ad21-4c25-88d5-68524339255b.png)

I checked another quarto blog (https://www.fast.ai/) and their site information also doesn't appear in the header.

Twitter card validator fails to render a card for either of the blogs as `twitter:site` is [a required piece of metadata](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup).

Including my full `_quarto.yml` per instructions below:
```

project:
  type: website

website:
  title: "tabularmusings"
  site-url: "https://www.tabularmusings.com"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/radekosmulski
      - icon: github
        href: https://github.com/radekosmulski
  twitter-card:
    site: "@radekosmulski"
    creator: "@radekosmulski"
  open-graph: true

format:
  html:
    theme: cosmo
    css: styles.css

execute:
    freeze: true
```

I am not using RStudio. I am using the following version of quarto: 1.1.189. I am deploying on netlify using the quarto plugin.

This is my OS version: Ubuntu 22.04.1 LTS

Thank you for your help! 🙂 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
