### ISSUE TITLE
Website listings - filter by category

### ISSUE THREAD

**Issue by kmasiello** [quarto-dev/quarto-cli#2577]
I'd like to use Listings to present specific content on a page based on either category or tag (I'll use which ever is easier to implement).  
I can almost get there today -- with `categories: true` as a site visitor I can click on a category and see my filtered list of content, however, I don't want this to be a site visitor action, as the site author I want to only show certain content based on tag. 

Ultimately I want to have a page with multiple listings, each listing defined by category.

**Comment by stevelinberg** [comment]
I'd add that it would be nice to be able *exclude* certain categories, like omitting blog posts with the "personal" category from a front-page post listing that wants to present a focused list of only non-personal posts.

**Comment by dragonstyle** [comment]
The next pre-release will support this, like:

```yaml
listing:
  contents: posts
  type: grid
  include:
    author: "{Harlow,Tristan}*"
  exclude:
    author: "Charles*"
```

or

```yaml
listing:
  contents: posts
  type: grid
  include:
    categories: [news, code]
  exclude:
    author: “Charles Teague”
```

String matching will be done using glob syntax, other types will use equality to match.
