### ISSUE TITLE
Cannot include resources

### ISSUE THREAD

**Issue by chadyuu** [quarto-dev/quarto-cli#2706]
## Issue
In `_quarto.yml`, `resources` data after `output-dir` does not work.

Below is an example of `_quarto.yml` that does not include `test.html` in the `docs` directory.
```
project:
  type: website
  output-dir: docs
  resources: 
    - "test.html"
```

This is an example that works as expected.
```
project:
  type: website
  resources: 
    - "test.html"
  output-dir: docs
```

## My environment
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_5_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
