### ISSUE TITLE
Author email not showing up

### ISSUE THREAD

**Issue by jmh530** [quarto-dev/quarto-cli#2751]
### Bug description

I am trying to get the author email to show up in the output of a Quarto file (using RStudio 2022.07.2 on Windows 10 with a version of Quarto I got off the website with the past week (I see v1.1.251 now, might be the same).

The default option below did not seem to work.

```yaml
---
title: "title"
author:
  - name: "Name"
    email: "XXX@test.com"
format: html
editor: visual
---
```
Next, I tried to use a lua filter from Pandoc based on what is described [here](https://github.com/quarto-dev/quarto-cli/issues/287#issuecomment-1116392282)), but this doesn't seem to be working for me either. 

Pandoc option
```yaml
---
title: "title"
author:
  - name: "Name"
    correspondence: "yes"
    email: "XXX@test.com"
format: html
editor: visual
filters:
  - build/scholarly-metadata.lua
  - build/author-info-blocks.lua
  - quarto
---
```
I also tried using `true` for correspondence and that doesn't work either. 

I copied the `scholarly-metadata.lua` and `author-info-blocks.lua` files from pandoc's github [repository ](https://github.com/pandoc/lua-filters)to a subfolder of the directory that the `qmd` file is in. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
