### ISSUE TITLE
Biblatex extra header

### ISSUE THREAD

**Issue by lcnhb** [quarto-dev/quarto-cli#2770]
### Bug description

When writing a book and using biblatex for the pdf bibliography, the latex automatically generates the section called bibliography. However, if I also am generating a website, this uses citeproc with a user setup section, called e.g. references. Thus the PDF version has both a references section (devoid of content) and a bibliography after this. How can I either not have a heading in biblatex or use citeproc with numbers? Additionally, if I go the biblatex route and have margin content enabled, how could I remove it for the autogenerated bibliography section, such that the bibliography can span the full width of the document?

**Comment by dragonstyle** [comment]
You should be able to target `cite-method` per format. For example:

```
---
title: My Document
format:
  pdf:
    cite-method: bib latex
  html:
    cite-method: citeproc
    css: apa.csl
```
