### ISSUE TITLE
Navbar right only works if left also present

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#28]
My YAML:

```
site:
  navbar:
    type: light
    right:
      - text: "Home"
        file: index.Rmd
      - text: why
```

Looks like:
<img width="1134" alt="Screen Shot 2021-04-23 at 1 41 35 PM" src="https://user-images.githubusercontent.com/12160301/115927771-d0e9b380-a439-11eb-89c3-59c9fcf5e75b.png">

If I add any left element:
```
site:
  navbar:
    type: light
    left: 
      - text: on your left
    right:
      - text: "Home"
        file: index.Rmd
      - text: why
```

Then the other elements correctly move to the right.
<img width="1099" alt="Screen Shot 2021-04-23 at 1 44 15 PM" src="https://user-images.githubusercontent.com/12160301/115927884-042c4280-a43a-11eb-9609-d25974d7579a.png">
