### ISSUE TITLE
Logo-href doesn't work

### ISSUE THREAD

**Issue by d-chambers** [quarto-dev/quarto-cli#2810]
### Bug description

Hello, 

The logo-href of the website/navbar option doesn't work. 

For example, if I create a new website template with 

```bash
quarto create-project mysite --type website
```

Then modify the _quarto.yml file like so:

```
project:
  type: website

website:
  title: "mysite"
  navbar:
    logo-href: about.qmd
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

```

The index.qmd content still shows up when I click on the title in the upper navbar (rather than the contents of about.qmd).

I am using the latest pre-release build of quarto 1.2.207. I am simply using the command line (no R studio) on Ubuntu 20.04. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
