### ISSUE TITLE
Document language-specific custom translations

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#2812]
I was going to request a feature but it turns out the following already works:

```
---
title: Title
author: John Doe
lang: fr
language: translations.yml
---

Text.
```

and in `translations.yml`:

```
de:
    title-block-author-single: Autor
fr:
    title-block-author-single: Auteur
```

Specifying `lang: fr` or `lang: de` picks up the right value from `translations.yml`, and `lang: en` uses the non-customized English as expected.

I don't think the documentation mentions that translations can be customized for different languages like this. I find it very useful (see use case in https://github.com/quarto-dev/quarto-cli/discussions/2796 ). Is this officially supported, and if yes would you like a PR for the documentation?
