### ISSUE TITLE
revealjs ul style preferred to task-list style

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#2834]
### Bug description

Using Quarto 1.2.209 rendered on macOS from the CLI; this is the Quarto version included in one of the most recent RStudio dailies.

Quarto with revealjs sees the revealjs style used rather than the default task-list style injected into the document. This is because the `.reveal ul` scoped CSS is preferred over the top-level CSS injected by Quarto+Pandoc.

````markdown
---
title: task list with reveal
format: revealjs
---

## tasks

- [x] wake up
- [ ] brush teeth
- [ ] drink coffee
````

As rendered, you can see both the original list icons and the check-boxes as rendered on Safari. Only the check-boxes should be displayed and they should be more prominent.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/362187/195606696-965bcc97-1c2f-4830-85d4-0f7879ac6a08.png">

I am locally using these override styles; they're imperfect, but an improvement.

```css
.reveal ul.task-list{list-style: none;}
.reveal ul.task-list li input[type="checkbox"] {
    width: 2em;
    height: 2em;
    margin: 0 1em 0.5em -1.6em;
    vertical-align: middle;
}
.reveal ul.task-list li input[type="checkbox"][disabled] {
    outline:1px solid lightgrey;
}
.reveal ul.task-list li input[type="checkbox"][disabled][checked] {
    outline:2px solid green;
}
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report. This looks so ugly with our existing CSS that I think your override styles would be a valid addition. Any chance you want to send a PR our way?

**Comment by aronatkins** [comment]
I'm not sure how that style would be threaded in. By "local override", I mean that I have style for my document:

```markdown
---
format:
  revealjs:
    css: styles.css
---
```

```css
.reveal ul.task-list{list-style: none;}
.reveal ul.task-list li input[type="checkbox"] {
    width: 2em;
    height: 2em;
    margin: 0 1em 0.5em -1.6em;
    vertical-align: middle;
}
.reveal ul.task-list li input[type="checkbox"][disabled] {
    outline:1px solid lightgrey;
}
.reveal ul.task-list li input[type="checkbox"][disabled][checked] {
    outline:2px solid green;
}
```

It almost feels as if we want to avoid checkbox `input` elements entirely and use some nicer presentation for task-lists, but I'm not sure what's Quarto and what's Pandoc in this situation.
