### ISSUE TITLE
[Feature request] Sidebar toc on every slide in revealjs-presentation

### ISSUE THREAD

**Issue by cathblatter** [quarto-dev/quarto-cli#286]
Hi

Thank you so much for this wonderful product - a passionate Rmd user and now with options for more - fantastic!🎊👏

I was wondering if there is a possiblitiy to implement a sidebar toc in revealjs-presentations similar to latex-beamer ([hannover theme](https://deic.uab.cat/~iblanes/beamer_gallery/large/Hannover-default-default-02.png) ? I know that I can toggle the menubar/toc with 'm' but I was more wondering about implementing it on the slides for the users to see along the presentation?

(I am posting this here instead of xaringan because the toc-request in [xaringan](https://github.com/yihui/xaringan/issues/217) was implemented here)

Again, thanks for the great work!😃

**Comment by jjallaire** [comment]
Yes this would indeed be a great addition! Here's an existing Reveal plugin that does something similar to what you are suggesting (LMK if I'm off base): https://e-gor.github.io/Reveal.js-TOC-Progress/demo/#/

Note that I don't think that plugin would work unmodified w/ Quarto Revealjs as we are already messing around w/ the footer in other ways.

**Comment by henryherkula** [comment]
Here is a small workaround for the YAML options. This creates a TOC in the bottom right on every slide (using the global footer) and removes the TOC slide afterwards.

```
format: 
  revealjs:
    toc: true
    footer: "<div id='toc-footer' style='position: absolute; right: 0; bottom: 0; padding: 1rem;'><ul></ul></div>"
include-after-body:
  text: <script type="text/javascript">document.querySelector("div#toc-footer ul").innerHTML = document.querySelector("#TOC ul").innerHTML; document.querySelector("section#TOC").remove();</script>
```
