### ISSUE TITLE
Anonymous figure and default-image-extensions don't work together

### ISSUE THREAD

**Issue by lcnhb** [quarto-dev/quarto-cli#2877]
### Bug description

When I include an anonymous figure without extension i.e. `![](test)`, and I have the default extensions set for pdf and html output in a book I get the following error 

```
Error running filter /opt/quarto/share/filters/quarto-post/quarto-post.lua:
/opt/quarto/share/filters/quarto-post/quarto-post.lua:2277: attempt to index a nil value (field 'attr')
stack traceback:
        /opt/quarto/share/filters/quarto-post/quarto-post.lua:1119: in function </opt/quarto/share/filters/quarto-post/quarto-post.lua:1113>
```

my _quarto.yml has the following shape:

```
project:
  type: book

book:
  title: "mwebib"
  author: "Jane Doe"
  date: "10/10/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cite-method: citeproc
    default-image-extension:  svg
  pdf:
    documentclass: scrreprt
    cite-method: biblatex
    default-image-extension:  tex
```

**Comment by lcnhb** [comment]
It seems it is specific to tex as pdf extensions..

**Comment by cscheid** [comment]
Can you share a minimal full example we can test ourselves?

**Comment by julianmatthewman** [comment]
Hi,

I encountered a very similar error, where I was able to render to HTML but not Word or PDF:

> Error running filter /Applications/quarto/share/filters/quarto-init/quarto-init.lua:
> ...cations/quarto/share/filters/quarto-init/quarto-init.lua:240: attempt to index a nil value (global 'text')
> stack traceback:
> 	...cations/quarto/share/filters/quarto-init/quarto-init.lua:10: in local 'fn'
> 	...cations/quarto/share/filters/quarto-init/quarto-init.lua:548: in function <...cations/quarto/share/filters/quarto-init/quarto-init.lua:542>

It also related to figure paths, however not to whether the figure was named or not; in my case I was referring to a figure in a subfolder in a .qmd file that was itsself in a different subfolder. Below a minimal example:

Folder structure:
```
├ quarto.yml
├ index.qmd
├ figures/
├── image.png
├ documents/
├── doc_with_figure.qmd
```

quarto.yml:
```
project:
  type: book
  execute-dir: project

book:
  chapters:
    - index.qmd
    - documents/doc_with_figure.qmd

format:
  html:
    theme: cosmo
  docx:
    toc: true
  pdf:
    toc: true

```

In doc_with_figure.qmd:
`![](/figures/image.png)` renders correctly to HTML but not to PDF or Word.
`![](../figures/image.png)` renders correctly to all formats.

So the `execute-dir: project` option only seems to be working for the HTML format but not PDF or Word.
