### ISSUE TITLE
Website listings - supplement auto content with custom metadata

### ISSUE THREAD

**Issue by kmasiello** [quarto-dev/quarto-cli#3071]
@cscheid per our conversation - 

When working with custom ejs formats for content listings I find myself wanting to add additional metadata. However I am limited to either using the default metadata available from auto content listings (ref: https://quarto.org/docs/websites/website-listings.html#listing-fields) OR defining my own custom metadata that's passed into the ejs format (ref: https://quarto.org/docs/websites/website-listings.html#listing-fields).  However if I use the latter, I lose access to the default metadata from the former. 
Would like to be able to add additional metadata to content listings using a format like: 

```
listing:
  - id: sample
    template: custom.ejs
    contents:
      - auto: content-folder
        custom-field: "custom metadata I want to add"

```
