### ISSUE TITLE
Broken output from a Julia chunk

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3093]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3091

<div type='discussions-op-text'>

<sup>Originally posted by **sje30** October 28, 2022</sup>
Using quarto 1.1.251 with the following file:

````
---
title: "test of julia"
author: "SJE"
engine: jupyter
execute:
  echo: true
format:
  beamer:
    keep-tex: true
    monofont: "JuliaMono"
---

## Test slide

```{julia} 
println(typeof(ones(3,2)))
```

````

generates the following output
<img width="592" alt="Screenshot 2022-10-28 at 16 56 15" src="https://user-images.githubusercontent.com/1095067/198680965-0007c6af-7674-404c-a9c3-af4d5dfa3100.png">

Here is the relevant .tex chunk

```

\begin{verbatim}
Matrix{
\end{verbatim}

\begin{verbatim}
Float64}
\end{verbatim}
```

whereas it should read `Matrix{Float64}`
</div>

**Comment by cscheid** [comment]
Repro without font dependencies:

## 3091.qmd

````
---
title: "test of julia"
author: "SJE"
engine: jupyter
execute:
  echo: true
format:
  beamer:
    keep-tex: true
    keep-md: true
    keep-ipynb: true
---

## Test slide

```{julia}
println(typeof(ones(3,2)))
```
````

Note the broken generated .md:

## 3091.md

````
---
title: "test of julia"
author: "SJE"
engine: jupyter
execute:
  echo: true
format:
  beamer:
    keep-tex: true
    keep-md: true
    keep-ipynb: true
---


## Test slide

::: {.cell execution_count=1}
``` {.julia .cell-code}
println(typeof(ones(3,2)))
```

::: {.cell-output .cell-output-stdout}
```
Matrix{Float64}
```
:::
:::
````

Note that this doesn't come from the .ipynb file:

## 3091.ipynb

```json
{
 "cells": [
  {
   "cell_type": "raw",
   "id": "5f94bb0c",
   "metadata": {},
   "source": [
    "---\n",
    "title: \"test of julia\"\n",
    "author: \"SJE\"\n",
    "engine: jupyter\n",
    "execute:\n",
    "  echo: true\n",
    "format:\n",
    "  beamer:\n",
    "    keep-tex: true\n",
    "    keep-md: true    \n",
    "    keep-ipynb: true\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8dcfd405",
   "metadata": {},
   "source": [
    "## Test slide\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d825d8ac",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Matrix{Float64}\n"
     ]
    }
   ],
   "source": [
    "println(typeof(ones(3,2)))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Julia 1.6.7",
   "language": "julia",
   "name": "julia-1.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

Somehow we seem to be breaking the stdout output where we shouldn't.
