### ISSUE TITLE
Listing field not inherited from global _quarto.yml

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#3121]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3088

<div type='discussions-op-text'>

<sup>Originally posted by **kris-brown** October 28, 2022</sup>
Hi, I have a global `_quarto.yml` with a `date: last-modified` line which applies to all the `.qmd` files in my project. 

I then have a listing in my project:
```
listing: 
  categories: true
  type: table
  fields: [title, categories, date]
```
But the `date` field is rendered empty unless I explicitly put `date: last-modified` in the corresponding files. Is there anything I can do such that the listing defaults to the global `yml` file when a field isn't found?
</div>
