### ISSUE TITLE
Affiliation header/label is "empty" thus no longer displayed in v1.2

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#3125]
### Bug description

Using Quarto v1.2.253, the following document does not display affiliation header/label.

```
---
title: "Hello world"
author:
  - name: Bill Gates
    orcid: 0000-0003-1689-0557
    email: bill@gates.com
    affiliations:
      - name: Bill & Melinda Gates Foundation
        address: 440 5th Ave N
        city: Seattle
        state: WA
        postal-code: 98109-4631
format: html
---
```

For some reason, the affiliation label is empty.
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/8896044/199118843-191b7705-0389-4c21-bcba-58c50fd37c48.png">

From Quarto v1.1.251

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/8896044/199119123-06190c2c-7755-4e2c-b57f-5eab32c6a7cc.png">

This seems to be related to authors/affiliations scheme changes since the template file did not change.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
