### ISSUE TITLE
number-offset does not work with pdf output

### ISSUE THREAD

**Issue by thedabs91** [quarto-dev/quarto-cli#3126]
I tried to render pdf with number-offset. The document seemed to run, but produced the error message:

Aeson exception:
Error in $: parsing [] failed, expected Array, but encountered Number

When I changed output to html or removed number-offset, the code worked. A short .qmd script that produced the error is below:

```
---
title: "Title"
author: "Author"
format:
  pdf:
    number-sections: true
    number-offset: -1
---

## Introduction

## The Methods

### Loading Data

### Computing methods

## Results
```

FYI, I am using quarto on a 64-bit Windows 11 machine, and the LaTeX installation is tinytex.
