### ISSUE TITLE
ERROR: No _publish.yml file available for GitHub pages CI

### ISSUE THREAD

**Issue by maikol-solis** [quarto-dev/quarto-cli#3147]
### Bug description

Hi!

I have a website with control version in GitHub. I want to include a CI process to render it every time I push something. 

Following the docs for GitHub pages (https://quarto.org/docs/publishing/github-pages.html#github-action) I copy-pasted this into `.github/workflows/publish.yml`

```yaml
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]

name: Quarto Publish


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

However, I'm getting this error in every action in the `Render and Publish` part 

```
ERROR: No _publish.yml file available (_publish.yml specifying a destination required for non-interactive publish)
Error: Process completed with exit code 1.
```

The full output is here
<details>

```
Run quarto-dev/quarto-actions/publish@v2
  with:
    target: gh-pages
    GITHUB_EMAIL: quarto-github-actions-publish@example.com
    GITHUB_USERNAME: Quarto GHA Workflow Runner
    path: .
    render: true
  env:
    BUNDLE_EXT: linux-amd64.deb
    GITHUB_TOKEN: ***
Run git config --global user.email "quarto-github-actions-publish@example.com"
  git config --global user.email "quarto-github-actions-publish@example.com"
  git config --global user.name "Quarto GHA Workflow Runner"
  TARGET=""
  if [ "$TARGET" == "" ]; then
    TARGET="gh-pages"
  fi
  if [ "true" != "true" ]; then
    quarto publish $TARGET . --no-render
  else
    quarto publish $TARGET .
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    BUNDLE_EXT: linux-amd64.deb
    GITHUB_TOKEN: ***
    CONNECT_SERVER: 
    CONNECT_API_KEY: 
    NETLIFY_AUTH_TOKEN: 
    QUARTO_PUB_AUTH_TOKEN: 
  
ERROR: No _publish.yml file available (_publish.yml specifying a destination required for non-interactive publish)
Error: Process completed with exit code 1.
```

</details>

Netlify requires a `_publish.yml` to work properly, but there is no documentation about this file for GitHub. 

Am I making some mistake somewhere?

Thanks in advance. 

Best. 

**System:**
- quarto Version: 1.2.256
- OS: MacOS 13.0

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
