### ISSUE TITLE
engine: should be respected globally at the _quarto.yml level

### ISSUE THREAD

**Issue by jthomasmock** [quarto-dev/quarto-cli#3157]
### Bug description

In the `_quarto.yml` file, setting `engine: knitr` or any variants (`jupyter: python3`, etc) should apply as the default for any files unless modified in the subsequent file's YAML.

On M1 Pro Mac running MacOS Monteray.

Using RStudio Version 2022.12.0-preview+303 (2022.12.0-preview+303)

Quarto v1.2.242

Reprex:

1. Create a project
```bash
quarto create-project test-engine
```

2. Set `engine: knitr` in the `_quarto.yml`

```yaml
project:
  type: website

website:
  title: "test-engine"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

engine: knitr #<- this is the change
```

2. Change a chunk in the `index.qmd` to `python`:

````
```{python}
1+1
```
````

3. `quarto render`

The render of `index.qmd` is done within a Jupyter kernel via `reticulate` even with the `engine: knitr` set at global/`_quarto.yml` level. The correct behavior would be to use `knitr` since that is set at the global level.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
