### ISSUE TITLE
Alignment of mermaid diagrams

### ISSUE THREAD

**Issue by VMTdeJong** [quarto-dev/quarto-cli#3294]
### Bug description

My apologies if i put this on the wrong page, or if it should be a feature request. I have not been able to find documentation for aligning mermaid diagrams.

Mermaid diagrams appear to be left-aligned for html and docx outputs. I can't change this with `fig-align: center` in the yml file, nor with `%%| fig-align: center` in the mermaid code.

For pdf, `fig-align` appears to work as intended in the yml, but not in the mermaid code.

````
project:
  type: book

book:
  title: "Mermaid alignment"
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
    fig-align: center
  docx:
    fig-align: center
  # pdf:
  #   documentclass: scrreprt
  #   fig-align: right

editor: source
````

````
```{mermaid}
%%| fig-cap: Mermaid diagram
%%| fig-align: center
flowchart TB
a --> b 
b --> c
```
````

Versions
- quarto version 1.2.269
- R version 4.2.2 (2022-10-31 ucrt)
- Platform: x86_64-w64-mingw32/x64 (64-bit)
- RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Windows
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

Output
html:
![html](https://user-images.githubusercontent.com/30228864/201351396-e4a41862-b626-4f27-ab0c-320b125b623d.png)

docx:
![docx](https://user-images.githubusercontent.com/30228864/201351429-a8903922-59f9-4bf7-805a-df929ad2d29e.png)

pdf (when not commented out): 
![pdf](https://user-images.githubusercontent.com/30228864/201351457-90460378-610f-422b-93e5-553402e0b1c3.png)

repo
https://github.com/VMTdeJong/Quarto-mermaid-align 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
