### ISSUE TITLE
Use WinGet Releaser for automated releases to winget-pkgs

### ISSUE THREAD

**Issue by russellbanks** [quarto-dev/quarto-cli#3334]
[WinGet Releaser](https://github.com/vedantmgoyal2009/winget-releaser) is a workflow that automatically creates manfiests for [winget-pkgs](https://github.com/vedantmgoyal2009/winget-releaser) and creates a PR for it. It would look a bit like this:

```yaml
name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: RStudio.quarto
          token: ${{ secrets.WINGET_TOKEN }}
```
