### ISSUE TITLE
Option for content-dir in `_quarto.yml`

### ISSUE THREAD

**Issue by akgold** [quarto-dev/quarto-cli#335]

**Comment by winniehell** [comment]
from my point of view it would be a better decision to have the directory below the `chapters` key because that would also allow for multiple subdirectories:

```yaml
chapters:
- introduction.qmd
- material-and-methods:
  - field-survey.qmd
  - laboratory.qmd
- results:
  - data.qmd
  - models.qmd
```

which would be equivalent to the flattened:

```yaml
chapters:
- introduction.qmd
- material-and-methods/field-survey.qmd
- material-and-methods/laboratory.qmd
- results/data.qmd
- results/models.qmd
```
