### ISSUE TITLE
Can not hide search from a quarto website project's navbar

### ISSUE THREAD

**Issue by elgabbas** [quarto-dev/quarto-cli#3369]
### Bug description

Hello,
I am trying to switch off the search button in a quarto website project using `search: false`. It does not work in the **navbar**, but works as expected in the **sidebar**.

Thanks, Ahmed

```
project:
  type: website

website:
  title: ""
  navbar:
    search: false
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
You should be able to disable search for a site using:

```yaml
website:
  search: false
```

(note that this isn't under the `navbar` key)

**Comment by elgabbas** [comment]
Thanks @dragonstyle..... But this will also overwrite the search option for `sidebar`, isn't it?

**Comment by dragonstyle** [comment]
That will disable search across the site. If you just want to move search from the navbar to the sidebar, you could use:


```yaml
website:
  search:
    location: sidebar
```

Is that what you're looking for?
