### ISSUE TITLE
out-width is ignored if fig-width is also set in _quarto.yml

### ISSUE THREAD

**Issue by fruchtblase** [quarto-dev/quarto-cli#3370]
### Bug description

Dear Quarto Team,

I encountered an annoying bug in Quarto.
To reproduce this bug:

1. create a book with `quarto create project book`
2. put an R chunk producing a figure in one of the chapters
3. set fig-width: 3 and out-width: "85%" in pdf section of format in _quarto.yaml
4. render project

Hope this reports helps to make the software even better :)

![grafik](https://user-images.githubusercontent.com/10699549/202713510-cad2dffe-ae16-4941-ac1d-d2b8012274f8.png)

Quarto 1.2.269 on Windows 10 (command line)
issue persists after installing Version 1.3.11

````
project:
  type: book

book:
  title: "repex"
  author: "Jane Doe"
  date: "18/11/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    fig-width: 3
    out-width: "85%"

````

````
# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.


```{r}
#| label: fig-test
#| fig-cap: This is a test
#| echo: false
library(ggplot2)

  ggplot(mtcars, aes(x = cyl, y = mpg)) + 
  geom_violin(aes(group = cyl, colour = factor(cyl)))

```
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
