### ISSUE TITLE
Document unsupported knitr chunk options

### ISSUE THREAD

**Issue by allenmanning** [quarto-dev/quarto-cli#3371]

**Comment by mcanouil** [comment]
In addition, `dev.args` (supposed to be a list in R) might not be that trivial to setup custom `dev` such as `ragg` or `svglite`, for example to use the `scaling` parameter.

```
knitr:
  opts_chunk:
    dev: ragg_png
    dev.args:
      - scaling: 1
```

From <https://quarto.org/docs/computations/r.html#knitr-options> and <https://quarto.org/docs/reference/cells/cells-knitr.html>, this is less clear.

Is the below YAML actually working?

```
knitr:
  opts_chunk:
    fig-width: 6
    fig-height: 4.25
    fig-align: center
```

The `knitr` options use dots and from <https://quarto.org/docs/computations/r.html#knitr-options>, it is kind of implied that in `knitr.opts_chunk` the options take the "dot" format.

```
knitr:
  opts_chunk:
    fig.width: 6
    fig.height: 4.25
    fig.align: center
```
