### ISSUE TITLE
root-relative hrefs in template links are not resolved properly

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3404]
This, in a website, will generate links to `/cv.pdf` and `/blog.html` regardless of the root directory of the website:

````
---
about:
  template: trestles
  links:
    - text: Blog
      url: "/blog.html"
    - text: CV
      url: "/cv.pdf"
---
````
