### ISSUE TITLE
Categories in post title banners don't wrap on small screens

### ISSUE THREAD

**Issue by mccarthy-m-g** [quarto-dev/quarto-cli#3431]
### Bug description

Categories in post title banners don't currently wrap on small screens. Instead they always display as a single row even if they exceed the screen width. Currently (v1.2.269) the CSS for categories is:

```css
.quarto-title .quarto-categories {
  display: flex;
  column-gap: .4em;
  padding-bottom: .5em;
  margin-top: .75em;
}
```

Adding the following fixes this:

```css
.quarto-title .quarto-categories {
  display: flex;
  column-gap: .4em;
  padding-bottom: .5em;
  margin-top: .75em;
  flex-wrap: wrap;
  row-gap: .5em;
}
```

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
