### ISSUE TITLE
FR: Uniform Cross-Reference Styling

### ISSUE THREAD

**Issue by SHogenboom** [quarto-dev/quarto-cli#3440]
### Bug description

I've noticed that the styling of cross-references (e.g., to chapters) differs for HTML and PDF output. 
I'm using R Studio with R version 4.2.2. Running Quarto 1.2.258 on a Windows computer.

**Minimal Reproducible Example:**
```
---
title: "HTML / PDF Cross-Rerefence Test"

# CROSS-REFERENCING
number-sections: true

# STYLING
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc-title: "Inhoud"
    toc-depth: 2
    link-citations: true
---

# This would be Chapter 1 {#sec-chap-1}

# This would be Chapter 2

With a link to @sec-chap-1
```

**Output: HTML**
![image](https://user-images.githubusercontent.com/28568743/203568477-ad8a00e0-c378-42a0-82a5-1a368f47752b.png)

**Output: PDF**
![image](https://user-images.githubusercontent.com/28568743/203568154-7d413491-2697-4c27-abd4-60d56cad269d.png)

**Expected Behavior:**
I would expect the PDF link to include the 'Section' - which is what is what is currently happening in the HTML styling. Underlining the link would also be nice for clearer visibility, but not necessary (could perhaps be achieved through custom css). At the moment with only the numbers as links it is very hard for readers to recognize that there is in fact a link!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
