### ISSUE TITLE
Error when specifying `hugo` options

### ISSUE THREAD

**Issue by pat-alt** [quarto-dev/quarto-cli#345]
Since updating to the latest version of quarto I get an error when trying specify `hugo` options.

```zsh
/ quarto render index.ipynb
ERROR: Validation of YAML front matter failed.
ERROR: In file index.ipynb
(line 16, columns 3--7) property name hugo is invalid
15: format:
16:   hugo:
      ~~~~~
17:     html-math-method: 
ℹ The error happened in location format:hugo.

ERROR: Render failed due to invalid YAML.
```

Here's my full YAML header:

```YAML
---
title: Effortless Bayesian Deep Learning in Julia
author: Patrick Altmeyer
date: '2022-02-16'
slug: effortless-bayesian-deep-learning-in-julia
categories: [Trustworthy AI]
tags: [bayes, deeplearning, julialang]
subtitle: ''
summary: 'An introduction to effortless Bayesian deep learning through Laplace approximation coded from scratch in Julia. See also the pure-play companion package [BayesLaplace.jl](https://www.paltmeyer.com/BayesLaplace.jl/dev/)'
authors: []
lastmod: 'r format(Sys.time(), "%b %d, %Y")'
featured: yes
projects: []
format:
  hugo:
    html-math-method: 
      method: webtex
      url: https://latex.codecogs.com/png.image?%5Cbg_black&space;
jupyter: julia
crossref:
  fig-prefix: Figure
  tbl-prefix: Table
bibliography: ../../../bib.bib
---
```

This is the version I'm on (tried the dev version as well, same error):

```zsh
/ quarto --version
0.9.21
```
Am I doing something wrong?
