### ISSUE TITLE
Can't specify TOC link color with CSS

### ISSUE THREAD

**Issue by lawalter** [quarto-dev/quarto-cli#3460]
### Bug description

Hello,

I am rendering a website on Windows 10 with the Quarto extension v1.56.0 on VS Code v1.73.1. I have tried and failed to change the active link color in the Table of Contents using CSS. I know that I am specifying the right CSS class because the style sheet below will affect the link boldness and background color, but not the link color itself. I have tried this with and without `!important`. 

```
.toc-active .nav-link.active {
    color: red !important;
    background-color: yellow;
    font-weight: bold;
}
```

The link text remains blue (example below).
![image](https://user-images.githubusercontent.com/32176622/204056745-ab60e7ad-d013-4ccc-be50-bcde06569aee.png)

Here's a reproducible yaml and index.qmd:

YAML:
```
project:
  type: website

website:
  title: "example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

index.qmd:
```
---
title: "example"
---

This is a Quarto website.

## Section 1 

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

## Section 2

Example

## Section 3

Example

## Section 4

Example

### Subsection 1

Example

## Section 5

Example
```

Any advice appreciated!

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
