### ISSUE TITLE
Author name attributes return `true` when rendering as `pdf`

### ISSUE THREAD

**Issue by arnaudgallou** [quarto-dev/quarto-cli#3483]
### Bug description

Quarto fails to render author name attributes when rendering as `pdf`.
```
---
title: test
format: pdf
author:
  - name:
      given: John
      family: Smith
      literal: John Smith
---
```
The `yaml` above returns `true` instead of `John Smith`.

Using the following works:
```
---
title: test
format: pdf
author:
  - name: John Smith
---
```

Tested in RStudio `2022.7.2.576`, Quarto `1.2.269` on MacOS `12.3.1`.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
