### ISSUE TITLE
Citeproc warning when using a Mastodon profile link

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#3493]
### Bug description

With the recent addition of the `rel: me` option to navbars, it's now possible to include a link to a Mastodon profile and have it be verified on their end:

```yaml
website:
  title: "Blah"
  navbar:
    right:
      - icon: mastodon
        aria-label: mastodon
        href: https://fediscience.org/@andrew
        rel: me
```

Mastodon profile links typically include a `@` in their URL, like `https://fediscience.org/@andrew` above. This causes a minor problem when working with citations, just like Twitter card issues in https://github.com/quarto-dev/quarto-cli/issues/1702. When a site's navbar has a URL with a `@`, it causes a pandoc warning:

```
[WARNING] Citeproc: citation andrew not found
```

It's not a breaking bug or anything, just kind of funny to see it happen with every page that gets rendered 🙃

![image](https://user-images.githubusercontent.com/73663/204395823-32472f49-5e79-4ca3-9f89-0dbfe90fdba9.png)

---

This is with Quarto 1.3.26 in RStudio 2022.07.2+576 (and also in VS Code) on macOS Monterey 12.6

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by mcanouil** [comment]
If you use explicit yaml string by adding double quotes around the url, does the issue still occur?

**Comment by andrewheiss** [comment]
The issue still happens if it's quoted:

```yaml
      - icon: mastodon
        aria-label: mastodon
        href: "https://fediscience.org/@andrew"
        rel: me
```

```text
output file: index.knit.md

[WARNING] Citeproc: citation andrew not found
```
