### ISSUE TITLE
setup.yml: tinytex not installing on macOS-latest

### ISSUE THREAD

**Issue by eeholmes** [quarto-dev/quarto-cli#3670]
Works fine on `ubuntu-latest` just not on `macOS-latest`

Here is the GitHub Action
```
on:
  push:
    branches: main

name: Setup

jobs:
  build-deploy:
    runs-on: macOS-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
```

Here is the error. `Error: TypeErrorL:`
<img width="985" alt="image" src="https://user-images.githubusercontent.com/2545978/207450678-5d36c236-4e64-44de-b3f3-54bcd19fbdc8.png">
