### ISSUE TITLE
Spurious Reference page when using biblatex in PDF output

### ISSUE THREAD

**Issue by fulem** [quarto-dev/quarto-cli#3825]
### Bug description

We get an spurious reference page when using biblatex citation method in PDF output, because biblatex adds its own header.

### Reproduce

index.qmd
```
# Start

See @knuth84 for discussion of literate programming.
```
_quarto.yml
```
project:
  type: book

book:
  title: "test"
  author: "Jane Doe"
  chapters:
    - index.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: report
    cite-method: biblatex
```
Where `references.bib` and `references.qmd` are in the standard quarto project example.

In the PDF output the result is something like:
<img width="186" alt="image" src="https://user-images.githubusercontent.com/98791224/210277202-d766ebcd-6d0b-4cb5-bdef-16a2495640f6.png">

### Possible solution

Generated latex code is:
```
\hypertarget{references}{%
\chapter*{References}\label{references}}
\addcontentsline{toc}{chapter}{References}

\markboth{References}{References}

\printbibliography   % this add new header named "Bibliography"
```

To instruct biblatex to not add its own heading, we can replace the last line with: 

`\printbibliography[heading=none]`

### More info

- Quarto 1.2.280
- R studio 2022.12.0 Build 353
- Windows 11 Pro 22H2

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
