### ISSUE TITLE
quarto-title-author-name and quarto-title-affiliation not obeying scss text-align on revealjs presentation title slide

### ISSUE THREAD

**Issue by drcaprosser** [quarto-dev/quarto-cli#3843]
Using a previous version of quarto (1.1.189) I had added some custom rules to a scss file that tweaked the formatting of the title/subtitle/author/institute fields on the title slide (size, bolding, italics, alignment etc) - in particular I had aligned all of the text to the left using the following rule:

```
#title-slide {
  text-align: left;
}
```

Which worked fine. 

I've just updated my RStudio and quarto has been updated to1.2.269, and the author and institution fields no longer obey the previous formatting rules. After a bit of tinkering I figured out the names of the author and title fields had changed to quarto-title-author-name and quarto-title-affiliation, and changing those in my scss I can get them to change size, bolding etc, but I cannot get them to align left, whether I set the rule as above, or specifically to quarto-title-author-name and quarto-title-affiliation.

Here is a very simple example that recreates the problem at my end, with a scss file called 'test.scss':

qmd file:
```
---
title: "This should be red"
subtitle: "This should be aqua"
author: "This should be green"
institute: "This should be orange"
format: 
  revealjs:
    theme: test.scss
---

```

test.scss contains:

```
/*-- scss:rules --*/

#title-slide {
  text-align: left;
}

#title-slide .title {
  color: #FF0000;
}

#title-slide .subtitle {
  color: #00FFFF;
}

#title-slide .quarto-title-author-name {
  color: #00FF00;
}

#title-slide .quarto-title-affiliation {
  color: #FFA500;
}

```

Or alternatively,

```
/*-- scss:rules --*/

#title-slide .title {
  color: #FF0000;
    text-align: left;
}

#title-slide .subtitle {
  color: #00FFFF;
   text-align: left;
}

#title-slide .quarto-title-author-name {
  color: #00FF00;
  text-align: left;
}

#title-slide .quarto-title-affiliation {
  color: #FFA500;
  text-align: left;
}

```

I know I'm tapping into the correct fields because the colour rules are obeyed, but I am stumped as to why the author and affiliation fields are staying centre aligned - not sure if this is a bug or I am just missing something somewhere and just need a different rule (I would guess the latter...).  

Help much appreciated!

**Comment by mcanouil** [comment]
It's because author scheme changed in 1.2.

See an example below:

```scss
/*-- scss:rules --*/

#title-slide {
  text-align: left;

  .quarto-title-authors {
    justify-content: left;
  
    .quarto-title-author { // optional, test it for yourself
      padding-left: 0em;
      padding-right: 0em;
      width: 100%;
    }
  }
}
```

```markdown
---
title: "Habits"
author:
  - name: "John Doe"
    affiliation: Unknown
format:
  revealjs:
    theme: demo.scss
---
```
