### ISSUE TITLE
Reveal js error for `show-notes: separate-page`

### ISSUE THREAD

**Issue by code86** [quarto-dev/quarto-cli#3996]
I get an error when I run the example on this webpage ("Print Options" section):

[https://quarto.org/docs/presentations/revealjs/presenting.html#print-options](https://quarto.org/docs/presentations/revealjs/presenting.html#print-options)

```
---
title: "Presentation"
format:
  revealjs:
    show-notes: separate-page
    slide-number: true
---
```

When I run "Quarto: Render" in VS Code, the error message is: 
`ERROR: Validation of YAML front matter failed.`
```Field "show-notes" has value separate-page, which must instead be `true` or `false` ```

FYI, the example compiles and runs perfectly when I replace `separate-page` with `true` or `false`. 

The documentation in the link above (Print Options section) states that `shownotes` option can take the value of either `true, false, or separate-page`.

In terms of version, I am running using the latest update of Google Chrome and Mac OS, and I just downloaded and installed Quarto two weeks ago.
