### ISSUE TITLE
book output: repo-actions only available if chapter has headers

### ISSUE THREAD

**Issue by ratnanil** [quarto-dev/quarto-cli#3998]
### Bug description

Not all the chapters in my book have headers. I've noticed that in the chapters without headers (and therefore no TOC on the right), the `repo-actions` I specified are missing. 

#### `_quarto.yml`

```
project:
  type: book
format: 
  html: 
    theme: darkly   # just to make the screenshots more clear
book:
  repo-url: https://github.com/test/test
  repo-actions: [edit]
  chapters: 
    - index.qmd
    - chapter1.qmd
```

#### `index.qmd`

```
# A header
```

#### `chapter1.qmd`

```
no header
```

#### `index.html`

![image](https://user-images.githubusercontent.com/12532091/213029321-89cad6b0-e08e-439c-bb55-dc02a6a2cc83.png)

(notice how `Edit this page` is available)

#### `chapter1.html`

![image](https://user-images.githubusercontent.com/12532091/213029357-3b03edd4-673e-48f7-bb07-7a0decd97bdc.png)

(notice how `Edit this page` is *not* available)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
