### ISSUE TITLE
Grid listing garbled with `lang: cs` and a valid `date` in listed document

### ISSUE THREAD

**Issue by petrbouchal** [quarto-dev/quarto-cli#4017]
### Bug description

# What happens

In a Quarto Website project, when, in `index.qmd` 
- the `listing` `type` is set to `grid` and 
- `lang` is set to `cs` (which is a supported language) either in `quarto.yml` or in the YAML header of `index.qmd` 
- the listed ("child") document contains a valid date in the `date` field

...the listing comes out like this:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/1666657/213404565-934486d3-02d6-4e57-a3c2-f8127f634f10.png">

The bug disappears i.e. the listing comes out correct when:
- the `lang` field is removed or set to other languages (including non-ascii like `pl` and `kr`)
- the `date` field contains non-date text - the listing looks correct and correctly displays "Invalid date"
- the `type` of listing is set to `default`
- (!) `lang: cs` is replaced with `language: _language-cs.yml`, where `_language-cs.yml` is a local copy of [the quarto language file for Czech](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language-cs.yml)

# How to reproduce:

1. In RStudio, create a new quarto website project.

2. In index.qmd, set the following YAML header:

```yaml
title: "quarto-listing-bug"
lang: cs
listing:
  type: grid
```

3. Create `test.qmd` with the following yaml header:

```yaml
title: "Untitled"
date: 2022-01-01
```

and remove any contents (for minimal reproducibility, the content makes no difference to the bug).

5. Leave other files untouched, including `_quarto.yml`:

```yaml
project:
  type: website

website:
  title: "quarto-listing-bug"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

6. Click `Render` on `index.qmd`. (Running `quarto render` or `quarto render index.qmd` has the same result.) No unusual Quarto output appears on the console.

# Versions

- Quarto: 1.2.313 - I wasn't able to test on the daily release, since the daily returned an error referring to missing Lua filters in a quarto shared directory.
- RStudio: Version 2023.03.0-daily+41 (2023.03.0-daily+41)
- OS: MacOS 13.2 (a) Beta (22D7750270d)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
