### ISSUE TITLE
Rendering .qmd to Commonmark md breakes inline LaTeX 

### ISSUE THREAD

**Issue by kellertuer** [quarto-dev/quarto-cli#4035]
### Bug description

I have a problem rendering from `.qml` to Markdown (to use with Documenter.jl) and to me this seems like a bug. here is the .qml file (hopefully with the full config)=

(_edit_: I of course meant a `.qmd` file here, sorry)

```
---
title: "CommonMark Bug?"
execute:
  freeze: auto
  eval: true
  echo: true
  output: true

format:
  commonmark:
    variant: -raw_html
    wrap: none

jupyter: julia-1.8
---

If I want to type something like $p^*$  so a p with a start upfront and run this
on Jupyter with Julia (not sure if relevant) to transfert to Commonmark (to use with Documenter.jl)
```

when running `quarto render my file.qmd` on this one gets

```
CommonMark Bug?
================

If I want to type something like *p*^(\*) so a p with a start upfront and run this on Jupyter with Julia (not sure if relevant) to transfert to Commonmark (to use with Documenter.jl)
```

which is not the  `$p^*$` (or rendered here $p^*$) I initiallytypeset there; I would even prefer if inline LaTeX from cmd to md would just stay as it is?

This is running on Mac OS Ventura (13.0.1) using quarto installed via Homebrew with current version of Quarto being 

```
❯ quarto --version
1.2.313
```

as an editor I use VS Code, IJulia from Julia 1.8.5, Jupyter installed via Conda.jl

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
