### ISSUE TITLE
Footnote in Revealjs on top of text

### ISSUE THREAD

**Issue by reuning** [quarto-dev/quarto-cli#4044]
### Bug description

Using Revealjs, the footnote is appearing on top of the text no matter how little text I have on the slide. See the below example. 

```
---
title: "Footnote"
format: revealjs
---

# Test

This needs a footnote^[Footnote]
```

Renders as: 
<img width="401" alt="Screenshot 2023-01-21 at 1 05 41 PM" src="https://user-images.githubusercontent.com/6343832/213880808-7dacec03-fa74-4858-9d75-0e1e21954a6f.png">

The settings: 
```
kevinreuning@Kevins-MacBook-Pro-4 R Bootcamp % quarto preview "/Users/kevinreuning/Dropbox/Teaching_Kevin/Spring_2023/R Bootcamp/
tmp.qmd" --no-browser --no-watch-inputs
pandoc 
  to: revealjs
  output-file: tmp.html
  standalone: true
  title-prefix: Presentations
  wrap: none
  default-image-extension: png
  html-math-method:
    method: mathjax
    url: >-
      https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML-full
  slide-level: 2
  
metadata
  link-citations: true
  width: 1050
  height: 700
  margin: 0.1
  center: false
  navigationMode: linear
  controlsLayout: edges
  controlsTutorial: false
  hash: true
  history: true
  hashOneBasedIndex: false
  fragmentInURL: false
  transition: none
  backgroundTransition: none
  pdfSeparateFragments: false
  lang: en
  auto-stretch: true
  author: Kevin Reuning
  theme:
    - default
  title: Footnote
  
Output created: _site/tmp.html
```

Quarto version: 1.2.280
System Version: macOS 13.1 (22C65)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
