### ISSUE TITLE
`page-footer` does not render with navbar: false

### ISSUE THREAD

**Issue by petrbouchal** [quarto-dev/quarto-cli#4053]
### Bug description

In a website, when the navbar is turned off via `navbar: false`, the footer set via `page-footer` is not rendered.

Reproducible example

1. create website project

```bash
quarto create-project quarto-footer-bug --type website
```

2. edit `_quarto.yml` to turn off navbar and include footer text

```yaml
project:
  type: website

website:
  title: "quarto-footer-bug"
  page-footer: "footer" # added
  navbar: false # edited

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```
 3. render site

```bash
quarto render quarto-footer-bug
```

Quarto version: 1.3.124
MacOS 13.2 (22D49)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
