### ISSUE TITLE
Book chapter numbering leaks in navbar

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#407]
Quarto 0.9.30 on Linux.

When I add a navbar to a book and include a link to a chapter as an item, the chapter number appears in the item text, even when I specify a "text" field for the navbar item in _quarto.yml.

Reproduce:

1. Create a new book project with "quarto create-project mybook --type book"
2. Edit _quarto.yml as follows (only change from default is navbar entry):

```
project:
  type: book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "3/11/2022"
  navbar:
    left:
      - text: "Intro"
        file: intro.qmd
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

3. Preview the project.  In the navbar, the item text is "1 Intro"

IMO the value of the "text" field for the navbar item should be definitive when it comes to what is displayed.
