### ISSUE TITLE
improve pre-post filter decomposition

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#4113]
cc @dragonstyle

We want to do filters like this:

```
      filters:
        pre:
          - pre.lua
        render:
          - render.lua
        post:
          - post.lua
```

The inspiration is the sweet positioning of asciidoc.lua and that's how everything else should be in our filter chain.

**Comment by cderv** [comment]
This would definitely help fill the gap with some R Markdown feature for custom formats. With R  Markdown, one can define some pre / post hooks in `output_format()` and obviously do stuff during rendering: 
* Before knitting 
* (During knitting by using knitr hooks)
* After knitting
* Before render  with Pandoc 
* (During pandoc render by passing filters to Pandoc)
* After render after render with Pandoc. 

Everything is in R for those hooks. Obviously for Quarto it will be Lua. Some pre and post filter will definitely help ! 

So 👍 to this !

**Comment by cscheid** [comment]
This unblocks @allenmanning's switch to a simpler, more robust confluence render. So it's going to 1.3.

**Comment by cscheid** [comment]
See also #2294. Let's consider how to allow after-citeproc filters as well (and where exactly to take citeproc processing since we can call it with `pandoc.utils.citeproc`)

**Comment by andrewheiss** [comment]
Here's a quick example of where a post-rendering Lua filter would be helpful: https://github.com/andrewheiss/quarto-wordcount#how-this-all-works. The filter works now because of the `citeproc.lua` wrapper mentioned here https://github.com/quarto-dev/quarto-cli/issues/2294#issuecomment-1238954661, but someday it'll be neat to just do something like this:

```yaml
format:
  html:
    filter:
      post:
        - '/path/to/wordcount.lua'
```
