### ISSUE TITLE
Custom config in _quarto.yml fails validation in v1.3.129

### ISSUE THREAD

**Issue by machow** [quarto-dev/quarto-cli#4114]
### Bug description

[quartodoc](https://machow.github.io/quartodoc/get-started/overview.html) uses a top-level config field in _quarto.yml, e.g.:

```yaml
project:
  type: website
  resources:
    - objects.json

quartodoc:
  style: single-page
  dir: reference
  package: quartodoc
  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        - get_object
        - preview
```

However, this fails validation, so `quarto render` raises:

```bash
ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 6, columns 1--10) property quartodoc does not match case convention _quarto
6: quartodoc:
  ~~~~~~~~~~
7:   style: single-page
```

I'm not sure if this is a bug, or an indication that quartodoc would need to implement a custom project type 😅. (tested on Mac OSX).

Note that quartodoc uses this information prior to rendering, so the workflow right now looks like...

```bash
python -m quartodoc build
quarto preview
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
