### ISSUE TITLE
Feature request: support enterprise GitHub links for website navigation

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#421]
Hi 👋 

I'd like to use [GitHub links](https://quarto.org/docs/websites/website-navigation.html#github-links) to help my team edit pages easier.

I added this to my `_quarto.yml`:

```
website:
  title: "hi-charles-and-jj"
  repo-url: https://github.ibm.com/team/hi-team
  repo-actions: [edit, issue]
```

But when I run `quarto preview`, I see:

```
WARNING: Repository links require a github.com repo-url
```

😢
