### ISSUE TITLE
Rendered HTML page interactivity not working on mobile browsers

### ISSUE THREAD

**Issue by thegilpatrick** [quarto-dev/quarto-cli#4242]
### Bug description

I rendered an HTML page and uploaded it on GitHub pages. Here is the [link to the webpage](https://thegilpatrick.com/blog/tidyTuesday/2023-01-31/Pet_Cats_UK.html).

The page loads fine, but none of the interactivity works on mobile (Safari or Chrome) (except for the show code button). I have some hyperlinks in markdown and you cannot click on them. I have some OJS inputs that don't work on mobile, but everything is working fine in multiple browsers (Chrome, Edge, Firefox) on desktop. I assumed at first that it was a Safari problem, but it seems to be something specific to mobile. But some of these same rendered HTML pages used to work fine on mobile before I updated Quarto to use the new `embed-resources` YAML option.

Below is my YAML for the HTML page I linked. I rendered this in VSCode with the extension. I have a Windows 10 Pro Operating System.

```
---
title: UK Pet Cats 
subtitle: Tidy Tuesday Week 5
date: 1/31/2023
format:
  html:
    code-fold: true
    toc: true
    toc-location: left
    embed-resources: true
    code-tools: true
    include-before-body: header.html
---
```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
