### ISSUE TITLE
Numbered lists greater than 9 show only the one's digits with {.scrollable} slide

### ISSUE THREAD

**Issue by javajon** [quarto-dev/quarto-cli#4283]
Add {.scrollable} to slide title and numbered lists greater than 9 show only the one's digits. In a qmd file add to a slide a list of items 1-15.  They can be number with just 1., 1., 1.  or 1. 2. 3. But once it gets to 10, the rendered output with reveal.js only show the last single digit.

```
## Slide title {.scrollable}
1.
1.
...
1.
1.
```

(workaround is to use "- 10.")

**Comment by cscheid** [comment]
That's a fun one. The high-order digits are still there, but `.scrollable` makes it so that elements left of the left border of the div are hidden.

I was ready to say "I don't think we would be able to fix this in general", but CSS is kind of incredible, so there actually is a fix (note that it won't work for 100 or more :D). It'll be available in the 1.3 prereleases soon.

**Comment by AndreiBiziuk** [comment]
I think fix from #4285 isn't working in 1.4. There is no `.scrollable` class on page, so style not applied to list.

**Comment by cscheid** [comment]
> There is no `.scrollable` class on page

I'm not sure I understand your question. The bugfix is for elements with `.scrollable` in them, so if there's no `scrollable` class, then this doesn't apply.

**Comment by AndreiBiziuk** [comment]
I'm using Quarto 1.4.358 and when I create reveal.js presentation with `scrollable: true` in front matter, if I have numbered list with more then 9 items, this bug is appearing (only one digit displaying). I've inspected the page, and there is no element with `.scrollable` class, so fix from #4285 

``` css
.reveal .scrollable ol li:first-child:nth-last-child(n + 10),
.reveal .scrollable ol li:first-child:nth-last-child(n + 10) ~ li {
  margin-left: 1em;
}
```

isn't working.

If I add

``` css
.reveal ol li:first-child:nth-last-child(n + 10),
.reveal ol li:first-child:nth-last-child(n + 10) ~ li {
  margin-left: 1em;
}
```

to css, margin applied and numbers greater than 9 displayed correctly.
