### ISSUE TITLE
auto generate ordered side navigation with subfolders

### ISSUE THREAD

**Issue by KaiWaldrant** [quarto-dev/quarto-cli#4290]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4265

<div type='discussions-op-text'>

<sup>Originally posted by **KaiWaldrant** February  7, 2023</sup>
We are creating a website with quarto and wanted to make use of the auto generating side bar navigation. Because we want to define the order of the layout we have added the `order` in the metadata of the `.qmd` files.

For some reason the the directory with subfolders (`contribute`) is ordered last in the navigation bar although we specified it to be higher then the `code of conduct`.

`_quarto.yaml`
```yaml
sidebar:
    - id: documentation
      collapse-level: 3
      title: Documentation
      contents: documentation

    - id: neurips2021_docs
      title: NeurIPS2021
      contents: competitions/neurips_2021_docs
```

`documentation/code_of_conduct/index.qmd`
```yaml
---
title: Code of conduct
engine: knitr
order: 60
---
```

`documentation/contribute/index.qmd`
```yaml
---
title: Contribute
order: 4
---
```

Can anybody see what we are doing wrong or is this a bug ?

You can view a preview of the website here: [website](https://restructure-docs--openproblems-experimental.netlify.app/documentation/)

You can find the code here: [github](https://github.com/openproblems-bio/website-experimental/tree/restructure-docs)

cc @rcannood </div>
