### ISSUE TITLE
suggestion: emit directory links rather than "./index.html" links

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#43]
Given a site defined by:

```yaml
project:
  type: site

site:
  title: "self-linking"
  navbar:
    left:
      - href: index.md
        text: Home
```

and a single Markdown file:

```markdown
---
title: self-linking
---

this is a link to [me](./).
```

The rendered content has a directory reference as its link:

```html
<p>this is a link to <a href="./">me</a>.</p>
```

However, the navbar links are generated as file references to `index.html`. Here's one example:

```html
  <a class="navbar-brand" href="./index.html">
    self-linking
  </a>
```

In comparison, a very similar mkdocs site (with a `docs/index.md` file):

```yaml
site_name: self-linking

nav:
  - "home": index.md
```

produces navbar links like:

```html
<a class="navbar-brand" href=".">self-linking</a>
```

This avoids leaking `index.html` into URLs.
