### ISSUE TITLE
sidebar section padding with fixed-font name

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#432]
Using Quarto 0.9.80

```bash
quarto create-project --type website quarto-fixed-section
```

Add a `bash.qmd` file into that project; its contents don't matter.

Use the following configuration:

```yaml
project:
  type: website

website:
  title: "quarto-fixed-section"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: bash.qmd
        text: "`bash`"
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
```

When rendered, the sidebar gives the impression that the `bash` entry is indented and possibly a sub-entry of `Home`. This is caused by the light grey box around the fixed-font text.

<img width="235" alt="image" src="https://user-images.githubusercontent.com/362187/158861845-fe6307f9-5bc7-40f8-93a7-a10b113a1d74.png">

I'm not sure how this should be adjusted. The spacing around fixed-font text generally feels appropriate, but it can sometimes make the text feel out-of-place with awkward spacing, as you can also get when it is part of header elements:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/362187/158862365-f18ebd97-d94f-4626-bc5e-9d5b16c42c94.png">
