### ISSUE TITLE
Quarto Website: Using local fonts (Google Fonts)

### ISSUE THREAD

**Issue by Klesel** [quarto-dev/quarto-cli#4387]
### Bug description

Setting: Quarto Website using a theme.

Objective: I would like to avoid downloading google fonts via the google api

Idea: Storing the fonts locally and include them via a custom scss file
`_quarto.yml`:
```yml
format:
  html:
    theme: 
      light: [flatly, light.scss]
``` 

`light.scss`:
```css
/* lato-regular - latin-ext_latin */
@font-face {
  font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src: url('fonts/lato-v23-latin-ext_latin-regular.woff2') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
       url('fonts/lato-v23-latin-ext_latin-regular.woff') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */

(...)

$font-family-sans-serif: 'Lato';
}
```

In my environment, the fonts are still downloaded from the google api in the fonts folder: `/site_libs/bootstrap/fonts`

This screenshot also shows that the api is still in use:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/41738984/219420144-118f9a6a-a6b3-43c0-98f9-7f3504c61701.png">

From a user perspetive, it would be most helpful to have a variable that ensures that no font is used via an api. Any other approach to ensure that only local fonts are used would likewise be appreciated.

As a side-note: This is particularily relevant in Germany, because there is a legal issue using google fonts that are included via the API. Therefore, this issue should be relevant for a larger group of users. 

I raised this issue [here](https://stackoverflow.com/questions/75464776/how-to-override-the-default-font-using-locally-stored-fonts-in-themes/75472368#75472368). 

My environment:
- WSL2 Ubuntu 20.04
- VS Code 1.75.1
- Quarto Version: 1.2.335

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
