### ISSUE TITLE
Font options don't work with pdflatex

### ISSUE THREAD

**Issue by rmcd1024** [quarto-dev/quarto-cli#4390]
### Bug description

This document renders correctly:
```
---
title: Here is a first title
author: Iam Author
format: 
  pdf:
    mainfont: Latin Modern Roman
    sansfont: Latin Modern Roman
    #pdf-engine: pdflatex
---

# First section

Here is some body text
```
If I remove the hash in front of `pdf-engine`, so that rendering uses `pdflatex` rather than `xelatex`, the font options are ignored. The two rendered examples are attached.

Not sure if this is a bug, but if not it should be documented. (I looked, but in general had trouble figuring out the font options from the online documentation.) 

This is using quarto version 1.3.191 on Ubuntu 22.04, and pdflatex is `pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) kpathsea version 6.3.4/dev`

[pdf-fonts-issue.zip](https://github.com/quarto-dev/quarto-cli/files/10759258/pdf-fonts-issue.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
