### ISSUE TITLE
Multi-format links don't distinguish formats with same extension

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4398]
### Bug description

When using the multi-format feature, formats that resolve to the same file extension aren't distinguished. For example, for a file called `test.qmd` with both `html` and `revealjs` formats specified, the RevealJS link points to `test.html` and gets the HTML page, not the revealJS presentation. 

The same problem arises with `pdf` and `beamer` formats.

An example:
````
---
title: Multi format example
format:
  html: default
  revealjs: default
---

## Getting up

- Turn off alarm
- Get out of bed

## Going to sleep

- Get in bed
- Count sheep

````

Dev Quarto, Mac OS, RStudio Version 2023.03.0-daily+302 (2023.03.0-daily+302)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
