### ISSUE TITLE
name of chapters in a book

### ISSUE THREAD

**Issue by sbalci** [quarto-dev/quarto-cli#445]
Hi,

Is it possible to change the name of chapters in the menu from `_quarto.yml`?

I am trying to make a bilingual (Turkish and English) book using `asis`. See code here: https://github.com/patolojiatlasi/patolojiatlasi.github.io/blob/main/kronikinflamasyon.Rmd

When I render the book I think the chapter name is retrieved from the first heading, and later the chapter content is rendered using chunk conditions. So when I select the language as TR or EN the content of the chapter is correct, but the name of the chapter on the menu is the first heading.

![Ekran görüntüsü 2022-03-19 123325](https://user-images.githubusercontent.com/7208830/159115999-649af845-06fd-4898-986e-a753513d4523.jpg)

**Comment by jjallaire** [comment]
You can override the chapter navigation `text` in `_quarto.yml` like this:

```yaml
  chapters:
    - index.qmd
    - text: "Intro"
      href: intro.qmd
    - summary.qmd
    - references.qmd
```

**Comment by sbalci** [comment]
Hi,
I get the error "Book chapter not found".
I am on v.0.9.116


<img width="1217" alt="Screen Shot 2022-03-19 at 23 01 37" src="https://user-images.githubusercontent.com/7208830/159136660-b929c675-171d-40c0-a9d0-1543522d52a7.png">

**Comment by dragonstyle** [comment]
Try:

```
chapters:
  - index.qmd
  - text: "Girig"
    href: girig.qmd
```

(note there is no `-` before the href, grouping the text / href into one entry)
