### ISSUE TITLE
How to specify more detailed files to render in project settings

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#446]
I wanted only the `index.qmd` file under the project to be the target of rendering, so I set it up as follows.

```yml
project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
```

However, it appears that `index.qmd` files in subdirectories (e.g. `subdir/index.qmd`) are also subject to rendering.
I had thought that to target all `index.qmd` I would have to write it like `"**/index.qmd"`.
Perhaps there is no way to exclude subdirectory `index.qmd`?
