### ISSUE TITLE
Numerical values for sidebar section names mishandled

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#450]
When I try to create a sidebar with multiple sections, and each section item in _quarto.yml is given a numerical value for a name, the last number specified is used as the text label for all sections in the rendered html.

To replicate:

1. create a new website project via "quarto create-project mysite --type website"

2. edit _quarto.yml as follows (only change is addition of sidebar section):

```
project:
  type: website

website:
  title: "mysite"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    - id: test
      contents:
        - section: "1"
          contents:
            - index.qmd
        - section: "2"
          contents:
            - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
```
3. render and view the site

Both sections in the sidebar show the text "2".
