### ISSUE TITLE
Confluence HTML output has a wrong path for theme.scss on Windows

### ISSUE THREAD

**Issue by m-legrand** [quarto-dev/quarto-cli#4510]
### Bug description

```
$ quarto --version
1.3.217
```

I am on windows, and when trying to render a document with the following frontmatter

```yaml
title: "Example"
format:
    confluence-html
```

I'm getting the following error:

```txt
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'C:\Users\JDoe\AppData\Local\Programs\Quarto\share\formats\html\bootstrap\themes\C:\Users\JDoe\AppData\Local\Programs\Quarto\share\extensions\quarto\confluence\theme.scss.scss'
```

If I'm decomposing the path in Python code, this looks like

```python
root = "/c/Users/JDoe/AppData/Local/Programs/Quarto/share"
path1 = f"{root}/extensions/quarto/confluence/theme.scss"
path2 = f"{root}/formats/html/bootstrap/themes/{path1}.scss"
```

This hints at a bug whereby `path1` is used somewhere instead of [`path1.stem`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.stem).
But this is as far as I could go in trying to pinpoint the issue.

---

Github complains about `*.qmd` attachements so I'm giving the source code of a minimal problematic example below:

```markdown
---
title: "Example"
format:
    confluence-html
---

Hello! This is an example.
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by allenmanning** [comment]
Thanks for reporting.  I'm looking to reproduce it and will post my findings here.

**Comment by allenmanning** [comment]
On windows I ran the following test.

Quarto Document
````
---
title: "Bug - Confluence HTML output has a wrong path for theme.scss on Windows"
format:
  confluence-html
---

Hello! This is an example.
````

````
quarto render bug-4510.qmd

PS C:\dev\quarto-confluence-test\bugs> quarto render .\bug-4510.qmd
pandoc
  to: html
  output-file: bug-4510.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  theme:
    - default
    - ../../quarto-cli/src/resources/extensions/quarto/confluence/theme.scss
  title: Bug - Confluence HTML output has a wrong path for theme.scss on Windows

Output created: bug-4510.html
````

I wasn't able to reproduce as theme was mapped to `../../quarto-cli/src/resources/extensions/quarto/confluence/theme.scss`

Can you please paste your render output so that I may compare with what I'm seeing.

Thank you.
