### ISSUE TITLE
page navigation show part name

### ISSUE THREAD

**Issue by sbalci** [quarto-dev/quarto-cli#453]
Hi,
In Quarto Books when the next chapter is under a "part" I think it would be better to show that the user is at the end of a section and goes to a new section.

In the below example when the user is in "parazit.qmd" the next link in page navigation is to "benign.qmd". But I think the link should also contain the part name. Because it is a different topic and not relevant to current page.

```yaml
   - part: "İnfeksiyöz Hastalıkların Patolojisi"
      chapters:
        - text: "Parazitler"
          href: parazit.qmd
    - part: "Temel Tümör Patolojisi"
       chapters:
        - benign.qmd
        - hamartom.qmd 
```

<img width="1057" alt="Screen Shot 2022-03-22 at 21 43 06" src="https://user-images.githubusercontent.com/7208830/159553274-f557bb81-467c-4977-8f3c-1554f3c2dcaf.png">
