### ISSUE TITLE
Two sidebar render bugs when item label includes number in parentheses

### ISSUE THREAD

**Issue by TclLab** [quarto-dev/quarto-cli#454]
Quarto version 0.9.128

1. create a new website project via "quarto create-project mysite --type website"
2. edit _quarto.yml as follows (only change is addition of sidebar section):

```
project:
  type: website

website:
  title: "mysite"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    - id: blog
      collapse-level: 1
      contents:
        - section: "Feb (1)"
          contents:
            - index.qmd
        - section: "Jan (1)"
          contents:
            - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css

```
3. render and view the site

Bug #1: the first entry "Feb (1)" ignores the collapse-level setting and shows the sub-item "mysite" below it.

Bug #2: the second entry "Jan (1)" is frozen and doesn't show the sub-item below it when its arrow is clicked on.

Bug 2 disappears when the numbers in parentheses are removed and the labels are simply "Feb" and "Jan"
