### ISSUE TITLE
pdf from qmd file, bug with fig.pos

### ISSUE THREAD

**Issue by timothee-bacri** [quarto-dev/quarto-cli#4568]
I use RStudio to compile the following qmd file:
````yaml
---
title: "AAA"
author: "BBB"
format: pdf
toc: false
fontsize: "12"
pdf-engine: pdflatex
number-sections: true
colorlinks: true

# Where to place figure and table captions (top, bottom, or margin)
cap-location: bottom

code-line-numbers: true

execute:
  echo: false
  warning: false

fig-env: 'figure'
fig-lp: 'fig:'
fig-align: 'center'
fig-pos: 'htb'
---

```{r AAA}
#| cache: true
#| fig.cap: BBB
#| fig.height: 2
#| fig.width: 4
library(ggplot2)
mydata <- data.frame(x=1:5, y=11:15)
ggplot(mydata) +
  geom_point(aes(x = x, y = y), size = 0.2)
```
````

The generated TeX document contains
```tex
\begin{htb}[htb]

{\centering \includegraphics{intro_files/figure-pdf/AAA-1.pdf}

}

\caption{BBB}

\end{htb}
```
and crashes.

Am I doing something wrong?

**Comment by cderv** [comment]
Crash is 
````
compilation failed- error
LaTeX Error: Environment htb undefined.
````

I don't think 
````
\begin{htb}[htb]
````
is expected. It should be `\begin{figure}[htb]` I believe. 

Somehow the `fig-pos` gets assigned to `fig-env` 🤔

**Comment by timothee-bacri** [comment]
> Somehow the `fig-pos` gets assigned to `fig-env `

It made me think that `fig-env` could be the problem, so I tried commenting it out
```yaml
# fig-env: 'figure'
fig-lp: 'fig:'
fig-align: 'center'
fig-pos: 'htb'
```
It produces the expected `\begin{figure}[htb]` and the compilation stops crashing.
I will keep doing that for now, but this is not a great solution as it prevents figure environments other than `figure`.

@cderv Thanks for moving the issue to the correct repo by the way :)
