### ISSUE TITLE
`include-after-body` doesn't insert at the right location

### ISSUE THREAD

**Issue by royfrancis** [quarto-dev/quarto-cli#4628]
### Bug description

I have a quarto website and here is a minimal example.

**_quarto.yml**

```
project:
  type: website

website:
  title: "Website"
  navbar:
    background: transparent
    left:
      - text: Home
        href: "index.html"
  page-footer:
    left: Left content
    right: Right content

format:
  html
```

**index.html**

```
---
format:
  html:
    include-after-body: "include.html"
---

# Hello

This is the index page.
```

**include.html**

```
<script type="text/javascript">
console.log("hello");
</script>
```

![Screenshot from 2023-03-05 13-05-47](https://user-images.githubusercontent.com/5083500/222959896-964d1af7-6470-4f1d-820c-9c8f48f63647.jpg)

As seen in the screenshot, the **include.html** content (highlighted red) is placed inside the `quarto-content` div rather than the `body` div. I think it should be below the footer div and at the bottom along with the other scripts highlighted in green.

I have tried moving ` include-after-body: "include.html"` from **index.html** to **_quarto.yml**, but that doesn't change this.

I am also unsure what the difference between ` include-after-body` and `include-after` is. `include-after` seems to place it in the right place but literally adds the text rather the content in the path.

```
🢒  quarto --version
1.2.1

🢒  lsb_release -a
No LSB modules are available.
Distributor ID:	Zorin
Description:	Zorin OS 16.2
Release:	16
Codename:	focal
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
