### ISSUE TITLE
[FR] Indexing on authors to centralize author declaration

### ISSUE THREAD

**Issue by ma-riviere** [quarto-dev/quarto-cli#4669]
Hi,

A useful feature for people with many articles/posts sharing multiple authors would be to declare a central list of authors and be able to reference them from individual pages, in a similar fashion to `affiliations`:

`_authors.yml`
```
authors:
  - id: author1
    name: ...
    affiliations:
       - ref: lab1
  - id: author2
    name: ...
    affiliations:
      - ref: lab1
 
affiliations:
  - id: lab1
    name: ...
```

`my_pub.qmd`
```
title: ...

metadata-files: [_authors.yml]

author:
  - ref: author1
```

Thanks !

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4630

<div type='discussions-op-text'>

<sup>Originally posted by **ma-riviere** March  5, 2023</sup>
Hi,

Is there a way to have a centralized list of authors as a standalone file that can then be imported in multiple .qmd files, but only have a selection of those authors listed in each .qmd ?

**Example:**

`_authors.yml`
```
authors:
  - id: author1
    name: ...
    affiliations:
       - ref: lab1
  - id: author2
    name: ...
    affiliations:
      - ref: lab1
 
affliliations:
  - id: lab1
    name: ...
```

`my_pub.qmd`
```
title: ...

metadata-files: [_authors.yml]

# This part gets completely ignored
author:
  - ref: author1
```

If I do the above, it will list **all** the authors referenced in `_authors.yml` in each .qmd file importing `_authors_yml`. Is there a way to specify which authors of that central author list I want to see displayed in a specific file ? (the same way we can reference affiliations)

Useful info:
- Website project (outputting to HTML)
- Quarto v1.3.242 on Ubuntu 22.04

Thank you</div>
