### ISSUE TITLE
Shortcode variables from _variables.yml not rendering correctly when used in a footer

### ISSUE THREAD

**Issue by andrewheiss** [quarto-dev/quarto-cli#4680]
### Bug description

With Quarto 1.3.242, shortcode variables are rendered with deubgging information when they're included in page footers, which then also makes them render incorrectly everywhere.

Here's a MWE, based on a brand new vanilla Quarto site (RStudio > New Project > Quarto website).

**_variables.yml**

```yaml
version: 1.2

email:
  info: info@example.com
  support: support@example.com

engine:
  jupyter: "[Jupyter](https://jupyter.org)"
  knitr: "[Knitr](<https://yihui.name/knitr>)"
```

**index.qmd**

```
---
title: "Example site"
---

Version {{< var version >}} is a minor upgrade.

Here's an e-mail address: {{< var email.info >}}
```

Ordinarily, this renders just fine:

<kbd><img width="486" alt="image" src="https://user-images.githubusercontent.com/73663/223497238-d979d503-2453-4366-97b1-37f5f8e0b4fc.png"></kbd>

If I include the shortcodes in a footer, though, like this:

**_quarto.yml**:

```yaml
website:
  title: "Example site"

  page-footer:
    left: |
      {{< var version >}} {{< var email.info >}}
```

…the shortcodes that are part of a nested YAML list (i.e. `email.info` and not `version`) do not render correctly, both in the main body and in the footer

<kbd><img width="533" alt="image" src="https://user-images.githubusercontent.com/73663/223497462-53a26478-5a56-44cc-a55d-c013e1a72d56.png"></kbd>

---

This wasn't happening in earlier versions of Quarto 1.3 (like down in the 1.3.50s). This is with Quarto 1.3.242, R 4.2.2, on macOS Ventura 13.2.1

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by andrewheiss** [comment]
I went back and grabbed an older 1.3 at random (1.3.151) and everything works fine there, so something happened after at least 1.3.151:

<kbd><img width="434" alt="image" src="https://user-images.githubusercontent.com/73663/223500220-1f6ff4c4-49bc-4a35-bc12-4a23109cb955.png"></kbd>

**Comment by dragonstyle** [comment]
The second invocation is resulting in `Inlines` becoming a `List`:

**_quarto.yml**
```yaml
project:
  type: website

website:
  title: "Example site"

format:
  html:
    theme: none
    minimal: true
```

**_variables.yml**
```yaml
email:
  info: info@example.com
```

**test.qmd**
```markdown
---
title: Cool
---

{{< var email.info >}}

{{< var email.info >}}
```

Bisects to this commit:
https://github.com/quarto-dev/quarto-cli/commit/7e131faeed5b7bf4c462b65ee5ba91a69b18bece
