### ISSUE TITLE
toc-location not working in HTML?

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-cli#471]
When I set `toc-location: left`, the table of contents still shows up on the right.

See the code and output below:

## Minimal Example

```
---
title: "Test"
toc: true
format:
  html:
    toc-location: left
---

# Section 1

## Section 2
```

## Output
<img width="1017" alt="Screen Shot 2022-03-27 at 13 56 25" src="https://user-images.githubusercontent.com/25734232/160296382-900482d7-f847-4002-8ae8-f958155d7160.png">

## System details

Quarto: Version: 0.9.128
MacOS: 12.3
Rendered in RStudio: 2022.02.0 Build 443
