### ISSUE TITLE
reorder transition on headroom class

### ISSUE THREAD

**Issue by KaiWaldrant** [quarto-dev/quarto-cli#4715]
### Bug description

The `transition: transfom` is overridden with the `transition: position` while  resp. the first one is a css3 property and the latter is a css2 property. Thus no transition will be performed. I would reorder the 2 lines. You can also change this to `all` instead of `transform`

![image](https://user-images.githubusercontent.com/80908902/223867301-fba476bf-730c-41ae-8b15-c2d9f7c39253.png)

```css
.headroom-target, header.headroom {
    will-change: transform; 
    transition: transform 200ms linear;
    transition: position 200ms linear; 
}
```

suggestion
```css
.headroom-target, header.headroom {
    will-change: transform;
    transition: position 200ms linear;  
    transition: transform 200ms linear;
}
```

suggestion nr. 2
```css
.headroom-target, header.headroom {
    will-change: transform;
    transition: position 200ms linear;  
    transition: all 200ms linear;
}
```

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
