### ISSUE TITLE
monobackgroundcolor being ignored

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#4746]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4736

<div type='discussions-op-text'>

<sup>Originally posted by **harrelfe** March  9, 2023</sup>
I can't get monobackgroundcolor to take effect as described in https://quarto.org/docs/output-formats/html-themes.html#sass-variables.  Here is a reproducible example.

````
---
title: "Test"
format:
  html:
    monobackgroundcolor: red
    backgroundcolor: cornsilk
    self-contained: true
    toc: true
    toc-location: left
    toc-title: Contents	
---

Here is some code: `xvariable <- pi`.  Regular text follows.

````
</div>
