### ISSUE TITLE
YAML validation: warn about about keys with empty objects

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#4751]
This yaml should give us a warning:

```
format:
  html:
    layout:
    some-other-entry
```

YAML allows an empty object to be the value of `layout`, but that's clearly wrong. We should emit a warning when we have a linter.

And maybe we should change our schemas to disallow empty values.
