### ISSUE TITLE
 `code-tools: true` is silently ignored if title is not present

### ISSUE THREAD

**Issue by GegznaV** [quarto-dev/quarto-cli#4763]
### Bug description

Code tools `code-tools: true` do not respond (are not present in HYML) if "title: " is not present.
I use Jupyter notebook in VS Code on Windows 10 and Quarto 1.3.242. 

YAML when no code tools are present:

```yaml
---  
format:
  html:
    code-fold: show
    code-tools: true
jupyter: python3
---
```

Here is a print screen of the code:

![image](https://user-images.githubusercontent.com/12725868/224476924-b41834c7-88fb-406d-be78-d24c3e97b6cc.png)

HTML output (broken):

![image](https://user-images.githubusercontent.com/12725868/224477707-bdc1f8ea-3c82-44c5-a4fa-eca30f344195.png)

YAML that does not produce the issue:

```yaml
---  
title: Project
format:
  html:
    code-fold: show
    code-tools: true
jupyter: python3
---
```

Output (as expected):

![image](https://user-images.githubusercontent.com/12725868/224477313-f0bde326-bd8f-4546-bcfe-6e16cd9bbfb3.png)

Some examples: [code-fold-tools-issue-1.zip](https://github.com/quarto-dev/quarto-cli/files/10948173/code-fold-tools-issue-1.zip)

# Expected behavior

1) Either fix the issue (show the toolbar) in both situations
2) Or produce a **clear** warning that some setup options are ignored and provide an example of how to get the desired outcome.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
