### ISSUE TITLE
`code-tools: true` functionality is broken by `link-external-icon` + `link-external-filter`

### ISSUE THREAD

**Issue by GegznaV** [quarto-dev/quarto-cli#4765]
### Bug description

`code-tools: true` functionality is broken by the combination of `link-external-icon` + `link-external-filter` as presented in the example of YAML:

```yaml
---  
title: Project
format:
  html:
    code-tools: true
    code-fold: show
    link-external-icon: true
    link-external-filter: "^https://"
jupyter: python3
---
```

By "broken", I mean that the _Show All Code_/_Hold All Code_ buttons do not respond.

The broken output:
![image](https://user-images.githubusercontent.com/12725868/224478888-679a365a-f691-4cc4-adc0-7927b643fc28.png)

I expect `code-tools: true` to work perfectly in all situations.

I use Windows 10, VS Code and 
![image](https://user-images.githubusercontent.com/12725868/224478189-3b80b240-e1d4-4dd6-a93b-e675300e312c.png)

Example to test: [code-fold-tools-issue-4.zip](https://github.com/quarto-dev/quarto-cli/files/10948249/code-fold-tools-issue-4.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
