### ISSUE TITLE
Error when using multiline string in author field with HTML document

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-cli#477]
I would like to have multiple lines in the author field of an HTML document, but I get the following error and the document does not render.

## Minimal Example

```
---
title: "Example"
author: |
  Author 1
  Author 2
format: html
---
```

## Error

`ERROR: TypeError: Cannot read properties of undefined (reading 'childNodes')`

## System details

Quarto: Version: 0.9.128
MacOS: 12.3
Rendered in RStudio: 2022.02.0 Build 443

**Comment by dragonstyle** [comment]
You can just write:

```yaml
---
title: "Example"
author: 
  - Author 1
  - Author 2
format: html
---
```

to get the behavior that you're looking for (though that error is bad - I'll improve that!)...

**Comment by maxdrohde** [comment]
Great, thank you!

**Comment by maxdrohde** [comment]
@dragonstyle The method you showed works for authors, but is there a way to use multiline strings? I'm running into other issues when I want to have other fields, such as subtitle, have multiple lines.

**Comment by dragonstyle** [comment]
Unfortunately the author support is pretty limited right now. The authors fields currently is designed to serve as the author across all the document formats (including PDF/LaTeX which typically have a more structured approach to authors that doesn't permit arbitrary multiline output), so is limited. 

I am working on improvements in this area which will allow you to pass more structured data for authors which we will render more intelligently (or will allow you to render yourself using a template if you'd like). That is still a little ways away, but an example of what I'm talking about that is currently handled gracefully for HTML output is:

```yaml
---
title: "Summarizing Output for Reproducible Documents"
description: | 
  A summary of the best practices for summarizing output of reproducible scientific documents.
date: 5/4/2018
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation-url: https://example.com/spacelysprokets
---
```

I will plan on supporting many more types of metadata for each author (e.g. their role, for example) as well as more information about their affiliation (and details of the affiliate) as well.

In the meantime, is there a single line format that might be acceptable?

**Comment by maxdrohde** [comment]
Got it, thank you for clarifying. So currently, for example, there is not a way to put Department and University affiliation on separate lines?

```
---
title: "Title"
author:
  - name: Author
    affiliation: Department of X / University of X
format:
  html:
    self-contained: true

---

```

<img width="699" alt="Screen Shot 2022-03-28 at 13 54 13" src="https://user-images.githubusercontent.com/25734232/160467361-a4f329c1-6ba3-4be2-ae86-7ecd7e992dd5.png">
