### ISSUE TITLE
Images not displaying on sub-folder listing page in pre-release v1.3.260

### ISSUE THREAD

**Issue by cgoo4** [quarto-dev/quarto-cli#4806]
### Bug description

After updating to the latest pre-release v1.3.260, I've encountered an issue with post `feature.jpg`s no longer additionally showing up in the respective listing page. This set-up had been working okay in an earlier release.  Reprex:

_quarto.yml:
````
project:
  type: website

website:
  title: "reprex"
  navbar:
    left:
      - text: Projects
        href: project/index.qmd
      - about.qmd
````

project/index.qmd:
````
---
title: "Projects"
listing:
  id: listing
  contents: .
---
````

project/project1/index.qmd
````
---
title: "reprex"
---

![](feature.jpg)
````

RStudio: Version 2022.12.0+353 (2022.12.0+353)
macOS: 13.2.1 (22D68)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
