### ISSUE TITLE
When using a dark theme, giscus should use a dark theme as well.

### ISSUE THREAD

**Issue by kdheepak** [quarto-dev/quarto-cli#4820]
### Bug description

Right now `giscus` uses a light theme by default even when a dark theme is toggled. 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1813121/224907905-db32d0e6-0f75-4d84-ba55-bc40df8f6c03.png">

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by allenmanning** [comment]
Thanks for posting this.

I wanted to document a proposed approach here for review:


## Setting Giscus Themes
Following the `theme` from the `html` format like

```
format:
  html:
    theme:
      light: lightly
      dark: darkly
```

We can now set Giscus themes to correspond

```
website:
  comments:
    giscus:
      theme:
        light: light
        dark: cobalt
```

So when the website is `lightly` Giscus will be `light`, and when `darkly` Giscus is `cobalt`.

## Existing single `string` theme

The existing single string theme will still be supported

```
website:
  comments:
    giscus:
      theme: cobalt
```
It will expand out to be `cobalt` in both cases so it is equivalent to 

```
website:
  comments:
    giscus:
      theme:
        light: cobalt
        dark: cobalt
```

## Sensible Defaults

### No  Giscus theme

If none is specified like

```
website:
  comments:
    giscus:
```

this is equivalent to

```
website:
  comments:
    giscus:
        light: light
        dark: dark
```

### Partial Giscus theme

If partially specified like

```
website:
  comments:
    giscus:
       dark: cobalt
```

We will fill in the default as

```
website:
  comments:
    giscus:
        light: light
        dark: cobalt
```

Note:  The order of the Giscus themes has no special value.  The single source of truth for default themes remains in the HTML format.
