### ISSUE TITLE
Pre render for quarto preview

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#4841]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/4822

<div type='discussions-op-text'>

<sup>Originally posted by **itepifanio** March 14, 2023</sup>
Quarto provides [pre and pos rendering](https://quarto.org/docs/projects/scripts.html#pre-and-post-render) features but it doesn't extend when live previewing the documents.

I have a script that reads `yaml` content and outputs `.qmd` files used in a Quarto website. I was trying to add a custom watcher for the `yaml` files, this way, when a `yaml` file changes the `.qmd` files the Quarto live previewing would refresh. 

My solution was running Quarto as a subprocess and creating the custom watcher. A pre rendering that works with live previewing would make my life easier because I would be able to run the `yaml` watcher script without working with subprocessing.</div>

**Comment by mcanouil** [comment]
From: https://github.com/quarto-dev/quarto-cli/issues/14028

A reproducible example:

```bash
quarto create project website i14028 i14028 --no-open
cd i14028
touch file1.md
touch file2.md
```

Added in `_quarto.yml`:

```yaml
project:
  type: website
  pre-render:
    - cp file1.md file1.qmd
    - cp file2.md file2.qmd
  post-render:
    - rm file1.qmd
    - rm file2.qmd
  render:
    - "*.qmd"
```

Then

```bash
quarto render
```

or for the issue:

```bash
quarto preview
```
