### ISSUE TITLE
Extended author name schema doesn’t display correctly in listings 

### ISSUE THREAD

**Issue by JoFrhwld** [quarto-dev/quarto-cli#4881]
### Bug description

When using the [extended author name schema](https://quarto.org/docs/journals/authors.html#author-schema), authors’ names get rendered as [object Object] on listing pages. 

I’ve set up an example (https://github.com/JoFrhwld/quarto-name) using the default quarto blog template in RStudio, but adjusting the authors names like so

```yaml
author: 
  - name: 
      given: "Harlow"
      family: "Malloc"
```

and 

```yaml

author: 
  - name: 
      given: "Tristan"
      family: "O'Malley"
      literal: "Tristan O'Malley"
```

Both posts appear with “[object Object]” as the author name on the listing page. 

### Quarto & RStudio Versions
I’ve only run this reproducible example on RStudio Workbench with Quarto v1.0.36.

But you can see a live example here, which was built with Quarto v1.3.264

- url: https://lingmethodshub.github.io/content/python/
- post source: https://github.com/LingMethodsHub/Speaker-Diarization-for-Linguistics/blob/main/index.ipynb

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by irmoodie** [comment]
I can recreate this using Quarto version 1.6.40. Using the examples from [the Quarto docs](https://quarto.org/docs/websites/website-listings.html#yaml-listing-content) with the extended author name schema renders author names as [object Object].

Using the qmd file:
```qmd
---
title: "Listing Example"
listing:
  id: sample-listings
  contents: listing.yaml
  sort: "date desc"
  type: table
---
```
And the listing yaml file `listing.yaml`:

```yaml
- title: "Item 1"
  author: 
    - name:
        family: Jones
        given: Nora
    - name:
        family: Smith
        given: Bob
```

Is rendered as: 

<img width="668" alt="Image" src="https://github.com/user-attachments/assets/4a9c6fc6-2271-4aa8-b23c-b5dc5ab9d07b" />
