### ISSUE TITLE
Floating sidebar causes footer border to disappear

### ISSUE THREAD

**Issue by ravimakhija** [quarto-dev/quarto-cli#4971]
## Issue Description

It seems that using a floating `sidebar` in Quarto sets the `floating` class on the `body` element, which in turn causes bootstrap to not apply `border-top` to `nav-footer` (see below), in turn causing the footer border to not show up. 

```css
body:not(.floating) .nav-footer {
    border-top: 1px solid #dee2e6;
}
```

We are using custom CSS as a workaround currently (https://github.com/datascijedi/website/pull/79). 

## Reproducible Example

`_quarto.yml`

```yaml
project:
  type: website
  output-dir: _site

website:
  sidebar:
    - title: "Page 1 Sidebar"
      style: "floating"
      # style: "docked"
      border: true
      collapse-level: 2
      align: left
      contents:
        - text: "Page 1"
          file: page1.qmd

  page-footer:
    border: true
    left: "Left Stuff"
```

`page1.qmd`

```md
# Page 1
```

## Environment Details

OS: macOS Ventura 13.2.1
Rendering via CLI with with `quarto preview`. 

Output of `quarto check`:

```
[✓] Checking Quarto installation......OK
      Version: 1.1.251
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.16
      Path: ...
      Jupyter: 4.8.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
