### ISSUE TITLE
Markdown not properly rendered in breadcrumbs

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#5027]
When rendering a website, markdown that appears in the sidebar item content is not properly rendered in breadcrumbs. For example:

```yml
project:
  type: website

website:
  title: "Foo"
  sidebar:
    contents:
      - href: index.qmd
        text: "![](clown.png) Home"
      - href: about.qmd
        text: "![](clown2.png) About"
               

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

Results in raw markdown images appearing in breadcrumbs.
