### ISSUE TITLE
TOC covers wide text

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#51]
Given a Quarto project with a single `index.md`:

````markdown
---
title: widelink
---

## level two

we will give a link to the `shiny_prerendered_app` function: <https://github.com/rstudio/rmarkdown/blob/1ea35758871f6246ace35dc87a7879153deea380/R/shiny_prerendered.R#L2-L3>

* a link to `html_dependency_highlightjs`: <https://github.com/rstudio/rmarkdown/blob/1ea35758871f6246ace35dc87a7879153deea380/R/html_dependencies.R#L411-L419>

  * a sublist with the same link: <https://github.com/rstudio/rmarkdown/blob/1ea35758871f6246ace35dc87a7879153deea380/R/html_dependencies.R#L411-L419>
````

```yaml
project:
  type: site

site:
  title: "wide link list"
  sidebar:
    contents:
      - index.md

format:
  html:
    theme: darkly
    toc: true
```

The rendered site shows the long links, presents it as wrapped, but some of the long-line text is hidden by the TOC box. Sometimes (depending on indenting), that text can flow to the far right-hand side (past the TOC box):

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/362187/124293022-36d27580-db24-11eb-912f-9335e18e6dc9.png">

This example is using the `darkly` theme to make the text truncation more obvious.

I saw this display problem because one of my Markdown documents had a bare link; I can avoid it by using `[text](url)` instead. I don't know if it happens with other text that can overflow.
