### ISSUE TITLE
layout-ncol not working in beamer

### ISSUE THREAD

**Issue by sje30** [quarto-dev/quarto-cli#5137]
### Bug description

MWE adapted from the block-layout section of the docs:

````md
---
title: "bug"
format: beamer
---

## test

Taken from <https://quarto.org/docs/authoring/figures.html#block-layout>

::: {layout-ncol=2}
### List One

- Item A
- Item B
- Item C

### List Two

- Item X
- Item Y
- Item Z
:::
````

When I compile the above minimal example, I get an error from tex:

```
updating tlmgr

updating existing packages

compilation failed- error
LaTeX Error: \begin{beamercolorbox} on input line 223 ended by \end{minipage}
.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.223 \end{frame}
```

but when I change it to "format: pdf" everything compiles okay.  Earlier layout examples on that documentation (for aligning images) work fine in beamer.  What's up?

I see elsewhere in the quarto docs an alternative way for making multiple columns, <https://quarto.org/docs/presentations/beamer.html#multiple-columns> but there is a certain attraction to the shorter form in this MWE.

Environment:
```
quarto 1.2.475
running on Mac 13.2.1
```

quarto check:

```

[✓] Checking Quarto installation......OK
      Version: 1.2.475
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Users/stephen/.pyenv/versions/3.11.1/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.3
      Path: /opt/homebrew/Cellar/r/4.2.3/lib/R
      LibPaths:
        - /Users/stephen/NOBACKUP/RLIB
        - /opt/homebrew/Cellar/r/4.2.3/lib/R/library
      rmarkdown: 2.19

[✓] Checking Knitr engine render......OK

```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by sje30** [comment]
p.s. just tried with quarto 1.3.313 - same outcome.

**Comment by cscheid** [comment]
Thanks for the report. We're about to get a 1.3 version out and are focusing on regressions. Since this behavior is there since 1.2, we'll look at it in 1.4.

**Comment by baptiste** [comment]
For future reference, I was also a bit puzzled by columns vs layout in this discussion thread (but for article, not beamer):

[https://github.com/quarto-dev/quarto-cli/discussions/4959#discussioncomment-5428704]( minipage .columns layout #4959)

**Comment by cscheid** [comment]
This is going to be relatively tricky for us to do correctly. The problem lies in the way that Pandoc generates Beamer output, by inserting `\end{block}` calls when it sees the _next_ Header cell. We emit the following AST:

```yml
blocks:
  - t: "Header"
    level: 2
    attr: "('test', [], [])"
    content: "test"
  - t: "Para"
    content:
      - "Taken from "
      - t: "Link"
        attr: "('', ['uri'], [])"
        content: "https://quarto.org/docs/authoring/figures.html#block-layout"
        target: "https://quarto.org/docs/authoring/figures.html#block-layout"
        title: ""
  - t: "Plain"
    content: []
  - t: "RawBlock"
    format: "latex"
    text: "\\begin{figure}"
  - t: "Para"
    content:
      - t: "RawInline"
        format: "latex"
        text: "\\begin{minipage}[t]{0.50\\linewidth}\n"
  - t: "Header"
    level: 3
    attr: "('list-one', [], [])"
    content: "List One"
  - t: "BulletList"
    content:
      - t: "Plain"
        content: "Item A"
      - t: "Plain"
        content: "Item B"
      - t: "Plain"
        content: "Item C"
  - t: "Para"
    content:
      - t: "RawInline"
        format: "latex"
        text: "\\end{minipage}%\n%\n\\begin{minipage}[t]{0.50\\linewidth}\n"
  - t: "Header"
    level: 3
    attr: "('list-two', [], [])"
    content: "List Two"
  - t: "BulletList"
    content:
      - t: "Plain"
        content: "Item X"
      - t: "Plain"
        content: "Item Y"
      - t: "Plain"
        content: "Item Z"
  - t: "Para"
    content:
      - t: "RawInline"
        format: "latex"
        text: "\\end{minipage}%\n\n"
  - t: "RawBlock"
    format: "latex"
    text: "\\end{figure}%"
```

The generated .tex file is:

```tex
\begin{document}
\frame{\titlepage}

\begin{frame}{test}
\phantomsection\label{test}
Taken from
\url{https://quarto.org/docs/authoring/figures.html\#block-layout}

\begin{figure}

\begin{minipage}[t]{0.50\linewidth}

\begin{block}{List One}
\phantomsection\label{list-one}
\begin{itemize}
\tightlist
\item
  Item A
\item
  Item B
\item
  Item C
\end{itemize}

\end{minipage}%
%
\begin{minipage}[t]{0.50\linewidth}
\end{block}

\begin{block}{List Two}
\phantomsection\label{list-two}
\begin{itemize}
...
```

Note the mismatched block structure, where `\end{block}` happens after the `\begin{minipage}` call. The fundamental problem is that we don't control the pair `\end{block}\n\begin{block}`; it's emitted by Pandoc. So we have no place where to insert the minipage code.

I really wish we could support this, but I can't think of a way to do it.
