### ISSUE TITLE
`title-prefix` ignored in websites

### ISSUE THREAD

**Issue by petrbouchal** [quarto-dev/quarto-cli#5196]
### Bug description

In a website project, setting the `title-prefix` parameter has no effect, no matter where one sets it - in _quarto.yml, individual quarto documents or via a cli option.

I would expect the prefix to override the website title for individual documents or directories.

How to reproduce

```bash
quarto create-project --type website
```

edit _quarto.yml:

```yaml
project:
  type: website

title-prefix: "noprefix"

website:
  title: "quarto-title"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

edit `about.qmd`

```md
---
title: "About"
title-prefix: "noprefixtoo"
format:
  html:
    title-prefix: "stillnoprefix"
---

About this site
```

or run

```bash
quarto render --metadata "title-prefix: cliprefix"
```

Quarto 1.3.324
RStudio Version 2023.05.0-daily+52 (2023.05.0-daily+52)
MacOS 13.4 beta

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
