### ISSUE TITLE
Sudden problem with YAML parsing

### ISSUE THREAD

**Issue by jonellevillar** [quarto-dev/quarto-cli#5202]
### Bug description

I am preparing a quarto presentation for Tuesday the 18th. Everything was going well, and then I had some problems not being able to render the .qmd. Now today I get a parsing error.  I am only including the YAML rather than the entire .qmd and the rendering stops at line 5.

````
YAML parse exception at line 5, column 0,
while scanning a simple key:
could not find expected ':'
````
Here is my YAML:

````
---
title: "My Presentation"
author: "Me"
date: 04/18/2023
date-format: long
format:
  revealjs:
    chalkboard: true
incremental: true 
bibliography: references.bib    
---

````

I am able to render and have no problem with your YAML. 

````

---
title: "Quarto Presentations"
subtitle: "Create beautiful interactive slide decks with Reveal.js"
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: images/quarto.png
    css: styles.css
    footer: <https://quarto.org>
resources:
  - demo.pdf
---
````

```
I have the pleasure of using R-Studio Version 2023.03.0+386 (2023.03.0+386)
I am using MacOS Ventura 13.3.1 

[✓] Checking Quarto installation......OK
      Version: 1.2.475
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK

````
Would love to concentrate on my presentation rather than moving everything over to a Xarangan presentation - which is also very wonderful. 

Thanks for your help. 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
