### ISSUE TITLE
eq-prefix behaves different between PDF and HTML document

### ISSUE THREAD

**Issue by XiangyunHuang** [quarto-dev/quarto-cli#526]
Both html and pdf format are`eq-prefix: " "` in `_quarto.yml`, HTML output is expected.

```yml
format:
  html:
    theme: cosmo
    crossref:
      chapters: true
      eq-prefix: " "
  pdf:
    documentclass: book
    crossref:
      chapters: true
      eq-prefix: " "
```

 `(@eq-black-scholes)` in PDF format output is not consistent with HTML, PDF has extra space.

### HTML output

<img width="92" alt="html" src="https://user-images.githubusercontent.com/12031874/161662943-fb114bca-fcfb-4bcf-8ef8-2b0226c464bc.png">

### PDF output

<img width="161" alt="pdf" src="https://user-images.githubusercontent.com/12031874/161664945-e92c2e07-11b3-4ad8-a603-79e281b6d30e.png">

when I remove space in `eq-prefix`, some strange happen.

```yml
format:
  html:
    theme: cosmo
    crossref:
      chapters: true
      eq-prefix: " "
  pdf:
    documentclass: book
    crossref:
      chapters: true
      eq-prefix: ""
```

<img width="119" alt="pdf2" src="https://user-images.githubusercontent.com/12031874/161665325-6d34087a-6efd-4f90-8af2-32c7bbc9e844.png">

## Session info

I use latest [geospatial](https://github.com/rocker-org/rocker-versioned2), so Quarto: 0.9.178 and Pandoc: 2.17.1.1

**Comment by jjallaire** [comment]
Could you provide the full source code for the example that's exhibiting the surprising behavior? (I'm having trouble reproducing w/o the actual equation, section headings, etc. you are using)

**Comment by XiangyunHuang** [comment]
Firstly,  follow guides by RStudio IDE to create skeleton quarto book project.

Then, copy following text into file `intro.qmd` 

```
$$
\frac{\partial \mathrm C}{ \partial \mathrm t } + \frac{1}{2}\sigma^{2} \mathrm S^{2}
\frac{\partial^{2} \mathrm C}{\partial \mathrm C^2}
  + \mathrm r \mathrm S \frac{\partial \mathrm C}{\partial \mathrm S}\ =
  \mathrm r \mathrm C 
$$ {#eq-black-scholes}
```

Then, use following text in `_quarto.yml` instead

```yml
project:
  type: book

book:
  title: "quarto-book"
  author: "Jane Doe"
  date: "4/5/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    crossref:
      chapters: true
      eq-prefix: " "
  pdf:
    documentclass: book
    crossref:
      chapters: true
      eq-prefix: " "

editor: visual
```

Lastly, render book.
