### ISSUE TITLE
Twitter card "description" is not working

### ISSUE THREAD

**Issue by ravimakhija** [quarto-dev/quarto-cli#5263]
## Description

We are using the `twitter-card` option to include a "summary" Twitter card. 

The main issue here is that the card shows up, but the "description" is not showing up in the card. In particular, the `twitter:description` meta element is added, but the content is missing, so our HTML source has the following: 

```html
<meta name="twitter:description" content="">
```

You can also see this by viewing the HTML source of our live website at https://datascijedi.org/. 

A second minor issue is that the "title" is not being pulled in automatically from the website settings, though this has an easy fix of adding the `title` key manually under the `twitter-card` setting. 

## Reproducible Example

Any Quarto config with the following `twitter-card` settings included within the `website` option should reproduce the issue:

```yaml
website:
  twitter-card:
    card-style: summary
    site: "@datascijedi"
    title: "JEDI Outreach Group"
    description: "The Justice, Equity, Diversity, and Inclusion (JEDI) Outreach Group, a community of statisticians and data scientists, is committed to communication, programming, and professional development to advance and support a society that values all people."
    image: "images/jedi-logo-square.png"
```

To test, just build the Quarto website and you should see that the HTML source is not including the description in the `twitter:description` meta element. 

To test the second minor issue mentioned, remove `title` from the `twitter-card` setting and ensure a `title` setting is included immediately under the `website` key. After building, you should see in the HTML source that the title is not in the `twitter:title` meta element. 

## Additional Information

As a reference, our full Quarto config is below:

https://github.com/datascijedi/website/blob/1960be6c6c5ccac8bd012f694f1dd80c9f5719eb/_quarto.yml

Quarto Version: `quarto-1.3.298-linux-amd64`
Operating System: Linux (the version being used on Netlify build servers)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
