### ISSUE TITLE
Non-root site path not working

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#5267]
Comments in the discussion referenced below mentioned a problem with URLs without trailing slash as opposed to with; to wit:

 "So when I go my website on the subdomain without a trailing / the site doesn't work. So for example I have this deployed to https://www.algebraicjulia.org/blog/ but if you go to https://www.algebraicjulia.org/blog the website does not function correctly."

@cscheid responded "Can you open a new issue? We definitely want to fix this."

Commenter apparently never did.  I'm doing it now because behavior is still the same.

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3615

<div type='discussions-op-text'>

<sup>Originally posted by **michielvdmeulen** December  9, 2022</sup>
I'm trying to serve a blog on a non-root path, but despite following the instructions in the [documentation](https://quarto.org/docs/websites/website-navigation.html#non-root-site-paths) I can't get it to work. My situation is identical to that in the docs, apart from different url naming of course, so something like this:

URL:
https://example.com/mysite/ 

_quarto.yml:
```
website:
  title: "My Site"
  site-path: "/mysite/"
```

When I render the site with and without the `site-path` option and compare the generated `index.html` file in the `_site` folder, both are exactly identical - even when I have completely deleted and re-rendered the content. In fact, only the `_site\site_libs\quarto-nav\quarto-nav.js` file has one line difference:
![Screenshot_1](https://user-images.githubusercontent.com/15234562/206665447-fe8aa527-bf25-4b13-a1a4-d0ea40750b3b.png)
Apparently, this is either not enough or is not picked up on the server side. I'm using the latest Quarto version (1.2.269).

Does someone have an idea what could be wrong? Any help would be highly appreciated!</div>

**Comment by cderv** [comment]
> I'm using the latest Quarto version (1.2.269).

@blacksqr Can you try with the 1.3 release candidate available already at main download ? https://quarto.org/docs/download/

I didn't test, and don't know for sure, but best to check if this is still happening without our current 1.3 version soon to be release. 

Thanks

**Comment by blacksqr** [comment]
I'm sorry, I should have specified that I'm using 1.3.282.

**Comment by nvelden** [comment]
I am having the same issue with `v1.4.245` using a books website. I have placed the /docs folder in the www directory in my Shiny app and navigate to the index file using:

```
tags$li(a(href = '/docs/index.html',
              target = "_blank",
              icon("info-circle", lib = "font-awesome"), style = "font-size: 18px; color: #356DEB"), class = "dropdown"
    ),
```

It opens fine but when I click on a book chapter and click back to my main index it navigates to /docs/ instead of /docs/index.html causing a page not found Error. 

_quarto.yml

```
project:
  type: book
  output-dir: docs

book:
  title: "User Guide"
  site-url: "/index.html"
  sidebar:
    title: "<a href='/index.html'>User Guide</a>"
    logo: logo.png
  repo-url: https://github.com/organisation/UserGuide
  repo-branch: main
  repo-actions: [issue]
  favicon: favicon.png

  chapters:
    - index.qmd
    - part: "Guides"
      chapters:
        - data.qmd
        - docker.qmd
        - actions.qmd
        - documentation.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
```

```
quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.5: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.245
      Path: /Applications/quarto/bin
```

```
quarto render

[1/5] index.qmd
[2/5] data.qmd
[3/5] docker.qmd
[4/5] actions.qmd
[5/5] documentation.qmd

pandoc 
  to: latex
  output-file: index.tex
  standalone: true
  toc: true
  number-sections: true
  top-level-division: chapter
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  crossref:
    chapters: true
  documentclass: scrreprt
  papersize: letter
  classoption:
    - DIV=11
    - numbers=noendperiod
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  bibliography:
    - references.bib
  editor: visual
  title: User Guide
  

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  

Output created: docs/index.html
```
