### ISSUE TITLE
title block banner doesn't display in mobile view

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#5296]
### Bug description

I created a listing page with a title block banner and categories set to true, with a sidebar defined in _quarto.yml.

When each of those elements is specified and I view the page in my browser (Firefox or Chromium), the title banner displays.

When I switch to mobile view (e.g. ctrl-shift-m in Firefox), the title banner disappears.

To reproduce:

Create a new website project: 

```
$ quarto create-project mysite --type website
$ quarto preview mysite
```

Edit _quarto.yml so its contents are as below.  Note only the sidebar entry has been added:

```
project:
  type: website

website:
  title: "mysite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    - id: sidebar_id

format:
  html:
    theme: cosmo
    css: styles.css
```

Edit about.qmd as below:

```
---
title: "Listing Example"
listing:
  type: default
  categories: true
title-block-banner: true
---

```

After quarto preview has re-rendered the site with these edits, switch to mobile view.  The title block with the text "Listing Example" is not displayed.  If I remove the "title-block-banner", "categories" or "sidebar" entry, the title block is displayed in mobile view.  It's the combination of the three features that causes the problem.

OS: Kubuntu 20.04

Quarto version: 1.3.282

Firefox version: 112.0.1

Chromium version: 111.0.5563.146 (Official Build) snap (64-bit)

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
