### ISSUE TITLE
`about` page doesn't allow computation in the YAML header

### ISSUE THREAD

**Issue by MikeLydeamore** [quarto-dev/quarto-cli#5308]
### Bug description

The `about` page templates don't seem to allow for computation within the YAML header. Computation still works in outer blocks like `title`, but not inside anything in `about`.

A reproducible example (from the Quarto page):

```
---
title: "Finley Malloc"
about:
  template: jolla
  image: profile.jpg
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: "`r Sys.Date()`"
---

Finley Malloc is the Chief Data Scientist at Wengo Analytics. When not innovating on data platforms, Finley enjoys spending  time unicycling and playing with her pet iguana.
```

The link for "GitHub" is the literal string `r Sys.Date()` rather than doing the computation.

I've tried `!expr` as well but haven't managed to get that to work successfully.

Quarto check:
```
✓] Checking Quarto installation......OK
      Version: 1.0.38
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

(\) Checking R installation...........Warning message:
This project is configured to use R version '4.1.2', but '4.2.2' is currently being used. 
[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mlyd0001/projects/SPECTRUMSPARKWebsite/renv/library/R-4.2/aarch64-apple-darwin20
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
