### ISSUE TITLE
Quarto 1.3 fails

### ISSUE THREAD

**Issue by msh855** [quarto-dev/quarto-cli#5323]
I just switched to Quarto 1.3 to be able to download multiple formats and this has broken everything on my website/blog. 

I am not sure what is causing the problem. But has broken all my processes. For example, I cannot preview my blog anymore.

Here is the error that I get once I type  `quarto preview` : 

ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 11, columns 3--10) property name listing is invalid
10:     left: "Usual Disclaimer applies"
11:   listing:
     ~~~~~~~~
12:     contents: posts
ℹ The error happened in location website:listing.


In file _quarto.yml
(line 17, columns 3--21) property name title-block-banner is invalid
16:     feed: true
17:   title-block-banner: true
     ~~~~~~~~~~~~~~~~~~~
ℹ The error happened in location website:title-block-banner.

In file _quarto.yml
(line 41, columns 3--10) property name filters is invalid
40:   cookie-consent: false
41:   filters:
     ~~~~~~~~
42:   - code-filename
ℹ The error happened in location website:filters.


Error: Project _quarto.yml validation failed.

In file _quarto.yml
(line 11, columns 3--10) property name listing is invalid
10:     left: "Usual Disclaimer applies"
11:   listing:
     ~~~~~~~~
12:     contents: posts
ℹ The error happened in location website:listing.

In file _quarto.yml
(line 17, columns 3--21) property name title-block-banner is invalid
16:     feed: true
17:   title-block-banner: true
     ~~~~~~~~~~~~~~~~~~~
ℹ The error happened in location website:title-block-banner.


In file _quarto.yml
(line 41, columns 3--10) property name filters is invalid
40:   cookie-consent: false
41:   filters:
     ~~~~~~~~
42:   - code-filename
ℹ The error happened in location website:filters.

    at readAndValidateYamlFromFile (file:///Applications/quarto/bin/quarto.js:42120:15)
    at async file:///Applications/quarto/bin/quarto.js:82868:26
    at async projectContext (file:///Applications/quarto/bin/quarto.js:82720:26)
    at async serveProject (file:///Applications/quarto/bin/quarto.js:103144:19)
    at async Command.fn (file:///Applications/quarto/bin/quarto.js:103742:13)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///Applications/quarto/bin/quarto.js:127535:5)
    at async file:///Applications/quarto/bin/quarto.js:127553:9

**Comment by cbrnr** [comment]
I'm not sure if this is related, but I also get an error with 1.3 (which I didn't get with 1.2):

```
ERROR: NotFound: No such file or directory (os error 2), stat '08/08/08/08_files/libs'

NotFound: No such file or directory (os error 2), stat '08/08/08/08_files/libs'
    at Object.statSync (deno:runtime/js/30_fs.js:322:9)
    at file:///Users/clemens/Applications/quarto/bin/quarto.js:121353:18
    at Array.reduce (<anonymous>)
    at normalizePublishFiles (file:///Users/clemens/Applications/quarto/bin/quarto.js:121351:45)
    at renderForPublish (file:///Users/clemens/Applications/quarto/bin/quarto.js:121303:24)
    at async renderForPublish (file:///Users/clemens/Applications/quarto/bin/quarto.js:109082:24)
    at async handlePublish (file:///Users/clemens/Applications/quarto/bin/quarto.js:108988:26)
    at async publishDocument (file:///Users/clemens/Applications/quarto/bin/quarto.js:121342:38)
    at async publish5 (file:///Users/clemens/Applications/quarto/bin/quarto.js:121438:132)
    at async doPublish (file:///Users/clemens/Applications/quarto/bin/quarto.js:121394:13)
```

Here, I used

```
quarto publish 08/08.qmd
```

However, when running the command from the same folder as the document, everything works:

```
quarto publish 08.qmd
```

I've already reported such an issue for an older version (#2623), but it seems like something broke that fix.

**Comment by dragonstyle** [comment]
Could you share your `_quarto.yml` file or a repo that I could look at to reproduce the issue? Based only upon the error messages, it is challenging to debug.

**Comment by cbrnr** [comment]
It looks like my error is unrelated, so I'll open a new issue.

**Comment by msh855** [comment]
It fixed the problem by removing what you suggested in the yml file. But it broke the process in publishing the website. 

I can an error about invalid web address. In the previous version i was publishing my website in a custom domain without problems: 


NOTE: GitHub Pages sites use caching so you might need to click the refresh
button within your web browser to see changes after deployment.

[✓] Deploying gh-pages branch to website (this may take a few minutes)
ERROR: TypeError: Invalid URL

TypeError: Invalid URL
    at getSerialization (deno:ext/url/00_url.js:76:13)
    at opUrlParse (deno:ext/url/00_url.js:67:12)
    at new URL (deno:ext/url/00_url.js:358:29)
    at new Request (deno:ext/fetch/23_request.js:306:27)
    at deno:ext/fetch/26_fetch.js:392:29
    at new Promise (<anonymous>)
    at fetch (deno:ext/fetch/26_fetch.js:388:20)
    at file:///Applications/quarto/bin/quarto.js:120516:40
    at async withSpinner (file:///Applications/quarto/bin/quarto.js:56612:9)
    at async Object.publish4 [as publish] (file:///Applications/quarto/bin/quarto.js:120510:9)

**Comment by dragonstyle** [comment]
I think that this should do it:

```yaml
project:
  type: website
  output-dir: docs

website:
  title: "Moustafa Chatzouz"
  site-url: www.the-quant-economist.com #https://msh855.github.io/TheQuantEconomist
  description: "Observations about Macroecnomics, Finance and Public Debates"
  page-footer:
    left: "Usual Disclaimer applies"

  navbar:
    #right:
     # - text: Home
     #   href: home.qmd
    right:
      #- text: Macroeconomics for Social Change
      #  href: macro_for_social_change.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/msh855
      - icon: twitter
        href: https://twitter.com/Hajjouz
      - icon: linkedin
        href: https://www.linkedin.com/in/moustafa-chatzouz/


    #  - icon: rss
    #    href: index.xml

  google-analytics:  "170377145"
  cookie-consent: false

execute:
  freeze: auto

#format:
#  html:
#    theme: yeti
#    css: styles.css

format:
  html:
    title-block-banner: true
    theme:
      light: theme.scss #yeti
      dark: Darkly
## ref: https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html

```

I did the following:

- Removed the `listing` entirely since that is really a per page thing not something global to projects.
- Move `title-block-banner` into the html formate
- Remove the code-filename filter, we should natively support code files in 1.3

LMK if this doesn't work - I didn't actually run it to verify ;-)
