### ISSUE TITLE
PDF Compilation not working

### ISSUE THREAD

**Issue by msh855** [quarto-dev/quarto-cli#5351]
I recently switched to Quarto 1.3, so I can have the option to include other formats in my blog posts. Sadly, this option does not work for me. Here is the error I get: 

```
ERROR: Error executing '/Users/safishajjouz/Library/TinyTeX/bin/universal-darwin/tlmgr': No such file or directory (os error 2)

Error: Error executing '/Users/safishajjouz/Library/TinyTeX/bin/universal-darwin/tlmgr': No such file or directory (os error 2)
    at execProcess (file:///Applications/quarto/bin/quarto.js:5630:15)
    at execTlmgr (file:///Applications/quarto/bin/quarto.js:85261:16)
    at tlmgrCommand (file:///Applications/quarto/bin/quarto.js:85275:16)
    at findPackages (file:///Applications/quarto/bin/quarto.js:85119:35)
    at Object.searchPackages (file:///Applications/quarto/bin/quarto.js:85482:20)
    at runLatexCommand (file:///Applications/quarto/bin/quarto.js:85440:60)
    at async runPdfEngine (file:///Applications/quarto/bin/quarto.js:85346:21)
    at async initialCompileLatex (file:///Applications/quarto/bin/quarto.js:85780:26)
    at async generatePdf (file:///Applications/quarto/bin/quarto.js:85754:22)
    at async Object.complete (file:///Applications/quarto/bin/quarto.js:86026:27)
```

My posts configurations are: 

```

---
title: "Fed's Forward Guidance"
subtitle: "*Some Stylised Facts and recent performance*"
date: "04/22/2023"
draft: false
categories:
  - Monetary Policy
  - Inflation  
execute:
   echo: false
format: 
  html: default
  ipynb: default
  pdf: default
title-block-banner: false
comments:
  hypothesis: 
    theme: clean
---
```

In case this helps this is the post/file: https://github.com/msh855/TheQuantEconomist/tree/main/posts/Hawkish_Fed
