### ISSUE TITLE
`og:image` doesn't propagate from `_quarto.yml` unless also mentioned in page front matter

### ISSUE THREAD

**Issue by hamelsmu** [quarto-dev/quarto-cli#5389]
The `og:image` tag doesn't show up in my website header tags if the only thing I do is set the following in `_quarto.yml`

```yaml
website:
  title: "nbdev Tutorial: JupyterCon 2023"
  image: nbdev.png
  site-url: "https://fastai.github.io/jupytercon-2023/"
  open-graph: true
```
From [this file](https://github.com/fastai/jupytercon-2023/blob/main/_quarto.yml#L1C1-L23)

According to the [docs](https://quarto.org/docs/reference/projects/websites.html#social) this should work.  " By default, Quarto will use the image value from the format metadata."

The reason I think this is a bug is then repeat this in a page front matter [like so](https://github.com/fastai/jupytercon-2023/blob/main/index.qmd), **then the image propagates to ALL pages on the site**. 

```yaml
---
title: "nbdev Tutorial"
description: "An outline of the nbdev + Quarto tutorial for JupyterCon, 2023."
image: nbdev.png
---
```

Here is a repo you can use to play with this https://github.com/fastai/jupytercon-2023
I tried this on both the bleeding edge `1.4.25` and stable `1.3.340` and happens in both places

cc: @jjallaire @seem @mcanouil
