### ISSUE TITLE
revealjs menu option useTextContentForMissingTitles is missing

### ISSUE THREAD

**Issue by nickriches** [quarto-dev/quarto-cli#5404]
Hi

The above option is available for the github version of the plugin. However the version of the menu plugin which ships with Quarto does not allow this. I would really love to have this option. Currently, the menu inserts the first few words of each slide whenever there is no title text. This fills up the menu with a lot of text and makes it very difficult to read. Having the above option would solve this issue.

(NB there is a general lack of documentation regarding the various options on the Quarto website).

**Comment by cderv** [comment]
What did you try exactly ? 

Let's try with 

````markdown
---
title: test
format: revealjs
---

# Content

## Content 2 

## 

No title 

## 

No title

## Title 3

# Another Part

## 

Content

## Title last

Content

````

We do set in Quarto  `useTextContentForMissingTitles: true` as a default so that slides with no title have some content showed in TOC 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/2bf737a0-df24-4dc3-82b2-58585c90dad0)


This  can be deactivated using `menu` options 
````yaml
format: 
  revealjs:
    menu:
      useTextContentForMissingTitles: false
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/33f59dd2-b8b6-4f03-9dfc-5d51dc5543e8)

And you can also apply the other option, if you want to hide them 

````yaml
format: 
  revealjs:
    menu:
      useTextContentForMissingTitles: false
      hideMissingTitles: true
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/a0ea21f6-7791-41b8-b109-a1306ab434c1)

So it seems to work as expected. 

I'll close this, but feel free to reopen if I missed something. 

Thank you !

**Comment by rdinter-usda** [comment]
Running into a similar issue, when yaml is:

```
format:
  revealjs:
    menu:
      hideMissingTitles: true
```
ie, not including the `useTextContentForMissingTitles: false` option, then the undesired behaviour occurs again:

![image](https://github.com/quarto-dev/quarto-cli/assets/82044401/663a3d4b-740e-48af-b391-b5b8af255f8f)
