### ISSUE TITLE
Field "cookie-consent" has value implicit, which must instead be an object

### ISSUE THREAD

**Issue by petzi53** [quarto-dev/quarto-cli#5424]
### Bug description

After I added the field "cookie-consent" under the `website` key, I got the error message: `Field "cookie-consent" has value implicit, which must instead be an object`. The same happened with the "express" qualifier. 

But there is no error message if I use "true" or "false". And "true" opens a window the first time: "We use cookies" and adds "Cookie Preferences" to the footer.

I used the [reference documentation](https://quarto.org/docs/reference/projects/websites.html#meta-project-type-upper) for "Website" but also the [Website Tools docs under Guide](https://quarto.org/docs/websites/website-tools.html). One of the links in the TOC on the right side of the docs "Website Tools" website says, "Cookie Consent" but this link does not work. It opens a submenu with "Cookie Preferences" and "Custom Script and Cookie Consent." Again, these links do not work.

Could it be that the documentation is not up-to-date?

I am using:

- R version 4.3.0 (2023-04-21), 
- RStudio Version 2023.03.0+386 (2023.03.0+386)
- Quarto Version: 1.4.36 from the latest nightly release (but tested I it also with Version 1.3.340)
- MacBook Pro, Ventura 13.3.1

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by dragonstyle** [comment]
Could you share the project file that is causing this issue? I tried with the following and am not able to reproduce the issue:

```yaml
project:
  type: website

website:
  title: "Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  cookie-consent:
    type: implied    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```
