### ISSUE TITLE
RSS XML file not generated when "embed-resources: true" set

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#5469]
### Bug description

When adding "embed-resources: true" to a working Quarto site with RSS enabled, no RSS xml file was generated, and at render a warning message appeared that the xml file could not be fetched.

To reproduce:

Create a new website project:

```
$ quarto create-project mysite --type website
```

Edit _quarto.yml so its contents are as below:

```
project:
  type: website

website:
  title: "mysite"
  site-url: https://www.myblogexample.io
  description: "A great sample blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: rss
        href: about.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: false
```

Edit about.qmd as below:

```
---
title: "Listing Example"
listing:
  contents: "*"
  type: default
  categories: true
  feed: true
---
```

At this point, `quarto render mysite` works as expected, and about.xml is created

Now in _quarto.yml, change `embed-resources: false` to `embed-resources: true`.  Execute `quarto render mysite` again.

The following output appears:

```
$ quarto render mysite
[1/2] index.qmd
[2/2] about.qmd
[WARNING] Could not fetch resource about.xml

Output created: _site/index.html
```

Clicking on the RSS icon of the newly-rendered navbar returns a 404 error, and there is no RSS xml file in the _site subdirectory.

Strangely, "quarto preview" appears to render the site correctly.

OS: Kubuntu 20.04

Quarto version: 1.3.282

```
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.282
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /usr/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.37
      rmarkdown: 2.11

[✓] Checking Knitr engine render......OK

```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
