### ISSUE TITLE
'--' should be escaped in href to avoid en dash conversion

### ISSUE THREAD

**Issue by rnd195** [quarto-dev/quarto-cli#5503]
### Bug description

While building a website using Quarto, a link that contains `--` (e.g., <https://docs.gitlab.com/ee/topics/git/git_rebase.html#--force-with-lease-flag>) is broken **because `--` is converted to an en dash `–`.**

However, this only seems to happen for links in the `_quarto.yml` config file. 

Steps to reproduce:

1. Create a new web project in Quarto
2. Add a link containing `--` to `_quarto.yml`, for example:
```yml
project:
  type: website

website:
  title: "quarto-bug"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://docs.gitlab.com/ee/topics/git/git_rebase.html#--force-with-lease-flag
        text: "Broken link with dash-dash"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

3. Render the page
4. The link now contains an en dash instead of `--`
```
# Expected
https://docs.gitlab.com/ee/topics/git/git_rebase.html#--force-with-lease-flag
# Actual
https://docs.gitlab.com/ee/topics/git/git_rebase.html#%E2%80%93force-with-lease-flag
```

Note that in this particular case, the user is still directed to the correct page, but not to the correct reference.

***

I am on Windows 10, below is the output of `quarto check`. The issue is also present on the latest nightly release.

```
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.340
      Path: C:\Users\<MyUserName>\AppData\Local\Programs\Quarto\bin
      CodePage: 1250

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.0
      Path: C:/PROGRA~1/R/R-43~1.0
      LibPaths:
        - C:/Users/<MyUserName>/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.0/library
      knitr: 1.42
      rmarkdown: 2.21

[>] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
I created a website project, added the link, it indeed turned into `https://docs.gitlab.com/ee/topics/git/git_rebase.html#–force-with-lease-flag` but it works on MacOS using Safari and Brave (chromium) browsers.

Note that `--` to en-dahs is Pandoc doing.
Maybe quarto could escape`--` in url or keep URL as raw as possible.

**Comment by mcanouil** [comment]
@rnd195 Could you rename the issue as `'--' should be escaped in href to avoid en-dash conversion` or something like that?

**Comment by cderv** [comment]
@dragonstyle I believe this is the related to issue https://github.com/quarto-dev/quarto-cli/issues/3493 and our discussion about escaped characters in `href` as we do currently some md replacement in `website-navigation-md.ts`

My understanding is that we do this pipeline of markdown parsing to allow `href: https://foo.com/ver-{{< var version >}}` - maybe it is not that common, or we should try to detect shortcode and do replacement only for this 🤷‍♂️ 

Anyway, just sharing for reference between both issues.

**Comment by mcanouil** [comment]
Same trick as https://github.com/quarto-dev/quarto-cli/discussions/5679#discussioncomment-5999333 should also work here.

In `_variables.yml`:

```yml
gitlab: "`https://docs.gitlab.com/ee/topics/git/git_rebase.html#--force-with-lease-flag`{=html}"
```

In `_quarto.yml`:

```yml
  navbar:
    left:
      - text: "Broken link with dash-dash"
        href: "{{< var gitlab >}}"
```
