### ISSUE TITLE
Enhancement: `quarto-navigation-envelope` for block elements (can't put block tags in footer)

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#5604]
### Bug description

When I attempt to put html tags in the text of the "page-footer" option, the tags are filtered out.

to reproduce:

create a new book project:

```
$ quarto create-project mybook --type book
$ quarto preview mybook
```

Edit _quarto.yml as below:

```
project:
  type: book

book:
  title: "mybook"
  author: "Norah Jones"
  date: "5/18/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  page-footer:
    center: outside<div>inside</div>

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

When the project is rendered, only the word "outside" is visible in the footer.  The div tags have been filtered out.

Is there a way to add arbitrary content to a footer?

OS: Kubuntu 20.04

Quarto version: 1.3.282

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
