### ISSUE TITLE
Cross-referencing unnumbered appendix slide in Revealjs presentation

### ISSUE THREAD

**Issue by jpowerj** [quarto-dev/quarto-cli#5621]
### Bug description

Hi all,

I'm using Quarto websites, with Quarto+Revealjs slides, for a course I'm teaching in the fall, and absolutely loving everything about it :)

I have a very corner-case issue: I can cross-reference slides perfectly well, except for those I've given the class `.unnumbered`, which I'm using at the moment for Appendix slides (extra info, answers to questions that may come up, etc.).

As far as I can tell, adding `.unnumbered` is what's breaking it, as my MWE hopefully shows. But I'm leaving in some of my front matter to show that e.g. `slide-number` is set to `true`, as is helpfully [mentioned in the docs](https://quarto.org/docs/authoring/cross-references.html#sections)!

From what I know about `pandoc` and traversing nodes and etc., it seems like it's probably related to #3234, though in my case it's all within a single `.qmd` file. And, feel free to close if it's already being fixed in the newer version referenced [here](https://github.com/quarto-dev/quarto-cli/issues/2412#issuecomment-1259362430)

MWE is just the following (and in a [gist](https://gist.github.com/jpowerj/32fa0c91edfb1992db4cf050b3a20b95#file-test-slides-qmd) just in case):

```
---
title: "Appendix Cross-Ref: MWE"
format:
  revealjs:
    slide-number: true
    number-sections: true
    number-depth: 2
    code-fold: true
    footnotes-hover: true
    scrollable: true
    df-print: kable
---

## First Slide

See @sec-appendix-a. Then see @sec-appendix-b.

## Appendix A: Continuous RV Support {#sec-appendix-a .unnumbered}

First appendix.

## Appendix B: Numbered {#sec-appendix-b .appendix}

Second appendix. This one can be referenced
```

I am using the VSCode extension, so no R Studio version issues I don't think. OS is Windows 11. Here is my `quarto check` output (I'm omitting the Jupyter part just because, I have a weird Jupyter setup for research stuff, so it just produces a big error that I know how to fix but haven't fixed yet!)

```
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.319
      Path: C:\Users\jpjac\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.10.5
      Path: C:/Python310/python.exe
      Jupyter: 5.3.0
      Kernels: whatlies, python3
```

Like I said, I imagine I'm in the same boat as #3234, but would love the ability to cross-reference Appendix slides/sections in future versions! Thanks so much.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
