### ISSUE TITLE
Wrong Open Graph image chosen

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#5625]
### Bug description

I specify website `image:`  and `open-graph: true` values, but the rendered page chooses another image for the `meta property="og:image"` content value.

To reproduce:

create a new weblog project:

```
$ quarto create-project myblog --type website:blog
$ quarto preview myblog
```

Edit _quarto.yml so it appears as follows:

```
project:
  type: website

website:
  title: "myblog"
  image: "/posts/post-with-code/image.jpg"
  open-graph: true
  page-footer:
    center: |
      Footer image:
      [![](/profile.jpg)](https://quarto.org/)
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: cosmo
    css: styles.css
```

The og metadata in the rendered page appears as:

```
<meta property="og:title" content="myblog">
<meta property="og:image" content="./profile.jpg">
<meta property="og:site-name" content="myblog">
```

The image from the footer section is chosen instead of the website `image:` metadata.

OS: Kubuntu 20.04

Quarto version: 1.3.282

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
