### ISSUE TITLE
Rendering to ePUB then HTML breaks page links.

### ISSUE THREAD

**Issue by BradyAJohnston** [quarto-dev/quarto-cli#564]
If I render first to `epub` then to `html`, the links in the HTML document are broken.

I have been able to replicate this with the beginner book project from "Create New Project" -> "Quarto Book" through the RStudio IDE, and making some minor changes to the `_quarto.yml` as below: 

```yaml
project:
  type: book

book:
  title: "test"
  author: "Jane Doe"
  date: "07/04/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  epub:
    html-math-method: mathjax
  html:
    theme: cosmo

editor: visual
```

Rendering first to `epub` with:
```bash
quarto render --to epub
```

Then if I render to HTML with:
```bash
quarto render --to HTML
```

The index page will load fine, but all of the links from the TOC on the left link to a `.epub` URL instead of `.html`, i.e. the "Introduction" will link to: 
```
file:///Users/brady/Desktop/test/_book/intro.epub
```
If I then change the `.epub` to the `.html` the page will load. All of the links from the TOC on the left hand side seem to be similarly affected.

If I remove the epub entry from the YAML and re-render the document to HTML the links are correct.
