### ISSUE TITLE
wrapped sidebar headings appear to be distinct entries

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#5640]
### Bug description

Using Quarto 1.3.340 and macOS

Using a Quarto project with the YAML:

```yaml
project:
  type: website

website:
  sidebar:
    - title: "navigations"
      contents:
        - text: "apples, bananas, and cucumbers"
          file: "index.qmd"
        - text: "cucumbers salad"
          file: "cucumbers.qmd"
        - text: "roasting brussels sprouts"
          file: "roasting.qmd"
```

Each of `index.qmd`, `cucumbers.qmd`, and `roasting.qmd` are empty files.

```bash
touch index.qmd cucumbers.qmd roasting.qmd
```

When rendered, the first heading tends to wrap. When it wraps, the line spacing makes the wrapped line look like a distinct entry, not like text that belongs with the previous line.

<img width="277" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/7137835e-9f68-43c5-bc44-35b75210712d">

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 3.6.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/3.6/Resources/library
      knitr: 1.42.8
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
