### ISSUE TITLE
sidebar click-to-expand region too narrow

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#5642]
### Bug description

Using Quarto 1.3.340 on macOS with Safari.

Given the Quarto project:

```yaml
project:
  type: website

website:
  sidebar:
    - title: "important things"
      collapse-level: 1
      contents:
        - text: "introduction"
          file: "index.qmd"
        - section: "R"
          contents:
            - text: "overview"
              file: "r.qmd"
            - text: "details"
              file: "details.qmd"
```

and empty `*.qmd` files:

```bash
touch index.qmd r.qmd details.qmd
```

When previewed, the sidebar navigation for "R" allows clicking only on the text "R" and the "&gt;" marker. The remainder of the line between the text and marker is not clickable. That region does, however, does activate the "hover" for that line.

This short capture shows the text becoming active on hover, but not allowing a click.

https://github.com/quarto-dev/quarto-cli/assets/362187/c17a0abb-1e35-4af0-a2e9-a46371154d99

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 3.6.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/3.6/Resources/library
      knitr: 1.42.8
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
