### ISSUE TITLE
extra book sidebar search icon visible in mobile view

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#5653]
### Bug description

If I create a book project and add a navbar to it, then (as expected) the sidebar search field is removed and a search icon is added to the navbar.

But If I switch to mobile view in a browser (ctrl-shift-m on Firefox), or look at the site on a mobile phone, then a search icon is added to the collapsible "sidebar" menu near the top, while the original search icon in the navbar remains.

To reproduce:

Create a new book project:

```
$ quarto create-project mybook --type book
$ quarto preview mybook
```

Add a navbar tag to _quarto.yml as follows:

```
project:
  type: book

book:
  title: "mybook"
  author: "Norah Jones"
  date: "5/23/2023"
  navbar:
    title: "My Book"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```
Switch to mobile view.  A search icon is visible on the right of the collapsed menu, under the navbar which has its own search icon.

OS: Kubuntu 20.04

Quarto version: 1.3.282

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
