### ISSUE TITLE
sidebar with single sidebar entry gets shown across entire website

### ISSUE THREAD

**Issue by machow** [quarto-dev/quarto-cli#5689]
### Bug description

When I create a quarto website with a single sidebar, it gets shown across all pages. However, if I add an additional sidebar entry, e.g. with `- id: dummy-sidebar`, it shows the original sidebar on only the relevant pages.

(I'm running quarto version 1.3.340)

Here an example setup where the sidebar displays on the home page.

**_quarto.yml**

```yaml
project:
  type: website

website:
  sidebar:
  - contents:
    - reference/index.qmd
    id: reference

  # note that uncommenting below fixes the issue
  #- id: dummy-sidebar
```

**index.qmd**

```
---
title: homepage
---

I am a test page
```

**reference/index.qmd**

```
---
title: reference
---

I am the reference page
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.
