### ISSUE TITLE
GitHub Action publish does not create "site_libs" folder

### ISSUE THREAD

**Issue by schochastics** [quarto-dev/quarto-cli#5738]
### Bug description

We are using the GitHub action to publish the website in this repository: https://github.com/gesiscss/quarto-workshop
to https://gesiscss.github.io/quarto-workshop/ but the action does not produce the `site_libs` folder with the required libraries. rendering it locally does produce the `site_libs` folder (quarto 1.3.151). The GA was setup according to the documentation on quarto.org.
This is the `publish.yml` file
```yaml
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Edit: using `lib-dir: "libs"` to change the default "site_libs" folder also did not fix the issue

### Steps to reproduce

deploy  https://github.com/gesiscss/quarto-workshop in a different github account
