### ISSUE TITLE
Quarto doesn't print authors and affiliations defined in the YAML if the title is missing

### ISSUE THREAD

**Issue by arnaudgallou** [quarto-dev/quarto-cli#5856]
### Bug description

Authors and affiliations in the YAML header aren't printed when there's no title defined.

### Steps to reproduce

```
---
format: html
author:
  - name: Norah Jones
    affiliations:
      - ref: cmu
      - ref: chicago
affiliations:
  - id: cmu
    name: Carnegie Mellon University
    city: Pittsburgh
    state: PA
  - id: chicago
    name: University of Chicago
    city: Chicago
    state: IL
---

Foo
```

### Expected behavior

I'd expect the output to show the author and her respective affiliations.

### Actual behavior

The example above prints `Foo` only.

### Your environment

IDE: RStudio 2023.03.1+446
OS: MacOS Monterey 12.3.1

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.361
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.12
      Path: /usr/local/opt/python@3.9/bin/python3.9
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.0
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```
