### ISSUE TITLE
GitHub Actions fails b/o missing rmarkdown package

### ISSUE THREAD

**Issue by pjastam** [quarto-dev/quarto-cli#5870]
### Bug description

I set-up a new website following the approach described [here](https://quarto.org/docs/publishing/netlify.html#github-action):

- Repo hosted on GitHub ([here](https://github.com/pjastam/test-github-actions/))
- Site built by GitHub actions
- Computations ran locally with creation of a _freeze directory put under version control
- Site hosted on Netlify

All works great at first. However, when I add some text to the `index.qmd` file and render the page, the GitHub workflow run fails. If I use a Windows runner instead of an Ubuntu runner the workflow finishes successfully again. (Note: I also added renv but this did not help me/change my use case, results not reported here)

### Steps to reproduce

See [this commit](https://github.com/pjastam/test-github-actions/commit/d39501081e95424ea453c823d079b574caed36c2) for the code that is running smoothly with GitHub Actions at first.

See [this commit](https://github.com/pjastam/test-github-actions/commit/6666f949ceb658681e59998e64d073d135452d3c) for the code changes due to adding some text to the `index.qmd` file, for which the workflow run fails.

See [this commit](https://github.com/pjastam/test-github-actions/commit/ab9b9d145b422daef63cab7bcc984c51d0b6f4d6) for code with the change to the Windows runner in the `publish.yml` file and after rerendering the Quarto website because of that.

### Expected behavior

The GitHub workflow runs as expected at first, see [this log](https://github.com/pjastam/test-github-actions/actions/runs/5228802815) of the workflow run. I would expect that this positive result would happen too after some minor text change. (PM: Note that the workflow log also shows a Node.js warning about 12 actions being deprecated)

### Actual behavior

[The log](https://github.com/pjastam/test-github-actions/actions/runs/5228802815) reports a successful execution of the workflow at first.

After adding some text to the `index.qmd` file, the GitHub workflow fails, see [this log](https://github.com/pjastam/test-github-actions/actions/runs/5228919262) of the workflow run. This log reports an `Error in loadNamespace(x) : there is no package called ‘rmarkdown’` and `knitr: (None)` and `rmarkdown: (None)` in the context of the R installation. (PM: Note that here too the workflow log issues a Node.js warning about 12 actions being deprecated)

After switching to the Windows runner we get [a log](https://github.com/pjastam/test-github-actions/actions/runs/5229125810/jobs/9441928612) that reports a successful workflow. (PM: Note that the Node.js warning disappeared also in this case).

### Your environment

R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

### Quarto check output

```bash
quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.361
      Path: C:\Users\USERNAME\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.9.16 (Conda)
      Path: C:/Users/USERNAME/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[>] Checking R installation...........OK
      Version: 4.3.0
      Path: C:/PROGRA~1/R/R-4.3.0
      LibPaths:
        - C:/Program Files/R/R-4.3.0/library
      knitr: 1.43
      rmarkdown: 2.22

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Your post relies on computing with freeze.
Since you make some changes, the document needs to be rendered again, but you did not setup your dependencies suck as `knitr`/`rmarkdown`.
Nothing in https://github.com/pjastam/test-github-actions/tree/main contains your R dependencies.

GitHub Actions logs are pretty clear on why the action is failing and how to resolve the issue (https://github.com/pjastam/test-github-actions/actions/runs/5228919262/jobs/9441578352)
<img width="1103" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/f499c6dd-3233-4b1f-b2aa-679d646a366f">

Quarto actions do not handle your dependencies, so you need to add a step in your workflow.
For `renv`, see <https://rstudio.github.io/renv/articles/ci.html#github-actions>.
See <https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies> for R dependencies.

Alternatively, you can have a pre-render script that contains `renv::restore()` (but no caching), see <https://quarto.org/docs/projects/scripts.html#pre-and-post-render>.

Regarding the Node.js 12 warnins, it's because you are using an outdated version of `actions/checkout@v2`, the latest is `actions/checkout@v3`.

Below of an example (updated from the links above).
Note that you need to setup renv for this to work.

```yaml
on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

      - name: Install and activate renv
        run: |
          install.packages("renv")
          renv::activate()
          renv::restore()
        shell: Rscript {0}

      - name: Get R and OS version
        id: get-version
        run: |
            echo "os-version=$(sessionInfo()$running)" >> $GITHUB_ENV
            echo "r-version=$(R.Version()$version.string)" >> $GITHUB_ENV
        shell: Rscript {0}

      - name: Restore Renv package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
```
