### ISSUE TITLE
Render revealjs with configured slide numbers

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#59]
According to the revealjs docs on slide numbering (https://revealjs.com/slide-numbers/), I should be able to use the `slideNumbers` variable with any of these values:

Value | Description
-- | --
h.v | Horizontal . Vertical slide number (default)
h/v | Horizontal / Vertical slide number
c | Flattened slide number, including both horizontal and vertical slides
c/t | Flattened slide number / total slides

I can set it to `true` / `false` without problems, but using any string like these results in invisible render behavior? See video:

https://user-images.githubusercontent.com/12160301/126241726-d6f070e3-aab1-4ee1-a8f6-6010d597fb49.mov

Here is my YAML:
```
---
title: "A slide deck"
author: "Alison Hill"
format: 
  revealjs:
    slideNumber: 'c/t'
---
```
