### ISSUE TITLE
SASS bug with `inherit` in "sub-properties"?

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#5927]
We have this in _bootstrap-rules.scss

```scss
.table > thead {
  border-top-width: 1px;
  border-top-color: $table-border-color;
  border-bottom: 1px solid $table-group-separator-color;
}
```

But because (I think?) the declaration for `$table-group-separator-color` has `!default` in it in `_variables.scss`:

```scss
$table-group-separator-color: currentColor !default;
```

... this causes our resulting CSS to be invalid:

<img width="495" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/a3a477b0-d6d5-4f08-8de8-e94256c52560">
