### ISSUE TITLE
repo actions (`edit`, `source`, `issue`) don't obey `link-external-newwindow: true`

### ISSUE THREAD

**Issue by declann** [quarto-dev/quarto-cli#5964]
### Bug description

Hi,

I really like the repo actions!

I have a draft website here where I use them:

https://models-on-a-plane.pages.dev/

In the footer there is a link to calculang on GitHub, which opens in a new window, due to `link-external-newwindow: true`.

The Edit this page, View Source and Report an issue links alongside them ("Repo actions links") don't follow the same behaviour.

### Steps to reproduce

https://gitlab.com/declann/models-on-a-plane

`_quarto.yml` has:

```
  repo-url: https://gitlab.com/declann/models-on-a-plane
  issue-url: https://gitlab.com/declann/models-on-a-plane/-/issues
  repo-actions:
    - edit
    - source
    - issue
```

and also `link-external-newwindow: true`

### Expected behavior

Repo actions links should obey `link-external-newwindow` i.e. open in a new window whenever set to true

### Actual behavior

Repo actions links take the user away from website

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.151
      Path: /opt/quarto/bin
```
