### ISSUE TITLE
"image-placeholder" listing option disables use of image in blog post body

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#6029]
### Bug description

If I create a sample blog using command:

`$ quarto create-project myblog --type website:blog`

then the text in myblog/posts/welcome/index.qmd looks like:

```
---
title: "Welcome To My Blog"
author: "Tristan O'Malley"
date: "2023-06-23"
categories: [news]
---

This is the first post in a Quarto blog. Welcome!

![](thumbnail.jpg)

Since this post doesn't specify an explicit `image`, the first image in the post will be used in the listing page of posts.
```
As the text in this file describes, thumbnail.jpg is used in the blog listing created in myblog/index.qmd.

But if I add an `image-placeholder` option to the listing entry, then thumbnail.jpg is no longer used in the blog listing.  It's ignored, and the image specified in the `image-placeholder` option is used in the listing.

I think using the `image-placeholder` option should not disable the feature that looks for an image in the blog post body if an image is not specified in the file metadata.  The image placeholder image should be a true last resort.

### Steps to reproduce

Create a blog project:

`$ quarto create-project myblog --type website:blog`

Edit myblog/index.qmd so it looks thus:

```
---
title: "myblog"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  image-placeholder: profile.jpg
page-layout: full
title-block-banner: true
---
```
and re-render.

### Expected behavior

Quarto should find that thumbnail.jpg is used in the body of the blog post at myblog/posts/welcome/index.qmd and use it in this file's entry in the blog listing.

### Actual behavior

Quarto ignores thumbnail.jpg and uses profile.jpg in the listing for the "Welcome To My Blog" entry.

### Your environment

Command line.

Linux Kubuntu 20.04
