### ISSUE TITLE
Render Quarto to Markdown remove author information from YAML header

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#6067]
### Bug description

If creator provides a valid [author metadata following Author Schema](https://quarto.org/docs/journals/authors.html#author-schema) and convert the `.qmd` file to Markdown, some information in the author metadata is discarted.

### Steps to reproduce

Consider the `index.qmd` file:

```
---
title: "MWE"
author:
  - name:
      given: Jane
      family: Doe
    email: jane@mail.com
    orcid: 0000
    attributes:
      corresponding: true
  - name:
      given: Jonh
      family: Doe
    orcid: 0000
---

Lorem ipsum
```

and run `quarto render index.qmd --to markdown --output rendered_index.md`.

### Expected behavior

Output is identical to the input:

```
---
title: "MWE"
author:
  - name:
      given: Jane
      family: Doe
    email: jane@mail.com
    orcid: 0000
    attributes:
      corresponding: true
  - name:
      given: Jonh
      family: Doe
    orcid: 0000
---

Lorem ipsum
```

This is what happen when using [Hugo format](https://quarto.org/docs/output-formats/hugo.html). `quarto render index.qmd --to hugo-md --output rendered_index.hugo && diff index.qmd rendered_index.hugo` produces

```
17c17
< Lorem ipsum
\ No newline at end of file
---
> Lorem ipsum
```

### Actual behavior

Information in the YAML header is lost:

```
---
author:
- family: Doe
  given: Jane
- family: Doe
  given: Jonh
title: MWE
toc-title: Table of contents
---

Lorem ipsum
```

### Your environment

- OS: Linux 6.2.12-1-MANJARO

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.176
      Path: /opt/quarto-1.4.176/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cderv** [comment]
@dragonstyle I believe it requires to ask explicitly for keeping YAML  

````markdown
---
title: "MWE"
author:
  - name:
      given: Jane
      family: Doe
    email: jane@mail.com
    orcid: 0000
    attributes:
      corresponding: true
  - name:
      given: Jonh
      family: Doe
    orcid: 0000
format: markdown+yaml_metadata_block
---

Lorem ipsum

````

It works when we add the format extensions as above. 


Note that this is a topic that had some changes over time. 

See https://github.com/quarto-dev/quarto-cli/issues/4210#issuecomment-1452185273 discussing the `keep-yaml` removal (to use the extension with `+` only. 
https://github.com/quarto-dev/quarto-cli/blob/a7f26f09f2882f266087cd60762e7ab96e3be810/src/command/render/output.ts#L128-L138

But then there is an internal option reintroduced to fix a bug : See https://github.com/quarto-dev/quarto-cli/pull/5087

So if you want to tackle the topic, this context should be taken into account IMO. Otherwise, we still go on and on with this topics and our various formats

**Comment by rgaiacs** [comment]
@cderv Thanks for the reply. Append the `markdown` format with `+yaml_metadata_block` will preserve the YAML header intact. A side effect is that no key-value pair can be added to the YAML header using `--metadata`. A minimal working example:

Input file (`index.qmd`):

```
---
title: "MWE"
author:
  - name:
      given: Jane
      family: Doe
    email: jane@mail.com
    orcid: 0000
    attributes:
      corresponding: true
  - name:
      given: Jonh
      family: Doe
    orcid: 0000
---

Lorem ipsum
```

Output of `quarto render mwe.qmd --to markdown --metadata="foo:bar"` (key-value pair added to YAML header as expected):

```
---
author:
- family: Doe
  given: Jane
- family: Doe
  given: Jonh
foo: bar
title: MWE
toc-title: Table of contents
---

Lorem ipsum
```

Output of `quarto render mwe.qmd --to markdown+yaml_metadata_block --metadata="foo:bar"` (YAML header intact):

```
---
title: "MWE"
author:
  - name:
      given: Jane
      family: Doe
    email: jane@mail.com
    orcid: 0000
    attributes:
      corresponding: true
  - name:
      given: Jonh
      family: Doe
    orcid: 0000
---



Lorem ipsum
```
