### ISSUE TITLE
Complete Author Schema is not render properly to commonmark

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#6068]
### Bug description

Author is render as `true`.

### Steps to reproduce

Consider `index.qmd` as

```
---
title: "MWE"
author:
  - name:
      given: Jane
      family: Doe
    email: jane@mail.com
    orcid: 0000
    attributes:
      corresponding: true
  - name:
      given: Jonh
      family: Doe
    orcid: 0000
---

Lorem ipsum
```

and run `quarto render index.qmd --to commonmark --output rendered_index.commonmark`.

### Expected behavior

Author is render using `author[].name.literal` from [Author Schema](https://quarto.org/docs/journals/authors.html#author-schema) like

```
# MWE

Jane Doe, John Doe

Lorem ipsum
```

### Actual behavior

Each author is render as `true`:

```
# MWE
truetrue

Lorem ipsum
```

### Your environment

- OS: Linux 6.2.12-1-MANJARO

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.176
      Path: /opt/quarto-1.4.176/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
