### ISSUE TITLE
`date`  keywords and formatting does not work in PDF

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#615]
```yaml
---
date: today
date-format: long #"MMMM DD, YYYY" # "`r format(Sys.Date(), '%B %d, %Y')`"
---
```
Does not seem to work for `format: pdf`.  How does dynamic date work in pdf output? 

> quarto version: quarto-0.9.228-macos.pkg (Pkg)

_Originally posted by @Eyayaw in https://github.com/quarto-dev/quarto-cli/discussions/452#discussioncomment-2550831_
