### ISSUE TITLE
"number-sections: false" ignored for "part" in mobile view

### ISSUE THREAD

**Issue by JonSilas** [quarto-dev/quarto-cli#6366]
### Bug description

If I create a book project and specify "number-sections: false" in _quarto.yml, I then include chapters within a part, after I view the rendered project in a browser in mobile view mode, the visible label of the collapsed sidebar will still show a section number for the chapters within a part.

### Steps to reproduce

Create a new book project:
```
$ quarto create-project mybook --type book
$ quarto preview mybook
```
Add "number-sections: false" to _quarto.yml, include some chapters within a 'part' as below:
```
project:
  type: book

book:
  title: "mybook"
  author: "Norah Jones"
  date: "4/25/2023"
  chapters:
    - part: index.qmd
      chapters: 
        - intro.qmd
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt
```
remove `{.unnumbered}` class from chapters under "part:", for example in "intro.qmd": 
```
# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

``` 
After the site is re-rendered, navigate to intro.html and switch to mobile view (e.g. ctrl-shift-m in Firefox).

The label next to the collapsed sidebar icon at the top of the screen reads "1 Introduction".

### Your environment

IDE: RStudio 2022.07.0
OS: Win 11

### Quarto check output

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.433
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/Jon/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.43
      rmarkdown: 2.22

[>] Checking Knitr engine render......OK
