### ISSUE TITLE
quarto code block syntax in python strings result in python syntax errors

### ISSUE THREAD

**Issue by machow** [quarto-dev/quarto-cli#6367]
When you have anything that looks like a code block in a python string, quarto erroneously truncates the python code during execution. This often results in a syntax error.

Seems like it may be loosely related to https://github.com/quarto-dev/quarto-cli/issues/5603 ? In this case, it's not necessarily executing, but acting on something (a codeblock inside a string) that it shouldn't be.

(This occurs when running both quarto v1.3.433 and 1.4.268)

## Simple example: markdown code block

**example.qmd**

``````
---
format: gfm
keep-md: true
jupyter:
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# example

```{python}
doc = """
    ```python
    ```
"""
```
``````

**error:**

``````python
Starting python3 kernel...Done

Executing 'example.ipynb'
  Cell 1/1: ''...ERROR:

An error occurred while executing the following cell:
------------------
doc = """
```python
------------------

  Cell In[1], line 2
    ```python

^
SyntaxError: EOF while scanning triple-quoted string literal

SyntaxError: EOF while scanning triple-quoted string literal (2149654370.py, line 2)
``````

It looks like quarto is improperly truncating the code at the begining of the md python block.

## Another example: python representation of a quarto code block

**example.qmd**

``````
---
format: gfm
keep-md: true
jupyter:
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# example

```{python}
# using the f-string means the python string uses 2 curly braces in its syntax,
# but the string itself is just single curly braces
# otherwise, quarto tries to execute the code (a separate issue)
# but quarto sees and interprets the double curly braces as a non-executable code block
doc = f"""
    ```{{python}}
    ```
"""
```
``````

**error:**

``````python
Executing 'example.ipynb'
  Cell 1/1: ''...ERROR:

An error occurred while executing the following cell:
------------------
# using the f-string means the python string uses 2 curly braces in its syntax,
# but the string itself is just single curly braces
# otherwise, quarto tries to execute the code (a separate issue)
# but quarto sees and interprets the double curly braces as a non-executable code block
doc = f"""
```{{python}}
------------------

  Cell In[3], line 6
    ```{{python}}

^
SyntaxError: EOF while scanning triple-quoted string literal

SyntaxError: EOF while scanning triple-quoted string literal (1950537022.py, line 6)
``````
