### ISSUE TITLE
Add Execution Options to  Project Options

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#637]
I'm using quarto to write an academic article and the default is have

```
execute:
  echo: false
  output: false
```

in my executable cell.

I can add this defaults to my document/file YAML header, for example

```
---
title: "My Document"
execute:
  echo: false
jupyter: python3
---
```

but I want to add the defaults to my project, i.e. to have `_quarto.yml` like

```
project:
  type: website
  output-dir: _site
  execute:
    echo: false
    output: false
```

**Comment by cderv** [comment]
Did you try 
````yaml
project:
  type: website
  output-dir: _site

execute:
  echo: false
  output: false
````

Every metadata should be configurable in `_quarto.yml` and will be merged with the document header. The format is the same as in the YAML header.
