### ISSUE TITLE
Preview with project outputed pdf doesn' t referesh in the browser on file change

### ISSUE THREAD

**Issue by danieltomasz** [quarto-dev/quarto-cli#6412]
### Bug description

I modified simple book template

```yml
project:
  type: book
  output-dir: _output
  preview:
    port: 4202
    browser: true
    navigate: true

book:
  title: "test"
  author: "Norah Jones"
  date: "8/2/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
```

When I try to have a updated preview in the browser with 
```
quarto preview
``` 
launched in the terminal, when I edit included file the pdf in the browser isn't updated, but the rendered pdf is updated
(and the output in the terminal seems to hang after the second xelatex run) 

### Expected behavior

The pdf will be updated in the browser

### Your environment

I am on macos 13.4.1 and quarto 1.4.287
