### ISSUE TITLE
Does not render the leaflet map in a .ipynb format 

### ISSUE THREAD

**Issue by ambarja** [quarto-dev/quarto-cli#643]
Hello everyone :nerd_face: , recently I am using **quarto** in my workflow, however I find a bug with use some libraries for processing spatial data, specially with leafmap or ipyleaflet (leaflet backend) , this happen when I use the .ipynb format, because when I use the qmd format in VisualCode , the output is excellent.
Regards.
Here put my template :point_down: 

```
---
title: "NO2 emission monitoring in Lima Metropolitana - Peru"
subtitle: "Report generated with Quarto - Jupyter-Lab"
author: "Antony Barja"
date: today
format: 
  html:
    code-fold: true
    self-contained: true
    code-tools: true
    css: style.css
    
jupyter: python3
theme:
   dark: darkly
   light: flatly
toc: true
toc-depth: 2
toc-location: left
---
```
```{python}
import geopandas as gp 
import leafmap
m = leafmap.Map(center=(40, -100), zoom=4)
m
```
![ksnip_20220414-224748](https://user-images.githubusercontent.com/23284899/163515177-43ca847e-279e-4a01-9ab3-25d70bb1796c.png)
