### ISSUE TITLE
"image-placeholder" setting ignored when more than one listing on a page

### ISSUE THREAD

**Issue by blacksqr** [quarto-dev/quarto-cli#6447]
### Bug description

If more than one listing is created for a page, and if the "image-placeholder" option is used for a listing, the image specified in the option is not used if a listing item does not have an image associated with it.  The listing item is simply shown with a blank field where the image should be.

### Steps to reproduce

Create a new blog project:

```
$ quarto create-project myblog --type website:blog
$ quarto preview myblog
```
Edit myblog/posts/welcome/index.qmd so that the image entry is commented out:

```
---
title: "Welcome To My Blog"
author: "Tristan O'Malley"
date: "2023-08-03"
categories: [news]
---

This is the first post in a Quarto blog. Welcome!

<!-- ![](thumbnail.jpg) -->

Since this post doesn't specify an explicit `image`, the first image in the post will be used in the listing page of posts.
```

Edit myblog/index.qmd so that it contains two identical listings with an image placeholder specified:

```
---
title: "myblog"
listing:
  - id: list1
    contents: posts
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: false
    image-placeholder: profile.jpg
  - id: list2
    contents: posts
    sort: "date desc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: false
    image-placeholder: profile.jpg
page-layout: full
title-block-banner: true
---

:::{#list1}
:::

:::{#list2}
:::
```

### Expected behavior

Since the "Welcome to my Blog" list entry doesn't have an image associated with it, the image placeholder profile.jpg should be used in the blog listings in the rendered index.html

### Actual behavior

The "Welcome to my Blog" list entry in each listing has no image associated with it.

### Your environment

Command line.

Linux Kubuntu 20.04

Quarto version: 1.4.217
