### ISSUE TITLE
`reveal-js-url` doesn't appear to be working

### ISSUE THREAD

**Issue by jdfoote** [quarto-dev/quarto-cli#6593]
### Bug description

I rendered a RevealJS presentation, and then took the revealjs folder, and moved it into a `libs` folder. The goal is to have a bunch of lectures that all use the same CSS, RevealJS, etc.

The option given in the documentation (https://quarto.org/docs/reference/formats/presentations/revealjs.html#slide-tools) appears to fail silently. Removing the first hyphen gives a stacktrace.

### Steps to reproduce

1. Save this as a .qmd file and render it.

````
---
title: Lecture title here
format: 
  revealjs:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    css: ./libs/custom.css
    reveal-js-url: /home/jeremy/Teaching/intro_to_programming_and_ds/lectures/libs/reveal.js-4.1.2/
---

# Test

## Not working

````
2. Save the revealjs folder to a new location, and change `reveal-js-url` to point to that location
3. Remove the original revealjs folder and render again.

### Expected behavior

Rendering should use the revealjs code pointed to by the option.

### Actual behavior

The revealjs files are recreated in the `QMD_TITLE_files` directory.

A quick look at the code shows the variable `revealjs-url` referenced, so I tried changing the YAML option from `reveal-js-url` to `revealjs-url` and that also failed, but differently. Now, I get the following trace:

```
ERROR: NotFound: No such file or directory (os error 2)

NotFound: No such file or directory (os error 2)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:42:16)
    at readTemplate (file:///home/jeremy/mambaforge/bin/quarto.js:126684:21)
    at revealFrameworkLayer (file:///home/jeremy/mambaforge/bin/quarto.js:126690:17)
    at revealTheme (file:///home/jeremy/mambaforge/bin/quarto.js:126666:20)
    at Object.formatExtras (file:///home/jeremy/mambaforge/bin/quarto.js:126769:33)
    at runPandoc (file:///home/jeremy/mambaforge/bin/quarto.js:79982:81)
    at async renderPandoc (file:///home/jeremy/mambaforge/bin/quarto.js:81044:26)
    at async Object.onRender (file:///home/jeremy/mambaforge/bin/quarto.js:86673:36)
    at async renderFiles (file:///home/jeremy/mambaforge/bin/quarto.js:86636:25)
    at async render (file:///home/jeremy/mambaforge/bin/quarto.js:90681:21)
```
