### ISSUE TITLE
Repeated `href` in sidebar navigation result in repeated `text`

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#6704]
### Bug description

If the `href` is the same (either to a .qmd or to an external site) and `sidebar` navigation is used, the `text` of the second link is shown. This issue doesn't show up if `navbar` navigation is used.

Sidebar: The text "Link to Post 2" and "External link 2" is repeated.

<img width="1624" alt="Screenshot 2023-09-04 at 9 30 58 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/3a03b9e8-fef8-4e8c-8ef9-ba12ea9ea3b5">

Navbar: No repeated text.

<img width="1624" alt="Screenshot 2023-09-04 at 9 30 43 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/479da878-06b7-4af8-84f3-8688136d8ce9">

### Steps to reproduce

- `quarto.yml` for sidebar navigation:

```yaml
project:
  type: website

website:
  title: "test-website"
  sidebar:
    contents:
      - href: index.qmd
      - href: posts/post1.qmd
        text: Link to Post 1
      - href: posts/post1.qmd
        text: Link to Post 2
      - href: https://google.com
        text: External link 1
      - href: https://google.com
        text: External link 2

format:
  html:
    theme: cosmo
```

- `quarto.yml` for navbar navigation:

``yaml
project:
  type: website

website:
  title: "test-website"
  navbar:
    left:
      - href: index.qmd
      - href: posts/post1.qmd
        text: Link to Post 1
      - href: posts/post1.qmd
        text: Link to Post 2
      - href: https://google.com
        text: External link 1
      - href: https://google.com
        text: External link 2

format:
  html:
    theme: cosmo
```

### Expected behavior

I expected "Link to Post 1" and "External link 1" to show up in the navigation on the sidebar.

### Actual behavior

Repeated text

### Your environment

- IDE: RStudio 2023.09.0 Build 380
- OS: Mac 13.5


### Quarto check output

```bash
Mines-MacBook-Pro:test-website mine$ quarto check
Quarto 1.4.346
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.346
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mine/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mine/Desktop/teaching/Duke/sta113-f23/sta113-f23.github.io/renv/library/R-4.3/aarch64-apple-darwin20
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```
