### ISSUE TITLE
Make Bootswatch paired light and dark themes available

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#6741]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/6740

<div type='discussions-op-text'>

<sup>Originally posted by **allefeld** September  6, 2023</sup>
### Description

For many of the Bootswatch themes there seem to be paired light and dark versions. For example, on the Cosmo theme page <https://bootswatch.com/cosmo/> there is a switch in the upper right corner which toggles between the standard light version and a version which retains fonts, formatting, and many colors, but has light-on-dark text.

I tried to implement that for my own website using

````yaml
    theme:
      light: cosmo
      dark: cosmo
````

and

````yaml
    theme:
      light: cosmo
      dark: cosmo-dark
````

or

````yaml
    theme:
      light: cosmo
      dark: cosmo_dark
````

but none of these work.

I downloaded the source code from the light and the dark version of the Cosmo theme page and compared the files, and the only difference seems to be that the `html` element has an additional attribute  `data-bs-theme="dark"`. Manipulating that manually via the inspector works on the Bootswatch theme page, but it does not work on Quarto-generated pages.

It would be nice if there was a way to take advantage of these paired themes in Quarto, instead of pairing two different light and dark themes.</div>

**Comment by cderv** [comment]
Just adding reference to this new feature in Bootstrap 5.3.0: 
* https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/#dark-mode
* https://blog.bootswatch.com/post/718934092278890496/dark-mode-appears-with-530

**Comment by th0ger** [comment]
Just looking for this. The only traditional bootswatch themes that can be used in paired light/dark mode without changing fonts etc. is [flatly](https://bootswatch.com/flatly/)/[darkly](https://bootswatch.com/darkly/):

```yaml
format:
  html:
    theme:
      light: flatly
      dark: darkly
```
The [customizing themes](https://quarto.org/docs/output-formats/html-themes.html#customizing-themes) approach is not feasible in practice.

**Comment by TonyFly3000** [comment]
in _quarto.yml
----------------------
format:
  html:
    theme:
      light: flatly
      dark: darkly
----------------------

it seems like the light/dark mode toggle only Appear in the main page. not in each post.

**Comment by kadykov** [comment]
> Just looking for this. The only traditional bootswatch themes that can be used in paired light/dark mode without changing fonts etc. is [flatly](https://bootswatch.com/flatly/)/[darkly](https://bootswatch.com/darkly/).

There is one more option:
```yaml
format:
  html:
    theme:
      light: cosmo
      dark: solar
```
