### ISSUE TITLE
listings with punctuation in titles render poorly

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#6745]
### Bug description

Given a Quarto project using a listing YAML file that contains punctuation characters, the project does not render correctly unless those characters are escaped in the YAML.

### Steps to reproduce

The `_quarto.yml`:

```
project:
  type: website
```

The `index.qmd`:

```markdown
---
title: Escaped titles
listing:
  contents: entries.yaml
  type: grid
  fields:
    - title
---
```

The `entries.yaml`:

```yaml
- author: "Quarto Bert"
  title: "@!#?@!$!"
  description: "When Q. Bert dies, words flow."
  date: "2023-01-01"
- author: "Quarto Bert"
  title: "@!#?@!$!"
  description: "When Q. Bert dies, words flow."
  date: "2023-01-01"
```

### Expected behavior

Rendering should show the punctuation in the titles:

<img width="580" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/c4645f01-51b1-4dcb-90d0-1d9f6dd286f0">

### Actual behavior

Rendering shows all sorts of markup:

<img width="864" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/44c26bb8-08f7-41e1-8e68-3d9d5881f220">

### Your environment

Quarto 1.3.433
macOS Ventura 13.5.1 (22G90)

### Quarto check output

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```
