### ISSUE TITLE
html output self contained, css links in toc and anchors not working

### ISSUE THREAD

**Issue by jacekkotowski** [quarto-dev/quarto-cli#682]
```
---
title: "Extract data from many tables"
subtitle: "Test data"
author: "Jacek Kotowski"
date: "`r Sys.Date()`"
format: 
  html: 
    theme: simplex
    self-contained: true
    toc: true
    toc-location: right
    toc-title: Contents
    number-sections: true
    code-fold: show
    code-summary: "Show the code"
    code-tools: true
    default-image-extension: svg
    fig-format: svg
---

```
Such yaml will generate a file but anchors at the title are not visible and toc links do not get highlighted when clicked.

**Comment by jchiquet** [comment]
Hi,

Same problem seen here (on a more /too? complete example)

https://computo.sfds.asso.fr/template-computo-quarto/

The YAML metadata in the main document is as follows:

```
---
title: "Template for contribution to Computo"
subtitle: "Example based on the quarto system"
author:
  - name: "The Computo team"
    url: https://computorg.github.io/
    affiliation: Société Française de Statistique
    affiliation-url: https://www.sfds.asso.fr/
date: last-modified
abstract: >+
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur posuere vestibulum facilisis. Aenean pretium orci augue, quis lobortis libero accumsan eu. Nam mollis lorem sit amet pellentesque ullamcorper. Curabitur lobortis libero eget malesuada vestibulum. Nam nec nibh massa. Pellentesque porttitor cursus tellus. Mauris urna erat, rhoncus sed faucibus sit amet, venenatis eu ipsum.
citation:
  type: article-journal
  container-title: "Computo"
  doi: "xxxx"
  url: https://computo.sfds.asso.fr/template-computo-quarto
github: https://github.com/computorg/template-computo-quarto
bibliography: references.bib
repo: "template-computo-quarto"
---
```

which must be completed by the `_quarto.yml` file found there:

https://github.com/computorg/template-computo-quarto/blob/main/_quarto.yml
