### ISSUE TITLE
"YAMLError: bad indentation" shows no file information

### ISSUE THREAD

**Issue by mpauper** [quarto-dev/quarto-cli#6825]
### Bug description

My project was using only python so far and I was using quarto with no issue rendering my qmd files using jupyter.

Yesterday, I needed to add R to my project to use a tool only available in R. Therefore, using `renv` I created an R environment, and as a result the following files and dirs were created:
```
.Renviron
.Rprofile
renv.lock
renv/
├── .gitignore
├── activate.R
├── settings.json
└── staging/
```

Since those changes, rendering the same qmd files that I used to render before adding the R environment raised the following error:

```
ERROR: YAMLError: bad indentation of a mapping entry at line 10, column 14:
            theme: zephyr
                 ^

YAMLError: bad indentation of a mapping entry at line 10, column 14:
            theme: zephyr
                 ^
    at generateError (file:///opt/quarto/bin/quarto.js:10719:12)
    at throwError (file:///opt/quarto/bin/quarto.js:10722:11)
    at readBlockMapping (file:///opt/quarto/bin/quarto.js:11361:20)
    at composeNode (file:///opt/quarto/bin/quarto.js:11528:84)
    at readBlockMapping (file:///opt/quarto/bin/quarto.js:11346:17)
    at composeNode (file:///opt/quarto/bin/quarto.js:11528:84)
    at readBlockMapping (file:///opt/quarto/bin/quarto.js:11346:17)
    at composeNode (file:///opt/quarto/bin/quarto.js:11528:84)
    at readDocument (file:///opt/quarto/bin/quarto.js:11642:5)
    at loadDocuments (file:///opt/quarto/bin/quarto.js:11679:9)
```

For reference, and example of the YAML header:

```
---
title: "my project"
author: Marc Pauper
toc: true
reference-location: margin
highlight-style: ayu
code-fold: true
format:
    html:
        embed-resources: true
        theme: zephyr
        toc-location: left
        link-external-newwindow: true
        link-external-icon: true
        toc-depth: 5
        footnotes-hover: true
        reference-location: margin
engine: jupyter
project:
    execute-dir: project
execute:
    cache: true
code-annotations: hover
---
```

I always get the same YAMLError at the same line for all the qmd files (they have the same YAML header except for title).

When I checkout my commit before adding any of the R files (and manually removing the `.Renviron` because it is not version-controlled), the error is gone.

I am not sharing anymore of the code in the qmd files, as it really seems it has nothing to do with it.

Quarto version: `1.3.433`
System: Pop-os 22.04 LTS

Please let me know if I can provide more details.

I have noticed issues #5979 and #5476 but one got stale and the other seemed quite obscure and ultimately different than my problem. I did check for `_quarto.yml` files in parent directories, just in case, but didn't find any.

### Quarto check output

This is after creating the R environment (nmd_project)

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /home/mpauper/.cache/pypoetry/virtualenvs/nmd-project-NMwd2pX9-py3.10/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /home/mpauper/.renv/nmd_project/R-4.1/x86_64-pc-linux-gnu
        - /home/mpauper/.cache/R/renv/sandbox/R-4.1/x86_64-pc-linux-gnu/9a444a72
      knitr: 1.40
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
We can't reproduce with only a subset of the files.
Please provide a reproducible and small Git repository we can use.
Than you!

**Comment by mpauper** [comment]
I am adding you as a collaborator in my private repo. In it, I have created a branck `quarto-issue`, please check out that one.

On said branch, commit `62edfe8` represents my repo before the addition of renv project.

Commit `aa2d118` is the creation of the renv project. At this stage things still work:

`poetry run quarto render doc/test.qmd`  -> success

Commit `d01860d` introduces two new `qmd` files in `doc/`. Now the previous command to render `doc/test.qmd` raises the YAML error. In fact, now the error is raised for any .qmd in the directory.

Please let me know if something is missing for you to test this. I think all the files are there for you to recreate the renv and poetry environments. In my case, I have set both of these environments' libraries to be stored outside the working directory of this project in order to limit the number of files and directories. A high number of files and directories was negatively impacting the performance of quarto render (recently had a discussion in the Quarto Discussions about this).

**Comment by cscheid** [comment]
The real problem here is in our error messages. When rendering a website, we sometimes need to render other pages first (for things like sidebar navigation). The YAML error is coming from one of those files. Specifically, your `doc/diann_proteomics_iq.qmd` file has invalid YAML:

````
format:
  html:
    code-fold: true
        theme: zephyr
        toc-location: left
        link-external-newwindow: true
        link-external-icon: true
        toc-depth: 5
        footnotes-hover: true
        reference-location: margin
````

Note the bad indentation of the _previous_ line. (As I said, our error message is very unhelpful here because it doesn't show which file this is about). That's the bug on our side.

On your side, you need to make sure that your YAML is formatted properly.
