### ISSUE TITLE
The location of references list is not assigned by `#refs` block

### ISSUE THREAD

**Issue by XiangyunHuang** [quarto-dev/quarto-cli#6867]
### Bug description

The location of references list is not assigned by `#refs` block

## Step 1: create book project 

```
quarto create-project mybook --type book
```

## Step 2: modify `_quarto.yml` as follow

I add an appendix after  the references.

```
project:
  type: book

book:
  title: "mybook"
  author: "Norah Jones"
  date: "9/17/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
  appendices:
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    keep-tex: true

```

### Expected behavior

The references's location is assigned by `#refs` block.

### Actual behavior

The following block doesn't work when output is pdf.

```
::: {#refs}
:::
```

the location of references list is not assigned by `#refs` block

<img width="672" alt="截屏2023-09-18 09 00 39" src="https://github.com/quarto-dev/quarto-cli/assets/12031874/fa5828ed-e2c4-476d-919f-7d31f779605a">

references append to appendix.

<img width="741" alt="截屏2023-09-18 08 59 18" src="https://github.com/quarto-dev/quarto-cli/assets/12031874/492baac6-8805-43d6-a017-6e9afacca8f2">

### Your environment

- RStudio 2023.06.2+561 "Mountain Hydrangea" Release (de44a3118f7963972e24a78b7a1ad48b4be8a217, 2023-08-25) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.2+561 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
- macOS 13.5.2 (22G91) 

### Quarto check output

```bash
quarto check
```

```

Quarto 1.4.369
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.369
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/xiangyun/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK


```
