### ISSUE TITLE
Undefined control sequence. <argument> \bbl@ensure@chinese 

### ISSUE THREAD

**Issue by XiangyunHuang** [quarto-dev/quarto-cli#6868]
### Bug description

```
quarto render --to pdf
```
```
[1/4] index.qmd
[2/4] intro.qmd
[3/4] references.qmd
[4/4] summary.qmd

pandoc 
  to: latex
  output-file: index.tex
  standalone: true
  toc: true
  number-sections: true
  top-level-division: chapter
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  crossref:
    chapters: true
  documentclass: book
  papersize: letter
  block-headings: true
  lang: zh
  bibliography:
    - references.bib
  title: mybook
  author: Norah Jones
  date: 9/17/2023
  

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
ERROR: 
compilation failed- Error compiling latex
Undefined control sequence.
<argument> \bbl@ensure@chinese 
                               -hans {附录} A\hspace {.3em}
l.6 ...附录} A\hspace {.3em}}Summary}{7}{appendix.A}
                                                  % 

see /Users/xiangyun/Downloads/Document/mybook/index.log for more information.
```

#### Step 1: create book project 

```
quarto create-project mybook --type book
```

#### Step 2: modify `_quarto.yml` as follow

```
project:
  type: book

lang: zh

book:
  title: "mybook"
  author: "Norah Jones"
  date: "9/17/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
  appendices:
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    include-in-header:
      text: |
        \usepackage[heading=true]{ctex}
    keep-tex: true
```

### Expected behavior

It should be work as Quarto 1.3.

### Your environment

- RStudio 2023.06.2+561 "Mountain Hydrangea" Release (de44a3118f7963972e24a78b7a1ad48b4be8a217, 2023-08-25) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.2+561 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
- macOS 13.5.2 (22G91) 

### Quarto check output

```bash
quarto check
```

```

Quarto 1.4.369
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.369
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/xiangyun/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/local/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK


```
