### ISSUE TITLE
improve behavior (or description) of `include-*` metadata

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#688]
The difference between the "inline" and the "file" versions of our include options could be improved, I think.

https://quarto.org/docs/output-formats/html-basics.html#includes

In order to do this with backward compatibility, I think we could create a schema like this:

```
anyOf:
  - string # retain current behavior of current options
  - object:
      properties:
        content: string # force inline behavior on whatever version is chosen
  - object:
      properties:
        file: string # force file inclusion behavior on whatever version is chosen
```

and then interpret it appropriately in the options. This way we can eventually deprecate the string behaviors in favor of the explicit option.
