### ISSUE TITLE
Document method to setup github workflow to publish to confluence

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#6923]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/6915

<div type='discussions-op-text'>

<sup>Originally posted by **kristian-relectrify** September 20, 2023</sup>
### Description

I have tried searching the docs and quarto's github repo but I could not find a guide on how to setup a workflow that publishes to confluence on merge. There are guides on how to setup a github workflow to publish to github pages, netlify, etc. but there isn't one for confluence. </div>

**Comment by cderv** [comment]
I updated the example workflow file [here](https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml) and added a publish to confluence job. The job sets up the environment variables using Github secrets and then runs the `quarto publish confluence`. 

```
    - name: Publish to confluence
      env: 
        CONFLUENCE_USER_EMAIL: ${{ secrets.CONFLUENCE_ACCOUNT_EMAIL }}
        CONFLUENCE_AUTH_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        CONFLUENCE_DOMAIN: ${{ secrets.CONFLUENCE_DOMAIN }}
      if: ${{ github.event.pull_request.merged == true }}
      run: |
        echo "Publishing quarto project to Confluence..."
        quarto publish confluence --no-browser --no-prompt 
```

_Originally posted by @kristian-relectrify in https://github.com/quarto-dev/quarto-cli/discussions/6915#discussioncomment-7058380_
