### ISSUE TITLE
Comment line in _quarto.yml causes error

### ISSUE THREAD

**Issue by wch** [quarto-dev/quarto-cli#693]
My _quarto.yml file has a line that starts with a comment. The relevant part looks like this (https://github.com/rstudio/pyshiny-site/blob/935c2707/_quarto.yml#L5):

```yml
project:
  type: website
  output-dir: docs
  render:
    # List index.qmd first so that / redirects to it instead of components.html.
    - /index.qmd
    - /*.qmd
```

When I run `quarto render`, it used to work with older versions of quarto, but now it errors out as follows:

```
$ quarto render
ERROR: Internal Error, couldn't locate key null

Error: Internal Error, couldn't locate key null
    at locate (file:///Users/winston/nobackup/quarto-cli/src/core/lib/yaml-validation/validator.ts:539:11)
    at file:///Users/winston/nobackup/quarto-cli/src/core/lib/yaml-validation/validator.ts:607:27
    at Array.every (<anonymous>)
    at file:///Users/winston/nobackup/quarto-cli/src/core/lib/yaml-validation/validator.ts:606:10
    at ValidationContext.withSchemaPath (file:///Users/winston/nobackup/quarto-cli/src/core/lib/yaml-validation/validator.ts:90:27)
    at validateObject (file:///Users/winston/nobackup/quarto-cli/src/core/lib/yaml-validation/validator.ts:604:22)
    at Object.object (file:///Users/winston/nobackup/quarto-cli/src/core/lib/yaml-validation/validator.ts:248:9)
    at schemaCall (file:///Users/winston/nobackup/quarto-cli/src/core/lib/yaml-schema/types.ts:285:39)
    at file:///Users/winston/nobackup/quarto-cli/src/core/lib/yaml-validation/validator.ts:230:5
    at ValidationContext.withSchemaPath (file:///Users/winston/nobackup/quarto-cli/src/core/lib/yaml-validation/validator.ts:90:27)
```

If I move the comment so that it's not on its own line, then it works fine:

```yml
project:
  type: website
  output-dir: docs
  render:
    - /index.qmd   # List index.qmd first so that / redirects to it instead of components.html.
    - /*.qmd
```

I bisected it to f0d1464d46bff83ebbcd5c4b2f15d58e749cbb08.
