### ISSUE TITLE
Inline image breaking line in PDF with Typst

### ISSUE THREAD

**Issue by ptram** [quarto-dev/quarto-cli#6977]
### Bug description

Hi,

I'm trying to render to PDF via Typst. Images inserted in a line of text break the line before and after the image. This code:

`the [page menu ![](images/page-menu-icon.png){width=3mm}]{custom-style="Parameter"}.`

gives this result in the PDF:

<img width="188" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/19186065/6f3d9776-3cdd-43fb-ba7b-b4399207a586">

This happens whether the text contains a character/inline style or not.

Please note that the same code renders well to WebHelp.

### Steps to reproduce

Code as in the previous section.

### Expected behavior

Images to sit in the same line, together with text.

### Actual behavior

Line broken before and after the image.

### Your environment

Mac Monterey 12.7
Quarto 1.4.376
Pandoc 3.1.8

### Quarto check output

```
quarto check
Quarto 1.4.376
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.376
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4
      Path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in .installbuilder. Did you forget to activate it?

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
Please could you provide a complete reproducible example which include the format? Thank you!
Thanks for the report!

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by ptram** [comment]
Sorry for the bad quotation! Let's see if this one can work.

````
---
title: "test"
format:
  typst:
    toc: true
    columns: 1
    papersize: a5
    fontsize: 9.5pt
---

# Title 1

## Title 2

### Title 3

#### Title 4

##### Title 5

Press the [FILE]{custom-style="Parameter"} button to go to the [File ]{custom-style="Parameter"}page, select the [Internal]{custom-style="Parameter"} group, select the [All]{custom-style="Parameter"} folder, and choose the [Save]{custom-style="Parameter"} command from the [page menu ![](images/page-menu-icon.png){width=3mm}]{custom-style="Parameter"} (on the top right corner). Then save the data as a KST folder in an external storage device.
````
![page-menu-icon](https://github.com/quarto-dev/quarto-cli/assets/19186065/441afc5c-5d2e-4cc0-9e78-5c299eb60441)
