### ISSUE TITLE
:::{#quarto-listing-pipeline .hidden} add in page

### ISSUE THREAD

**Issue by thilop** [quarto-dev/quarto-cli#7021]
### Bug description

Suddenly this appears:

:::{#quarto-listing-pipeline .hidden}

:::{.hidden render-id=“pipeline-listing-listing”}
:::{.list .quarto-listing-default} 

https://kielkontrovers.com/

I just updated an article an it appears on the index page

### Steps to reproduce

1. add an article on a blog

### Expected behavior

all well

### Actual behavior

added some markdown with mixed CSS

### Your environment

- IDE: 2023.06.2 Build 561
- Quarto: 1.3.450

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 4.9.1
      Kernels: python3

(/) Checking Jupyter engine render....[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /home/thilo/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.44
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
Thanks for the report!

Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by thilop** [comment]
```qmd
---
title: "Startseite"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  feed: true
page-layout: full
title-block-banner: true
---
```

**Comment by mcanouil** [comment]
Unfortunately, this is not enough.
We need the code (or any code that help) and the steps to reproduce or else we won't be able to do anything.

**Comment by thilop** [comment]
this is the code.
i can only add the _quarto .yaml

Also the code is not the problem, it worked for months. This error jsut appeared out of nowhere.


```
project:
  type: website
  preview: 
    port: 2000
website:
  title: "KielKontrovers"
  site-url: https://kielkontrovers.com
  description: "Gesellschaftliches Blog aus Kiel"
  navbar:
    right:
      - about.qmd
      - wahlen/index.qmd
      - archiv/index.qmd
      - impressum.qmd
      - icon: mastodon
        href: https://mastodon.social/web/@kielkontrovers
      - icon: rss
        href: index.xml
  search: 
    location: navbar
    type: overlay
format:
  html:
    theme: flatly
    css: styles.css
    mainfont: "sans-serif"
    lang: "de"
    anchor-section: true
    author: Thilo Pfennig
default.metadata:
  date:
    label: "Datum"
    value: "13. März 2023"

```
