### ISSUE TITLE
Lua: finer-grained control of filter orders

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#7066]
We currently only allow "pre" or "post" Lua filters. We now have a better understanding of the structure of our own filter chain in different steps, and we should expose those as entry points for external Lua filters. We also currently use filter names in our chain for debugging. 

We can leverage this naming mechanism. The cleanest API change to do this is to enrich our filter syntax to allow the `entry-point` key for filter names, and then create a set of names that are publicly available (and validated against).

This way, one would be able to write, for example:

```yaml
filters:
  - entry-point: before-quarto
    path: my_filter.lua
  - entry-point: after-render
    path: my_filter_2.lua
```

Going forward, the current "pre" and "post" filters in our current setup would be translated to specific entry points, so all filter injection semantically goes through specific entry points.

We want to do this to add at least one more entry point, that of "after filter processing, but before format-specific rendering". Notably, this would happen after crossref resolution, but before format-specific rendering. The need for that entry point comes up in custom Quarto formats.
