### ISSUE TITLE
Listings don't show default preview image

### ISSUE THREAD

**Issue by richardsprague** [quarto-dev/quarto-cli#7102]
### Bug description

One of the many .md files in my `downloads` directory contains as its first image the following markdown, which displays correctly upon rendering.

```md

![Almond Flour Bread](https://onedrive.live.com/embed?resid=8BC6084B92FFA451%21543979&authkey=%21AC9ByIteI8i__iA&width=660&height=999999?no.jpg)
```

However, that image doesn't show on the listing page set up like this: 

```yml
---
title: All Recipes
listing: 
    categories: true
    contents: "downloads/"
    type: grid
    feed: true
show_toc: TRUE
---
```

instead it generates an empty placeholder card with this html

```html
<div class="listing-item-img-placeholder card-img-top" style="height: 150px;">&nbsp;</div>
```

quarto --version
1.4.395
