### ISSUE TITLE
Add `logo-alt` or similar option for `logo` in navbar YAML (a11y issue)

### ISSUE THREAD

**Issue by batpigandme** [quarto-dev/quarto-cli#711]
Currently, you can specify `logo` in the [Navbar options](https://quarto.org/docs/reference/projects/websites.html#navbar) to get an image for `.navbar-brand`, e.g. for quarto-web, there's (effectively):

```yaml
website:
  navbar:
    logo: quarto.png
```

However, there isn't a way (that I've figured out) to add alt-text for this image. So, perhaps `logo-alt` might be added?

I'm assuming it would be much more complicated to actually have that item be code, à la the page-footer options where you could use the quarto `fig-alt` syntax.
```yaml
  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){width=65px}](https://www.rstudio.com)
```
https://github.com/quarto-dev/quarto-web/blob/a80db52e7b9bb07f441f4d663edc3a3b38322783/_quarto.yml#L25-L28

Link to issue report from testing Quarto site with axe: <https://axe.deque.com/issues/ee26e47c-e699-49b5-8ec3-e70b3a374f9c>
