### ISSUE TITLE
Bootstrap variable for pagination link color getting overwritten

### ISSUE THREAD

**Issue by ravicodelabs** [quarto-dev/quarto-cli#7184]
### Bug description

Bootstrap provides the scss variable `$pagination-active-color` (more info at [bootstrap docs](https://getbootstrap.com/docs/5.0/components/pagination/)) to set the text color on pagination buttons (e.g. the buttons that appear when the `listing:` property is used in the front matter of a qmd file). 

However, when adding to a theme scss file like below, it is not working:

```scss
/*-- scss:defaults --*/

$pagination-active-color: #bf04ed; 
```

I believe it is getting overwritten by the scss here:

[src/resources/projects/website/listing/quarto-listing.scss](https://github.com/quarto-dev/quarto-cli/tree/f81a600445422b0cd419e4d660dcce77bdcdfc6c/src/resources/projects/website/listing/quarto-listing.scss)

In particular, the following scss might have a higher specificity than `.active > .page-link`:

```scss
ul.pagination {
  float: right;
  padding-left: 8px;
  padding-top: 0.5em;
  li {
    padding-right: 0.75em;
  }
  li.disabled,
  li.active {
    a {
      color: $body-color;
      text-decoration: none;
    }
  }
  li:last-of-type {
    padding-right: 0;
  }
}
```

Hence, there doesn't seem to be a way to set the active pagination link text color currently without a special case manual CSS override (which is what we are doing for now). 

### Steps to reproduce

Any Quarto website with a page using pagination should do, just add the following and see that it doesn't change the color of the active pagination link text:

```scss
/*-- scss:defaults --*/

$pagination-active-color: #bf04ed; 
```

### Expected behavior

Active pagination link text color should be set according to the bootstrap variable `$pagination-active-color` via CSS selector `.active > .page-link`. 

### Actual behavior

Active pagination link text color is being set with CSS selector `ul.pagination li.active a`. 

### Your environment

Quarto v1.4.388 (and earlier versions).
