### ISSUE TITLE
`reveljs` output, background images and `navigation-mode: vertical`: Apparent Image Stacking

### ISSUE THREAD

**Issue by r-cheologist** [quarto-dev/quarto-cli#7196]
### Bug description

When using `navigation-mode: vertical` in the context of `format: revealjs`, background images are layered in puzzling ways and require manual intervention to homogenize appearance across all levels of the presentation.

### Steps to reproduce

Consider the following setup:

1. `_quarto.yml`:
    ```yml
    format:
      revealjs:
        theme: [default, custom.scss]
        navigation-mode: vertical
    ```
2. `custom.scss`:
    ```css
    /*-- scss:defaults --*/
    
    /*-- scss:rules --*/
    .reveal .slide-background-content{
      background-image: url("https://flyclipart.com/thumb2/solid-circle-solid-tran-with-png-and-vector-format-634178.png");
      background-size: auto 600px;
      background-position: bottom right;
      opacity: 0.3;
    }
    ```
3. `00_presentation.qmd`:
    ```md
    # Top Level Slide 1
    
    # Top Level Slide 2 (with branch)
    
    [Note the additive transparency of the background image!]{style="color: red"}
    
    ## Branch Level Slide 2.1
    
    Additive transparency persists here...
    
    # Top Level Slide 3 (no branch)
    
    Transparency is back to "normal"...
    
    # Top Level Slide 4 (branching)  {background-opacity=0}
    
    Here we manually fix the apparent layering of background images.
    
    ## Branch Level Slide 4.1  {background-opacity=0}
    
    See: all good now.
    ```
Run `quarto render` and examine the resulting `00_presentation.html` **including the vertical branches** (see navigation arrows on screen).

### Expected behavior

No matter what level or branch of the presentation one is in, the buildup from graphical elements is expected to identical - in the example exemplified by the transparency of the background image (0.3).

### Actual behavior

What is observed is layering of graphical background elements in the **entire** vertical branch (including the parent slide). Manual intervention confusingly requires fixing background transparency in the complete branch, again **including** the parent slide.

### Your environment

`rocker/bioconductor_docker` image with RStudio Server 2023.03.0 Build 386

### Quarto check output

```bash
Quarto 1.4.398
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.398
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.10
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/rstudio/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/local/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/local/lib/R/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```
