### ISSUE TITLE
Julia quarto documents render plots as svg, when both PDF and html formats specified in project file

### ISSUE THREAD

**Issue by jeremiahpslewis** [quarto-dev/quarto-cli#722]
This causes the latex PDF build to fail as it doesn't support SVG.

Project file snippet:
```yaml
format:
  html:
    theme: cosmo
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
```
