### ISSUE TITLE
Sidebar toggle button is not working

### ISSUE THREAD

**Issue by road2you** [quarto-dev/quarto-cli#7333]
### Bug description

In a narrow screen, the sidebar changes to a toggle button, and clicking the toggle button is supposed to expand the sidebar's content. However, clicking the button results in no response.

![image](https://github.com/quarto-dev/quarto-cli/assets/35862752/a19ba817-7ca2-4977-9fcf-1493f2106abc)
![image](https://github.com/quarto-dev/quarto-cli/assets/35862752/2b6abe9f-d91b-4558-975c-6ac2f604b001)

### Steps to reproduce

```yaml
project:
  type: book

book:
  title: "page_nav"
  author: "Norah Jones"
  date: "2023. 10. 22."
  chapters:
    - index.qmd
    - intro.qmd
    - intro2.qmd
    - intro3.qmd
    - summary.qmd
    - references.qmd
    
  sidebar: 
    style: "docked"
    search: true
    backgroud: dark
    title: "sidebar TEST"
  
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

### Expected behavior

In the previous implementation, the sidebar content appeared as an overlay when the toggle button was clicked

### Actual behavior

However, now clicking the toggle button results in no changes.

### Your environment

- IDE: RStudio 2023.09.2+508
- OS: Ubuntu 23.04

### Quarto check output

```bash
Quarto 1.4.444
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.444
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      Chromium: 869685
      TinyTeX: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.13 (Conda)
      Path: /home/snoopy/miniconda3/envs/pytorch/bin/python
      Jupyter: 5.3.0
      Kernels: pytorch, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /opt/R/4.3.1/lib/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /opt/R/4.3.1/lib/R/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by sda030** [comment]
I can confirm the bug exists also in Quarto 1.4.435. 
Even smaller reprex:
````yaml
project:
  type: book

book:
  chapters:
    - index.qmd
    - test.qmd
    - test2.qmd
    
  sidebar: 
    style: floating
  ````
