### ISSUE TITLE
Yaml header option `standalone: false` does not work

### ISSUE THREAD

**Issue by GuillaumeDehaene** [quarto-dev/quarto-cli#7335]
### Bug description

In 1.4.444, for formats `html` and `latex`, the yaml header option `standalone: false` has no effect.
The bug is not present in 'rtf' and 'tei' which also have the `standalone` option.

It should be forwarded to pandoc and produce a document with only the body.
However, the output document is the same for both standalone: true, standalone: false

The issue is probably that the option is simply not forwarded to pandoc.

### Steps to reproduce

Here is a MWE

````markdown
---
title: "Test"
format:
    html:
        standalone: false
    latex:
        standalone: false
    rtf:
        standalone: false
    tei:
        standalone: false
---

Content
````

Run with `quarto render test.qmd`

Quarto render log on my machine:
```
pandoc 
  to: html
  output-file: test.html
  standalone: false
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Test

pandoc 
  to: latex
  output-file: test.tex
  standalone: false
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  title: Test

pandoc 
  to: rtf
  output-file: test.rtf
  standalone: false
  default-image-extension: png

metadata
  title: Test

pandoc 
  to: tei
  output-file: test.tei
  standalone: false
  default-image-extension: png

metadata
  title: Test

Output created: test.html
```

examine output files:
- test.html and test.tex are full documents.

### Expected behavior

When `standalone: false`, test.html and test.tex should include only the body of the document.

### Actual behavior

When `standalone: false`, test.html and test.tex produce a standalone document.

### Your environment

- IDE: VSCode
- OS: Windows 11
- Quarto: 1.4.444

### Quarto check output

Quarto 1.4.444
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.444
      Path: C:\Users\Guillaume\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: Installation From Path
      Path: C:\texlive\2023\bin\windows
      Version: 2023

[>] Checking basic markdown render....OK

ERROR: The file cannot be accessed by the system. (os error 1920): ...

**Comment by olivroy** [comment]
I think that `standalone` is deprecated in favour of `self-contained`

Can you try ?

```
---
title: "Test"
format:
    html:
        self-contained: false
    latex:
        self-contained: false
    rtf:
        self-contained: false
    tei:
        self-contained: false
---

Content
```
