### ISSUE TITLE
Twitter Card Paths Invalid When Site Url Has Trailing Slash

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#737]
```yaml
website:
  site-url: "https://www.quarto.org/"
title: "My Document"
```
Will generate invalid paths in the meta tags, like:

```
<meta name="twitter:image" content="https://www.quarto.org//posts/foo.png">
```
