### ISSUE TITLE
Insert custom css into revealjs presentation

### ISSUE THREAD

**Issue by py9mrg** [quarto-dev/quarto-cli#746]
Hello,

So this is a bit of a weird one and it's possible I've missed something obvious. 

My problem - I don't like the default logo sizes and want to change these.

I've found that the key part of the resulting html file is the following css:

```css
@media screen and (max-width: 800px) {
    .reveal .slide-logo {
    max-height: 1.1rem;
    bottom: -2px;
    right: 10px;
    }
}
```
So this is what I need to change, e.g. to:

```css
@media screen and (max-width: 800px) {
    .reveal .slide-logo {
    max-height: 10.1rem;
    bottom: -2px;
    right: 10px;
    }
}
```

I've tried a number of things:

1. Add the adjusted css to the scss rules section of a `custom.scss` file in the yaml with `theme: custom.scss`. (I don't understand this very well so it's no surprise to me this didn't work).
2. Added some custom css using a `custom.css` file containing the above adjusted css e.g. in the yaml `css: custom.css`. But this doesn't work as it seems to get inserted into the html file *before* the default css and so the default overwrites it back.
3. Added a css code chunk at the start of the presentation. But this then starts the rendering with Jupyter, which I don't have installed.

The only way I can get this to work is if I force knitr compilation using an empty r code chunk first, e.g., the first thing below the yaml is:

    ```{r}
    ```

    ```{css, echo = FALSE}
    @media screen and (max-width: 800px) {
        .reveal .slide-logo {
        max-height: 20.1rem;
        bottom: -2px;
        right: 10px;
        }
    }
    ```

This then works because the css is inserted into the html file *after* the default css and so overwrites that.

But the problem with this is that I would end up with a lot of custom css at the start of every presentation. Is there a way to source this css into the document so that it appears *after* the default css settings? Or just a better way in general?!

**Comment by cderv** [comment]
I am under the impression we have an order of rules that prevent you from tweaking this using `theme:` or `css`

Logo size is defined also in `footer.css` 
https://github.com/quarto-dev/quarto-cli/blob/f7000f0dc50a5b6fe2f90d9a52fec979473904e4/src/resources/formats/revealjs/plugins/support/footer.css#L1-L9

which is loaded as part of a revealjs plugin which leads to load the css after the one you are inserting using `theme` or `css`. 
This is specific for css rules for the footer loaded in `footer.css`

As a workaround I see two solution 

Using `!important` to flag you rule as the one to use no matter one
```scss
/*-- scss:rules --*/

.reveal .slide-logo {
  max-height: 10.1rem !important;
  bottom: -2px;
  right: 10px;
}
````
then use 
````yaml
format: 
  revealjs:
    logo: logo.png
    theme: [default, custom.scss]
````

Otherwise, you need to load your custom CSS this way 
```
format: 
  revealjs:
    logo: logo.png
    header-includes: |
      <link href="style.css" rel="stylesheet">
````
This will be added in header, but after the other CSS. 

Or you could use `!important flag`

@jjallaire do we want to improve this ? Or is this expected for `footer` rule ?
