### ISSUE TITLE
global 'continue and skip on errors' ...     `error: true ` in _quarto.yml not having the observed behavior 

### ISSUE THREAD

**Issue by daaronr** [quarto-dev/quarto-cli#748]
It's very important to my coding to allow the book to build even with bugs ... which I will correct later.

In my template repo [here](https://github.com/daaronr/dr_quarto_template) I have several errors in the `summary.qmd` file. 

But in `_quarto.yml` I specify:

```
book:
  title: "Reinstein's template for Quarto (WIP)"
   execute:
    freeze: auto # re-render only when source changes
    warning: false
    message: false
    error: true
  ```
  
It says in the docs [here](https://quarto.org/docs/computations/execution-options.html) that the  execution option 

`error: true`

Implies:

> Include errors in the output (note that this implies that errors executing code will not halt processing of the document).

What am I doing wrong? Is there a way to tell it 'keep processing over all errors, just report them'? 

Thanks.

**Comment by jjallaire** [comment]
It should be working the way you outlined. What exactly are you seeing when rendering a qmd with errors?

**Comment by daaronr** [comment]
I type

```
system("quarto render")
```

Everything goes OK until

```
label: unnamed-chunk-2
Quitting from lines 40-41 (summary.qmd)
Error in eval(expr, envir, enclos) : object 'xtest' not found
Calls: .main ... withVisible -> eval_with_user_handlers -> eval -> eval
In addition: Warning messages:
1: Removed 37 rows containing non-finite values (stat_smooth).
2: Removed 37 rows containing missing values (geom_point).

Execution halted
```

**Comment by jjallaire** [comment]
I see what's likely to be the problem. The `execute` key goes at the top level (rather than under the `book` key). So something like this should work:

```yaml
project:
  type: book
  output-dir: docs

book:
  title: "Reinstein's template for Quarto (WIP)"
  author: "David Reinstein"
  repo-url: https://github.com/daaronr/dr_quarto_template/
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/summary.qmd
    - references.qmd
  reader-mode: true

 execute:
    freeze: auto # re-render only when source changes
    warning: false
    message: false
    error: true
```
