### ISSUE TITLE
Tweaking the proposed custom crossref YAML 

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#7484]
A couple of questions to consider for the custom cross-reference feature. @cscheid I hope this captures what we discussed.

## What should the names of keys for custom cross-references be?

The main keys to be set are currently called `prefix`, `name` and `ref-type`:
```yaml
crossref:
  custom: 
    - kind: float
      # the prefix for reference in output ("In Figure 1, ..")
      prefix: Diagram 
      # the prefix for captions ("Figure 1: ..")
      name: Diagram
      # the prefix for the reference identifier ("In @fig-1, ...")
      ref-type: dia
```

Some considerations:
* `prefix` and `name` specify things that are seen in the rendered output. It might be nice to use keys that reflect that they share that feature, e.g. a common suffix.
* There are existing options that we might want to maintain consistency with:
    * `fig-title`, `tbl-title`, “title prefix used for captions”. Suggests maybe `name` should be `title`?
    * `fig-prefix`, `tbl-prefix`, “prefix used for inline reference”. Suggests maybe `prefix` should remain `prefix`?
* We don't have a great way to describe what `ref-type` is. We currently talk about these as the type of cross reference, e.g. from Guide > Authoring > Scholarly Writing > Cross References: "Note that cross reference identifiers must start with their type (e.g. fig- or tbl-)." But this conflates the "type" with the abbreviation used for it. (Or not, if we are consistent that type just means the abbreviation...)

## At what level in the YAML should the numbering scheme of custom cross references be set?

To set the numbering scheme of built-in cross reference types you specify them under `crossref`, e.g.:
```yaml
---
crossref:
  fig-labels: alpha a    # (default is arabic)
---
```

Do we want it to work the same way for custom types, e.g.
```yaml
---
crossref:
  dia-labels: alpha a 
---
```
 Or should it be done under the `custom` key:
```yaml
crossref:
  custom: 
    - kind: float
      # the prefix for reference in output ("In Figure 1, ..")
      prefix: Diagram 
      # the prefix for captions ("Figure 1: ..")
      name: Diagram
      # the prefix for the reference identifier ("In @fig-1, ...")
      ref-type: dia
      labels: alpha a   
```

**Comment by cwickham** [comment]
On a related note, it seems like `prefix` and `name` are, more often than not, identical. Might be nice if a user only specifies one to have the other take the same value.

**Comment by cscheid** [comment]
> On a related note, it seems like `prefix` and `name` are, more often than not, identical. Might be nice if a user only specifies one to have the other take the same value.

That's a really good idea, we should definitely do it.

**Comment by cscheid** [comment]
Similarly to `labels`, we should support `cap-location` in the custom crossref definition.

**Comment by cwickham** [comment]
And also `title-delim`?

**Comment by cscheid** [comment]
- `caption-location` is now supported in the custom crossref YAML
- `reference-prefix` is now the new name for `name`
- `caption-prefix` is now the new name for `prefix`

I chose to use longer names here since:

- the user will not type frequently
- the user will read frequently
- will be accessible under auto-completion

This is my proposed schema for crossref keys in v1.4:

```yaml
 kind:
   enum: [float]
   description: The kind of cross reference (currently only "float" is supported).
 reference-prefix:
   string:
     description: The prefix used in rendered references when referencing this type.
 caption-prefix:
   string:
     description: The prefix used in rendered captions when referencing this type.
 space-before-numbering:
   default: true
   boolean:
     description: If false, use no space between crossref prefixes and numbering.
 ref-type:
   string:
     description: The prefix string used in references ("dia-", etc.) when referencing this type.
 latex-env:
   string:
     description: In LaTeX output, the name of the custom environment to be used.
 latex-list-of-file-extension:
   string:
     description: In LaTeX output, the extension of the auxiliary file used by LaTeX to collect names to be used in the custom "list of" command. If omitted, a string with prefix `lo` and suffix with the value of `ref-type` is used.
 latex-list-of-description:
   string:
     description: The description of the crossreferenceable object to be used in the title of the "list of" command. If unspecified, the field `name` is used.
 caption-location:
   enum: [top, bottom, margin]
   default: bottom
   description: The location of the caption relative to the crossreferenceable content.
```
