### ISSUE TITLE
HTML table with custom css styles

### ISSUE THREAD

**Issue by juliantao** [quarto-dev/quarto-cli#7566]
### Bug description

I used the following scss styles to customize tables in the HTML formats and it worked perfectly.  It seems like that it does not work well now.

````scss

/*--scss:rules --*/

/* Tables */

table {
  background: grey;
  border: 0px;
}

table td, table th {
  // color: darkgrey;
  border: 1px;
  // font-size: 11pt;
  // height: 15px;
  padding: 0px 5px 0px 5px;
  cellpadding: 0;
  cellspacing: 0;
  text-shadow: none;
}

.header {
  background: red;
  color: white;
  font-size: 1.3em;
  font-weight: bold;
}

.table-hover tbody tr:hover td, .table-hover tbody tr:hover th {
  background-color: red;
}

````

### Steps to reproduce

To reproduce, follow the steps below:

1. save the above scss as `table.scss` to the root directory
2. use the [latest version](https://github.com/quarto-dev/quarto-cli/commit/f851959ded3b975c4c1585ac28b84c159f049400) of quarto, render the following `qmd` file in the same root directory

````qmd
---
title: "HTML table with custom css style"
date: "2023-11-13"
theme:
  - cosmo
  - "./table.scss"
---

This is a table rendered using the up-to-date commit "f851959ded3b975c4c1585ac28b84c159f049400"

| Col1 | Col2 | Col3 |
|------|------|------|
| row1 | row1 | row1 |
| row2 | row2 | row2 |
| row3 | row3 | row3 |

````

You should get a table shown below, and note that the table was not styled.

![image](https://github.com/quarto-dev/quarto-cli/assets/60116296/63c609a3-3323-4cf4-8941-b3f827459bd2)

3. Now, checkout an [older commit, say one on Sep. 30](https://github.com/quarto-dev/quarto-cli/commit/9bd1efbd02f8930d7076d391fea98fab0240082f), reconfigure quarto, and render the qmd file.

````qmd
---
title: "HTML table with custom css style"
date: "2023-11-13"
theme:
  - cosmo
  - "./table.scss"
---

This is a table rendered using commit "9bd1efbd02f8930d7076d391fea98fab0240082f"

| Col1 | Col2 | Col3 |
|------|------|------|
| row1 | row1 | row1 |
| row2 | row2 | row2 |
| row3 | row3 | row3 |

````
Now, the rendered table is styled.

![image](https://github.com/quarto-dev/quarto-cli/assets/60116296/f5a1de15-eff6-4b3b-a86f-6ed66f9d354a)

### Expected behavior

The table should be styled as customized using css. See the second figure

### Actual behavior

See the first figure 

### Your environment

- OS: Linux Pop!_OS 22.04 LTS x86_64

### Quarto check output

Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/julian/quarto-cli/package/dist/bin

Check file:///home/julian/quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
[✓] Checking tools....................OK
      TinyTeX: v2023.06
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/julian/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: 4.10.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

R scripting front-end version 4.1.2 (2021-11-01)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
