### ISSUE TITLE
[FR] Enable site-wide footer

### ISSUE THREAD

**Issue by apreshill** [quarto-dev/quarto-cli#76]
This is related to a Workbench request, something like this:

https://docs.rstudio.com/

A few other footer examples:
https://rstudio.github.io/distill/website.html#site-footer
https://hugo-apero-docs.netlify.app/
https://www.tidyverse.org/packages/
https://www.tidymodels.org/start/

**Comment by dragonstyle** [comment]
Should be supported now (https://github.com/quarto-dev/quarto-cli/releases/tag/v0.2.82)

```
1) Simple markdown
footer: |
  Type **markdown** here

2) Complex footers
  footer:
    left: |
      Copyright © 2021 RStudio, PBC. All Rights Reserved.
    center:
      Center content or list of items could go here.
    right:
      - icon: house-fill
        href: https://www.rstudio.com
      - icon: question-circle-fill
        href: https://support.rstudio.com/hc/en-us
      - icon: lightbulb-fill
        href: https://solutions.rstudio.com
      - icon: keyboard
        href: https://docs.rstudio.com/keyboard-shortcuts/
      - icon: twitter
        href: https://twitter.com/rstudio
```
