### ISSUE TITLE
Teach engine about new custom crossreff

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7665]
Discussed in https://github.com/quarto-dev/quarto-cli/discussions/7653

This would work: 
````
---
title: "Estimating associations..."
format: html
keep-md: true
crossref:
  custom: 
    - kind: float
      ref-type: supptbl
      latex-env: supptbl
      prefix: Table S
      name: Table S
      space-before-numbering: false
execute:
  echo: false
---

::: {#supptbl-info-chems}

```{r info-chems}
knitr::kable(head(cars))
```

Information about non-persistent EDCs
:::


See @supptbl-info-chems
````

However, OP is trying to use cell options 

````markdown
---
title: "Estimating associations..."
format: html
keep-md: true
crossref:
  custom: 
    - kind: float
      ref-type: supptbl
      latex-env: supptbl
      prefix: Table S
      name: Table S
      space-before-numbering: false
execute:
  echo: false
---

```{r}
#| label: supptbl-info-chems
#| tbl-cap: "Information about non-persistent EDCs"
knitr::kable(head(cars))
```

See @supptbl-info-chems
````

Should it work ? 

Intermediate .md

````markdown
::: {.cell tbl-cap='Information about non-persistent EDCs'}
::: {.cell-output-display}


| speed| dist|
|-----:|----:|
|     4|    2|
|     4|   10|
|     7|    4|
|     7|   22|
|     8|   16|
|     9|   10|


:::
:::


See @supptbl-info-chems
````

Currently label is not identified as `tbl-` or `fig-` so is unknown and not passed through

We could: 

* Teach engine about `crossref` and parse it to know we should pass the labels on the `.cells` as for Table and Figures
* Don't filter labels, and always add a cell engine label as ID to the .cell div - may have some side effect as we don't do that by filtering out other labels.
