### ISSUE TITLE
Extra <p> added in html ouput when creating website

### ISSUE THREAD

**Issue by jpmorr** [quarto-dev/quarto-cli#7732]
### Bug description

I'm using Quarto to generate a website and on one page I've added a `<div>` that contains two buttons I want to centre. I'm using a `flex` as I thought that would be the best option.

```css
.button-box {
    display: flex;
    align-items: center;
    justify-content: center;    
    text-align: center;
    height: 120px;
    width: 600px;
    border-radius: 10px;
    background-color: #a89c9c;
    margin: auto;
}
```

```html
<div class="button-box">
  <a type="button" class="btn btn-primary btn-lg button" href="#" target="_blank">Left Button</a>

  <a class="btn btn-primary btn-lg button" href="#" target="_blank">Right Button</a>
</div>
```

However, using this code results in buttons that are not centered vertically and I was confused as to why.
![image](https://github.com/quarto-dev/quarto-cli/assets/10863809/a123fe50-cd13-4165-8377-28c62c8af5eb)

### Steps to reproduce

````yaml
project:
  type: website

website:
  title: "testing site"
  back-to-top-navigation: true
  navbar:
    background: primary
    left:
      - text: "Home"
      - text: "Page 2"
      - text: "Page 3"

format:
  html:
    theme: zephyr
    toc: true 
    css: style.css
````

````css
.button-box {
    display: flex;
    align-items: center;
    justify-content: center;
    text-align: center;
    height: 120px;
    width: 600px;
    border-radius: 10px;
    background-color: #a89c9c;
    margin: auto;
}

.button {
    margin: 15px;

}
````

````qmd
---
title: "Test Page" 
---

## What is Lorem Ipsum?
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

<div class="button-box">

  <a class="btn btn-primary btn-lg button">Left Button</a>
  <a class="btn btn-primary btn-lg button">Right Button</a>

</div>
````

### Expected behavior

The buttons should be centred using the specified styling and html provided in the .qmd.

### Actual behavior

Looking at the generated HTML, it appears that an extra paragraph has been added around the button links, which has some extra margin at the bottom which messes with the vertical centring.
```html
<div class="button-box">
<p>
    <a class="btn btn-primary btn-lg button">Left Button</a> 
    <a class="btn btn-primary btn-lg button">Right Button</a>
</p>
</div>
```

Is this extra paragraph supposed to get added to the included `html` in the `qmd` file? I think this would be unexpected to have your html changed?

If it's not unexpected, how do I prevent it or at least remove the extra padding associated with the paragraph so that the vertical centring is correct?

### Your environment

I'm using Quarto 1.4.506 on Windows 11 with VS Code.

### Quarto check output

````
Quarto 1.4.506
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.506
      Path: C:\Users\jpmor\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.6 (Conda)
      Path: C:/Users/jpmor/anaconda3/python.exe
      Jupyter: 5.4.0
      Kernels: julia-1.4, julia-1.6, julia-1.7, juliapro_v1.5.4-1-1.5, pycharm-20203b08, python3, iota

[>] Checking Jupyter engine render....OK

(\) Checking R installation...........R scripting front-end version 4.1.3 (2022-03-10)
[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
````
