### ISSUE TITLE
Improve behavior of render list with only negations

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#7793]
The following render list doesn't do what one would expect:

```
project:
  type: website
  render:
    - "!LICENSE.md"
```

That happens because when render lists aren't the default, they need positive examples to exclude. We should improve this so that if every render list spec is a negation, then we subtract those from the default render list instead of providing an empty list.
