### ISSUE TITLE
footer images wrapped as figure

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#7801]
### Bug description

An image in the page-footer is wrapped with figure markup, which changes its position/placement.

### Steps to reproduce

```yaml
project:
  type: website

website:
  title: a website
  page-footer:
    left: |
      this is the left
    center: |
      this is the center
    right: |
      [![](/posit-logo-fullcolor-TM.svg){fig-alt="Posit"}](https://posit.co){.nav-link target="_blank"}

format:
  html:
    theme: cosmo
    css: styles.css
```

```css
/* size footer logo image and avoid padding */
.nav-footer a.nav-link {
    padding-top: 0;
    padding-bottom: 0;
}
.nav-footer img {
    height: 1em;
}
```

```markdown
---
title: ""
---

this is home.
```

I used a Posit logo image in my tests, but any image will do. Any Markdown file in this project will also suffice.

<img width="1255" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/ca7f49a3-51b6-496a-b690-e45de530535b">

### Expected behavior

The footer image should be right-flush

<img width="1255" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/13bfba83-e5a6-4b80-ac2b-ec008c6934b6">

### Actual behavior

The image is wrapped in figure markup and presented in the center of the right footer column.

### Your environment

macOS Sonoma 14.1.1
Quarto 1.4.518
 

### Quarto check output

```
Quarto 1.4.518
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.518
      Path: /Users/aron/Downloads/quarto-1.4.518/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/aron/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.44
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
This is a funny one. The Markdown content you put in that image is what we call a "Linked Figure Div"; a paragraph containing exactly a link to exactly one image (it's a paragraph for funny reasons). The AST looks for the right part of the footer looks like this:

```yaml
t: "Para"
content:
  - t: "Link"
    attr: "('', ['nav-link'], ['target,_blank'])"
    content:
      - t: "Image"
        attr: "('', [], ['fig-alt,Posit'])"
        caption: []
        src: "/logo.jpg"
        title: ""
    target: "https://posit.co"
    title: ""
```

If you put them in the document _body_, you'd expect them to be handled like a Figure. We recently taught Quarto to recognize these constructs more generally, and so we're now finding the "Figure" in the footer.

We have a bit of a conundrum. I don't want to disable this processing because it will also disable other things we want to resolve correctly, like shortcodes. But I agree with you that calling this a Figure is wrong.

I'll get back to you on this one.
