### ISSUE TITLE
R Leaflet legends are centered when labelled as `fig-`s

### ISSUE THREAD

**Issue by jack-davison** [quarto-dev/quarto-cli#7843]
### Bug description

When a leaflet map is included in a Quarto HTML report, any categorical legend ends up centered when the chunk is labelled as a figure. This looks a little strange/ugly, particularly when the labels are either very different lengths or are only subtly different lengths. Oddly, if you just print the leaflet map without labelling it as a figure, everything works okay.

Note that you can manually fix this by adding this to a style tag, but I imagine this isn't the intended fix, and that messing around with quarto's style options may have unintended consequences.

```css
.quarto-figure-center>figure>p, .quarto-figure-center>figure>div {
    text-align: left;
}
```

No idea if this happens with Python/Folium, but I intuitively expect so?

### Steps to reproduce

````qmd
---
title: Dodgy leaflet
format: html
---

```{r}
#| label: makemap
library(leaflet)

map <-
  leaflet() |> 
  addTiles() |> 
  addLegend(
    labels = c("Big long label oh no!", "lil' lab"), 
    colors = c("red", "blue")
  )
```


```{r}
#| label: fig-leaflet
#| fig-cap: "A leaflet figure"
map
```

```{r}
#| label: nolab
map
```
````

![image](https://github.com/quarto-dev/quarto-cli/assets/45171616/51e68ca2-0e44-418b-9436-5aeb9d7c20cd)

### Expected behavior

The leaflet legend should be left aligned (bottom of image).

### Actual behavior

The leaflet legend is centered (top of image).

### Your environment

- RStudio 2023.03.0+386
- Windows 10

### Quarto check output

```bash
$ quarto check
A new release of Deno is available: 1.28.2 → 1.38.5 Run `deno upgrade` to install it.
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.450
      Path: C:\Users\jd38\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.3
      Path: C:/Users/jd38/AppData/Local/Programs/R/R-4.2.3
      LibPaths:
        - C:/Users/jd38/AppData/Local/R/win-library/4.2
        - C:/Users/jd38/AppData/Local/Programs/R/R-4.2.3/library
      knitr: 1.44
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Thanks for the report. This is indeed the CSS we use to style Figure captions and labels, so we can't change it on our side.

Immediately, a better CSS workaround for you is this:

```css
figure.quarto-float div.leaflet-control {
  text-align: left;
}
```

I'm wondering how we can address this. @cderv is there a way to check, at the end of knitr execution, if user code attached a package? The good fix here would be for us to detect that someone used `leaflet`, and then add a css sheet of fixups.

**Comment by cderv** [comment]
@cscheid in fact, another ideas: 

We could also just adapt our CSS rules for Quarto figures to not apply on `div` of class `html-widget`. I believe all HTML widgets output created with R will have a div of this class. 

For example, the rule that causes issue here is 
````css
.quarto-figure-center>figure>p, .quarto-figure-center>figure>div {
    text-align: center;
}
````

And so we could do 
````css
.quarto-figure-center>figure>p, .quarto-figure-center>figure>div:not(.html-widget) {
    text-align: center;
}
````

This should prevent issues with any other HTML widgets. What do you think ?

**Comment by cderv** [comment]
Oh no that wouldn't work just like that... 😓  sorry

**Comment by jack-davison** [comment]
> @cscheid in fact, another ideas:
> 
> We could also just adapt our CSS rules for Quarto figures to not apply on `div` of class `html-widget`. I believe all HTML widgets output created with R will have a div of this class.
> 
> For example, the rule that causes issue here is
> 
> ```css
> .quarto-figure-center>figure>p, .quarto-figure-center>figure>div {
>     text-align: center;
> }
> ```
> 
> And so we could do
> 
> ```css
> .quarto-figure-center>figure>p, .quarto-figure-center>figure>div:not(.html-widget) {
>     text-align: center;
> }
> ```
> 
> This should prevent issues with any other HTML widgets. What do you think ?

I'd support a widget-agnostic approach if possible, I've had similar issues with `{timevis}` (not from Posit, I believe) that were resolved by fudging the CSS at the top of the doc, which I can put in a separate issue. But good to hear that the `{leaflet}` fix isn't too hard!

**Comment by cderv** [comment]
This would be the rule that works 
````css
.quarto-figure-center > figure > p,
.quarto-figure-center > figure > div:not(.html-widget, :nth-child(1):not(.html-widget)) /* for mermaid and dot diagrams */ {
  text-align: center;
}
````

With need the `nth-child(1)` because of the way Quarto wraps those figure into a specific div enclosing the one for the HTML widget . Example 
````
<div aria-describedby="fig-plotly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
````

I'll make a PR with this fix.

**Comment by cscheid** [comment]
> What are the `.quarto-figure-center>figure>p, .quarto-figure-center>figure>div` selectors intending to target?

It's intended to target (for example) the div emitted by mermaidjs. Clearly the selectors are being too broad, but I'm not sure what the clean fix would be.

**Comment by cderv** [comment]
Let's go back to context of this rule addition maybe. It was added in 
* #3433
in order to fix 
* #3294

So if I understand correctly, the aim is to get the SVG mermaid content aligned. 

We could probably use a more targeted rule for this. What about ?
````scss
.quarto-figure-center>figure>div:has(svg.mermaid-js) {
    text-align: center
}
````

**Comment by cscheid** [comment]
> which I've tried without success with quarto 1.3.450 and 1.4.451 (latest dev release).

FYI, [v1.4.525](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.525) -- and I think I just fixed those mermaid issues between 451 and 525.

**Comment by gadenbuie** [comment]
Thanks -- v1.4.525 is the one I downloaded and installed but `qvm` and I have been fighting lately 😞

**Comment by cscheid** [comment]
Ah. The issue is that you have a small bug in your label: you need `fig-mermaid-diagram`. Then:

![Uploading image.png…]()

**Comment by gadenbuie** [comment]
Oh! That makes sense now. Is this the expected appearance with the fig caption left-aligned and the mermaid diagram centered?

**Comment by cderv** [comment]
Sorry wasn't around - Yes that was it - you need to use the `fig-` prefix for it to be a figure and the figure centering to apply.

This is current limitaton because of a figure node requirement. This may evolved in the future 

* https://github.com/quarto-dev/quarto-cli/issues/4376

**Comment by gadenbuie** [comment]
If the last screenshot looks okay, then here's another set of rules that are worth considering:

```css
.quarto-figure > figure > div {
    display: block;
    width: fit-content;
}

.quarto-figure-center > figure > div {
    margin-left: auto;
    margin-right: auto;
}

.quarto-figure-left > figure > div {
    margin-right: auto;
}

.quarto-figure-right > figure > div {
    margin-left: auto;
}
```

This seems pretty reasonable for htmlwidgets in general, but you could also make those rules more specific to mermaid by targeting `.quarto-figure-* > figure svg.mermaid-js`.

**Comment by cderv** [comment]
> Selecting against svg.mermaid-js is probably not a good idea, because mermaid cells can also choose to render themselves to PNG files through mermaid-format.

But in that case, this is nothing mermaid specific right ? It is like other image and this is covered by the first part of the rule targetting `p` element I believe. Isn't it ? 

````css
.quarto-figure-center>figure>p, .quarto-figure-center>figure>div {
    text-align: left;
}
````
