### ISSUE TITLE
Improve context on Reference > Projects > Websites

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#7869]
On [Reference > Projects > Websites](https://quarto.org/docs/reference/projects/websites.html) some sections give context on where to use the option with example YAML, e.g. [Nav Items](https://quarto.org/docs/reference/projects/websites.html#nav-items) has the example:

```yaml
---
website:
  navbar:
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
---
```

Some sections do not, e.g. [Feed](https://quarto.org/docs/reference/projects/websites.html#feed) does not, but should. E.g. something like

```yaml
---
website:
  listing:
    feed:
      items: 10
---
```

On a first glance, these sections need an example for context:

* Project: Serve
* Social: Twitter, Social: Open Graph
* Listings: Feed
* About
