### ISSUE TITLE
jumpy animation on sidebar expansion

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#7871]
### Bug description

The menu sidebar jumps up a few pixels after its expansion and animation.

Screen recording:
https://github.com/quarto-dev/quarto-cli/assets/362187/4cf6fd4b-8011-4bf6-9ce9-676469a30b38

This behavior is in Quarto 1.4.525, but not the Quarto 1.3 release.

### Steps to reproduce

The following navigation structure causes this issue:

```yaml
project:
  type: website

website:
  title: a website
  navbar:
    pinned: true
    left:
      - text: 'Home'
        href: 'index.md'
      - text: 'Admin'
        href: 'admin/index.md'
      - text: 'User'
        href: 'user/index.md'

  sidebar:
    - title: 'Admin'
      collapse-level: 1
      contents:
        - text: 'Overview'
          file: 'admin/index.md'
        - section: 'Sub'
          contents:
            - text: 'Overview'
              file: 'admin/sub/index.md'
            - text: 'SubSub'
              file: 'admin/sub/subsub/index.md'
    - title: 'User'
      contents:
        - text: 'Overview'
          file: 'user/index.md'
        - section: 'Sub'
          contents:
            - text: 'Overview'
              file: 'user/sub/index.md'
            - text: 'SubSub'
              file: 'user/sub/subsub/index.md'

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-expand: true
```

You can put any content within the hierarchy; what is important is that the sidebar is visible and can be expanded/collapsed.

### Expected behavior

Smooth menu expansion with no position adjustment.

### Actual behavior

Menu expansion which jumps up after expanding.

### Your environment

Quarto 1.4.525

### Quarto check output

```
Quarto 1.4.525
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.525
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /opt/R/4.3.0/lib/R
      LibPaths:
        - /opt/R/4.3.0/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```
