### ISSUE TITLE
Fix attributes quoting issue HTML generated by video shortcode 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7911]
looking at the HTML generated, we may have some generation issue too (look at the attributes and quoting issues)

````html
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://player.vimeo.com/video/32001208" frameborder="0" allow="autoplay; title=" "="" fullscreen;="" picture-in-picture"="" allowfullscreen=""></iframe></div>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/wo9vZccmqwc" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
````

From

````markdown
---
title: "Quarto Playground"
format: html
keep-md: true
---

{{< video https://vimeo.com/32001208 >}}

{{< video https://www.youtube.com/embed/wo9vZccmqwc >}}
````

_Originally posted by @cderv in https://github.com/quarto-dev/quarto-cli/issues/7905#issuecomment-1853546507_

**Comment by cscheid** [comment]
The shortcode is emitting a bad rawblock. From our filter trace:

```
blocks:
  - t: "RawBlock"
    format: "html"
    text: "<div class=\"quarto-video ratio ratio-16x9\"><iframe data-external=\"1\" src=\"https://player.vimeo.com/video/32001208\" frameborder=\"0\" allow=\"autoplay; title=\"\" fullscreen; picture-in-picture\" allowfullscreen></iframe></div>"
```
