### ISSUE TITLE
Add truly minimal rendering

### ISSUE THREAD

**Issue by JosiahParry** [quarto-dev/quarto-cli#7986]
I would like to be able to render quarto docs to truly minimal html but am only able to get part of the way there with the following front-matter

```yaml
format:
   html:
      minimal: true
      highlight-style: none
      self-contained: true
```

However, this still add a lot of style tags with css. Is there a way to get truly minimal rendering? e.g. pure html without the style? The idea being that I can use the rendered html in a different site perhaps one that even doesn't use bootstrap! :)
