### ISSUE TITLE
Navbar not rendering shortcodes

### ISSUE THREAD

**Issue by pommevilla** [quarto-dev/quarto-cli#80]
Shortcodes for values in `_variables.yml` are not rendering properly in navbars:

![image](https://user-images.githubusercontent.com/6981612/128214170-70a7321a-10c7-477f-b942-22dbe19b5155.png)

They work in the titles of individual documents, though:

```
--- 
title: "RStudio Workbench {{< var version >}}"
date: "`r Sys.Date()`"
--- 
```
![image](https://user-images.githubusercontent.com/6981612/128214389-7d395b8c-3f98-4383-b2a7-601cd433623a.png)

Relevant `_quarto.yml`:

```
site:
  title: "RStudio Workbench Administration {{< var version >}}"
  navbar:
    type: light
    # title: "RStudio Workbench Administration {{< var version >}}"
```

The shortcode isn't evaluated properly regardless of which `title` line is being used.

Here's a repo with a minimal example: https://github.com/pommevilla/navbar-shortcodes
