### ISSUE TITLE
Tertiary Bootstrap Theme

### ISSUE THREAD

**Issue by Vinnie-Palazeti** [quarto-dev/quarto-cli#8047]
### Bug description

I cannot get quarto to use the third theme option listed on the Bootstrap example page. 

See: https://bootswatch.com/sandstone/

I've been able to use sandstone & sandstone-light, but I have not found any documentation related to this on the website. So it could be as easy as finding the available suffixes for sandstone-

### Steps to reproduce

```
project:
  type: website

website:
  title: "Site"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sandstone-light
    css: styles.css
```

### Expected behavior

Renders with light colored navbar (third here:  https://bootswatch.com/sandstone/)

### Actual behavior

Renders with primary colored navbar
