### ISSUE TITLE
Looks like #2787 has re-reappeared (?) "Subscribe doesn't show up in the posts"

### ISSUE THREAD

**Issue by bryanhanson** [quarto-dev/quarto-cli#8057]
### Bug description

Working on a blog post today and noticed the behavior described in #2787 seems to have returned.  As far as I can tell the process for including a subscribe button is unchanged.  Using quarto as available today via git pull and running the configuration script.

### Steps to reproduce

Build the blog document.  Here is my `_quarto.yml` which seems to comply with the documentation:

```
project:
  type: website
  output-dir: docs
  resources:
    - slow-blink.mp4
website:
  title: "Chemometrics and Spectroscopy Using R"
  site-url: http://chemospec.org
  description: "Applying chemometrics to spectroscopy using R"
  cookie-consent:
    prefs-text: "Cookies are used to track visits only"
  body-footer: <script data-goatcounter="https://chemospec.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
  twitter-card: true
  margin-header: subscribe.html
  comments:
    utterances:
      repo: bryanhanson/CSR
  navbar:
    background: primary
    foreground: "#FFFFFF"
    search: true
    right:
      - text: "About"
        file: about.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "R-Bloggers"
        href: https://www.r-bloggers.com/
      - icon: envelope-fill
        href: mailto:hanson@depauw.edu
      - icon: twitter
        href: https://twitter.com/profbryanhanson
      - icon: mastodon
        aria-label: Mastodon
        href: https://fosstodon.org/%40ProfBryanHanson
        rel: "me"
      - icon: git
        href: https://github.com/bryanhanson
      - icon: rss
        file: index.xml
format:
  html:
    theme: simplex
    css: styles.css
    code-line-numbers: true
```

### Expected behavior

As described in #2787

### Actual behavior

As described in #2787

### Your environment

Using the command line on MacOS 14.2.1:
```
quarto render
quarto preview
```

### Quarto check output

```bash
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/package/dist/bin

Check file:///Users/bryanh/Documents/Professional/Research/R_Pkgs/quarto-cli/src/resources/vendor/deno-land/x/puppeteer@9-0-2/mod.ts
[✓] Checking tools....................OK
      TinyTeX: v2023.07.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/bryanh/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```
