### ISSUE TITLE
cap-location: margin doesn't play nicely with .column-page & .column-margin (PDF)

### ISSUE THREAD

**Issue by pastorn** [quarto-dev/quarto-cli#8136]
### Bug description

I'm trying out the Tufte style features (PDF) with quarto but I can't get figure captions to work. Here's my output:

![quarto-bugrep-1](https://github.com/quarto-dev/quarto-cli/assets/712688/fc123661-b7b7-4679-80e7-57ec99b1cf70)

```yaml
---
reference-location: margin
citation-location: document
tbl-cap-location: margin
cap-location: margin

pdf-engine: lualatex

format:
    pdf:
      papersize: a4
      geometry:
        - showframe # not for final release
        - left=15.0mm
        - textwidth=102.0mm
        - marginparsep=7.7mm
        - marginparwidth=70.3mm
---
```

And this is my qmd code:

```md
![Hello from margin, please.](widea.jpg){#fig-widea}

@fig-widea is a nice one.

---

::: {.column-page #fig-widea-wider }

![](widea.jpg)

WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?! WHY DO YOU TREAT ME LIKE NOTHING!?!?!

:::

@fig-widea-wider is a bit wider.



---

for spacing...

---

::: {.column-margin #fig-wideb}

![](wideb.jpg)

Here's the caption text to the village picture. Here's the caption text to the village picture. Here's the caption text to the village picture. Here's the caption text to the village picture. 

:::

@fig-wideb looks like a nice place.
```

![quarto-bugrep-2](https://github.com/quarto-dev/quarto-cli/assets/712688/ba170dd4-2b1b-4701-ac4a-db4bb7bea09b)

As you can see the caption text is there, but doesn't respect the image height (it seems to me). 

In case it's not clear, these are the properties I expected:

  * The caption text to Figure 2 should be in the margin, starting at the right underneath the image.
  * The caption to Figure 3 should be underneath the image, all placed in the margin.

<details>
  <summary><b>Quarto check output</b></summary>

Based on git commit d089957780198d26b0ba96269b4e05e1c35be117
Fri Jan 5 08:56:19 2024

```
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/sasja/.quarto/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/sasja/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /usr/bin/python3
      Jupyter: 5.5.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/lib64/R
      LibPaths:
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

But issue is also there on `quarto-1.4.534` (Aug 4 2023)

</details>
