### ISSUE TITLE
Make code tools in sidebar/navbar localised

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8145]
From what I see, it seems some tooltip are localised:
| Source | Reader |
|--------|--------|
|![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/81ec46a5-f1d8-46a7-b943-d2b08a53fda6) | ![image](https://github.com/quarto-dev/quarto-cli/assets/8896044/e1408f5c-6180-4414-bfb3-fcef4c03182f) | 

See https://github.com/quarto-dev/quarto-cli/blob/094f50717a6854448c984ea0bd4b0b72fcfda260/src/resources/language/_language-pt-BR.yml#L77-L78

The issue is that the template does not use the language but the default aria label: https://github.com/quarto-dev/quarto-cli/blob/094f50717a6854448c984ea0bd4b0b72fcfda260/src/resources/projects/website/templates/navtools.ejs

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8125

<div type='discussions-op-text'>

<sup>Originally posted by **luifrancgom** January  4, 2024</sup>
### Description

I am developing a book in a language other than English. I need to know if it's possible to modify the tooltip text that appears when hovering over the icons in the side navbar, specifically for the 'Share' and 'Source Code' options.

While the tooltip text for the 'Reader Mode' and 'Light/Dark Theme' icons correctly adapts to different languages, this isn't the case for the aforementioned icons.

![video_question](https://github.com/quarto-dev/quarto-cli/assets/50002526/8a0f4867-e4ad-45f3-8c99-cdd80021e39c)

I have many elements in the yalm but this are the relevant elements:

```yaml
project:
  type: book

lang: pt-BR

book:
  sharing: [twitter, linkedin, facebook]
  site-url: https://luifrancgom.github.io/estatistica-descritiva-R-1ed/
  repo-url: https://github.com/luifrancgom/estatistica-descritiva-R-1ed
  repo-branch: main
  issue-url: https://github.com/luifrancgom/estatistica-descritiva-R-1ed/issues
  reader-mode: true

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
```
Where according to [Quarto Localization](https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language) `pt-BR` is supported with the following [translation](https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language-pt-BR.yml).

Is there a way to modify the tooltip text for the 'Share' and 'Source Code' options or it is a feature I need to request so the developers can add this option in [Quarto Localization](https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language)?</div>
