### ISSUE TITLE
Quarto book - gravis in title of page

### ISSUE THREAD

**Issue by pjastr** [quarto-dev/quarto-cli#8148]
### Bug description

In the latest version of RealSense Candidate, I have this error: if the grave accent symbol is used in the title of the page (section), it is not recognized as code in the navigation on the left. Previously in version 1.3, it was fine.

### Steps to reproduce

```
# Interfejs `Comparable`
```

![image](https://github.com/quarto-dev/quarto-cli/assets/24464854/2976f3f2-36e6-495e-aaa6-1f75d225f30c)

### Expected behavior

![image](https://github.com/quarto-dev/quarto-cli/assets/24464854/f059da05-7fb1-4c57-bba3-a55441d24376)

### Actual behavior

![image](https://github.com/quarto-dev/quarto-cli/assets/24464854/2976f3f2-36e6-495e-aaa6-1f75d225f30c)

### Your environment

RStudio 2023.12.0+369 "Ocean Storm" Release (33206f75bd14d07d84753f965eaa24756eda97b7, 2023-12-14) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.0+369 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

**Comment by mcanouil** [comment]
Could you share a small self-contained "working" (reproducible) example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

**Comment by pjastr** [comment]
Test repo https://github.com/pjastr/test601

Output html https://pjastr.github.io/test601/

_quarto.yml

```
project:
  type: book

book:
  title: "Test repo"
  author: pjastr
  date: today
  chapters:
    - index.qmd
    - part: "Test part"
      chapters: 
        - part1.qmd
 
format:
  html:
    theme:
      light: cosmo
      dark: solar
    lang: pl
  pdf:
    lang: pl


editor: visual
```

part1.qmd

```qmd
# Test `someCode`

Test
```
