### ISSUE TITLE
Convert PDF images to SVG for Typst format (as done for PDF/LaTeX)

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8185]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8180

<div type='discussions-op-text'>

<sup>Originally posted by **psads-git** January  9, 2024</sup>
### Description

Consider the code:

```
---
title: Page Layout
format:
  typst:
    papersize: a4
    margin:
      x: 1cm
      y: 1cm
    # columns: 2
---

# Introduction

![My image](excel01.pdf){width=80%}
```

When compiling, I get the error:

```
[typst]: Compiling Untitled-1.typ to Untitled-1.pdf...error: unknown image format
    ┌─ Untitled-1.typ:251:16
    │
251 │ #box(width: 80%,image("excel01.pdf"))
    │                 ^^^^^^^^^^^^^^^^^^^^
```    

I am aware that `typst` does not accept PDF images.

My question is: Is there another way to insert `PDF` images with `quarto` than manually convert them to, say, `SVG`? Thanks!
</div>
