### ISSUE TITLE
using `field-types` key in the front matter causes `date-format` to be ignored

### ISSUE THREAD

**Issue by danmackinlay** [quarto-dev/quarto-cli#8197]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8134

<div type='discussions-op-text'>

<sup>Originally posted by **danmackinlay** January  6, 2024</sup>
### Description

I am trying to create a custom listing which adds some custom numerical rating  (`usefulness`) to some blog posts  and displays the listing using that custom metadata. I would like to  sorting by either date or by rating using the sort ui.

The frontmatter on my listing page looks like this:

```yaml
title: Notebooks
listing:
  page-size: 50
  sort: "date-modified desc"
  type: default
  categories: true
  sort-ui:
    - title
    - date
    - date-modified
    - usefulness
  filter-ui:
    - title
    - subtitle
  template: theme/living_listing.ejs
  contents:
    - notebook
  feed: true
  # field-types:
  #   date: date
  #   date-modified: date
  #   usefulness: number
  field-display-names:
    title: "Title"
    date: "Created"
    date-modified: "Modified"
    usefulness: "Usefulness"
  date-format: YYYY-MM-DD
```

This nearly works, in that it displays some blog posts; A formatted example is show here:

<img width="827" alt="Screenshot 2024-01-05 at 21 08 38" src="https://github.com/quarto-dev/quarto-cli/assets/21740/7bf6e530-f05b-4926-888f-af9ffe5b3239">

The problem is that I cannot really sort by `usefulness` here, since I have not declared that it is a numerical rating, I need to declare the metadata to be numerical, so I uncomment the `field-types` section:

```yaml
title: Notebooks
listing:
  page-size: 50
  sort: "date-modified desc"
  type: default
  categories: true
  sort-ui:
    - title
    - date
    - date-modified
    - usefulness
  filter-ui:
    - title
    - subtitle
  template: theme/living_listing.ejs
  contents:
    - notebook
  feed: true
  field-types:
  #   date: date
  #   date-modified: date
    usefulness: number
  field-display-names:
    title: "Title"
    date: "Created"
    date-modified: "Modified"
    usefulness: "Usefulness"
  date-format: YYYY-MM-DD
```

Now I *can* sort by usefulness, but the date formatting has gone haywire:

<img width="917" alt="Screenshot 2024-01-05 at 21 10 01" src="https://github.com/quarto-dev/quarto-cli/assets/21740/ec0b86bf-a308-44ee-89a8-a28466fbb09f">

I.e. using the `field-types` key at all causes date display to ignore the specified simple clean date format `YYYY-MM-DD`, e.g.  `2020-01-22` to some kind of  maximalist alternate `Wed Jan 22 2020 11:28:53 GMT+0800 (GMT+08:00)`. (The timezone so nice we mention it twice)
I can further uncomment the `date`, `date-modified` entries in the front matter, but that does not restore the date formatting.

```yaml
title: Notebooks
listing:
  page-size: 50
  sort: "date-modified desc"
  type: default
  categories: true
  sort-ui:
    - title
    - date
    - date-modified
    - usefulness
  filter-ui:
    - title
    - subtitle
  template: theme/living_listing.ejs
  contents:
    - notebook
  feed: true
  field-types:
    date: date
    date-modified: date
    usefulness: number
  field-display-names:
    title: "Title"
    date: "Created"
    date-modified: "Modified"
    usefulness: "Usefulness"
  date-format: YYYY-MM-DD
```

I can present the template as well if this will help clarify the problem. This already feels like a long post though, so I will for now just include the part that displays the date:

```ejs
        <div class="metadata"><a href="<%- item.path %>" class="no-external">
            <span class="archive-item-date">
                <span class="listing-date">
                    <%= item.date %>
                </span>
                <% if (item['date-modified']) { %>
                    — <span class="listing-date-modified">
                        <%= item['date-modified'] %>
                    </span>
                <% } %>
            </span>
        </a></div>
```

What is going on here? Have I missed some basic understanding of how to apply `date-format`? Or is this a bug?
</div>

**Comment by danmackinlay** [comment]
MWE demonstrating this behaviour here: https://github.com/danmackinlay/quarto_custom_listing

**Comment by danmackinlay** [comment]
I constructed an MWE for this. Here is the repo: https://github.com/danmackinlay/quarto_custom_listing

Here is a custom listingdisplaying mangled date formatting:
https://github.com/danmackinlay/quarto_custom_listing/blob/main/index_custom_w_field_types.qmd
And here is one that displays no such mangling:
https://github.com/danmackinlay/quarto_custom_listing/blob/main/index_custom.qmd

**Comment by cderv** [comment]
Helping to diagnose this: 

when no `field-types` provided, only the default one will be used 
https://github.com/quarto-dev/quarto-cli/blob/564d01520f37dcd60bc52292830e66f68a104d2a/src/project/types/website/listing/website-listing-read.ts#L160-L166

Default listing is hydrated at 
https://github.com/quarto-dev/quarto-cli/blob/564d01520f37dcd60bc52292830e66f68a104d2a/src/project/types/website/listing/website-listing-read.ts#L595-L611

It happens that we `...listing` at the end. 

This means the any `field-types` provided in the document listing will be merged with default and override. So doing
````yaml
  field-types:
    usefulness: number
````
will replace the  default `listingHydrated[kFieldTypes]` 


This leads to the requirement to provide values also for usually default fields. Hence why this fix it
````yaml
  field-types:
    date: date
    date-modified: date
    usefulness: number
````

Is this the expected merging behavior @dragonstyle ? 

We do specifically try to merge the `field-types` later at
https://github.com/quarto-dev/quarto-cli/blob/564d01520f37dcd60bc52292830e66f68a104d2a/src/project/types/website/listing/website-listing-read.ts#L661-L665

but this is too late - it has already been replaced and `listingHydrated[kFieldTypes]` is equal to `listing[kFieldTypes]`

So maybe we have a bug here ? 

Hope it helps
