### ISSUE TITLE
`date-modified` metadata is only used for sorting with custom template

### ISSUE THREAD

**Issue by danmackinlay** [quarto-dev/quarto-cli#8198]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/7854

<div type='discussions-op-text'>

<sup>Originally posted by **danmackinlay** December  9, 2023</sup>
### Description
To summarise that discussion

1. Quarto 1.4 does support the use of a `date-modified` metadata field, which, if used correctly will allow you to sort by date-modified, as well as date
2.  I created an [MWE demonstrating how to do this](https://github.com/danmackinlay/quarto_date_modified)
3. There is probably a bug in quarto, because contrary to the [documentation](https://quarto.org/docs/websites/website-listings.html#customizing-fields) and to @mcanouil 's [helpful comment](https://github.com/quarto-dev/quarto-cli/discussions/7854#discussioncomment-7936934), this `date-modified` stuff appears to only work as a custom sort if I create a custom template,  [as seen in my MWE](https://github.com/danmackinlay/quarto_date_modified)

Example of failure to sort by date-modified [quarto\_date\_modified/index\_modified.qmd](https://github.com/danmackinlay/quarto_date_modified/blob/main/index_modified.qmd)

<img width="772" alt="Screenshot 2024-01-10 at 10 52 29" src="https://github.com/quarto-dev/quarto-cli/assets/21740/46c79f34-38ac-4fe8-897c-b87a9dfb8d22">

Example of successful sort by date-modifeid if we use a custom template:
 [quarto\_date\_modified/index\_modified\_custom.qmd at main](https://github.com/danmackinlay/quarto_date_modified/blob/main/index_modified_custom.qmd)
 
<img width="825" alt="Screenshot 2024-01-10 at 10 52 37" src="https://github.com/quarto-dev/quarto-cli/assets/21740/20c96b74-7e2f-425f-9d2d-d7505223224d">

**Comment by dragonstyle** [comment]
This is actually behaving as designed. For the built in types of listing, we provide a default list of fields for sorting, which you can override. For custom listing types, since we don't "know" what the listing is doing, we don't have this default behavior to the sort list - we just include the fields.

To control the fields that are displayed in the sort ui, just pass the field names to `sort-ui` like:

```yaml
listing:
  page-size: 50
  sort: "date-modified desc"
  type: default
  categories: true
  # Note `sort-ui` with list of keys to include in sort ui
  sort-ui:
    - date
    - date-modified
    - title
  filter-ui: true
  contents:
    - posts
  fields: [date, date-modified, title]
  field-types:
    date: date
    date-modified: date
  field-display-names:
    title: "Title"
    date: "Created"
    date-modified: "Modified"
```

HTH!
