### ISSUE TITLE
Allow to disable dashboard navbar when integrated in a website

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8265]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8262

<div type='discussions-op-text'>

<sup>Originally posted by **andrewheiss** January 14, 2024</sup>
### Description

It's currently possible to include Quarto dashboards as pages in a Quarto website (and I hope that's by design and not accidental! It's super helpful!)

However, the dashboard includes its own navbar, which is also by design, since [1st level headings cause dashboards to have multiple pages](https://quarto.org/docs/dashboards/layout.html#pages).

When part of a website, this creates a double navbar. That makes sense in cases where people might be including a multi-page dashboard, but when including a single-page dashboard, the double navbar is redundant:

![image](https://github.com/quarto-dev/quarto-cli/assets/73663/405122db-b7ef-45ed-8e58-604a14630a33)

It would be neat if there was a way to turn off the navbar for a dashboard. My current solution is to hide it with CSS, but that feels hacky.

``` yaml
include-before-body: 
  text: |
    <style>
      #quarto-dashboard-header {
        display: none
      }
    </style>
```

---

Here's a reproducible example:

**_quarto.yml**

``` yaml
project:
  type: website

website:
  title: "Dashboard in website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - dashboard.qmd
```

**index.qmd**

```` qmd
---
title: "Dashboard in a website"
---

Blah.
````

**dashboard.qmd**

````qmd
---
title: "Dashboard"
format: 
  dashboard: default
---

## Row {height=40%}
::: {.card}
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
:::

::: {.valuebox icon="pencil" color="blue"}
A number

3
:::

## Row {height=60%}

::: {.card}
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
:::
````

Change **dashboard.qmd** to this to get rid of the dashboard navbar:

````qmd
---
title: "Dashboard"
format: 
  dashboard: default
include-before-body: 
  text: |
    <style>
      #quarto-dashboard-header {
        display: none
      }
    </style>
---

## Row {height=40%}
::: {.card}
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
:::

::: {.valuebox icon="pencil" color="blue"}
A number

3
:::

## Row {height=60%}

::: {.card}
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
:::
````

Now it's gone:

![image](https://github.com/quarto-dev/quarto-cli/assets/73663/3d51f47e-5aeb-4190-b894-3c74c8efb2c5)
</div>
