### ISSUE TITLE
When the filename suffix is qmd, the compiled html has no theme

### ISSUE THREAD

**Issue by williamlorder** [quarto-dev/quarto-cli#827]
As the title says, when the filename is suffixed with `qmd`, the compiled html has no theme(default setting).

In this case only if I add `standalone: true` to the yaml will the html compile with a theme, or change the file suffix to `md`.

**Comment by jjallaire** [comment]
All of our tests + our website + our development scaffolds use file with the `.qmd` extension and there is no problem with rendering/themes. If you could provide a more complete example (ideally a git repo with a simple reproducible case) that would be help us get to the bottom of things.

**Comment by williamlorder** [comment]
Sure, as you can see below, Here is what I declare in  my `yaml` header.

```yaml
title : "Test"
author: "Test"
institute: "Test"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    html-math-method: katex
    #self-contained: true
    #toc-title: 目录
    #theme: journal
    number-sections: true
  docx:
    reference-doc: /Users/zekai/custom-reference.docx  
  #gfm:
    #html-math-method: katex
#crossref:
  #chapters: true
  #fig-title: Fig # (default is "Figure")
  #tbl-title: Tbl # (default is "Table")
  #fig-prefix: Figure   # (default is "fig.")
  #tbl-prefix: Table    # (default is "tbl.")
#zotero:
  #library: <group name> 
  #scannable-cite: false
  #client: <zotero or jurism> 
  #author-in-text: false 
  #csl-style: apa 
bibliography: "/Users/zekai/References.json"
filters: 
  - /Users/zekai/zotero.lua
#csl: "/Users/zekai/sustainability.csl"
```

After render, it came out this (without the additional files which contains `css` or something else).
<img width="508" alt="截屏2022-05-08 19 08 21" src="https://user-images.githubusercontent.com/83387569/167293427-ffb2f91f-b5bf-40f0-b971-4559d522bef9.png">

And here's the content in html

<img width="508" alt="截屏2022-05-08 19 09 08" src="https://user-images.githubusercontent.com/83387569/167293470-e1e0e9b7-66c9-47f1-882c-bb18cfd69361.png">
