### ISSUE TITLE
Sidebar options like style can only be set on first sidebar in config

### ISSUE THREAD

**Issue by machow** [quarto-dev/quarto-cli#8431]
### Bug description

Quarto's website navigation docs show an example of a hybrid sidebar, with options like `style: docked` set on the first sidebar entry:

```yaml
website:
  title: ProjectX
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:tutorials
      - sidebar:howto
      - sidebar:fundamentals
      - sidebar:reference

  sidebar:
    - id: tutorials
      title: "Tutorials"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        # navigation items
        
    - id: howto
      title: "How-To"
      contents:
        # navigation items
        
    - id: fundamentals
      title: "Fundamentals"
      contents: :
        # navigation items
        
    - id: reference
      title: "Reference"
      contents: 
        # navigation items
    
```

This works. However, it makes all 4 sidebar styles "docked". Specifying `style: ...` on other entries does not affect the corresponding sidebar.

### Steps to reproduce

Create the website corresponding to the quarto example pasted above. Move the `style: docked` to another sidebar entry. The sidebar will not be docked on any sidebar.

(Note also that the example code above docks the sidebar on all sidebars)

### Expected behavior

All sidebars can have any of the sidebar options specified. Options specified for the first sidebar only apply to that sidebar.

### Actual behavior

Options like `style:` set on the first sidebar apply to all. The same option set on others, do not get applied.

### Your environment

Mac OS

### Quarto check output

```bash
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.2
      Path: /Users/machow/.virtualenvs/quartodoc/bin/python3
      Jupyter: 5.5.0
      Kernels: python3, venv-siuba, venv-tidyselect, venv-siuba-docs2, venv-pins-python, venv-shout, venv-vetiver-test, venv-siuba-polars, venv-data-analyses, venv-intro-to-siuba, venv-tidyverse-dashboard-duckdb, venv-gt-python, venv-gh_reader, venv-stadium-economics, venv-vetiver-python, venv-shiny-examples, venv-duckops, venv-quartodoc, venv-pyshiny-site, venv-notes, venv-siuba-docs, venv-siuba-workshop, venv-griffe

[✓] Checking Jupyter engine render....OK
```

**Comment by gadenbuie** [comment]
Thanks for creating this issue @machow! The Shiny team is interested in this issue -- we'd like to have a docked sidebar in the [Shiny for Python API reference](https://shiny.posit.co/py/api/) while using [a floating sidebar elsewhere](https://shiny.posit.co/py/components/inputs/action-button/) on the site.

**Comment by mcanouil** [comment]
From:


---

### Bug description

As of the latest development version of Quarto CLI (a180400ca298df9e55e5306252f5a8e05dd1dc08), it appears it's not possible to customise the `style` of sidebar.
The first style will be used for all sidebar regardless of a `style` being defined for the other sidebars.

### Steps to reproduce

```sh
quarto create project blog
````

Edit `_quarto.yml` to add sidebars:

```yml
website:
  ...
  sidebar:
    - id: index
      style: "docked"
      contents:
        - index.qmd
    - id: about
      style: "floating"
      contents:
        - about.qmd
```

### Actual behavior

https://github.com/user-attachments/assets/576a24a2-b497-437c-ad67-2795fb184b27

### Expected behavior

The sidebar in the "about" page should use the "floating" style, not the "docked" style defined for the other sidebar.

### Your environment

_No response_

### Quarto check output

```bash
Check file:///Users/mcanouil/Projects/quarto/quarto-cli/src/quarto.ts
Quarto 99.9.9
[✓] Checking environment information...
      Quarto cache location: /Users/mcanouil/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      commit: a180400ca298df9e55e5306252f5a8e05dd1dc08
      Path: /Users/mcanouil/Projects/quarto/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2025.02
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mcanouil/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
      Source: QUARTO_CHROMIUM

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.13.2
      Path: /Users/mcanouil/Projects/quarto/quarto-playground/.venv/bin/python
      Jupyter: 5.7.2
      Kernels: julia-1.11, python3

[✓] Checking Jupyter engine render....OK

(|) Checking R installation...........ℹ R version 4.4.2 (2024-10-31)
! Config '~/.Rprofile' was loaded!
[✓] Checking R installation...........OK
      Version: 4.4.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/mcanouil/Projects/quarto/quarto-playground/renv/library/macos/R-4.4/aarch64-apple-darwin20
        - /Users/mcanouil/Library/Caches/org.R-project.R/R/renv/sandbox/macos/R-4.4/aarch64-apple-darwin20/f7156815
      knitr: 1.46
      rmarkdown: 2.29

[✓] Checking Knitr engine render......OK
```
