### ISSUE TITLE
Custom callout boxes

### ISSUE THREAD

**Issue by tavareshugo** [quarto-dev/quarto-cli#844]
Firstly, many thanks for the fantastic package you are developing!

I am following from @athulsudheesh's [comment](https://github.com/quarto-dev/quarto-cli/issues/556#issuecomment-1098078841) in #556, to request a new feature for custom callout boxes.

One use case I have in mind is for exercises in books or course materials, for example:

```md
:::{.callout-exercise}

Exercise description.

:::{.callout-answer collapse="true"}
The answer to the exercise
:::

:::
```

I guess these would have to be defined somewhere following a template (on the front matter? or on a separate YAML, that is then referenced on the front-matter?).

```yaml
callout: "exercise"
    title: "Exercise"
    color: "purple"
    icon: "fa-question"
    collapse: "false"
callout: "answer"
    title: "Answer"
    color: "green"
    icon: "fa-pen"
    collapse: "true"    
```

Alternatively maybe this could be done through a generic callout with a couple of extra options, such as:

```md
:::{.callout-custom color="purple" icon="fa-question"}
## Exercise

A purple callout block with a question mark icon.
:::
```

The disadvantage here is that there is more typing involved.
