### ISSUE TITLE
Hyperlink to part in Quarto books should not be clickable if part does not contain anything.

### ISSUE THREAD

**Issue by olivroy** [quarto-dev/quarto-cli#8446]
### Bug description

Hi, for books in Quarto 1.4

### Steps to reproduce

1. Go to https://r-pkgs.org/testing-design.html
2. On the top, hover over Testing
![image](https://github.com/quarto-dev/quarto-cli/assets/52606734/245d2027-1098-45fa-90b6-0bced267af99)
3. If you click, it takes you to the first chapter of Testing (and as you see on the bottom left, it shows the hyperlink

### Expected behavior

I think that if the Part testing has some text, than create an hyperlink, otherwise, not create an hyperlink, just like in the sidebar.
![image](https://github.com/quarto-dev/quarto-cli/assets/52606734/6908812c-dc38-4f59-9260-5ce7f3db1947)
Hovering over **Testing** does not create an hyperlink.

### Actual behavior

Creates an hyperlink to the first chapter of the Part. (I guess that if the part is non-empty, the link takes us to the part, which seems reasonable.

### Your environment

N/A (probably quarto 1.4 latest?)

**Comment by mcanouil** [comment]
Thanks for the report!
Could you provide the output of `quarto check` as requested in the template?

**Comment by olivroy** [comment]
Well, I am simply reading the book online. but could the github actions used help? https://github.com/hadley/r-pkgs/blob/main/.github/workflows/render.yaml

**Comment by olivroy** [comment]
oh maybe sharing the `_quarto.yml` may help make this clearer

This should not generate an hyperlink for the part.
```yaml
  - part: Testing
    chapters:
    - testing-basics.Rmd
    - testing-design.Rmd
    - testing-advanced.Rmd
  ```

while a setting like this should generate one?

```yaml
  - part: test.qmd
    chapters:
    - testing-basics.Rmd
    - testing-design.Rmd
    - testing-advanced.Rmd
  ```
