### ISSUE TITLE
Support gender/pronous in author metadata?

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8476]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2796

<div type='discussions-op-text'>

<sup>Originally posted by **knuesel** October 11, 2022</sup>
Following https://github.com/quarto-dev/quarto-cli/discussions/1309 quarto uses a neutral form for the author text in French. Maybe the author metadata could also support a "gender", so that translations can use the appropriate male/female/neutral form?

For example

```
---
title: Titre
author:
  name: Jane Doe
  gender: female
lang: fr
---
```

could produce a title block with "Autrice: Jane Doe"  (and "Auteur: Jane Doe" in case of `gender: male`) instead of the current "Auteur·rice: Jane Doe".

I think "auteur·rice" is nice when the gender is not known or when there are several authors of different gender, but when the gender is known it's rather weird... (for readers unfamiliar with French, an English equivalent would be to write "(Wo)man who wrote this: Jane Doe").

For example if I put my name on a document for my students, of course I know my gender and it seems impersonal and strange to write "auteur·rice".</div>

<div type='discussions-op-text'>

<sup>Originally posted by **javentous
** January 28, 2024</sup>
Hello, I was looking for a pronoun option as well for a blog I am making. I wanted to add it to the `yaml` in the `.qmd` preceeding the document body.

something like

```
---
title: "Paradise Lost"
author: "John Milton"
author-pronouns: "he / him"
categories:
  - Epic Poetry
  - Blank Verse
  - Religious Fiction
  - Christian Mythology
---
```

or for an extended `author` section

```
---
title: "Paradise Lost"
author: 
  name: "John Milton"
  pronouns: "he / him"
  gender: "man"
categories:
  - Epic Poetry
  - Blank Verse
  - Religious Fiction
  - Christian Mythology
---
```

Thanks for the work! Really liking `quarto a ton`</div>
