### ISSUE TITLE
Sidebar `align` no longer respected

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#8510]
Although not documented, we used to respect `sidebar: align`. I broke this in Quarto 1.4, forcing it only to respect `alignment`.

This should work:

```yaml
  sidebar:
    logo: salute.gif
    align: center
```

even though this is preferred:

```yaml
  sidebar:
    logo: salute.gif
    alignment: center
```
