### ISSUE TITLE
listing categories with `'` in them can't be clicked on

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#8517]
I'll come up with a full example soon, but I think this should trigger it.

Create a listing like this:

````
---
title: "log"
listing:
  contents: 
    - "2024-*.qmd"
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
  feed: true
page-layout: full
title-block-banner: true
---
````

then in one of the posts add a category like this:

````
---
title: "2024-01-01"
categories:
  - i'm-an-idiot
  - other
---
````

That category will show up on the listings sidebar but can't be clicked on, and if you click on `other`, this post won't be part of the filtered subset.
