### ISSUE TITLE
quarto preview with .ipynb - issue parsing with Javascript/CSS? (Holoviews/Bokeh)

### ISSUE THREAD

**Issue by jules32** [quarto-dev/quarto-cli#857]
Hi! 

We've been having issues with .ipynb files that have Holoviews/Bokeh - these often take a long time to `quarto preview` in our JupyterHub, and also with our GitHub Action. We've encountered this before and likely chatted about it but wanted to revisit –

Here are a few example notebooks where we are seeing this (included in [_quarto.yml#L52-L58](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/_quarto.yml#L52-L58)):

- [LPDAAC_ECOSTRESS_LSTE__Kerchunk.ipynb](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/examples/LPDAAC/LPDAAC_ECOSTRESS_LSTE__Kerchunk.ipynb)
- [PODAAC_ECCO_SSH__Kerchunk.ipynb](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/examples/PODAAC/PODAAC_ECCO_SSH__Kerchunk.ipynb)
- [GESDISC_MERRA2_tavg1_2d_flx_Nx__Kerchunk.ipynb](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/examples/GESDISC/GESDISC_MERRA2_tavg1_2d_flx_Nx__Kerchunk.ipynb) > note that this is currently not included in our quarto site ([_quarto.yml#L54](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/_quarto.yml#L54)) because `quarto preview` was taking so long

A few more details about it in [this earthdata-cloud-cookbook issue](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/issues/102), where @betolink says:

> I think this may be because these notebooks use Holoviews/Bokeh. `HVPlot` injects a lot of Javascript and CSS into the notebook ([in the order of megabytes](https://raw.githubusercontent.com/NASA-Openscapes/earthdata-cloud-cookbook/main/examples/GESDISC/GESDISC_MERRA2_tavg1_2d_flx_Nx__Kerchunk.ipynb)) and perhaps Quarto is having issues parsing all of this.

Thanks in advance for any help!

**Comment by jjallaire** [comment]
I haven't been able to repro anything terribly unexpected here. I've downloaded these notebooks and included this `_quarto.yml` file:

````yaml
project:
  type: website
  
website: 
  navbar: 
    title: "Test Notebooks"
    left: 
      - text: NB 1
        href: GESDISC_MERRA2_tavg1_2d_flx_Nx__Kerchunk.ipynb
      - text: NB 2
        href: LPDAAC_ECOSTRESS_LSTE__Kerchunk.ipynb
      - text: NB 3
        href: PODAAC_ECCO_SSH__Kerchunk.ipynb
````

On my laptop it takes about 9 seconds to render the site. Depending on how fast your server machine is though this could blow up quite a bit (5x slower?). In terms of preview, assuming it's fully rendered the site comes up in a second or two and each page takes about 3 seconds to render when clicked on in the browser (of course this could be considerably slower if your server is slower).

So it does seem like on a slower server machine .ipynb files of this size could be slow to preview (but definitely wouldn't be slow to serve to end users). These are ~ 10mb notebooks so this might be close to as good as it gets, but I'll do some more digging to see what's accounting for the time and whether we can do anything better.
