### ISSUE TITLE
`<?foo?>` in the yaml footer breaks the parser

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#8575]
Create a website project and replace `_quarto.yml` with:

````
project:
  type: website

website:
  page-footer:
    left: "<?lua.year?> Brand"
````

That produces the following output on index.html:

<img width="649" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/97daed17-cc3e-4891-9439-51e99792ed73">

The broken fence div comes from a badly parsed navigation envelope, as evidenced by our filter trace: 

```
  - t: "Div"
    attr: "('quarto-navigation-envelope', ['hidden'], [])"
    content:
      - t: "Para"
        content:
          - t: "Span"
            attr: "('', ['hidden'], ['render-id,quarto-int-sidebar-title'])"
            content: "Issue-8571"
          - ""
          - t: "Span"
            attr: "('', ['hidden'], ['render-id,quarto-int-navbar-title'])"
            content: "Issue-8571"
      - t: "Para"
        content:
          - ":::{.hidden render-id="
          - t: "Quoted"
            content: "\"footer-left"
          - "}"
          - t: "RawInline"
            format: "html"
            text: "<?lua.year?>"
          - " Brand"
  - t: "Para"
    content: ":::"
```

**Comment by cscheid** [comment]
This parsing is coming directly from Pandoc:

```
$ quarto pandoc -f markdown -t native
:::{.hidden render-id="footer-left"}
<?lua.year?> Brand
:::
^D
[ Para
    [ Str ":::{.hidden"
    , Space
    , Str "render-id="
    , Quoted DoubleQuote [ Str "footer-left" ]
    , Str "}"
    , SoftBreak
    , RawInline (Format "html") "<?lua.year?>"
    , Space
    , Str "Brand"
    , SoftBreak
    , Str ":::"
    ]
]
```

I think the issue here is that `<?foo?>` is something that Pandoc really doesn't like to see. Your custom filter appears to be expecting a RawInline block containing that text. It's a lot safer to write that explicitly: `` `<?foo?>`{=html} ``

Although this is technically a regression, but it's a change in Pandoc behavior that we don't control, using syntax that we don't endorse (because `<?foo?>` is not valid HTML). You will have to fix that on your own code.

The following syntax is accepted by Pandoc:

````
$ quarto pandoc -f markdown -t native
:::{.hidden render-id="footer-left"}
`<?lua.year?>`{=html} Brand
:::

[ Div
    ( "" , [ "hidden" ] , [ ( "render-id" , "footer-left" ) ] )
    [ Para
        [ RawInline (Format "html") "<?lua.year?>"
        , Space
        , Str "Brand"
        ]
    ]
]
````

So you should change your `_quarto.yml` file to:

````
project:
  type: website

website:
  page-footer:
    left: "`<?lua.year?>`{=html} Brand"
    right: "Published with [Quarto](https://quarto.org/) v`<?quarto.version?>`{=html}"

format: html

filters:
  - custom.lua
````

And you'll then see this:

<img width="754" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/4aa86b5d-7af8-4af6-b0c2-15645f27b3fd">
