### ISSUE TITLE
raw HTML with tables incurs quarto processing

### ISSUE THREAD

**Issue by daslu** [quarto-dev/quarto-cli#8582]
### Bug description

I ran across a situation, where text indentation seems to be broken by the content of raw HTML.

Trying to make the example as small as possible, I reached the following qmd example.

### Steps to reproduce

````qmd
### A
```{=html}
<div>
  <table></table>
  <h3></h3>
  <table>
    <tbody>
      <tr></tr>
    </tbody>
  </table>
</div>
```
1
````

### Expected behavior

Usually, the "A" and the "1" would have the same indentation.

### Actual behavior

On rendering, the resulting HTML looks as follows:
![image](https://github.com/quarto-dev/quarto-cli/assets/5673102/1e3ba293-fba8-48d0-b0cf-3524c0fee3b9)

You see, the "1" text is no longer indented.

### Your environment

Ubuntu 22.04.
Quarto 1.4.549.
Edited with Emacs and ran `quarto preview` of the qmd file from the linux shell.

### Quarto check output

```bash
quarto check
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/daslu/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /workspace/anaconda3/bin/python
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

R scripting front-end version 4.1.2 (2021-11-01)
[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/


```

**Comment by mcanouil** [comment]
There is no bugs here.
You are making a single paragraph since you did not add empty lines.
Headers and code blocks/cells should be surrounded by empty lines.

**Comment by cscheid** [comment]
I think this is happening because of Quarto's [HTML table parsing](https://quarto.org/docs/prerelease/1.4/ast.html#finer-control-over-table-processing). Try adding `html-table-processing: none` to your YAML front matter.

**Comment by mcanouil** [comment]
The HTML produced:

```html
<main class="content" id="quarto-document-content">




<section id="a" class="level3">
<h3 class="anchored" data-anchor-id="a">A</h3>
<div>
<div>
  
<table data-quarto-postprocess="true">
</table>
<section id="raw-header" class="level3">
<h3 class="anchored" data-anchor-id="raw-header">Raw header</h3>
<table data-quarto-postprocess="true" class="table">
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>3</td>
<td>4</td>
</tr>
</tbody>
</table>

</section></div>
</div></section>
</main></div>
<p>1</p>
```

The issue is the table when not empty which triggers Quarto table processing.
Disabling the processing in the code solves the issue:
<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr>
<td>

````qmd
### A

```{=html}
<div>
  <table data-quarto-disable-processing="true"></table>
  <h3>Raw header</h3>
  <table data-quarto-disable-processing="true">
    <tbody>
      <tr>
        <td>1</td>
        <td>2</td>
      </tr>
      <tr>
        <td>3</td>
        <td>4</td>
      </tr>
    </tbody>
  </table>
</div>
```

1
````

</td>
<td>
<img width="306" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/a497bf17-8834-49b1-840e-bed3700607b5">
</td>
</tr>
</table>

**Comment by cscheid** [comment]
So this isn't a bug, it's intended (although perhaps obscure) behavior. I'm not quite sure how we can make it clearer what's going on. I'm going to leave this open as an enhancement ticket, but I don't have anything actionable at the moment.

**Comment by daslu** [comment]
> `html-table-processing: none`

This works beautifully.

Many thanks for your kind & quick help.

**Comment by daslu** [comment]
Many thanks for your kind & quick help.

**Comment by RegalPlatypus** [comment]
> I think this is happening because of Quarto's [HTML table parsing](https://quarto.org/docs/prerelease/1.4/ast.html#finer-control-over-table-processing). Try adding `html-table-processing: none` to your YAML front matter.

Passing you my thanks as well! After updating to the latest Quarto version all my {gt} tables started aligning right. This addition to the YAML fixed the issue.

**Comment by cscheid** [comment]
This is actually a bug.

Specifically, the problem is that `<h3>` element is getting parsed by Pandoc into a section.

Then, this section is getting converted into a Pandoc section which is bringing in the closing `</div>` part of the rawblock, causing our HTML to be invalid, and the document to be misrendered.

**Comment by cscheid** [comment]
The bad .html we generate here is this:

```
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">hello</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="a" class="level3">
<h3 class="anchored" data-anchor-id="a">A</h3>
<div>
<div>
  
<table data-quarto-postprocess="true">
</table>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<table data-quarto-postprocess="true">
<tbody>
<tr class="header">
</tr>

</tbody>
</table>

</section></div>
</div></section>
</main></div>
<p>1</p>
```

Note the mess we made out of the matching tags.

**Comment by cscheid** [comment]
Looking at our trace output, the bug is actually that we are parsing the interstitial header element between the two tables:

```
  - op: "add"
    path: "/blocks/1/content"
    value:
      - t: "RawBlock"
        format: "html"
        text: "<div>\n  "
      - t: "RawBlock"
        format: "html"
        text: "<table data-quarto-postprocess=\"true\">"
      - t: "RawBlock"
        format: "html"
        text: "</table>"
      - t: "Header"
        level: 3
        attr: "('section', [], [])"
        content: []
      - t: "Table"
        attr: "('', [], ['quarto-postprocess,true'])"
        caption:
          - null
          - []
        colspecs: []
        head:
          t: "TableHead"
          attr: "('', [], [])"
          rows: []
        body:
          - t: "TableBody"
            row_head_columns: 0
            attr: "('', [], [])"
            intermediate_head:
              - t: "TableRow"
                attr: "('', [], [])"
                cells: []
            body: []
        foot:
          t: "TableFoot"
          attr: "('', [], [])"
          rows: []
      - t: "RawBlock"
        format: "html"
        text: "\n</div>"
```

Notice how Pandoc interprets the heading as a section marker, and then the closing `</div>` tag is misplaced.
