### ISSUE TITLE
BibTeX file not found in resource path

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#861]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/853

<div type='discussions-op-text'>

<sup>Originally posted by **rgaiacs** May 12, 2022</sup>
When I run `quarto render --execute --to html --output-dir public`, I get

```
[17/17] references.qmd

Starting conda-env-first-carpal-py kernel...(Notebook read from cache)


File ../references.bib not found in resource path
```

I have `references.bib` in my project. What can be causing this error?

# Content of `references.qmd`

``` 
---
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.13.8
  kernelspec:
    display_name: 'Python [conda env:first-carpal]'
    language: python
    name: conda-env-first-carpal-py
---

# References {.unnumbered}

::: {#refs}
:::
```

# Content of `_quarto.yml`

```
project:
  type: book

execute:
  cache: true
  echo: false
  output: false
  eval: true

book:
  title: "AI for First Carpal Bone Detection"
  author: "Raniere Silva"
  chapters:
    - index.qmd
    - intro.qmd
    - data.qmd
    - part: classification/index.qmd
      chapters:
      - classification/models.qmd
      - classification/data-annotation.qmd
      - classification/data-preparation-fastai.qmd
      - classification/data-augmentation.qmd
      - classification/training-fastai.qmd
    - part: detection/index.qmd
      chapters:
      - detection/models.qmd
      - detection/data-annotation.qmd
      - detection/data-preparation-fastai.qmd
      - detection/data-augmentation.qmd
      - detection/training-fastai.qmd
    - faq.qmd
    - references.qmd
  repo-url: https://gitlab.com/raniere-phd/ai-for-first-carpal-bone-detection
  repo-actions:
    - edit
    - source
    - issue

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

# Other information

No error when I reduce `_quarto.yml` to

```
project:
  type: book

execute:
  cache: true
  echo: false
  output: false
  eval: true

book:
  title: "AI for First Carpal Bone Detection"
  author: "Raniere Silva"
  chapters:
    - index.qmd
    - part: detection/index.qmd
      chapters:
      - detection/models.qmd
    - faq.qmd
    - references.qmd
  repo-url: https://gitlab.com/raniere-phd/ai-for-first-carpal-bone-detection
  repo-actions:
    - edit
    - source
    - issue

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```</div>
