### ISSUE TITLE
[FR] Make 'Others formats" field configurable (e.g `format: typst` will lead to Typst format and not just PDF)

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#8610]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8596

<div type='discussions-op-text'>

<sup>Originally posted by **fredguth** February  4, 2024</sup>
### Description

When you generate a manuscript that besides html also generate a typst built pdf, in "Other Formats" it shows "Typst".
![image](https://github.com/quarto-dev/quarto-cli/assets/392879/b1667ff5-6d64-44a9-9bc5-7e1ab9f30a84)

Would it be possible to just call it "PDF"?</div>

**Comment by cscheid** [comment]
(I think this is a duplicate of a different request to configure this "other format" more generally)

**Comment by mcanouil** [comment]
FYI:
- https://github.com/quarto-dev/quarto-cli/issues/7459

```
format-links:
  - html
  - format: typst
    text: PDF
    icon: pdf
  - title: Other Link
     href: https://www.charlesteague.com/
     icon: thumbs-up
```
