### ISSUE TITLE
[Question/Feature Request] Parameterised notebooks within projects

### ISSUE THREAD

**Issue by p-gw** [quarto-dev/quarto-cli#864]
Hi everyone, 

I have a question regarding a somewhat advanced use case:
If I have created a project that contains a simple notebook (e.g. `introduction.qmd`) and a parameterised notebook (e.g. `report_by_state.qmd`) whose output is required multiple times with different parameter values is it possible to render the whole project using `quarto render`? 

Say I want to render `introduction.qmd` and `report_by_state.qmd` for state `1`, `2`, and `3`. If using html outputs this should result in

- `introduction.html`
- `report_state_1.html`
- `report_state_2.html`
- `report_state_3.html`

It is of course possible to write a shell script to render reports in this way, but I think it would be nice if there was something like this

```yaml
project:
    render:
        - introduction.qmd
        - input: report_by_state.qmd
          params: 
              state: 1
          output: report_state_1.html
        - input: report_by_state.qmd
          params: 
              state: 2
          output: report_state_2.html
        - input: report_by_state.qmd
          params: 
              state: 3
          output: report_state_3.html
```

and being able to render everything with a single `quarto render`.

Except writing a custom shell script, is there currently a method which makes it possible to achieve something like this?
