### ISSUE TITLE
Custom reference-doc renders corrupted Powerpoint file

### ISSUE THREAD

**Issue by polmonroig** [quarto-dev/quarto-cli#867]
### Steps to reproduce
1. Generate reference powerpoint template using the documentation command (https://quarto.org/docs/presentations/powerpoint.html)

`quarto pandoc -o template.pptx --print-default-data-file reference.pptx `

2. Setting the reference doc in qmd file 

```
---
title: "Quarto Basics"
format: 
  pptx: 
    reference-doc: template.pptx
jupyter: python3
---
```

3. Render QMD file => powerpoint works

4. Then edit the template.pptx file within PowerPoint as desired, in the most minimal way (changing the theme or the master slides) 

5. Rendering QMD file and opening the file

![image](https://user-images.githubusercontent.com/43550053/168272108-54e2bbc0-d089-4f6c-affa-d31ae7ad9729.png)

6. Clicking repair 

![image](https://user-images.githubusercontent.com/43550053/168272343-9c3fb6eb-2b7f-488e-b49d-8c9f9fd812aa.png)
