### ISSUE TITLE
shortcode meta author fails in any file other than index.qmd when rendering a book to html, works everywhere for PDF

### ISSUE THREAD

**Issue by yadbor** [quarto-dev/quarto-cli#8675]
### Bug description

When attempting to render a book project, the shortcode
{{< meta author >}}
only works in index.qmd when rendering to HTML.

If used in any other file it renders as **?meta:author**

During rendering quarto produces a warning message for every use of the shortcode:
WARNING (/Applications/quarto/share/filters/main.lua:15677) Unknown meta key author specified in a metadata Shortcode.

### Steps to reproduce

In RStudio create a new Project of type Quarto Book

Add the shortcode 
{{< meta author >}}

somewhere in the text of in index.qmd and in any other file (I used intro.qmd)

Save and Render Book to All Formats

### Expected behavior

The shortcode should render correctly, no matter which .qmd file it is used in.
Rendering should also be (broadly) consistent between output formats.

### Actual behavior

The shortcode {{< meta author >}} in any file except index.qmd renders to **?meta:author** when rendering to HTML
The shortcode works correctly in index.qmd for HTML and PDF, and in any file when rendering to PDF

### Your environment

- IDE: RStudio 2023.12.1+402 
- OS: MacOS Sonoma 14.2.1 (23C71)
- Hardware: Apple M1 Pro, 14 inch 2021

### Quarto check output

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/yadbor/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

**Comment by dragonstyle** [comment]
This is currently by design as the author field is expected to be used to create the title block (and in addition the author field can accept arrays and other complex structures to represent multiple authors and more author meta data). 

I think a good workaround for the time being would be just to use a different field name in your metadata, designed to be displayed within pages, for example:

```
project:
  type: book

book:
  title: "B"
  author: 
    - name: "Norah Jones"
      email: foo@gmail.com
      orcid: 23423l4k23nj4lk23j4l2
    - "Charles Teague"
  date: "2/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
author-display: Charles T
```




```
# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

{{< meta author-display >}}
```

**Comment by yadbor** [comment]
Thank you for the prompt and informative answer. I am indeed using the more complex features of the author field.

Could the documentation be fixed to reflect this behaviour, to avoid other people getting caught and wasting your time as I did? Or is this so unusual & specific it would just clutter the documentation for most people?

I have also just found that quarto yaml supports using aliases (or references), so this works & avoids the risk of getting the two author names out of sync:
```
project:
  type: book

book:
  title: "B"
  author: 
    - name: &a "Norah Jones"
      email: foo@gmail.com
      orcid: 23423l4k23nj4lk23j4l2
    - "Charles Teague"
  date: "2/11/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
author-display: *a
```
```
# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

{{< meta author-display >}}
```

The shortcode in this case will render to Norah Jones.

I don't know if this behaviour will be supported in future, as it doesn't appears to be referenced by the quarto documentantion. I may have missed it, of course.
