### ISSUE TITLE
Language setting not working for book

### ISSUE THREAD

**Issue by CommunyAS** [quarto-dev/quarto-cli#8744]
### Bug description

I tried setting the main language of a Quarto book with the `lang` option in the **_quarto.yml** as described in the [Document Language Guide](https://quarto.org/docs/authoring/language.html#lang-option) or [DocBook Options](https://quarto.org/docs/reference/formats/docbook.html#language), but it results in error messages when rendering to html or pdf - here is the error message for a sample book:
> Error: Project _quarto.yml validation failed.
>
> In file _quarto.yml
> (line 8, columns 3--7) property name lang is invalid
> 7:   date: "2/15/2024"
> 8:   lang: fr
 >    ~~~~~
>ℹ The error happened in location book:lang.

I found several issue reports on this problem, all in the end rendering books with the `lang` option correctly.

Is the `lang` option not supported in Quarto books anymore or is this a bug?
If not, what do I have to change in the **_quarto.yml** file?

### Your environment

- IDE: RStudion Version 2023.12.1+402
- OS: macOS Sonoma 14.2.1

**Comment by mcanouil** [comment]
Please properly fill the template with all the information requested.
We do need to know the `quarto check` output and to have a **self-contained "working" (reproducible)** example.

We can't help you if you don't provide us with the means to.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

![A placeholder image](https://placehold.co/600x400.png)

The end.
````
`````

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by CommunyAS** [comment]
For demonstration you can simply use the standard Quarto book files that are created if you start a new Quarto book project with RStudio. Here are those files: [Sample_Book.zip](https://github.com/quarto-dev/quarto-cli/files/14297795/Sample_Book.zip)


Just insert the `lang` option in the **_quarto.yml** file like in the following code:

```
project:
  type: book

book:
  title: "Sample_Book"
  author: "Norah Jones"
  date: "2/15/2024"
  lang: en                              # code line for language settings added to the original file
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
```

Rendering the book (i.e. any qmd file listed under chapters) results in the following error code:

```
==> quarto preview index.qmd --to html --no-watch-inputs --no-browse

ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 8, columns 3--7) property name lang is invalid
7:   date: "2/15/2024"
8:   lang: en
    ~~~~~
9:   chapters:
ℹ The error happened in location book:lang.


Error: Project _quarto.yml validation failed.

In file _quarto.yml
(line 8, columns 3--7) property name lang is invalid
7:   date: "2/15/2024"
8:   lang: en
    ~~~~~
9:   chapters:
ℹ The error happened in location book:lang.

    at readAndValidateYamlFromFile (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:42120:15)
    at async file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:82873:26
    at async projectContext (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:82725:26)
    at async Command.fn (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:103701:25)
    at async Command.execute (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:127545:5)
    at async file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:127563:9
```

The output of `quarto check` run in the terminal is:

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

I use the latest 'official' built of RStudio that you can download from the Posit website:
IDE: RStudion Version 2023.12.1+402
OS: macOS Sonoma 14.2.1

Hope this helps, please let me know if you need further information.

**Comment by dragonstyle** [comment]
The most likely cause of this is that you're placing the `lang` option under `book` like so:

```yaml
book:
  title: "Book"
  author: "Norah Jones"
  date: "2/15/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  lang: fr

bibliography: references.bib
```

this isn't correct as `lang` isn't an option specific to books, it is a global option. It is most common to place it at the root level of the project, like:

```yaml
book:
  title: "Book"
  author: "Norah Jones"
  date: "2/15/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
lang: fr
```
HTH!
