### ISSUE TITLE
About page templates `solana` and `broadside` don't respect order of content

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#8750]
### Bug description

When using the about page templates `solana` and `broadside` with partial page content, content that occurs after the identifying div appears above it when rendered.

### Steps to reproduce

In a default website project:
```bash
quarto create project website test
```

Edit `about.qmd` to:
````
---
title: "Finley Malloc"
about:
  id: hero-heading
  template: broadside
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com
---

:::{#hero-heading}

Content for about template.

:::

## Content below about content div
````

### Expected behavior

The heading "Content below about content div" should appear after the templated about contents.

### Actual behavior

The heading "Content below about content div" appears before the templated about contents.

<img width="1408" alt="Screenshot 2024-02-16 at 10 44 34 AM" src="https://github.com/quarto-dev/quarto-cli/assets/25964/4ef24835-d157-4561-a2d6-201fd1fb78b1">

### Quarto check output

```bash
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/wickhamc/Documents/posit/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.09
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/wickhamc/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.0
      Path: /usr/local/bin/python3
      Jupyter: 5.5.0
      Kernels: ir, julia-1.9, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```
