### ISSUE TITLE
`fig-align` code cell option not supported in Typst

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8767]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/8766

<div type='discussions-op-text'>

<sup>Originally posted by **psads-git** February 17, 2024</sup>
Please, consider the following `quarto` document. The figure is not being centered. Am I doing something wrong? Thanks!

````
---
format: typst
papersize: a4
fontsize: 12pt
margin:
  x: 2.54cm
  y: 2.54cm
jupyter: python3
---

```{python}
#|echo: false
#|fig-align: center

import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

fig.savefig("test.png")
plt.show()
```
````</div>

**Comment by cderv** [comment]
> changed in pandoc 3.1.9

Nope - we added `fig-align` after and more recently 
* https://github.com/quarto-dev/quarto-cli/pull/7577

So this is not fully working.

**Comment by gordonwoodhull** [comment]
As with the Typst table centering issue #8797, we need to either not add the two `#block`s, or apply the centering at the top block associated with the figure.

I'm looking at these, any opinions are welcome.

**Comment by cscheid** [comment]
> One thing I have to sort out is that centering already seems to be the default, but our #blocks are causing them to align left.

Right. And centering, I think, is a feature we _would_ like to be consistent across formats (since it is for PDF and HTML right now).

The Pandoc AST shows this at the end of the processing:

````
  - t: "Div"
    attr: "('', ['cell'], ['execution_count,1'])"
    content:
      - t: "Div"
        attr: "('', ['cell-output', 'cell-output-display'], [])"
        content:
          - t: "Plain"
            content:
              - t: "RawInline"
                format: "typst"
                text: "#align(center)["
          - t: "Plain"
            content:
              - t: "Image"
                attr: "('', [], [])"
                caption: []
                src: "8767_files/figure-typst/cell-2-output-1.svg"
                title: ""
          - t: "Plain"
            content:
              - t: "RawInline"
                format: "typst"
                text: "]"
````

Each of those divs is becoming a block, and there's one block too many. The question is which we drop and why.
