### ISSUE TITLE
Citedrive bibliography not rendering in Quarto book html

### ISSUE THREAD

**Issue by loreabad6** [quarto-dev/quarto-cli#8814]
### Bug description

CiteDrive generates a URL that can normally be used within Quarto documents. But for HTML books, the reference.qmd section won't render. This works fine with PDF. Also only rendering `index.qmd` formats the inline citations correctly.

### Steps to reproduce

1. Create a New Project, Quarto Book in RStudio.
2. Use the following `_quarto.yml` file:
```
project:
  type: book

book:
  title: "test"
  author: "Norah Jones"
  date: "21/02/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: 
    - references.bib
    - "https://api.citedrive.com/bib/fe951e8e-8d9a-4b1e-9242-7a5591d4ca2b/references.bib?x=eyJpZCI6ICJmZTk1MWU4ZS04ZDlhLTRiMWUtOTI0Mi03YTU1OTFkNGNhMmIiLCAidXNlciI6ICIyNTY4IiwgInNpZ25hdHVyZSI6ICJkMWUyZWQ5NjE0MDdjOGVmNTIxMzEwMmE5ZTYwM2E5YzI3ZGY1ODc0YWJhNjJkZjU4YzU4ZmZiZjVkYTFjNjg0In0=/bibliography.bib"

format:
  html:
    theme: cosmo
  pdf: default
```
3. Contents of `index.qmd`:
```
# Preface {.unnumbered}

@Harvey_2006 

[@Goodchild_2019]
```

### Expected behavior

Bibliography from CiteDrives renders normally

### Actual behavior

Rendering the HTML book fails with the error:

```
Could not fetch https:/api.citedrive.com/bib/xxx/bibliography.bib" "URL must be absolute"
```

### Your environment

R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)
RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-28) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36

### Quarto check output

```
Quarto 1.4.550
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.550
      Path: C:\Users\b1066081\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2023.04
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\b1066081\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: C:/Users/b1066081/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: 5.3.1
      Kernels: python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-4.3.1
      LibPaths:
        - C:/Users/b1066081/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```
