### ISSUE TITLE
Links in qmd with index.html are have the file name stripped when served leading to 404

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#8837]
from @AshleyHenry15 @jthomasmock

* Create a website 
* `_quarto.yml`
````yaml
project:
  type: website

website:
  title: "Reprex for index.html"
  navbar:
    left:
      - href: index.qmd
        text: Home
````
* `index.qmd`
````
 ---
format: 
  html:
    code-tools: true
---

<https://docs.databricks.com/en/dev-tools/auth/index.html#databricks-client-unified-authentication>

[https://docs.databricks.com/en/dev-tools/auth/index.html#databricks-client-unified-authentication](https://docs.databricks.com/en/dev-tools/auth/index.html#databricks-client-unified-authentication)
````

When rendered and then served, the `index.html`  is stripped and links become 
````
https://docs.databricks.com/en/dev-tools/auth/#databricks-client-unified-authentication
````

which leads to 404
