### ISSUE TITLE
Markdown breaks in sidebar child nav items

### ISSUE THREAD

**Issue by gregswinehart** [quarto-dev/quarto-cli#8858]
### Bug description

Hi there, 
You all were nice enough to enable markdown in the sidebar, which allowed me to sneak in images.  Just wanted to say thank you for that!  Something I've noticed is when those images are used in child nav items, the markdown breaks in the breadcrumb.  Here is an example of the markdown working in a top level sidebar nav item:

<img width="1211" alt="Screenshot 2024-02-22 at 3 20 40 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5993637/bea36118-39b0-407e-9194-a18962144488">

And here is what shows when markdown is used to add an image, and the breadcrumb has multiple levels: 

<img width="1211" alt="Screenshot 2024-02-22 at 3 24 21 PM" src="https://github.com/quarto-dev/quarto-cli/assets/5993637/893170bb-d4e4-4d3d-8877-9436fdfd9d12">

### Steps to reproduce

In _quarto.yml, I have this for a sidebar

```
- id: getstarted-r
      collapse-level: 1
      contents:
        - text: "__GET STARTED__"
          href: /r/getstarted/
        - section: "![](/images/1-square-fill.svg){.sidebar-icon} Shiny Basics" 
          contents:
            - r/getstarted/shiny-basics/lesson1/index.qmd
        - section: "![](/images/2-square-fill.svg){.sidebar-icon} Build an App"
          contents:
            - section: "Hello Shiny!"
              contents:
              - r/getstarted/build-an-app/hello-shiny/getting-started.qmd
```
            
The breadcrumb doesn't appear to like jumping two levels like that.    
              
              
              

### Expected behavior

I'd like the markdown to be rendered

### Actual behavior

The markdown code shows, unrendered.

### Quarto check output

Quarto 1.4.542
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.542
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.7
      Path: /opt/homebrew/opt/python@3.11/bin/python3.11
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
