### ISSUE TITLE
Font awesome won't load for me in the HTML of a book (self-contained: true)

### ISSUE THREAD

**Issue by fuhrmanator** [quarto-dev/quarto-cli#889]
Along the lines of #859 I tried the following in a Book project:

```yaml
format:
  html:
    header-includes: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
            rel="stylesheet"/>
    self-contained: true
```

Sadly, when I preview the web site, the link is never inserted (and the icon won't render). 

If I turn off `self-contained` the icons are visible, but my other diagrams produced by a filter are then broken. Is it possible to have `self-contained` and `head-includes` working together?
