### ISSUE TITLE
reveal presentation: footnotes in wrong position, using vertical slides

### ISSUE THREAD

**Issue by aborruso** [quarto-dev/quarto-cli#890]
Hi,
as you can see below the footnote is above the text.

The code of that slide is

~~~
## CSV^[only a test] {.center}

```{.txt}
nome,note
"Marco,Bianchi","Lorem

Ipsum"
Ciccio Bombo,Lorem
"Bianca ""Stella"" Balti",Ipsum
```

- [csvkit](https://csvkit.readthedocs.io/)
- 💘 [Miller](https://miller.readthedocs.io/en/latest/)
- 💘 [VisiData](https://ondata.github.io/guidaVisiData/)
~~~

My settings are

```
title: "My title"
#subtitle: ""
format:
  revealjs:
    slide-number: true
    preview-links: auto
    auto-stretch: false
    navigation-mode: vertical
    center-title-slide: false
    lang: it
    hash-type: number
    self-contained: false
resources:
  - demo.pdf
```

Thank you

![image](https://user-images.githubusercontent.com/30607/168534156-5129b8df-8049-4241-a960-dbcbec6d1923.png)
