### ISSUE TITLE
Trailing ::: at bottom of rendered html pages depending on quoting in `page-footer`

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#8932]
_Originaly discussed in https://github.com/quarto-dev/quarto-cli/discussions/8931 

* Create a website
	````bash
	quarto create website test-quarto-website
	````

* Add the following to `_quarto.yml` under `website`
	````yaml
	  page-footer:
	    center:
	      - text: 'Project "created"'
	````
  
* `quarto preview`

This will look like this: 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/b28b6731-de9c-4a54-b7b3-db3575b06ade)

Now change the quoting of the YAML field

````yaml
  page-footer:
    center:
      - text: "Project 'created'"
````

The `:::` will disappear

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/c9f71fe2-251d-445d-8986-9ef5ce267f81)

It happens in 1.4 but not in 1.3

So probably something with

* How we process page footer exactly ? 
* The fact that `key: 'value'` is not the same as `key: "value"` in YAML ([double quotes](https://yaml.org/spec/1.2.2/#731-double-quoted-style) and [single quotes](https://yaml.org/spec/1.2.2/#732-single-quoted-style)  have different escaping behavior)

**Comment by cderv** [comment]
I just noticed that  this works. 
````yaml
website:
  page-footer:
    center: 'Project "created"'
````

but not 
````yaml
website:
  page-footer:
    center:
       - text: 'Project "created"'
````

Related in a way 
* https://github.com/quarto-dev/quarto-cli/issues/8575

**Comment by cderv** [comment]
Ok so #8575 gave me some hints, and this happens because we do create this hidden div
````markdown
:::{.hidden render-id="footer-center-Project "created""}
Project "created"
:::
````

For the rendering, and the `render-id` attribute is not valid. The double quotes are not escaped 

````powershell
> quarto pandoc -t native -f markdown
:::{.hidden render-id="footer-center-Project "created""}
Project "created"
:::
^Z
[ Para
    [ Str ":::{.hidden"
    , Space
    , Str "render-id="
    , Quoted DoubleQuote [ Str "footer-center-Project" ]
    , Str "created\8221"
    , Quoted DoubleQuote [ Str "}" , SoftBreak , Str "Project" ]
    , Str "created\8221"
    , SoftBreak
    , Str ":::"
    ]
]
````

**Comment by retostauffer** [comment]
Experienced the same when using double-quotes to add information to the footer (adding some custom HTML). As soon as it contains `"` the `<p>:::</p>` artifact is added at the end of each `main.contaner` as described above.

## Software/system

Tested with quarto release version `1.4.554` as well as with pre-release candidates 1.5.37` and `1.5.39`, all showing the same behavior (Ubuntu linux).

## Reproducing the error

Can easily be reproduced by adding the following to the footer (left, right, or center):

```
website:
  page-footer: 
    center:
      - text: '<a href=\"www.google.com\">foo</a>'
```
Same when using not escaping the double quotes (`"` instead of `\"`).

## Fix (changing quotes)

As outlined above, changing the quotes resolves the issue; artifacts no longer created.

```
      - text: "<a href='www.google.com'>foo</a>" 
```
