### ISSUE TITLE
fig cap location not changing

### ISSUE THREAD

**Issue by vrbiki** [quarto-dev/quarto-cli#8938]
### Bug description

When I try to place the figure caption at the top of my figure it still defaults to the bottom. 

### Steps to reproduce

---
title: "test fig cap"
format:
  revealjs:
    fig-cap-location: top
editor: visual
---

new slide

## Slide

```{r}
#| fig-cap: "awelrkj"
#| fig-cap-location: top
plot(1:10)
```

### Expected behavior

By adding `fig-cap-location: top` to the code chunk (I also added it to the YAML in case the global declaration would help) I would have expected the caption to appear above the rendered plot. 

### Actual behavior

Instead it appears below.
<img width="1701" alt="Screenshot 2024-02-29 at 10 59 37 AM" src="https://github.com/quarto-dev/quarto-cli/assets/12956294/6800549b-1238-4f65-a55c-b634f80f6139">

### Your environment

- IDE RStudio Version 2023.12.1+402 (2023.12.1+402)
- MacOS 14.3.1 (23D60)

### Quarto check output

Quarto 1.4.549

**Comment by mcanouil** [comment]
Thanks for the report!

Could you properly format your post using code blocks for code and terminal outputs? Thanks.
If your code contains code blocks, you need to enclose it using more backticks, *i.e.*, usually four ` ```` `.



---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by cscheid** [comment]
`fig-cap-location` is currently only picked up for crossreferenceable figures. Adding `label: fig-youridhere` should solve the problem in the meantime.

**Comment by vrbiki** [comment]
Adding a label does not seem to do the trick

````
---
title: "test fig cap"
format:
  revealjs:
    fig-cap-location: top
editor: visual
---

## Slide

```{r}
#| fig-cap: "This caption should appear on top but doesn't"
#| fig-cap-location: top
#| label: fig-whatever

plot(1:10)
```

Does reference @fig-whatever help?
````

<img width="1621" alt="Screenshot 2024-02-29 at 11 52 05 AM" src="https://github.com/quarto-dev/quarto-cli/assets/12956294/a6df611a-eb3d-4815-b643-7595ad9bf65b">

**Comment by cscheid** [comment]
Oh no, I'm so sorry! That's definitely a bug on our side (I've reproed and it's specific to revealjs).

**Comment by cscheid** [comment]
@cderv I think the bug here is that the revealjs post-processor doesn't respect the ordering between `figcaption` and the content inside the figure. I say that because the output we generate from Pandoc _does_ put the caption on top:

````
          - t: "Div"
            attr: "('fig-whatever', ['quarto-figure', 'quarto-figure-center', 'quarto-float'], ['cap-location,top'])"
            content:
              - t: "RawBlock"
                format: "html"
                text: "<figure class=\"quarto-float quarto-float-fig\">"
              - t: "RawBlock"
                format: "html"
                text: "<figcaption class=\"quarto-float-caption-top quarto-float-caption quarto-float-fig\" id=\"fig-whatever-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca\">"
              - t: "Plain"
                content: "FigureÂ 1: This caption should appear on top but doesnât"
              - t: "RawBlock"
                format: "html"
                text: "</figcaption>"
              - t: "Div"
                attr: "('', [], ['aria-describedby,fig-whatever-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca'])"
                content:
                  - t: "Plain"
                    content:
                      - t: "Image"
                        attr: "('', [], ['width,960'])"
                        caption: []
                        src: "8938_files/figure-revealjs/fig-whatever-1.png"
                        title: ""
              - t: "RawBlock"
                format: "html"
                text: "</figure>"
````

It seems like it should be easy to fix because we're still emitting `cap-location: top` on the div.

**Comment by filipemsc** [comment]
Any updates on this?

**Comment by mcanouil** [comment]
@filipemsc m All updates are in the thread.

**Comment by cderv** [comment]
This is a bug in the [auto stretch](https://quarto.org/docs/presentations/revealjs/advanced.html#stretch) processing that does not correctly account for the caption placement. 

The current workaround is opting out of auto-stretch for now. 
````
format:
  revealjs:
    auto-stretch: false
    fig-cap-location: top
````
