### ISSUE TITLE
Support ignore certain Rmd or qmd file for quarto website

### ISSUE THREAD

**Issue by psychelzh** [quarto-dev/quarto-cli#898]
Currently all Rmd or qmd files will be rendered when previewing site. There seems no option to ignore certain file (e.g., rmd child) or folder. It will be very useful to have such option.

**Comment by cscheid** [comment]
By default, quarto ignores files and folders that start with underscores (`_`).

**Comment by jjallaire** [comment]
You can do arbitrary ignores by using a ! prefix on the render target list (https://quarto.org/docs/projects/quarto-projects.html#render-targets):

```yaml
project:
    render: 
        - *.qmd
        - ! ignored.qmd
        - ! ignored-dir/
```
