### ISSUE TITLE
Hybrid Navigation for Websites does not work when using sidebar groups with titles

### ISSUE THREAD

**Issue by micah-svenson** [quarto-dev/quarto-cli#9008]
### Bug description

Hybrid Navigation does not work at all when configuring `sidebar:` with one or more entries containing titles that match navbar entries.

However, I can manually give the sidebar an id and force it to show by adding the sidebar to the front matter of a given page.

### Steps to reproduce

1. Generate a default website project using the quarto cli. 
2. Edit the `_quarto.yml` as follows:
````qmd
project:
  type: website

website:
  title: "Hybrid Nav Test"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: about.qmd
        text: "About"
  sidebar:
    - title: "About"
      contents:
        - test.qmd
````
4. Add a new file called `test.qmd` with the following content.
````quarto
---
title: "Test"
---

This should show up in the side bar
````

### Expected behavior

The "Home" page should not have a sidebar entry

The "About" page should have a side bar entry called "Test"

### Actual behavior

Neither the "Home" or "About" page have a sidebar.

### Your environment

VSCode 1.85.2, Ubuntu 22.04

### Quarto check output

Note: I also tested on 1.4.551 with the same behavior.
```bash
Quarto 1.5.24
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.24
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.10
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/micahsvenson/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: 5.2.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by mcanouil** [comment]
I don't see any bugs.

For hybrid navigation, you need to match navbar and sidebar which is not the case of your example:

```yaml
      - file: about.qmd
        text: "About"
  sidebar:
    - title: "About"
      contents:
        - test.qmd
```

See <https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation>.

1. `quarto create project website mywebsite Demo`
2. Replace `_quarto.yml`:

````yml
project:
  type: website

website:
  title: "Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  sidebar:
    - title: Home
      contents:
        - index.qmd
    - title: About
      contents:
        - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
````
