### ISSUE TITLE
Nested sub-menus in top navigation throws `this menu does not support sub-menus`

### ISSUE THREAD

**Issue by mfisher87** [quarto-dev/quarto-cli#9015]
### Bug description

Only one level of sub-menus is supported in top navbar.

Created this issue based on [this discussion](https://github.com/quarto-dev/quarto-cli/discussions/6461) because it sounded like the current behavior is not the desired behavior, but I couldn't find a corresponding issue. I'm not sure "bug" is the appropriate classification here.

### Steps to reproduce

Copied from discussion:

```yaml
website:
  title: "Nested drop down menu"
  navbar:
    right:
      - text: "Menu Title"
        menu:
          - text: submenu
            menu:
              - text: "Submenu Title"
                href: whatever.qmd
          - text: "Item title"
            href: whatever.qmd
          - text: "Item title"
            href: whatever.qmd
```

### Expected behavior

A nested sub-menu element is rendered

### Actual behavior

`this menu does not support sub-menus`

### Your environment

Vim

Pop!_OS 22

### Quarto check output

```bash
$ quarto check
Quarto 1.4.550
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.58.3: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.550
      Path: /home/robatt/.local/share/miniconda3/envs/mfisher87.github.io/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/robatt/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.8 (Conda)
      Path: /home/robatt/.local/share/miniconda3/envs/mfisher87.github.io/bin/python
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```
