### ISSUE TITLE
Quarto book does not run same working dir for HTML or PDF

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9033]
- Create a project
````powershell
quarto create project book test-quarto-book --no-prompt
````

- Tweak content 
````bash
 cd .\test-quarto-book\
mkdir chapters
mv intro.qmd .\chapters\
rm .\summary.qmd
rm .\references.qmd
````

- Modify config by adding a filter, and moving `intro.qmd` into `chapters`
````
project:
  type: book

book:
  title: "Test-quarto-book"
  author: "Norah Jones"
  date: "11/03/2024"
  chapters:
    - index.qmd
    - chapters/intro.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

filters: 
  - workdir.lua
````

- Add this Lua filter
````lua
Pandoc = function(doc)
  quarto.log.output("LUA_WD: "..pandoc.system.get_working_directory())
end
````

Now see the difference of context 

## For HTML

````
> quarto render --to html
[1/2] index.qmd
LUA_WD: C:\Users\chris\AppData\Local\Temp\quarto\test-quarto-book
[2/2] chapters\intro.qmd
LUA_WD: C:\Users\chris\AppData\Local\Temp\quarto\test-quarto-book\chapters

Output created: _book\index.html
````

## For PDF

````
> quarto render --to pdf
[1/2] index.qmd
[2/2] chapters\intro.qmd

pandoc
  to: latex
  output-file: index.tex
  standalone: true
  toc: true
  number-sections: true
  top-level-division: chapter
  pdf-engine: xelatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf

metadata
  crossref:
    chapters: true
  documentclass: scrreprt
  papersize: letter
  classoption:
    - DIV=11
    - numbers=noendperiod
  header-includes:
    - '\KOMAoption{captions}{tableheading}'
  block-headings: true
  bibliography:
    - references.bib
  title: Test-quarto-book
  author: Norah Jones
  date: 11/03/2024

LUA_WD: C:\Users\chris\AppData\Local\Temp\quarto\test-quarto-book

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode

running xelatex - 2
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode


Output created: _book\Test-quarto-book.pdf
````

You can see for PDF we use the Lua filters only once and not twice, with only the project root as workdir. 

## What is the impact ? 

Modify the project this way 
````
mv .\workdir.lua .\chapters\
````

Remove 
```
filters: 
  - workdir.lua
