### ISSUE TITLE
Book: Error crossreferencing custom object when tex template is used

### ISSUE THREAD

**Issue by pbousquets** [quarto-dev/quarto-cli#9034]
### Bug description

I'm writing a quarto book, where I need to add Supplementary Figures. I followed the steps from the tutorial, with my YAML having:

```
crossref:
  chapters: false
  custom:
    - kind: float
      key: sfig
      latex-env: suppfig
      reference-prefix: Figure S
      caption-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
```

I add my figure in the appendix:

```
::: {#sfig-modifs}
![](figures/supps/fig1.png)

My caption.

:::
```

And then I cite it with: 
``` 
Check  [@sfig-modifs].
```

### Expected behavior

It should cite the suppfig

### Actual behavior

ERROR: 
compilation failed- error
Undefined control sequence.
l.2124 (\quartosfigref
                      {sfig-modifs}). 

### Your environment

quarto 1.4.542

**Comment by cscheid** [comment]
We need a full file; I can't repro your simple case:

<img width="664" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/97a987f2-1cd2-4370-888c-bb33a21e7fb3">

````
---
crossref:
  chapters: false
  custom:
    - kind: float
      key: sfig
      latex-env: suppfig
      reference-prefix: Figure S
      caption-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
keep-tex: true
---


::: {#sfig-modifs}

![](https://placeholder.co/400/400.png)

My caption.

:::

See [@sfig-modifs].
````

**Comment by cscheid** [comment]
Ah, I think I know what this is. (This is why we ask for full repros, incidentally, and please try to provide them in the future) It has to be related to books specifically.

**Comment by cscheid** [comment]
Actually, I can't reproduce it in a book setting either. Did you add the crossref entries to the project metadata?

<img width="241" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/dfa7f115-db22-4c69-a57b-6edcece385ee">

**Comment by pbousquets** [comment]
Hi, thanks a lot for replying so quickly.

You're totally right. I should've shared a full file. I tried what you did and it worked indeed. My book is a bit complex, it has a large preamble to format the final PDF. Actually, I just found that providing a template tex file is what causes the issue:

I created a new book. I changed the yaml to:
```
project:
  type: book

book:
  title: "mybook"
  author: "Norah Jones"
  date: "3/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
crossref:
  chapters: false
  custom:
    - kind: float
      key: sfig
      latex-env: suppfig
      reference-prefix: Figure S
      caption-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    template: mytex.tex
```

And then, I added a minimal template (mytex.tex):

```
\documentclass[a4paper]{book}
\usepackage{bookmark}
\usepackage{framed}
\newenvironment{Shaded}{\begin{singlespace}\begin{snugshade}}{\end{snugshade}\end{singlespace}}

\begin{document}
$body$
\end{document}
```

I tried to use `sfig` in the index.qmd file:

```
# Preface {.unnumbered}

This is a Quarto book.

To learn more about Quarto books visit <https://quarto.org/docs/books>.

[@sfig-na]


::: {#sfig-na}
![aa](cover.png){fig-align="center"}
:::
```
I attached a zip file for this example book.
[aa.zip](https://github.com/quarto-dev/quarto-cli/files/14570120/aa.zip)
