### ISSUE TITLE
dashboard: `favicon` support

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#9126]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/9118

<div type='discussions-op-text'>

<sup>Originally posted by **melissavanbussel** March 17, 2024</sup>
### Description

Is it possible to add a favicon to a Quarto dashboard? I couldn't find any with favicons on the [examples page](https://quarto.org/docs/dashboards/examples/). For example, assume this is `dashboard.qmd`: 

```
---
title: "My Quarto Dashboard"
format: 
  dashboard:
    favicon: logo.png
    logo: logo.png
---
```

The logo shows up on the dashboard, but the favicon doesn't. 

Thank you in advance for your help!</div>
