### ISSUE TITLE
Sidebar max-height not taking into account header image

### ISSUE THREAD

**Issue by jazzabeanie** [quarto-dev/quarto-cli#9144]
### Bug description

When you have a sidebar and a header image, the size of the header image is not taken into account in the max-height css value. This means that the scroll bar appears off the bottom of the page.

### Steps to reproduce

Here is the _quarto.yml file:
```
project:
  type: website

website:
  title: "Sidebar scroll issue with header"
  search: true
  navbar:
    title: "Sidebar scroll issue with header"
  sidebar:
    style: "floating"
    search: true
    pinned: true
    collapse-level: 3
    contents:
      - section: "Products"
        contents:
          - section: "Hydrodynamic Model"
            contents:
              - section: "GBR1"
                contents:
                  - text: "Temperature, wind, salinity and current"
                  - text: "Temperature at 2.35m, 18m and 49m depth"
                  - text: "Current at 2.35m, 18m and 103m depth"
                  - text: "Salinity at 2.35m, 5.35m and 18m depth"
                  - text: "Fresh water exposure at 2.35m"
                  - text: "Current magnitude average at 2.35m"
                  - text: "Temperature range at 2.35m"
                  - text: "Flood plume extents for major rivers on GBR based on modelled river tracers"
              - section: "GBR4"
                contents:
                  - text: "Temperature, wind, salinity and current"
                  - text: "Temperature at 1.5m, 18m and 49m depth"
                  - text: "Current at 1.5m, 18m and 103m depth"
                  - text: "Temperature range at 1.5m"
                  - text: "Comparing eReefs (GBR4 temperature, current) to IMOS satellite temperature and ocean current"
          - section: "BioGeoChemical Model (4 km)"
            contents:
              - section: "Water chemistry"
                contents:
                  - text: "Total alkalinity, PH & Aragonite saturation state"
                  - text: "Dissolved inorganic nitrogen, nitrate & ammonia"
                  - text: "Dissolved oxygen & oxygen saturation percentage"
                  - text: "Dissolved Inorganic (Carbon, Nitrogen & Phosphorus)"
                  - text: "Dissolved Organic (Carbon, Nitrogen & Phosphorus)"
                  - text: "Particulate inorganic phosphorus & particulate inorganic"
              - section: "Water quality measures"
                contents:
                  - text: "Total chlorophyll, dissolved inorganic nitrogen & total suspended solids"
                  - text: "Total Suspended Solids, dust, mud carbonate & mud mineral"
                  - text: "Secchi depth, vertical attenuation at 490nm & light intensity above seagrass"
                  - text: "Simulated true colour"
              - section: "Macroalgae, seagrass and coral"
                contents:
                  - text: "Coral symbiont (nitrogen & chlorophyll) & coral host nitrogen"
                  - text: "Nitrogen (macroalgae, seagrass zostera, seagrass halophila & deep seagrass)"

format:
  html:
    toc: false
```

And here is the index.qmd file:

```
---
title: "Sidebar scroll issue with header"
format:
  html:
    include-in-header:
      - text: |
          <style>
          .large-image-header { height: 30vw; max-height: 50vh; }
          </style>
      - text: <div class="large-image-header" style="background-image:url('https://quarto.org/quarto.png')"></div>
---

Expand categories of the sidebar until the scrollbar appears. Then you will see that the scroll bar is larger than the page. The 
javascript does not consider the size of the image in the header when setting the max-height.
```

### Expected behavior

The scrollbar should fit the available space in the viewport.

### Actual behavior

The sidebar is bigger than the available space in the view port and it's not until you scroll down in the main page that you see the full sidebar.

### Your environment

- IDE: neovim
- OS: windows 11

### Quarto check output

```bash
Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /home/jjohnsto/Workspace/quarto-cli/package/dist/bin
```
