### ISSUE TITLE
`target` parameter not working on dropdown items on top navigation bar

### ISSUE THREAD

**Issue by AndreiBiziuk** [quarto-dev/quarto-cli#9153]
### Bug description

There is `target` option on navigation link which allows to open links in new window, but it's not working on dropdown menus.

### Steps to reproduce

`_quarto.yml`:
```
project:
  type: website

website:
  title: "Test"
  page-navigation: true
  navbar:
    left:
      - text: "External"
        href: "http://example.com"
        target: "_blank"

      - sidebar:drop

  sidebar:
    - id: drop
      title: "Dropdown"
      contents:.
        - text: "External not working"
          href: "http://example.com"
          target: "_blank"

format:
    html: default
```

`index.qmd`:
```
---
title: Test
---

# Header
```

run `quarto render`

open `_site/index.html`

Click on link "External" -- opens on new page

Click on link "External not working" -- opens on the same page

### Expected behavior

Option `target` working on dropdown menu items

### Actual behavior

Option `target` not working on dropdown menu items

### Your environment

Quarto 1.5.25

### Quarto check output

```
Quarto 1.5.25
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.25
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      Chromium: 869685
      TinyTeX: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.8
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: haskell, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/lib64/R
      LibPaths:
        - /home/andrei/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK

```

**Comment by AndreiBiziuk** [comment]
Maybe I'm doing dropdown menu wrong. If I make this menu with `menu` option like this:

```
...
      - text: "menu"
        menu:
        - text: "item 1"
          href: "http://example.com"
          target: "_blank"

        - text: "item 2"
          href: "http://example.com"
          target: "_blank
...
```

than `target` option working.

So maybe `sidebar` is intended only for internal links.

**Comment by mcanouil** [comment]
Could you share a small **self-contained "working" (reproducible)** example to work with, _i.e._, a complete Quarto document or a Git repository? Thanks.
Currently, the YAML you shared in either messages are not valid: indentation, dot misplaced, etc.

---

You can share a **self-contained "working" (reproducible)** Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).
See <https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines>.

If you have multiple files (and if it is **absolutely required** to have multiple files), please share as a Git repository.

<table>
<tr><th>R</th><th>Python</th></tr>
<tr><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: knitr
---

This is a reproducible Quarto document.

```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(1, 4, 9, 16, 25)

plot(x, y)
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td><td>

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
engine: jupyter
---

This is a reproducible Quarto document.

```{python}
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

plt.plot(x, y)
plt.show()
```

![An image](https://placehold.co/600x400.png)

The end.
````
`````

</td></tr>
</table>

Additionally and if not already given, please share the output of `quarto check` within a code blocks (*i.e.*, using three backticks ` ```txt `), see <https://quarto.org/bug-reports.html#check>.

**Comment by mcanouil** [comment]
FYI, I cannot reproduce:

```bash
quarto create project website issue-9153 Issue-9153
```

Then replace the `_quarto.yml` with:

```yaml
project:
  type: website

website:
  title: "Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    - title: "How-To"
      contents:
        - index.qmd
        - text: "External not working"
          href: "https://quarto.org"
          target: "_blank"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

**Comment by AndreiBiziuk** [comment]
Sorry, there was extra dot in my first listing. Try this one:

`_quarto.yml`:
```yaml
project:
  type: website

website:
  title: "Test"
  page-navigation: true
  navbar:
    left:
      - text: "External"
        href: "http://example.com"
        target: "_blank"

      - sidebar:drop

  sidebar:
    - id: drop
      title: "Dropdown"
      contents:
        - text: "External not working"
          href: "http://example.com"
          target: "_blank"

format:
    html: default
```

One link opens in new window, another -- don't

**Comment by mcanouil** [comment]
Still, your YAML is invalid.

<img width="520" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/531a7ae1-9441-4f8d-9236-640953573a08">

Please ensure, you have valid YAML and you follow the documentation.
Then, share the full steps to reproduce.
Take a look at what works and what I shared in https://github.com/quarto-dev/quarto-cli/issues/9153#issuecomment-2028886419

**Comment by dragonstyle** [comment]
That does not seem intentional.

**Comment by mcanouil** [comment]
Thanks, I opened a separate issue for this:
- #9242

@AndreiBiziuk I am going ahead and close this as I cannot reproduce the issue you are describing, using latest Quarto.
From the various invalid example you provided, I believe the issue is there and not in Quarto.
If you manage to provide a fully reproducible valid example, please do, we'll reopen.

**Comment by AndreiBiziuk** [comment]
Have you tryed to render my example exactly as I provided? Because You quote

```yaml
  - sidebar: drop
```

while in my example there is

```yaml
  - sidebar:drop
```

without space. It is intentional.

There is chapter in documentation about hybrid navigation: 
https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation
I've tryed to implement dropdown menu using this technic. 

Later I realize, that it is better to use `menu:`  like this:

```yaml
project:
  type: website

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - about.qmd

      - text: "Dropdown menu"
        menu:
          - text: "Link 1"
            href: "http://example.com"
            target: "_blank"
          - text: "Link 2"
            href: "http://example.com"
            target: "_blank"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

Strangely there is no clear example in documentation about implementing dropdown menu in navbar, except hybrid navigation.
