### ISSUE TITLE
reuse chunks: empty table caption gets created on a chunk that is not evaluated

### ISSUE THREAD

**Issue by eyayaw** [quarto-dev/quarto-cli#9203]
### Bug description

I am using knitr's [chunk reuse feature](https://bookdown.org/yihui/rmarkdown-cookbook/reuse-chunks.html#same-label) with the `eval: false` option and reusing the same chunk somewhere else with the same label. However, the table captions get created in the source chunk, perhaps due to the `tbl—` prefix, as quarto requires it for tables.

### Steps to reproduce

````yml
---
title: "Reusing chunks: tbl-caption created for a chunk that is not evaluated"
editor: visual
execute: 
  echo: true
engine: knitr
---


```{r}
#| label: tbl-head-mtcars
#| eval: false
#| output: asis
knitr::kable(head(mtcars))
```

```{r}
#| label: tbl-head-mtcars
#| tbl-cap: "Head of mtcars"
```
````

![image](https://github.com/quarto-dev/quarto-cli/assets/49317723/1dba9409-f307-4aea-9710-b35a707e8dbd)

### Your environment

- IDE: RStudio Version 2023.09.0+463 (2023.09.0+463)
- OS: macOS Sonoma 14.3.1

### Quarto check output
<details>
<summary>Expand</summary>
```bash
> quarto check
Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/eyayaw/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /opt/homebrew/Cellar/r/4.3.3/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.3/lib/R/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```
</details>
