### ISSUE TITLE
FR: support for multiple html-based output types - specifically `email` + `dashboard`

### ISSUE THREAD

**Issue by kmasiello** [quarto-dev/quarto-cli#9230]
A Quarto doc on Connect can support multiple output formats such as a html-email output and typst option, e.g., 

```
format:
  email:
    toc: true
    toc-location: left

  typst:
    toc: true
```

however, because `email` is html based, use of another html-based output (such as `dashboard`) is in conflict and will not render.

FR: enable both `dashboard` and `email` format types to be specified, or more generally, support multipe html-based outputs in a document.
