### ISSUE TITLE
Book project download multiple format, no icons

### ISSUE THREAD

**Issue by JulienGAMartin** [quarto-dev/quarto-cli#9269]
### Bug description

Hi
when allowing to download multiple format from the website of a book project, the bootstrap icons for the files to download are not showing up

### Steps to reproduce

I first created a basic book project with
```bash
quarto create project book bug-icons
```

Then you can edit the _quarto.yml by adding a download option and an epub format like here

```yaml
project:
  type: book

book:
  title: "bug-icons"
  author: "Norah Jones"
  date: "2024-04-04"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  downloads: [pdf, epub]

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub: default
```

### Expected behavior

I expect to see the icons for pdf and epub in the dropdown menu

![Screenshot from 2024-04-04 08-12-09](https://github.com/quarto-dev/quarto-cli/assets/10862457/97988325-5374-491c-8533-d9c4ea098a4a)

### Actual behavior

Icons are not showing up

![Screenshot from 2024-04-04 08-00-41](https://github.com/quarto-dev/quarto-cli/assets/10862457/c9305009-4c47-41d0-844f-c232aadf979e)

when looking at any of the produced ".html" files you can see in the menu section that the icons are badly names with "bi-" repeated twice.

![Screenshot from 2024-04-04 08-01-27](https://github.com/quarto-dev/quarto-cli/assets/10862457/87be7cb6-9f41-421a-afd2-4758e5b7dd38)

A simple hack for the moment is to search and replace in all .html, but certainly inconvenient and not expected

### Your environment

- IDE VS code 1.87.2
- quarto 1.4.549
- Ubuntu 22.04

### Quarto check output

Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/lib/R
      LibPaths:
        - /home/julien/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
