### ISSUE TITLE
Navbar current page highlight doesn't work when logo is in sidebar (hybrid navigation)

### ISSUE THREAD

**Issue by aaronkrusniak** [quarto-dev/quarto-cli#9277]
### Bug description

On website projects, Quarto sites that use a navbar will highlight the link of the page that is being currently viewed.  However, when hybrid navigation is used and a sidebar is introduced, and when that sidebar includes a logo, the navbar does not highlight the correct page and instead always seems to highlight the home page of the website.

Here's what a sample website using hybrid navigation looks like without a logo in the sidebar.  Note that the About page is visited, and the About header is highlighted in the navbar:

![results_without_logo](https://github.com/quarto-dev/quarto-cli/assets/107069665/49fe15de-2cdf-418c-8567-630d05aacf34)

Here's the same website, now with a logo in the sidebar.  Note that the About page is visited, but the Home header is highlighted in the navbar:

![results_with_logo](https://github.com/quarto-dev/quarto-cli/assets/107069665/fb4b86cc-ad4b-4891-bf50-e8dba1c361c8)

Here's the `_quarto.yml` used to generate this site.  The only difference between the two images is that line containing the sidebar logo has been commented out in the case of the first screenshot:

```yml
project:
  type: website

website:
  title: "website-testing"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: About this Site
        file: about.qmd


  sidebar:
    - title: Home
    # logo: seurat.jpg
      contents:
        - text: Home
          file: index.qmd

    - title: About this Site
      contents:
        - text: About
          file: about.qmd
        - text: More Info
          file: about2.qmd
        - text: Bibliography
          file: about3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

Thanks for looking into this, and thanks for making Quarto!

### Steps to reproduce

1. Clone the website project at [https://github.com/aaronkrusniak/hybridnav-logo-issue](https://github.com/aaronkrusniak/hybridnav-logo-issue).

2. Run `quarto preview` on the project and navigate to the About page.

3. Add/remove the `logo: seurat.jpg` code in the `_quarto.yml` file to see the changes.

### Expected behavior

When a logo is added to the sidebar, the navbar should preserve link highlighting on the currently-viewed page.

### Actual behavior

When a logo is added to the sidebar, the navbar highlights the Home page as though it were the currently-viewed page, regardless of which page is actually being viewed.

### Your environment

- IDE: RStudio 2023.09.01 Build 494
- Quarto: 1.4.550
- OS: Windows 10 Enterprise 19045.4170

### Quarto check output

```bash
$ quarto check
Quarto 1.4.550
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.550
      Path: C:\Users\442894\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\442894\AppData\Roaming\TinyTeX\bin\win32\
      Version: 2022

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.5 (Conda)
      Path: C:/Users/442894/anaconda3/python.exe
      Jupyter: 5.5.0
      Kernels: rt-modeling, python3

[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/Users/442894/AppData/Local/Programs/R/R-4.2.0
      LibPaths:
        - C:/Users/442894/AppData/Local/R/win-library/4.2
        - C:/Users/442894/AppData/Local/Programs/R/R-4.2.0/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
I tried your repository but cannot see any obvious difference.
Making very wide screenshots for what seems to be few pixels diff is not the best way to show the issue.

**Comment by mcanouil** [comment]
Weird, It seems my edit did not came through ...

The actual issue is that when a logo is set in the sidebar, the active link in the navbar is no longer updated, it stays on the first item.

A simpler/smaller reproducible example:
1. `quarto create project website issue-9277 Issue-9277`
2. Replace `_quarto.yml`:
````yaml
project:
  type: website

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    logo: https://quarto.org/quarto.png
    contents: 
      - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
````

**Comment by aaronkrusniak** [comment]
@mcanouil You're right, sorry, probably should have scaled those images more thoughtfully.

But yes, we're talking about the same issue here— just as you said, when a logo is set in the sidebar, the active link stops updating.  Appreciate you looking into it.

**Comment by fkohrt** [comment]
I'm also having this issue when no logo is in the sidebar, but some pages appear both in the navbar and the sidebar:

```yml
project:
  title: "Issue-9277"
  type: website

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - a.qmd
  sidebar:
    contents: 
      - index.qmd
      - a.qmd

format:
  html:
    theme: cosmo
    toc: true
```
