### ISSUE TITLE
SVG broken when rendering into a PDF

### ISSUE THREAD

**Issue by gskorokhod** [quarto-dev/quarto-cli#9282]
### Bug description

Text in an SVG image appears broken, and the image itself is weirdly cropped

Actual image: 

![image](https://github.com/quarto-dev/quarto-cli/assets/64529579/39b0c38e-802e-4d06-a360-3717187a9f46)

Image when rendered in the quarto PDF document:

![image](https://github.com/quarto-dev/quarto-cli/assets/64529579/a9599a25-74ef-47b8-b64e-5d5ba0db9aff)

### Steps to reproduce

1. Include the SVG in the markdown document: `![](bubbleup.svg)`
2. Run `quarto render`
3. The text in the SVG appears broken

The offending SVG file:

![bubbleup](https://github.com/quarto-dev/quarto-cli/assets/64529579/5ea9a44f-4978-45cb-b90e-e602a9c9a1fd)

Quarto config:

```yml
project:
  render: ["report.qmd"]
  output-dir: .


resource-path: ['.','figures']
bibliography: references.bib  
csl: ieee-with-url.csl

link-citations: true
links-as-notes: true # links as footnotes
number-sections: true

date-format: full

format:
  pdf:
    pdf-engine: pdflatex
    # use quarto's latexmk wrapper to auto install missing packages
    latex-auto-mk : true
    documentclass: scrartcl
    papersize: a4
    geometry: a4paper
    highlight-style: haddock
    header-includes: |
      \usepackage{charter}
    classoption: headings=standardclasses,headings=big
```

### Expected behavior

SVG should be rendered correctly as a figure inside the PDF document

### Actual behavior

SVG is rendered broken

### Your environment

- OS: Linux (Fedora Workstation 39)
- IDE: NVim v0.9.5
- Quarto v. 1.4.552 (installed from the release tarball)
- RStudio: 2023.12.1+402 (installed from official fedora repo)

### Quarto check output

```bash
Quarto 1.4.552
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.552
      Path: /opt/quarto-1.4.552/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.04
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/mayday/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /usr/bin/python3
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/lib64/R
      LibPaths:
        - /home/mayday/R/x86_64-redhat-linux-gnu-library/4.3
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```
