### ISSUE TITLE
logo-href does not work in sidebar of quarto book

### ISSUE THREAD

**Issue by pmoris** [quarto-dev/quarto-cli#9317]
### Bug description

https://github.com/quarto-dev/quarto-cli/issues/6779 mentions that the `logo-href` option has been added to the `sidebar` option of quarto books (previously only `navbar` was supported). However, this does not appear to be working in my minimal example, nor is it listed in the [documentation](https://quarto.org/docs/reference/projects/books.html) (the navbar option is).

### Steps to reproduce

Create a new quarto book using `quarto create`, then edit the `_quarto.yml` file:

```
project:
  type: book

book:
  title: "Quarto Book"
  author: "Norah Jones"
  date: "4/9/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  sidebar:
    logo: https://quarto.org/quarto.png
    logo-href: https://www.google.com
  

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
```

### Expected behavior

The logo should become a clickable link pointing to the `logo-href` URL in `_quarto.yml`.

### Actual behavior

the logo links back to the index page of the book.

### Your environment

```
WSL Ubuntu 22.04 running on Win 10
$ quarto --version
1.4.552
```

### Quarto check output

```
Quarto 1.4.552
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.552
      Path: /home/pmoris/opt/quarto/quarto-1.4.552/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.03.13
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/pmoris/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.14 (Conda)
      Path: /home/pmoris/miniforge3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

```
