### ISSUE TITLE
link-external-* marks relative paths

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#9354]
### Bug description

Given a two page website where the `index.qmd` page links to the `about.qmd` and both `link-external-*` settings are enabled, relative links are identified as external when the site is viewed from a different URL than the `website.site-url`.

```yaml
project:
  type: website

website:
  title: "external links"
  site-url: "https://quarto.org/"
  navbar:
    left:
      - text: "Home"
        href: "index.qmd"
      - text: "About"
        href: "about.qmd"

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
```

The `index.qmd` file:

```markdown
---
title: home
---

this is home. go see [about](about.qmd).
```

The `about.qmd` contents do not matter.

### Steps to reproduce

```bash
quarto preview
```

Rather than visiting `http://localhost:PORTNUM` to preview the site, visit `http://quarto.localtest.me:PORTNUM` or any other non-`localhost` host name that maps to your Quarto preview site.

### Expected behavior

Relative links should not be marked as external.

### Actual behavior

Relative links are marked as external and cause all links to open in new tabs.

<img width="264" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/3581b16f-8ba0-4cc9-ade7-bbc05bcc64ce">

### Quarto check output

```
Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /Users/aron/quarto/quarto-1.4.551-macos/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK
```
