### ISSUE TITLE
Ability to include html in the <head> element of a Dashboard

### ISSUE THREAD

**Issue by billgeo** [quarto-dev/quarto-cli#9445]
I am [trying to add Google Analytics to a Quarto Dashboard that we have deployed via Shinyapps.io](https://github.com/EECA-NZ/eeud-dashboard/pull/1/files).
The HTML format type has a series of [includes options](https://quarto.org/docs/reference/formats/html.html#includes). Would these be able to added to any format that outputs as HTML, such as dashboards?

## Description of issue

This code:
```
--- 
title: "Dashboard"
format: 
  dashboard:
    includes:
      in_header: google-analytics.html
server: shiny
---
```

Results in:
An index.html file created without `google-analytics.html` html added to the header. Ideally this html would be added to the header.
