### ISSUE TITLE
footer icons need HTML, which prevents extensions from resolving assets

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#9473]
### Bug description

An extension defining a custom project type wants to declare a shared footer and use some images as icons within that footer. For example:

````yaml
website:
  page-footer:
    right:
      - text: "<img src='/images/posit-logo-black-TM.svg' id='footer-right-posit-logo'>"
        href: "https://posit.co"
````

If the page footer supported an `image` attribute and took an image path, the in-extension path could be resolved without resorting to HTML.

````yaml
website:
  page-footer:
    right:
      - image: "/images/posit-logo-black-TM.svg"
        href: "https://posit.co"
````

My understanding is that Quarto does not attempt to resolve asset paths within text, but can do so for fields which are known to contain file references.

**Comment by mcanouil** [comment]
In the case of the addition of `image`, then `image-alt` and `image-title` should also be added.

**Comment by mcanouil** [comment]
FYI, markdown works in `text`.

```yaml
  page-footer:
    right:
      - text: "![](/images/posit-logo-black-TM.svg){#footer-right-posit-logo width=100px}"
        href: "https://posit.co"
```

Although, Quarto will raise a warning:

```sh
WARNING (src/resources/filters/./quarto-pre/parsefiguredivs.lua:517) Figure with invalid crossref category: footer-right-posit-logo
Won't be able to cross-reference this figure.
```
