### ISSUE TITLE
extension navbar merging needs order

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#9474]
### Bug description

When a custom project type defined by an extension configures navbar entries, a project which uses that extension cannot control the order that its own navbar entries are merged.

For example, when the extension has configuration like:

````yaml
contributes:
  project:
    project:
      type: website
    website:
      navbar:
        pinned: true
        right:
         - icon: "list"
           menu:
           - text: "docs.posit.co"
             href: "https://docs.posit.co"
           - text: "Posit Support"
             href: "https://support.posit.co/hc/en-us/"
````

A project using this extension might have additional navbar configuration like:

```yaml
website:
  navbar:
    right:
      - text: "Release Notes"
        url: "https://docs.posit.co/ide/news/"
```

When rendered, the navbar entries from the project-type are rendered to the left of the navbar entries from the project itself.

<img width="243" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/baa6bfa8-2c7c-45f3-ace5-e253121041cc">

Custom project types and projects should have some way of determining the final order for navbar items.

This same problem likely happens when other types of list-like configurations are merged, like page-footer entries.
