### ISSUE TITLE
revealjs theming broken when `theme` specified at top-level of frontmatter

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#9548]
good:

```yml
format: 
  revealjs:
    theme: beige
```

bad:

```yml
format: revealjs
theme: beige
```
