### ISSUE TITLE
Book Crossrefs for chapters or sections not working when adding parts and appendices

### ISSUE THREAD

**Issue by luifrancgom** [quarto-dev/quarto-cli#9556]
### Bug description

Adding parts and appendices to a Quarto book can cause cross references related to sections or chapters to stop working.

## GitHub Repo 

https://github.com/luifrancgom/cross_reference_bug_quarto

## `_quarto.yml`

```yml
project:
  type: book

book:
  title: "test_book"
  author: "Norah Jones"
  date: "5/2/2024"
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
      - summary.qmd
    - references.qmd
  appendices: 
    - appendix1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
```

## `intro.qmd`

````qmd

# Introduction {#sec-introduction}

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

```{r}
1 + 1
```
````

## ` summary.qmd`

````qmd

# Summary

In summary, this book has no content whatsoever.

@sec-introduction

```{r}
1 + 1
```
````

## ` appendix1.qmd`

```qmd
# Appendix 1

@sec-introduction

```

### Expected behavior

Visualize the cross references related to `intro.qmd`

## Cross reference in ` appendix1.qmd`

![Screenshot 2024-05-02 030449](https://github.com/quarto-dev/quarto-cli/assets/50002526/c102a765-7d09-44ea-b1a1-404f610b3ac6)

## Cross reference in ` summary.qmd`

![Screenshot 2024-05-02 030511](https://github.com/quarto-dev/quarto-cli/assets/50002526/65918171-26f0-47cb-984e-1e08d59dc54b)

### Your environment

- IDE: RStudio 2024.04.0+735 "Chocolate Cosmos" 
- OS: Windows 11 Pro

### Quarto check output

```bash
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.13: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.5.31
      Path: C:\Users\Usuario\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: v2024.01
      Chromium: 869685

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\Usuario\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2023

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.12.1
      Path: C:/Python312/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.3
      Path: C:/PROGRA~1/R/R-43~1.3
      LibPaths:
        - C:/Users/Usuario/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.3/library
      knitr: 1.45
      rmarkdown: 2.26

[>] Checking Knitr engine render......OK
```
