### ISSUE TITLE
`number-sections:true` breaks pdf output

### ISSUE THREAD

**Issue by sknauff** [quarto-dev/quarto-cli#956]
Setting `number-sections:true` with pdf as output format breaks the output.

For example:
```
---
title: "My document"
format:
  pdf:
    toc: true
    number-sections: false
---

# Beginning

# Middle

# End
```

The example above works as expected, but as soon as `number-sections` is set to `true`, the created PDF has "End" as Title, and only a single headline with "Table of contents" as content. I tried out several of the previous versions, none of them produced the expected outcome. 

With `number-sections:true`, I checked with `keep-tex: true` the `.tex`-file, which had the following as document body:
```
\begin{document}
\maketitle
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[boxrule=0pt, frame hidden, sharp corners, interior hidden, borderline west={3pt}{0pt}{shadecolor}, enhanced, breakable]}{\end{tcolorbox}}\fi

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}




\end{document}
```

I guess this is a bug in quarto?

**Comment by sknauff** [comment]
If anyone else has the same issue, a workaround for me is to use:
```
format: 
  pdf:
    number-sections: false
    header-includes: |
      \setcounter{secnumdepth}{3}
```
