### ISSUE TITLE
Conditional content doesn't apply to chapter headings in books

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#9630]
I have a book with just an `index.qmd` and the following `_quarto.yml`.

```yaml
project:
  type: book

book:
  title: "test-book"
  chapters:
    - index.qmd

format:
  html: default
  pdf: default
```

The contents of `index.qmd` is as follows:

```markdown
::: {.content-hidden unless-format="html"}
# This header should not appear in PDF {.unnumbered}
:::

This page should not have a header when rendered to PDF.
```

I would expect the header to appear in the HTML output but not the PDF output, however it shows up in both.

<img width="450" alt="Screenshot 2024-05-09 at 8 19 11 AM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/88eb3726-2068-4a3e-9d83-eb626d17bb4d">
<img width="450" alt="Screenshot 2024-05-09 at 8 19 40 AM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/93a28edb-3687-4a0b-949e-bb2ecf875219">

Conditional content for headers works as expected when in a single document, but not in a book.

<img width="1000" alt="Screenshot 2024-05-09 at 8 22 26 AM" src="https://github.com/quarto-dev/quarto-cli/assets/5965649/4d4fee15-e505-46bd-96ab-d0ddd3cbf83a">

I'm using Quarto `1.5.33`.

**Comment by mcanouil** [comment]
Here it's not any headers, it's the title of the chapter.

What is it that you are trying to do? The whole picture might help, as it's similar to what another user tried to do when in fact he/she wanted to have conditional chapters (which actually falls under Project Profile).

**Comment by mine-cetinkaya-rundel** [comment]
Yes, it is what I'm trying. In my particular case this title is .unlisted and .unnumbered but there's other content on the page / chapter I'd like visible in the PDF.

**Comment by mcanouil** [comment]
I am not sure to follow.
Title (or first heading) is not an optional component of Book project.
A document/chapter should have a title or it's a content you include in the previous chapter.
As far as I can tell, everything here is an expected behaviour.

The following would work, because Quarto finds a title and does not have to promote the first heading.

```qmd
---
title: "This is a chapter"
---

::: {.content-hidden unless-format="html"}
# This header should not appear in PDF {.unnumbered}
:::

This page should not have a header when rendered to PDF.
```

Maybe you can share a more complex example that is closer to your use case.


A project profile would offer better results I think.

- `_quarto.yml`

````yml
project:
  type: book

book:
  title: "test-book"
  chapters:
    - index.qmd

format:
  html: default
```

- `_quarto-pdf.yml`

````yml
book:
  chapters:
    - index-pdf.qmd

format:
  pdf: default
```
