### ISSUE TITLE
New Rendering Error

### ISSUE THREAD

**Issue by zachcp** [quarto-dev/quarto-cli#979]
Hi Team Quarto,

I've been using the Quarto engine to generate a website and blog posts for months but just encountered the following error for the first time when attempting to render:

```
ERROR: TypeError: Cannot read properties of undefined (reading 'innerHTML')
```

This is triggered by the `blog.qmd` which has the following content:

```
---
title: "Blog"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
---
```

I was able to replicate this issue on both `0.9.449` and  `0.9.446` but going back to `0.9.418` works fine. 

zach cp
