### ISSUE TITLE
`background-image` not embedded when `self-contained: true`

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#980]
it appears that the `background-image` is never embedded in the `html` file for some reason.
If the background image is set with `{background-image="assets/background.jpg"}`, it is embedded.

The following setup in the yaml, will result in slides without background.  
While, it's working fine when the generated `html` is at the same level as the `qmd` file it comes from.

```
format:
  revealjs:
    self-contained: true
    background-image: background.jpg
    output-file: docs/index.html
```

See https://github.com/mcanouil/quarto-issues/tree/main/quarto-cli%23980

Version: `0.9.449`
Originally from: quarto-dev/quarto-cli#951
