### ISSUE TITLE
Add a line border to show hierarchy better in main navigation

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#9826]
A border might help:

```css
.sidebar-menu-container .sidebar-section {
  border-left: 1px solid lightgrey;
}
```

![image](https://github.com/quarto-dev/quarto-cli/assets/6520659/304f5f02-6507-41ee-afc4-9816d0fb204b)

_Originally posted by @jimjam-slam in https://github.com/quarto-dev/quarto-cli/discussions/9777#discussioncomment-9576243_

------

This would be like we do in TOC right sidebar
