### ISSUE TITLE
id-less typst figures get numbered inside other figures

### ISSUE THREAD

**Issue by gordonwoodhull** [quarto-dev/quarto-cli#9857]
And wrongness of numbering ensues.

<img width="811" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1366709/3bb324f3-b1dc-4c26-9ce1-f0ed89bce782">

Same example as #9854 

````
---
title: "Typst messy subnumbering"
format:
  typst:
    keep-typ: true
---


::: {#fig-panel2 layout-ncol=2}

![Placeholder](pl200.png)

![Placeholder](pl200.png)

Panels

:::
````

1. There should not be supplements and numbering for figures without ids
2. However, Typst has defined a figure as something that is cross-referenceable, so
3. It gets automatically upgraded on rendering
4. But it wasn't a `FloatRefTarget` so `has_subfloats` is false.

Note that plain

```qmd
![Placeholder](pl200.png)
```

by itself also gets printed as a figure with supplement and numbering.

We seem to be stuck with that for now, unless we wanted to not use Typst figure for these cases, or number them in a void context and strip the text out in post, yuck.

So it seems we should detect this case, and transform these captioned, no-id figures as subfloats so they get lettered appropriately instead of numbered inappropriately.

**Comment by cscheid** [comment]
> by itself also gets printed as a figure with supplement and numbering.
> 
> We seem to be stuck with that for now, unless we wanted to not use Typst figure for these cases, or number them in a void context and strip the text out in post, yuck.

Agreed. Just to reiterate, this is the same situation as in LaTeX. An image with a caption and without a `fig-` label still becomes a default float (`Figure`):


````
---
format: pdf
---

Hi.

![A caption]({{< placeholder >}})

Hi.
````

<img width="512" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/a068f3a1-a717-4756-b882-e59599a4e77a">

> So it seems we should detect this case, and transform these captioned, no-id figures as subfloats so they get lettered appropriately instead of numbered inappropriately.

Exactly. Ideally we'd do the same thing in LaTeX, but I just realized that the following causes a LaTeX bug:

````
::: {#fig-1}

![An inner caption]({{< placeholder >}})

![An inner caption]({{< placeholder >}})

An outer caption.

:::
````

This causes the dreaded `not in outer par mode` case. I think it happens because we have an outer FloatRefTarget with inner pandoc.Figure nodes, per our filter trace:

````yml
  - t: "Para"
    content: "Hi."
  - customAST: true
    type: "Figure"
    identifier: "fig-1"
    t: "FloatRefTarget"
    attributes: []
    classes: []
    scaffold:
      - t: "Div"
        attr: "('', [], ['__quarto_custom_scaffold,true'])"
        content:
          - t: "Figure"
            attr: "('', [], [])"
            content:
              - t: "Plain"
                content:
                  - t: "Image"
                    attr: "('', [], [])"
                    caption: "An inner caption"
                    src: "data:image/png;base64,..."
                    title: ""
            caption:
              - null
              -
                - t: "Plain"
                  c:
                    - t: "Str"
                      c: "An"
                    - t: "Space"
                    - t: "Str"
                      c: "inner"
                    - t: "Space"
                    - t: "Str"
                      c: "caption"
          - t: "Figure"
            attr: "('', [], [])"
            content:
              - t: "Plain"
                content:
                  - t: "Image"
                    attr: "('', [], [])"
                    caption: "An inner caption"
                    src: "data:image/png;base64,..."
                    title: ""
            caption:
              - null
              -
                - t: "Plain"
                  c:
                    - t: "Str"
                      c: "An"
                    - t: "Space"
                    - t: "Str"
                      c: "inner"
                    - t: "Space"
                    - t: "Str"
                      c: "caption"
      - t: "Div"
        attr: "('', [], ['__quarto_custom_scaffold,true'])"
        content:
          - t: "Plain"
            content: "An outer caption."
````
