### ISSUE TITLE
extensions - project contributions don't take pre- and post-render scripts into account

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#9889]
The following should work:

## `extension.yml`

````
title: Pre-Render test
author: cscheid
version: 1.0.0
quarto-required: ">=1.2.0"
contributes:
  project:
    project:
      pre-render:
        - pre-render.ts
````

Specifically, extensions should be able to contribute `pre-render` and `post-render` script lists that get executed as if these had been declared at the `_quarto.yml` project configuration.
