### ISSUE TITLE
Search cannot be disable in navbar

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#9905]
It's not possible to disable the search button/bar when in its default location, namely `navbar`.

The search will still appear on the right of the navbar.

```yaml
website:
  search: 
    location: navbar
  navbar:
    search: false
```

As a comparison, the same for sidebar works as expected:

```yaml
website:
  search: 
    location: sidebar
  sidebar:
    search: false
```

_Originally posted by @mcanouil in https://github.com/quarto-dev/quarto-cli/discussions/9836#discussioncomment-9692676_

**Comment by cderv** [comment]
So the aim is to control the search box inclusion at the navbar or sidebar level and not at the top level `website.search` ? 

This is the issue here, is this correct understanding ?

**Comment by mcanouil** [comment]
Possibly, at least the documentation implies that it is possible. If you cannot disable at the `navbar` level, then it's odd to have `search: true` and the below description in the documentation.

> Include a search box (true or false). Note that if there is already a search box on the top navigation bar it won’t be displayed on the sidebar.

Source: https://quarto.org/docs/websites/website-navigation.html#side-navigation

The main issue to me is that if you want to disable search, from the documentation, it is very likely, a user will try:

```yaml
website:
  navbar:
    search: false
```
