### ISSUE TITLE
Footer text vertical alignment not centered

### ISSUE THREAD

**Issue by ravicodelabs** [quarto-dev/quarto-cli#9938]
### Bug description

Not all of the footer text is centered vertically. In particular, the horizontally centered footer text (using `footer:center:` in the yaml) seems to be raised in the footer. 

### Steps to reproduce

Create a Quarto website with a footer like below:

```yaml
  page-footer:
    border: true
    left: "Left Footer"
    center: "Center Footer"
    right:
    - text: "Right Footer 1"
    - text: "Right Footer 2"
```

The center footer is showing up above the vertical center position. 

### Quarto version

Quarto v1.4.555

Note: the issue was not present in Quarto v1.3.298..

**Comment by cscheid** [comment]
I can't seem to repro this:

<img width="1003" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/49bc1979-f1c5-46c4-9678-82c736afc3ab">

Can you provide:

- a screenshot of what you're seeing, 
- a link to a repository that we can use to recreate your example

**Comment by ravicodelabs** [comment]
Thanks for the quick response! Quick correction: all of the footer text seemed to be raised by default (e.g. not just the horizontally center text), though the temp fix we used for the center text was slightly different. 

Here is a temp repo for reproducing the issue: https://github.com/datascijedi/temp--quarto-footer-issue. You can uncomment the css in `styles.css` to see the temporary fix we are using. 

**Screenshot of issue:**

![Footer - Not Verically Centered](https://github.com/quarto-dev/quarto-cli/assets/87270246/4acced52-87b4-4b11-bee1-4e256790b152)

**Screenshot of issue addressed with temp fix:**

![Footer - Vertically Centered](https://github.com/quarto-dev/quarto-cli/assets/87270246/867a0e62-8fa4-400f-add3-0a40d3008278)

**Comment by mcanouil** [comment]
Isn't it the default Bootstrap for `nav-footer`?

```css
.nav-footer {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: baseline;
    text-align: center;
    padding-top: .5rem;
    padding-bottom: .5rem;
    background-color: #333
}
```

Changing. `align-items: baseline` to `align-items: center` should do it.

**Comment by mcanouil** [comment]
Regarding the other suggested change:

```css
.nav-footer-center {
    min-height: 0px;
} 
```

I don't think that is the right fix here. See the original CSS:

- https://github.com/quarto-dev/quarto-cli/blob/f1ab12ba73d76f5a43e9f1585e691bf552cab006/src/resources/projects/website/navigation/quarto-nav.scss#L905-L919

**Comment by cscheid** [comment]
Is this a `Future` bug or is it even a bug to begin with?

**Comment by mcanouil** [comment]
To me, it's more of a design decision.

**Comment by ravicodelabs** [comment]
Hi - thanks all for looking into this one! A few more details:

## What Changed

After taking a closer look, it looks like the below difference between the rendered bootstrap from different Quarto versions is what seems to be have changed the footer vertical alignment. In particular, in v1.3.299 the `padding` top/bottom values seem to be set explicitly to `.5rem`, whereas in v1.4.555 it relies on bootstrap variables being set. 

Quarto 1.3.299 - rendered bootstrap.min.css:

```css
.nav-link {
    display: block;
    padding: .5rem 2rem;
    color: #18bc9c;
    text-decoration: none;
    -webkit-text-decoration: none;
    -moz-text-decoration: none;
    -ms-text-decoration: none;
    -o-text-decoration: none;
    transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out;
}
```
Quarto v1.4.555 - rendered bootstrap.min.css:

```css
.nav-link {
    display: block;
    padding: var(--bs-nav-link-padding-y) var(--bs-nav-link-padding-x);
    font-size: var(--bs-nav-link-font-size);
    font-weight: var(--bs-nav-link-font-weight);
    color: var(--bs-nav-link-color);
    text-decoration: none;
    -webkit-text-decoration: none;
    -moz-text-decoration: none;
    -ms-text-decoration: none;
    -o-text-decoration: none;
    background: none;
    border: 0;
    transition: color .15s ease-in-out, background-color .15s ease-in-out, border-color .15s ease-in-out;
}
```

Furthermore, the value for the bootstrap variable `--bs-nav-link-padding-y` is set in two places in bootstrap as shown below, but neither sets it on `nav-link`, so perhaps it doesn't get applied in the newer version of Quarto within the context of the footer. 

source: https://github.com/twbs/bootstrap/blob/v5.3.1/dist/css/bootstrap.css

```css
.navbar-nav {
  --bs-nav-link-padding-x: 0;
  --bs-nav-link-padding-y: 0.5rem;
  --bs-nav-link-font-weight: ;
  --bs-nav-link-color: var(--bs-navbar-color);
  --bs-nav-link-hover-color: var(--bs-navbar-hover-color);
  --bs-nav-link-disabled-color: var(--bs-navbar-disabled-color);
  display: flex;
  flex-direction: column;
  padding-left: 0;
  margin-bottom: 0;
  list-style: none;
}

.nav {
  --bs-nav-link-padding-x: 1rem;
  --bs-nav-link-padding-y: 0.5rem;
  --bs-nav-link-font-weight: ;
  --bs-nav-link-color: var(--bs-link-color);
  --bs-nav-link-hover-color: var(--bs-link-hover-color);
  --bs-nav-link-disabled-color: var(--bs-secondary-color);
  display: flex;
  flex-wrap: wrap;
  padding-left: 0;
  margin-bottom: 0;
  list-style: none;
}
```

## Fixes

The CSS I provided in my example was not really meant to be a suggestion on how to fix it, it was just informational, sorry for any confusion there. That being said, it does do the job, at least for our particular website. And, setting `min-height: unset` also works, which is probably cleaner than `min-height: 0px`. 

On the other hand, with the change possibly identified, I suppose another "fix" might be to go back to using explicit values for the padding, in particular `0.5rem` for top/bottom. Doing this fixes the vertical alignment as well, without changing flex's `align-items` or messing with the `min-height`. Though it doesn't seem as intuitive as `align-items: center`.
