### ISSUE TITLE
Improve image layout in hover effect for cross-reference

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#9950]
The below CSS rule fixes the "white space" left in the hover container beside the image.
It needs further testing to ensure it does not lead to spurious display.

```css
.tippy-content img {
    width: 100% !important;
}
```

_Originally posted by @apcamargo in https://github.com/quarto-dev/quarto-cli/discussions/9888#discussioncomment-9682762_
