### ISSUE TITLE
Wish: Changing SCSS variables for light/dark themes only

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#996]
Similar to #990, it would be great if one could change top-level colors like `color-bg` for only light or dark theme respectively.
Often enough the default colors (or the adapted ones) don't look great in one theme setting.

E.g. something along the lines of

```yml
format:
  html:
    theme:
      light: 
        css: [default, custom.scss]
        code-color: "blue" # just an example
      dark: 
        css: [custom-dark.scss, slate]
        code-color: "red" # just an example
```

Currently these must be changed within a custom `.scss` file though there changes often must make use of the `!important` option to get honored and by this do more than they should do.
